### ISSUE TITLE
Error while bulding torch xla

### ISSUE THREAD

**Issue by BadrYoubiIdrissi** [pytorch/xla#1015]
I'm trying to build from source and pytorch generated wheels properly but when it comes to torch_xla I have the following error:

```ERROR: Skipping '//tensorflow/compiler/xla/xla_client:libxla_computation_client.so': error loading package 'tensorflow/compiler/xla/xla_client': Label '//tensorflow/core:platform/default/build_config.bzl' crosses boundary of subpackage 'tensorflow/core/platform' (perhaps you meant to put the colon here: '//tensorflow/core/platform:default/build_config.bzl'?)
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/compiler/xla/xla_client': Label '//tensorflow/core:platform/default/build_config.bzl' crosses boundary of subpackage 'tensorflow/core/platform' (perhaps you meant to put the colon here: '//tensorflow/core/platform:default/build_config.bzl'?)
INFO: Elapsed time: 0.106s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/compiler/xla/xla_client
Failed to run '['/home/badrdr/Dev/pytorch/xla/build_torch_xla_libs.sh', 'install']'
```

I executed the commands under Buidling with script in the README.

**Comment by dlibenzi** [comment]
I remember to have seen that error time ago, but I do not remember the cause 😞 
Is this your first build of pytorch/xla?
I'd try to run `python setup.py clean` and also remove the Bazel cache `rm -rf $HOME/.cache/bazel`.
Also, which Bazel version are you using (`bazel version`)?
We use 0.24.1 for our builds:

https://github.com/pytorch/xla/blob/a8d9bc1b3f387fb4afbf10a13c77eb8e077e08ba/scripts/build_torch_wheels.sh#L10

**Comment by BadrYoubiIdrissi** [comment]
Thank you for the suggestion! I'll try it out as soon as i can. I'll keep you posted. I didn't have bazel so it installed 0.24.1 ! And yes this is my first pytorch/xla build.
