### ISSUE TITLE
Tests don't work 

### ISSUE THREAD

**Issue by tetelias** [pytorch/xla#1024]
Probably an easy to fix issue, but they stop on "from common_utils import TestCase, run_tests", since there's no "common_utils.py".

**Comment by dlibenzi** [comment]
What is your environment?
Are you using nightly builds? Dockers? Cloud TPU VM images?

**Comment by ailzhang** [comment]
@tetelias These files are in `pytorch/pytorch` repo. 
To run the test suite, you'll need to put `xla` folder under `pytorch`:
```
pytorch/
  torch/
  ... # other folders under pytorch
  xla/
    test/ # xla test
```
We might improve this logic in the future, but since tests are not included in shipped binary, it's lower priority I think.

**Comment by tetelias** [comment]
Sorry for delayed answer. Yes, my mistake: I tried to start from downloaded repo alone.
