### ISSUE TITLE
Mean accuracy with multiprocess

### ISSUE THREAD

**Issue by zcain117** [pytorch/xla#1052]
## 🐛 Bug

Right now, we are mistakenly reporting the per-device accuracy as the mean accuracy:
https://github.com/pytorch/xla/blob/master/test/test_train_mp_imagenet.py#L212

This results in the user seeing something like this:

> [xla:0/0] Accuracy=26.85%
> [xla:0/1] Accuracy=26.90%
> [xla:0/5] Accuracy=27.19%
> [xla:0/2] Accuracy=27.39%
> [xla:0/6] Accuracy=27.17%
> [xla:0/3] Accuracy=27.43%
> Epoch: 3, Mean Accuracy: 26.85%
> [xla:0/7] Accuracy=27.65%
> Epoch: 3, Mean Accuracy: 27.19%
> Epoch: 3, Mean Accuracy: 26.90%
> Epoch: 3, Mean Accuracy: 27.39%
> Epoch: 3, Mean Accuracy: 27.17%
> Epoch: 3, Mean Accuracy: 27.43%
> Epoch: 3, Mean Accuracy: 27.65%
> [xla:0/4] Accuracy=26.90%
> Epoch: 3, Mean Accuracy: 26.90%

@dlibenzi : In the multiprocess case, is there any way we can compute mean accuracy per epoch across all devices?

**Comment by dlibenzi** [comment]
We do feed the whole test dataset to each device, so there is no "mean" notion.
Though accuracies should be the same...

**Comment by zcain117** [comment]
Closing for now since the issue is inaccurate. We correctly compute the accuracy of the entire test set in each process, but there may or may not be a discrepancy between processes. I'll look more into that and file an issue if something looks off
