### ISSUE TITLE
remove sys.path code in test

### ISSUE THREAD

**Issue by ailzhang** [pytorch/xla#1075]
Currently our test imports a few things from pytorch tests. Which forces us to have manipulate `sys.path` to get it work properly. 

We could probably 
- remove dependency 
- set up test to be run without changing `sys.path`.

**Comment by dlibenzi** [comment]
For this, either of:
 1. PyTorch installs common_utils somewhere we can pick it up
 2. We clone and trim the pytorch one and carry in our folder

Either is fine for me.

**Comment by ailzhang** [comment]
This is completed by @dlibenzi , thanks!
