### ISSUE TITLE
Make RegistrationDeclarations.h contain namespace

### ISSUE THREAD

**Issue by ailzhang** [pytorch/xla#1139]

**Comment by ailzhang** [comment]
https://github.com/pytorch/xla/pull/1106

**Comment by mruberry** [comment]
@ailzhang Can we close this now?

**Comment by ailzhang** [comment]
Yea I've checked that in PyTorch we do register those ops with `at::` namespace instead of c10. Our usage of `at::` is fine unless PyTorch removes `at::MemoryFormat` and change the way aten ops are registered. We can safely close this.  :D

**Comment by ailzhang** [comment]
For future reference: the file I looked at was `/private/home/ailzhang/pytorch/build/aten/src/ATen/Functions.h` and searched for `clone` as example.
