### ISSUE TITLE
Clairification on the definition of a single XLA device

### ISSUE THREAD

**Issue by bkkaggle** [pytorch/xla#1181]
## ❓ Questions and Help

Hi,

Does training on a single XLA device, like in the example [here](https://github.com/pytorch/xla/blob/master/API_GUIDE.md#running-on-a-single-xla-device), mean that your model will be trained on one core of a cloud TPU that has 8 cores or on all 8 cores of the TPU? Does this mean that you have to follow the [multiprocessing](https://github.com/pytorch/xla/blob/master/API_GUIDE.md#running-on-multiple-xla-devices-with-multiprocessing) or [multithreading](https://github.com/pytorch/xla/blob/master/API_GUIDE.md#running-on-multiple-xla-devices-with-multithreading) examples to train on all cores of a TPU?

Also, does the TPU device printed out from
```
>>> print(xm.xla_device())
device(type='xla', index=1)
```
refer to the cloud TPU as a whole or to a single core of the TPU?

Thanks!

**Comment by asuhan** [comment]
A single XLA device is a single TPU core. Yes, you need to follow the multiprocessing / multithreading examples to use all the cores on a TPU.

The printed device also refers to a single core of the TPU.

**Comment by bkkaggle** [comment]
Thanks!

Should I add some information on the distinction between single and multi device training to API_GUIDE.md? I can send in a pull request with the changes for review.

**Comment by dlibenzi** [comment]
Is there really confusion about it, to be clarified?

**Comment by dlibenzi** [comment]
Maybe this can help (pardon us ... we still have a lot of TF-specific mentions in our docs)?

https://cloud.google.com/tpu/docs/system-architecture

**Comment by bkkaggle** [comment]
Thanks, this article is really helpful
