### ISSUE TITLE
Performance differences between multiprocessing and multithreading

### ISSUE THREAD

**Issue by bkkaggle** [pytorch/xla#1182]
## ❓ Questions and Help

It says in your [api guide](https://github.com/pytorch/xla/blob/master/API_GUIDE.md#running-on-multiple-xla-devices-with-multithreading) that

> Running on multiple XLA devices using processes (see above) is preferred to using threads

Is there a reason (decreased performance?) for this, or is preferring multiprocessing more of a convention?

**Comment by dlibenzi** [comment]
With `DataParallel` you have N (8) threads executing Python's code, which is serialized by the process GIL.
Even when PyTorch falls into C++ code and releases the GIL, the GIL implementation logic, and the fact that the time spent in XLA code is very small, prevent the Linux scheduler to properly parallelize the load.
So it is almost as running on a single CPU core.
With multi-processing the model's Python code will not contend the GIL with other threads, and hence they will be able to use different CPU cores.
So there is a performance advantage on using multi-processing.

**Comment by bkkaggle** [comment]
Thanks, closing
