### ISSUE TITLE
Parallel loader returns batches as (1, [img_tensor, label_tensor])

### ISSUE THREAD

**Issue by bkkaggle** [pytorch/xla#1187]
## ❓ Questions and Help

Hi,

I'm working on reimplementing the mnist multiprocessing example script in colab and ran into this problem:

When iterating over the `parallel_loader`, batches returned from it are returning tuples of (1, [img_tensor, label_tensor]) instead of just the batch tensors, [img_tensor, label_tensor]. The unusual thing is that it looks like the parallel loader is working normally in your original [script](https://github.com/pytorch/xla/blob/master/test/test_train_mp_mnist.py#L111), returning only the tensors in the batch itself, but it's not working like that when I tried it out in colab.

I made a colab notebook that shows this error occuring [here](https://colab.research.google.com/drive/1h2N7CBicp02mkQLLn1vdOO0KvJ1FqSFq)

Could this be a problem with colab itself, since it uses TF 1.15 and a prebuilt `pytorch_xla` wheel?

Thanks

**Comment by dlibenzi** [comment]
We have reverted that behavior in https://github.com/pytorch/xla/pull/1179
Before the ParallelLoader had an "enumerate like" behavior.
Once we cherry-pick that change into the official release build, we will update the Colabs.

**Comment by bkkaggle** [comment]
Thanks, is there any way to manually install pytorch_xla from source on colab? 

Would just cloning the repository and running [this](https://github.com/pytorch/xla/blob/master/CONTRIBUTING.md#building-with-script) script work?

**Comment by dlibenzi** [comment]
Maybe I am confused, but can't you just do what we did before that change?
```Python
for batchno, (sample, target) in loader:
  ...
```

**Comment by bkkaggle** [comment]
Yes it works, but I wasn't sure at the time that parallel_loader worked like enumerate()

Thanks, closing

**Comment by jysohn23** [comment]
@bkkaggle Just an FYI: The colabs have been updated to also remove the "enumerate like" behavior of `ParallelLoader` and instead we do `enumerate(loader)` just like a data loader.
