### ISSUE TITLE
Error with pytorch/xla/test/run_tests.sh

### ISSUE THREAD

**Issue by zcain117** [pytorch/xla#1189]
## 🐛 Bug

Starting around Oct 8, `test_comparison_ops_with_type_promotion` started failing on nightly docker:
https://github.com/pytorch/pytorch/blob/master/test/test_type_promotion.py#L234

## To Reproduce

1. Create new PyTorch VM from Google Cloud
2. Create new TPU with pytorch-nightly software type
3. Run `docker run --shm-size 16 -e XRT_TPU_CONFIG="tpu_worker;0;10.0.101.2:8470" gcr.io/tpu-pytorch/xla:nightly bash pytorch/xla/test/run_tests.sh;`

Result:

======================================================================
FAIL: test_comparison_ops_with_type_promotion (__main__.TestTypePromotion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/pytorch/xla/test/test_operations.py", line 1605, in test_comparison_ops_with_type_promotion
    self.assertEqual(out_res, expected)
  File "/pytorch/xla/test/test_operations.py", line 335, in assertEqual
    assertTensorsEqual(x, y)
  File "/pytorch/xla/test/test_operations.py", line 279, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError: tensor(1, device='xla:1', dtype=torch.int32) not less than or equal to 1e-05 : 

----------------------------------------------------------------------
Ran 93 tests in 70.937s

FAILED (failures=1)

**Comment by zcain117** [comment]
Interesting that this test passes in circleci: https://circleci.com/gh/pytorch/xla/4709?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by dlibenzi** [comment]
Thanks @zcain117 ... I am looking into this.
It also passes if you only run that test alone.

**Comment by zcain117** [comment]
Another way of running the test:

> export XRT_TPU_CONFIG="tpu_worker;0;10.0.101.2:8470"
> conda activate torch-xla-nightly
> bash test/run_tests.sh

This version also fails with the same error as Docker

**Comment by dlibenzi** [comment]
Yes, it fails on TPU only.

**Comment by dlibenzi** [comment]
Fixed by https://github.com/pytorch/xla/pull/1214
