### ISSUE TITLE
PerDeviceLoader and ParallelLoader missing key attributes and methods

### ISSUE THREAD

**Issue by tmabraham** [pytorch/xla#1191]
PerDeviceLoader interestingly do not subclass DataLoader. This leads to some missing attributes and methods when treating it as a DataLoader. For example, it is missing a dataset attribute and a length method. Could these attributes and methods and related attributes and methods be added?
Some properties might also need to be added to ParallelLoader
Of course, since these are parallel dataloaders that are only sending portions of the dataset to the different TPUs, special care needs to be taken.

**Comment by dlibenzi** [comment]
The `PerDeviceLoader` is not a `DataLoader` in PyTorch terms.
The latter takes a `Dataset` definition and provides iterator capability over its data.
The `ParallelLoader` is a `DataLoader` wrapper.
We could forward some methods to the wrapped `DataLoader` but I am not sure whether this results in correct behavior from a PyTorch API semantics.

**Comment by tmabraham** [comment]
@dlibenzi Interesting, I did not realize that. I had assumed because PerDeviceLoader has an `__iter__` function, which is found in DataLoader objects. 

Looking particularly at the PerDeviceLoader, if it returns the length of `self._loader._loader` it will return the correct length if the DataLoader is using a DistributedSampler.

**Comment by dlibenzi** [comment]
I think it is OK for them to live as wrappers.
Maybe we could expose the internal loader object, but if the caller fiddle with it while it is in the hands of the `ParallelLoader`, funny things can happen.

**Comment by tmabraham** [comment]
@dlibenzi So will I need to continue to monkey-patch PerDeviceLoader if you don't plan to fix this? I currently have monkey-patched the PerDeviceLoader to add a length method, and a dataset attribute.

**Comment by dlibenzi** [comment]
The length would be valid only if this is feeding a single device.
But if you do, can you just get the length from the original loader?

**Comment by tmabraham** [comment]
@dlibenzi That is what I do now.

This is what I have:
def len_parallelloader(self):
  return len(self._loader._loader)
pl.PerDeviceLoader.__len__ = len_parallelloader

**Comment by dlibenzi** [comment]
Why would you need that?
When you create the `ParallelLoader` (which is the only dispenser of `PerDeviceLoader` objects) you have the original loader at hands.
Just get the length there and pass it to the functions which take the `PerDeviceLoader` ...

**Comment by tmabraham** [comment]
@dlibenzi I am creating a callback to use with fastai. The training loop in fastai iterates over the dataloader, so I have to set the `PerDeviceLoader` as the dataloader so fastai iterates over the correct object.

**Comment by dlibenzi** [comment]
Oh, OK. So your code assumes a `DataLoader` interface? Got it!
Instead of monkey-patching, you could create a real object which wraps the `PerDeviceLoader`?

For us adding a `__len__()` is trouble because the same `PerDeviceLoader` class is also used for multi-threads based data parallel, where the samples of the original loader are spread across device, and, we have the `fixed_batch_size` argument which makes pre-calculation difficult.
We also don't want to load all the samples, as we might run out of memory.
So the `ParallelLoader` and `PerDeviceLoader` works more like streamers interfaces.

**Comment by tmabraham** [comment]
@dlibenzi Yes, fastai assumes the `DataLoader` interface. If I wrap an object for `PerDeviceLoader` I still need to be able to define attributes like length. However, I guess I could set `__next__` to be the same as `PerDeviceLoader.__next__`

I am still not understanding the reasoning behind `__len__()`. In the case of threading, if multiple XLA devices are being used, then the `DistributedSampler` should be used. Since `DataLoader` obtains the length from the sampler, `DistributedSampler` should return the correct length as spread across devices. Is there something I am misssing?

**Comment by dlibenzi** [comment]
No.
In multi-thread case, the ParallelLoader does the (part of) sharding, and the number of samples is not know before (unless you loop&load though all samples - which we do not want).
You are confusing multi-threading with multi-processing.

**Comment by bkkaggle** [comment]
Just to clarify @dlibenzi , will @tmabraham 's path work correctly when training on a single device or when on multiprocessing?

**Comment by dlibenzi** [comment]
Yes, for single core, and multi-processing, should work.

**Comment by julien-c** [comment]
Also see https://github.com/pytorch/xla/pull/1991
