### ISSUE TITLE
Differences between `data_parallel` and `xla_multiprocessing`.

### ISSUE THREAD

**Issue by brendanxwhitaker** [pytorch/xla#1202]
## ❓ Questions and Help
Is it possible to process a single epoch in parallel across multiple devices via `xla_multiprocessing`? As opposed to instead of running `n` epochs via `n` processes, each on separate devices, as seems to be done in the example here: [https://github.com/pytorch/xla/blob/master/test/test_train_mp_mnist.py](url). Or do you have to use multithreading via `torch_xla.distributed.data_parallel` to achieve this behavior?

I printed out the index of the process (passed as first argument to `_mp_fn`) and the index of the data point upon each iteration in each training loop in the above example, and found that it was processing  the `k`-th data point `n` times at each time step, one for each device. Code snippet below:

```python
    def train_loop_fn(loader):
        tracker = xm.RateTracker()

        model.train()
        for x, (data, target) in enumerate(loader):
            print("Index %d data %d" % (index, x))
            optimizer.zero_grad()
            output = model(data)
            loss = loss_fn(output, target)
            loss.backward()
            xm.optimizer_step(optimizer)
            tracker.add(FLAGS.batch_size)
            if x % FLAGS.log_steps == 0:
                test_utils.print_training_update(
                    device, x, loss.item(), tracker.rate(), tracker.global_rate()
                )
```

And a sample of the output:
```
Index 2 data 39
Index 4 data 39
Index 0 data 39
Index 1 data 39
Index 6 data 39
Index 7 data 39
Index 3 data 39
Index 5 data 39
Index 0 data 40
Index 2 data 40
Index 6 data 40
Index 7 data 40
Index 4 data 40
Index 1 data 40
Index 5 data 40
Index 3 data 40
[xla:0/2](40) Loss=0.00014 Rate=3615.88 GlobalRate=3832.21 Time=Wed Oct 16 00:05:56 2019
[xla:0/6](40) Loss=0.00014 Rate=3709.91 GlobalRate=3856.45 Time=Wed Oct 16 00:05:56 2019
```

I'm a bit confused because the explanations here [http://pytorch.org/xla/](url) seem to imply they are equivalent. I may be misunderstanding something. Pointers or clarifications appreciated. Thanks!

**Comment by jysohn23** [comment]
Hi @brendanxwhitaker, the step count you're seeing there on each of the `n` processes each has a different batch. So in fact where you see `data 39` 8 times, all 8 of those batches should have different data as the data is sharded among all the 8 processes. The sharding is done [here](https://github.com/pytorch/xla/blob/master/test/test_train_mp_mnist.py#L82) by a regular `DistributedSampler` based on the ordinal of the process. Hope that's clear!

**Comment by brendanxwhitaker** [comment]
Ah I see. It is, thanks for explaining!
