### ISSUE TITLE
test_train_mp_mnist.py is only using xla:0?

### ISSUE THREAD

**Issue by tmabraham** [pytorch/xla#1203]
Why is [test_train_mp_mnist.py](https://github.com/pytorch/xla/blob/master/test/test_train_mp_mnist.py) only using `xla:0`?

This check for the world_size and subsequent use of DistributedSampler seems to indicate that the intent was to use all available XLA devices.

https://github.com/pytorch/xla/blob/master/test/test_train_mp_mnist.py#L81-L86

However, I ran this script with Colab's TPU v3-8, and I get output like this:
```
[xla:0/3](0) Loss=2.41745 Rate=3.82 GlobalRate=3.82 Time=Wed Oct 16 00:41:27 2019
[xla:0/7](0) Loss=2.39922 Rate=3.83 GlobalRate=3.83 Time=Wed Oct 16 00:41:27 2019
[xla:0/6](0) Loss=2.41655 Rate=3.84 GlobalRate=3.84 Time=Wed Oct 16 00:41:27 2019
[xla:0/1](0) Loss=2.41790 Rate=3.79 GlobalRate=3.79 Time=Wed Oct 16 00:41:27 2019
[xla:0/5](0) Loss=2.41677 Rate=3.78 GlobalRate=3.78 Time=Wed Oct 16 00:41:27 2019
[xla:0/0](0) Loss=2.39519 Rate=3.44 GlobalRate=3.44 Time=Wed Oct 16 00:41:27 2019
[xla:0/2](0) Loss=2.37788 Rate=3.67 GlobalRate=3.67 Time=Wed Oct 16 00:41:27 2019
[xla:0/4](0) Loss=2.36522 Rate=3.73 GlobalRate=3.73 Time=Wed Oct 16 00:41:27 2019
```
On the other hand, the threading Colab example displays like this:

```
[xla:4](20) Loss=2.36352 Rate=110.60 GlobalRate=131.51 Time=Mon Oct  7 23:26:56 2019
[xla:7](20) Loss=2.39862 Rate=110.86 GlobalRate=132.54 Time=Mon Oct  7 23:26:56 2019
[xla:5](20) Loss=2.34457 Rate=110.76 GlobalRate=132.15 Time=Mon Oct  7 23:26:56 2019
[xla:8](20) Loss=2.38541 Rate=111.00 GlobalRate=133.04 Time=Mon Oct  7 23:26:56 2019
[xla:1](20) Loss=2.33874 Rate=110.21 GlobalRate=130.25 Time=Mon Oct  7 23:26:56 2019
[xla:2](20) Loss=2.39182 Rate=110.23 GlobalRate=130.30 Time=Mon Oct  7 23:26:56 2019
[xla:6](20) Loss=2.32715 Rate=110.81 GlobalRate=132.26 Time=Mon Oct  7 23:26:56 2019
[xla:3](20) Loss=2.38970 Rate=110.44 GlobalRate=130.79 Time=Mon Oct  7 23:26:56 2019
```

Additionally, I printed which device is being used before beginning any training, and it always prints `xla:0`.

Is this a bug?

**Comment by dlibenzi** [comment]
No, it is just a different device mapping.
As far as multi-processing goes, each process sees only one device. Could be `xla:0` ... but you should not be assuming `0`.
The `xl.xla_device()` API will return the proper device.

In multi-threading, each process sees a set of devices (8 for v3-8), which are getting different ordinals.

**Comment by zcain117** [comment]
The output you're seeing comes from the `_get_device_spec` function:
https://github.com/pytorch/xla/blob/master/test/test_utils.py#L10

The first number is device, which will always be 0 unless you're using multiple TPUs. In test_train_mp_mnist.py, we find the device here using the method Davide mentioned:
https://github.com/pytorch/xla/blob/master/test/test_train_mp_imagenet.py#L161

**Comment by tmabraham** [comment]
I am getting a little confused.

IIRC Colab comes with a TPU v3-8 which has 8 cores, correct? When I print `xm.get_xla_supported_devices()` I get `['xla:1', 'xla:2', 'xla:3', 'xla:4', 'xla:5', 'xla:6', 'xla:7', 'xla:8']` and `xm.xrt_world_size()` returns 8. So I thought each core is one XLA device. However, `xm.xla_device()` has always returned `xla:0` from _all 8 processes_ and you are saying that `xla:0` represents something else? Could you please clarify?

**Comment by dlibenzi** [comment]
Yes. From the main process, if you list the devices, you get 8 devices.
But when you run multiprocessing, if you notice, you call `xmp.spawn()` at the very beginning, and this is going to create 8 separate processes each own seeing 1 of the 8 devices, and they will all be called `xla:0`.

**Comment by tmabraham** [comment]
OK thanks for the clarification. Indeed, when I print `xm.get_xla_supported_devices()` from the main process I get all 8 devices, but from each individual process I get only `xla:0`.
