### ISSUE TITLE
PyTorch XLA MP semaphore issue

### ISSUE THREAD

**Issue by tmabraham** [pytorch/xla#1204]
I ran the test_train_mnist_mp.py script with Colab's TPU and got the following warning as the epoch is finishing after the loss metrics have been printed:
```
/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
```

What is the cause of this issue?

**Comment by dlibenzi** [comment]
Not sure. Is it a warning or a fatal?

**Comment by tmabraham** [comment]
@dlibenzi It is a warning.

**Comment by thomasbrandon** [comment]
Yes, it's just a warning from [here](https://github.com/python/cpython/blob/cb064fc2321ce8673fe365e9ef60445a27657f54/Lib/multiprocessing/semaphore_tracker.py#L142). Unfortunately they don't give the semaphore name(s) which have been recorded and might aid in tracking it down.
If it is always 1 leaked semaphore then it at least seems to indicate they're not being repeatedly leaked. In which case there shouldn't be a major risk of hitting the semaphore limit. The tracker cleans them up after reporting on process termination.
A quick search didn't find a clear link to colab though that seems possible. There were some reports of it with PyTorch non-XLA, on older versions. Couldn't see any real resolution there.

**Comment by dlibenzi** [comment]
We don't even use `torch.multiprocessing` gradient reduction capabilities.
The only reason we use `torch.multiprocessing` instead of plain Python multiprocessing is because pytorch might want to do things to make sure the pytorch library ecosystem does not fight with it.
Like the force-use of `spawn` as process creation method.

**Comment by tmabraham** [comment]
@dlibenzi This error seems to come right after printing the metrics. Has this error not been seen when using TPUs on GCP?

**Comment by taylanbil** [comment]
I have seen this when using **GPUs** on GCP, and I recall doing some research online, it seemed mild. I have not seen this w/ TPUs, although I did not play w/ the file in question much.

**Comment by dlibenzi** [comment]
Yesterday I ran a few experiments with multi-processing on my VMs, and never saw this warning.
In any case I believe (until proven contrary) this is harmless, so IMHO we can close this issue and eventually re-open with more information in case it will reveal to be fatal.
