### ISSUE TITLE
Address family not supported by protocol

### ISSUE THREAD

**Issue by brendanxwhitaker** [pytorch/xla#1211]
## ❓ Questions and Help

Cryptic error message running custom model on Colab TPUs. 

I'm guessing by address it's referring to the TPU address information that is printed at the beginning of each run. Anyone seen this before? Help appreciated!

```
2019-10-16 23:56:30.217307: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:1194] 
Creating mesh service bound to localhost:51131
E1016 23:56:30.218200495   53633 server_chttp2.cc:40]        {
  "created": "@1571270190.218176851",
  "description": "Only 1 addresses added out of total 2 resolved",
  "file": "external/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc",
  "file_line": 357,
  "referenced_errors": [
    {
      "created": "@1571270190.218163539",
      "description": "Address family not supported by protocol",
      "errno": 97,
      "file": "external/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc",
      "file_line": 379,
      "os_error": "Address family not supported by protocol",
      "syscall": "socket",
      "target_address": "[::1]:51131"
    }
  ]
}
```

**Comment by dlibenzi** [comment]
Are you trying to run multi-processing on Colab?

**Comment by brendanxwhitaker** [comment]
Yes, sorry should have been more specific. I adapted the multiprocessing example on the pytorch website. The above error popped up when only using `nprocs==1`, though.

**Comment by dlibenzi** [comment]
Weird that only happens with `nprocs == 1`.
Is it fatal?

**Comment by brendanxwhitaker** [comment]
It is not fatal, though the TPU utilization is suspiciously low (<0.05%), and then drops to zero fairly quickly, and the training is exceptionally slow. However it does not say no data. I wonder if it's falling back to running on CPU or something. A similar thing happens when running 8 processes. I suppose it's possible that that error is being printed when running on 8 as well, the start up output is massive and I might have missed it.

**Comment by dlibenzi** [comment]
Oh, I see. I think GRPC might try to bind to every address it got back by resolving `localhost`, and the IPV6 address binding failed.

**Comment by brendanxwhitaker** [comment]
Is that something that should affect performance?

**Comment by dlibenzi** [comment]
No. That is the client mesh service which is, for now, only used at initialization time.

**Comment by brendanxwhitaker** [comment]
Ah okay it must be unrelated then, thanks for your help! I take it this can be safely ignored?

**Comment by dlibenzi** [comment]
Yes.
If the client mesh would not bind at all, you would get an error at initialization time.
If you don't get that, you are off the woods.
