### ISSUE TITLE
Nearest/Bilinear Upsampling

### ISSUE THREAD

**Issue by eridgd** [pytorch/xla#1227]
## ❓ Questions and Help

I'm working on a super-resolution application that requires upsampling layers but it seems that nn.Upsample() is not yet supported:

```
Counter: aten::upsample_nearest2d
  Value: 88
Counter: aten::upsample_nearest2d_backward
```
ConvTranspose2d does work, but gives sub-par results. Is lowering for bilinear/nearest neighbor upsampling on the horizon?

Thank you

**Comment by dlibenzi** [comment]
Yes, I think we should be able to give those a try.

**Comment by dlibenzi** [comment]
Nearest will be going in soon.
We will be working on bilinear next ...

**Comment by eridgd** [comment]
Confirmed that it's working, thanks!

**Comment by nicholasturner1** [comment]
Hi, thank you for maintaining this!

Any chance you could implement the same op for 3d tensors?

**Comment by dlibenzi** [comment]
We will take a look into it.
I can offer no guarantees at this time.

**Comment by dlibenzi** [comment]
BTW, meanwhile you can cope with a bit of logic over the existing 2D resize features.
If your input is:
```
N, C, X, Y, Z
```
And you want to resize to:
```
N, C, X', Y', Z'
```
You reshape to:
```
N, C*X, Y, Z
```
And resize to:
```
N, C*X, Y', Z'
```
This creates a stack of C*X resized 2D tensors.
Then reshape to:
```
N, C, X, Y'*Z'
```
And resize to (note Y'*Z' does not change):
```
N, C, X', Y'*Z'
```
Finally reshape to:
```
N, C, X', Y, Z'
```
