### ISSUE TITLE
Problem with model accuracy (after restore) on TPU

### ISSUE THREAD

**Issue by mgrankin** [pytorch/xla#1245]
## 🐛 Bug

I’m training GPT-2 from huggingface/transformers on TPU. It’s training well. At the end of a training I’ve got loss around 4.36. When I save and restore the model - the loss skyrockets somewhere to 9.75.

## To Reproduce

The whole code is here https://github.com/mgrankin/ru_transformers/blob/master/tpu_lm_finetuning.py

## Expected behavior

I’ve got no similar issues with saving and loading on GPU with that code. The loss should stay the same.

## Environment

 - reproducible on XLA backend [CPU/TPU]: TPU
 - torch_xla version: daily build

## Additional context

https://discuss.pytorch.org/t/problem-with-model-accuracy-after-restore-on-tpu/59304

**Comment by dlibenzi** [comment]
Hi Mikhail,

can you try something like this, but with your model instead of MNIST?

https://github.com/pytorch/xla/blob/2ddfcffd3cf91e7105bae61f7defa4591cdcb900/test/test_operations.py#L1222

**Comment by mgrankin** [comment]
I've tried to do that here

https://github.com/mgrankin/ru_transformers/blob/d858cb494677af88d82f3b9481ade676d1faf5f2/tpu_lm_finetuning.py#L663

If I don't comment the line `model = model.to(xla_device)` then the process hangs on the line `xm.save(to_save(model).state_dict(), 'tf3.bin')`

If do comment (as in the code right now), then I got an assertion error. 
`AssertionError: tensor(0.0361, device='xla:0') not less than or equal to 1e-05 :`

The model already should be on the device, so I have no idea why doing `model = model.to(xla_device)` results in freezing.

**Comment by dlibenzi** [comment]
`xm.save()` already handles the master ordinal.
You should not be having that. Just call `xm.save()`.
But to clear things out, just run single-core.
Just call `main(0)` instead of `xmp.spawn(main)`.

Also, the is `xm.master_print()` utility now.

**Comment by mgrankin** [comment]
I did the following
1. uncommented `model = model.to(xla_device)`
1. put a `main(0)` instead of `xmp.spawn(main)`

No freezing and I've got an error

`AssertionError: tensor(0.0003, device='xla:1') not less than or equal to 1e-05 :`

0.0003 is much smaller than previous 0.0361, so I called `assertEqual` with `prec=1e-3`. No error in that case. Where do we go from here?

**Comment by dlibenzi** [comment]
Is this done by simply creating a model from scratch (brand new weights, no computations done on them)?

**Comment by mgrankin** [comment]
The first model is trained a bit and then saved. The second model is created from scratch, loaded with saved weights from the file and no computations done on that model.

the second model:
```
state_dict = torch.load('tf3.bin')
cpu_model = model_class(config=config)
cpu_model.load_state_dict(state_dict)
loaded_model = cpu_model.to(xla_device)
```

**Comment by dlibenzi** [comment]
Can you just do this?
```Python
    xla_device = xm.xla_device()
    model = model_class(config=config).to(xla_device)
    with tempfile.NamedTemporaryFile() as tf:
      xm.save(model.state_dict(), tf)
      state_dict = torch.load(tf.name)
    cpu_model = model_class(config=config)
    cpu_model.load_state_dict(state_dict)
    loaded_model = cpu_model.to(xla_device)
    self.assertEqual(model.state_dict(), loaded_model.state_dict())
```

**Comment by mgrankin** [comment]
This works perfectly, no errors.

**Comment by dlibenzi** [comment]
OK, good. There is no "weirdness" in the model parameters structure.
I see from your code that you are exiting the training loop manually, with the optimizer step potentially not being run.
Even when existing by the end of the `enumerate()`, if your gradient accumulation step is not 1, you could end up with un-applied gradients.
Can we try to simplify those to see if we can better diagnose the issue?
You do not need `barrier=True` normally in the `xm.optimizer_step()`.
Also, when debugging precision/convergence issues, better run in single core.
Instead of hacking `main(0)` call, you can pass `nprocs=1` to `xmp.spawn()`.

**Comment by mgrankin** [comment]
I've simplified the training loop
```
        for epoch in train_iterator:
            p_train_dataloader = pl.ParallelLoader(train_dataloader, [args.device])
            epoch_iterator = tqdm(p_train_dataloader.per_device_loader(args.device), total=len(train_dataloader), desc="Iteration", disable=not xm.is_master_ordinal())

            model.train()
            for step, batch in enumerate(epoch_iterator):
                optimizer.zero_grad()
                outputs = model(batch, labels=batch)
                loss = outputs[0]  # model outputs are always tuple in pytorch-transformers (see doc)

                loss.backward()
                xm.optimizer_step(optimizer)
                scheduler.step()  

            # evaluate once in an epoch    
            if args.evaluate_during_training: 
                log_info(f"Eval {evaluate(args, model, tokenizer)}")            
```

https://github.com/mgrankin/ru_transformers/blob/4cbc2df625fcc6953d2769f794af3c31ea89045b/debug_lm_finetuning.py#L371

**Comment by dlibenzi** [comment]
What happens if you do not save the model, and do two consecutive `evaluate()`?
Does the perplexity stay constant?

**Comment by dlibenzi** [comment]
One more thing, do you have BF16 enabled?

**Comment by mgrankin** [comment]
With two consecutive `evaluate()` with no reloading the perplexity stays perfectly the same.

BF16 is typically enabled, but I've disabled it for the debugging purpose and even started a fresh container with fresh TPU. No change - perplexity is worse after reloading and `assertEqual` gives an error.

**Comment by dlibenzi** [comment]
Thank for following up!
So now, **running single core**, can you try to use straight `torch.save()` instead of `xm.save()`?

**Comment by mgrankin** [comment]
With single core and `torch.save()` I've got the same error. I don't know if that matters, but in that case `assertEqual ` reports way bigger difference and perplexity skyrockets.

```
10/28/2019 17:21:30 - INFO - __mp_main__ -   Eval1 {'perplexity': tensor(73.9242)}
10/28/2019 17:22:08 - INFO - __mp_main__ -   Eval2 {'perplexity': tensor(61233.3125)}
AssertionError: tensor(1.7888, device='xla:1') not less than or equal to 1e-05
```

**Comment by mgrankin** [comment]
I've modified `assertEqual` to see which tensors are wrong. I run single core with `xm.save()`. The code for new `assertEqual` is here https://github.com/mgrankin/ru_transformers/blob/9d52a4caef16df5b921c386f4841c879877d03a4/debug_lm_finetuning.py#L568

Interestingly, the only tensor that is wrong is the first one - `transformer.wte.weight`. All others are good!

```
transformer.wte.weight
tensor(0.4786, device='xla:1') not less than or equal to 1e-05 :
transformer.wpe.weight
ok
transformer.h.0.ln_1.weight
ok
transformer.h.0.ln_1.bias
ok
transformer.h.0.attn.bias
ok
```

**Comment by mgrankin** [comment]
I did the following

```
    print(state_dict['transformer.wte.weight'])
    cpu_model = model_class(config=config)
    cpu_model.load_state_dict(state_dict)
    print(cpu_model.state_dict()['transformer.wte.weight'])
```

It appears that these two are already different. So it's the model-specific problem. I'm so sorry I wasted so much of your time.

**Comment by dlibenzi** [comment]
Is the `state_dict` in the first line already on CPU, or is it on XLA device?

**Comment by mgrankin** [comment]
```
    xm.save(model.state_dict(), 'tf4.bin')
    state_dict = torch.load('tf4.bin')
```

It on CPU.

**Comment by dlibenzi** [comment]
Hmm, so it seems that `model.load_state_dict()` is changing them.

**Comment by mgrankin** [comment]
Hurray! I've found a bug and a workaround! In GPT-2 model the input and output embeddings are the same, they use the following code to tie weights:

```
    def __init__(self, config):
        super(GPT2LMHeadModel, self).__init__(config)
        self.transformer = GPT2Model(config)
        self.lm_head = nn.Linear(config.n_embd, config.vocab_size, bias=False)

        self.init_weights()
        self.tie_weights()

    def tie_weights(self):
        """ Make sure we are sharing the input and output embeddings.
            Export to TorchScript can't handle parameter sharing so we are cloning them instead.
        """
        self._tie_or_clone_weights(self.lm_head,
                                   self.transformer.wte)

...


    def _tie_or_clone_weights(self, first_module, second_module):
        """ Tie or clone module weights depending of weither we are using TorchScript or not
        """
        if self.config.torchscript:
            first_module.weight = nn.Parameter(second_module.weight.clone())
        else:
            first_module.weight = second_module.weight

        if hasattr(first_module, 'bias') and first_module.bias is not None:
            first_module.bias.data = torch.nn.functional.pad(
                first_module.bias.data,
                (0, first_module.weight.shape[0] - first_module.bias.shape[0]),
                'constant',
                0
            )
```

For some reason, after I move the mode to TPU, using `model = model.to(device)`, the weights become decoupled. Then I save decoupled weights and during restore it ties them again. It loads correctly, it just doesn't expect tied weights to be different.

The workaround is to tie weights again after moving model to the TPU.

```
    model = model.to(args.device)
    model.tie_weights()
```

**Comment by mgrankin** [comment]
Great, so I reopened an issue in huggingface/transformers. Thank you so much for your tremendous help and patience!

**Comment by mgrankin** [comment]
Just to make sure. Is this a correct and expected behaviour for PyTorch XLA?

```
import torch
from torch import nn
import torch_xla
import torch_xla.core.xla_model as xm

class MD(nn.Module):
    def __init__(self):
        super(MD, self).__init__()    
        self.a = nn.Linear(1, 1)
        self.b = nn.Linear(1, 1)

net = MD()
net.a.weight = net.b.weight # tie weights

# cpu
net.a.weight.data = torch.tensor([1.])
net.b.weight.data = torch.tensor([2.])
assert(net.a.weight.data == net.b.weight.data)
# tpu
net.to(xm.xla_device())
net.a.weight.data = torch.tensor([1.], device=xm.xla_device())
net.b.weight.data = torch.tensor([2.], device=xm.xla_device())
assert(net.a.weight.data == net.b.weight.data)

```

**Comment by dlibenzi** [comment]
A `model.to()` ends up calling the `apply()` model method, which by default transforms the state dictionary.
If you model does special weight handling, it needs to override the `apply()` method IMHO, call the parent's, and then redo all the special weight handling on the transformed tensors.

**Comment by mgrankin** [comment]
The problem is Pytorch keeps the links intact then you call `model.to` and Pytorch/XLA breaks the links. It would be great to have a consistent experience with two libraries. Is there a reason not to implement that as a feature?

**Comment by dlibenzi** [comment]
What are the link being broken?
Can you give us an example?

**Comment by mgrankin** [comment]
Yes, the example is [in my comment](https://github.com/pytorch/xla/issues/1245#issuecomment-548223090)

After that 
`net.a.weight = net.b.weight # tie weights`

`a` and `b` point to the same object, when you change `b` weights you change `a`. `model.to` on PyTorch keeps the link and `model.to` on PyTorch/XLA brakes it and makes them two different objects.

**Comment by dlibenzi** [comment]
That is what I was mentioning when I talked about the module's `apply()` override.
Can you check whether doing a `to(GPU)` and then asserting, holds true?

**Comment by mgrankin** [comment]
It works the same way on GPU as on CPU. PyTorch keeps the link. Why PyTorch/XLA should brake it?

**Comment by dlibenzi** [comment]
I think it is not XLA backend fault, but the way core tensor data is handled in a `set_data()` variable operation. We do not have control of that layers, which sits above us.
But we will check about it.

**Comment by dlibenzi** [comment]
Yeah, if you print:
```Python
print(id(net.a.weight))                                                                                                                                                                                                                     
print(id(net.b.weight))
```
After the `net.to(XLA)` you will find these are already two separate objects.
I think the model's `to()` might not handle correctly anything besides CPU or CUDA.
If you try after a `net.to(CUDA)` you will find matching id()s.

**Comment by dlibenzi** [comment]
I think they key should be here:

https://github.com/pytorch/pytorch/blob/466ab93ef55ce05da99c251ea88cdcfc8f1c2cfa/torch/nn/modules/module.py#L203

And ultimately around her:

https://github.com/pytorch/pytorch/blob/466ab93ef55ce05da99c251ea88cdcfc8f1c2cfa/c10/core/TensorImpl.h#L913

**Comment by mruberry** [comment]
@mgrankin Thanks for reporting this issue! We should update our programming tips & tricks to include sharing weights. You're right that you have to "retie" your weights after moving them to an XLA device and don't (today) when moving to CUDA. 

It looks like the CUDA behavior will change to be more like the XLA behavior in the future, however, so retying weights is probably the correct (and future-proof) solution.

**Comment by mgrankin** [comment]
@mruberry Thank you for updating the troubleshooting guide!

**Comment by MouathAb** [comment]
Thank you all,


    reproducible on XLA backend [CPU/TPU]: TPU (google colab)
    torch_xla version: 1.7
    model: Vision Transformer 

I've got the same problem with model accuracy (after restore) on TPU, and I think this time it's not about saving/loading the model! 
This is a part of the code for train/valid:
`    for epoch in range(1, epochs + 1):
        gc.collect()
        para_train_loader = pl.ParallelLoader(train_loader, [device])#

        xm.master_print(f"{'='*50}")
        xm.master_print(f"EPOCH {epoch} - TRAINING...")
        
        train_loss, train_acc = model.train_one_epoch(para_train_loader.per_device_loader(device), criterion, optimizer, device,scheduler)
        xm.master_print(
            f"\n\t[TRAIN] EPOCH {epoch} - LOSS: {train_loss}, ACCURACY: {train_acc}\n"
        )
        train_losses.append(train_loss)
        train_accs.append(train_acc)
        gc.collect()
        
        # evaluate the model on the validation data
        if valid_loader is not None:
            gc.collect()
            para_valid_loader = pl.ParallelLoader(valid_loader, [device])
            xm.master_print(f"EPOCH {epoch} - VALIDATING...")
            valid_loss, valid_acc = model.validate_one_epoch(
                para_valid_loader.per_device_loader(device), criterion, device)
            xm.master_print(f"\t[VALID] LOSS: {valid_loss}, ACCURACY: {valid_acc}\n")
            valid_losses.append(valid_loss)
            valid_accs.append(valid_acc)
            gc.collect()`

And this is the inference part where I re-test the saved model on the validation dataset  :

`valid_dataset = Dataset(valid_df, transforms=transforms_valid)
valid_sampler = torch.utils.data.distributed.DistributedSampler(valid_dataset,num_replicas=xm.xrt_world_size(),rank=xm.get_ordinal(),shuffle=False)
valid_loader = torch.utils.data.DataLoader(dataset=valid_dataset,batch_size=len(valid_df),sampler=valid_sampler,drop_last=True,num_workers=8)

model = TRAIN(n_classes=num_classes, pretrained=True) # create the model
device = xm.xla_device()
model.to(device)
model.load_state_dict(torch.load(Path_to_saved_modell))
model.eval()
criterion = nn.CrossEntropyLoss()

data, target = next(iter(valid_loader))
data = data.to(device, dtype=torch.float32)
target = target.to(device, dtype=torch.int64)

with torch.no_grad():

    # compute predicted outputs by passing inputs to the model
    output = model(data)
    pred = output.argmax(dim=1)

    # calculate the batch loss
    loss = criterion(output, target)

    # Calculate Accuracy
    accuracy = (pred == target).float().mean()

print(accuracy)
`

PS : I tried one  thing that works but .., during valid/train process I validate on a vf dataFrame which is the valid_df duplicated 8 times as the number of cores and I set the batch size as the length of valid_df: 

`vf = pd.concat([valid_df,valid_df,valid_df,valid_df,valid_df,valid_df,valid_df,valid_df],ignore_index=True)
valid_dataset = Dataset(vf, transforms=transforms_valid)
valid_sampler = torch.utils.data.distributed.DistributedSampler(
            valid_dataset,
            num_replicas=xm.xrt_world_size(),
            rank=xm.get_ordinal(),
            shuffle=False,
        )
valid_loader = torch.utils.data.DataLoader(
            dataset=valid_dataset,
            batch_size = len(valid_df),
            sampler=valid_sampler,
            drop_last=True,
            num_workers=8,
        )
` 
in that way, I could have the same performance.
