### ISSUE TITLE
Is tensorboard visualization of computation graphs supported?

### ISSUE THREAD

**Issue by 20171130** [pytorch/xla#1260]
Hi. I would like to know is it possible to dump a tensorboard visualization of the structure of the computation graph and the TPU compatibility graph for debugging purposes.
[reference](https://cloud.google.com/tpu/docs/cloud-tpu-tools#profile_tab) This can be done in TF by setting the "model_dir" attribute of tf.estimator API.

**Comment by 20171130** [comment]
Thank you for your rapid reply!  So I guess I can get a visualization of the computation graph with the function `save_tensors_graph` and inspect TPU compatibility with `metric_report`. (Looking forward to a tensorboard integrated visualization which might be visually more appealing and intereactive.)

**Comment by dlibenzi** [comment]
For visualization, you can:
```Python
print(torch_xla._XLAC._get_xla_tensors_dot([tensor...]))
```

And the feed to `graphviz`.
Graphs gets pretty big though, so you might not be able to get it rendered.
