### ISSUE TITLE
How to share weights memory while running big models

### ISSUE THREAD

**Issue by Glorf** [pytorch/xla#1262]
## ❓ Questions and Help

Hello, I use pytorch-xla multiprocessing approach to train my gpt2 model from `huggingface-transformers`. When training from pretrained weights, the model is however loaded multiple times, which increase the need for host memory. While for GPT2-small it's not a problem. GPT2-large can fill up to 80GB of ram when loaded by all processes. What is the suggested way to share host memory for model weights while running multiprocessing? Is this possible at all?

The part of code, run by each thread that causes the problem:
```
    model_class = GPT2LMHeadModel
    model = model_class.from_pretrained("gpt2")
    model.to(device).train()
```

**Comment by Glorf** [comment]
Thanks for your response!
I'd like to implement the mentioned hack as I don't really need any permanent solution. However, I'm not sure how can I use multiprocessing critical sections or barriers on group of processes spawned using xmp.spawn()
When I try to use standard torch mp.barrier(), I get `Default process group is not initialized`
The only barrier-like function I see is mark_step() which calls something like:
```
  torch_xla._XLAC._xla_step_marker(
      torch_xla._XLAC._xla_get_default_device(), [],
      wait=xu.getenv_as('XLA_SYNC_WAIT', bool, False))
```
However, I have no idea how it works. Can you give me any advice in this area?

**Comment by dlibenzi** [comment]
You can use Unix flock (in os) or things like NamedAtomicLock.
The mark_step() has nothing to do with it.
It gets tricky to implement this though.

**Comment by Glorf** [comment]
Thanks, this approach solved my problem:
```python
lock_file = "tpu.lock"
fd = open(lock_file, "w")
fcntl.lockf(fd, fcntl.LOCK_EX)
#load a model here
model.train().to(device)
gc.collect()
fcntl.lockf(fd, fcntl.LOCK_UN)
#continue to training

However, it'd be nice to be able to use standard python multiprocessing for that - I didn't manage to do it.
From my perspective the solution is good enough, closing

**Comment by srush** [comment]
I would love to reopen this issue (as we are now trying to add this to Hugging Face). I wasn't able to get the proposed solution to work. `gc.collect()` doesn't seem to free any RAM when called right afterwards. `model.to(device)`. Is it loaded in lazily? @Glorf do you have an example of your solution.

**Comment by dlibenzi** [comment]
The full explanation is a bit long, but I try to summarize.
As mentioned, when creating XLA tensors with PyTorch CPU tensors data, the send-to-device is delayed, so we can batch it.
Since this is happening async, we need to make a copy of the pytorch CPU data, as otherwise one could have done:
```Python
xt = x.to(xla_device)
x.add_(...)
```
And when we send `xt` data we end up sending the add result.
If pytorch had a `Copy On Write` bit we could set, we could avoid copies.
the effectiveness of serializing `model.to()` calls depends on Python GC and the underlying memory allocators.

But the above is only part of the issue.
When you checkpoint, you will have the same exact problem.
Since all the core in a TPU/POD have to run the same exact code, the CPU data fetch will happen in all cores:

https://github.com/pytorch/xla/blob/7c9ec60884a7d3a78b3f93446eb45e4be3280f37/torch_xla/core/xla_model.py#L487

So, while this is software and things can be done in one way or another, the added complexity and potential fragility need to be balanced with the ROI.

**Comment by srush** [comment]
I see, so the lesson here is that we really should allocate 8x model/data CPU ram to get TPU benefits. 

What a funny issue for Colab to have such awesome TPUs with such tiny ram.

**Comment by dlibenzi** [comment]
If you are trying to experiment, you can still run on one core (the code will be the same, just change `nprocs=1` as `xmp.spawn()` argument).
Colab is free, and we already bumped RAM 8-fold recently.
One cannot expect to run large models, at full performance, on Colab.

We are also changing the architecture in 2020, and based on the new one, the VMs should have _a lot_ more memory by default (north on 128GB).

**Comment by srush** [comment]
Cool, yeah I didn't mean to complain, it's awesome to have this access. It just felt close to being able to let people do superfast fine tuning jobs on TPU, which colab is perfect for. I'll try 1 core, but it seems around GPU speed.

**Comment by dlibenzi** [comment]
Our usual compare, since they end up costing the same $$, is one V100 with 2 TPU v3 cores.

**Comment by srush** [comment]
Silly question. Can you use 2 cores, I thought it was 1 or 8?

**Comment by dlibenzi** [comment]
We do not support 2 cores.

**Comment by srush** [comment]
@dlibenzi So I think you answered this above, but it sounds like checkpointing is going to also be 8x model size? Are there any tricks to limit this cost? I was able to get all my models on TPU and run an epoch, but as you anticipated checkpointing kills me.

**Comment by dlibenzi** [comment]
https://github.com/pytorch/xla/pull/1694 can help on the save side, but the issue remains in other places.
