### ISSUE TITLE
How should we create custom layer with trainable parameters?

### ISSUE THREAD

**Issue by RuiWang1998** [pytorch/xla#1289]
## ❓ Questions and Help
I was so excited to discover TPU support for PyTorch and its speed, but when I try to implement a Gaussian layer with trainable standard deviation, that is, I set the standard deviation as the parameter of the layer, based on which, every time a batch of input is fed into the layer, it generates a Gaussian convolutional/FIR filter and perform convolution with the input image. 

I have tried to just implement this layer on top of the ResNet-18/Cifar-10 notebook and every time I run the training part, the notebook session crashes. Is there a general guideline on how we are supposed to do it?

**Comment by RuiWang1998** [comment]
`class GaussianLayer(nn.Module):` 

    def __init__(self, input_channels: int, kernel_size: int, pad_type: str = 'zero', stride:list=[1,1],
                 std: float = None, fixed_std:bool=False):
        """
        Initializer
        :param input_channels: the number of input channels
        :param kernel_size: the size of the gaussian filter
        :param pad_type: the type of the padding
        :param fixed_std: the feature of the paper
        """
        super(GaussianLayer, self).__init__()
        self.input_channels = input_channels
        self.kernel_size = kernel_size
        self.stride = stride
        
        self.xy_squared_sum = nn.Parameter(self._generate_grid(kernel_size, input_channels), requires_grad=False)
        self.std = nn.Parameter(torch.tensor(std or 1).type(torch.float), requires_grad=not fixed_std)
        self.pad = self._get_pad_layer(pad_type)(kernel_size // 2)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Each time a forward method is called, the model generates a new Gaussian filter
        based on current standard deviation
        :param x: the input
        :return: the de-noised output
        """
        return F.conv2d(F.pad(x, self.kernel_size//2, 'constant', 0), self._generate_gaussian(), stride=self.stride, groups=self.input_channels)

    @staticmethod
    def _generate_grid(kernel_size: int, channels: int) -> torch.Tensor:
        """
        This function creates the coordinates of (x, y) for generating Gaussian filters
        :param kernel_size: the size of the square kernel
        :return: the grid to facilitate the calculation
        """
        xv, yv = torch.meshgrid([torch.arange(-kernel_size // 2 + 1, kernel_size // 2 + 1),
                                 torch.arange(-kernel_size // 2 + 1, kernel_size // 2 + 1)])
        xv, yv = xv.type(torch.float).repeat(channels, 1, 1), yv.type(torch.float).repeat(channels, 1, 1)
        return (xv ** 2 + yv ** 2) / 2

    def _generate_gaussian(self):
        """
        This function generates the Gaussian filter based on the standard deviation
        :return: the new Gaussian filter
        """
        kernel = torch.exp(- self.xy_squared_sum / self.std ** 2)

        kernel = kernel / kernel.sum() * self.input_channels
        return kernel.view(self.input_channels, 1, self.kernel_size, self.kernel_size)

**Comment by dlibenzi** [comment]
Can you provide a full repro code so we can try to debug not in Colab (so we have better tools for the job)?

**Comment by RuiWang1998** [comment]
Sure, here it is, I just add a few of these into the model, if you just add one before the first layer of the model, it fails.

class GaussianLayer(nn.Module):
    """
    A gaussian layer whose trainable parameter is the standard deviation and we suggest put this
    """

    def __init__(self, input_channels: int, kernel_size: int, pad_type: str = 'zero', stride:list=[1,1],
                 std: float = None, fixed_std:bool=False):
        """
        Initializer
        :param input_channels: the number of input channels
        :param kernel_size: the size of the gaussian filter
        :param pad_type: the type of the padding
        :param fixed_std: the feature of the paper
        """
        super(GaussianLayer, self).__init__()
        self.input_channels = input_channels
        self.kernel_size = kernel_size
        self.stride = stride
        
        self.xy_squared_sum = nn.Parameter(self._generate_grid(kernel_size, input_channels), requires_grad=False)
        self.std = nn.Parameter(torch.tensor(std or 1).type(torch.float), requires_grad=not fixed_std)
        self.pad = self._get_pad_layer(pad_type)(kernel_size // 2)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Each time a forward method is called, the model generates a new Gaussian filter
        based on current standard deviation
        :param x: the input
        :return: the de-noised output
        """
        return F.conv2d(F.pad(x, self.kernel_size//2, 'constant', 0), self._generate_gaussian(), stride=self.stride, groups=self.input_channels)

    @staticmethod
    def _generate_grid(kernel_size: int, channels: int) -> torch.Tensor:
        """
        This function creates the coordinates of (x, y) for generating Gaussian filters
        :param kernel_size: the size of the square kernel
        :return: the grid to facilitate the calculation
        """
        xv, yv = torch.meshgrid([torch.arange(-kernel_size // 2 + 1, kernel_size // 2 + 1),
                                 torch.arange(-kernel_size // 2 + 1, kernel_size // 2 + 1)])
        xv, yv = xv.type(torch.float).repeat(channels, 1, 1), yv.type(torch.float).repeat(channels, 1, 1)
        # for computation
        return (xv ** 2 + yv ** 2) / 2

    def _generate_gaussian(self):
        """
        This function generates the Gaussian filter based on the standard deviation
        :return: the new Gaussian filter
        """
        kernel = torch.exp(- self.xy_squared_sum / self.std ** 2)

        kernel = kernel / kernel.sum() * self.input_channels
        return kernel.view(self.input_channels, 1, self.kernel_size, self.kernel_size)

**Comment by RuiWang1998** [comment]
> Can you provide a full repro code so we can try to debug not in Colab (so we have better tools for the job)?

The rest of the code is just the one in the notebook.

**Comment by ailzhang** [comment]
@RuiWang1998 If you could export the notebook as a `.py` file, it'll help a lot :D Thanks!

**Comment by RuiWang1998** [comment]
> @RuiWang1998 If you could export the notebook as a `.py` file, it'll help a lot :D Thanks!

[gaussian_tpu.zip](https://github.com/pytorch/xla/files/3810541/gaussian_tpu.zip)

**Comment by ailzhang** [comment]
@RuiWang1998 The bug is not specific to Colab notebook. When I ran the `GaussianLayer` with an example output on CPU 
```
test_layer = GaussianLayer(3, 3)
x = torch.randn((128, 3, 32, 32))
a = test_layer(x)

```
And here's the error I got, it's mainly complaining the code about `F.pad`, if you fix that, it should work as expected. 
```

  File "gaussian.py", line 112, in <module>
    a = test_layer(x)
  File "/home/ubuntu/pytorch/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "gassian.py", line 83, in forward
    return F.conv2d(F.pad(x, self.kernel_size//2, 'constant', 0), self._generate_gaussian(), stride=self.stride, groups=self.input_channels)
  File "/home/ubuntu/pytorch/torch/nn/functional.py", line 2850, in pad
    assert len(pad) % 2 == 0, 'Padding length must be divisible by 2'
TypeError: object of type 'int' has no len()
```

**Comment by RuiWang1998** [comment]
[new_gaussian.zip](https://github.com/pytorch/xla/files/3810808/new_gaussian.zip)
@ailzhang Thank you and I apologies for miss-use of F.pad in the first place, but here is the real problem, if I add the layer at the beginning, it runs fine, (as commented in code), but if I add it somewhere else, it somehow fails.

**Comment by ailzhang** [comment]
@RuiWang1998 No worries, yea it's always easy to debug with CPU/GPU/XLA CPU backend before going to TPUs for speedup. Feel free to let me know if you see some weird behaviors after you try it out.

**Comment by RuiWang1998** [comment]
Hey all,

So it appears that xla does not work well with padding layers in Pytorch yet, where everything else is fixed and runs smoothly, if I use a padding layer in Pytorch, it runs for the first forward-backward pass and nothing more, but if I only uses conv2d's padding option, it runs fine.

**Comment by dlibenzi** [comment]
If you can post an example that works with PyTorch CPU/GPU and does not work with XLA devices, we will look into it and fix it.

**Comment by RuiWang1998** [comment]
@dlibenzi 
[new.zip](https://github.com/pytorch/xla/files/3816264/new.zip)

Hi, this seems to work fine on a GPU/CPU, not padding though

BTW, how should one save the model_parallel?

**Comment by ailzhang** [comment]
@RuiWang1998 `xm.save(model, <file_path>)` should work and save the models as CPU tensors. When reload, just manually move them to TPU by calling `.to()`. 

Btw we are interested in fixing the padding layer if you could give us a small repro. Thank you! :D

**Comment by RuiWang1998** [comment]
@ailzhang In GCP or Colab, I got this error with `xm.save()`
`AttributeError: module 'torch_xla.core.xla_model' has no attribute 'save'`

I will provide the padding layer code tonight regarding the issue, thanks!

**Comment by ailzhang** [comment]
@RuiWang1998 Oh I see, so that's something we added after 0.5 release and it's available in nightly images I think. 
In the 0.5 version, you can do `torch.save(model)` or `torch.save(model.to('cpu'))` directly. Let us know if that doesn't work for you :D

**Comment by RuiWang1998** [comment]
[paddingissue.zip](https://github.com/pytorch/xla/files/3826945/paddingissue.zip)
@ailzhang Sorry for the delay, I have been writing the paper. BTW how do I cite your work here?

**Comment by RuiWang1998** [comment]
@ailzhang 
Hi I used 
`torch.save(model_parallel, "model.pth")` and then load it with `torch.load("model.pth)`
and got this error
`ModuleNotFoundError: No module named 'schedulers'`

**Comment by ailzhang** [comment]
@RuiWang1998 Which pytorch version is that? 
Are you using the same environment to save/load the checkpoint btw?
