### ISSUE TITLE
xenv.WORLD_SIZE is inaccurate if xmp.spawn is run multiple times

### ISSUE THREAD

**Issue by jysohn23** [pytorch/xla#1341]
## 🐛 Bug

If you run `xmp.spawn` multiple times within the lifetime of a single process, the value of `xenv.WORLD_SIZE` will be incorrect and blow up because of this line: https://github.com/pytorch/xla/blob/95f76eb9d5a98977e5d2962457d769825a99c29a/torch_xla/distributed/xla_multiprocessing.py#L73

## To Reproduce

1. Run something like `test_train_mp_mnist.py` where we call `xmp.spawn` multiple times within the lifetime of the process.

**Comment by dlibenzi** [comment]
It is not supposed to be used like that.
You spawn once, and every action being repeated will be once you are within the "single device" worlds.

**Comment by jysohn23** [comment]
> It is not supposed to be used like that.
> You spawn once, and every action being repeated will be once you are within the "single device" worlds.

But in the Colab scenario we'd expect users to run the training/eval loop cell multiple times after tuning bits. For now locally I have a hack where I do something like:

```
import os
os.environ['XRT_SHARD_WORLD_SIZE'] = '1'
```

But it feels clunky.

**Comment by dlibenzi** [comment]
https://github.com/pytorch/xla/pull/1342

Though, I am not sure whether this should be encouraged.

**Comment by jysohn23** [comment]
#1342 fixes the issue.
