### ISSUE TITLE
Cannot load checkpoints in fairseq-tpu

### ISSUE THREAD

**Issue by zhuohan123** [pytorch/xla#1343]
## 🐛 Bug

Cannot load checkpoints in fairseq-tpu when running the code for both tpu and gpu.

## To Reproduce

Just train the MT model for a while, kill it after the first checkpoint, and load it back. it will fail after several training steps for TPU, and will fail at the first validation step after loading on GPU.

## Expected behavior

The code should run smoothly.

## Environment

 - reproducible on XLA backend [CPU/TPU]: 16-highmem-cpu, TPUv3-8 TPU
 - torch_xla version: nightly or v0.5, both don't work
 - Any other relevant information: we also tried to train on GPU on a V100

**Comment by zhuohan123** [comment]
@taylanbil

**Comment by zcain117** [comment]
@zhuohan123 could you provide us a with a stack trace or explain how the model failed during the validation step?

**Comment by taylanbil** [comment]
Thanks for reporting this. We changed the lower level model saving/loading mechanism just before we cut the 0.5 branch, and forgot to fix it in 0.5. This then fell off our radar, but I'll cherry pick the fix soon to 0.5 so it works there.

I'm now looking at nightly, the failure there should be new.

**Comment by taylanbil** [comment]
Something about the optimizer's state_dict being saved/loaded seems to be broken. @zhuohan123 are you saying that it's broken in the upstream repo too? or just pytorch-tpu version on gpus?

**Comment by taylanbil** [comment]
The issue doesn't happen if optimizer's state_dict to be loaded is moved to the device first. We are working on resolving this, will send out a pr that will fix the issue on nightly soon.

**Comment by sIncerass** [comment]
> Something about the optimizer's state_dict being saved/loaded seems to be broken. @zhuohan123 are you saying that it's broken in the upstream repo too? or just pytorch-tpu version on gpus?

It's broken while we trying to load for gpu as well as loading for tpus. 

Could you please detailed the process you are solving it (how to move the optimizer's state_dict to the device first) @taylanbil ?

**Comment by taylanbil** [comment]
fyi: I will post a fix on the tpu branch for this soon.

**Comment by taylanbil** [comment]
This issue actually stopped happening on the latest nightly + tpu branch for me.

In order to fix it on the 0.5 branch, I added something like the following [here](https://github.com/pytorch-tpu/fairseq/blob/tpu-r0.5/fairseq/trainer.py#L177):
```
for x in last_optim_state:
  x.to(device)
```

of course, make sure to pass the device down to the trainer.

**Comment by dlibenzi** [comment]
Hmm, if `x` is a tensor, `x.to(device)` should not change `x` (like in modules) AFAIK, but return the to-ed tensor.

**Comment by taylanbil** [comment]
Right, so it's actually a bit more complex, `last_optim_state` is a dict... Let me re-do the solution and add a diff here to this issue tomorrow.

**Comment by taylanbil** [comment]
@sIncerass @zhuohan123 do you need the fix on 0.5? Is the issue happening for you on nightly?

**Comment by Eric-Wallace** [comment]
It happens on both 0.5 and nightly.

**Comment by taylanbil** [comment]
pr linked above should fix this issue. keep in mind that checkpoint loading requires additional memory, so n1-standard-16 does not work (ooms), I tried on n1-standard-64 and it works.

**Comment by taylanbil** [comment]
with https://github.com/pytorch-tpu/examples/pull/39, the fix will be in nightly. please let me know if the issue persists for you.

**Comment by taylanbil** [comment]
closing this, please re-open if you are still having issues.
