### ISSUE TITLE
How to tell if a graph recompilation is happening?

### ISSUE THREAD

**Issue by hrbigelow** [pytorch/xla#1368]
## 📚 Documentation

Thanks so much for the great library!  I'm running my Pytorch model on Google Colab with TPU.  Following the tips in TROUBLESHOOTING.md, I see the following in my XLA_METRICS_FILE:
```
Metric: CompileTime
  TotalSamples: 12
  Accumulator: 44s280ms699.409us
  ValueRate: 952ms609.347us / second
  Rate: 0.25789 / second
  Percentiles: 1%=230ms554.170us; 5%=230ms554.170us; 10%=253ms547.395us; 20%=256ms764.061us; 50%=304ms288.564us; 80%=12s512ms567.169us; 90%=12s778ms277.508us; 95%=18s450ms18.269us; 99%=18s450ms18.269us
...
Metric: CompileTime
  TotalSamples: 14
  Accumulator: 01m03s282ms217.172us
  ValueRate: 924ms148.456us / second
  Rate: 0.20445 / second
  Percentiles: 1%=026ms136.061us; 5%=026ms136.061us; 10%=230ms554.170us; 20%=253ms547.395us; 50%=304ms288.564us; 80%=12s778ms277.508us; 90%=18s450ms18.269us; 95%=19s976ms381.702us; 99%=19s976ms381.702us
[more to follow]
```

There is one of these sections produced per SGD iteration.  Does the fact that the ValueRate value is about the same in each one, mean that the graph is being compiled each time?  If so, how do I tell what is causing it?  I have studied the output of XLA_SAVE_TENSORS_FILE, and I can't find any place where the tensor dimensions are different.

However, I do also see lots of occurrences of `aten::permute`, `aten::view`, `aten::squeeze`, `aten::relu`, etc.

I also find that the code runs quite slow compared to GPU.

Thanks again,

Henry

**Comment by dlibenzi** [comment]
Hi!
Can you post the full metrics?
Also, it is strange to see things like those `aten::` ops, as we lower them to XLA.
Are you sure they are `aten::*` and not `xla::*`?

**Comment by dlibenzi** [comment]
Sorry, I misread what you said.
If you are looking at the IR graph, the vast majority of the ops are `aten::*`.
The only ones which are `xla::*` are the internal ones which do not have a match in the pytorch/aten API.
So seeing `aten::*` in the IR graph is normal.
If you post the full metrics report, we can better asses the issue.

**Comment by hrbigelow** [comment]
Hi Davide,

Ahh, that's good to hear.  Actually, I reread the TROUBLESHOOTING.md and saw that you mentioned the aten operations in the metrics report, not the save-tensors report.

In any case, can you try this Colab out to reproduce the problem?  [tpu_ae_wavenet_tests](https://colab.research.google.com/drive/1MDY5ZpjlIU9Np4r0xSFNevtGekZT6vZk)

If that doesn't work, the repo is [ae-wavenet](https://github.com/hrbigelow/ae-wavenet) and I'm running it with the test data inside the dat directory with the command:

```
%run ae-wavenet/train.py new \
    -af ae-wavenet/par/arch.ae.json \
    -tf ae-wavenet/par/train.basic.json \
    -hw TPU -lrr 1e-6 -lrs 0 -nw 100 -nb 4 -si 5000 ./basic.full.%.ckpt \
    ae-wavenet/dat/librispeech.some.dat
```

It runs about 3-5 times faster on GPU (use `-hw GPU` command-line switch, otherwise everything identical).  I also find that, despite the larger memory, I get OOM errors if I increase the batch size (`-nb` switch) on TPU where the GPU can handle up to a batch size of 10.

Here are the outputs:
[xla_metrics.txt](https://github.com/pytorch/xla/files/3852784/xla_metrics.txt)
[xla_save_tensors.txt](https://github.com/pytorch/xla/files/3852785/xla_save_tensors.txt)

**Comment by dlibenzi** [comment]
Hmm, it is recompiling, but I see `aten::std` and we do override that.
Also I don't see the metric about the graph size, which suggests me you are running older wheels?

**Comment by hrbigelow** [comment]
Yes, they probably are old.  Apologies for that, this is actually my first time using Colab, and I'm not very familiar with ipython, pip, or the mechanics of wheels either.  Is there a link you have to a Colab workspace that uses up-to-date torch_xla environment?

I derived the linked environment from [here](https://colab.research.google.com/github/pytorch/xla/blob/master/contrib/colab/mnist-training-xrt-1-15.ipynb), in which you can see they initialize it with the wheels.

**Comment by dlibenzi** [comment]
They might not be that old in general terms, but at the pace changes happen on this project, they end up being such :smile: 
The first two cells on the Colab we have as examples, could bring newer code:

https://github.com/pytorch/xla/blob/master/contrib/colab/mnist-training-xrt-1-15.ipynb

We will also have soon instructions on how to have PyTorch/XLA Colabs setup with the most recent (nightly) wheels and XLA backend.

**Comment by hrbigelow** [comment]
Oh that's great!  I'll stay tuned.  So, in the meantime, when you mentioned that it is recompiling, how did you determine that from looking at the metrics file and save-tensors file?

**Comment by dlibenzi** [comment]
You can tell from a few things.
One is the ration between Compile and Execute metrics (TotalSamples).
The other one is the `UncachedSyncTensors` counter, which should not be increasing, or increasing at a very small fraction of the `CachedSyncTensors` one.

**Comment by hrbigelow** [comment]
Ahh cool, thanks.  So, I studied the save-tensors file and I couldn't see any difference in dimensions of any tensor from one training step to the next.  Any idea what else could be causing recompilation?  (It could be that there is something I missed - I have a pretty clunky diff-based technique I'm using)

**Comment by jysohn23** [comment]
By the way I've tried running your Colab but with nightly client and server-side. All I changed is the first cell variables (I'll update our notebooks with notes on how to update versions):

```
XRT_VERSION = "nightly"
DIST_BUCKET = "gs://tpu-pytorch/wheels"
TORCH_WHEEL = "torch-{}-cp36-cp36m-linux_x86_64.whl".format(XRT_VERSION)
TORCH_XLA_WHEEL = "torch_xla-{}-cp36-cp36m-linux_x86_64.whl".format(XRT_VERSION)
TORCHVISION_WHEEL = "torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl"
```

Then metrics show no `aten::std` though the CompileTime metric is increasing per step meaning there's probably some dynamic shape somewhere.

```
[MetricsData; step=9]
Metric: CompileTime
  TotalSamples: 92
  Accumulator: 02m44s963ms609.866us
  ValueRate: 820ms584.043us / second
  Rate: 0.725277 / second
  Percentiles: 1%=002ms356.538us; 5%=003ms584.632us; 10%=003ms802.884us; 20%=003ms169.099us; 50%=126ms519.035us; 80%=306ms917.096us; 90%=333ms746.688us; 95%=352ms848.011us; 99%=24s712ms913.329us
Metric: ExecuteTime
  TotalSamples: 108
  Accumulator: 03s486ms882.675us
  ValueRate: 034ms912.422us / second
  Rate: 1.05068 / second
  Percentiles: 1%=003ms604.211us; 5%=003ms833.113us; 10%=003ms234.253us; 20%=004ms688.599us; 50%=005ms697.710us; 80%=007ms572.513us; 90%=041ms820.624us; 95%=345ms836.768us; 99%=355ms89.606us
Metric: InboundData
  TotalSamples: 144
  Accumulator: 306.00B
  ValueRate: 2.98B / second
  Rate: 1.4012 / second
  Percentiles: 1%=1.00B; 5%=1.00B; 10%=1.00B; 20%=1.00B; 50%=1.00B; 80%=4.00B; 90%=4.00B; 95%=4.00B; 99%=4.00B
Metric: OutboundData
  TotalSamples: 246
  Accumulator: 149.07MB
  ValueRate: 1.44MB / second
  Rate: 2.37991 / second
  Percentiles: 1%=4.00B; 5%=4.00B; 10%=4.00B; 20%=1.00KB; 50%=138.00KB; 80%=736.00KB; 90%=736.00KB; 95%=1.00MB; 99%=9.00MB
Metric: ReleaseDataHandlesTime
  TotalSamples: 542
  Accumulator: 03s621ms653.045us
  ValueRate: 025ms495.861us / second
  Rate: 5.27302 / second
  Percentiles: 1%=555.972us; 5%=643.196us; 10%=702.115us; 20%=829.978us; 50%=001ms67.708us; 80%=002ms539.104us; 90%=002ms329.118us; 95%=004ms100.974us; 99%=162ms248.314us
Metric: SyncTensorsGraphSize
  TotalSamples: 109
  Accumulator: 148444.00
  ValueRate: 1438.01 / second
  Rate: 1.05591 / second
  Percentiles: 1%=6.00; 5%=6.00; 10%=36.00; 20%=88.00; 50%=175.00; 80%=268.00; 90%=340.00; 95%=13319.00; 99%=13415.00
Metric: TransferFromServerTime
  TotalSamples: 144
  Accumulator: 676ms119.100us
  ValueRate: 007ms579.019us / second
  Rate: 1.4012 / second
  Percentiles: 1%=001ms118.815us; 5%=001ms189.706us; 10%=001ms248.222us; 20%=001ms403.569us; 50%=002ms615.904us; 80%=002ms871.764us; 90%=002ms125.321us; 95%=027ms654.337us; 99%=110ms398.242us
Metric: TransferToServerTime
  TotalSamples: 246
  Accumulator: 01s108ms427.993us
  ValueRate: 011ms724.091us / second
  Rate: 2.38006 / second
  Percentiles: 1%=001ms331.787us; 5%=001ms474.341us; 10%=002ms662.753us; 20%=002ms898.652us; 50%=003ms700.081us; 80%=005ms882.035us; 90%=007ms559.970us; 95%=009ms971.110us; 99%=026ms18.950us
Counter: CachedSyncTensors
  Value: 17
Counter: CreateCompileHandles
  Value: 92
Counter: CreateDataHandles
  Value: 7637
Counter: CreateXlaTensor
  Value: 61364
Counter: DestroyDataHandles
  Value: 6997
Counter: DestroyXlaTensor
  Value: 60540
Counter: MarkStep
  Value: 10
Counter: ReleaseDataHandles
  Value: 6997
Counter: SyncTensorsToData
  Value: 1
Counter: UncachedSyncTensors
  Value: 92
Counter: XRTAllocateFromTensor_Empty
  Value: 30
Counter: XrtCompile_Empty
  Value: 1280
Counter: XrtExecuteChained_Empty
  Value: 1280
Counter: XrtExecute_Empty
  Value: 1280
Counter: XrtRead_Empty
  Value: 1280
Counter: XrtReleaseAllocationHandle_Empty
  Value: 1280
Counter: XrtReleaseCompileHandle_Empty
  Value: 1280
Counter: XrtSessionCount
  Value: 11
Counter: XrtSubTuple_Empty
  Value: 1280
Counter: aten::_local_scalar_dense
  Value: 144
Counter: xla::_log_softmax
  Value: 10
Counter: xla::_log_softmax_backward_data
  Value: 20
Counter: xla::_softmax
  Value: 10
Counter: xla::abs
  Value: 10
Counter: xla::add
  Value: 2750
Counter: xla::add_
  Value: 6182
Counter: xla::addcdiv_
  Value: 1970
Counter: xla::addcmul_
  Value: 1970
Counter: xla::addmm
  Value: 10
Counter: xla::alias
  Value: 70
Counter: xla::as_strided
  Value: 3200
Counter: xla::cat
  Value: 10
Counter: xla::clone
  Value: 1060
Counter: xla::convolution_backward_overrideable
  Value: 2710
Counter: xla::convolution_overrideable
  Value: 1380
Counter: xla::copy_
  Value: 8645
Counter: xla::div
  Value: 2030
Counter: xla::empty
  Value: 8150
Counter: xla::empty_strided
  Value: 1060
Counter: xla::eq
  Value: 90
Counter: xla::expand
  Value: 70
Counter: xla::fill_
  Value: 60
Counter: xla::gather
  Value: 19
Counter: xla::index_add_
  Value: 80
Counter: xla::index_select
  Value: 60
Counter: xla::max
  Value: 9
Counter: xla::mean
  Value: 38
Counter: xla::mm
  Value: 10
Counter: xla::mul
  Value: 1110
Counter: xla::mul_
  Value: 3940
Counter: xla::neg
  Value: 30
Counter: xla::permute
  Value: 40
Counter: xla::pow
  Value: 30
Counter: xla::relu
  Value: 110
Counter: xla::scatter_add_
  Value: 20
Counter: xla::select
  Value: 560
Counter: xla::sigmoid
  Value: 200
Counter: xla::sigmoid_backward
  Value: 400
Counter: xla::sign
  Value: 20
Counter: xla::slice
  Value: 8260
Counter: xla::sqrt
  Value: 1980
Counter: xla::squeeze
  Value: 5460
Counter: xla::std
  Value: 20
Counter: xla::sub
  Value: 10
Counter: xla::sum
  Value: 120
Counter: xla::t
  Value: 30
Counter: xla::tanh
  Value: 200
Counter: xla::tanh_backward
  Value: 400
Counter: xla::threshold_backward
  Value: 220
Counter: xla::transpose
  Value: 40
Counter: xla::unsqueeze
  Value: 5119
Counter: xla::view
  Value: 650
Counter: xla::zero_
  Value: 8537
```

Per the `aten::_local_scalar_dense` you might benefit from calling `.item()` on tensors only every N-steps. But looks like the biggest slowdown is from compiles. You can try diff graphs with the following command to try find where shapes may be changing:

```
cat /PATH/TO/FILE | xla/scripts/grab_graphs.py --graphdir=/PATH/TO/DIR > report.txt
```

**Comment by hrbigelow** [comment]
Thanks so much Jin Young.  I ran with the latest wheels using your snippet.  Looking at the output now.  I'll post what I learn.

**Comment by hrbigelow** [comment]
Hi Jin Young, so I see lots of the following (see below), each frame is growing by 7 more lines.  Is that bad?  Is the goal to eliminate all of the occurrences of '+' or '-' in the IR diffs?

```
  Frame 22 (len=114, count=1, id=37) vs 23 (len=121, count=1, id=38)
  --- frame-22
  +++ frame-23
  @@ -1,5 +1,8 @@
   IR {
     f32[] prim::Constant(), location=forward@wave_encoder.py:43, value=0
  +  f32[768]{0} xla::device_data(), location=forward@conv.py:202, device=TPU:0
  +  f32[768,768,1]{1,0,2} xla::device_data(), location=forward@conv.py:202, device=TPU:0
  +  f32[768,768,1,1]{3,2,1,0} aten::view(), location=forward@conv.py:202, output_size=(768, 768, 1, 1)
     f32[768]{0} xla::device_data(), location=forward@conv.py:202, device=TPU:0
     f32[768,768,3]{1,0,2} xla::device_data(), location=forward@conv.py:202, device=TPU:0
     f32[768,768,1,3]{3,2,1,0} aten::view(), location=forward@conv.py:202, output_size=(768, 768, 1, 3)
  @@ -109,6 +112,10 @@
     f32[4,768,1,15]{3,2,1,0} aten::convolution_overrideable(), location=forward@conv.py:202, stride=[1, 1], padding=[0, 0], dilation=[1, 1], transpose=0, output_padding=[0, 0], groups=1
     f32[4,768,15]{2,1,0} aten::squeeze(), location=forward@conv.py:202, dim=2
     f32[4,768,15]{2,1,0} aten::relu(), location=relu@functional.py:914
  +  f32[4,768,1,15]{3,2,1,0} aten::view(), location=forward@conv.py:202, output_size=(4, 768, 1, 15)
  +  f32[4,768,1,15]{3,2,1,0} aten::convolution_overrideable(), location=forward@conv.py:202, stride=[1, 1], padding=[0, 0], dilation=[1, 1], transpose=0, output_padding=[0, 0], groups=1
  +  f32[4,768,15]{2,1,0} aten::squeeze(), location=forward@conv.py:202, dim=2
  +  f32[4,768,15]{2,1,0} aten::relu(), location=relu@functional.py:914
     f32[] aten::sum(), location=forward@wave_encoder.py:43, dimensions=[0, 1, 2], keep_reduced_dimensions=0, dtype=-1
     pred[] aten::eq(), location=forward@wave_encoder.py:43, ROOT=0
   }
```

The code around `wave_encoder.py:43` looks like this:

```python
    def forward(self, x):
        '''
        B, C, T = n_batch, n_in_chan, n_win
        x: (B, C, T)
        '''
        pre = self.conv(x)
        # out = self.bn(out)
        act = self.relu(pre)
        if self.do_res:
            act[...] += x[:,:,self.residual_offsets[0]:self.residual_offsets[1] or None]
            # act += x[:,:,self.residual_offsets[0]:self.residual_offsets[1] or None]
=>43    if act.sum().eq(0.0):
            print('encoder layer {}: {}'.format(self.name, act.sum()))
        #print('bias mean: {}'.format(self.conv.bias.mean()))
        return act
```

To explain, there are 20 of these modules, all linked up in a torch.nn.Sequential.  Each one is a convolution, followed by a relu, followed by an optional residual connection.  The convolutions are not padded, so the outputs are getting smaller at each step.  That's why the residual connection line takes a slice of `x` rather than the full x.

However, for each of these 20 modules, the self.do_res flag is the same at each timestep, and the self.residual_offsets[] values are also the same.  So, the geometries of the tensors involved should not be changing between timesteps.

But, is this kind of branching during a `forward()` call also a problem, even if the branch is the same each time?

Thanks again!

Henry

**Comment by jysohn23** [comment]
Yes, the goal is not necessarily to remove all diffs (i.e. have a single graph for entire training), but to eventually converge on a couple of unique graphs so that we can hit the compilation cache consistently once training stabilizes on those graphs.

Thanks for explaining your use case. From what I can tell, I don't think this type of branching should cause a problem since you say that the branching behavior is consistent throughout training.

Looking at the graph diffs I posted it looks like your graphs are consistently growing by 15 lines towards the end (411 vs 412, 412 vs 413, and so on) all seemingly due to that branch depending on `self.do_res` in `ConvReLURes.forward`. 

I'd try to do 2 things:
* Setting `self.do_res = False` artificially and seeing whether that reduces compiles.
* Printing the shapes of `act` and `x[:,:,self.residual_offsets[0]:self.residual_offsets[1] or None]` to see if those consistently change.

**Comment by hrbigelow** [comment]
Yes, in fact I did try that but nothing much changed.  One interesting thing though:

```python
        pre = self.conv(x)
        # out = self.bn(out)
        act = self.relu(pre)
        if self.do_res:
            act[...] += x[:,:,self.residual_offsets[0]:self.residual_offsets[1] or None]
            # act += x[:,:,self.residual_offsets[0]:self.residual_offsets[1] or None]
=>      # if act.sum().eq(0.0):
=>      #    print('encoder layer {}: {}'.format(self.name, act.sum()))
        #print('bias mean: {}'.format(self.conv.bias.mean()))
        return act
```

Commenting out the two above lines changes the graph structure drastically.

With those lines active:
```python
=>      if act.sum().eq(0.0):
=>         print('encoder layer {}: {}'.format(self.name, act.sum()))
```
```
Parsed 175 graph(s)
3 frame group(s)
Frame has 144 graph(s) (135 unique):
  forward (/content/ae-wavenet/wave_encoder.py:43)
Frame has 16 graph(s) (16 unique):
  mark_step (/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py:372)
Frame has 15 graph(s) (1 unique):
  print_metrics (/content/ae-wavenet/netmisc.py:35)
```

Removing them:
```python
=>      # if act.sum().eq(0.0):
=>      #    print('encoder layer {}: {}'.format(self.name, act.sum()))
```
I get:
```
Parsed 27 graph(s)
2 frame group(s)
Frame has 14 graph(s) (14 unique):
  mark_step (/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py:372)
Frame has 13 graph(s) (1 unique):
  print_metrics (/content/ae-wavenet/netmisc.py:35)
```

Any thoughts?  Perhaps this is very bad because in this case, there very well could be an extra tensor at any time, depending on the sum.  But, I'm still not sure why this would mess things up.

Can you maybe give a hint what a Frame and a Frame Group are?

**Comment by hrbigelow** [comment]
Okay, I've done some more inspection.  One pattern that occurs in my code is the following dynamic trimming sort of operation:

original x, (rows are samples in the batch)
```
--************-
************---
---************
-************--
```

```python
# the variable 'trim' is dynamically computed at each iteration.
# in the above example, trim[] = [ [2, 1], [0, 3], [3, 0], [1, 2] ]
# but, in general will be different at each iteration
for b in range(batch_size):
    beg, end = trim[b]
    x_trim[b,...] = x[b,beg:end]
```

The reason for this odd-looking code is that I have an autoregressive model with downsampling and upsampling convolutions, and that introduces different phases for intermediate calculations.  In order to mitigate using different sized tensors, I first take a bit more, and then trim as appropriate, and re-pack.

So, is there any way to coax torch_xla to treat this as one graph?

The IR diffs induced by this section of code are below, and I can see that the only difference between the '+' and '-' line is the differing value of 'start' and 'end' arguments.

```
  Frame 12 (len=12690, count=1, id=24) vs 13 (len=12690, count=1, id=26)
  --- frame-12
  +++ frame-13
  @@ -181,25 +181,25 @@
     f32[1,128,2628]{2,1,0} xla::generic_slice(), location=forward@wavenet.py:329, base_indices=(3, 0, 0), sizes=(1, 128, 2628)
     f32[128,2628]{1,0} aten::view(), location=forward@wavenet.py:329, output_size=(128, 2628)
     f32[128,2628]{1,0} xla::select(), location=forward@wavenet.py:329, dim=0, start=0, end=128, stride=1
  -  f32[128,2146]{1,0} xla::select(), location=forward@wavenet.py:329, dim=1, start=262, end=2408, stride=1
  +  f32[128,2146]{1,0} xla::select(), location=forward@wavenet.py:329, dim=1, start=382, end=2528, stride=1
     f32[128,2146]{1,0} aten::view(), location=forward@wavenet.py:329, output_size=(128, 2146)
     f32[1,128,2146]{2,1,0} aten::view(), location=forward@wavenet.py:194, output_size=(1, 128, 2146)
     f32[1,128,2628]{2,1,0} xla::generic_slice(), location=forward@wavenet.py:329, base_indices=(2, 0, 0), sizes=(1, 128, 2628)
     f32[128,2628]{1,0} aten::view(), location=forward@wavenet.py:329, output_size=(128, 2628)
     f32[128,2628]{1,0} xla::select(), location=forward@wavenet.py:329, dim=0, start=0, end=128, stride=1
  -  f32[128,2146]{1,0} xla::select(), location=forward@wavenet.py:329, dim=1, start=262, end=2408, stride=1
  +  f32[128,2146]{1,0} xla::select(), location=forward@wavenet.py:329, dim=1, start=302, end=2448, stride=1
     f32[128,2146]{1,0} aten::view(), location=forward@wavenet.py:329, output_size=(128, 2146)
     f32[1,128,2146]{2,1,0} aten::view(), location=forward@wavenet.py:194, output_size=(1, 128, 2146)
     f32[1,128,2628]{2,1,0} xla::generic_slice(), location=forward@wavenet.py:329, base_indices=(1, 0, 0), sizes=(1, 128, 2628)
     f32[128,2628]{1,0} aten::view(), location=forward@wavenet.py:329, output_size=(128, 2628)
     f32[128,2628]{1,0} xla::select(), location=forward@wavenet.py:329, dim=0, start=0, end=128, stride=1
  -  f32[128,2146]{1,0} xla::select(), location=forward@wavenet.py:329, dim=1, start=302, end=2448, stride=1
  +  f32[128,2146]{1,0} xla::select(), location=forward@wavenet.py:329, dim=1, start=462, end=2608, stride=1
     f32[128,2146]{1,0} aten::view(), location=forward@wavenet.py:329, output_size=(128, 2146)
     f32[1,128,2146]{2,1,0} aten::view(), location=forward@wavenet.py:194, output_size=(1, 128, 2146)
     f32[1,128,2628]{2,1,0} xla::generic_slice(), location=forward@wavenet.py:329, base_indices=(0, 0, 0), sizes=(1, 128, 2628)
     f32[128,2628]{1,0} aten::view(), location=forward@wavenet.py:329, output_size=(128, 2628)
     f32[128,2628]{1,0} xla::select(), location=forward@wavenet.py:329, dim=0, start=0, end=128, stride=1
  -  f32[128,2146]{1,0} xla::select(), location=forward@wavenet.py:329, dim=1, start=222, end=2368, stride=1
  +  f32[128,2146]{1,0} xla::select(), location=forward@wavenet.py:329, dim=1, start=242, end=2388, stride=1
     f32[128,2146]{1,0} aten::view(), location=forward@wavenet.py:329, output_size=(128, 2146)
     f32[1,128,2146]{2,1,0} aten::view(), location=forward@wavenet.py:194, output_size=(1, 128, 2146)
     f32[] prim::Constant(), location=forward@wavenet.py:324, value=0
```

**Comment by dlibenzi** [comment]
Yes, that is expected.
By printing values, you trigger the graph execution (which is then dumped into the graph file) in order to extract the Python scalar to print.
Printing within a model execution should be done minimally, only after a given number of steps, and trying not to print things within a loop.

**Comment by hrbigelow** [comment]
Hmm.  So, can you let me know if the following description is accurate.  I'm just trying to understand this conceptually.

When you say that printing triggers graph execution -- let's say I instead accumulate the values in a separate tensor at each step.  Is it that execution will be triggered in a lazy, possibly out-of-order fashion?

If I use that approach of accumulating these metrics in a tensor and only printing that tensor after 10 or 100 steps, let's say, would there be fewer unique graphs (or frames)?  Or is the problem merely the forcing of execution due to printing?

**Comment by dlibenzi** [comment]
If you keep them as tensor, and print them after N steps, it is OK.
The `item()` call triggers an exit from the *Tensor World* to the *Python Scalar World*, which means we have to materialize the IR value rooted at the tensor which is source of the `item()` call.

This is one example we use in our tests:

https://github.com/pytorch/xla/blob/c654169b188b97c518de19cf4ce7f558c39885ac/test/test_train_mp_mnist.py#L125

**Comment by dlibenzi** [comment]
I am closing this one, as we chatted about the `torch.take()` in the other issue as well.
To solve this nicely we will have to wait for the dynamic `torch.narrow()`.
