### ISSUE TITLE
Proper way to create copies of models for xmp.spawn?

### ISSUE THREAD

**Issue by hrbigelow** [pytorch/xla#1390]
## ❓ Questions and Help

I notice from [here](https://github.com/pytorch/xla/blob/d3096b1eda5720b2637ebee70e1c7448875b27ad/test/test_train_mp_mnist.py#L111) that the `MNIST()` constructor is called once per spawned process.  This seems to imply that, if you were creating these models using random weight initialization, then care must be taken to actually get identical models.

What is the recommended practice?  Do people just use a copy.deepcopy, or is there something more "torch"-like?

Thanks!

**Comment by jysohn23** [comment]
Typically we set the seed like we did [here](https://github.com/pytorch/xla/blob/d3096b1eda5720b2637ebee70e1c7448875b27ad/test/test_train_mp_mnist.py#L58) another example [here](https://github.com/huggingface/transformers/blob/master/examples/run_glue.py#L73), which is enough to guarantee same initialization of weight as long as its done close to actual initialization. If you start branching differently between processes from the time of setting the seed and initializing the weights, the weights may be different.

**Comment by hrbigelow** [comment]
Ahh I see, I missed that.  Thanks very much Jin Young!

**Comment by jysohn23** [comment]
Feel free to open if you have other questions, but closing for now.
