### ISSUE TITLE
Should CPU constants be ported to tensors to prevent IR recompilation?

### ISSUE THREAD

**Issue by hrbigelow** [pytorch/xla#1398]
## ❓ Questions and Help

I have various constructs in my code like:

```python
rec_loss = - log_pred_target.mean()
ze_norm = (self.bottleneck.ze ** 2).sum(dim=1).sqrt()
norm_loss = self.norm_gamma * torch.abs(ze_norm - 1.0).mean()
total_loss = rec_loss + norm_loss
```

Would moving the `2` and `1.0` constants from CPU to scalar TPU tensors improve anything or will this be cached efficiently in the IR graph?

**Comment by dlibenzi** [comment]
The current policy WRT constants (we actually don't know whether they are rally invariant across training steps), is that 0 and 1 gets expanded to graph constants, and every other one becomes a tensor on device.
The rationale is, we want to let the compiler to see 0 and 1 (which are more likely to be real invariants) as constant, so optimization passes can simplify, while we want the others to become device data, so the graph will not change if the "constant" is.
