### ISSUE TITLE
Depthwise Convolution not faster than traditional Convolution on Google Colab

### ISSUE THREAD

**Issue by thanhhvnqb** [pytorch/xla#1430]
## 🐛 Bug

The training and testing speed of Network using Depthwise Convolution is not faster than traditional Convolution on Google Colab.

## To Reproduce

I modified the ResNet18 training example from https://github.com/pytorch/xla/blob/master/contrib/colab/resnet18-training-xrt-1-15.ipynb
to have a bigger Network which uses Depthwise Convolution or traditional Convolution.
The notebook I use is public at https://colab.research.google.com/drive/1xlY0XdLUp44XJ5d3YJEbSzAY6Eh1UXb-

## Environment
- Google Colab with TPU runtime.
- Lastest version of Pytorch xla

Log files:
[Colab-TPU-DWConv.log](https://github.com/pytorch/xla/files/3900196/Colab-TPU-DWConv.log)
[Colab-TPU-TraditionalConv.log](https://github.com/pytorch/xla/files/3900197/Colab-TPU-TraditionalConv.log)

**Comment by dlibenzi** [comment]
How much DW Conv helps depends on the model, but if you enable `metrics_debug` and report the logs, we can get a better idea.

**Comment by thanhhvnqb** [comment]
Here is the log when metrics_debug is enabled. But I cannot understand the debug log ^^.

[dw_conv_metrics_debug.log](https://github.com/pytorch/xla/files/3903955/dw_conv_metrics_debug.log)
[vanilla_conv_metrics_debug.log](https://github.com/pytorch/xla/files/3903956/vanilla_conv_metrics_debug.log)

**Comment by dlibenzi** [comment]
If you look at the ExecuteTime, they look similar, with one exception.
The Accumulator is almost double in the vanilla run, which means there is some outlier escaping the 99%.
Also the training time you print for the DW has much lower stddev.
I would run as single core, to get more stable numbers, but from what I can see here, the core TPU execute time will be very close for the two implementations.

**Comment by thanhhvnqb** [comment]
I rerun the code with single core and used as many DWConv as possible.
I don't know why now the training time of DWConv is much longer.
I found out that the running time of both networks is similar.
Can you tell me where is the value I need to focus to know that DWConv is faster than Vanilla Conv?

[dw_conv_metrics_debug.log](https://github.com/pytorch/xla/files/3906698/dw_conv_metrics_debug.log)
[vanilla_conv_metrics_debug.log](https://github.com/pytorch/xla/files/3906699/vanilla_conv_metrics_debug.log)

**Comment by dlibenzi** [comment]
Now `ExecuteTime` and `TransferToServerTime` are the ones standing out (in worse) in the DW run.
I confirmed that DW is about 12 times slower (look at the Rate being printed).
Also both metrics listed above are bad.
While `ExecuteTime` could be explained with some bad lowering, the `TransferToServerTime` is strange. I suspected we would be swapping host<->device memory, but lowered the batch size to 64 and this is till happening.
We need to look closer at this, as with this feature count, DW should be at the very least as performing as normal convolutions.

**Comment by dlibenzi** [comment]
We are looking into fixing this issue on the XLA side.

**Comment by dlibenzi** [comment]
Hi!
We have made changes that sped up grouped convs 13x.
You can check them out on nightly builds.

**Comment by dlibenzi** [comment]
This should be fixed now.
