### ISSUE TITLE
How to use a specific commit of pytorch-xla in Colab?

### ISSUE THREAD

**Issue by hrbigelow** [pytorch/xla#1447]
## ❓ Questions and Help

Hi,

I'm eager to use a specific commit (or the latest) in Colab.  My current setup is this cell:

```bash
XRT_VERSION = "nightly"
DIST_BUCKET = "gs://tpu-pytorch/wheels"
TORCH_WHEEL = "torch-{}-cp36-cp36m-linux_x86_64.whl".format(XRT_VERSION)
TORCH_XLA_WHEEL = "torch_xla-{}-cp36-cp36m-linux_x86_64.whl".format(XRT_VERSION)
TORCHVISION_WHEEL = "torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl"

# Update TPU XRT version
import os
import requests
import threading
def update_server_xrt():
  print("Updating server-side XRT...")
  url = 'http://{TPU_ADDRESS}:8475/requestversion/{XRT_VERSION}'.format(
      TPU_ADDRESS=os.environ['COLAB_TPU_ADDR'].split(':')[0],
      XRT_VERSION=XRT_VERSION,
  )
  print("Done updating server-side XRT: {}".format(requests.post(url)))

update = threading.Thread(target=update_server_xrt)
update.start()

# Install Colab TPU compat PyTorch/TPU wheels and dependencies
!pip uninstall -y torch torchvision
!gsutil cp "$DIST_BUCKET/$TORCH_WHEEL" .
!gsutil cp "$DIST_BUCKET/$TORCH_XLA_WHEEL" .
!gsutil cp "$DIST_BUCKET/$TORCHVISION_WHEEL" .
!pip install "$TORCH_WHEEL"
!pip install "$TORCH_XLA_WHEEL"
!pip install "$TORCHVISION_WHEEL"
!sudo apt-get install libomp5
update.join()
```

But that only gets the nightly version.  Is there some way to name a specific commit?

**Comment by jysohn23** [comment]
Unfortunately, we only build and publish our wheels and the server-side binary on a nightly cadence. Is is possible for your use-case to just use the nightly published versions?

**Comment by hrbigelow** [comment]
Hi Jin Young, unfortunately not in this case because it hangs due to #1443.  Would it be possible for me to build a wheel from HEAD and install it that way?  Or does it need to be hosted on a special server?

**Comment by jysohn23** [comment]
So per https://github.com/pytorch/xla/pull/1444 which was just checked in, this fix should show up in tomorrow's nightlies. You could also build the wheels yourself from HEAD and install them on Colab, as long as the APIs haven't changed between Client VM (Colab runtime) and Server (TPU VM) side.

**Comment by hrbigelow** [comment]
Awesome!  Thanks @jysohn23 I'll try that.  Is there any special advice for building a wheel from the torch-xla codebase?  I have never built a wheel before.

**Comment by jysohn23** [comment]
This [guide](https://github.com/pytorch/xla/blob/master/CONTRIBUTING.md) should have some instructions on how to build from source. Also you can try use this [script](https://github.com/pytorch/xla/blob/master/scripts/build_torch_wheels.sh) or read it and follow the steps inside it. It'll take quite a while to build so we recommend using a machine with 10+ cores if possible.

**Comment by hrbigelow** [comment]
Great, thanks so much!  Will try.  I have a i7-8750 laptop, which has 12 cores.

**Comment by hrbigelow** [comment]
Hi @jysohn23 I did:

```bash
$ git clone --recursive https://github.com/pytorch/pytorch
$ cd pytorch
$ git clone --recursive https://github.com/pytorch/xla.git
$ ./xla/scripts/build_torch_wheels.sh
```

It ran for a couple hours, and then I got this error:

```
clang++-7 -pthread -shared -B /home/henry/anaconda3/envs/pytorch/compiler_compat -L/home/henry/anaconda3/envs/pytorch/lib -Wl,-rpath=/home/henry/anaconda3/envs/pytorch/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/home/henry/ai/pytorch/vision/torchvision/csrc/vision.o build/temp.linux-x86_64-3.6/home/henry/ai/pytorch/vision/torchvision/csrc/cpu/PSROIAlign_cpu.o build/temp.linux-x86_64-3.6/home/henry/ai/pytorch/vision/torchvision/csrc/cpu/ROIAlign_cpu.o build/temp.linux-x86_64-3.6/home/henry/ai/pytorch/vision/torchvision/csrc/cpu/ROIPool_cpu.o build/temp.linux-x86_64-3.6/home/henry/ai/pytorch/vision/torchvision/csrc/cpu/nms_cpu.o build/temp.linux-x86_64-3.6/home/henry/ai/pytorch/vision/torchvision/csrc/cpu/PSROIPool_cpu.o -o build/lib.linux-x86_64-3.6/torchvision/_C.so
building 'torchvision.video_reader' extension
creating build/temp.linux-x86_64-3.6/home/henry/ai/pytorch/vision/torchvision/csrc/cpu/video_reader
clang-7 -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/henry/ai/pytorch/vision/torchvision/csrc/cpu/video_reader -I/usr/include -I/home/henry/ai/pytorch/vision/torchvision/csrc -I/home/henry/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include -I/home/henry/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/henry/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/TH -I/home/henry/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/THC -I/home/henry/anaconda3/envs/pytorch/include/python3.6m -c /home/henry/ai/pytorch/vision/torchvision/csrc/cpu/video_reader/VideoReader.cpp -o build/temp.linux-x86_64-3.6/home/henry/ai/pytorch/vision/torchvision/csrc/cpu/video_reader/VideoReader.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=video_reader -D_GLIBCXX_USE_CXX11_ABI=1
In file included from /home/henry/ai/pytorch/vision/torchvision/csrc/cpu/video_reader/VideoReader.cpp:6:
In file included from /home/henry/ai/pytorch/vision/torchvision/csrc/cpu/video_reader/FfmpegDecoder.h:6:
/home/henry/ai/pytorch/vision/torchvision/csrc/cpu/video_reader/FfmpegHeaders.h:4:10: fatal error: 'libavcodec/avcodec.h' file not found
#include <libavcodec/avcodec.h>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
error: command 'clang-7' failed with exit status 1
henry@henry-gs65:pytorch$ locate avcodec.h
/home/henry/miniconda3/envs/pytorch/include/libavcodec/avcodec.h
/home/henry/miniconda3/envs/tensorflow/include/libavcodec/avcodec.h
/home/henry/miniconda3/envs/tensorflow/include/libavfilter/avcodec.h
/home/henry/miniconda3/pkgs/ffmpeg-2.8.6-hf82bc7d_7/include/libavcodec/avcodec.h
/home/henry/miniconda3/pkgs/ffmpeg-2.8.6-hf82bc7d_7/include/libavfilter/avcodec.h
/home/henry/miniconda3/pkgs/ffmpeg-4.0-hcdf2ecd_0/include/libavcodec/avcodec.h
/home/henry/miniconda3/pkgs/ffmpeg-4.1-h6dce934_1000/include/libavcodec/avcodec.h
```

Would you have any advice by chance?

**Comment by jysohn23** [comment]
Hmmm, what OS are you using? I've only tried that script from a Debian 9 distro (not entirely sure if it'd make that difference).

**Comment by dlibenzi** [comment]
Maybe?
```Shell
apt-get install libavcodec-dev
```

**Comment by hrbigelow** [comment]
Cool, I installed libavcodec-dev.  (I'm using ubuntu 18.04, kernel 4.15.0).  Recompiling now.

**Comment by hrbigelow** [comment]
Hi @jysohn23 @dlibenzi 

I'm still seeing the #1443  recursion error after installing nightly just now.  Has the bug fix been incorporated into the nightly wheel that is available in Colab through this snippet, or do I need to specify something different?

```
XRT_VERSION = "nightly"
DIST_BUCKET = "gs://tpu-pytorch/wheels"
TORCH_WHEEL = "torch-{}-cp36-cp36m-linux_x86_64.whl".format(XRT_VERSION)
TORCH_XLA_WHEEL = "torch_xla-{}-cp36-cp36m-linux_x86_64.whl".format(XRT_VERSION)
 ```

**Comment by zcain117** [comment]
Our latest nightly failed to build :( 
One of our dependencies is down. They are aware of the issue and supposedly just submitted a fix. I'll retry to build our nightly now

Error was:
> Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/66be6c76fc01.tar.gz, https://bitbucket.org/eigen/eigen/get/66be6c76fc01.tar.gz] to /root/.cache/bazel/_bazel_root/df10a46af757c9817bc8ced472071f03/external/eigen_archive/66be6c76fc01.tar.gz: All mirrors are down: [Checksum was e9753df25d9582fe909fd0a4709fa9a4e55051d37a33f08d06649fe14d10c7f5 but wanted 6d8ed482addd14892d7b0bd98fec2c02f18fdab97775bda68c3f2a99ffb190fb, GET returned 404 Not Found] and referenced by '//third_party/eigen3:eigen3'

**Comment by hrbigelow** [comment]
Ahh okay.  No problem, please let me know when the build succeeds, I'm eager to try it.  As an aside, I'm using my own built wheel and seeing a bizarre new bug, but I'm not sure if it is a problem with API versions or something.  I submitted a bug issue #1451.  

By the way, @jysohn23 I have been using your snippet:

```
import os
import requests
import threading
def update_server_xrt():
  print("Updating server-side XRT...")
  url = 'http://{TPU_ADDRESS}:8475/requestversion/{XRT_VERSION}'.format(
      TPU_ADDRESS=os.environ['COLAB_TPU_ADDR'].split(':')[0],
      XRT_VERSION=XRT_VERSION,
  )
  print("Done updating server-side XRT: {}".format(requests.post(url)))

update = threading.Thread(target=update_server_xrt)
update.start()

# install things
update.join()
```

and in the cell output, the first thing I see is:

```
Updating server-side XRT...
Done updating server-side XRT: <Response [404]>
```

Does this mean the command is failing?

**Comment by jysohn23** [comment]
@hrbigelow Yes that command is failing. Oh better than that snippet you could just copy paste the setup cell in our colab notebooks: https://github.com/pytorch/xla/blob/master/contrib/colab/mnist-training-xrt-1-15.ipynb.

**Comment by hrbigelow** [comment]
Cool, thanks I've updated it

**Comment by zcain117** [comment]
The nightly build succeeded - I think it should be ready to use

**Comment by hrbigelow** [comment]
Great, thanks @zcain117 I used it last night and it worked as expected.

**Comment by jysohn23** [comment]
@hrbigelow Closing the issue, but feel free to reopen at any time if you face additional issues!

**Comment by AdityaSoni19031997** [comment]
What's the setup procedure if we are on non-colab GCP Env?

**Comment by jysohn23** [comment]
If you're using a fairly recent GCE VM image we created, you should be able to run the script `scripts/update_nightly_torch_wheels.sh`. In the VM it should be in `/usr/share/torch-xla-nightly/pytorch/xla/scripts/update_nightly_torch_wheels.sh`.
