### ISSUE TITLE
pytorch/xla vs TF

### ISSUE THREAD

**Issue by bkkaggle** [pytorch/xla#1490]
## ❓ Questions and Help

Hi, is training a model with pytorch xla slower than training a model with tf? Are there any other limitations to using pytorch/xla compared to TF?

**Comment by mruberry** [comment]
Hi @bkkaggle!

Thanks for your question. We haven't done a thorough study of the performance differences of TPU training with PyTorch vs. with TensorFlow. Some networks may run faster with PyTorch, and some networks might run faster with TensorFlow.

Ultimately I think the choice between using PyTorch or TensorFlow is about which framework you're more comfortable with.
