### ISSUE TITLE
When the amount of data is large, multi-processing consumes a large amount of memory

### ISSUE THREAD

**Issue by Lisennlp** [pytorch/xla#1513]
## ❓ Questions and Help

I followed the [multiprocess instructions ](https://github.com/pytorch/xla/blob/master/API_GUIDE.md)to modify my own code, data greater than 320,000, ran multiprocess training, found 128 GB of memory is not enough to support my training, may need more than 400 GB of memory to be enough, torch-xla-nighlty multi-process is not each process to copy all the data? Can't you send different data to each process?

**Comment by dlibenzi** [comment]
Hi!
What is this 320000? Bytes? Samples?
Which data loader do you use?

**Comment by zcain117** [comment]
Here is an example where we send different data to each process: https://github.com/pytorch/xla/blob/master/test/test_train_mp_imagenet.py#L145.

Also- when you say 128G memory is not enough, are you referring to   8 TPU cores * 16 GB per core  and you're seeing HBU OOM errors? Or is this 128G on the VM in GCE?

**Comment by Lisennlp** [comment]
@zcain117 Sorry, I didn't make myself clear. I was talking about GCE memory

**Comment by Lisennlp** [comment]
@dlibenzi The data size is about 7Gb,  The part of the code for the loader is as follows： 

   import torch_xla.distributed.parallel_loader as pl

   my_dataloader = MyDataloader(train_dataset)

    if xm.xrt_world_size() > 1:
        train_sampler = torch.utils.data.distributed.DistributedSampler(my_dataloader,
                                                                        num_replicas=xm.xrt_world_size(),
                                                                        rank=xm.get_ordinal())
    train_dataloader = torch.utils.data.DataLoader(
        train_dataloaders,
        batch_size=args.train_batch_size,
        sampler=train_sampler,
        drop_last=True,
        shuffle=False if train_sampler else True,
        num_workers=8)

    .......
        for epoch in range(1, int(args.num_train_epochs) + 1, 1):
        start = time.time()
        para_loader = pl.ParallelLoader(train_dataloader, [device])
        tpu_training_loop(para_loader.per_device_loader(device))
        end = time.time()
        xm.master_print('Finished training epoch {}, takes time {}'.format(epoch, end-start))

**Comment by dlibenzi** [comment]
I am not sure what "my_dataloader" does, but if it tries to slurp all the samples in, by 8 processes, it can be a problem.
Just to verify, can you use just one core (pass `xprocs=1` to `xmp.spawn()`)?

**Comment by dlibenzi** [comment]
You could also try to print the CPU tensors memory size with something like this:

```Python
import gc
import torch
import re

def get_tensors_memory(devrx):
  memory_size = 0
  accounted = set()
  for obj in gc.get_objects():
    if not torch.is_tensor(obj):
      continue
    if not re.match(devrx, str(obj.device)):
      continue
    storage = obj.storage()
    data_ptr = storage.data_ptr()
    if data_ptr in accounted:
      continue
    accounted.add(data_ptr)

    element_size = storage.element_size()
    memory_size += storage.size() * storage.element_size()
  return memory_size
```

And:
```Python
print(get_tensors_memory(r'cpu:?.*'))
```

Mind, for 8 cores there are 8 processes, so account from all of them.

**Comment by Lisennlp** [comment]
@dlibenzi I took a closer look at my dataloader and found that it was possible to duplicate eight pieces of data, causing the multiprocess to have too much memory, so I modified my dataloader to fix the problem. But there is still the problem of growing memory, which thankfully is growing more slowly than before. I used 1/3 data, about 2.3 G. However, for every 20 steps, GCE's total memory always increased by 100 M. Plus, it's odd that I need more than 200 G of GCE memory for all the 7 G of data I'm using. By the way you gave me that, I got the CPU's tensor size, which has been stable at 673309244 bytes. It's strange why the GCE memory keeps growing.

**Comment by dlibenzi** [comment]
Can you try single core (like I mentioned above)?

**Comment by Lisennlp** [comment]
> Can you try single core (like I mentioned above)?

@dlibenzi Well, I tried a single core run, but there was still a constant increase in memory, about 100 M per 160 steps, which equates to 20 steps for an 8 core run. And the total GCE memory dropped from 200 GB to 22 GB.

**Comment by Lisennlp** [comment]
@dlibenzi The following is the GCE memory change for each line of code that I analyzed using a single core (66 total batch, or 66 steps) . You can see that the memory has grown once from the batch data loader (line 363) , then at the end of the for loop, the program frees up some memory (line 395) , but adds about 40 MB overall, that is, 40 M in 66 steps, the equivalent of 20 batches of eight cores (160 total steps) adds about 100 M of Memory (160 / 66 * 4096.9 M) . That's the problem, but why wasn't all the memory released at the end?

Line #    Mem usage    Increment   Line Contents
================================================
   358   1931.2 MiB   1931.2 MiB       @profile
   359                                 def tpu_training_loop(loader):
   360   1931.2 MiB      0.0 MiB           tracker = xm.RateTracker()
   361   1931.2 MiB      0.0 MiB           model.train()
   362   1931.2 MiB      0.0 MiB           tr_loss = None
   363   2272.5 MiB    341.4 MiB           for step, data in enumerate(loader):
   364   2272.5 MiB      0.0 MiB               optimizer.zero_grad()
   365   2272.5 MiB      0.0 MiB               input_ids, input_mask, segment_ids, position_ids, answer_ids, answer_mask = data
   366                                         # print(f'step = {step}, input_ids = {input_ids}')
   367   2272.5 MiB      0.0 MiB               log_prob, _ = model(input_ids,
   368   2272.5 MiB      0.0 MiB                                   segment_ids,
   369   2272.5 MiB      0.0 MiB                                   input_mask,
   370   2272.5 MiB      0.0 MiB                                   position_ids,
   371   2272.5 MiB      0.0 MiB                                   answer_ids=answer_ids,
   372   2278.5 MiB      6.0 MiB                                   answer_mask=answer_mask)
   373   2278.8 MiB      0.3 MiB               loss = criterion(log_prob, answer_ids[:, 1:].contiguous().view(-1))
   374   2283.2 MiB      4.4 MiB               loss.backward()
   375   2283.2 MiB      0.0 MiB               if args.gradient_accumulation_steps > 1:
   376                                             loss = loss / args.gradient_accumulation_steps
   377   2283.2 MiB      0.0 MiB               tr_loss = loss * args.gradient_accumulation_steps if step == 0 else tr_loss + loss * arg
s.gradient_accumulation_steps
   378   2283.2 MiB      0.0 MiB               if (step + 1) % args.gradient_accumulation_steps == 0:
   379   2244.3 MiB      0.0 MiB                   xm.optimizer_step(optimizer)
   380   2244.3 MiB      0.0 MiB                   optimizer.zero_grad()
   381   2244.3 MiB      0.0 MiB               tracker.add(args.train_batch_size)
   382   2244.3 MiB      0.0 MiB               loss = tr_loss * (1 / (step + 1)) if step > 0 else tr_loss
   383   2244.3 MiB      0.0 MiB               if step % 1 == 0:
   384   2244.3 MiB      0.0 MiB                   xm.add_step_closure(_train_update, args=(device, step, loss, tracker))
   395   1973.4 MiB      0.0 MiB           return loss.item() / step


Next, we look at the second epoch and find that at the end of the loop, all memory is freed。

 Line #    Mem usage    Increment   Line Contents
================================================
   358   2768.6 MiB   2768.6 MiB       @profile
   359                                 def tpu_training_loop(loader):
   360   2768.6 MiB      0.0 MiB           tracker = xm.RateTracker()
   361   2768.6 MiB      0.0 MiB           model.train()
   362   2768.6 MiB      0.0 MiB           tr_loss = None
   363   2832.6 MiB     54.1 MiB           for step, data in enumerate(loader):
   364   2832.6 MiB      0.3 MiB               optimizer.zero_grad()
   365   2832.6 MiB      0.0 MiB               input_ids, input_mask, segment_ids, position_ids, answer_ids, answer_mask = data
   366                                         # print(f'step = {step}, input_ids = {input_ids}')
   367   2832.6 MiB      0.0 MiB               log_prob, _ = model(input_ids,
   368   2832.6 MiB      0.0 MiB                                   segment_ids,
   369   2832.6 MiB      0.0 MiB                                   input_mask,
   370   2832.6 MiB      0.0 MiB                                   position_ids,
   371   2832.6 MiB      0.0 MiB                                   answer_ids=answer_ids,
   372   2832.6 MiB      0.0 MiB                                   answer_mask=answer_mask)
   373   2832.6 MiB      0.0 MiB               loss = criterion(log_prob, answer_ids[:, 1:].contiguous().view(-1))
   374   2832.6 MiB      0.0 MiB               loss.backward()
   375   2832.6 MiB      0.0 MiB               if args.gradient_accumulation_steps > 1:
   376                                             loss = loss / args.gradient_accumulation_steps
   377   2832.6 MiB      0.0 MiB               tr_loss = loss * args.gradient_accumulation_steps if step == 0 else tr_loss + loss * args.gradient_accumulation_steps
   378   2832.6 MiB      0.0 MiB               if (step + 1) % args.gradient_accumulation_steps == 0:
   379   2832.6 MiB      0.2 MiB                   xm.optimizer_step(optimizer)
   380   2832.6 MiB      0.0 MiB                   optimizer.zero_grad()
   381   2832.6 MiB      0.0 MiB               tracker.add(args.train_batch_size)
   382   2832.6 MiB      0.0 MiB               loss = tr_loss * (1 / (step + 1)) if step > 0 else tr_loss
   383   2832.6 MiB      0.0 MiB               if step % 1 == 0:
   384   2832.6 MiB      0.0 MiB                   xm.add_step_closure(_train_update, args=(device, step, loss, tracker))
   385   2770.6 MiB      0.0 MiB           return loss.item() / step
  
The following is the GCE memory change for each line of code that I analyzed using a single core (66 total batch, or 66 steps) . You can see that the memory has grown once from the batch data loader (line 363) , then at the end of the for loop, the program frees up some memory (line 395) , but adds about 40 MB overall, that is, 40 mb in 66 steps, the equivalent of 20 batches of eight cores (160 total steps) adds about 100 mb of Memory (160 / 66 * 4096.9 mb) . That's the problem, but why wasn't all the memory released at the end?

Next, we look at the second epoch and find that at the end of the loop, almost all memory is freed

 Line #    Mem usage    Increment   Line Contents
================================================
   358   2768.6 MiB   2768.6 MiB       @profile
   359                                 def tpu_training_loop(loader):
   360   2768.6 MiB      0.0 MiB           tracker = xm.RateTracker()
   361   2768.6 MiB      0.0 MiB           model.train()
   362   2768.6 MiB      0.0 MiB           tr_loss = None
   363   2832.6 MiB     54.1 MiB           for step, data in enumerate(loader):
   364   2832.6 MiB      0.3 MiB               optimizer.zero_grad()
   365   2832.6 MiB      0.0 MiB               input_ids, input_mask, segment_ids, position_ids, answer_ids, answer_mask = data
   366                                         # print(f'step = {step}, input_ids = {input_ids}')
   367   2832.6 MiB      0.0 MiB               log_prob, _ = model(input_ids,
   368   2832.6 MiB      0.0 MiB                                   segment_ids,
   369   2832.6 MiB      0.0 MiB                                   input_mask,
   370   2832.6 MiB      0.0 MiB                                   position_ids,
   371   2832.6 MiB      0.0 MiB                                   answer_ids=answer_ids,
   372   2832.6 MiB      0.0 MiB                                   answer_mask=answer_mask)
   373   2832.6 MiB      0.0 MiB               loss = criterion(log_prob, answer_ids[:, 1:].contiguous().view(-1))
   374   2832.6 MiB      0.0 MiB               loss.backward()
   375   2832.6 MiB      0.0 MiB               if args.gradient_accumulation_steps > 1:
   376                                             loss = loss / args.gradient_accumulation_steps
   377   2832.6 MiB      0.0 MiB               tr_loss = loss * args.gradient_accumulation_steps if step == 0 else tr_loss + loss * args.gradient_accumulation_steps
   378   2832.6 MiB      0.0 MiB               if (step + 1) % args.gradient_accumulation_steps == 0:
   379   2832.6 MiB      0.2 MiB                   xm.optimizer_step(optimizer)
   380   2832.6 MiB      0.0 MiB                   optimizer.zero_grad()
   381   2832.6 MiB      0.0 MiB               tracker.add(args.train_batch_size)
   382   2832.6 MiB      0.0 MiB               loss = tr_loss * (1 / (step + 1)) if step > 0 else tr_loss
   383   2832.6 MiB      0.0 MiB               if step % 1 == 0:
   384   2832.6 MiB      0.0 MiB                   xm.add_step_closure(_train_update, args=(device, step, loss, tracker))
   385   2770.6 MiB      0.0 MiB           return loss.item() / step

There will be no additional memory when epoch >= 2.

**Comment by Lisennlp** [comment]
@dlibenzi Hi. I ran it through the memory tool（memory_profiler） , I found the memory increases when using torch_xla.distributed.parallel_loader function to load data. However when  I used my own loader in a single core to run program(simple, like  .to(device)), GCE memory is stable. You can check to see if there's something wrong with torch_xla.distributed.parallel_loade?

**Comment by dlibenzi** [comment]
It could be two things. Memory fragmentation or Python Queue not releasing references to tensors.
Can you try issuing `gc.collect()` in some places?
I will also run a few experiments using the `SampleGenerator` to see if memory grows for me as well.
But, we ran resnet50 training on whole imagenet for 90+ EPOCH, and if there was a real leak there, we would have OOM-ed.

**Comment by dlibenzi** [comment]
I have tried this on my machine, and memory jumps up and down, but definitely does not leak.
Now, the sample generators just returns the same tensors, but you reported that was growing memory as well.
And AFAICT, while the memory grows and shrinks, it does not "leak".

```Python
import torch
import torch_xla
import torch_xla.core.xla_model as xm
import torch_xla.distributed.parallel_loader as pl
import torch_xla.utils.utils as xu

BATCH_SIZE = 1024
NUM_EPOCHS = 20


def test():
  device = xm.xla_device()
  loader = xu.SampleGenerator(
      data=(torch.zeros(BATCH_SIZE, 3, 32,
                        32), torch.zeros(BATCH_SIZE, dtype=torch.int64)),
      sample_count=10000)

  for epoch in range(1, NUM_EPOCHS + 1):
    para_loader = pl.ParallelLoader(loader, [device])
    device_loader = para_loader.per_device_loader(device)
    for data, target in device_loader:
      pass


if __name__ == '__main__':
  test()
```

**Comment by dlibenzi** [comment]
But this shows memory growing, which is not good.
```Python
import gc
import resource
import torch
import torch_xla
import torch_xla.core.xla_model as xm
import torch_xla.distributed.parallel_loader as pl
import torch_xla.utils.utils as xu

BATCH_SIZE = 1024
NUM_EPOCHS = 20


class SampleGenerator(object):

  def __init__(self, fn, sample_count):
    self._fn = fn
    self._sample_count = sample_count
    self._count = 0

  def __iter__(self):
    return SampleGenerator(self._fn, self._sample_count)

  def __len__(self):
    return self._sample_count

  def __next__(self):
    return self.next()

  def next(self):
    if self._count >= self._sample_count:
      raise StopIteration
    self._count += 1
    return self._fn()


def test():

  def genfn():
    return torch.zeros(BATCH_SIZE, 3, 32, 32), torch.zeros(
        BATCH_SIZE, dtype=torch.int64)

  device = xm.xla_device()
  loader = SampleGenerator(fn=genfn, sample_count=10000)

  for epoch in range(1, NUM_EPOCHS + 1):
    para_loader = pl.ParallelLoader(loader, [device])
    device_loader = para_loader.per_device_loader(device)
    for data, target in device_loader:
      pass
    gc.collect()
    print('EPOCH {}, RSS={}MB'.format(
        epoch,
        resource.getrusage(resource.RUSAGE_SELF).ru_maxrss // 1024))


if __name__ == '__main__':
  test()
```


```
EPOCH 1, RSS=1140MB
EPOCH 2, RSS=1405MB
EPOCH 3, RSS=1621MB
EPOCH 4, RSS=1843MB
EPOCH 5, RSS=2114MB
EPOCH 6, RSS=2390MB
EPOCH 7, RSS=2762MB
EPOCH 8, RSS=2927MB
EPOCH 9, RSS=3327MB
EPOCH 10, RSS=3505MB
```

**Comment by dlibenzi** [comment]
This shows that it is not pytorch tensor memory being added:
```Python
import gc
import re
import resource
import torch
import torch_xla
import torch_xla.core.xla_model as xm
import torch_xla.distributed.parallel_loader as pl
import torch_xla.utils.utils as xu

BATCH_SIZE = 1024
NUM_EPOCHS = 20


class SampleGenerator(object):

  def __init__(self, fn, sample_count):
    self._fn = fn
    self._sample_count = sample_count
    self._count = 0

  def __iter__(self):
    return SampleGenerator(self._fn, self._sample_count)

  def __len__(self):
    return self._sample_count

  def __next__(self):
    return self.next()

  def next(self):
    if self._count >= self._sample_count:
      raise StopIteration
    self._count += 1
    return self._fn()


def get_tensors_memory(devrx):
  memory_size = 0
  accounted = set()
  for obj in gc.get_objects():
    if not torch.is_tensor(obj):
      continue
    if not re.match(devrx, str(obj.device)):
      continue
    storage = obj.storage()
    data_ptr = storage.data_ptr()
    if data_ptr in accounted:
      continue
    accounted.add(data_ptr)
    memory_size += storage.size() * storage.element_size()
  return memory_size


def test():

  def genfn():
    return torch.zeros(BATCH_SIZE, 3, 32, 32), torch.zeros(
        BATCH_SIZE, dtype=torch.int64)

  device = xm.xla_device()
  loader = SampleGenerator(fn=genfn, sample_count=10000)

  for epoch in range(1, NUM_EPOCHS + 1):
    para_loader = pl.ParallelLoader(loader, [device])
    device_loader = para_loader.per_device_loader(device)
    for data, target in device_loader:
      pass
    gc.collect()
    tmem = get_tensors_memory(r'cpu:?.*')
    print('EPOCH {}, RSS={}MB, TMEM={}MB'.format(
        epoch,
        resource.getrusage(resource.RUSAGE_SELF).ru_maxrss // 1024,
        tmem // (1024 * 1024)))


if __name__ == '__main__':
  test()
```

```
EPOCH 1, RSS=1162MB, TMEM=0MB
EPOCH 2, RSS=1374MB, TMEM=0MB
EPOCH 3, RSS=1638MB, TMEM=0MB
EPOCH 4, RSS=1879MB, TMEM=0MB
```

**Comment by dlibenzi** [comment]
It seems to be an artifact of the system memory allocator.
If I run it under `TCMALLOC`, memory usage is much more limited.
```Shell
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4 python ~/tmp/scratch/para_loader_memtest.py
```

```
EPOCH 1, RSS=666MB, TMEM=0MB
EPOCH 2, RSS=666MB, TMEM=0MB
EPOCH 3, RSS=684MB, TMEM=0MB
EPOCH 4, RSS=685MB, TMEM=0MB
EPOCH 5, RSS=685MB, TMEM=0MB
EPOCH 6, RSS=685MB, TMEM=0MB
```

**Comment by Lisennlp** [comment]
@dlibenzi I'm sorry, there was a problem I didn't describe clearly before, that is, during training, not every epoch GCE memory will grow, but it will grow in the first epoch, and remain stable after the second epoch.I think maybe torch_xla.distributed.parallel_loader added some data to the GCE memory in the first epoch, so the GCE memory stays stable after the second epoch.

**Comment by dlibenzi** [comment]
Oh, OK. In any case, I suggest you giving TCMALLOC a try.
It seems it keep memory under control (on top of being faster).

**Comment by Lisennlp** [comment]
@dlibenzi  Here is the result of the first epoch. You can see that the GCE memory was 1931.2 mb before the start of the for loop (line 363) , but when the first epoch ended (line 385) , the memory grew to 1973.4 mb. Indeed, there was a fluctuation in the middle of the loop and it was released, but it didn't completely free up, and it still added 41.8 mb of memory, which is just a little bit of data, and when the data is big, it's going to be big

    Line #    Mem usage    Increment   Line Contents
    ================================================
       358   1931.2 MiB   1931.2 MiB       @profile
       359                                 def tpu_training_loop(loader):
       360   1931.2 MiB      0.0 MiB           tracker = xm.RateTracker()
       361   1931.2 MiB      0.0 MiB           model.train()
       362   1931.2 MiB      0.0 MiB           tr_loss = None
       363   2272.5 MiB    341.4 MiB           for step, data in enumerate(loader):
       364   2272.5 MiB      0.0 MiB               optimizer.zero_grad()
       365   2272.5 MiB      0.0 MiB               input_ids, input_mask, segment_ids, position_ids,answer_ids, answer_mask = data
       366                                         # print(f'step = {step}, input_ids = {input_ids}')
       367   2272.5 MiB      0.0 MiB               log_prob, _ = model(input_ids,
       368   2272.5 MiB      0.0 MiB                                   segment_ids,
       369   2272.5 MiB      0.0 MiB                                   input_mask,
       370   2272.5 MiB      0.0 MiB                                   position_ids,
       371   2272.5 MiB      0.0 MiB                                   answer_ids=answer_ids,
       372   2278.5 MiB      6.0 MiB                                   answer_mask=answer_mask)
       373   2278.8 MiB      0.3 MiB               loss = criterion(log_prob, answer_ids[:, 1:].contiguous().view(-1))
       374   2283.2 MiB      4.4 MiB               loss.backward()
       375   2283.2 MiB      0.0 MiB               if args.gradient_accumulation_steps > 1:
       376                                             loss = loss / args.gradient_accumulation_steps
       377   2283.2 MiB      0.0 MiB               tr_loss = loss * args.gradient_accumulation_steps if step == 0 else tr_loss + loss * args.gradient_accumulation_steps
       378   2283.2 MiB      0.0 MiB               if (step + 1) % args.gradient_accumulation_steps == 0:
       379   2244.3 MiB      0.0 MiB                   xm.optimizer_step(optimizer)
       380   2244.3 MiB      0.0 MiB                   optimizer.zero_grad()
       381   2244.3 MiB      0.0 MiB               tracker.add(args.train_batch_size)
       382   2244.3 MiB      0.0 MiB               loss = tr_loss * (1 / (step + 1)) if step > 0 else tr_loss
       383   2244.3 MiB      0.0 MiB               if step % 1 == 0:
       384   2244.3 MiB      0.0 MiB                   xm.add_step_closure(_train_update, args=(device, step, loss, tracker))
       385   1973.4 MiB      0.0 MiB           return loss.item() / step

Looking at the results after epoch 1, you can see that after the loop, the GCE  memory is almost completely freed (for line 363 to 385), which confirms my above.

    Line #    Mem usage    Increment   Line Contents
    ================================================
       358   2768.6 MiB   2768.6 MiB       @profile
       359                                 def tpu_training_loop(loader):
       360   2768.6 MiB      0.0 MiB           tracker = xm.RateTracker()
       361   2768.6 MiB      0.0 MiB           model.train()
       362   2768.6 MiB      0.0 MiB           tr_loss = None
       363   2832.6 MiB     54.1 MiB           for step, data in enumerate(loader):
       364   2832.6 MiB      0.3 MiB               optimizer.zero_grad()
       365   2832.6 MiB      0.0 MiB               input_ids, input_mask, segment_ids, position_ids, answer_ids, answer_mask = data
       366                                         # print(f'step = {step}, input_ids = {input_ids}')
       367   2832.6 MiB      0.0 MiB               log_prob, _ = model(input_ids,
       368   2832.6 MiB      0.0 MiB                                   segment_ids,
       369   2832.6 MiB      0.0 MiB                                   input_mask,
       370   2832.6 MiB      0.0 MiB                                   position_ids,
       371   2832.6 MiB      0.0 MiB                                   answer_ids=answer_ids,
       372   2832.6 MiB      0.0 MiB                                   answer_mask=answer_mask)
       373   2832.6 MiB      0.0 MiB               loss = criterion(log_prob, answer_ids[:, 1:].contiguous().view(-1))
       374   2832.6 MiB      0.0 MiB               loss.backward()
       375   2832.6 MiB      0.0 MiB               if args.gradient_accumulation_steps > 1:
       376                                             loss = loss / args.gradient_accumulation_steps
       377   2832.6 MiB      0.0 MiB               tr_loss = loss * args.gradient_accumulation_steps if step == 0 else tr_loss + loss * args.gradient_accumulation_steps
       378   2832.6 MiB      0.0 MiB               if (step + 1) % args.gradient_accumulation_steps == 0:
       379   2832.6 MiB      0.2 MiB                   xm.optimizer_step(optimizer)
       380   2832.6 MiB      0.0 MiB                   optimizer.zero_grad()
       381   2832.6 MiB      0.0 MiB               tracker.add(args.train_batch_size)
       382   2832.6 MiB      0.0 MiB               loss = tr_loss * (1 / (step + 1)) if step > 0 else tr_loss
       383   2832.6 MiB      0.0 MiB               if step % 1 == 0:
       384   2832.6 MiB      0.0 MiB                   xm.add_step_closure(_train_update, args=(device, step, loss, tracker))
       385   2770.6 MiB      0.0 MiB           return loss.item() / step

**Comment by Lisennlp** [comment]
> Oh, OK. In any case, I suggest you giving TCMALLOC a try.
> It seems it keep memory under control (on top of being faster).

@dlibenzi ok, I will try it, thanks !

**Comment by dlibenzi** [comment]
```Shell
sudo apt-get install libtcmalloc-minimal4
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4 CMD ARGS...
```

In older distributions the library will be in `/usr/lib/`.

**Comment by Lisennlp** [comment]
@dlibenzi Well, GCE memory doesn't grow when I use TCMALLOC, thank you very much! ！! But 7 G data, still takes up 200 G  GCE memory, so I need to double-check whether my dataloade or the 
 torch_xla.distributed.parallel_loader  caused the problem.

**Comment by dlibenzi** [comment]
200GB in 8 cores or 1 core mode?

**Comment by Lisennlp** [comment]
@dlibenzi It is in 8 cores. I tried to split the data into 8 parts and read them using different process indexes. Even so, it still consumes 200 GB GCE memory, but with a 1 core, it's only about 30 GB.

**Comment by dlibenzi** [comment]
We are talking about RSS memory, right? No VSZ?

**Comment by Lisennlp** [comment]
> We are talking about RSS memory, right? No VSZ?

@dlibenzi Yes, I'm talking about RSS Memory, No VSZ.
