### ISSUE TITLE
MTCNN on TPU

### ISSUE THREAD

**Issue by nosound2** [pytorch/xla#1521]
## ❓ Questions and Help

I wish to run [facenet-pytorch](https://github.com/timesler/facenet-pytorch) **inference** on TPU, but it is too slow. A single image on CPU takes 1s, and on TPU one image 10-14s, a batch of 2 images 232s (116s per image), and a batch of 3 images 449s (150s per image). You see the trend. 

As far as I understand by looking at the MTCNN code, it is far from optimal for TPU. The main code is [here](https://github.com/timesler/facenet-pytorch/blob/master/models/mtcnn.py), but it calls [detect_face() function](https://github.com/timesler/facenet-pytorch/blob/master/models/utils/detect_face.py) which has a lot of custom logic.

Please advise, is there hope to run the inference for MTCNN on TPU in a reasonable time? How to approach the problem?

Full code to reproduce is attached below

```
from facenet_pytorch import MTCNN
import torch_xla
import torch_xla.core.xla_model as xm
from PIL import Image
import time

im = Image.open('20141120_212803.jpg')
print(im.size)

mtcnn = MTCNN(device='cpu', thresholds=[0.3, 0.3, 0.3]).eval()

st = time.time()
boxes, probs = mtcnn.detect(im)
print('time', time.time()-st)

device = xm.xla_device()
print(device)

mtcnn = MTCNN(device=device, thresholds=[0.3, 0.3, 0.3]).eval()

st = time.time()
mtcnn.detect(im)
print('time', time.time()-st)
st = time.time()
mtcnn.detect([im for i in range(2)])
print('time', time.time()-st)
st = time.time()
mtcnn.detect([im for i in range(3)])
print('time', time.time()-st)
st = time.time()
mtcnn.detect(im)
print('time', time.time()-st)
```

the output is
```
(1670, 2174)
time 1.0946919918060303
xla:1
time 14.350183248519897
time 231.74382662773132
time 448.8833785057068
time 10.932560920715332
```

**Comment by dlibenzi** [comment]
Can you try to run under `debug_run.py` so we get an idea of it?

https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#using-debug_runpy-to-collect-debug-information

Just run 5..10 steps and then hit `CTRL^C` ...

**Comment by dlibenzi** [comment]
But I can see at least one of the issues.
There are functions in that detect-face code, that explicitly send tensors to CPU.

**Comment by nosound2** [comment]
Hi @dlibenzi , thank you for the feedback. I was not able to run `debug_run.py` so far. I used the following line, which was running indefinitely, only starting to write `debug_run.tar.gz`. Looks like it was just hanging in the beginning. 

```
python3 ./debug_run.py --outfile /tmp/debug_run.tar.gz -- python -u test.py
```

But more worrying to me is that I tried to measure and run only the line 

```
reg, probs = pnet(im_data)
```

also multiple times in a loop, and on CPU it is just an order of magnitude faster. It is a very simple network, just 4 convolutional layers, and all the weights and the tensors already on the device, so I am very puzzled why it doesn't do it fast. If you have any directions please share.

**Comment by nosound2** [comment]
Some more details. I am using `torch-xla-nightly` and 'torch-nightly' for the TPU. The TPU is `v3-8` and running with CPU `n-8`. 

Tried now to run the same with P100 GPU, as expected running several times faster than the CPU.

**Comment by dlibenzi** [comment]
I don't know what pnet is, but if it is the same network I looked in this post, that code does explicit calls to .cpu() which is not good.
Can you at least print the metrics and post here, after each pnet() call?
```Python
import torch_xla.debug.metrics as met
print(met.metrics_report())
```

**Comment by nosound2** [comment]
Hi @dlibenzi , I have already decommissioned my TPU VM, as I estimated the chance for success as low. But you can super easily reproduce the issue by installing `pip install facenet-pytorch` and then running the simple code provided above.

MTCNN is comprised of 3 small networks running consecutively, - pnet, rnet and onet. The first is run several times on different images sizes. Before looking at explicit calls to cpu() that you mentioned I checked if there is promise of speedup in TPU, as I said, by running only the first pnet call on TPU and measuring its time. And it is very bad for some reason.
