### ISSUE TITLE
Change of signature for "split" and "split_with_sizes"

### ISSUE THREAD

**Issue by albanD** [pytorch/xla#1529]
Hi,

I am making a change in the main pytorch repo here: https://github.com/pytorch/pytorch/pull/32044
This fixes some wrong signatures for `split` and `split_with_sizes`.
This breaks the xla test here: https://app.circleci.com/jobs/github/pytorch/pytorch/4227536

Could you let me know what should I do to fix these?
Should I update some signatures here (not sure where) and merge both PRs at the same time?

**Comment by dlibenzi** [comment]
This should fix those: https://github.com/pytorch/xla/pull/1530

**Comment by albanD** [comment]
This has not been fixed.
Unfortuntly, the pytorch PR mentionned above had to be reverted because users are relying on this mostly broken behavior. This will require more work on our side to be able to allow the valid use case and disallow the others. I'll close this for now, and I will re-open when it is ready again.
