### ISSUE TITLE
Rebuilds everything every time

### ISSUE THREAD

**Issue by cjolivier01** [pytorch/xla#1534]
## 🐛 Bug

Maybe I am missing something, but is it supposed to rebuild the entire torch xla sources every time setup.py is run (not referring to tf bazel build of xla)?  For any code change, for instance?  Am I missing something? I see that cmake is used for tests, but not main code.  i apoligize for this dumb question, but I have been struggling to build this thing for quite some time and the constant rebuild is painful.

**Comment by dlibenzi** [comment]
`pytorch` (the containing folder) is built once.
Then within the `xla` subfolder we build `tensorflow` and `pytorch/xla`.
The latter uses setuptools which always rebuilds AFAIK.
But that should not take too much time.

**Comment by cjolivier01** [comment]
Yes, it is the setuptools build I was referring to. Thanks for the quick clarification.

**Comment by dlibenzi** [comment]
```Shell
time python setup.py install

real    4m44.068s
user    28m15.467s
sys     1m21.287s
```

It depends on the VM (number of cores mostly).

**Comment by cjolivier01** [comment]
btw they renamed TensorTypeId.h to DispatchKey.h, I think, and it's breaking the build

**Comment by dlibenzi** [comment]
We already pushed a PR to fix that :wink:
