### ISSUE TITLE
TF 1.14 suppot

### ISSUE THREAD

**Issue by cjolivier01** [pytorch/xla#1540]
## ❓ Questions and Help
Sorry to bother you again.  What is the last somewhat stable commit that uses Tensorflow 1.14?  I have a restriction for compatibility wth TF1.14 XLA compiler.

**Comment by dlibenzi** [comment]
Hard to say, but there has been MANY changes since then.
It's likely somewhere spring or early summer 2019.

**Comment by cjolivier01** [comment]
Thank you.

**Comment by cjolivier01** [comment]
btw, Last day for TF1.14 was October 4, 2019:

```bash
git checkout $(git rev-list -1 --before="October 1 2019" master) && git submodule sync && git submodule update --init --recursive && cat third_party/tensorflow/tensorflow/core/public/version.h | grep TF_.*_VERSION
```
