### ISSUE TITLE
[question] Loading from Google Cloud Storage

### ISSUE THREAD

**Issue by david-macleod** [pytorch/xla#1544]
I am currently limited to GCP free tier ($300 credits) which means I cannot create a VM with more than 8 cores, which I am pretty sure has resulted in my TPU training being bottlenecked on data loading.

1. Is it possible to check that I am bottlenecked on data loading conclusively via the summary metrics? 
2. Is it possible to load directly from GCS onto the TPU as tensorflow does? I know this wasn't possible at some point last year but have noticed a new TFRecord reader and cloud storage I/O module in the repo, but could not tell if this was simply for loading TFRecords onto the VM and then loading them onto the TPU in a two step process.

Many thanks!

**Comment by dlibenzi** [comment]
1) If you measure time it takes to fetch the next sample, that will tell you if you are bottlenecked:

https://github.com/pytorch/xla/blob/2024f30390fe693d761792a2c1114a9ecdc60f21/test/test_train_mp_mnist.py#L122

2) We do not support XLA infeed and I am not sure we ever will. We are changing the Cloud TPU infrastructure such that there won't be 2 VMs anymore, so the whole infeed thing will become less relevant.

**Comment by david-macleod** [comment]
Thanks!
