### ISSUE TITLE
Code hangs when `xm.xla_device()` called if TPUs not found

### ISSUE THREAD

**Issue by harpone** [pytorch/xla#1548]
## 🐛 Bug

Maybe not a bug strictly speaking, but calling `xm.get_xla_supported_devices()` or `xm.xla_device()` just freezes the system instead of raising an error in case where the correct TPU env variables are not set or when a TPU has been shut down.

This makes developing and testing with CPU difficult. Would be nice to return CPU devices or raising an error so one could catch it with try-except.

**Comment by zcain117** [comment]
We run into this hang sometimes while developing and I agree it's not a good experience. We'll look into improving this, thanks for bringing it up!

**Comment by dlibenzi** [comment]
Not much fix here. TF GRPC has reconnection logic where it tries to reconnect in case network goes temporarily out.
I am not sure it has exposed environment variables to tune that behavior.

**Comment by harpone** [comment]
hmm OK... is there any way to tweak some configs to timeout or give up after N reconnection attempts @dlibenzi ?

**Comment by dlibenzi** [comment]
I'd say no, but we can look.
Another issue is that in some cases the connection will need to wait for quite some time, like during POD training, which can take many seconds before the full mesh becomes initialized.

**Comment by harpone** [comment]
Would something like asserting `TPU_IP_ADDRESS` is not empty and then pinging that address work as a temporary hack at start of script?

**Comment by dlibenzi** [comment]
I think we are looking into something which very rarely happen in reality.
Maybe in Colab happens more, but TPU_IP_ADDRESS should really be set to a correct IP address.
A Tensorflow Colab (using the same GRPC machinery) would behave in a similar fashion.

**Comment by harpone** [comment]
Well yeah I have `TPU_IP_ADDRESS` set now in .bashrc, but basically I'm thinking of a workflow where I work on the code on the VM (using the VM interpreter as a remote interpreter) while the expensive TPU is stopped, then when it's AOK, start the TPU and run the training.

I'm open to suggestions if this seems like a silly workflow :)

**Comment by harpone** [comment]
(the point being that I expect bugs when running my PyTorch code on a TPU and that it would be really nice to debug with PyCharm's fantastic debugger)

**Comment by dlibenzi** [comment]
Oh, so are you using a normal Google Cloud VM or Colab?
Mentions to .bashrc suggest me the former.

**Comment by harpone** [comment]
Yeah Google Cloud VM

**Comment by dlibenzi** [comment]
In theory it would be better to have a script which looks up the IP address given a TPU VM name, so one can replace:
```Shell
$TPU_IP_ADDRESS
```
With:
```Shell
$(resolve_tpu_ip $TPU_VM_NAME)
```

**Comment by jysohn23** [comment]
We plan on introducing a way to run your models on any TPU like:
```
(vm)$ python -m torch_xla.distributed.xla_dist --tpu=$NAME -- python train.py
```

**Comment by harpone** [comment]
Oh OK that would be cool! Anyway, I guess for now I can just work with a small TPU or hard code a flag to use the CPU. Thanks all!
