### ISSUE TITLE
xla:0 vs. xla:1 when using xmp.spawn

### ISSUE THREAD

**Issue by myleott** [pytorch/xla#1577]
When using `xmp.spawn`, why does `xm.xla_device()` return `xla:1` for rank 0 and `xla:0` for all other ranks? I would have expected all 8 ranks to see `xla:0`. Is my output below expected?

Code:
```
import torch
import torch_xla.core.xla_model as xm
import torch_xla.distributed.xla_multiprocessing as xmp

def main(rank):
    t = torch.rand(1).to(device=xm.xla_device())
    print('rank: {}, t: {}'.format(rank, t))

if __name__ == '__main__':
    xmp.spawn(main, args=(), nprocs=8)
```

Output:
```
rank: 4, t: tensor([0.2270], device='xla:0')
rank: 1, t: tensor([0.3275], device='xla:0')
rank: 2, t: tensor([0.7419], device='xla:0')
rank: 6, t: tensor([0.9121], device='xla:0')
rank: 5, t: tensor([0.3112], device='xla:0')
rank: 3, t: tensor([0.0844], device='xla:0')
rank: 7, t: tensor([0.1149], device='xla:0')
rank: 0, t: tensor([0.3322], device='xla:1')   <-- should this be xla:0?
```

I'm on the nightly build.

**Comment by dlibenzi** [comment]
It is a matter of internal devices being registered.
In the master the local CPU device is registered.
But the user should never assume any `xla:*` numbering. Devices should be handed over by APIs like `xm.xla_device()`.
The call to `xm.xla_device()` also sets the default device, which is required to make things work correctly (especially autograd).
