### ISSUE TITLE
Error after instancing the device (device=xm.xla_device())

### ISSUE THREAD

**Issue by kerenskybr** [pytorch/xla#1591]
Every time I try to instance the tpu device, this happens. Both envs torch-xla-0.5, and nightly

2020-02-04 13:53:21.307041: I    2086 tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:217] XRT device 
(LOCAL) TPU:0 -> /job:tpu_worker/replica:0/task:0/device:TPU:0
2020-02-04 13:53:21.307135: I    2086 tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:221] Worker grpc
://localhost:51000 for /job:tpu_worker/replica:0/task:0
2020-02-04 13:53:21.307158: I    2086 tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:225] XRT default
 device: TPU:0
2020-02-04 13:53:21.307181: I    2086 tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:1114] Configurin
g TPU for master worker tpu_worker:0 at grpc://localhost:51000
2020-02-04 13:53:21.324940: E    2086 tensorflow/core/framework/op_kernel.cc:1579] OpKernel ('op: "ErfinvGrad" devi
ce_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_DOUBLE } } }') for unknown op: ErfinvGrad
2020-02-04 13:53:21.325032: E    2086 tensorflow/core/framework/op_kernel.cc:1579] OpKernel ('op: "ErfinvGrad" devi
ce_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_FLOAT } } }') for unknown op: ErfinvGrad
2020-02-04 13:53:21.325049: E    2086 tensorflow/core/framework/op_kernel.cc:1579] OpKernel ('op: "NdtriGrad" devic
e_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_DOUBLE } } }') for unknown op: NdtriGrad
2020-02-04 13:53:21.325073: E    2086 tensorflow/core/framework/op_kernel.cc:1579] OpKernel ('op: "NdtriGrad" devic
e_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_FLOAT } } }') for unknown op: NdtriGrad

**Comment by dlibenzi** [comment]
Can you post a minimal code that allows this to reproduce?

**Comment by kerenskybr** [comment]
I just followed the docs. Create a vm using debian + torch, create a tpu node, export the tpu ip, activate the conda env, python, then run the imports and device=xm.xla_device()

I'm trying to run a resnet model with torch, but do the same error output

**Comment by dlibenzi** [comment]
Does this work for you?

https://github.com/pytorch/xla/blob/master/test/test_train_mp_mnist.py

**Comment by dlibenzi** [comment]
Can you try selecting pytorch nighty on both user VM and TPU VM?

**Comment by kerenskybr** [comment]
Running on cpu goes fine, but it's very slow (more than in my machine). Running the test codes you've said, throws the same error. 

There's a slight difference between the tutorial and the gcp options. Debian + torch now is under "Deep learning" section. Could something had changed in this vm?
I'm facing this problem for 3 days. Tried to redo everything but the error persists. I don't know what I did wrong

**Comment by dlibenzi** [comment]
For "test codes" you mean `test/run_tests.sh` and `test/cpp/run_tests.sh`?

**Comment by kerenskybr** [comment]
No, those train mnist and train imagenet python files

**Comment by jysohn23** [comment]
Trying to repro

**Comment by jysohn23** [comment]
Hi @kerenskybr,

I am not able to reproduce your error. I created a fresh GCE VM with the following command:

```
gcloud compute --project=$PROJECT instances create $VM --zone=$ZONE --machine-type=n1-standard-16 --subnet=default --network-tier=PREMIUM --maintenance-policy=MIGRATE --service-account=109651010708-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/cloud-platform --image=debian-9-torch-xla-v20200204 --image-project=ml-images --boot-disk-size=200GB --boot-disk-type=pd-standard --boot-disk-device-name=$VM --reservation-affinity=any
```

And a TPU with `pytorch-nightly` SW version. Then all I did was ssh onto the GCE VM, export the TPU IP address and run:
```
export XRT_TPU_CONFIG="tpu_worker;0;$TPU_IP_ADDRESS:8470"
python /usr/share/torch-xla-nightly/pytorch/xla/test/test_train_mp_mnist.py 
```

Also tried running with XLA/CPU but no error:
```
export XRT_DEVICE_MAP="CPU:0;/job:localservice/replica:0/task:0/device:XLA_CPU:0"
export XRT_WORKERS="localservice:0;grpc://localhost:40934"
```

**Comment by kerenskybr** [comment]
I'll try using those command lines instead of the gui/browser and see what happens. I'll back with the results, thank you all

**Comment by jysohn23** [comment]
Browse UI should work too. Were the env vars all set?

**Comment by kerenskybr** [comment]
Did all again. Deleted the vm and node, and created again. After that, I used this configs in the SSH:
First of all, I had to use _gcloud auth login_

$ _gcloud beta compute  ssh "instance" --zone "us-central1-c"._
(^ here the dot causes an error, had to remove)
(vm)$ _export TPU_IP_ADDRESS=177.220.234.78_
(^ my public ip address, right?)
(vm)$ _export XRT_TPU_CONFIG="tpu_worker;0;$10.240.0.2:8470"_
(^ the ip in the TPU node)
(vm)$ _conda activate torch-xla-0.5
(torch-xla-0.5)$  python /usr/share/torch-xla-0.5/pytorch/xla/test/test_train_imagenet.py --fake_data --model=resnet50 --num_epochs=10 --num_workers=64 --batch_size=128 --log_steps=20_

The same error happened. It's the first time I use GCP, surely did something wrong, but can't find it

**Comment by jysohn23** [comment]
First of all, `TPU_IP_ADDRESS` is not your public IP address. It's just an environment variable used to replace: `XRT_TPU_CONFIG="tpu_worker;0;$TPU_IP_ADDRESS:8470"`.

Also your `export XRT_TPU_CONFIG="tpu_worker;0;$10.240.0.2:8470"` should be ` export XRT_TPU_CONFIG="tpu_worker;0;10.240.0.2:8470"` (got rid of the "$" sign) assuming that `10.240.0.2` is your TPU's internal IP address.

**Comment by kerenskybr** [comment]
No luck. Same error. I had been cursed

**Comment by dlibenzi** [comment]
Can you try to run this in your VM?
```Python
import torch_xla
print(torch_xla.version.__xla_gitrev__)
print(torch_xla.version.__torch_gitrev__)
```

**Comment by kerenskybr** [comment]
Hi, I manage to solve changing the zone to ' us-central1-b ', and then selecting the' tpu type = 3.8'. That solved the issue.

Thank you all, really appreciate the help :)
