### ISSUE TITLE
View followed by copy_ doesn't update

### ISSUE THREAD

**Issue by ailzhang** [pytorch/xla#1616]
```
import torch
import torch_xla

def do_test(d0, d1):
    x = torch.tensor([1.5, 2.5, 3.5, 4.5, 5.5, 6.5], device=d0)
    y = torch.tensor([0, 0, 0, 0, 0, 0], device=d1)

    y[::2].copy_(x[::2])
    print(y)

do_test('cpu', 'xla:0')
```

**Comment by dlibenzi** [comment]
Hmm, I wonder if this would trigger cross device.

https://github.com/pytorch/xla/pull/1615

But here there should only be one device (XLA CPU).

**Comment by dlibenzi** [comment]
OK, found it.
Here we have an issue:

https://github.com/pytorch/xla/blob/f72e2e768ec17b92194b67896e903227845cb930/torch_xla/csrc/aten_xla_type.cpp#L836

**Comment by dlibenzi** [comment]
@ailzhang Should be using, like #1615 , UpdateFromTensor().

**Comment by ailzhang** [comment]
@dlibenzi  Thanks! I'll give it a try!

**Comment by ailzhang** [comment]
Nice it worked! Thanks @dlibenzi !
