### ISSUE TITLE
Sending .to(device) after defining optimizer leads to subtle bug

### ISSUE THREAD

**Issue by harpone** [pytorch/xla#1623]
## 🐛 Bug

Doing

```
model = MyModel(...)
optimizer = optim.SGD(model.parameters())
model.to(device)
```

for XLA device instead of

```
model = MyModel(...).to(device)
optimizer = optim.SGD(model.parameters())
```

will lead to an extremely subtle bug: model gradients and everything else seems to be fine (optimizer grads not?) and no error is raised. 

With CUDA, both approaches would work, or an error would be raised (depending on optimizer): https://discuss.pytorch.org/t/effect-of-calling-model-cuda-after-constructing-an-optimizer/15165

## Expected behavior

Preferably raise an error.

## Environment

 - reproducible on XLA backend [CPU/TPU]: on TPUss
 - torch_xla version: torch-xla-nightly 0.8+e68039d

**Comment by dlibenzi** [comment]
The optimizer captures the parameters at constructor time, so I am guessing the latter is the proper way of doing things?

**Comment by ailzhang** [comment]
@dlibenzi  In CPU & CUDA, both work in most cases, but we have updated doc to instruct users to use the latter approach here. "If you need to move a model to GPU via .cuda(), please do so before constructing optimizers for it. Parameters of a model after .cuda() will be different objects with those before the call." 
It'll be good if we could find a way to throw an error in the first case.

**Comment by harpone** [comment]
OK thats good to know @ailzhang thanks! Yeah it would be really useful to get an error... it can be very tricky to spot something like that :joy_cat:
