### ISSUE TITLE
xla barrier?

### ISSUE THREAD

**Issue by williamFalcon** [pytorch/xla#1654]
Working on finishing TPU support for Lightning.

However, running into an issue that's likely related to downloading the dataset on multiple processes. The way to solve this in PT dist would be to download from gpu=0 and add dist.barrier().

Is there a .barrier for xla?

![image](https://user-images.githubusercontent.com/3640001/74615789-ba3b2480-50f1-11ea-94bd-e8fed48d8ea4.png)

It all works great until...

![image](https://user-images.githubusercontent.com/3640001/74615802-cd4df480-50f1-11ea-830e-2d578860ff14.png)

**Comment by dlibenzi** [comment]
This should be doing it: https://github.com/pytorch/xla/pull/1655

**Comment by dlibenzi** [comment]
This is in now (will be in tomorrow nightly builds), give it a try.

**Comment by jysohn23** [comment]
FYI @williamFalcon, after https://github.com/pytorch/xla/pull/1669 goes in make sure to call the barrier with `torch_xla.core.xla_model.rendezvous`.

**Comment by williamFalcon** [comment]
@jysohn23 @dlibenzi thanks!
