### ISSUE TITLE
Is torchvision.ops.nms supported?

### ISSUE THREAD

**Issue by nosound2** [pytorch/xla#1667]
## ❓ Questions and Help

Is this operation supported on TPU tensors?
[torchvision.ops.nms()](https://pytorch.org/docs/stable/torchvision/ops.html#torchvision.ops.nms)

I pass valid TPU tensor for both boxes and scores, but get an error

```
/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torchvision-0.6.0a0+6c2cda6-py3.6-linux-x86_64.egg/torchvision/ops/boxes.py in batched_nms(boxes, scores, idxs, iou_threshold)
     74     offsets = idxs.to(boxes) * (max_coordinate + 1)
     75     boxes_for_nms = boxes + offsets[:, None]
---> 76     keep = nms(boxes_for_nms, scores, iou_threshold)
     77     return keep
     78 

/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torchvision-0.6.0a0+6c2cda6-py3.6-linux-x86_64.egg/torchvision/ops/boxes.py in nms(boxes, scores, iou_threshold)
     34         by NMS, sorted in decreasing order of scores
     35     """
---> 36     return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
     37 
     38 

RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
```

I can give a standalone example to reproduce on request.

**Comment by dlibenzi** [comment]
From a quick look ... no?

https://github.com/pytorch/vision/blob/master/torchvision/csrc/nms.h

**Comment by ailzhang** [comment]
`nms` is custom ops implemented in `torchvision` where it only has cpu/cuda implementations. In the current implementation the best case scenario is we push it back to CPU to execute `nms` but it hurts performance a lot. 
And it's part of detectron models where shapes are super dynamic iirc. cc: @jysohn23 for a quick update on porting those models?

**Comment by jysohn23** [comment]
@sprt did do some of the work to get the forward pass of MaskRCNN running on TPUs, but it was quite a pain to optimize the performance since the model was quite dynamic. In particular operations like NMS and remove_small_boxes were a pain.

Performance degradation from ops like nms are two-fold: (1) They filter out boxes, and thus the shape of the tensor changes, triggering a recompilation on the TPUs (which is more expensive than execution time), (2) that op is not lowered to TPU so it'll have to make a round trip to CPU, which is also expensive.

**Comment by dlibenzi** [comment]
How does TF handle NMS?
Maybe there is a path to have a TPU friendly PyTorch implementation?

**Comment by jysohn23** [comment]
@dlibenzi Even with TPU + TF it's quite a big pain. If you want to check out the full implementation of the custom op they have:
* https://github.com/tensorflow/tpu/blob/master/models/official/detection/ops/postprocess_ops.py#L283
* https://github.com/tensorflow/tpu/blob/master/models/official/detection/ops/nms.py#L111
* https://github.com/tensorflow/tpu/blob/master/models/official/mask_rcnn/box_utils.py#L31

**Comment by Sunny478** [comment]
When can we expect to use pytorch for object detection on TPU's ?

**Comment by dlibenzi** [comment]
We do have our own NMS, though it has not thoroughly tested:

https://github.com/pytorch/xla/blob/5430aca79ffdd1e0084c151a0d0302d40e5f55b3/torch_xla/core/functions.py#L87
