### ISSUE TITLE
What is "Lowering" referring to?

### ISSUE THREAD

**Issue by cjolivier01** [pytorch/xla#1675]
## ❓ Questions and Help
Sorry for the stupid question, but what is meant by "Lowering", as it applies to LowerContext class, which appears to convert IR->XLA?  

such as:
```cpp
XlaOpVector LoweringContext::LowerNode(const Node* node) {
...
}
```

**Comment by dlibenzi** [comment]
Lowering in compiler terms mean a generic operation which moves for higher level representations, to lower level ones.

**Comment by cjolivier01** [comment]
Thank you for your time.
