### ISSUE TITLE
little help needed with the error

### ISSUE THREAD

**Issue by level14taken** [pytorch/xla#1711]
## ❓ Questions and Help
hey i have followed colab pytorch notebook as reference,but i ended with the following error

https://colab.research.google.com/drive/1TISpmEKfBkeWFvzRSv3ouwLZKH34ou-7
last but one cell is where tpu is used 
can anyone help on this  issue

**Comment by dlibenzi** [comment]
Can you try to use `nightly` in the VERSION selector?

**Comment by dlibenzi** [comment]
![image](https://user-images.githubusercontent.com/14933084/75631252-27e15900-5ba6-11ea-9221-2ef7c3ac4d55.png)

**Comment by level14taken** [comment]
Hi, it gave the same error as before!!

**Comment by dlibenzi** [comment]
The error is different but AFAICT you are mixing Tensorflow with PyTorch/XLA, and I am not sure it is safe on the same Colab notebook.

**Comment by level14taken** [comment]
my bad, the code was running till the complete epochs specified,but was giving exception only at the last epoch during validation,so i will just ignore the validation on last epoch and then everything is fine.
