### ISSUE TITLE
help on multiple dataset preparation 

### ISSUE THREAD

**Issue by level14taken** [pytorch/xla#1713]
## ❓ Questions and Help
in the colab demo notebooks 8 datasets were downloaded and each core was given a seperate dataset as :
root=os.path.join(FLAGS['data_dir'], str(xm.get_ordinal()))

should i copy the data 8 times if dataset is in local folder?? or should i just use 1 dataset for all the 8 cores??

**Comment by dlibenzi** [comment]
The only reason we direct to 8 different folders is that the each DataLoader (8 of them, one for each process handing one core) will try to download at the same time.
If you have a local copy you download before start training you can just point to the same local folder.
