### ISSUE TITLE
XLA + Autocast Interaction

### ISSUE THREAD

**Issue by mcarilli** [pytorch/xla#1752]
I'm working on native Pytorch support for [automatic mixed precision](https://github.com/pytorch/pytorch/pull/32140), implemented by adding an [AutocastTensorId](https://github.com/pytorch/pytorch/blob/687eb35f33f162327b0b633d20f54a9ddb9681db/c10/core/DispatchKey.h#L132) that registers wrappers to perform casts before autograd history recording.  The initial implementation is done, pending documentation approval.

I noticed XLA has dedicated pre- and post-autograd dispatch keys, and I'm wondering how (or if) they should interact with `AutocastTensorId`.

Right now, I think they ignore each other.  `AutocastTensorId` has higher priority than `XLAPreAutograd`, but autocasting only affects tensors for which `is_cuda()` is true.  As far as I know, XLA is exposed by constructing and using tensors whose device type is XLA, for which (I assume) `is_cuda()` is false, so autocasting wouldn't touch them.  Any XLA+autocasting interaction can be decided/added in the future.

Hypothetically, if we did want XLA and autocasting to interact, I can imagine two schools of thought:

1. If XLA and autocasting are both enabled, XLA wants to know the casting decisions autocasting made, and can then fuse or elide them as it sees fit.  In this case `AutocastTensorId` should probably remain higher priority, so autocasting precedes whatever XLA's dispatch layers want to record.
2. XLA is a strong independent compiler that wants to make its own casting decisions, and doesn't need autocast's suggestions.  In this case `XLAPreAutograd` should be higher priority/precede autocasting.

2 becomes more complex because autocasting (if enabled) will still perform casts after routing through `XLAPreAutograd`, which may pull the rug out from under XLA in some way.  In this case `XLAPreAutograd`'s wrappers might need to disable `AutocastTensorId`.

Mostly raising this issue for awareness/discussion, I don't think it needs immediate attention, but please let me know if I'm wrong about that.  Tagging people @dlibenzi told me would be interested.

@dlibenzi @ailzhang @ezyang @jysohn23 @mruberry @ngimel @csarofeen @myleott

**Comment by dlibenzi** [comment]
Thanks for opening this issue!

**Comment by ailzhang** [comment]
Not sure if we already have tier of priorities in the current dispatch key set, if so, IMHO putting XLAPreAutograd and AutocastTensorId in the same set where we don't have to decide an order now will be ideal :D 
@ezyang would know more about this.

**Comment by dlibenzi** [comment]
Just a few comment.
XLA devices are definitely not `is_cuda()`.
An XLA device can end up using a GPU as well, but that totally out of any upper layer control.

Are the auto-casting hooks price paid by any user, even if he does not care about it, or it's an opt-in feature?

XLA does not support FP16 but uses (TPU) BF16.
How can an auto-casting know that, for example, on TPU, a given op can be safely downgraded to BF16?
I feel that all this logic needs to necessarily be per-device, and a single GPU-only engine does not cut it (as it will make decisions which are GPU bound).

**Comment by mcarilli** [comment]
Autocast is opt-in, with a context manager to specify regions:
```
with torch.cuda.amp.autocast():
    c = torch.mm(a, b)
```
The context manager becomes a no-op (does not enable the autocast dispatch layer) if `torch.cuda.is_available()` is `False`.  (The `is_cuda()` check within the autocast wrappers is separate, and acts to make autocast wrappers a no-op if it happens to be enabled and intercepts an op acting on non-cuda tensors.)

Autocasting doesn't know about TPU capabilities, and currently only casts back and forth between FP16 and FP32.  The decisions it makes are specific to GPUs, based on our experience and the known capabilities of Pytorch's GPU kernels.  Bfloat16 would be easy to add as an option to the autocasting frontend and backend if we assume the best cast decisions are the same as with FP16, but that's likely not the case in general.  My dispatch layer might have to make different casting decisions depending on whether the desired "fast type" is FP16 or bfloat16, and I don't know what the right casting decisions for TPU might be.

Given this, it appears you're leaning towards "no, they shouldn't interact" for the time being.  That seems fine as long as they peacefully ignore each other.  In any case since autocasting is (currently) GPU-only, I expect people won't write scripts that target XLA and use autocasting.

**Comment by dlibenzi** [comment]
Yeah, I think it is the safest approach ATM.
