### ISSUE TITLE
torch.einsum behavior on xla is not the same as on CPU & GPU

### ISSUE THREAD

**Issue by magicknight** [pytorch/xla#1767]
## 🐛 Bug

When using  torch.einsum on tensors, the axis of tensor is not the same as tensor on CPU & GPU

`
result = torch.einsum('jk,ijk->ij', first, second)
`
first.shape :  torch.Size([8, 3])
second.shape: torch.Size([25, 8, 3])

this line results in an error when running on xla device:

`
RuntimeError: /pytorch/xla/third_party/tensorflow/bazel-tensorflow/tensorflow/compiler/xla/xla_client/debug_macros.h:27 : Check failed: status.status() == ::tensorflow::Status::OK() (Invalid argument: Cannot infer shape for dot operation: s64[8,1,3] <dot> f32[8,3,25]. Element types do not match. vs. OK)
`

But the same line is OK on CPU and GPU

## To Reproduce

1.
2.
3.

## Expected behavior

Same Behavior as running on CPU and GPU

## Environment

 - reproducible on XLA backend [CPU/TPU]: V3-8
 - torch_xla version: nightly
 - Any other relevant information. In case of issues related to slow executions, re-compilations, etc.., it is useful to have the `tar.gz` report from https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#using-debug_runpy-to-collect-debug-information

**Comment by ailzhang** [comment]
@magicknight Can you provide a minimal repro of the bug? 
I tried a simple one based on your report but it seems fine. 
```

In [7]: a = torch.rand(8, 3, device='xla')

In [8]: b = torch.rand(25, 8, 3, device='xla')

In [9]: result = torch.einsum('jk,ijk->ij', a, b)

In [10]: result
Out[10]: print(result)
```

**Comment by magicknight** [comment]
> @magicknight Can you provide a minimal repro of the bug?
> I tried a simple one based on your report but it seems fine.
> 
> ```
> 
> In [7]: a = torch.rand(8, 3, device='xla')
> 
> In [8]: b = torch.rand(25, 8, 3, device='xla')
> 
> In [9]: result = torch.einsum('jk,ijk->ij', a, b)
> 
> In [10]: result
> Out[10]: print(result)
> ```



Thanks for reply.
I have wrote some lines of codes to demostrate this bug.

`
import torch
import torch_xla
import torch_xla.core.xla_model as xm

device = xm.xla_device()

first_tensor = torch.tensor([[-0.5000, -0.5000,  1.0000],
        [ 0.0000, -0.5000,  1.0000],
        [ 0.5000, -0.5000,  1.0000],
        [-0.5000,  0.0000,  1.0000],
        [ 0.0000,  0.0000,  1.0000],
        [ 0.5000,  0.0000,  1.0000],
        [-0.5000,  0.5000,  1.0000],
        [ 0.0000,  0.5000,  1.0000],
        [ 0.5000,  0.5000,  1.0000]], device=device)


point_tensor = torch.tensor([ 0,  0, -1], device=device)

third_tensor = first_tensor - point_tensor

norm_third_tensor = torch.nn.functional.normalize(third_tensor, p=2, dim=1, eps=1e-8)

forth_tensor = torch.tensor([
    [[0, 0, 0], [1, 0, 0], [0, 1, 0]],
    [[0, 0, 0], [0, 1, 0], [-1, 0, 0]],
    [[0, 0, 0], [0, -1, 0], [1, 0, 0]],
    [[0, 0, 0], [-1, 0, 0], [0, -1, 0]],
    # 
    [[0, 0, -0.5], [0, 1, -0.5], [1, 0, -0.5]],
    [[0, 0, -0.5], [-1, 0, -0.5], [0, 1, -0.5]],
    [[0, 0, -0.5], [1, 0, -0.5], [0, -1, -0.5]],
    [[0, 0, -0.5], [0, -1, -0.5], [-1, 0, -0.5]],
    ],
    dtype=torch.float,
    device=device)

fifth_tensor = forth_tensor[:, 1, :] - forth_tensor[:, 0, :]
sixth_tensor = forth_tensor[:, 2, :] - forth_tensor[:, 0, :] 

seventh_tensor = torch.cross(fifth_tensor, sixth_tensor, dim=1)

eijk = torch.zeros((3, 3, 3), device=device)
eijk[0, 1, 2] = eijk[1, 2, 0] = eijk[2, 0, 1] = 1
eijk[0, 2, 1] = eijk[2, 1, 0] = eijk[1, 0, 2] = -1


a_tensor = torch.einsum('ijk,uj,vk->uvi', eijk, norm_third_tensor, sixth_tensor)


b_tensor = point_tensor - forth_tensor[:, 0, :]


result = torch.einsum('jk,ijk->ij', b_tensor, a_tensor)

`

Tested the codes above on TPU v3-8 and pytorch-xla-nightly environment, I got the following output:

`
/pytorch/xla/third_party/tensorflow/bazel-tensorflow/tensorflow/compiler/xla/xla_client/debug_macros.h:27 : Check failed: status.status() == ::tensorflow::Status::OK() (Invalid argument: Cannot infer shape for dot operation: s64[8,1,3] <dot> f32[8,3,9]. Element types do not match. vs. OK)
`

**Comment by harpone** [comment]
I'm also doing similar tensor manipulation stuff and also getting shape inference error, but _only_ when running in multiprocessing distributed mode... using torch-xla  0.8+c77641f.

The error:
```
Invalid argument: Cannot infer shape for dot operation: f32[128,64] <dot> f32[256,64]. Contracting dimension sizes do not match. vs. OK)
```

**Comment by dlibenzi** [comment]
This worked (setting proper dtypes):
```Python
import torch
import torch_xla
import torch_xla.core.xla_model as xm

device = xm.xla_device()
#device='cpu'

first_tensor = torch.tensor(
    [[-0.5000, -0.5000, 1.0000], [0.0000, -0.5000, 1.0000],
     [0.5000, -0.5000, 1.0000], [-0.5000, 0.0000, 1.0000],
     [0.0000, 0.0000, 1.0000], [0.5000, 0.0000, 1.0000],
     [-0.5000, 0.5000, 1.0000], [0.0000, 0.5000, 1.0000],
     [0.5000, 0.5000, 1.0000]],
    dtype=torch.float32,
    device=device)

point_tensor = torch.tensor([0, 0, -1], device=device, dtype=torch.float32)

third_tensor = first_tensor - point_tensor

norm_third_tensor = torch.nn.functional.normalize(
    third_tensor, p=2, dim=1, eps=1e-8)

forth_tensor = torch.tensor(
    [
        [[0, 0, 0], [1, 0, 0], [0, 1, 0]],
        [[0, 0, 0], [0, 1, 0], [-1, 0, 0]],
        [[0, 0, 0], [0, -1, 0], [1, 0, 0]],
        [[0, 0, 0], [-1, 0, 0], [0, -1, 0]],
        #
        [[0, 0, -0.5], [0, 1, -0.5], [1, 0, -0.5]],
        [[0, 0, -0.5], [-1, 0, -0.5], [0, 1, -0.5]],
        [[0, 0, -0.5], [1, 0, -0.5], [0, -1, -0.5]],
        [[0, 0, -0.5], [0, -1, -0.5], [-1, 0, -0.5]],
    ],
    dtype=torch.float32,
    device=device)

fifth_tensor = forth_tensor[:, 1, :] - forth_tensor[:, 0, :]
sixth_tensor = forth_tensor[:, 2, :] - forth_tensor[:, 0, :]

seventh_tensor = torch.cross(fifth_tensor, sixth_tensor, dim=1)

eijk = torch.zeros((3, 3, 3), device=device, dtype=torch.float32)
eijk[0, 1, 2] = eijk[1, 2, 0] = eijk[2, 0, 1] = 1
eijk[0, 2, 1] = eijk[2, 1, 0] = eijk[1, 0, 2] = -1

a_tensor = torch.einsum('ijk,uj,vk->uvi', eijk, norm_third_tensor, sixth_tensor)

b_tensor = point_tensor - forth_tensor[:, 0, :]

result = torch.einsum('jk,ijk->ij', b_tensor, a_tensor)
```

**Comment by magicknight** [comment]
Ah, so it is the problem with uncorrect dtype? Thank you dlibenzi 👍
