### ISSUE TITLE
compatibility with torchaudio

### ISSUE THREAD

**Issue by laurencejennings** [pytorch/xla#1769]
## ❓ Questions and Help
I'm trying to run a pytorch script which is using torchaudio on a google TPU. To do this I'm following [this notebook][2], more specifically I'm using this code cell to load the xla:

```
!pip install torchaudio
import os
assert os.environ['COLAB_TPU_ADDR'], 'Make sure to select TPU from Edit > Notebook settings > Hardware accelerator'

VERSION = "20200220"  #@param ["20200220","nightly", "xrt==1.15.0"]
!curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
!python pytorch-xla-env-setup.py --version $VERSION

import torch

import torchaudio

import torch_xla
```

however this is incompatible with the version of torchaudio that I need as: `ERROR: torchaudio 0.4.0 has requirement torch==1.4.0, but you'll have torch 1.5.0a0+e95282a which is incompatible.`

I couldn't find anywhere how to load `torch 1.4.0` using pytorch xla. 

I tried to use the nightly version of torch audio but that gives the error as follows: 

``` 
!pip install torchaudio_nightly -f https://download.pytorch.org/whl/nightly/torch_nightly.html

import os
assert os.environ['COLAB_TPU_ADDR'], 'Make sure to select TPU from Edit > Notebook settings > Hardware accelerator'

VERSION = "20200220"  #@param ["20200220","nightly", "xrt==1.15.0"]
!curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
!python pytorch-xla-env-setup.py --version $VERSION

import torch
import torchaudio

import torch_xla
```

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-968e9d93c06f> in <module>()
      9 
     10 import torch
---> 11 import torchaudio
     12 
     13 import torch_xla

/usr/local/lib/python3.6/dist-packages/torchaudio/__init__.py in <module>()
      3 
      4 import torch
----> 5 import _torch_sox
      6 
      7 from .version import __version__, git_version

ImportError: /usr/local/lib/python3.6/dist-packages/_torch_sox.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_29E

---------------------------------------------------------------------------
```

On the documentation and around on the internet I couldn't find how to load the stable version or 1.4.0 version of pytorch using xla. How should I set the variable version in order to get a non nightly version? Also if you know of any workaround like using a different torchaudio version that would be of great help!

Thanks a lot 

  [1]: https://github.com/pytorch/xla
  [2]: https://colab.research.google.com/github/pytorch/xla/blob/master/contrib/colab/style_transfer_inference-xrt-1-15.ipynb#scrollTo=j1w1G4AcWw9f

**Comment by dlibenzi** [comment]
We do not have `audio` packaged with our builds, and neither we have a specific cut at 1.4 (which also would be pretty old for us).
We can discuss whether we should bundle `audio` as well, but meanwhile can you try if building from source works?

```
!git clone https://github.com/pytorch/audio.git
os.chdir("audio")
!python setup.py install
```

**Comment by laurencejennings** [comment]
thank you very much, this seems to work.

**Comment by dlibenzi** [comment]
We will also be bundling `audio` in our next releases (@jysohn23 ).
