### ISSUE TITLE
[getting-started.ipynb] ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by chrisdoyleIE** [pytorch/xla#1794]
## To Reproduce

1. Open getting-started.ipynb in Colab
2. Run the 1st and 2nd cells
<img width="790" alt="Screenshot 2020-03-22 at 13 01 00" src="https://user-images.githubusercontent.com/44365591/77250064-39fe6680-6c3d-11ea-8196-8c5785cc91a9.png">

## Environment

 - reproducible on XLA backend [CPU/TPU]:
 - torch_xla version:
 - Any other relevant information. In case of issues related to slow executions, re-compilations, etc.., it is useful to have the `tar.gz` report from https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#using-debug_runpy-to-collect-debug-information

**Comment by dlibenzi** [comment]
Are you using `nightly` or `20200220`?
Check the **VERSION** listbox at the right of the first cell ...

**Comment by 6desislava6** [comment]
I'm using `20200325`.
Same problem.

**Comment by liulai** [comment]
> ## 🐛 Can't get the getting-started.ipynb to run....
> ## To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Open getting-started.ipynb in Colab
> 2. Run the 1st and 2nd cells
> 
> <img alt="Screenshot 2020-03-22 at 13 01 00" width="790" src="https://user-images.githubusercontent.com/44365591/77250064-39fe6680-6c3d-11ea-8196-8c5785cc91a9.png">
> 
> ## Expected behavior
> ## Environment
> * reproducible on XLA backend [CPU/TPU]:
> * torch_xla version:
> * Any other relevant information. In case of issues related to slow executions, re-compilations, etc.., it is useful to have the `tar.gz` report from https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#using-debug_runpy-to-collect-debug-information
> 
> ## Additional context

hi, 

> ## 🐛 Can't get the getting-started.ipynb to run....
> ## To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Open getting-started.ipynb in Colab
> 2. Run the 1st and 2nd cells
> 
> <img alt="Screenshot 2020-03-22 at 13 01 00" width="790" src="https://user-images.githubusercontent.com/44365591/77250064-39fe6680-6c3d-11ea-8196-8c5785cc91a9.png">
> 
> ## Expected behavior
> ## Environment
> * reproducible on XLA backend [CPU/TPU]:
> * torch_xla version:
> * Any other relevant information. In case of issues related to slow executions, re-compilations, etc.., it is useful to have the `tar.gz` report from https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#using-debug_runpy-to-collect-debug-information
> 
> ## Additional context

you must update code in the getting-started.ipynb(**add libomp5 and libopenblas-dev packages**):

VERSION = "20200325"  #@param ["1.5" , "20200325", "nightly"]
!curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
!python pytorch-xla-env-setup.py --version $VERSION  --apt-packages libomp5 libopenblas-dev

**Comment by dlibenzi** [comment]
@jysohn23 Can you double check?
`libomp5` is already in the defaults, but `linopenblas-dev` is not ...

**Comment by jysohn23** [comment]
Hmm, I'm not able to repro.

```
VERSION = "20200325"  #@param ["1.5" , "20200325", "nightly"]
!curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
!python pytorch-xla-env-setup.py --version $VERSION

import torch
import torch_xla
```

Just worked fine for me. Mind trying to repro @dlibenzi ?

**Comment by ninjakx** [comment]
@jysohn23 not working on kaggle kernel.

**Comment by jysohn23** [comment]
@ninjakx Can you be more specific? What did you run? Checkout sample examples like these ones: https://www.kaggle.com/c/jigsaw-multilingual-toxic-comment-classification/discussion/143613

This works on Kaggle:
```
!curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
!python pytorch-xla-env-setup.py --apt-packages libomp5 libopenblas-dev
```

**Comment by tzhong518** [comment]
@jysohn23 Hi, I met the same problem, neither of the 1.5,20200325 nor nightly works.
The message during installing torch are as following
`TPU address is grpc://10.111.111.10:8470
Processing ./torchvision-nightly+20200325-cp36-cp36m-linux_x86_64.whl
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from torchvision==nightly+20200325) (1.18.5)
Requirement already satisfied: torch in /usr/local/lib/python3.6/dist-packages (from torchvision==nightly+20200325) (1.5.0a0+d6149a7)
Requirement already satisfied: pillow>=4.1.1 in /usr/local/lib/python3.6/dist-packages (from torchvision==nightly+20200325) (7.0.0)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from torchvision==nightly+20200325) (1.12.0)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from torch->torchvision==nightly+20200325) (0.16.0)
Installing collected packages: torchvision
  Found existing installation: torchvision 0.6.0a0+3c254fb
    Uninstalling torchvision-0.6.0a0+3c254fb:
      Successfully uninstalled torchvision-0.6.0a0+3c254fb
Successfully installed torchvision-0.6.0a0+3c254fb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4264  100  4264    0     0  51373      0 --:--:-- --:--:-- --:--:-- 51373
Updating TPU and VM. This may take around 2 minutes.
Updating TPU runtime to pytorch-1.5 ...
Uninstalling torch-1.5.0a0+d6149a7:
  Successfully uninstalled torch-1.5.0a0+d6149a7
Uninstalling torchvision-0.6.0a0+3c254fb:
  Successfully uninstalled torchvision-0.6.0a0+3c254fb
Copying gs://tpu-pytorch/wheels/torch-1.5-cp36-cp36m-linux_x86_64.whl...
- [1 files][ 79.0 MiB/ 79.0 MiB]                                                
Operation completed over 1 objects/79.0 MiB.                                     
Copying gs://tpu-pytorch/wheels/torch_xla-1.5-cp36-cp36m-linux_x86_64.whl...
- [1 files][106.6 MiB/106.6 MiB]                                                
Operation completed over 1 objects/106.6 MiB.                                    
Copying gs://tpu-pytorch/wheels/torchvision-1.5-cp36-cp36m-linux_x86_64.whl...
/ [1 files][  2.5 MiB/  2.5 MiB]                                                
Operation completed over 1 objects/2.5 MiB.                                      
Processing ./torch-1.5-cp36-cp36m-linux_x86_64.whl
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from torch==1.5) (1.18.5)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from torch==1.5) (0.16.0)
ERROR: fastai 1.0.61 requires torchvision, which is not installed.
Installing collected packages: torch
Done updating TPU runtime: <Response [200]>
Successfully installed torch-1.5.0a0+ab660ae
Processing ./torch_xla-1.5-cp36-cp36m-linux_x86_64.whl
Installing collected packages: torch-xla
  Found existing installation: torch-xla 1.6+e788e5b
    Uninstalling torch-xla-1.6+e788e5b:
      Successfully uninstalled torch-xla-1.6+e788e5b
Successfully installed torch-xla-1.5
Processing ./torchvision-1.5-cp36-cp36m-linux_x86_64.whl
Requirement already satisfied: pillow>=4.1.1 in /usr/local/lib/python3.6/dist-packages (from torchvision==1.5) (7.0.0)
Requirement already satisfied: torch in /usr/local/lib/python3.6/dist-packages (from torchvision==1.5) (1.5.0a0+ab660ae)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from torchvision==1.5) (1.12.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from torchvision==1.5) (1.18.5)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from torch->torchvision==1.5) (0.16.0)
Installing collected packages: torchvision
Successfully installed torchvision-0.6.0a0+3c254fb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libomp5 is already the newest version (5.0.1-1).
The following package was automatically installed and is no longer required:
  libnvidia-common-440
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 59 not upgraded.`
