### ISSUE TITLE
Handling large batch size

### ISSUE THREAD

**Issue by gakshaygupta** [pytorch/xla#1843]
## ❓ Questions and Help
In #1797 I questioned about the IO problem I was facing related to the dataloader. I was able to pinpoint the problem to the Network IO between the CPU VM and TPU VM. The size of the mini-batch for my model is around 1 to 2 GB and it is taking around 20x to 30x more time for IO compared to the forward or backward propagation. Is there a way to increase the Network IO to solve this problem?

**Comment by jysohn23** [comment]
First of all are you using `ParallelLoader`? That will overlap sending batches of data with compile/execution on TPU.

Also in that previous post I see you run with `--num_workers=2` can you try increasing that num_workers if the GCE VM size you're using allows? What's the size of your GCE VM (CPU cores/RAM)?

**Comment by gakshaygupta** [comment]
Yes, I am using ParallelLoader. I tried increasing num_workers and didn't found any performance increase. This is because workers will load the data to the CPU VM ram, not to the TPU VM so the batches still need to be sent to the TPU VM over the network. And the configuration I am using is n1-standard-16 (16 vCPUs, 60 GB memory).

**Comment by jysohn23** [comment]
Depending on the model and dataset, it may take way more CPUs to fully saturate the TPU cores. For example on a ResNet50 model with real data (Imagenet) we need 64+ CPUs to really get the most out of the TPUs. You may want to try see your current CPU utilization, increase VM size and also increase num_workers after that.

Also, you may want to play around with [prefetch size](https://github.com/pytorch/xla/blob/master/torch_xla/distributed/parallel_loader.py#L71-L72) though typically we don't mess with those.

**Comment by gakshaygupta** [comment]
Thanks for the suggestion. I tried a VM with 64 cores and the IO timing decreased. will try using the prefetch size also.

**Comment by gakshaygupta** [comment]
Could you explain what is the effect of loader_prefetch_size and device_prefetch_size in https://github.com/pytorch/xla/blob/master/torch_xla/distributed/parallel_loader.py#L71-L72[]?

**Comment by gakshaygupta** [comment]
> Depending on the model and dataset, it may take way more CPUs to fully saturate the TPU cores. For example on a ResNet50 model with real data (Imagenet) we need 64+ CPUs to really get the most out of the TPUs. You may want to try see your current CPU utilization, increase VM size and also increase num_workers after that.
> 
> Also, you may want to play around with [prefetch size](https://github.com/pytorch/xla/blob/master/torch_xla/distributed/parallel_loader.py#L71-L72) though typically we don't mess with those.

Could you explain what is the effect of loader_prefetch_size and device_prefetch_size in https://github.com/pytorch/xla/blob/master/torch_xla/distributed/parallel_loader.py#L71-L72[]?

**Comment by dlibenzi** [comment]
It is the number of batches we try to send to the device (prefetch), in parallel.
This tends to use multiple TCP channels, so it increases the throughput to the TPU VM, and prefetches data to the device.
This comes at device memory cost though, though the TPU VM has the option to swap out (from device to host memory) the unneeded device memory (which comes at a cost though).
