### ISSUE TITLE
Deep Graph Library on TPUs

### ISSUE THREAD

**Issue by shirinmous** [pytorch/xla#1849]
## ❓ Questions and Help
Hi 
I want to run my code that uses DGL on TPU.
Is it necessary for DGL to support TPUs?

**Comment by dlibenzi** [comment]
The core code should be OK.
You will need to change the train/test scripts to follow the XLA guidelines, especially for multi-processing.
Example code:

https://github.com/pytorch/xla/blob/f07bb0594b8d87162553829e7f2f62b55e9eda81/test/test_train_mp_mnist.py#L171
