### ISSUE TITLE
`torch.nn.functional.cross_entropy` is very slow when doing semantic segmentation

### ISSUE THREAD

**Issue by harpone** [pytorch/xla#1850]
## 🐛 Bug

I am using `F.cross_entropy(logit, target.to(torch.int64))`, where `logit` is shape `[batch_size, target_dim, height, width]` and `target` is shape `[batch_size, height, width]` with integer values.

`F.cross_entropy` requires the torch.int64/torch.long dtype, but I understand TPUs can't handle this dtype well, which might be the cause of the slowdown?

I tried setting `XLA_USE_32BIT_LONG` to 1 but that raises an error because it's the wrong dtype :(

For reference, I get about 2.3 iters/s for `sigmoid_l1_loss` vs. 0.4 iters/s for the `cross_entropy` loss. This is after about 200 iterations, after which there's no change.

## Environment

 - reproducible on XLA backend [CPU/TPU]: TPU
 - torch_xla version: 0.8+c77641f

**Comment by dlibenzi** [comment]
Are you able to post repro code or at least the full error message?
Can you try with nightly? 0.8 is *really* old in pytorch/xla life years 😉

**Comment by harpone** [comment]
Oh wow I thought I updated last week or so... OK I'll update ASAP and will report back.

Don't have the error at hand, but it's the standard error you get when trying to use `torch.int32` or other dtypes in `F.cross_entropy` instead of `torch.int64`.

**Comment by harpone** [comment]
Does gather work fine with `torch-xla` in case I want to implement the cross entropy loss myself with `torch.int32` dtype target?

**Comment by dlibenzi** [comment]
Let's see the error first ...

**Comment by harpone** [comment]
OK I don't really have time to do that now (I work on EU time zones), but will do that tomorrow!

**Comment by harpone** [comment]
OK updated to version 1.6+3c94753 but same thing happens: `F.cross_entropy(logit_this, target_this.to(torch.int64))` gives about 0.4 iters / s.

If I try `F.cross_entropy(logit_this, target_this.to(torch.int32)), I get the standard wrong dtype error:

```
 File "/home/heka/code/pycharm-2342/core/losses.py", line 139, in loss_segmentation_fn
    loss += F.cross_entropy(logit_this, target_this.to(torch.int32))
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/nn/functional.py", line 2338, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/nn/functional.py", line 2138, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: expected scalar type Long but found Int
```

Also same thing whether or not I'm using bfloat16 for floats.

**Comment by harpone** [comment]
Also gather and scatter expect a `LongTensor` dtype so they will not help either :(

**Comment by harpone** [comment]
Just in case others with the same issue stumble here, just using one-hot `target` of shape `[batch_size, num_classes, height, width]` and e.g. the 1hot version of xent segmentation loss below will work well, although this will require somewhat more memory.

```
def cross_entropy_1hot(logit_, target_):
    """One-hot version of cross entropy, because int `target_` version not working fast on torch-xla.

    :param logit_: shape [B, n_classes, H, W]; dtype torch.float32
    :param target_: shape [B, n_classes, H, W]; dtype torch.int32
    :return loss: scalar
    """
    log_smax = F.log_softmax(logit_, dim=1)
    loss = -(target_ * log_smax).sum(1).mean()

    return loss
```

**Comment by dlibenzi** [comment]
It is *very* hard to debug with repro code.
Can you show me the error when you set `XLA_USE_32BIT_LONG=1`?
While it is true that int64 is not native TPU type, in many cases it just works with little performance penalty.
Is there any way you can drop some repro code in a copy of this Colab template?

https://github.com/pytorch/xla/blob/master/contrib/colab/issue-report.ipynb

**Comment by dlibenzi** [comment]
Also, about the speed.
We want to make sure there are no surprised such that we suddenly go to PyTorch/CPU for an op, so maybe a metrics report can tell us something.
CrossEntropyLoss has been fully supported (and AFAIK performing well) for a while, but sometimes PyTorch changes things from underneath us.

**Comment by harpone** [comment]
OK I can take a look at the Colab later... now I'm a bit scrambling to meet a deadline :/

Anyway, since `F.cross_entropy` uses `gather` under the hood (I think), this is probably related to #898

**Comment by dlibenzi** [comment]
The gather issue on that thread has been solved AFAIK.
I have tried the repro code on that issue with `XLA_USE_32BIT_LONG=1` on both TPU and CPU, and they seem OK.

```Python
import torch
import torch_xla
import torch_xla.core.xla_model as xm
import torch_xla.debug.metrics as met

VOCAB_SIZE = 30522

device = xm.xla_device()
ids = torch.LongTensor(32, 20, VOCAB_SIZE).random_(0, 127).to(device)
labels = torch.LongTensor(32, 20).random_(0, VOCAB_SIZE - 1).to(device)
preds = torch.rand(32, 128, VOCAB_SIZE, requires_grad=True, device=device)

gathered_preds = preds.gather(1, ids)
loss = torch.nn.functional.cross_entropy(gathered_preds.view(-1, VOCAB_SIZE), labels.view(-1))
loss.backward()

print('PREDS.GRAD:\n', torch_xla._XLAC._get_xla_tensors_hlo([loss, preds.grad]))
print('LOSSA', loss.cpu())
print(met.metrics_report())
```

**Comment by harpone** [comment]
OK good to know! Seems about same order of magnitude I'm doing, except that I have 2D data, this is 1D. I'll try the Colab as soon as I can (may take a week though).

**Comment by dlibenzi** [comment]
You can also play with `XLA_DENSE_GATHER_FACTOR`.
We can use two gather implementations, depending on how many elements in the input tensor you are gathering.
The Sparse version (the real XLA gather) is slower when selecting many elements.
Currently we use Sparse if `gather_indices_size < input_size / FACTOR`.
But the default value should already give you best performance.

**Comment by harpone** [comment]
Uhh tried it on the colab notebook and `F.cross_entropy` is definitely about 15% faster than my `cross_entropy_1hot` for `[128, 64, 64]`, so there must be something funny with the rest of my code :/

Closing. Will reopen if it turns out to be a problem with torch-xla after all.
