### ISSUE TITLE
Confirming PyTorch XLA MT is deprecated?

### ISSUE THREAD

**Issue by tmabraham** [pytorch/xla#1871]
I see that the PyTorch XLA MT API was removed from API_USAGE_GUIDE.md as it was deprecated but it seems like DataParallel is still available and documented in the official PyTorch docs. Is PyTorch XLA MT officially deprecated?

If so, what was the reasoning behind this?

**Comment by dlibenzi** [comment]
We will drop it from the documentation.

**Comment by taylanbil** [comment]
It is typically considerably slower compared to MP, so the recommended way is MP.

**Comment by tmabraham** [comment]
@dlibenzi Oh ok. Is there a reason this interface is deprecated? Is it just due to lack of usage? 
Also, I read that while multithreading is slower, it uses less memory, so wouldn't multithreading be useful for more memory-intensive tasks?

**Comment by dlibenzi** [comment]
> @dlibenzi Oh ok. Is there a reason this interface is deprecated? Is it just due to lack of usage?
> Also, I read that while multithreading is slower, it uses less memory, so wouldn't multithreading be useful for more memory-intensive tasks?

We prefer not to confuse users and suggest them to use MP.
Keeping MT alive and fully support can limit us on the interfaces.
So far it should still everything work.

**Comment by tmabraham** [comment]
@dlibenzi Ok thanks for the clarification.
