### ISSUE TITLE
Tpu won't run with Unknown issue but runs well with n_procs =1

### ISSUE THREAD

**Issue by level14taken** [pytorch/xla#1911]
## ❓ Questions and Help
Hi, the code given below works well when n_procs changed to 1, but keeps running and never halts for 8 nprocs, 
The code works for n_procs=8 when this line is changed,i.e  another architecture is used like this 
`model = smp.Unet().to(device)` changed to `model = unet().to(device)`

The code never really exectued beyond this line `model =smp.Unet().to(device)`
I can't debug what is happening, 

```
def train_resnet34():
  torch.manual_seed(1)

  transform_train = transforms.Compose([     
      transforms.ToTensor(),
  ])
  
train_ind= list(range(len(file_list)))
  kf = StratifiedKFold(7, shuffle=True, random_state=0)
  for fold, (trn_idx, val_idx) in enumerate(kf.split(train_ind, coverage)):
      xm.master_print('*******************   fold  %d   *******************' % fold)
    
      train = TGSSaltDataset(train_path, file_list_train)
      
      train_sampler = torch.utils.data.distributed.DistributedSampler(
          train,
          num_replicas=xm.xrt_world_size(),
          rank=xm.get_ordinal(),
          shuffle=True)
      
      train_loader = torch.utils.data.DataLoader(
          train,
          batch_size=FLAGS['batch_size'],
          sampler=train_sampler,
          num_workers=FLAGS['num_workers'],
          drop_last=False)
      
      learning_rate = FLAGS['learning_rate'] 
      device = xm.xla_device()
      model = R_unet().to(device)
      loss_fn = FocalLoss()
      optimizer = torch.optim.Adam(model.parameters(),lr=  learning_rate)
      def train_loop_fn(loader):
        model.train()
        for x, (image, mask) in enumerate(loader): 
          y_pred = model(image)
          loss = loss_fn(y_pred, mask)
          optimizer.zero_grad()
          loss.backward()
          xm.optimizer_step(optimizer)

        return loss.item(),IOU
      
      for epoch in range(1, FLAGS['num_epochs'] + 1):
        para_loader = pl.ParallelLoader(train_loader, [device])
        train_loss,train_iou=train_loop_fn(para_loader.per_device_loader(device))
        
  return None
```
I tried changing batch size from 64 to 16 but it didn't work
unet(300MB),smp.Unet(180MB)

**Comment by dlibenzi** [comment]
We have no information to even try to reproduce the issue.
If you can create a repro according to the general guidance we outline here, we can take a look:

https://github.com/pytorch/xla/blob/master/contrib/colab/issue-report.ipynb

**Comment by satyajitghana** [comment]
can confirm this happens, but difficult to reproduce, if ever i see that colab is not working on nproc=8 and as soon as i make it nproc=1, it starts working, this bug happens on most of my colab sessions

**Comment by dlibenzi** [comment]
Without a small Colab repro we cannot diagnose unfortunately.

**Comment by satyajitghana** [comment]
so i ran a sample train.py
most of the time it gets stuck at `Waiting to connect to client mesh master` , and sometimes it SIGSEGV's

related issues:
https://discuss.pytorch.org/t/pytorch-xla-exception-sigsegv/61771
https://github.com/PyTorchLightning/pytorch-lightning/issues/1090

**Comment by satyajitghana** [comment]
how do i print more info about the TPU assigned to me in colab ? couldn't find much docs on that, something like nvidia-smi

**Comment by dlibenzi** [comment]
We have revised the bootstrap code for Colab, to make things simpler.
Can you try to start with this as base:

https://github.com/pytorch/xla/blob/master/contrib/colab/mnist-training.ipynb

**Comment by satyajitghana** [comment]
okay so i narrowed down my problem to this : `model = ResUNet().to(device)` <- all the tpu cores are stuck at this, i'm not sure why, it was working before tpu core:0 is spawed at the end (after all the other 7 are spawned) , could that be problem ? before(when the model 'was' working) the tpu core:0 had spawned first

**Comment by satyajitghana** [comment]
```
def train_model():
    print(f'{xm.get_ordinal()}, {xm.is_master_ordinal()}')

    if not xm.is_master_ordinal():
        # Barrier: Wait until master is done downloading
        xm.rendezvous('download_only_once')

    if xm.is_master_ordinal():
        # Barrier: Master done downloading, other workers can proceed
        xm.rendezvous('download_only_once')
```
```
def _mp_fn(rank):
    train_model()
xmp.spawn(_mp_fn, nprocs=8, start_method='fork')
```

this is all i'm doing, and the cell is stuck here
as per my understanding xm.rendezvous takes a str a input just to keep track of name of barrier, so when the master ordinal releases the barrier the rest can proceed. but here all of them are stuck

**Comment by satyajitghana** [comment]
> We have revised the bootstrap code for Colab, to make things simpler.
> Can you try to start with this as base:
> 
> https://github.com/pytorch/xla/blob/master/contrib/colab/mnist-training.ipynb

this works !

so i wondered if i put my experimental code here, will it work ? 
yesss !!
```
0, True
3, False
6, False
4, False
7, False
5, False
1, False
2, False
```

it works !, the same code does not work in my other colab file

basically if the master ordinal is spawned first, everything is fine, else it goes on forever ever yielding any output

**Comment by satyajitghana** [comment]
can confirm !, run the colab file using this code
```python
def train_model():
    print(f'{xm.get_ordinal()}, {xm.is_master_ordinal()}')

    if not xm.is_master_ordinal():
        # Barrier: Wait until master is done downloading
        xm.rendezvous('download_only_once')

    if xm.is_master_ordinal():
        # Barrier: Master done downloading, other workers can proceed
        xm.rendezvous('download_only_once')
```

and if the master ordinal does not get spawned first, the cell will run forever

**Comment by satyajitghana** [comment]
update

```
---> 14 xmp.spawn(_mp_fn, nprocs=8, start_method='fork')

2 frames
/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py in join(self, timeout)
    117         msg = "\n\n-- Process %d terminated with the following error:\n" % error_index
    118         msg += original_trace
--> 119         raise Exception(msg)
    120 
    121 

Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 116, in _start_fn
    _setup_replication()
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 108, in _setup_replication
    device = xm.xla_device()
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 137, in xla_device
    devkind=[devkind] if devkind is not None else None)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 41, in get_xla_supported_devices
    xla_devices = torch_xla._XLAC._xla_get_devices()
RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:1198 : Check failed: session.Run({tensorflow::Output(result, 0)}, &outputs) == ::tensorflow::Status::OK() (Already exists: From /job:tpu_worker/replica:0/task:0:
Resource localhost/tpu_proto_cache/N10tensorflow17TpuIsaProtoLookupE
	 [[{{node configure_distributed_tpu/_0}}]] vs. OK)
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	xla::XrtComputationClient::InitializeAndFetchTopology(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tensorflow::ConfigProto const&)
	xla::XrtComputationClient::InitializeDevices(std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
	xla::XrtComputationClient::XrtComputationClient(xla::XrtComputationClient::Options, std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
	xla::ComputationClient::Create()
	xla::ComputationClient::Get()
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	
	
	
	_PyObject_FastCallKeywords
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
*** End stack trace ***
```

**Comment by dlibenzi** [comment]
Can you please provide a full Colab notebook for us to test?
No code snippet. Fully working (or not) Colab.

**Comment by satyajitghana** [comment]
> Can you please provide a full Colab notebook for us to test?
> No code snippet. Fully working (or not) Colab.

will try to get a colab session which causes this issue persistently.

as of now, its working again, i have no clue what was causing the problem, i did no change to my code, just restarted the runtime a few times, and now it works.

**Comment by jhillhouse92** [comment]
> ```
> def train_model():
>     print(f'{xm.get_ordinal()}, {xm.is_master_ordinal()}')
> 
>     if not xm.is_master_ordinal():
>         # Barrier: Wait until master is done downloading
>         xm.rendezvous('download_only_once')
> 
>     if xm.is_master_ordinal():
>         # Barrier: Master done downloading, other workers can proceed
>         xm.rendezvous('download_only_once')
> ```
> 
> ```
> def _mp_fn(rank):
>     train_model()
> xmp.spawn(_mp_fn, nprocs=8, start_method='fork')
> ```
> 
> this is all i'm doing, and the cell is stuck here as per my understanding xm.rendezvous takes a str a input just to keep track of name of barrier, so when the master ordinal releases the barrier the rest can proceed. but here all of them are stuck

Thanks @satyajitghana, this fixed the issue for me using xmp. I was also able to get it running with `multiprocessing` and `ProcessPoolExecutor` from `concurrent.futures` but there were issues with my training code and the concurrent library didn't reveal it like xmp did.
