### ISSUE TITLE
xmp.spawn to accept more values for nprocs argument

### ISSUE THREAD

**Issue by anhmeow** [pytorch/xla#1915]
Currently on Google Colab, xmp.spawn accept  1 or 8 for nprocs parameter (number of TPU cores to use).

Because of environment setup, especially available RAM, running on 8 TPU cores is not always feasible but downscaling to 1 is limiting.

Would it be possible to provide values such as 2, 3, ..., 6, 7.
More generally, if there are N TPU cores, it would be great to specify a value between 1 and N.

**Comment by dlibenzi** [comment]
Unfortunately only 1 or 8 are supported by the HW/SW.

**Comment by anhmeow** [comment]
ok, understand, too bad

**Comment by dlibenzi** [comment]
There is a current thread where some hints can be found to try to minimize memory: https://github.com/pytorch/xla/issues/1870

**Comment by anhmeow** [comment]
Thanks, it managed to get it work (on Kaggle) : using nightly build and bfloat.

But, i'm not clear on bfloat : 
torch.tensor(480, dtype=torch.bfloat16)
torch.tensor(481, dtype=torch.bfloat16)

The two lines outputs the same 480 value : 
tensor(480., dtype=torch.bfloat16)

Is that normal with bfloat ?

**Comment by dlibenzi** [comment]
It is expected, given the 7 bit fraction component.

![image](https://user-images.githubusercontent.com/14933084/79262148-aee04d00-7e45-11ea-885c-d8329952eb7e.png)

**Comment by gridcellcoder** [comment]
I was hoping for some help please, I'm trying to run a simple rosenbrock optimization and I wanted to comment here before opening a new issue.

```python
import torch.optim as optim
from torch.autograd import Variable
import torch_xla.distributed.data_parallel as dp
import torch_xla.core.xla_model as xm
import torch_xla.distributed.parallel_loader as pl
import torch_xla.distributed.xla_multiprocessing as xmp

!cat /proc/cpuinfo | grep processor | wc -l
# returns 40

def model(x,y):
    return (1 - x) ** 2 + 100 * (y - x ** 2) ** 2

def _mp_fn(index):
  device = xm.xla_device()

  x = Variable(torch.rand(1, 1, device=device), requires_grad=True)
  y = Variable(torch.rand(1, 1, device=device), requires_grad=True)
  optimizer = torch.optim.Adam([x, y], lr=1e-2)

  for t in range(5):
    print(t)
    # Compute and print loss.
    optimizer.zero_grad()
    loss = model(x,y).to(device)
    print(loss)
    loss.backward()
    xm.optimizer_step(optimizer)

xmp.spawn(_mp_fn, args=(), start_method='fork', nprocs=8)
```

in colab, when `nprocs=1` it works but nothing happens, colab keeps spinning with no output when `nprocs=8` is this a limitation of colab or perhaps something wrong in the implementation above for multi processes?

It works fine in single device/single process.

I'm also using `start_method='fork'` as suggested in other issues. Thanks

**Comment by dlibenzi** [comment]
This works for me:
```Python
import time
import torch
import torch.optim as optim
import torch_xla.distributed.data_parallel as dp
import torch_xla.core.xla_model as xm
import torch_xla.distributed.parallel_loader as pl
import torch_xla.distributed.xla_multiprocessing as xmp

def model(x, y):
    return (1 - x) ** 2 + 100 * (y - x ** 2) ** 2

def _mp_fn(index):
  device = xm.xla_device()

  x = torch.rand(1, 1).to(device).requires_grad_()
  y = torch.rand(1, 1).to(device).requires_grad_()
  optimizer = torch.optim.Adam((x, y), lr=1e-2)

  for t in range(5):
    optimizer.zero_grad()
    loss = model(x, y)
    loss.backward()
    xm.optimizer_step(optimizer, barrier=True)
    print(time.time(), index, t, '{:.4f}'.format(loss.item()), flush=True)

  xm.rendezvous('exit')

xmp.spawn(_mp_fn, args=(), start_method='fork', nprocs=8)
```

But, there is currently a bug (just fixed) in the replication setup code, which does not setup replication correctly, so cores train disjointly.

**Comment by gridcellcoder** [comment]
Thanks so much, just tested it and works really fast, that colab output can't keep up! Please can you link to the replication code bug, it would help to keep track.
