### ISSUE TITLE
fp16 (not bf16) support

### ISSUE THREAD

**Issue by bobzhuyb** [pytorch/xla#1936]
## 🚀 Feature

Request for supporting FP16 for XLA+CUDA

## Motivation

I was playing with PyTorch+XLA+CUDA and managed to run https://github.com/pytorch/xla/blob/master/test/test_train_imagenet.py, both with XLA+CUDA and natively on CUDA (with some quick modification). Then I tried to test the performance with fp16, and found that current implementation does not support it. I see that bf16 is supported. However, unfortunately, many GPUs do not support it.

Quick reproduce:
```
import torch
import torch_xla.core.xla_model as xm
d = xm.xla_device()
x = torch.rand(8, 5).to(device=d, dtype=torch.float16)
```
This throws:
```
2020-04-20 16:22:11.841534: E tensorflow/compiler/xla/xla_client/tf_logging.cc:11] Type not supported: Half
```

A quick check shows that https://github.com/pytorch/xla/blob/master/torch_xla/csrc/tensor_util.cpp#L820 does not support Half for now.

## Pitch

Is it possible to add fp16 support to tensor_util.cpp?

**Comment by dlibenzi** [comment]
We are about to make XLA GPU support more available soon.
The vast majority is already there, like you have noticed.
We need to add multi-GPU all-reduce support, and automate our wheel/docker builds to build with GPU support as well.

**Comment by bobzhuyb** [comment]
Thanks. I am going to test the master branch.

**Comment by bobzhuyb** [comment]
@dlibenzi Would you tell me which PyTorch commit number are you using that is relatively stable? 

I am using pytorch-xla commit https://github.com/pytorch/xla/commit/3cdcf810427a6bb9a4d04d962b4b82e1334bc665
and pytorch commit https://github.com/pytorch/pytorch/commit/7f50162d1e095c7b84de73e023983a23bea41130 (for this I just randomly chose one recent commit)

I got this compilation error:
```
torch_xla/csrc/aten_xla_type_default.cpp:9676:20: error: use of undeclared identifier 'aten'; did you mean 'atan'?
TORCH_LIBRARY_IMPL(aten, XLA, m) {
                   ^~~~
                   atan
/usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/math.h:41:12: note: 'atan' declared here
using std::atan;
           ^
torch_xla/csrc/aten_xla_type_default.cpp:9676:1: error: C++ requires a type specifier for all declarations
TORCH_LIBRARY_IMPL(aten, XLA, m) {
^
torch_xla/csrc/aten_xla_type_default.cpp:9676:26: error: use of undeclared identifier 'XLA'
TORCH_LIBRARY_IMPL(aten, XLA, m) {
                         ^
torch_xla/csrc/aten_xla_type_default.cpp:9676:31: error: use of undeclared identifier 'm'
TORCH_LIBRARY_IMPL(aten, XLA, m) {
                              ^
torch_xla/csrc/aten_xla_type_default.cpp:9676:33: error: expected ';' after top level declarator
TORCH_LIBRARY_IMPL(aten, XLA, m) {
                                ^
                                ;
5 errors generated.
/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/cpp_extension.py:306: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
error: command 'clang-8' failed with exit status 1```

I was following the steps you updated here https://github.com/pytorch/xla/issues/1448#issuecomment-567974633

It worked fine last time I built it

**Comment by dlibenzi** [comment]
PyTorch/XLA and PyTorch are tightly coupled, and you likely pulled PyTorch/XLA by leaving PyTorch behind.
I saw the very same error in my workstation yesterday, and pulling PyTorch HEAD fixed it.

**Comment by bobzhuyb** [comment]
@dlibenzi Thanks. The build passed again after trying a few different commits.

However, I got this error `Unable to lower scalar 0 of shape f16[]` threw from here

https://github.com/pytorch/xla/blob/master/torch_xla/csrc/ops/scalar.cpp#L84

**Comment by dlibenzi** [comment]
https://github.com/pytorch/xla/pull/1971 should fix that.

**Comment by bobzhuyb** [comment]
@dlibenzi Thank you. 

Now I am hitting the following. Not sure is it because the training code or some issue similar to https://github.com/pytorch/xla/issues/1330#issuecomment-555347771

```
Exception in model function for device=xla:1: _th_equal not supported on CPUType for Half
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/data_parallel.py", line 104, in _module_runner
    result.result = loop_fn(module, loader, torch.device(device), context)
  File "/opt/tiger/arnold_toolbox/arnold_examples/pytorch_xla/test_train_imagenet.py", line 200, in train_loop_fn
    xm.optimizer_step(optimizer)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/core/xla_model.py", line 538, in optimizer_step
    loss = optimizer.step(**optimizer_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py", line 67, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/optim/sgd.py", line 99, in step
    d_p = d_p.add(p, alpha=weight_decay)
RuntimeError: _th_equal not supported on CPUType for Half
```

The training code (just a few lines different from your imagenet example)
https://github.com/bobzhuyb/xla/commit/e7c7bcbb224cfc5a707d1e2315218764e03142b9

**Comment by dlibenzi** [comment]
Just missing an entry here:

https://github.com/pytorch/xla/blob/d7236c302530bf863a2a9aa5863452da0eb7e90d/torch_xla/csrc/tensor_util.cpp#L676

Will do tomorrow.

**Comment by dlibenzi** [comment]
https://github.com/pytorch/xla/pull/1987

**Comment by bobzhuyb** [comment]
@dlibenzi Thank you. Now my FP16 version (linked in my previous post) can run.
