### ISSUE TITLE
Any interest in CMake build files?

### ISSUE THREAD

**Issue by cjolivier01** [pytorch/xla#1957]
## ❓ Questions and Help
I've been working with some cmake build files I've made that actually build pytorch, tensorflow (via bazel launch), xla and the xla tests (includes current CMakelists.txt) for some time now.  If there's interest, I can clean them up -- maybe leave out the pytorch part, whatever.
I've had some experience with this as I created and managed the cmake stuff for mxnet for a couple of years (not the CI -- just the cmake stuff since I pulled it together in order to use CLion).
Mine also loads cmakelists generated from tensorflow so it can be loaded in CLion and indexed via bazel-cmakelists, etc.

**Comment by dlibenzi** [comment]
For us the main (in terms of LOC count) build is `Tensorflow`, and that is `Bazel` native.
For the other part I personally like `setuptools`, and being able to do build machinery in `Python` WRT the kinda odd `cmake` scripting.

**Comment by cjolivier01** [comment]
Just to clarify, uses bazel to build TF, launched via cmake as a target, not building tf directly with native cmake files. Same idea as done with setup.py.
Anyway, thanks for the input.
