### ISSUE TITLE
Someone can help me get TPU support to this project?

### ISSUE THREAD

**Issue by kirkgutierrdd** [pytorch/xla#1964]
## ❓ Questions and Help

Hey guys
I am not into the development era but I dont have a small hobby I like to enhance and colorize films whatever its with "Topaz Enhance Ai v1.2.1" or with "DeOldfy" and I want to use DeepRemaster Ai on a tpu... but it just aint working for me I guess
https://github.com/satoshiiizuka/siggraphasia2019_remastering

I know this section is not for help but common you spend hours on Ai :) you understand which lines I should modifie I know that I wont learn anything from but common I have no interest into be an Ai reseach all I want is a TPU support :)

I found this Colab that teaches us how to install PyTouch-XLA 
https://colab.research.google.com/drive/1_FbJ3tyvhdXzRBAJLn9bKM9CuDUV1_uc#scrollTo=Zj-yv-Mxe6Yz&forceEdit=true&sandboxMode=true
But I am still not there yet...
Here is a colab I made for using it in a gpu 
https://colab.research.google.com/github/kirkgutierrdd/DeepRemaster-Colab-notepad/blob/master/DeepRemaster.ipynb
(Make sure the "runtime" is on a TPU if you wanna try a TPU)

Thanks :)

**Comment by kirkgutierrdd** [comment]
Bump I guess :/

**Comment by ailzhang** [comment]
Hi @kirkgutierrdd  what's the issue here? Did you install `torch_xla` as shown in the example notebook?

**Comment by kirkgutierrdd** [comment]
> Hi @kirkgutierrdd what's the issue here? Did you install `torch_xla` as shown in the example notebook?

Yes I did, but I dont understand which line to use :/

**Comment by kirkgutierrdd** [comment]
> Hi @kirkgutierrdd what's the issue here? Did you install `torch_xla` as shown in the example notebook?

Please help me :) I just want to restore some old footage ;)

**Comment by ailzhang** [comment]
@kirkgutierrdd I couldn't find a clear description of what's the reported issue / question so it'll be lower priority compared to other issues in our queue.

**Comment by kirkgutierrdd** [comment]
> @kirkgutierrdd I couldn't find a clear description of what's the reported issue / question so it'll be lower priority compared to other issues in our queue.

Can I jplease help getting TPU working on this thing I am really not a developer or good with this kind of stuff just want to restore old footage
