### ISSUE TITLE
About setting up the Optimizer

### ISSUE THREAD

**Issue by shizhediao** [pytorch/xla#1967]
## ❓ Questions and Help
I found that in the mnist example, the optimizer is set by the following command.

> optimizer = context.getattr_or(  
> 'optimizer',  
> lambda: optim.SGD(model.parameters(), lr=lr, momentum=FLAGS.momentum))

I was wondering what's the function of context.getattr_or
Could I just use
`optimizer = optim.SGD(model.parameters(), lr=lr, momentum=FLAGS.momentum))`
to define my optimizer?

**Comment by dlibenzi** [comment]
Seems like you based your code upon the old (deprecated) multi-thread based DataParallel.
In that case, yes, such code would be necessary.
But we recommend using the new multi-process based interface, like in this example:

https://github.com/pytorch/xla/blob/master/test/test_train_mp_mnist.py

**Comment by shizhediao** [comment]
> Seems like you based your code upon the old (deprecated) multi-thread based DataParallel.
> In that case, yes, such code would be necessary.
> But we recommend using the new multi-process based interface, like in this example:
> 
> https://github.com/pytorch/xla/blob/master/test/test_train_mp_mnist.py

Yes, you are right. I'm using the multi-thread one.
Thanks for your suggestion. I will try the multi-process one.
One small thing, if I have multiple models, let's say, I have 4 models: Model_{a,b,c,d}
How to put these 4 models into the device.
I think in the multi-process one, it's not hard. I can use model_a.to(device), model_b.to(device) and so on, am I correct?

If I use a multi-thread one, what I am doing is like this: I create an instance of a nn.Module and put it to the device by using parallel.

```
class SUPER_MODEL(nn.Module):
  def __init__(self, model_a, model_b, model_c, model_d):
    super(SUPER_MODEL, self).__init__()
    self.a = model_a
    self.b = model_b
    self.c = model_c
    self.d = model_d
super_model = SUPER_MODEL(model_a, model_b, model_c, model_d)
model_parallel = dp.DataParallel(super_model, device_ids=devices)
```

It is a correct implementation?
Thanks!
