### ISSUE TITLE
Choosing the batch_size

### ISSUE THREAD

**Issue by shizhediao** [pytorch/xla#1968]
## ❓ Questions and Help
Is it a must to set the batch_size as the exact times of the number of processes/threads?
In other words, may I set batch_size=12 when I have 8 threads.

**Comment by taylanbil** [comment]
Per core batch size is unrelated to number of cores, and can be set independently.

Without code / repro, hard to help, but if you're referring to `test_train_imagenet.py`, that batch size is per core, in that file, so can be set independently.

Let me add finally that the recommendation is to use multi-processing over multi-threading.

**Comment by shizhediao** [comment]
Yeah, I have moved to multi-processing.
I just want to clarify: in multi-threading, referring to test_train_imagenet.py, can I set batch_size=12 when I have 8 cores?
