### ISSUE TITLE
What's the function of xm.rendezvous()?

### ISSUE THREAD

**Issue by shizhediao** [pytorch/xla#1976]
## ❓ Questions and Help
I was confused when do we need this function and how it works?
I see this function usually in download to avoid downloading many time.
Are there any other situations we need it?

**Comment by taylanbil** [comment]
Rendezvous is used to synchronize the parallel processes. `torch_xla` uses `xm.rendezvous` underneath, when doing things like model saving, or mesh reduce.

Using it to only download from one process only is a clever trick. You may use it in similar situations when you want to do one long running thing from one process only, or whenever you want the processes to wait for one another and synchronize.

**Comment by shizhediao** [comment]
Do we need to synchronize all processes explicitly by xm.rendezvous()?
In test_train_mp_mnist.py, I do not find xm.rendezvous() but in my code, I found that different processes are in different steps (see below), Is it normal?
This is my log:
> Device: 0, at step 2 of epoch 1.
> Device: 0, at step 2 of epoch 1.
> Device: 0, at step 2 of epoch 1.

**Comment by taylanbil** [comment]
It is highly recommended to use `pl.ParallelLoader` in multi-processing. Parallel loader will automatically mark steps and take care of the synchronization for you, so every process stays in the same step.

Without looking at the code, it's not possible to comment on what's going on that produces the logs above, but generally, no, it's not normal, and all processes should be in the same step at a given time.

**Comment by ultrons** [comment]
@shizhediao , Under xla/contrib/colab/mnist-training.ipynb, you can find a really simple but illustrative example of using xm.rendezvous. Look for "download_only_once". Synchronization among thread is done on need basis. In that example we want only the master ordinal to download the data and make sure rest of the thread wait until that download is finished. you can notice, how xm.rendezvous is used to do that.

**Comment by shizhediao** [comment]
Got it.
Thanks!

**Comment by Jeevesh8** [comment]
Where can I find docs corresponding to xm.rendezvous() ? I saw [this example](https://github.com/pytorch/xla/blob/master/contrib/colab/multi-core-alexnet-fashion-mnist.ipynb), and in the second code cell argument to xm.rendezvous is 'init' . I think it is erroneous because the cell just keeps running and running. What is the meaning of these arguments in terms of behavior ?

**Comment by dlibenzi** [comment]
A rendezvous is a barrier that all replicas (unless you use replica groups) must join below they can all move along.
If a rendezvous keep running there is some bug somewhere else in the code.

**Comment by Jeevesh8** [comment]
Thank you. I understand now. What is the meaning of different arguments(like 'init' ; 'download_only_once'), though ?

**Comment by dlibenzi** [comment]
They are names/tags for the rendezvous operation.
No special meaning.

**Comment by Jeevesh8** [comment]
Meaning the behavior of rendezvous is same in both cases ?
