### ISSUE TITLE
Accessing "original" Tensor from Compile

### ISSUE THREAD

**Issue by cjolivier01** [pytorch/xla#1978]
## ❓ Questions and Help

Is there a canonical way to access the original Tensor for the list of XLATensors passed to XLATensor::Compile() ?  In order to access their attributes such as from is_leaf(), requires_gradient() ?
Seems 

To be honest, I don't fully understand what's the difference between tensor_data, view and ir_value as a state of XLATensor::Data.  XLATensor seems created via an impl hook and often never "sees" the original Tensor object? I haven't come across many situations in the main training graph so far where the tensor_data member of XLATensor::Data is set (i.e. where Tensor is passed ot the constructor).  

Any insight would be very helpful.

**Comment by dlibenzi** [comment]
There is not.
You will have to change the code to pass down the at::Tensors from init_python_bindings.cpp, and unwrap the XLATensor from inside the tensor.cpp file (and keep mapping around in all the relevant tensor.cpp code).

**Comment by cjolivier01** [comment]
Thank you!  Will do.
