### ISSUE TITLE
PyTorch/XLA tracing

### ISSUE THREAD

**Issue by a2bhulla** [pytorch/xla#1984]
## ❓ Questions and Help
How is the python code in pytorch traced and used to build a graph? 

I was also wondering why pytorch/xla is a tensor backend of Pytorch rather than accepting a JIT traced graph and if this supports capturing of control flow?

Thanks!

**Comment by ailzhang** [comment]
Pytorch/xla trace the python ops and build the graph, this logic sits in op lowering code inside pytorch/xla. 
It's a lazy tensor backend for pytorch see http://pytorch.org/xla/release/1.5/index.html#xla-tensors-are-lazy. The main difference from JIT tracing is pytorch/xla support eager mode without user explicitly trace the graph.

**Comment by a2bhulla** [comment]
Thanks for the help!

Another question I had was about support for control flow. Since the python ops are traced would those be captured?

**Comment by ailzhang** [comment]
@a2bhulla Control flow is not captured in the graph, graph will only contain what has been executed. 
In the cases like `if tensor[i] == 1:` case, it'll automatically trigger graph execution to calculate `tensor[i]` and then proceed to the right branch.

**Comment by a2bhulla** [comment]
Thanks!
