### ISSUE TITLE
XLAGuardImpl registry

### ISSUE THREAD

**Issue by a2bhulla** [pytorch/xla#1985]
## ❓ Questions and Help
How does XLAGuardImpl get registered in the  DeviceGuardImplRegistrar?

**Comment by ailzhang** [comment]
are you asking about https://github.com/pytorch/xla/blob/dc954831aade2e570fd38e992b64b4e81f3f2246/torch_xla/csrc/tensor_impl.cpp#L49?

**Comment by a2bhulla** [comment]
Yes but specifically how does this get linked to pytorch when building from sources

**Comment by ailzhang** [comment]
Please take a look at https://github.com/pytorch/xla/blob/master/setup.py for linking to pytorch.
