### ISSUE TITLE
Does it support Quant Noise?

### ISSUE THREAD

**Issue by mrm8488** [pytorch/xla#1986]
## ❓ Questions and Help
Does it support Quant Noise for training RoBERTa like models?

**Comment by ailzhang** [comment]
cc: @taylanbil

**Comment by taylanbil** [comment]
It seems quant noise was added to fairseq pretty recently. Our working branch https://github.com/pytorch-tpu/fairseq/tree/tpu is based on an older upstream, so it does not have it.

AFAIK we have not experimented at all w/ quantization, so I'm not sure if it would work out of the box. Definitely worth a try.
