### ISSUE TITLE
Colab crashes while accessing XLA_CPU

### ISSUE THREAD

**Issue by ailzhang** [pytorch/xla#2004]
The following code snippet passes on my local dev machine, but it crashes on Colab. 
https://colab.research.google.com/drive/1_7MbMUW2R0a8ZdM-jBajJ_kh_243DAGb

**Comment by dlibenzi** [comment]
I don't think we have ever tried that ... or if even that makes much sense 😄

**Comment by ailzhang** [comment]
It turns out to be missing envs `XRT_DEVICE_MAP="CPU:0;/job:localservice/replica:0/task:0/device:XLA_CPU:0" XRT_WORKERS="localservice:0;grpc://localhost:40935"`, closing.
