### ISSUE TITLE
Matching source and updated weight tensors?

### ISSUE THREAD

**Issue by cjolivier01** [pytorch/xla#2008]
## ❓ Questions and Help
Hi, sorry to bother y'all again.
I was wondering, is there a way, from within the torch_xla/csrc base, to match up the input and output weight/bias tensors?  Either from input->output or visa versa?  For example, for  a simple mnist single-fc network, I'll have as inputs to the network, (feature, label, fc_weight, fc_bias) and as outputs, (loss, new_fc_weight, new_fc_bias).  I would need to, either via tensor or node (or some other means besides physically walking the graph, which I think wouldn't be reliable), to match up that in2 matches to out1 and in3 matches to out2 (in this case).  

Acceptable times to determine or track this would be anywhere -- directly from tensors, aliasing(?), lowering of outputs, creating parameter, anywhere.  Preferably not in the python layer, however.

Any help would be greatly appreciated.

**Comment by dlibenzi** [comment]
We are already doing it, when we setup the aliases:

https://github.com/pytorch/xla/blob/631182a313d5566e16ff1be4e9302dd79f5b6ca5/torch_xla/csrc/tensor.cpp#L1408

**Comment by cjolivier01** [comment]
Thank you!
