### ISSUE TITLE
Using multiple TPU nodes for distributed training

### ISSUE THREAD

**Issue by giannisdaras** [pytorch/xla#2010]
## ❓ Questions and Help
Hi!
I am sorry for troubling you with this, but I want to be sure if something can happen or not and I can't seem to find it.

I have access to multiple v3-8 TPUs on us-central1-a zone. However, as far as I know, in this zone you cannot create v3-8 pods, only v3-8 nodes.
So my question is this: Can I simulate the behavior of a tpu v3 pod, let's say v3-32, with 4 v3-8 TPUs?
I guess that I would have to use: `python -m torch_xla.distributed.xla_dist`, however it doesn't seem to support providing multiple TPU addresses. Is what I am asking doable?

Thanks in advance for your time!

**Comment by dlibenzi** [comment]
Now you cannot do that ATM.
TPU which are part of a TPU slice need to be interconnected in a special way.

**Comment by giannisdaras** [comment]
Ok, thanks for clarifying. Closing!

**Comment by dav-ell** [comment]
This is a pretty significant downside for me. Any plans for this to be included in the future?

**Comment by dav-ell** [comment]
Thanks for the response and explanation.

I use the TensorFlow Research Cloud (TFRC) grant, which only provides v2-8
and v3-8 instances. Though it does provide 100 v2-8 preemptible instances,
which I'd like to use.

**Comment by mehadi92** [comment]
HI, @dlibenzi what is the status of using multiple **v3-8** TPU in a distributed way? Does **python -m torch_xla.distributed.xla_dist** accept multiple **v3-8 TPU**

Thanks
