### ISSUE TITLE
What causes Tensor padding? (128x expansion)

### ISSUE THREAD

**Issue by Jerry2001Qu** [pytorch/xla#2016]
## ❓ Questions and Help

I've been following the Cloud TPU guidelines to minimize padding (https://cloud.google.com/tpu/docs/troubleshooting#memory-usage)

However, my model on colab has OOM issues, where padding is causing a 128x expansion.

1.3% utilization: Unpadded (294.49M) Padded (23.01G)

I was hoping to understand what might be causing this, or if there are guidelines to follow I have missed. I can share a version if need be.

Thanks!

**Comment by dlibenzi** [comment]
Can you post the full error dump and the debug_run tarbal as explained here?

https://github.com/pytorch/xla/blob/master/contrib/colab/issue-report.ipynb

**Comment by Jerry2001Qu** [comment]
Actually, I just reran my code after sleeping last night, and everything's working fine now. I didn't change anything, so I don't know what was causing it, but it's all good now. Thanks!
