### ISSUE TITLE
TPU seems to be unable to leave the training loop.

### ISSUE THREAD

**Issue by joshclancy** [pytorch/xla#2020]
## ❓ Questions and Help
Hello!
I am trying to get the free TPU on collab working before migrating to a VM and running on google cloud.

My problem is that the TPU seems to never leave my training loop for some reason. As in, it gets to the last batch and just stops. There is no crash (and so no error to follow up on). It just gets keeps running indefinitely. 

I am new to using xla but not PyTorch, and it works on collabs GPU so I am at a loss. Please help! 

here is my training loop: 
`            
for image_batch, labels in data_loader:

                # to cuda

                image_batch = image_batch.to(device)

                labels = labels.to(device).float()

                # vae reconstruction

                outputDict = model(image_batch, outputDict)

                # reconstruction error

                lossDict = VACTS_loss(image_batch, labels, run, outputDict, lossDict)

                #loss propogation through each VCap

                lossy = lossDict["loss"]

                # backpropagation

                optimizer.zero_grad()

                lossy.backward(retain_graph=True)

                # one step of the optmizer (using the gradients from backpropagation)            
   
                optimizer.step()

                print(met.metrics_report())

                if verbose == 2: print("|", end = "")` 

here is the metrics report at the last batch, before infinite running. 

Metric: CompileTime
  TotalSamples: 109
  Accumulator: 16s842ms200.190us
  ValueRate: 752ms322.271us / second
  Rate: 5.17625 / second
  Percentiles: 1%=007ms796.724us; 5%=007ms207.873us; 10%=007ms318.353us; 20%=008ms711.078us; 50%=008ms191.383us; 80%=009ms138.766us; 90%=012ms722.064us; 95%=01s221ms614.286us; 99%=04s589ms627.651us
Metric: DeviceLockWait
  TotalSamples: 754
  Accumulator: 002ms638.153us
  ValueRate: 039.945us / second
  Rate: 18.3857 / second
  Percentiles: 1%=000.948us; 5%=001.137us; 10%=001.239us; 20%=001.390us; 50%=001.774us; 80%=002.867us; 90%=003.318us; 95%=003.657us; 99%=006.731us
Metric: ExecuteTime
  TotalSamples: 754
  Accumulator: 02s445ms280.499us
  ValueRate: 060ms758.581us / second
  Rate: 18.4265 / second
  Percentiles: 1%=002ms731.089us; 5%=002ms876.672us; 10%=002ms971.287us; 20%=002ms098.800us; 50%=002ms396.882us; 80%=003ms951.032us; 90%=003ms346.984us; 95%=004ms785.642us; 99%=036ms855.317us
Metric: InboundData
  TotalSamples: 754
  Accumulator: 3.61MB
  ValueRate: 90.38KB / second
  Rate: 18.4293 / second
  Percentiles: 1%=1.00B; 5%=8.00B; 10%=8.00B; 20%=8.00B; 50%=24.00B; 80%=128.00B; 90%=512.00B; 95%=3.38KB; 99%=144.00KB
Metric: IrValueTensorToXlaData
  TotalSamples: 1523
  Accumulator: 08s807ms564.329us
  ValueRate: 170ms422.602us / second
  Rate: 25.5333 / second
  Percentiles: 1%=954.678us; 5%=001ms026.148us; 10%=001ms099.570us; 20%=001ms214.278us; 50%=002ms974.018us; 80%=004ms002.668us; 90%=005ms770.744us; 95%=067ms055.780us; 99%=070ms407.326us
Metric: OutboundData
  TotalSamples: 1527
  Accumulator: 410.86MB
  ValueRate: 10.17MB / second
  Rate: 25.5685 / second
  Percentiles: 1%=4.00B; 5%=4.00B; 10%=4.00B; 20%=8.00B; 50%=32.00B; 80%=128.00KB; 90%=128.00KB; 95%=5.62MB; 99%=5.62MB
Metric: ReleaseDataHandlesTime
  TotalSamples: 1081
  Accumulator: 01s094ms417.762us
  ValueRate: 023ms168.509us / second
  Rate: 25.3842 / second
  Percentiles: 1%=554.847us; 5%=640.440us; 10%=692.636us; 20%=746.761us; 50%=885.132us; 80%=001ms053.452us; 90%=001ms146.444us; 95%=001ms240.969us; 99%=002ms669.293us
Metric: TensorsGraphSize
  TotalSamples: 754
  Accumulator: 22636.00
  ValueRate: 553.09 / second
  Rate: 18.4233 / second
  Percentiles: 1%=4.00; 5%=4.00; 10%=5.00; 20%=5.00; 50%=5.00; 80%=7.00; 90%=7.00; 95%=7.00; 99%=1590.00
Metric: TransferFromServerTime
  TotalSamples: 754
  Accumulator: 01s327ms949.347us
  ValueRate: 032ms433.385us / second
  Rate: 18.4293 / second
  Percentiles: 1%=001ms007.044us; 5%=001ms138.150us; 10%=001ms219.273us; 20%=001ms334.129us; 50%=002ms601.136us; 80%=002ms908.310us; 90%=002ms188.448us; 95%=003ms623.485us; 99%=006ms227.331us
Metric: TransferToServerTime
  TotalSamples: 1527
  Accumulator: 08s808ms812.648us
  ValueRate: 171ms583.416us / second
  Rate: 25.5667 / second
  Percentiles: 1%=951.384us; 5%=001ms021.358us; 10%=001ms093.508us; 20%=001ms210.185us; 50%=002ms965.690us; 80%=004ms006.365us; 90%=005ms769.110us; 95%=067ms036.482us; 99%=070ms389.572us
Metric: TransferToServerTransformTime
  TotalSamples: 1527
  Accumulator: 388ms795.248us
  ValueRate: 008ms603.816us / second
  Rate: 25.5685 / second
  Percentiles: 1%=080.224us; 5%=092.474us; 10%=098.032us; 20%=114.007us; 50%=156.089us; 80%=230.760us; 90%=319.088us; 95%=002ms977.212us; 99%=002ms139.679us
Counter: CachedCompile
  Value: 645
Counter: CreateCompileHandles
  Value: 109
Counter: CreateDataHandles
  Value: 2283
Counter: CreateXlaTensor
  Value: 148838
Counter: DestroyDataHandles
  Value: 1115
Counter: DestroyXlaTensor
  Value: 146614
Counter: ReleaseDataHandles
  Value: 1115
Counter: UncachedCompile
  Value: 109
Counter: XRTAllocateFromTensor_Empty
  Value: 56
Counter: XrtCompile_Empty
  Value: 384
Counter: XrtExecuteChained_Empty
  Value: 384
Counter: XrtExecute_Empty
  Value: 384
Counter: XrtRead_Empty
  Value: 384
Counter: XrtReleaseAllocationHandle_Empty
  Value: 384
Counter: XrtReleaseCompileHandle_Empty
  Value: 384
Counter: XrtSessionCount
  Value: 4
Counter: XrtSubTuple_Empty
  Value: 384
Counter: aten::_local_scalar_dense
  Value: 20
Counter: aten::masked_select
  Value: 2
Counter: aten::repeat_interleave
  Value: 138
Counter: aten::uniform_
  Value: 81
Counter: xla::abs
  Value: 4
Counter: xla::add
  Value: 20286
Counter: xla::add_
  Value: 17749
Counter: xla::addmm
  Value: 621
Counter: xla::as_strided
  Value: 1440
Counter: xla::bitwise_and_out
  Value: 2
Counter: xla::cat
  Value: 2484
Counter: xla::ceil
  Value: 2
Counter: xla::convolution_backward_overrideable
  Value: 7176
Counter: xla::convolution_overrideable
  Value: 9522
Counter: xla::copy_
  Value: 2162
Counter: xla::div
  Value: 2
Counter: xla::empty
  Value: 10138
Counter: xla::empty_strided
  Value: 1440
Counter: xla::eq
  Value: 2
Counter: xla::expand
  Value: 138
Counter: xla::fill_
  Value: 69
Counter: xla::gt
  Value: 142
Counter: xla::index_select
  Value: 138
Counter: xla::leaky_relu
  Value: 8418
Counter: xla::leaky_relu_backward
  Value: 6348
Counter: xla::lt
  Value: 2
Counter: xla::masked_select
  Value: 2
Counter: xla::max
  Value: 2
Counter: xla::min
  Value: 2
Counter: xla::mm
  Value: 414
Counter: xla::mse_loss
  Value: 207
Counter: xla::mse_loss_backward
  Value: 207
Counter: xla::mul
  Value: 1934
Counter: xla::native_batch_norm
  Value: 8418
Counter: xla::native_batch_norm_backward
  Value: 6348
Counter: xla::ne
  Value: 6
Counter: xla::select
  Value: 304
Counter: xla::sigmoid
  Value: 897
Counter: xla::sigmoid_backward
  Value: 621
Counter: xla::slice
  Value: 3450
Counter: xla::sum
  Value: 621
Counter: xla::t
  Value: 1242
Counter: xla::upsample_nearest2d
  Value: 1932
Counter: xla::upsample_nearest2d_backward
  Value: 1104
Counter: xla::view
  Value: 899
Counter: xla::zero_
  Value: 81
Metric: XrtAllocateFromTensor
  TotalSamples: 1527
  Accumulator: 01s047ms605.870us
  Mean: 861.787us
  StdDev: 821.663us
  Rate: 25.5668 / second
  Percentiles: 25%=284.484us; 50%=491.961us; 80%=002ms540.494us; 90%=002ms943.571us; 95%=003ms557.562us; 99%=003ms209.345us
Metric: XrtCompile
  TotalSamples: 109
  Accumulator: 15s469ms691.371us
  Mean: 142ms914.600us
  StdDev: 603ms951.807us
  Rate: 5.17632 / second
  Percentiles: 25%=006ms443.406us; 50%=007ms780.718us; 80%=008ms603.044us; 90%=009ms815.772us; 95%=01s216ms688.801us; 99%=04s572ms244.032us
Metric: XrtExecute
  TotalSamples: 754
  Accumulator: 01s157ms207.444us
  Mean: 002ms534.758us
  StdDev: 003ms261.843us
  Rate: 18.4265 / second
  Percentiles: 25%=990.113us; 50%=001ms152.829us; 80%=001ms398.038us; 90%=002ms606.373us; 95%=002ms810.506us; 99%=019ms799.849us
Metric: XrtExecutorEvict
  TotalSamples: 0
  Accumulator: nanB
  Mean: nanB
  StdDev: nanB
  Percentiles: 
Metric: XrtReadLiteral
  TotalSamples: 756
  Accumulator: 436ms350.023us
  Mean: 577.183us
  StdDev: 310.534us
  Rate: 18.4782 / second
  Percentiles: 25%=404.967us; 50%=523.887us; 80%=694.720us; 90%=828.766us; 95%=001ms108.233us; 99%=002ms748.813us
Metric: XrtReleaseAllocation
  TotalSamples: 1081
  Accumulator: 026ms608.076us
  Mean: 024.037us
  StdDev: 025.355us
  Rate: 25.3842 / second
  Percentiles: 25%=013.859us; 50%=019.013us; 80%=027.168us; 90%=036.476us; 95%=051.980us; 99%=138.665us

**Comment by taylanbil** [comment]
This would happen if you didn't drop the last batches, and the loaders have
different lengths per device. Could be something else too, but that would
be my first check.

**Comment by joshclancy** [comment]
Dam that idea sounded right to me but I just added drop_last=True to my data loader and printed out the batch_size each time to double-check... Even with the consistent batch size, it is still not finishing the training loop.

**Comment by taylanbil** [comment]
Let's definitely keep `drop_last=True`. Looking at the code, I see that you send batches to device yourself. Are you using `pl.ParallelLoader`? See [here](https://github.com/pytorch/xla/blob/master/test/test_train_mp_imagenet.py#L229) for example. This is highly recommended as it takes care of sending to device for you, and marking steps as the next batch is yielded, etc.

**Comment by joshclancy** [comment]
I am not using the parallel loader. I was under the impression that one device was hard enough, and so I wasn't looking into those methods :) . Im now trying to get that to work, but the parallel loader seems to be causing problems with my loss function. 

RuntimeError: /pytorch/xla/third_party/tensorflow/bazel-tensorflow/tensorflow/compiler/xla/xla_client/debug_macros.h:27 : Check failed: status.status() == ::tensorflow::Status::OK() (Invalid argument: Binary op subtract with different element types: f32[30,2] and s64[30,2]. vs. OK)
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	xla::Shape const* ConsumeValue<xla::Shape const*>(stream_executor::port::StatusOr<xla::Shape const*>&&)
	torch_xla::XlaHelpers::ShapeOfXlaOp(xla::XlaOp)
	torch_xla::BuildMseLoss(xla::XlaOp, xla::XlaOp, torch_xla::ReductionMode)
	torch_xla::ir::ops::InferOutputShape(absl::Span<xla::Shape const>, std::function<xla::XlaOp (absl::Span<xla::XlaOp const>)> const&)
	
	torch_xla::ir::Node::GetOpShape(std::function<xla::Shape ()> const&) const
	torch_xla::ir::Node::Node(torch_xla::ir::OpKind, absl::Span<torch_xla::ir::Value const>, std::function<xla::Shape ()> const&, unsigned long, unsigned long)
	torch_xla::ir::ops::MseLoss::MseLoss(torch_xla::ir::Value const&, torch_xla::ir::Value const&, torch_xla::ReductionMode)
	torch_xla::XLATensor::mse_loss(torch_xla::XLATensor const&, torch_xla::XLATensor const&, long long)
	torch_xla::AtenXlaType::mse_loss(at::Tensor const&, at::Tensor const&, long)
	c10::detail::wrap_kernel_functor_unboxed_<c10::detail::WrapRuntimeKernelFunctor_<at::Tensor (*)(at::Tensor const&, at::Tensor const&, long), at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&, long> >, at::Tensor (at::Tensor const&, at::Tensor const&, long)>::call(c10::OperatorKernel*, at::Tensor const&, at::Tensor const&, long)

	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	
	
	_PyObject_FastCallKeywords
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	
	Py_Main
	main
	__libc_start_main
	_start
*** End stack trace ***

**Comment by taylanbil** [comment]
While using parallel loader, let's remove the lines

```python
            image_batch = image_batch.to(device)
            labels = labels.to(device).float()
```

**Comment by joshclancy** [comment]
yeah, good idea but I already did that.

**Comment by dlibenzi** [comment]
Replace this:
```Python
optimizer.step()
```

With this (if using `ParallelLoader`):
```Python
xm.optimizer_step(optimizer)
```

Or this, if not:
```Python
xm.optimizer_step(optimizer, barrier=True)
```

**Comment by joshclancy** [comment]
Hell yeah! thank you both.

The combination of drop_last =True with xm.optimizer_step(optimizer, barrier=True) did it. 

I never could get the parallel loader to work, but I'm not intending to work on multiple TPU's yet, so that is a problem for another day.

**Comment by dinhanhx** [comment]
> This would happen if you didn't drop the last batches, and the loaders have different lengths per device. Could be something else too, but that would be my first check.

Thanks. I understand now.

**Comment by MiniXC** [comment]
> I never could get the parallel loader to work, but I'm not intending to work on multiple TPU's yet, so that is a problem for another day.

I just found using ```repeat_interleave``` stops the parallel loader from working, could that be the issue?

**Comment by JackCaoG** [comment]
@MiniXC this thread is old, if you have other issues feel free to open a new one.
