### ISSUE TITLE
How to run nprocs > 1 on local CPU using the XRT client ?

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/xla#2021]
## ❓ Questions and Help

I would like to test locally some code with `xmp.spawn(..., nprocs=8)`. When I use suggested env vars in https://github.com/pytorch/xla/blob/master/CONTRIBUTING.md#running-the-tests, my tests pass with nprocs=1 and fail with nprocs > 1 complaining about gRPC
```
2020-05-02 23:51:20.896158: E    1654 tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:509] Unknown: Could not start gRPC server
```
Any suggestions on how to setup properly XRT_DEVICE_MAP and XRT_WORKERS ?
Thanks 

PS: 
I test the code with docker : gcr.io/tpu-pytorch/xla r1.5

**Comment by dlibenzi** [comment]
Which environment?
Colab TPU?
Google Cloud TPU?
Your local machine CPU?
Else?

**Comment by vfdev-5** [comment]
Sorry, didn't mention that explicitly in the text but only in the title of the issue :(

> Which environment?

On my local machine CPU

**Comment by dlibenzi** [comment]
Something like:
```Shell
export XRT_DEVICE_MAP="CPU:0;/job:localservice/replica:0/task:0/device:XLA_CPU:0"
export XRT_WORKERS="localservice:0;grpc://localhost:40934"
```

But of course, you cannot test `nprocs=8` on your local machine as there is only 1 CPU device.

**Comment by vfdev-5** [comment]
Thanks @dlibenzi yes, this is what provided in the contributing guide. 

We can not reuse the same CPU as being multple TPU devices ?
Maybe, multiple CPU emulatation can be done with mulitple docker containers ?

**Comment by dlibenzi** [comment]
Even though creating multiple processes each with one XLA CPU device is possible, than cross replica reduces won't work as XLA does not implement them on CPU.

**Comment by vfdev-5** [comment]
OK, thanks for the info. I close the issue as solved.

And for my curiosity how do you guys test those cross replica ops ? Any CI on TPUs ?

**Comment by dlibenzi** [comment]
On TPUs and soon on GPUs.
