### ISSUE TITLE
Why does `_run_direct` call `sys.exit(0)` on success?

### ISSUE THREAD

**Issue by erip** [pytorch/xla#2022]
## ❓ Questions and Help

I'm trying to run tests using an XRT client on CPU with `nprocs==1`. I find that with a single process, the function passed to `xmp.spawn` finishes successfully and then control is broken immediately by [this line](https://github.com/pytorch/xla/blob/55f4945c3561ddd357141d9a087474cbcd06f763/torch_xla/distributed/xla_multiprocessing.py#L240).

I believe this is at odds with how `torch.multiprocessing.spawn` behaves and it makes it impossible to ever reach the final print statement in the following minimal program:

```python
#!/usr/bin/env python3

import torch_xla.distributed.xla_multiprocessing as xmp

def foo(index):
    print(f"Hello from {index}!")

if __name__ == "__main__":
    xmp.spawn(foo, args=(), nprocs=1)
    print("Finished spawning")
```

To verify it behaves differently, `s/torch_xla.distributed.xla_multiprocessing/torch.multiprocessing/`

**Comment by dlibenzi** [comment]
Actually pytorch returns a context, because you can wait offline for termination:

https://github.com/pytorch/pytorch/blob/cc0f1b22a2734663d305aa07be50ab5d0a92152f/torch/multiprocessing/spawn.py#L200

But for us, nprocs=1 is a feature to allow to GDB a process.

**Comment by erip** [comment]
So what I can infer from this and from [this](https://github.com/pytorch/xla/issues/2021) is that there's no way to make my stub above run as expected on a single CPU?

**Comment by dlibenzi** [comment]
You do not need to use xmp.spawn() for testing. We run thousands of tests (pytorch tests, our python tests, our C++ tests) w/out using xmp.spawn().
Try to run:
```Shell
test/run_tests.sh
test/cpp/run_tests.sh
```
That will run hundreds of tests, on single CPU.

**Comment by erip** [comment]
I may be missing something, but every test I see labeled `test_mp*.py` contains an `xmp.spawn` call in the `__main__`. 😄 If I want to integrate `torch_xla` in my code and test something in a similar way, I cannot assume that the tests will be invoked from `__main__`.

**Comment by dlibenzi** [comment]
I am not sure why you expect a test which is a stand-alone binary to return from spawn, but anyway, this should fix your case and still allow debugging:

https://github.com/pytorch/xla/pull/2023

**Comment by erip** [comment]
In ignite we have various pytest fixtures depending on environment (distributed single node, multinode, etc). Our single node XLA fixture looks like this:

```python
@pytest.fixture()
def distributed_context_single_node_xla(local_rank):
    import os

    if "XRT_DEVICE_MAP" not in os.environ:
        os.environ["XRT_DEVICE_MAP"] = "CPU:0;/job:localservice/replica:0/task:0/device:XLA_CPU:0"

    if "XRT_WORKERS" not in os.environ:
        os.environ["XRT_WORKERS"] = "localservice:0;grpc://localhost:40934"

    import torch_xla.distributed.xla_multiprocessing as xmp

    yield lambda fn, args: xmp.spawn(fn, args=args)
```

where the test to be executed is passed into `xmp.spawn`. `sys.exit` means we never finish the test on a single worker even though the test actually passes.

**Comment by dlibenzi** [comment]
I see.
Keep in mind that multi-processing (both the PT and the PT/XLA ones) can be pretty tricky WRT what you have in the global context.
And how it is used.
With PT/XLA you cannot have code in the global scope which accesses XLA devices, for example.
Everything needs to happen within the target function of xmp.spawn().
With one core, it does not matter, as it is simply a function call.
With TPU, accessing XLA devices at global scope instantiates contexts in the main process, which can lock resources in the spawned ones.

**Comment by erip** [comment]
Right, this is why it's important to call `xm.xla_device()` etc. from within the spawned contexts. Since we only have a single worker test now it's OK but we'll need to think about how that works going forward. Perhaps just a simple wrapper around the test which injects those resources.
