### ISSUE TITLE
Creating randn tensor on XLA device

### ISSUE THREAD

**Issue by a2bhulla** [pytorch/xla#2030]
## ❓ Questions and Help
When creating tensor using: tensor.randn(2, 2, device=xm.xla_device()) does the normal distribution use PyTorch's implementation of normal?

**Comment by JackCaoG** [comment]
This kind of question can be find out by finding the xla implemention of the operation (https://github.com/pytorch/xla/search?q=normal&unscoped_q=normal) and run with a breakpoint on gdb 😄 .

**Comment by JackCaoG** [comment]
or you can find all of the ops that xla overwritten in https://github.com/pytorch/xla/blob/master/torch_xla/csrc/aten_xla_type.h

**Comment by a2bhulla** [comment]
Thanks!
