### ISSUE TITLE
Set up TPU connection to VM for jupyter notebook.

### ISSUE THREAD

**Issue by joshclancy** [pytorch/xla#2031]
## ❓ Questions and Help
Hello,
I am trying to get a TPU instance connected to a google VM and then be able to run a deep learning script in Jupyter lab. I am most of the way there. I have the VM running with Jupyter lab. I also have a tpu node active in the same zone. 

```
gcloud alpha compute tpus list
NAME    ZONE           ACCELERATOR_TYPE  NETWORK_ENDPOINTS  NETWORK  RANGE            STATUS
node-1  us-central1-f  v2-8              (ip address taken out)  default  (ip address taken out)  READY
```

Then I believe I am supposed to do this:

`joshu@tpu3:~$ export TPU_NAME=node-1`

Is this now connected??? I am not sure how to confirm. and have not found any resources on this.

Also perhaps this is a different problem but on jupyter lab, when I run:

```
import os
VERSION = "1.5"  #@param ["1.5" , "20200325", "nightly"]
!tpu_ip = ##########
!curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
!python pytorch-xla-env-setup.py --version $VERSION
```

I get:

/bin/sh: 1: tpu_ip: not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3727  100  3727    0     0  62116      0 --:--:-- --:--:-- --:--:-- 62116
Traceback (most recent call last):
  File "pytorch-xla-env-setup.py", line 112, in <module>
    run_setup(args)
  File "pytorch-xla-env-setup.py", line 83, in run_setup
    tpu_ip = args.tpu_ip if args.tpu_ip else parse_env_tpu_ip()
  File "pytorch-xla-env-setup.py", line 52, in parse_env_tpu_ip
    m_tpu_ip = tpu_ip_regex.match(tpu_addr)
TypeError: expected string or bytes-like object

Does this mean there is another way to connect my "tpu_ip" that I do not know about?

**Comment by jysohn23** [comment]
Kaggle specifically does some setup in the background to set your `TPU_NAME` env var to be of the form `grpc://10.21.63.18:8470` for example. In your case since you're running your jupyter notebook on a GCE VM directly, just provide the TPU IP address. Where "(ip address taken out)" is your IP you can just put it in the `--tpu-ip` flag.

```
TPU_IP=10.0.0.2  # for example
!python pytorch-xla-env-setup.py --version $VERSION --tpu-ip $TPU_IP
```

**Comment by joshclancy** [comment]
Awesome thanks that did it.
