### ISSUE TITLE
import of torch_xla stalls.

### ISSUE THREAD

**Issue by joshclancy** [pytorch/xla#2035]
## ❓ Questions and Help

Weird problem. My import of torch_xla seems to stall. There is no error, it just will not continue. See below image. 

![image](https://user-images.githubusercontent.com/9357539/81101106-7a9b0200-8ec2-11ea-9546-a1497d4ec179.png)

I have tried using different env setups 
as in pytorch-xla-env-setup.py --version 1.5 and 20200325
but this did not help. 

I am using Jupyter notebook, python 3.6.10.

Any ideas ???

**Comment by joshclancy** [comment]
I seem to have gotten past this problem by starting over with a new environment... but now I have another issue perhaps related. 


RuntimeError: tensorflow/compiler/xla/xla_client/computation_client.cc:234 : Missing XLA configuration

![image](https://user-images.githubusercontent.com/9357539/81104728-cdc38380-8ec7-11ea-8f71-8126f57a907b.png)

I have been using xla for awhile now in colab, which made the set up stage easy... but now that I am moving up to a VM and TPU these problems emerge. 

Please help if you can! thanks

**Comment by JackCaoG** [comment]
My guess is that you didn't setup the `XRT_TPU_CONFIG`. Something like
```
(vm)$ export XRT_TPU_CONFIG="tpu_worker;0;$TPU_IP_ADDRESS:8470"
```
You can find more detail information about how to setup the environment correctly on https://github.com/pytorch/xla/blob/master/README.md

**Comment by joshclancy** [comment]
Thankyou! You are right that I did not do this, but it is still not working. 

```
import os
!VERSION="nightly"  #@param ["1.5" , "20200325", "nightly"]
!TPU_IP="myTPU_IP"
!export XRT_TPU_CONFIG="tpu_worker;0;myTPU_IP:8470"
!export TPU_NAME="node-1"
!python pytorch-xla-env-setup.py --version nightly --tpu-ip TPU_IP
```

outputs:

Updating TPU and VM. This may take around 2 minutes.
Updating TPU runtime to pytorch-nightly ...
APT_CMD['apt-get', 'install', '-y', 'libomp5']
1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc8258d46d8>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tpu_ip', port=8475): Max retries exceeded with url: /requestversion/pytorch-nightly (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8258d46d8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "pytorch-xla-env-setup.py", line 26, in update_tpu_runtime
    print('Done updating TPU runtime: {}'.format(requests.post(url)))
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='tpu_ip', port=8475): Max retries exceeded with url: /requestversion/pytorch-nightly (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8258d46d8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

Found existing installation: torch 1.6.0a0+7fa897e
Uninstalling torch-1.6.0a0+7fa897e:
  Successfully uninstalled torch-1.6.0a0+7fa897e
Found existing installation: torchvision 0.7.0a0+bd27e94
Uninstalling torchvision-0.7.0a0+bd27e94:
  Successfully uninstalled torchvision-0.7.0a0+bd27e94
2
Copying gs://tpu-pytorch/wheels/torch-nightly-cp36-cp36m-linux_x86_64.whl...
- [1 files][ 72.2 MiB/ 72.2 MiB]                                                
Operation completed over 1 objects/72.2 MiB.                                     
3
Copying gs://tpu-pytorch/wheels/torch_xla-nightly-cp36-cp36m-linux_x86_64.whl...
\ [1 files][119.1 MiB/119.1 MiB]                                                
Operation completed over 1 objects/119.1 MiB.                                    
4
Copying gs://tpu-pytorch/wheels/torchvision-nightly-cp36-cp36m-linux_x86_64.whl...
/ [1 files][  2.3 MiB/  2.3 MiB]                                                
Operation completed over 1 objects/2.3 MiB.                                      
5
Processing ./torch-nightly-cp36-cp36m-linux_x86_64.whl
Requirement already satisfied: numpy in /anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages (from torch==nightly) (1.18.1)
Requirement already satisfied: future in /anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages (from torch==nightly) (0.18.2)
Installing collected packages: torch
Successfully installed torch-1.6.0a0+7fa897e
6
Processing ./torch_xla-nightly-cp36-cp36m-linux_x86_64.whl
Installing collected packages: torch-xla
  Attempting uninstall: torch-xla
    Found existing installation: torch-xla 1.6+36553ae
    Uninstalling torch-xla-1.6+36553ae:
      Successfully uninstalled torch-xla-1.6+36553ae
Successfully installed torch-xla-1.6+36553ae
7
Processing ./torchvision-nightly-cp36-cp36m-linux_x86_64.whl
Requirement already satisfied: pillow>=4.1.1 in /anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages (from torchvision==nightly) (6.2.1)
Requirement already satisfied: torch in /anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages (from torchvision==nightly) (1.6.0a0+7fa897e)
Requirement already satisfied: numpy in /anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages (from torchvision==nightly) (1.18.1)
Requirement already satisfied: future in /anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages (from torch->torchvision==nightly) (0.18.2)
Installing collected packages: torchvision
Successfully installed torchvision-0.7.0a0+bd27e94
8
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?

Any ideas for me to try?

**Comment by joshclancy** [comment]
Nevermind I figured out one of the problems:

!python pytorch-xla-env-setup.py --version nightly --tpu-ip TPU_IP

was not accepting the TPU_IP. So that part now runs fine BUTTT I still get the original error:

<ipython-input-8-a4671c947190> in <module>
     10 print("4")
     11 # dev = "cuda"
---> 12 dev = xm.xla_device()
     13 print("done")

/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/core/xla_model.py in xla_device(n, devkind)
    136   if n is None:
    137     devices = get_xla_supported_devices(
--> 138         devkind=[devkind] if devkind is not None else None)
    139     assert devices, 'No devices of {} kind'.format(devkind or 'ANY')
    140     # This is a utility API mainly called from tests or simple code which wants

/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/core/xla_model.py in get_xla_supported_devices(devkind, max_devices)
     40     The list of device strings.
     41   """
---> 42   xla_devices = torch_xla._XLAC._xla_get_devices()
     43   devkind = devkind or ['TPU', 'GPU', 'CPU']
     44   for kind in devkind:

RuntimeError: tensorflow/compiler/xla/xla_client/computation_client.cc:234 : Missing XLA configuration

**Comment by joshclancy** [comment]
OK solved for good now. 

First I was forgetting this line: 

(vm)$ export XRT_TPU_CONFIG="tpu_worker;0;$TPU_IP_ADDRESS:8470"

Then my problem was that I kept trying to include code from colab to get this thing running. 

If you just follow the recommendations here: https://github.com/pytorch/xla/blob/master/README.md it should work (who could've guessed to just follow the instructions? crazy idea) 

There is no need to include the extra code that is required in colab:

!VERSION="nightly"  #@param ["1.5" , "20200325", "nightly"]
!TPU_IP="myTPU_IP"
!export TPU_NAME="node-1"
!python pytorch-xla-env-setup.py --version nightly --tpu-ip TPU_IP

^ So do not include that. The google VM has conda environments that have everything you need.

**Comment by ludwigwittgenstein2** [comment]
I am getting same error, and I am not sure how to solve this in Colab, any ideas?

**Comment by kevint324** [comment]
Same here, seems pytorch xla gpu is poorly documented.

**Comment by JackCaoG** [comment]
Can you check out the new doc https://github.com/pytorch/xla#running-pytorchxla-on-cloud-tpu-and-gpu ?

**Comment by kevint324** [comment]
update
I missed this line
```
export GPU_NUM_DEVICES=1
```
and it fixed the problem on GPU.

I was wondering there might be a `XRT_GPU_CONFIG` or something.

Thanks

**Comment by TahaBinhuraib** [comment]
@kevint324 Thanks a lot. This is what I was missing in my google VM!
