### ISSUE TITLE
tf 2.2

### ISSUE THREAD

**Issue by cjolivier01** [pytorch/xla#2039]
## ❓ Questions and Help
Hi!
Will you be pulling in the new tf2.2 release commit 2b96f3662bd776e277f86997659e61046b56c315?
Or are you already past that?
Looking for a "stable" commit on both sides, but currently working off of your "pytorch 1.5" release, but of course that's a transitional 2.1+ commit.  What do you recommend?

**Comment by dlibenzi** [comment]
You can check yourself.
```Shell
cd third_party/tensorflow/
git log
```
We pull cutting edge TF continuously, as we keep adding features/fixes on the TF/XLA side.

**Comment by cjolivier01** [comment]
Thank you.
