### ISSUE TITLE
std::move(holders) may occur before holders is used in the same scope

### ISSUE THREAD

**Issue by cjolivier01** [pytorch/xla#2052]
## 🐛 Bug

In several places in xrt_computation_client.cc, most notably this function:
```Cpp
const XrtSession::CachedNode& XrtComputationClient::GetAllocateNode(
    XrtSession* session, const tensorflow::Scope& scope,
    const std::string& device, const Shape& shape) const
```

The move here seems to be responsible for a crash I am seeing when compiling with gcc.  It seems that, since push order is last-to-first, it is possible that at the bottom of this function, the expression:
```cpp
    cache->Add(std::make_shared<XrtSession::CachedNode>(
        tensorflow::ops::XRTAllocateFromTensor(scope, {holders[0].output},
                                               {tensor_shape}, alloc_attrs),
        std::move(holders)));
```
I think that under some circumstances (compiler, optimizations),  std::move(holders) can execute before the {holders[0].output}

Later, getting the value from the cache has some corruption and a seg fault occurs at the cache items' use.

I know that you guys normally compile with clang, but it works for the most part for me with gcc, and this is with all optimizations turned off, so one can imagine that gcc behaves strictly in order here, "pushing" the std::move(holders) "value" to the stack first, followed by calling and then pushing the result of tensorflow::ops::XRTAllocateFromTensor(...)

The crash goes away when I substitute with (obviously a change just for checking the crash goes away):

```cpp
/*std::move(*/holders/*)*/
```

![image](https://user-images.githubusercontent.com/11234557/81486475-e3a7b000-9209-11ea-9df4-02c837a1ac61.png)

^ Node::name() seg faults because the output node is null here (nulled out by the move in debug mode?)

It could be that I am mistaken?

**Comment by dlibenzi** [comment]
Good point. We are lucky hitting the sunny side of C++ UB.
I will be posting a PR soon.

**Comment by cjolivier01** [comment]
Thanks!  btw, I am happy to do the PR if you're busy.  I know it's the weekend.  Maybe param as && and move in the CachedNode constructor, or some other permutation.
