### ISSUE TITLE
pytorch xla printing 1 epoch performance 8 times and validation accuracy using 1 core always

### ISSUE THREAD

**Issue by mobassir94** [pytorch/xla#2054]
is the code attached below bug free?

```
def train_model():
    global train_dataset, valid_dataset
    
    torch.manual_seed(42)
    
    train_sampler = torch.utils.data.distributed.DistributedSampler(
        train_dataset,
        num_replicas=xm.xrt_world_size(),
        rank=xm.get_ordinal(),
        shuffle=True)
    
    train_loader = torch.utils.data.DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        sampler=train_sampler,
        num_workers=0,
        drop_last=True) # print(len(train_loader))
    
    '''valid_sampler = torch.utils.data.distributed.DistributedSampler(
        train_dataset,
        num_replicas=xm.xrt_world_size(),
        rank=xm.get_ordinal(),
        )'''
        
    valid_loader = torch.utils.data.DataLoader(
        valid_dataset,
        batch_size=BATCH_SIZE,
        #sampler=valid_sampler,
        shuffle=False,
        num_workers=0,
        drop_last=True)
    
    #xm.master_print(f"Train for {len(train_loader)} steps per epoch")
    LOGGER.debug(f"Train for {len(train_loader)} steps per epoch")
    # Scale learning rate to num cores
    lr  = 0.0001 * xm.xrt_world_size()

    # Get loss function, optimizer, and model
    device = xm.xla_device()

    #model = model()
    '''
    for param in model.base_model.parameters(): # freeze some layers
        param.requires_grad = False'''
    
    
    global model
    
    model = model.to(device)

    criterion = torch.nn.BCEWithLogitsLoss() #  MSELoss
    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=5e-4)
    scheduler = OneCycleLR(optimizer, 
                           lr, 
                           div_factor=10.0, 
                           final_div_factor=50.0, 
                           epochs=NUM_EPOCH,
                           steps_per_epoch=len(train_loader))
    
    
    
    def train_loop_fn(loader):
        tracker = xm.RateTracker()
        model.train()
        
        #xm.master_print('Epoch {}/{}'.format(epoch, num_epochs - 1))
        LOGGER.debug('Epoch {}/{}'.format(epoch, num_epochs - 1))
        #xm.master_print('-' * 10)
        LOGGER.debug('-' * 10)
        scheduler.step()
        
        running_loss = 0.0
        tk0 = tqdm(loader, total=int(len(train_loader)))
        counter = 0
        for bi, d in enumerate(tk0):
            inputs = d["image"]
            labels = d["label"].view(-1, 1)
            inputs = inputs.to(device, dtype=torch.float)
            labels = labels.to(device, dtype=torch.float)
            optimizer.zero_grad()
            #with torch.set_grad_enabled(True):
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            #loss = criterion(outputs, torch.max(labels, 1)[1])
            loss.backward()
            xm.optimizer_step(optimizer)
            running_loss += loss.item() * inputs.size(0)
            #print(running_loss)
            counter += 1
            tk0.set_postfix(loss=(running_loss / (counter * BATCH_SIZE)))
        epoch_loss = running_loss / len(train_loader)
        #xm.master_print('Training Loss: {:.8f}'.format(epoch_loss))
        LOGGER.debug('Training Loss: {:.8f}'.format(epoch_loss))

                
    def test_loop_fn(loader):
        tk0 = tqdm(loader, total=int(len(valid_loader)))
        counter = 0
        total_samples, correct = 0, 0
        for bi, d in enumerate(tk0):
            inputs = d["image"]
            labels = d["label"].view(-1, 1)
            inputs = inputs.to(device, dtype=torch.float)
            labels = labels.to(device, dtype=torch.float)
            optimizer.zero_grad()
            
            with torch.no_grad():
                
                output = model(inputs)
                
                pred = output.max(1, keepdim=True)[1]
                correct += pred.eq(labels.view_as(pred)).sum().item()
                total_samples += inputs.size()[0]
        accuracy = 100.0 * correct / total_samples
        #print('[xla:{}] Accuracy={:.4f}%'.format(xm.get_ordinal(), accuracy), flush=True)
        model.train()
        return accuracy

    # Train - valid  loop
    accuracy = []
    for epoch in range(1, num_epochs + 1):
        start = time.time()
        para_loader = pl.ParallelLoader(train_loader, [device])
        train_loop_fn(para_loader.per_device_loader(device))
        
        para_loader = pl.ParallelLoader(valid_loader, [device])
        accuracy.append(test_loop_fn(para_loader.per_device_loader(device)))
        #xm.master_print("Finished training epoch {}  Val-Acc {:.4f} in {:.4f} sec".format(epoch, accuracy[-1],   time.time() - start))        
        
        LOGGER.debug("Finished training epoch {}  Val-Acc {:.4f} in {:.4f} sec".format(epoch, accuracy[-1],   time.time() - start))   
        valauc = accuracy[-1]
        if(epoch>4):
            xm.save(model.state_dict(), f"./epoch{epoch}valauc{valauc}.bin")
    return accuracy

def _mp_fn(rank, flags):
    global acc_list
    torch.set_default_tensor_type('torch.FloatTensor')
    res = train_model()

FLAGS={}
xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=8, start_method='fork')
```

1st epochs train log looks like this : 

2020-05-09 12:21:29,371 DEBUG Train for 445 steps per epoch
2020-05-09 12:21:29,710 DEBUG Train for 445 steps per epoch
2020-05-09 12:21:29,721 DEBUG Train for 445 steps per epoch
2020-05-09 12:21:29,911 DEBUG Train for 445 steps per epoch
2020-05-09 12:21:30,561 DEBUG Epoch 1/6
2020-05-09 12:21:30,564 DEBUG ----------
2020-05-09 12:21:31,065 DEBUG Epoch 1/6
2020-05-09 12:21:31,076 DEBUG ----------
2020-05-09 12:21:31,120 DEBUG Epoch 1/6
2020-05-09 12:21:31,130 DEBUG ----------
2020-05-09 12:21:31,390 DEBUG Epoch 1/6
2020-05-09 12:21:31,426 DEBUG ----------
2020-05-09 12:21:32,629 DEBUG Train for 445 steps per epoch
2020-05-09 12:21:33,573 DEBUG Train for 445 steps per epoch
2020-05-09 12:21:33,748 DEBUG Train for 445 steps per epoch
2020-05-09 12:21:33,883 DEBUG Train for 445 steps per epoch
2020-05-09 12:21:34,889 DEBUG Epoch 1/6
2020-05-09 12:21:34,914 DEBUG ----------
2020-05-09 12:21:35,573 DEBUG Epoch 1/6
2020-05-09 12:21:35,613 DEBUG ----------
2020-05-09 12:21:35,823 DEBUG Epoch 1/6
2020-05-09 12:21:35,845 DEBUG ----------
2020-05-09 12:21:36,128 DEBUG Epoch 1/6
2020-05-09 12:21:36,171 DEBUG ----------
2020-05-09 12:35:08,162 DEBUG Training Loss: 11.22450873
2020-05-09 12:35:08,172 DEBUG Training Loss: 11.19612112
2020-05-09 12:35:08,309 DEBUG Training Loss: 11.18398799
2020-05-09 12:35:08,352 DEBUG Training Loss: 11.16665337
2020-05-09 12:35:08,362 DEBUG Training Loss: 11.20103131
2020-05-09 12:35:08,357 DEBUG Training Loss: 11.19919075
2020-05-09 12:35:08,368 DEBUG Training Loss: 11.19310062
2020-05-09 12:35:08,386 DEBUG Training Loss: 11.21970569
2020-05-09 12:39:31,562 DEBUG Finished training epoch 1  Val-Acc 50.5348 in 1080.4523 sec

the validation accuracy calculation is slow,somehow validation accuracy is using 1 core for calculation where in train phase it is using 8 cores,how do i solve this issue? i need to make the validation calculation fast, also in all epoch i see same validation accuracy, maybe i have bug in my code? another thing is,if i train this model for 8-10 epoch then kaggle kernel doesn't finish commit,it gives error that's not visible,so maybe somewhere in my code i am requesting more memory and getting OOM for that? also in my code if i try sampler=valid_sampler for valid_loader then i get error. please help me find bugs in my code,thank you a lot in advance

**Comment by dlibenzi** [comment]
There are 8 processes each running on one core, so having 8 prints is normal.
This is what `xm.master_print()` is for.
You have disabled the sampler in the validation, which means you are running the full set on each core.
This is OK, but if you want to speed things up you can use a sampler, and then use `xm.mesh_reduce()` to average accuracies:

https://github.com/pytorch/xla/blob/760e027487e1e37da9c0be703ba734bed2bb616b/torch_xla/core/xla_model.py#L616

You also have optimizer.zero_grad() calls in test loop, remove them.
Remove also the no_grad thing, and use `model.eval()`:

https://github.com/pytorch/xla/blob/760e027487e1e37da9c0be703ba734bed2bb616b/test/test_train_mp_mnist.py#L135

Also, no not print/report loss at each step, as this slows down performance.
Use something like this:

https://github.com/pytorch/xla/blob/760e027487e1e37da9c0be703ba734bed2bb616b/test/test_train_mp_mnist.py#L129

**Comment by mobassir94** [comment]
@dlibenzi  i didn't use validation sampler because if i use that then i get this error : 

2020-05-10 16:46:53,860 DEBUG Training Loss: 11.06514018
2020-05-10 16:46:53,863 DEBUG Training Loss: 11.30319023
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/indexes/range.py", line 376, in get_loc
    return self._range.index(new_key)
ValueError: 500 is not in range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch_xla/distributed/parallel_loader.py", line 134, in _loader_worker
    _, data = next(data_iter)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "<ipython-input-19-7cab027df936>", line 12, in __getitem__
    img_name =  self.data.loc[idx][0]
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/indexing.py", line 1424, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/indexing.py", line 1850, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/indexing.py", line 160, in _get_label
    return self.obj._xs(label, axis=axis)
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/generic.py", line 3737, in xs
    loc = self.index.get_loc(key)
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/indexes/range.py", line 378, in get_loc
    raise KeyError(key)
KeyError: 500


and i don't understand anything from this error

**Comment by dlibenzi** [comment]
May I suggest you dropping your full model in Colab following this template?

https://github.com/pytorch/xla/blob/master/contrib/colab/issue-report.ipynb

At least with that we can try to replicate.

**Comment by mobassir94** [comment]
@dlibenzi  i can share the kaggle kernel link with you,is that ok?
here it is : https://www.kaggle.com/mobassir/pytorch-tpu-transfer-learning-baseline
let me know if i still need it to drop in colab using the template you provided?

**Comment by mobassir94** [comment]
hello @dlibenzi  any update please?

i am having 2 problems now : 
problem 1 : if i use validation sampler in my code then i get error that i showed you in my last comment

problem 2 : i am unable to do inference on tpu. (i got error like this : input tensor is not xla tensor it is float tensor)

the code i used for inference is this : 


```
class test_images(Dataset):
 
    def __init__(self, csv_file):
 
        self.data = csv_file
 
    def __len__(self):
        return len(self.data)
 
    def __getitem__(self, idx):
        img_name =  self.data.loc[idx][0]
        image = Image.open(img_name)
        image = image.resize((512, 512), resample=Image.BILINEAR)
        #label = self.data.loc[idx][1] #torch.tensor(self.data.loc[idx, 'label'])
        #image = self.transform(image)
        return {'image': transforms.ToTensor()(image)}
 
testdataset = pd.DataFrame({ 'images': list(test_paths)},columns=['images'])
 
testdataset = test_images(testdataset)
 
 
Test_BATCH_SIZE = 1    
test_sampler = torch.utils.data.distributed.DistributedSampler(
      testdataset,
      num_replicas=xm.xrt_world_size(),
      rank=xm.get_ordinal(),
      shuffle=True)
 
test_data_loader = torch.utils.data.DataLoader(
    testdataset,
    batch_size=Test_BATCH_SIZE,
    sampler=test_sampler,
    #drop_last=True,
    num_workers=0
)
 
device = xm.xla_device()
 
testpara_loader = pl.ParallelLoader(test_data_loader, [device])
 
sub["Label"] = pd.to_numeric(sub["Label"].astype(float))
 
 
# test_set contains only images path list
 
 
test_loader =  testpara_loader.per_device_loader(device)
 
for param in model.parameters():
    param.requires_grad = False
 
prediction_list = []
tk0 = tqdm(test_loader)
 
for i, x_batch in enumerate(tk0):
    #print(i)
   
    x_batch = x_batch["image"]
    #print(x_batch)
    pred =  model(x_batch.to(device))
    #prediction_list.append(pred.cpu())
    #print( type(pred.item()))
    #print("\n")
    sub.Label[i] = pred.item()
    #print(sub.Label[i])
```


and the error comes while executing this line of code =  pred =  model(x_batch.to(device))

where i am making mistakes? using almost similar code i trained my model,please help?

**Comment by taylanbil** [comment]
```
    '''valid_sampler = torch.utils.data.distributed.DistributedSampler(
        train_dataset,
```

Taking a quick look, it seems like you're sampling from the train dataset in `valid_sampler`, which may be the cause of the KeyError.

**Comment by mobassir94** [comment]
thank you @taylanbil ,that was a terrible mistake,i just solved that now,i just replaced train_dataset with valid_dataset in valid_sampler and kept everything as it was and now i get this error : 

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-26-fbdc51ff9648> in <module>
      7 
      8 FLAGS={}
----> 9 xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=8, start_method='fork')

/opt/conda/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py in spawn(fn, args, nprocs, join, daemon, start_method)
    180         join=join,
    181         daemon=daemon,
--> 182         start_method=start_method)

/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py in start_processes(fn, args, nprocs, join, daemon, start_method)
    156 
    157     # Loop on join until it returns True or raises an exception.
--> 158     while not context.join():
    159         pass
    160 

/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py in join(self, timeout)
    106                 raise Exception(
    107                     "process %d terminated with signal %s" %
--> 108                     (error_index, name)
    109                 )
    110             else:

Exception: process 2 terminated with signal SIGABRT

and also can you please tell me how do i solve the  issue  of problem 2(as i  asked in my last comment)

**Comment by mobassir94** [comment]
after reducing batch size from 16 to 10 it now works,but i think it is a bug,because with batch size  16 i can train this model on 8 core but at the same time i can't do validation with that same batch size using 8 cores. and also can you please tell me how do i solve the issue of problem 2(as i asked in my last comment)



problem 2 : i am unable to do inference on tpu. (i got error like this : input tensor is not xla tensor it is float tensor)

the code i used for inference is this : 


```
class test_images(Dataset):
 
    def __init__(self, csv_file):
 
        self.data = csv_file
 
    def __len__(self):
        return len(self.data)
 
    def __getitem__(self, idx):
        img_name =  self.data.loc[idx][0]
        image = Image.open(img_name)
        image = image.resize((512, 512), resample=Image.BILINEAR)
        #label = self.data.loc[idx][1] #torch.tensor(self.data.loc[idx, 'label'])
        #image = self.transform(image)
        return {'image': transforms.ToTensor()(image)}
 
testdataset = pd.DataFrame({ 'images': list(test_paths)},columns=['images'])
 
testdataset = test_images(testdataset)
 
 
Test_BATCH_SIZE = 1    
test_sampler = torch.utils.data.distributed.DistributedSampler(
      testdataset,
      num_replicas=xm.xrt_world_size(),
      rank=xm.get_ordinal(),
      shuffle=True)
 
test_data_loader = torch.utils.data.DataLoader(
    testdataset,
    batch_size=Test_BATCH_SIZE,
    sampler=test_sampler,
    #drop_last=True,
    num_workers=0
)
 
device = xm.xla_device()
 
testpara_loader = pl.ParallelLoader(test_data_loader, [device])
 
sub["Label"] = pd.to_numeric(sub["Label"].astype(float))
 
 
# test_set contains only images path list
 
 
test_loader =  testpara_loader.per_device_loader(device)
 
for param in model.parameters():
    param.requires_grad = False
 
prediction_list = []
tk0 = tqdm(test_loader)
 
for i, x_batch in enumerate(tk0):
    x_batch = x_batch["image"]
    pred =  model(x_batch.to(device))
    sub.Label[i] = pred.item()
    
```


and the error comes while executing this line of code =  pred =  model(x_batch.to(device))

where i am making mistakes? using almost similar code i trained my model,please help?

**Comment by taylanbil** [comment]
It is not easy to reproduce what you're doing w/ code samples only, and there's no stack trace. Could you give a little bit more info? 

You have this comment: `# test_set contains only images path list`. Is `xbatch['image']` a tensor of correct type? you could print it to see what it looks like maybe?

Also, it seems like you're recording the labels using indices. If so, I suggest you disable shuffling for the validation set, and take into account the sharding.

**Comment by mobassir94** [comment]
@taylanbil  thanks
i removed shuffle and print(x_batch['image']) gives me this : 

tensor([[[[0.5569, 0.5529, 0.5451,  ..., 0.8157, 0.8157, 0.8157],
          [0.5373, 0.5412, 0.5412,  ..., 0.8196, 0.8157, 0.8157],
          [0.5373, 0.5412, 0.5451,  ..., 0.8235, 0.8157, 0.8118],
          ...,
          [0.7137, 0.7059, 0.7020,  ..., 0.7059, 0.7059, 0.7098],
          [0.7137, 0.7059, 0.7020,  ..., 0.7098, 0.7098, 0.7098],
          [0.7176, 0.7098, 0.7020,  ..., 0.7176, 0.7137, 0.7098]],

         [[0.4235, 0.4196, 0.4118,  ..., 0.0000, 0.0000, 0.0000],
          [0.4039, 0.4078, 0.4078,  ..., 0.0039, 0.0000, 0.0000],
          [0.4039, 0.4078, 0.4118,  ..., 0.0078, 0.0000, 0.0000],
          ...,
          [0.4863, 0.4784, 0.4745,  ..., 0.5176, 0.5176, 0.5216],
          [0.4863, 0.4784, 0.4745,  ..., 0.5216, 0.5216, 0.5216],
          [0.4902, 0.4824, 0.4745,  ..., 0.5294, 0.5255, 0.5216]],

         [[0.2745, 0.2706, 0.2627,  ..., 0.1255, 0.1255, 0.1255],
          [0.2549, 0.2588, 0.2588,  ..., 0.1294, 0.1255, 0.1255],
          [0.2549, 0.2588, 0.2627,  ..., 0.1333, 0.1255, 0.1216],
          ...,
          [0.4000, 0.3922, 0.3882,  ..., 0.2745, 0.2745, 0.2784],
          [0.4000, 0.3922, 0.3882,  ..., 0.2784, 0.2784, 0.2784],
          [0.4039, 0.3961, 0.3882,  ..., 0.2863, 0.2824, 0.2784]]]],
       device='xla:1')

you can see device='xla:1' but still getting the error

**Comment by taylanbil** [comment]
do you have a traceback for this error?

**Comment by mobassir94** [comment]
@taylanbil  sorry i forgot to share the traceback  in last comment,here is the traceback for that error : 

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<timed exec> in <module>

/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    556             result = self._slow_forward(*input, **kwargs)
    557         else:
--> 558             result = self.forward(*input, **kwargs)
    559         for hook in self._forward_hooks.values():
    560             hook_result = hook(self, input, result)

/opt/conda/lib/python3.6/site-packages/efficientnet_pytorch/model.py in forward(self, inputs)
    191         bs = inputs.size(0)
    192         # Convolution layers
--> 193         x = self.extract_features(inputs)
    194 
    195         # Pooling and final linear layer

/opt/conda/lib/python3.6/site-packages/efficientnet_pytorch/model.py in extract_features(self, inputs)
    173 
    174         # Stem
--> 175         x = self._swish(self._bn0(self._conv_stem(inputs)))
    176 
    177         # Blocks

/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    556             result = self._slow_forward(*input, **kwargs)
    557         else:
--> 558             result = self.forward(*input, **kwargs)
    559         for hook in self._forward_hooks.values():
    560             hook_result = hook(self, input, result)

/opt/conda/lib/python3.6/site-packages/efficientnet_pytorch/utils.py in forward(self, x)
    142     def forward(self, x):
    143         x = self.static_padding(x)
--> 144         x = F.conv2d(x, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups)
    145         return x
    146 

RuntimeError: torch_xla/csrc/aten_xla_bridge.cpp:69 : Check failed: xtensor 
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	torch_xla::bridge::GetXlaTensor(at::Tensor const&)
	torch_xla::AtenXlaType::convolution_overrideable(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long)
	c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<at::Tensor (*)(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long), at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long> >, at::Tensor (at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long)>::call(c10::OperatorKernel*, at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long)
	
	
	
	
	at::native::_convolution(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long, bool, bool, bool)
	
	
	
	
	at::native::convolution(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long)
	
	
	
	
	at::native::conv2d(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long)
	
	
	
	
	
	_PyCFunction_FastCallDict
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	_PyObject_FastCallDict
	_PyObject_Call_Prepend
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	_PyObject_FastCallDict
	_PyObject_Call_Prepend
	PyObject_Call
	
	_PyObject_FastCallDict
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	_PyObject_FastCallDict
	_PyObject_Call_Prepend
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	_PyObject_FastCallDict
	_PyObject_Call_Prepend
	PyObject_Call
	
	_PyObject_FastCallDict
	
	_PyEval_EvalFrameDefault
	PyEval_EvalCodeEx
	PyEval_EvalCode
	
	_PyCFunction_FastCallDict
	
	_PyEval_EvalFrameDefault
	PyEval_EvalCodeEx
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	_PyObject_FastCallDict
	_PyObject_Call_Prepend
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	PyEval_EvalCodeEx
	PyEval_EvalCode
	
	_PyCFunction_FastCallDict
	
	_PyEval_EvalFrameDefault
	_PyGen_Send
	_PyEval_EvalFrameDefault
	_PyGen_Send
	_PyEval_EvalFrameDefault
	_PyGen_Send
	_PyCFunction_FastCallDict
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	_PyObject_FastCallDict
	_PyObject_Call_Prepend
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	_PyCFunction_FastCallDict
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	_PyCFunction_FastCallDict
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
*** End stack trace ***
Input tensor is not an XLA tensor: torch.FloatTensor






`

**Comment by taylanbil** [comment]
it's happening here:

`--> 144         x = F.conv2d(x, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups)`

can you edit the file `/opt/conda/lib/python3.6/site-packages/efficientnet_pytorch/utils.py` to print these tensors devices? one of these seems to be on the cpu, not on the xla device.

**Comment by taylanbil** [comment]
quicker check: are you sending the model to device? you are doing so in training code, but I don't see a `model.to(device)` in the inference code?

**Comment by mobassir94** [comment]
thanks @taylanbil  it solves the error, actually in training i was doing :
global model
model = model.to(device)

i thought model is still on xla device during testing.thank you.
i still  have some confusion that i want to tell  you : 
confusion 1 : is pytorch tpu slower than tensorflow tpu? actually there is another kernel in kaggle that uses efficientnet,no  augmentation,512x512 resize,same amount of  data like my model(as  you have seen above) and that tf tpu kernel (this one) : https://www.kaggle.com/xhlulu/alaska2-efficientnet-on-tpus is way faster than my code,even though i am using 8 core and using your solution to use validation sampler,still my model is way slower than  that  keras kernel,if you compare my model with that then you can see both are same,his one is written in tf and i am using pytorch
confusion 2 : why pytorch tpu is giving me OOM? in that tf tpu kernel the author is doing BATCH_SIZE = 16 * strategy.num_replicas_in_sync and after converting his model to pytorch tpu i am unable to use 16 batch size  for train and validation set,it gives error : "Exception: process 2 terminated with signal SIGABRT", i knew that pytorch is way faster than tensorflow but pytorch tpu is proving me  wrong or maybe i am unable to find a way to make it faster like that tf tpu model, thank you a lot anyway for helping me

**Comment by dlibenzi** [comment]
Because in PyTorch, the input pipeline runs on the Colab/Kaggle VM, which has limited resources in terms of CPUs and RAM.
Hence the slowness (you are likely input bound and if you print the metrics we can say for sure) and OOM.
In TF the real input pipeline runs on the VM the TPU HW is attached to, which has 100+ cores and 300+GB of RAM.
If you try that, say, on TF GPU you will find the same limitations, as in that case TF will play by the same constraints PyTorch does (running pipelines on the Colab/Kaggle VM).
By the end of this year the Cloud TPU architecture will change, and that will make TF and PyTorch play by the same rules.

You also have things in your model, like reporting loss at every step, which I already mentioned it will slow down (as much as 50%) the training.
You also do not need to(device) for the inputs, when using the ParallelLoader, as those are already on device.

**Comment by dlibenzi** [comment]
You can see also the discussions in this issue:

https://github.com/pytorch/xla/issues/1870

Many times folks have a raw dataset, and iterates over and over on it (to tune hyper parameters, model tweaks, etc..).
In those case it is much better to write a cooked dataset, and then use (in a streaming fashion - like shown in the Colab posted in that issue) the cooked data for training and validation.
This way you can save both memory and CPU.

**Comment by ashaw596** [comment]
> Because in PyTorch, the input pipeline runs on the Colab/Kaggle VM, which has limited resources in terms of CPUs and RAM.
> Hence the slowness (you are likely input bound and if you print the metrics we can say for sure) and OOM.
> In TF the real input pipeline runs on the VM the TPU HW is attached to, which has 100+ cores and 300+GB of RAM.
> If you try that, say, on TF GPU you will find the same limitations, as in that case TF will play by the same constraints PyTorch does (running pipelines on the Colab/Kaggle VM).
> By the end of this year the Cloud TPU architecture will change, and that will make TF and PyTorch play by the same rules.
> 
> You also have things in your model, like reporting loss at every step, which I already mentioned it will slow down (as much as 50%) the training.
> You also do not need to(device) for the inputs, when using the ParallelLoader, as those are already on device.

Just wondering. Its more than a year later. Do we have a timeline on when there will be dataloading parity?

**Comment by JackCaoG** [comment]
@ashaw596 Cloud TPUVM is under Public Preview right now, please check out [this section](https://github.com/pytorch/xla#-running-on-a-cloud-tpu-vm)
