### ISSUE TITLE
Skipping epochs while fine-tuning a transformer model

### ISSUE THREAD

**Issue by Ravi-0809** [pytorch/xla#2077]
## ❓ Questions and Help

Hey guys, 

I'm trying to fine-tune a transformer model using the TPUs on colab. The model I'm using is Roberta, provided by huggingface trnsformers, with a custom head. I'm fine-tuning the model for 3 epochs and during the process, epoch 1 runs as expected but epoch 2 and 3 get skipped entirely. I'm attaching a screenshot for referrence. 
![Screenshot from 2020-05-15 19-53-30](https://user-images.githubusercontent.com/25024865/82061164-f88eb280-96e5-11ea-89cd-e65b21e7ebe0.png)

The tqdm bar for epochs shows that all three have completed and hence proceeds to the next fold, but the model doesn't fine-tune for 2 epochs. This same behaviour occurs for all the following folds. I'm doing a k-fold cross validation during the fine-tuning, and validation is done after each epoch.

Below are the code snippets for the run function and the code used to call that function.
`xmp.spawn(run, args=(), start_method='fork', nprocs=1)`

```
def run(param):

    for fold in range(config.FOLDS):
        model_config = transformers.RobertaConfig.from_pretrained("roberta-base")
        model_config.output_hidden_states = True
        MX = TweetModel(conf=model_config)

        train_df = dfx[dfx.kfold != fold].reset_index(drop=True)
        valid_df = dfx[dfx.kfold == fold].reset_index(drop=True)

        device = xm.xla_device()
        model = MX.to(device)
        xm.master_print(f"Pushed model to device - {model.device}")

        train_para_loader, valid_para_loader, train_len, valid_len =\
         create_datasets(train_df, valid_df, fold, device)

        num_train_steps = int(len(train_df) / config.TRAIN_BATCH_SIZE * config.EPOCHS)
        param_optimizer = list(model.named_parameters())
        no_decay = [
            "bias",
            "LayerNorm.bias",
            "LayerNorm.weight"
        ]
        optimizer_parameters = [
            {
                'params': [
                    p for n, p in param_optimizer if not any(
                        nd in n for nd in no_decay
                    )
                ], 
            'weight_decay': 0.001
            },
            {
                'params': [
                    p for n, p in param_optimizer if any(
                        nd in n for nd in no_decay
                    )
                ], 
                'weight_decay': 0.0
            },
        ]
        num_train_steps = int(
            len(train_df) / config.TRAIN_BATCH_SIZE * config.EPOCHS
        )
        optimizer = AdamW(
            optimizer_parameters, 
            lr=config.LEARNING_RATE
        )
        scheduler = get_linear_schedule_with_warmup(
            optimizer,
            num_warmup_steps=0,
            num_training_steps=num_train_steps
        )

        best_jac = 0
        num_batches = int(len(train_df) / config.TRAIN_BATCH_SIZE)

        xm.master_print("Starting training now")
        tk_epochs = tqdm(range(config.EPOCHS), desc="Epochs")
        for epoch in tk_epochs:

            if config.do_train:
                train_fn(
                    train_para_loader, 
                    model, 
                    optimizer, 
                    device,
                    num_batches,
                    scheduler,
                    train_len
                )

            if config.do_valid:
                jac = eval_fn(
                    valid_para_loader, 
                    model, 
                    device,
                    valid_len
                )
                xm.master_print(f'Epoch={epoch}, Fold={fold}, Jaccard={jac}')
                if jac > best_jac:
                        xm.save(model.state_dict(), f"model_{fold}.bin")
                        xm.master_print(f"saved model to path model_{fold}.bin")
                        best_jac = jac

```

Additional information:
* Using the nightly build of xla
* The train and validation datasets are loaded using `ParallelLoader` by creating a `DataLoader` and a `DistributedSampler` is also used
* The train and validation are itered through using this method - `tqdm(data_loader.per_device_loader(device), desc="Training")`  where device is passed as a parameter to that function from the `run()` function

I'm not able to figure out the reason for the epochs being skipped and I thought it might be due to the incorrect use of the xla library.
Any help is greatly appreciated. Thank you!

**Comment by taylanbil** [comment]
one quick thing I can observe is the following difference:

in [this example](https://github.com/pytorch/xla/blob/master/test/test_train_mp_imagenet.py#L227-L234), we create the parallel loader every epoch. In the above code, `train_para_loader` is created only once.

**Comment by Ravi-0809** [comment]
Thank you for the response @taylanbil. Creating the `ParallelLoader` on every epoch solves the issue.

**Comment by zcain117** [comment]
For models using the multiprocessing API (which is what we recommend for all models), now we recommend the new `MpDeviceLoader`:

https://github.com/pytorch/xla/blob/master/test/test_train_mp_mnist.py#L153
https://github.com/pytorch/xla/pull/2117/files
