### ISSUE TITLE
Typo in the official docs (pytorch.org/xla)

### ISSUE THREAD

**Issue by SriRangaTarun** [pytorch/xla#2087]
## 📚 Documentation

Hello everyone, great work on this amazing library! I just found a small typo in the PyTorch XLA official docs. The word "method" is spelled as "mathod" under <code>torch_xla.distributed.xla_multiprocessing.spawn</code>.

![Untitled drawing (1)](https://user-images.githubusercontent.com/24350575/82179504-19c8ec00-98fc-11ea-8aed-55a5f92d4421.png)

**Comment by dlibenzi** [comment]
Thanks for reporting!

**Comment by SriRangaTarun** [comment]
Thank you for the quick action, @dlibenzi!
