### ISSUE TITLE
Support saving/restoring RNG state

### ISSUE THREAD

**Issue by myleott** [pytorch/xla#2093]
## 🚀 Feature
Support saving/restoring RNG state.

## Motivation
While `xm.set_rng_seed` allows us to manually set the seed, forking the RNG requires the ability to save/restore as well. This functionality is needed for model parallel use cases, where we need more control over the RNG state.

## Pitch
Either add `xm.get_rng_state` and `xm.set_rng_state` or plug into the PyTorch RNG.

**Comment by dlibenzi** [comment]
I am not sure what you mean for `forking`? Do you mean `fork(2)`?
I though PyTorch (at least CUDA) was no keen on `fork(2)` things ...

**Comment by myleott** [comment]
I meant something like `torch.random.fork_rng`.

There are two use cases for this. For model parallel we need to fork the RNG when applying dropout in some cases (here’s an example: https://github.com/pytorch/fairseq/blob/775122950d145382146e9120308432a9faf9a9b8/fairseq/model_parallel/modules/multihead_attention.py#L230)

**Comment by myleott** [comment]
Added in #2096
