### ISSUE TITLE
ComputationClient and xla_service.proto parallels

### ISSUE THREAD

**Issue by cjolivier01** [pytorch/xla#2108]
## ❓ Questions and Help
Hi, as you're of course aware, ComputationClient is a pretty close parallel to xla_service.proto
Of course, calls for ComputationClient are piped through Grp-session rather than xla_service, which sort of map to the same things (session offering some consolidation it seems on things like DeconstructTuple on outputs, for instance, which take several separate calls via xla_service).  Some things are curious, such as DeconstructTuple exists in ComputationClient, but not used, so I am not sure if the code is moving towards or away from xla_service?  Maybe it's just a coincidence?  Reason being, I am building a proxy from ComputationClient to xla_service (via derived class) and I wonder if I am going to lose anything in the process?  I considered doing it at the grpc-session level, but tbh, it's just a bit "icky" down there on that side and I need some custom behavior for my use-case (I swear there's n ROI in there somewhere :D )

Any grounding/advice on this front would be greatly appreciated.

**Comment by dlibenzi** [comment]
The first implementation was indeed using XLA service, but that would not have worked in Cloud TPU as there is no XLA service exposed (and neither there was the intention at that time to expose it).
It was also missing features like TPU mesh initialization, and other things.
Then XRT was created, and the few "extra" APIs you see are the fruit of the reshaping/optimization of the API which happened over time.

That API will change again once Cloud TPU will move to the new 1VM architecture, but the core concepts are pretty simple and are going to be very close to the current API.

**Comment by cjolivier01** [comment]
Thank you for the information!
