### ISSUE TITLE
Why ParallelLoader is epoch-wise ?

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/xla#2115]
## ❓ Questions and Help

I would like to understand why in all the examples and test usage of `ParallelLoader` is epoch-wise:
```python
for epoch in range(1, FLAGS['num_epochs'] + 1):
    para_loader = ParallelLoader(train_loader, [device])
    data_iter = para_loader.per_device_loader(device)
```

Can't we use a single instance of `para_loader` for the whole training ?
```python
para_loader = ParallelLoader(train_loader, [device])
for epoch in range(1, FLAGS['num_epochs'] + 1):
    data_iter = para_loader.per_device_loader(device)
```

Thanks !

**Comment by dlibenzi** [comment]
Not in that way.
But the posted PR allows for even simpler code.

**Comment by vfdev-5** [comment]
Yes, but for the current stable API of v1.5 ?
Any specific reason for epoch wise restart ?

**Comment by dlibenzi** [comment]
Could be back-ported to 1.5 ... but we always suggest running on a recent nightly.
For experience, `Stable` has never been more stable than `nightly`.

The reason for epoch wise restart, and the reason the added wrapper only works for multi-processing based data parallelism, comes from the roots of that class, which started with multi-threading based parallelism.
In that case, you have to create one ParallelLoader, and have each thread pull the per-device ones.

**Comment by vfdev-5** [comment]
OK, I understand from playing with the code of `ParallelLoader`, that its role is to loop once over the provided loader and it can not restart the data loader.

I close the issue as answered.
