### ISSUE TITLE
Using 2 TPUs (separately) on one VM 

### ISSUE THREAD

**Issue by joshclancy** [pytorch/xla#2124]
## ❓ Questions and Help
I am running experiments on a VM and often want to train different networks at the same time. Using a GPU I would specify which GPU I wanted for which task. How would I do this with TPUs??
I started with this:
 export XRT_TPU_CONFIG="tpu_worker;0;TPUIP1:8470"
 export XRT_TPU_CONFIG="tpu_worker;1;TPUIP2:8470"

which when listed seems to work: (edited to take out IP)

NAME    ZONE           ACCELERATOR_TYPE  NETWORK_ENDPOINTS   NETWORK  RANGE             STATUS
node-2  us-central1-f  v2-8              IP:8470  default  IP/29  READY
node-1  us-central1-f  v2-8              IP:8470   default  IP/29   READY

But then when I run:

```
# imports the torch_xla package
print("start")
import torch_xla
print("1")
import torch_xla.core.xla_model as xm
print("2")
import torch_xla.debug.metrics as met
print("3")
import torch_xla.distributed.parallel_loader as pl
print("4")
# dev = "cuda"
dev = xm.xla_device()
print("done")
```

The dev = xm.xla_device() breaks. 

I have tried:
dev = xm.xla_device("0"), dev = xm.xla_device(0), dev = xm.xla_device("node-1"), dev = xm.xla_device(node-1)... etc.

I have also been looking online but haven't found anything. Please help and thankyou!

**Comment by dlibenzi** [comment]
The different `XRT_TPU_CONFIG` should work.
Of course, you need to do that from two different shells or subprocesses.

**Comment by joshclancy** [comment]
hmm well, I keep getting this error, I am now using 2 jupyter notebooks from 2 shells just to be sure:

   10 print("4")
     11 # dev = "cuda"
---> 12 dev = xm.xla_device()
     13 print("done")

/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/core/xla_model.py in xla_device(n, devkind)
    136   if n is None:
    137     devices = get_xla_supported_devices(
--> 138         devkind=[devkind] if devkind is not None else None)
    139     assert devices, 'No devices of {} kind'.format(devkind or 'ANY')
    140     # This is a utility API mainly called from tests or simple code which wants

/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/core/xla_model.py in get_xla_supported_devices(devkind, max_devices)
     40     The list of device strings.
     41   """
---> 42   xla_devices = torch_xla._XLAC._xla_get_devices()
     43   devkind = devkind or ['TPU', 'GPU', 'CPU']
     44   for kind in devkind:

RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:1223 : Check failed: session.Run({tensorflow::Output(result, 0)}, &outputs) == ::tensorflow::Status::OK() (Invalid argument: No matching devices found for '/job:tpu_worker/replica:0/task:1/device:TPU_SYSTEM:0' vs. OK)
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	xla::XrtComputationClient::InitializeAndFetchTopology(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tensorflow::ConfigProto const&)
	xla::XrtComputationClient::InitializeDevices(std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
	xla::XrtComputationClient::XrtComputationClient(xla::XrtComputationClient::Options, std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
	xla::ComputationClient::Create()
	xla::ComputationClient::Get()
	
	
	_PyCFunction_FastCallDict
	
	_PyEval_EvalFrameDefault

**Comment by dlibenzi** [comment]
Try this.
Shell 1:
```Shell
export XRT_TPU_CONFIG="tpu_worker;0;TPUIP1:8470"
```

Shell 2:
```Shell
export XRT_TPU_CONFIG="tpu_worker;0;TPUIP2:8470"
```

**Comment by joshclancy** [comment]
That worked! thank you
