### ISSUE TITLE
[PT_BREAK] Improve CUDA performance of GroupNorm

### ISSUE THREAD

**Issue by BIT-silence** [pytorch/xla#2126]
In https://github.com/pytorch/pytorch/pull/28204, we are trying to improve CUDA performance of PyTorch GroupNorm. In this PR, we removed the native_batch_norm function in group_norm. Instead, we introduced new native_group_norm function which is much faster. The current xla test for GroupNorm has one check of xla::native_batch_norm at https://github.com/pytorch/xla/blob/d75a2ea756dedbbd128aea1d6dc27551a3b67ef2/test/cpp/test_aten_xla_tensor.cpp#L1470

Maybe we have to change it to native_group_norm after https://github.com/pytorch/pytorch/pull/28204 merged.

**Comment by dlibenzi** [comment]
That mean we will have to take action to deal with `native_group_norm()` as otherwise we will take a trip to CPU when `group_norm()` is called.

**Comment by ailzhang** [comment]
This is merged, closing
