### ISSUE TITLE
What are the Root(s) of the Graph?

### ISSUE THREAD

**Issue by yaochengji** [pytorch/xla#2127]
## ❓ Questions and Help
As I know, torch xla tensors are lazy, different from native torch. And I'm afraid their results differ in some scenes.  I tried to run the code below, it ran correctly! So I guess when `print(r1)`, both `r0` and `r1` are the roots of the graph?

```
xla_device = xm.xla_device()
x = torch.ones(2, 2, device=xla_device)
y = torch.ones(2, 2, device=xla_device)
z = torch.ones(2, 2, device=xla_device)
r0 = x + y
r1 = r0 + z
x.add_(z * 100)
print(r1)
print(r0)
```

**Comment by dlibenzi** [comment]
`Leaf` vs `Root`, `Source` vs `Sink`, are different ways to name the inputs/outputs of a graph based computation.

When you materialize `r0` and `r1` they become `Roots` as they will be outputs of the graph based computation.
The most efficient way to materialize a set of tensors is to use the `unlazy()` API:

https://github.com/pytorch/xla/blob/3b01b57fedfd76e983909436345218d9e43c7cb5/torch_xla/core/xla_model.py#L217

Example:
```Python
unlazy([r0, r1])
print(r0.cpu())
print(r1.cpu())
```

With that API only one graph execution will happen, and in that execution both `r0` and `r1` will be roots.

**Comment by yaochengji** [comment]
Thanks for your reply, @dlibenzi.

But I'm still confused. I printed the tensor in the order below.
```
print(r1)
print(x)
print(r0)
```

stdout
```
tensor([[3., 3.],
        [3., 3.]], device='xla:0')
tensor([[101., 101.],
        [101., 101.]], device='xla:0')
tensor([[2., 2.],
        [2., 2.]], device='xla:0')
```
I checked the graph by using `XLA_SAVE_TENSORS_FILE`, I could see that only `r1` is root when `print(r1)`. When `print(r0)`, a new graph was compiled and executed. At that time, `x` was already updated to the new value,  how could  pytorch xla make the result of `r0` be `old_x + y = [[2, 2], [2, 2]]`, not `new_x + y = [[101, 101], [101, 101]]`?

**Comment by dlibenzi** [comment]
When you execute the graph, you do not re-do the operations. You do not re-walk the python code.
The graph is created when python is executed.
The reason I said to use `unlazy()` is because you save N-1 graph executions for N roots.

**Comment by yaochengji** [comment]
Thanks.
