### ISSUE TITLE
Cumulative behaviour of all_reduce on nightly

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/xla#2134]
## To Reproduce
In Colab with nightly:
```python
import torch
import torch_xla
import torch_xla.core.xla_model as xm
import torch_xla.distributed.xla_multiprocessing as xmp

def simple_map_fn(index, flags):
  torch.manual_seed(1234)
  xm.rendezvous('init')
  device = xm.xla_device()

  # ONE
  n = 4
  xm.master_print("- before n={}".format(n))
  # all reduce n
  t_n = torch.tensor(n, dtype=torch.float32, device=device)
  xm.all_reduce('sum', [t_n, ])
  n = t_n.item()
  xm.master_print("- after n={}".format(n))

  # TWO (should be like a separate stuff)
  n = 4
  xm.master_print("-- before n={}".format(n))
  # all reduce n
  t_n2 = torch.tensor(n, dtype=torch.float32, device=device)
  xm.all_reduce('sum', [t_n2, ])
  n = t_n2.item()
  xm.master_print("-- after n={}".format(n))

  print("end")

flags = {}
xmp.spawn(simple_map_fn, args=(flags,), nprocs=8, start_method='fork')
```
>>>
```
- before n=4
- after n=32.0
-- before n=4
-- after n=256.0
end
end
end
end
end
end
end
end
```

## Expected behavior
```
- before n=4
- after n=32.0
-- before n=4
-- after n=32.0
```
like with
- PyTorch version: 1.5.0a0+ab660ae
- PyTorch xla version: 1.5

## Environment

 - Reproducible on XLA backend [CPU/TPU]: TPU
 - torch_xla version: 
PyTorch version: 1.6.0a0+916084d
PyTorch xla version: 1.6+3dee9ae
 - Any other relevant information. In case of issues related to slow executions, re-compilations, etc.., it is useful to have the `tar.gz` report from https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#using-debug_runpy-to-collect-debug-information

**Comment by dlibenzi** [comment]
Hmm ... I think I know what is going on 😄 
Can you try `n = 5` at the second iteration?

**Comment by vfdev-5** [comment]
@dlibenzi I already tried and get 40 as expected :)

**Comment by vfdev-5** [comment]
@dlibenzi for my understanding, why it worked in 1.5 and is broken in nightly ?

**Comment by dlibenzi** [comment]
Because input/output aliasing was added after 1.5.
