### ISSUE TITLE
Inconsistent results from getting number of devices/ world size before and after spawn

### ISSUE THREAD

**Issue by harpone** [pytorch/xla#2141]
## 🐛 Bug

Some weirdness before and after calling `xmp.spawn()` with TPU pod training (this is on 4 nodes):

BEFORE SPAWN
```
torch_xla._XLAC._xla_get_replication_devices_count=0
xm.xrt_world_size()=4
len(xm.get_xla_supported_devices(max_devices=None))=8
```

AFTER SPAWN
```
torch_xla._XLAC._xla_get_replication_devices_count=32
xm.xrt_world_size()=32
len(xm.get_xla_supported_devices(max_devices=None))=1
```

Not a huge issue but can be confusing... also leaving this here as a note to self and others.

**Comment by dlibenzi** [comment]
XLA APIs are not supposed to be called at all, before the `xmp.spawn()` call.
Especially with `fork` start method.

**Comment by harpone** [comment]
OK got it! Would be nice to have that on boldface somewhere :)
