### ISSUE TITLE
RuntimeError: TPU node-v3-32 is not HEALTHY yet. Re-run when all TPUs are HEALTHY

### ISSUE THREAD

**Issue by harpone** [pytorch/xla#2142]
## 🐛 Bug

After training in a multi-node setting is interrupted (getting an error or interrupting), the TPU pod seems to fall back to an "unhealthy" state and doesn't seem to recover... the only way to get around that seems to be to delete the pod and create a new one, which takes quite a while...

Can't see any hanging python processes on any of the VMs.

Also, it doesn't seem to be possible to stop a TPU pod... I'm only able to delete them.

Any advice?

## Environment

 - Reproducible on XLA backend [TPU]:
 - torch_xla version: 1.5

**Comment by harpone** [comment]
Actually it seems that if there's an error on all nodes, it's OK. But e.g. interrupting by CTRL+C on one VM leads to the above problem... is there something I could do to ensure graceful exit at e.g. `except KeyboardInterrupt`?

**Comment by dlibenzi** [comment]
Can you post the error "on all nodes" that you get?
What is the behavior you notice when you mention that it does not work anymore?

Also, please, use `nightly`.

**Comment by harpone** [comment]
No longer getting this even with torch-xla-1.5 so closing... maybe it was just a broken worker VM.
