### ISSUE TITLE
mark_step() performing multiple steps

### ISSUE THREAD

**Issue by cjolivier01** [pytorch/xla#2145]
## ❓ Questions and Help
Hi,

I am not asking you guys to implement, but I have a question (in case I need to implement for myself, unless others want it, then I am happy to submit):

Imagine I have a "device" that is *extremely* fast, batches per second in the millions (for the sake of argument).  In addition, the graph compile is somewhat expensive for this "device" compared to a TPU, for instance.

Given these constraints, and ignoring the possibilities of multi-process/multi-node possibilities for the moment, I was thinking that it might make sense to have mark_step perform more than one batch execution for the following reasons:
* The python execution, including the aten dynamic graph construction of each train loop is slower than the time it takes to actually train on that batch's data by orders of magnitude
* Due to compile heaviness in this case, it is important that python code doesn't change frequently and cause another recompile for at least some reasonable number of batches, even if that must be foreced by not allowing python code to run for some number of steps

Expectations would be:
* Only the results from the last batch of data is available via TransferFromServer() after that multiple-run mark_step() call.
* Any code within the training loop that cares about the current step would need to be aware that the step increment was not one for the given training loop.
* Data loader would also send the prescribed number of steps per iteration
* Assumption is that the graph has coalesced in this case (and that this is known) and no more compiles are occurring for a given mark_step() interval (i.e. wouldn't want to call ExecuteComputation() on some arbitrary sideband calculation 15000 times in a row :) )

So underneath, roughly the equivalent concept of ExecuteComputation() gets called some N times before returning from mark_step(), for instance.

I was wondering there is anything serious I am missing from this scenario that would make this approach problematic?

Best regards,

-Chris

**Comment by cjolivier01** [comment]
ok

**Comment by dlibenzi** [comment]
Sorry, I do not have much time left to follow Pindaric Flights 😄 

I am not sure I follow what you are trying to achieve there, but some time ago I created a WIP to avoid running the python code and caching the XLA computation:

https://github.com/pytorch/xla/commit/5fb44ce78a67ee66ec47b2c9b65dc61968966e40

At the end, is added complexity, with little/no return for the most common cases, and some tricky pitfalls.
We hide python code time behind computation, so unless one have models with very little step time (why not bump batch size then?), the python code effect is essentially zero.
There are also pitfalls related to python conditional executions, which would be silently chopped in that case.

**Comment by cjolivier01** [comment]
Fair enough (on the "Pindaric Flights" -- I had to Google that :D )
Your input is always greatly appreciated!

**Comment by cjolivier01** [comment]
oh, btw, in answer to your question, for a sufficient batch size increase, there are memory constraints which are exceeded.

**Comment by dlibenzi** [comment]
There is usually a proportionality between used device memory, and step time.
Since the used memory need to be accessed (ML computations are no hash lookups kinda things), and the memory BW is limited, big memory rarely correlates with small step times.
