### ISSUE TITLE
xmp.spawn multiprocessing freezes at model.to(device)

### ISSUE THREAD

**Issue by SriRangaTarun** [pytorch/xla#2160]
## ❓ Questions and Help

Hello everyone! I am facing a small issue with XLA multiprocessing (<code>xmp.spawn</code>). The multiprocessing just freezes and stops executing for a long time at the line: <code>network = EFNCD().to(device)</code>. <code>EFNCD</code> is an EfficientNet-B7 model with a dense head, and this line of code is wrapped inside the <code>train_fn</code> function which is passed to <code>xmp.spawn</code> I am not sure why this happens. Can someone guide me on this? Thank you!

**Comment by SriRangaTarun** [comment]
I am still looking for the entire source code that produces the problem. I will post it here as soon as I find it :D

**Comment by dlibenzi** [comment]
Any chance you can create a small Colab repro so we can debug?

**Comment by SriRangaTarun** [comment]
I will try to make a Colab repro as soon as possible. Thanks, @dlibenzi! Should I keep the issue open until I provide the repro?

**Comment by dlibenzi** [comment]
Yes, please. Keep open.

**Comment by mwesthelle** [comment]
Hi @SriRangaTarun, did you manage to find a solution for this? I'm facing the same issue.
