### ISSUE TITLE
Failed C++ tests on XLA GPU backend. 

### ISSUE THREAD

**Issue by ailzhang** [pytorch/xla#2168]
https://github.com/pytorch/xla/pull/2159
[  FAILED  ] AtenXlaTensorTest.TestIndexAdd
[  FAILED  ] AtenXlaTensorTest.TestIndexAddInPlace
[  FAILED  ] AtenXlaTensorTest.TestIndexCopy
[  FAILED  ] AtenXlaTensorTest.TestIndexCopyInPlace
[  FAILED  ] AtenXlaTensorTest.TestTransposedConv2DBackward
[  FAILED  ] AtenXlaTensorTest.TestConv3DBackward
[  FAILED  ] AtenXlaTensorTest.TestTransposedConv3DBackward

**Comment by JackCaoG** [comment]
All of the test mentioned above is now passing on GPU, close the issue
