### ISSUE TITLE
Get current default device public API

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/xla#2171]
## 🚀 Feature & Motivation

@dlibenzi I was wondering if you think it would make sense to have a method to expose 
internal `_xla_get_default_device()` method.

Use-case, user would like to run in parallel without any synchronization multiple runs like that
```python
folds=5
Parallel(n_jobs=folds, backend="threading")(delayed(main_fold)(i) for i in range(folds))
``` 
where
```
def foo():
     # get current device
     # device = xm.xla_current_device()


def main_fold(fold):
    device = xm.xla_device(fold + 1)
    ...
    foo()
    ...
```

Alternatively, we can pass the argument device everywhere, but it would be more simple to have it with `xm.xla_*device()`.

**Comment by dlibenzi** [comment]
From an API POV, it is batter to pass down the information.

I also notice you are still using threading, which for us is a tentative-support.
Meaning, if we get a roadblock in the future where threading does not work, we will drop it.

**Comment by vfdev-5** [comment]
> I also notice you are still using threading, which for us is a tentative-support.
Meaning, if we get a roadblock in the future where threading does not work, we will drop it.

What would be an equivalent to replace threading and run on 5 devices (not 8) in parallel but without any synchronization ?

**Comment by dlibenzi** [comment]
On 5 devices, neither of them will work, as soon at you start using any collective API.
