### ISSUE TITLE
Why does this LSTM training stop after few steps, even when shapes are same ?

### ISSUE THREAD

**Issue by Jeevesh8** [pytorch/xla#2172]
## ❓ Questions and Help
I extended [this](https://gist.github.com/dlibenzi/d049894d6e1cde15f0d39a6149a1fdb5#file-xla_lstm-py-L56) lstm implementation provided by @dlibenzi . But, running seems to stop after few steps, and starts after some time as though re-compilation is happening. But all the shapes are same.
Please help. This is the [colab notebook](https://colab.research.google.com/drive/18m01KoOcKqt1GBWDk_bcmocXygjxoQWU?usp=sharing) showing the issue.

**Comment by dlibenzi** [comment]
If you print the metrics, it will show whether it is recompiling:

https://github.com/pytorch/xla/blob/0c58086654b1aa4ee57c24d83b9fdc5577770797/test/test_train_mp_mnist.py#L170
