### ISSUE TITLE
[PT_BREAK] AtenXlaTensorTest.TestGroupNorm

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/xla#2179]
https://github.com/pytorch/pytorch/pull/39636

```
Jun 08 05:00:23 [  PASSED  ] 550 tests.
Jun 08 05:00:23 [  FAILED  ] 1 test, listed below:
Jun 08 05:00:23 [  FAILED  ] AtenXlaTensorTest.TestGroupNorm
```

https://circleci.com/gh/pytorch/pytorch/5729684?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by JackCaoG** [comment]
Thanks for reporting, https://github.com/pytorch/xla/pull/2150 is merged and should fix this!
