### ISSUE TITLE
Running unsupported layers between supported layers

### ISSUE THREAD

**Issue by lmorino** [pytorch/xla#2203]
## ❓ Questions and Help
Hello,

If a module has the following layers in sequence: A->B->C->D and layers A,B can be run on TPU but C is unsupported. I understand that when C is dispatched to torch/sage, an XLA computation holding A->B will be invoked and C will run on CPU. 

If D, the last layer in the module is supported. When and hw is that compiled and run on TPU

Thanks!

**Comment by dlibenzi** [comment]
Yes, this happens all transparently for the user.
Of course, running stuff on pytorch/CPU will likely be slower.

**Comment by lmorino** [comment]
I see, but I am curious about how layer D would be executed.

**Comment by dlibenzi** [comment]
D will run on TPU.

**Comment by lmorino** [comment]
Is there a way to trigger it?
