### ISSUE TITLE
error when running the demo

### ISSUE THREAD

**Issue by ipyffor** [pytorch/xla#2207]
![image](https://user-images.githubusercontent.com/47955238/84492476-cd918180-acd8-11ea-8266-71b04596fc05.png)
notebook：https://colab.research.google.com/drive/1h025d1NYs9BF3k2T0hNCgklmjFJfLtqj?usp=sharing

**Comment by dlibenzi** [comment]
The Colab is not public ... but, are you trying to run MaskRCNN or similar models?

**Comment by ipyffor** [comment]
The problem has been solved by following:
model = torch.hub.load('pytorch/vision', 'resnet50', pretrained=True) ==>
model = torch.hub.load('pytorch/vision:v0.6.0', 'resnet50', pretrained=True)
