### ISSUE TITLE
How to call tensor.item() on single proc after a collective op ?

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/xla#2225]
## ❓ Questions and Help

Hi, I'm trying to log tensor value by calling `res[0].item()` in a single process after `all_reduce` on this tensor. Execution seems to hang.

To reproduce:
```python
import torch
import torch_xla.core.xla_model as xm
import torch_xla.distributed.xla_multiprocessing as xmp


def test_tensor_item(index):

  xm.rendezvous('init')
  print(index, "test_tensor_item")

  device = xm.xla_device()
  rank = xm.get_ordinal()
  t = torch.tensor([rank + 0.0, rank + 1.0, rank + 2.0], device=device)

  res = xm.all_reduce("sum", t)
  print(index, res, flush=True)

  xm.rendezvous('sync')
  if index == 0:
      print(index, res[0].item(), flush=True)

xmp.spawn(test_tensor_item, args=(), nprocs=8, start_method='fork')
```

Any hints, please.
Thanks

**Comment by dlibenzi** [comment]
That will not work, as tend to create asymmetric computations across cores (which are OK ... unless you use cross replica reduce ops).
This is what `xm.master_print()` is for:

https://github.com/pytorch/xla/blob/33aac1726fd5649c7e5e25c338ef3a3709a6baa9/torch_xla/core/xla_model.py#L126

```Python
xm.master_print(res[0].item(), flush=True)
```

**Comment by vfdev-5** [comment]
Well, here `print(index, res[0].item(), flush=True)` is just for an example. Real code uses an experiment tracking system like tensorboard:
```
writer.add_scalar("test", res[0].item())
```

Looking at the code of `xm.master_print` it does almost the same thing as in my snippet. Am i missing something ?

**Comment by dlibenzi** [comment]
Your snippet does not do the same thing.
In your snippet `item()` (a graph execution) is only called for rank 0, which creates uneven computations.
In my case, `item()` is called on every core, and the result used only on rank 0.
So in a more generic case, I suggest you using a step closure, as it is faster:

https://github.com/pytorch/xla/blob/33aac1726fd5649c7e5e25c338ef3a3709a6baa9/torch_xla/core/xla_model.py#L494

https://github.com/pytorch/xla/blob/33aac1726fd5649c7e5e25c338ef3a3709a6baa9/test/test_train_mp_mnist.py#L134

Remember to pass the *Tensors* as step closure arguments, and call `item()` inside the step closure itself.
