### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by antoniomastro1996** [pytorch/xla#2227]
## ❓ Questions and Help

Hi everybody. 
During my experiments with a revisited version of the following notebook https://colab.research.google.com/drive/1jwXgtOXE8v8_qkiOCbjFQRFC5semK8T7?usp=sharing

I got the error posted below.
I'm also using Colab pro, with the maximum available RAM.

Thanks in advance :)

06/15/2020 16:24:15 - INFO - transformers.training_args -   PyTorch: setting up devices
06/15/2020 16:24:15 - WARNING - __main__ -   Process rank: -1, device: xla:1, n_gpu: 0, distributed training: False, 16-bits training: False
06/15/2020 16:24:15 - INFO - __main__ -   Training/evaluation parameters TrainingArguments(output_dir='./models/tpu', overwrite_output_dir=True, do_train=True, do_eval=False, do_predict=False, evaluate_during_training=False, per_device_train_batch_size=8, per_device_eval_batch_size=8, per_gpu_train_batch_size=8, per_gpu_eval_batch_size=8, gradient_accumulation_steps=4, learning_rate=0.0001, weight_decay=0.0, adam_epsilon=1e-08, max_grad_norm=1.0, num_train_epochs=8, max_steps=-1, warmup_steps=0, logging_dir='runs/Jun15_16-24-15_8ae1f3efa3b8', logging_first_step=False, logging_steps=500, save_steps=500, save_total_limit=None, no_cuda=False, seed=42, fp16=False, fp16_opt_level='O1', local_rank=-1, tpu_num_cores=8, tpu_metrics_debug=False, dataloader_drop_last=False)
06/15/2020 16:24:15 - INFO - transformers.training_args -   PyTorch: setting up devices
06/15/2020 16:24:15 - INFO - transformers.training_args -   PyTorch: setting up devices
06/15/2020 16:24:15 - WARNING - __main__ -   Process rank: -1, device: xla:1, n_gpu: 0, distributed training: False, 16-bits training: False
06/15/2020 16:24:15 - WARNING - __main__ -   Process rank: -1, device: xla:1, n_gpu: 0, distributed training: False, 16-bits training: False
06/15/2020 16:24:15 - INFO - __main__ -   Training/evaluation parameters TrainingArguments(output_dir='./models/tpu', overwrite_output_dir=True, do_train=True, do_eval=False, do_predict=False, evaluate_during_training=False, per_device_train_batch_size=8, per_device_eval_batch_size=8, per_gpu_train_batch_size=8, per_gpu_eval_batch_size=8, gradient_accumulation_steps=4, learning_rate=0.0001, weight_decay=0.0, adam_epsilon=1e-08, max_grad_norm=1.0, num_train_epochs=8, max_steps=-1, warmup_steps=0, logging_dir='runs/Jun15_16-24-15_8ae1f3efa3b8', logging_first_step=False, logging_steps=500, save_steps=500, save_total_limit=None, no_cuda=False, seed=42, fp16=False, fp16_opt_level='O1', local_rank=-1, tpu_num_cores=8, tpu_metrics_debug=False, dataloader_drop_last=False)
06/15/2020 16:24:15 - INFO - transformers.tokenization_utils -   Model name '/content/drive/My Drive/to_convert/model.ckpt-500000.model' not found in model shortcut name list (t5-small, t5-base, t5-large, t5-3b, t5-11b). Assuming '/content/drive/My Drive/to_convert/model.ckpt-500000.model' is a path, a model identifier, or url to a directory containing tokenizer files.
06/15/2020 16:24:15 - INFO - transformers.training_args -   PyTorch: setting up devices
06/15/2020 16:24:15 - INFO - __main__ -   Training/evaluation parameters TrainingArguments(output_dir='./models/tpu', overwrite_output_dir=True, do_train=True, do_eval=False, do_predict=False, evaluate_during_training=False, per_device_train_batch_size=8, per_device_eval_batch_size=8, per_gpu_train_batch_size=8, per_gpu_eval_batch_size=8, gradient_accumulation_steps=4, learning_rate=0.0001, weight_decay=0.0, adam_epsilon=1e-08, max_grad_norm=1.0, num_train_epochs=8, max_steps=-1, warmup_steps=0, logging_dir='runs/Jun15_16-24-15_8ae1f3efa3b8', logging_first_step=False, logging_steps=500, save_steps=500, save_total_limit=None, no_cuda=False, seed=42, fp16=False, fp16_opt_level='O1', local_rank=-1, tpu_num_cores=8, tpu_metrics_debug=False, dataloader_drop_last=False)
06/15/2020 16:24:15 - WARNING - __main__ -   Process rank: -1, device: xla:1, n_gpu: 0, distributed training: False, 16-bits training: False
06/15/2020 16:24:15 - INFO - __main__ -   Training/evaluation parameters TrainingArguments(output_dir='./models/tpu', overwrite_output_dir=True, do_train=True, do_eval=False, do_predict=False, evaluate_during_training=False, per_device_train_batch_size=8, per_device_eval_batch_size=8, per_gpu_train_batch_size=8, per_gpu_eval_batch_size=8, gradient_accumulation_steps=4, learning_rate=0.0001, weight_decay=0.0, adam_epsilon=1e-08, max_grad_norm=1.0, num_train_epochs=8, max_steps=-1, warmup_steps=0, logging_dir='runs/Jun15_16-24-15_8ae1f3efa3b8', logging_first_step=False, logging_steps=500, save_steps=500, save_total_limit=None, no_cuda=False, seed=42, fp16=False, fp16_opt_level='O1', local_rank=-1, tpu_num_cores=8, tpu_metrics_debug=False, dataloader_drop_last=False)
06/15/2020 16:24:15 - INFO - transformers.tokenization_utils -   Model name '/content/drive/My Drive/to_convert/model.ckpt-500000.model' not found in model shortcut name list (t5-small, t5-base, t5-large, t5-3b, t5-11b). Assuming '/content/drive/My Drive/to_convert/model.ckpt-500000.model' is a path, a model identifier, or url to a directory containing tokenizer files.
06/15/2020 16:24:15 - INFO - transformers.tokenization_utils -   Model name '/content/drive/My Drive/to_convert/model.ckpt-500000.model' not found in model shortcut name list (t5-small, t5-base, t5-large, t5-3b, t5-11b). Assuming '/content/drive/My Drive/to_convert/model.ckpt-500000.model' is a path, a model identifier, or url to a directory containing tokenizer files.
06/15/2020 16:24:15 - INFO - transformers.tokenization_utils -   Model name '/content/drive/My Drive/to_convert/model.ckpt-500000.model' not found in model shortcut name list (t5-small, t5-base, t5-large, t5-3b, t5-11b). Assuming '/content/drive/My Drive/to_convert/model.ckpt-500000.model' is a path, a model identifier, or url to a directory containing tokenizer files.
06/15/2020 16:24:15 - WARNING - transformers.tokenization_utils -   Calling T5Tokenizer.from_pretrained() with the path to a single file or url is deprecated
06/15/2020 16:24:15 - INFO - transformers.training_args -   PyTorch: setting up devices
06/15/2020 16:24:15 - WARNING - transformers.tokenization_utils -   Calling T5Tokenizer.from_pretrained() with the path to a single file or url is deprecated
06/15/2020 16:24:15 - WARNING - transformers.tokenization_utils -   Calling T5Tokenizer.from_pretrained() with the path to a single file or url is deprecated
06/15/2020 16:24:15 - INFO - transformers.tokenization_utils -   loading file /content/drive/My Drive/to_convert/model.ckpt-500000.model
06/15/2020 16:24:15 - WARNING - transformers.tokenization_utils -   Calling T5Tokenizer.from_pretrained() with the path to a single file or url is deprecated
06/15/2020 16:24:15 - WARNING - __main__ -   Process rank: -1, device: xla:1, n_gpu: 0, distributed training: False, 16-bits training: False
06/15/2020 16:24:15 - INFO - transformers.tokenization_utils -   loading file /content/drive/My Drive/to_convert/model.ckpt-500000.model
06/15/2020 16:24:15 - INFO - transformers.tokenization_utils -   loading file /content/drive/My Drive/to_convert/model.ckpt-500000.model
06/15/2020 16:24:15 - INFO - transformers.tokenization_utils -   loading file /content/drive/My Drive/to_convert/model.ckpt-500000.model
06/15/2020 16:24:15 - INFO - __main__ -   Training/evaluation parameters TrainingArguments(output_dir='./models/tpu', overwrite_output_dir=True, do_train=True, do_eval=False, do_predict=False, evaluate_during_training=False, per_device_train_batch_size=8, per_device_eval_batch_size=8, per_gpu_train_batch_size=8, per_gpu_eval_batch_size=8, gradient_accumulation_steps=4, learning_rate=0.0001, weight_decay=0.0, adam_epsilon=1e-08, max_grad_norm=1.0, num_train_epochs=8, max_steps=-1, warmup_steps=0, logging_dir='runs/Jun15_16-24-15_8ae1f3efa3b8', logging_first_step=False, logging_steps=500, save_steps=500, save_total_limit=None, no_cuda=False, seed=42, fp16=False, fp16_opt_level='O1', local_rank=-1, tpu_num_cores=8, tpu_metrics_debug=False, dataloader_drop_last=False)
06/15/2020 16:24:15 - INFO - transformers.modeling_utils -   loading weights file /content/drive/My Drive/to_convert/t5_model.bin
06/15/2020 16:24:15 - INFO - transformers.modeling_utils -   loading weights file /content/drive/My Drive/to_convert/t5_model.bin
06/15/2020 16:24:15 - INFO - transformers.modeling_utils -   loading weights file /content/drive/My Drive/to_convert/t5_model.bin
06/15/2020 16:24:15 - INFO - transformers.training_args -   PyTorch: setting up devices
06/15/2020 16:24:15 - WARNING - __main__ -   Process rank: -1, device: xla:1, n_gpu: 0, distributed training: False, 16-bits training: False
06/15/2020 16:24:15 - INFO - __main__ -   Training/evaluation parameters TrainingArguments(output_dir='./models/tpu', overwrite_output_dir=True, do_train=True, do_eval=False, do_predict=False, evaluate_during_training=False, per_device_train_batch_size=8, per_device_eval_batch_size=8, per_gpu_train_batch_size=8, per_gpu_eval_batch_size=8, gradient_accumulation_steps=4, learning_rate=0.0001, weight_decay=0.0, adam_epsilon=1e-08, max_grad_norm=1.0, num_train_epochs=8, max_steps=-1, warmup_steps=0, logging_dir='runs/Jun15_16-24-15_8ae1f3efa3b8', logging_first_step=False, logging_steps=500, save_steps=500, save_total_limit=None, no_cuda=False, seed=42, fp16=False, fp16_opt_level='O1', local_rank=-1, tpu_num_cores=8, tpu_metrics_debug=False, dataloader_drop_last=False)
06/15/2020 16:24:15 - INFO - transformers.tokenization_utils -   Model name '/content/drive/My Drive/to_convert/model.ckpt-500000.model' not found in model shortcut name list (t5-small, t5-base, t5-large, t5-3b, t5-11b). Assuming '/content/drive/My Drive/to_convert/model.ckpt-500000.model' is a path, a model identifier, or url to a directory containing tokenizer files.
06/15/2020 16:24:15 - WARNING - transformers.tokenization_utils -   Calling T5Tokenizer.from_pretrained() with the path to a single file or url is deprecated
06/15/2020 16:24:15 - INFO - transformers.modeling_utils -   loading weights file /content/drive/My Drive/to_convert/t5_model.bin
06/15/2020 16:24:15 - INFO - transformers.tokenization_utils -   Model name '/content/drive/My Drive/to_convert/model.ckpt-500000.model' not found in model shortcut name list (t5-small, t5-base, t5-large, t5-3b, t5-11b). Assuming '/content/drive/My Drive/to_convert/model.ckpt-500000.model' is a path, a model identifier, or url to a directory containing tokenizer files.
06/15/2020 16:24:15 - WARNING - transformers.tokenization_utils -   Calling T5Tokenizer.from_pretrained() with the path to a single file or url is deprecated
06/15/2020 16:24:15 - INFO - transformers.tokenization_utils -   loading file /content/drive/My Drive/to_convert/model.ckpt-500000.model
06/15/2020 16:24:15 - INFO - transformers.tokenization_utils -   loading file /content/drive/My Drive/to_convert/model.ckpt-500000.model
06/15/2020 16:24:15 - INFO - transformers.training_args -   PyTorch: setting up devices
06/15/2020 16:24:15 - INFO - transformers.modeling_utils -   loading weights file /content/drive/My Drive/to_convert/t5_model.bin
06/15/2020 16:24:15 - WARNING - __main__ -   Process rank: -1, device: xla:1, n_gpu: 0, distributed training: False, 16-bits training: False
06/15/2020 16:24:15 - INFO - transformers.modeling_utils -   loading weights file /content/drive/My Drive/to_convert/t5_model.bin
06/15/2020 16:24:15 - INFO - __main__ -   Training/evaluation parameters TrainingArguments(output_dir='./models/tpu', overwrite_output_dir=True, do_train=True, do_eval=False, do_predict=False, evaluate_during_training=False, per_device_train_batch_size=8, per_device_eval_batch_size=8, per_gpu_train_batch_size=8, per_gpu_eval_batch_size=8, gradient_accumulation_steps=4, learning_rate=0.0001, weight_decay=0.0, adam_epsilon=1e-08, max_grad_norm=1.0, num_train_epochs=8, max_steps=-1, warmup_steps=0, logging_dir='runs/Jun15_16-24-15_8ae1f3efa3b8', logging_first_step=False, logging_steps=500, save_steps=500, save_total_limit=None, no_cuda=False, seed=42, fp16=False, fp16_opt_level='O1', local_rank=-1, tpu_num_cores=8, tpu_metrics_debug=False, dataloader_drop_last=False)
06/15/2020 16:24:15 - INFO - transformers.tokenization_utils -   Model name '/content/drive/My Drive/to_convert/model.ckpt-500000.model' not found in model shortcut name list (t5-small, t5-base, t5-large, t5-3b, t5-11b). Assuming '/content/drive/My Drive/to_convert/model.ckpt-500000.model' is a path, a model identifier, or url to a directory containing tokenizer files.
06/15/2020 16:24:15 - WARNING - transformers.tokenization_utils -   Calling T5Tokenizer.from_pretrained() with the path to a single file or url is deprecated
06/15/2020 16:24:15 - INFO - transformers.tokenization_utils -   loading file /content/drive/My Drive/to_convert/model.ckpt-500000.model
06/15/2020 16:24:15 - INFO - transformers.modeling_utils -   loading weights file /content/drive/My Drive/to_convert/t5_model.bin
06/15/2020 16:24:15 - INFO - transformers.training_args -   PyTorch: setting up devices
06/15/2020 16:24:15 - WARNING - __main__ -   Process rank: -1, device: xla:1, n_gpu: 0, distributed training: False, 16-bits training: False
06/15/2020 16:24:15 - INFO - __main__ -   Training/evaluation parameters TrainingArguments(output_dir='./models/tpu', overwrite_output_dir=True, do_train=True, do_eval=False, do_predict=False, evaluate_during_training=False, per_device_train_batch_size=8, per_device_eval_batch_size=8, per_gpu_train_batch_size=8, per_gpu_eval_batch_size=8, gradient_accumulation_steps=4, learning_rate=0.0001, weight_decay=0.0, adam_epsilon=1e-08, max_grad_norm=1.0, num_train_epochs=8, max_steps=-1, warmup_steps=0, logging_dir='runs/Jun15_16-24-15_8ae1f3efa3b8', logging_first_step=False, logging_steps=500, save_steps=500, save_total_limit=None, no_cuda=False, seed=42, fp16=False, fp16_opt_level='O1', local_rank=-1, tpu_num_cores=8, tpu_metrics_debug=False, dataloader_drop_last=False)
06/15/2020 16:24:15 - INFO - transformers.tokenization_utils -   Model name '/content/drive/My Drive/to_convert/model.ckpt-500000.model' not found in model shortcut name list (t5-small, t5-base, t5-large, t5-3b, t5-11b). Assuming '/content/drive/My Drive/to_convert/model.ckpt-500000.model' is a path, a model identifier, or url to a directory containing tokenizer files.
06/15/2020 16:24:15 - WARNING - transformers.tokenization_utils -   Calling T5Tokenizer.from_pretrained() with the path to a single file or url is deprecated
06/15/2020 16:24:15 - INFO - transformers.tokenization_utils -   loading file /content/drive/My Drive/to_convert/model.ckpt-500000.model
06/15/2020 16:24:16 - INFO - transformers.modeling_utils -   loading weights file /content/drive/My Drive/to_convert/t5_model.bin
loading training data
loading training data
loading training data
loading training data
loading training data
loading training data
loading training data
loading training data
Exception in device=TPU:2: Cannot add elem. Use .add() instead.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 231, in _start_fn
    fn(gindex, *args)
  File "<ipython-input-59-2fb0d5edf0d7>", line 194, in _mp_fn
    main()
  File "<ipython-input-59-2fb0d5edf0d7>", line 144, in main
    train_dataset  = torch.load(data_args.train_file_path)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 583, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 841, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.6/dist-packages/nlp/splits.py", line 493, in __setitem__
    raise ValueError("Cannot add elem. Use .add() instead.")
ValueError: Cannot add elem. Use .add() instead.
Exception in device=TPU:7: Cannot add elem. Use .add() instead.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 231, in _start_fn
    fn(gindex, *args)
Exception in device=TPU:5: Cannot add elem. Use .add() instead.
  File "<ipython-input-59-2fb0d5edf0d7>", line 194, in _mp_fn
    main()
Traceback (most recent call last):
Exception in device=TPU:3: Cannot add elem. Use .add() instead.
  File "<ipython-input-59-2fb0d5edf0d7>", line 144, in main
    train_dataset  = torch.load(data_args.train_file_path)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 231, in _start_fn
    fn(gindex, *args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 583, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
Traceback (most recent call last):
  File "<ipython-input-59-2fb0d5edf0d7>", line 194, in _mp_fn
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 841, in _load
    result = unpickler.load()
Exception in device=TPU:1: Cannot add elem. Use .add() instead.
Exception in device=TPU:0: Cannot add elem. Use .add() instead.
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 231, in _start_fn
    fn(gindex, *args)
  File "<ipython-input-59-2fb0d5edf0d7>", line 144, in main
    train_dataset  = torch.load(data_args.train_file_path)
Exception in device=TPU:6: Cannot add elem. Use .add() instead.
  File "/usr/local/lib/python3.6/dist-packages/nlp/splits.py", line 493, in __setitem__
    raise ValueError("Cannot add elem. Use .add() instead.")
  File "<ipython-input-59-2fb0d5edf0d7>", line 194, in _mp_fn
    main()
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 583, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
ValueError: Cannot add elem. Use .add() instead.
Traceback (most recent call last):
  File "<ipython-input-59-2fb0d5edf0d7>", line 144, in main
    train_dataset  = torch.load(data_args.train_file_path)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 231, in _start_fn
    fn(gindex, *args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 231, in _start_fn
    fn(gindex, *args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 841, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 231, in _start_fn
    fn(gindex, *args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 583, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "<ipython-input-59-2fb0d5edf0d7>", line 194, in _mp_fn
    main()
  File "<ipython-input-59-2fb0d5edf0d7>", line 194, in _mp_fn
    main()
  File "/usr/local/lib/python3.6/dist-packages/nlp/splits.py", line 493, in __setitem__
    raise ValueError("Cannot add elem. Use .add() instead.")
  File "<ipython-input-59-2fb0d5edf0d7>", line 194, in _mp_fn
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 841, in _load
    result = unpickler.load()
  File "<ipython-input-59-2fb0d5edf0d7>", line 144, in main
    train_dataset  = torch.load(data_args.train_file_path)
  File "<ipython-input-59-2fb0d5edf0d7>", line 144, in main
    train_dataset  = torch.load(data_args.train_file_path)
ValueError: Cannot add elem. Use .add() instead.
  File "<ipython-input-59-2fb0d5edf0d7>", line 144, in main
    train_dataset  = torch.load(data_args.train_file_path)
  File "/usr/local/lib/python3.6/dist-packages/nlp/splits.py", line 493, in __setitem__
    raise ValueError("Cannot add elem. Use .add() instead.")
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 583, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 583, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 583, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 841, in _load
    result = unpickler.load()
ValueError: Cannot add elem. Use .add() instead.
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 841, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 841, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.6/dist-packages/nlp/splits.py", line 493, in __setitem__
    raise ValueError("Cannot add elem. Use .add() instead.")
  File "/usr/local/lib/python3.6/dist-packages/nlp/splits.py", line 493, in __setitem__
    raise ValueError("Cannot add elem. Use .add() instead.")
  File "/usr/local/lib/python3.6/dist-packages/nlp/splits.py", line 493, in __setitem__
    raise ValueError("Cannot add elem. Use .add() instead.")
ValueError: Cannot add elem. Use .add() instead.
ValueError: Cannot add elem. Use .add() instead.
ValueError: Cannot add elem. Use .add() instead.
Exception in device=TPU:4: Cannot add elem. Use .add() instead.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 231, in _start_fn
    fn(gindex, *args)
  File "<ipython-input-59-2fb0d5edf0d7>", line 194, in _mp_fn
    main()
  File "<ipython-input-59-2fb0d5edf0d7>", line 144, in main
    train_dataset  = torch.load(data_args.train_file_path)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 583, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 841, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.6/dist-packages/nlp/splits.py", line 493, in __setitem__
    raise ValueError("Cannot add elem. Use .add() instead.")
ValueError: Cannot add elem. Use .add() instead.
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-64-73174769e3d1> in <module>()
----> 1 xmp.spawn(_mp_fn, args=(), nprocs=8, start_method='fork')

2 frames
/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py in join(self, timeout)
    111                 raise Exception(
    112                     "process %d terminated with exit code %d" %
--> 113                     (error_index, exitcode)
    114                 )
    115 

Exception: process 2 terminated with exit code 17

**Comment by jysohn23** [comment]
Hi, so I took a look at your example, and it looks like that error boils down to this line: https://github.com/huggingface/nlp/blob/5353490e9bceb25b662a2c5c407c087baca37028/src/nlp/splits.py#L493

So for some reason at loading time of the preprocessed dataset on disk it looks like the huggingface/nlp library is unexpectedly hitting that line so something like this even errors:
```
torch.save(train_dataset, 'train_data.pt')
torch.load('train_data.pt')
```

You could just use `train_data.pt` as is as a workaround.

**Comment by antoniomastro1996** [comment]
@jysohn23 Thanks a lot. This solve the problem.
