### ISSUE TITLE
Possibility to batch cpu tensor conversion?

### ISSUE THREAD

**Issue by hrbigelow** [pytorch/xla#2231]
## ❓ Questions and Help

I did a benchmark on my model and found that at each iteration, doing a forward + backward + gradient update takes 3 seconds, while printing a mere 7 scalar tensors takes 2.4 seconds.  Similarly, calling SummaryWriter::add_scalar takes 4.1 seconds.

The bottleneck seems to be the conversion of these tensors to CPU first.  So, I wondered, instead of being restricted to print only every 100 steps, to collect the losses, various histograms, accuracies, etc tensors over those 100 steps all in TPU.  Then, do a TPU to CPU conversion of all of them at one time, then print them out?

My initial thought would be to have a single tensor, and simply store the individual scalar values to separate elements of it, and then at the appropriate time (very infrequently) convert it to cpu, and print out a bunch of timestep information.  But that is finicky and not very maintainable.

I am looking through the code and this function looks promising:
`torch_xla._XLAC._xla_get_cpu_tensors(tensors)`

Is there a public interface to it?

**Comment by dlibenzi** [comment]
This is what the step closure are for.
You pass in *Tensor* arguments (not the result of `item()` calls), and then do `item()` calls from within the closure.
All step closures are scheduled at the end of the step, when `item()` calls are just device data fetches (and not graph executions).
You still need to avoid issuing them every step because they cause a sync execution of the graph (which otherwise would happen overlapped with the next step python execution).

https://github.com/pytorch/xla/blob/22bd36c45233a91f771d570bb5382e0ccb1ee125/test/test_train_mp_mnist.py#L134

https://github.com/pytorch/xla/blob/22bd36c45233a91f771d570bb5382e0ccb1ee125/torch_xla/core/xla_model.py#L494

**Comment by hrbigelow** [comment]
Ahh, thanks Davide.  That's excellent.  My apologies for not reading the documentation and examples more thoroughly - I see the answer is right there in plain sight ;/

**Comment by hrbigelow** [comment]
@dlibenzi  

Just one other question.  In the docs on `xm.add_step_closure`, it says: "adds a closure to the list of ones to be run at the *end* of the step".

But, what if you need a quantity that depends on some data before, and some data after the update?  In my case, the weights-to-updates ratio, as recommended [here](https://cs231n.github.io/neural-networks-3/).

It seems the easiest way to do that is:
```
def print_stats(uw_min, uw_max):
  xm.master_print(f'min_ratio: {uw_min.item()}, max_ratio: {uw_max.item()}')

if step % every_nth == 0:
  old_pars = [par.data.clone() for par in model.parameters()]

xm.optimizer_step(optimizer)

if step % every_nth == 0:
  iterator = zip(model.parameters(), old_pars)
  delta_norms = t.stack([t.norm(new.data - old) for new, old in iterator])
  old_norms = t.stack([par.norm() for par in old_pars])
  uw_ratio = delta_norms / old_norms
  min_uw = uw_ratio.min()
  max_uw = uw_ratio.max()
  xm.add_step_closure(print_stats, (min_uw, max_uw))
```

However, this means that there are XLA tensor calculations being done after the optimizer step runs, but before the step closure is called.  Is that okay, or would it lead to problems?

**Comment by dlibenzi** [comment]
I must be missing something. The step closure comes into play only when you want to exit graph mode to enter python scalar mode (ie, `item()`, `cpu()`, ...).
If you do normal operations on tensors, you can do whatever you can do with normal pytorch.

**Comment by hrbigelow** [comment]
Ahh, I think I understand now.  I was incorrectly thinking that `xm.add_step_closure` somehow registers the closure and calls it just after `xm.optimizer_step is called`.  indeed it is called within the next loop's `mark_step` call in the data loader.
