### ISSUE TITLE
as_strided limitation

### ISSUE THREAD

**Issue by ibeltagy** [pytorch/xla#2238]
## 🐛 Bug

One use of `as_strided` is to convert a tensor like `[10, 20, 30, 40]` into `[[10, 20, 30], [20, 30, 40]]` which is a form of overlapping sliding window. This doesn't work and I get an error that `slice_size` is greater than `input_element_count`. Is this expected, or it is a bug? if this is a known limitation, any plans to support it? or any workarounds? 

Another solution to get an overlapping sliding window is to use `unfold` but it is not lowered. I will open a different issue for `unfold`. 

## To Reproduce

Running something like the following with pytroch xla
```
x = torch.tensor([10, 20, 30, 40]) 
strided_x = x.as_strided(size=[2, 3], stride=[1, 1])
```
It throws the error:
```
*** RuntimeError: Error while lowering: f32[2,3]{1,0} aten::as_strided, size=(2, 3), stride=(1, 1), storage_offset=0
Error: torch_xla/csrc/ops/as_strided.cpp:25 : Check failed: storage_offset + slice_size <= input_element_count (6 vs. 4)
```

## Expected behavior

```
strided_x = tensor([[10, 20, 30], [20, 30, 40]])
```

## Environment

 - Reproducible on XLA backend [CPU/TPU]: TPU (didn't try CPU)
 - torch_xla version: 1.5 and nightly 

## Additional context

Trying to run Longformer on pytorch-xla. Model code is [here](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_longformer.py)

**Comment by dlibenzi** [comment]
It is expected.
We have limited support for `as_strided()` and I believe it is frowned upon even by recent pytorch guidelines.
XLA does not have real storage, and there is no explicit stride+size tricks one can play with.
In XLA `as_strided()` tricks have to be mapped to existing HLO operations with real transposes, reshapes, slices, etc...

**Comment by ibeltagy** [comment]
I guess this means this won't be fixed. I will close this issue and wait for the `unfold` lowering instead. Thanks, @dlibenzi.
