### ISSUE TITLE
SummaryWriter flush doesn't work

### ISSUE THREAD

**Issue by hrbigelow** [pytorch/xla#2243]
## To Reproduce

1. ran !python xla/test/test_train_mp_mnist.py --logdir /content/gdrive/My\ Drive/ai/log/test
2. It runs for 20 epochs and completes successfully
3. I run tensorboard on the log directory, and see lots of results, but only see 5 steps in tag: Accuracy/test.  Those values do in fact correspond to the stdout of the other Colab running in step 1 above, so I know that it is able to write to that directory.

I see https://github.com/pytorch/xla/blob/c629a00f31ee96b5c394b6d5e7d5628f234689ac/test/test_train_mp_mnist.py#L171

which calls:

https://github.com/pytorch/xla/blob/c629a00f31ee96b5c394b6d5e7d5628f234689ac/torch_xla/test/test_utils.py#L58

But it doesn't appear to be getting flushed.

## Environment

 - Reproducible on XLA backend [CPU/TPU]:
 - torch_xla version: nightly
 - Any other relevant information. In case of issues related to slow executions, re-compilations, etc.., it is useful to have the `tar.gz` report from https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#using-debug_runpy-to-collect-debug-information

**Comment by dlibenzi** [comment]
I would try first to set the logdir to a local folder, not a Drive mounted one.

**Comment by hrbigelow** [comment]
Yes, I think that would be a good idea, but is there any way to monitor that folder in real time?  I can only run one cell at a time in Colab, and as far as I know, there is no way for a second Colab to connect to the first one.

**Comment by hrbigelow** [comment]
Okay, yup, writing to /tmp flushes fine.  I had assumed I'd need a second Colab to have the tensorboard cell update automatically, but it updates just fine if running in the same Colab as the pytorch process.

**Comment by dlibenzi** [comment]
I'd just write/flush local, and upload to Drive.

**Comment by hrbigelow** [comment]
@dlibenzi just a follow up:  I tried writing SummaryWriter to My\ Drive folder and it actually does update in real time after a flush, as long as I load the tensorboard in the same Colab.  If I launch the tensorboard cell in a different Colab, that's when I get the lag.

I think maybe what is happening is that Google Colab has a separate buffer that only periodically flushes writes to the mounted Google Drive folder.
