### ISSUE TITLE
Constant Propagation in XLA + Data Movement

### ISSUE THREAD

**Issue by lmorino** [pytorch/xla#2262]
## ❓ Questions and Help
Is tensor data copied to device immediately when pytorch dispatches a copy_ instruction? If so, is constant propagation unable to run on the created XLA computation as constant propagation could potentially wipe out some redundant constants?

**Comment by dlibenzi** [comment]
We only generate constants on 0 and 1 rank0 scalars.
The benefit of enabling XLA CSE is outweighed by the risk of triggering recompilations, which is a far greater damage.
