### ISSUE TITLE
Ci

### ISSUE THREAD

**Issue by cjolivier01** [pytorch/xla#2265]
## ❓ Questions and Help
Do all draft PR’s kick off a new build/test for every commit? Is there a way to not run every time, such as a “test please” trigger?

**Comment by dlibenzi** [comment]
I remember FB has a magic keyword, but I think it works only for them. @ailzhang ?

**Comment by ailzhang** [comment]
IIUC there's no way to skip CI for new commits unless you turn it off in circleci setting. 
The pytorchbot is used to manually trigger additional CI runs, but it only works in pytorch/pytorch repo now.
