### ISSUE TITLE
CreateXrtMetricReport in json

### ISSUE THREAD

**Issue by cjolivier01** [pytorch/xla#2266]
## ❓ Questions and Help
I would like to generate a json version of this report in order to be parsed and shared with unit test validation mechanisms (I can do this).
Would you prefer CreateXrtMetricReport() were modified to produce either or a separate function for json?

**Comment by dlibenzi** [comment]
I am not sure this is a useful feature to be added to the common code base, especially at C++ level.
If a user really wants it, it can implement his own module it over the existing core API:

https://github.com/pytorch/xla/blob/master/torch_xla/debug/metrics.py

**Comment by cjolivier01** [comment]
fair enough, although I feel it's useful to make sure someone didn't change a model for instance that gets compiled every pass or more frequently than it should.

**Comment by cjolivier01** [comment]
oic I did not know about that python interface, thanks
