### ISSUE TITLE
synchronization between device and host

### ISSUE THREAD

**Issue by shz0116** [pytorch/xla#2288]
## 🚀 Feature

On CUDA, there is a synchronization torch.cuda.synchronize(), is there a similar function available in XLA ?

In tensorflow, here is the trick to use:
https://www.tensorflow.org/guide/eager#performance

def measure(x, steps):
  tf.matmul(x, x)
  start = time.time()
  for i in range(steps):
    x = tf.matmul(x, x)
  _ = x.numpy()
  end = time.time()
  return end - start

If I change this function to pytorch using torch.mm(x,x) on TPU,
what to do with "_ = x.numpy()" line in XLA ?

**Comment by dlibenzi** [comment]
`x.cpu()`

**Comment by shz0116** [comment]
Thanks a lot for the quick response.
Another related, kind of dumb question:
If the loop like:
for i in range(100):
   c = torch.mm(a, b)
c.cpu()
XLA will optimize the loop and only execute torch.mm 1 time ? or it will execute torch.mm 100 time ?
Since XLA is lazy execution, wonder whether it is too smart.

**Comment by dlibenzi** [comment]
Only one time.

**Comment by shz0116** [comment]
I also noted that the execution time for torch(a, b, out=c) and c = torch.mm(a,b) are quite different using colab test.
I think they should take the same time. Not sure it's colab problem or others.

**Comment by shz0116** [comment]
> Only one time.

This seems different from CPU and GPU. I saw increased execution time with the number of iterations there.

**Comment by dlibenzi** [comment]
You still have the python execution size of the loop.

**Comment by shz0116** [comment]
Here is the some results on my macbook, the running times has a linear relationship with the number of steps,
but the performance is ok, around 270 GF/s.

CPU Time is 0.0818641120000001 0.08187199400000011 seconds, rate 262.29770927528614 GFlops for iter 10
CPU Time is 0.7819166809999998 0.781923741 seconds, rate 274.64105965801593 GFlops for iter 100
CPU Time is 7.6065347 7.606542573 seconds, rate 282.32059801027816 GFlops for iter 1000

When I run the code using XLA with colab (google notebook) on TPU:
C results :  tensor(1.1411, device='xla:1')
CPU Time is 0.001555524000650621 0.27766257600069366 seconds, rate 4949.855160590912 GFlops for iter 10
CPU Time is 0.011150672999974631 0.2878380089996426 seconds, rate 47748.7160051092 GFlops for iter 100

You can notice the rate is about 10x from iter= 10 to iter=100. **clearly something not right**.
Following is the code I used, following link
https://colab.research.google.com/github/pytorch/xla/blob/master/contrib/colab/getting-started.ipynb
and change one code cell to:

import time
def measure_cpu(a, b, steps, m, n):
  global c
  start = time.perf_counter()
  for i in range(steps):
    c = torch.mm(a, b)
    i1 = i % m
    a[i1][0] = c[i1][0] + a[i1][0]
  end1 = time.perf_counter()
  c.to('cpu')
  end2 = time.perf_counter()
  return end1 - start, end2 - start

steps=10
m = 4096
n = 4096
k = 4096
a0 = torch.randn(m,k)
b0 = torch.randn(k,n)
c0 = torch.zeros(m, n)

dt = torch.float32
print("c0 device: ", c0.device)
a = a0.to(dtype=dt, device=dev)
b = b0.to(dtype=dt, device=dev)
c = c0.to(dtype=dt, device=dev)

print("a a0 device: ", a.device, a0.device)
measure_cpu(a, b, 100, m, n)
elapsed1, elapsed2 = measure_cpu(a, b, steps, m, n)
print("C results : ", c[0][0])
print("CPU Time is {0} {1} seconds, rate {2} GFlops for iter {3}".format(elapsed1, elapsed2, m*n*k*2*1.0/(elapsed2*1000000000/steps), steps))

**Comment by dlibenzi** [comment]
The code is a bit hard to read since it has been flattened (edit your post after mine), but AFAICT you are just measuring the pytorch python time, not the TPU (or GPU) execute time.
Which is linear of the number of iterations.
The `cpu()` call is the one that materializes the result, and that is out of the timed section.

Try this:
```Python
import torch
import torch_xla
import torch_xla.core.xla_model as xm
import torch_xla.debug.metrics as met

device = xm.xla_device()
a = torch.randn(2, 2, device=device)
for _ in range(0, 1000):
  c = torch.mm(a, a)
print(torch_xla._XLAC._get_xla_tensors_text([c]))
print(c.cpu())
print(met.metrics_report())
```

You can see that there is only one device (in this case XLA CPU) execution:
```
Metric: ExecuteTime
  TotalSamples: 1
  Accumulator: 052ms511.191us
  Percentiles: 1%=052ms511.191us; 5%=052ms511.191us; 10%=052ms511.191us; 20%=052ms511.191us; 50%=052ms511.191us; 80%=052ms511.191us; 90%=052ms511.191us; 95%=052ms511.191us; 99%=052ms511.191us
```

And the IR graph is just one MM:
```
IR {
  %0 = s64[] xla::device_data(), location=<module>@many_mm.py:7, device=CPU:0
  %1 = s64[] prim::Constant(), location=<module>@many_mm.py:7, value=214013
  %2 = s64[] aten::mul(%1, %0), location=<module>@many_mm.py:7
  %3 = s64[] prim::Constant(), location=<module>@many_mm.py:7, value=2.53101e+06
  %4 = s64[] aten::add(%3, %2), location=<module>@many_mm.py:7
  %5 = f32[] prim::Constant(), location=<module>@many_mm.py:7, value=1
  %6 = f32[2,2]{1,0} aten::expand(%5), location=<module>@many_mm.py:7, size=(2, 2)
  %7 = f32[] prim::Constant(), location=<module>@many_mm.py:7, value=0
  %8 = f32[2,2]{1,0} aten::expand(%7), location=<module>@many_mm.py:7, size=(2, 2)
  %9 = f32[2,2]{1,0} aten::normal(%8, %6, %4), location=<module>@many_mm.py:7
  %10 = f32[2,2]{1,0} aten::mm(%9, %9), location=<module>@many_mm.py:9, ROOT=0
} 
```

**Comment by dlibenzi** [comment]
Actually, in you case you are slicing and patching the source tensors, so this is no more the case you opened the thread with.

**Comment by shz0116** [comment]
Thanks for formatting and explanation. Just want to be clear, there are two timers,
one before c.cpu() and one after it. I use the second to compute the rate,
so it should include both python loop overhead and TPU execution time.

Btw, what's the % number meaning ? "1%=052ms511.191us; 5%=052ms511.191us; 10%=052ms511.191us ...." ?

**Comment by dlibenzi** [comment]
Those are percentiles.
You can try the one below if you want to have some approx. measure of MM FLOPS:

```Python
import time
import torch
import torch_xla
import torch_xla.core.xla_model as xm

SIZE = 8192
N = 10

device = xm.xla_device()
a = torch.randn(SIZE, SIZE).to(device)
b = torch.randn(SIZE, SIZE).to(device)
total_delta = 0
for i in range(0, N):
  s = time.time()
  c = torch.mm(a, b)
  c.cpu()
  delta = time.time() - s
  if i > 0:
    # Skip first sample as includes compilation time.
    total_delta += delta

FLOPS = 2 * (SIZE ** 3) * (N - 1) / total_delta
print('{:.2f} GFLOPS'.format(FLOPS * 1e-9))
```

**Comment by shz0116** [comment]
This is great. But is there a way to measure the MM flops without the c.cpu() overhead ? I mean to exclude the data transfer time from device to host ? I assume c.cpu() include both the mm execution time and data transfer time.

**Comment by dlibenzi** [comment]
```Python
torch_xla._XLAC._xla_sync_multi([c], devices=[], wait=True, sync_xla_data=True)
```

**Comment by zcain117** [comment]
@shz0116 are you running into any more problems or can I close this issue?

**Comment by shz0116** [comment]
Yes, you can close it. Thanks.

shan
________________________________

**Comment by shz0116** [comment]
> ```python
> torch_xla._XLAC._xla_sync_multi([c], devices=[], wait=True, sync_xla_data=True)
> ```

@dlibenzi Hi, I revisit the sync operation problem, wondering what's the real meaning behind the
sync op, modify your above code a little bit as following:
```python
import time
import torch
import torch_xla
import torch_xla.core.xla_model as xm

m = 4096
n = 40928
k = 1024
h = min(n,k)
N = 201

print("torch version: ", torch.__version__)

device = xm.xla_device()
a = torch.randn(m,k).to(device)
b = torch.randn(k,n).to(device)
total_delta = 0

s = time.time()
for i in range(0, N):
  c = torch.mm(a, b)
  a[:, 0:h] = torch.min(a[:, 0:h], c[:, 0:h])
# xm.mark_step()
# print(torch_xla._XLAC._get_xla_tensors_text([c]))
xm.mark_step()
torch_xla._XLAC._xla_sync_multi([c], devices=[], wait=True, sync_xla_data=True)
total_delta = time.time() - s
c.cpu()
total_time = time.time() - s
print("TIME: ", total_time, total_delta)

FLOPS = 2.0 * (m * n *k) * (N - 1) / total_delta
print('{:.2f} GFLOPS'.format(FLOPS * 1e-9))
```
The output is: (the 391 TF/s seems too high)
torch version:  1.6.0
TIME:  4.922183036804199 0.17561125755310059
391010.18 GFLOPS

It seems using torch_xla._XLAC._xla_sync_multi or mark_step could not guarantee that
the loop has been executed. 
From the IR report, we see exactly 201 aten::mm operations.
$grep "aten::mm" output.txt |wc
    201    1006   10150
$ grep "aten::mm" output.txt |tail
  %10 = f32[4096,40928]{1,0} aten::mm(%9, %4)
  %21 = f32[4096,40928]{1,0} aten::mm(%20, %4)
...

So we must depends on c.cpu() to execute the loop ?
Thanks.

**Comment by shz0116** [comment]
Do I need to open a new issue for this problem ?
