### ISSUE TITLE
ipdb type() not implemented in kaggle kernel

### ISSUE THREAD

**Issue by foobar8675** [pytorch/xla#2291]
## 🐛 Bug

When trying to view the type of tensors on TPU, I get a not implemented error.

## To Reproduce
view this kernel, and run. when hit breakpt, type `p foo2.type()`

1. run all cells in this kernel https://www.kaggle.com/matthewchung/test-tpu?scriptVersionId=37731139
2. when hit breakpt, type `p foo2.type()`

Stacktrace
```
ipdb> p foo2.type()
*** RuntimeError: Unimplemented backend XLA
```
 

## Expected behavior

should display type of tensor

## Environment

 - Reproducible on XLA backend [CPU/TPU]:
 - torch_xla version: torch-xla-1.6+5d090b1

**Comment by dlibenzi** [comment]
Does not seem we can access the Kaggle link.
Any chance of posting the full stack trace?

![image](https://user-images.githubusercontent.com/14933084/86042212-aedefa80-b9fb-11ea-8019-ee9ddd21aa61.png)

**Comment by foobar8675** [comment]
sorry about that. here is the public kernel
https://www.kaggle.com/matthewchung/test-tpu?scriptVersionId=37731139

I can do the full stack trace this evening. i had a typo in the original bug. which I just fixed.

**Comment by dlibenzi** [comment]
I got it, but does not seem the error is related to PyTorch/XLA:
```
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.
```

**Comment by foobar8675** [comment]
sorry about that, I just updated the original bug and it's only when running debugging interactively.
