### ISSUE TITLE
xla_dist will block and training hang if worker process does not write to stdout

### ISSUE THREAD

**Issue by matt-peters** [pytorch/xla#2308]
## 🐛 Bug

The `stream.readline` in this line https://github.com/pytorch/xla/blob/master/torch_xla/distributed/xla_dist.py#L135 will block the thread and process if there is nothing to read from the stream.  If that stream is never written to, it will block forever, allowing the other stream buffers that are being written to fill as they are connected to the worker processes with pipes (https://github.com/pytorch/xla/blob/master/torch_xla/distributed/xla_dist.py#L194).    When this occurs training hangs.  Since I'd wrapped all the output to stdout when training with `if xm.is_master_ordinal()` to reduce output from many workers (and is common in frameworks like pytorch-lightning), training eventually hung.  I fixed it by hacking `xla_dist` to remove the streaming functionality.

## To Reproduce

1.  Run distributed training with one worker that outputs to stdout every minute and many others that never output to stdout.

## Environment

 - Reproducible on XLA backend [CPU/TPU]:  TPU
 - torch_xla version:  nightly

**Comment by jysohn23** [comment]
Hey @matt-peters thanks for reporting. Weird that you saw nothing be streamed through to the xla_dist process as it should at least be receiving the hearbeat markers and thus not block there. I'll see I can repro your issue.

**Comment by matt-peters** [comment]
I think the heartbeat markers are sent to stderr, my guess is it was blocking on stdout.

**Comment by jysohn23** [comment]
I tried repro-ing but I don't believe its hanging just because of the logging. All that thread is doing is streaming stdout from the processes to the user. I did commented all logs from 3 workers and only kept one of them and it trained fine to end: https://gist.github.com/jysohn23/2fec16844bfc5f20af9c86110c1d2fd5

**Comment by jysohn23** [comment]
Are you sure all you were commenting out was just logging? If in the logging you end up having different cores do different tensor work, then yes, the training will hang as each of the cores graphs do not match, which would cause a problem since we need all replicas to do the same work.

**Comment by matt-peters** [comment]
I also commented out the health check portion as I didn't need it.  Here is a diff:

```
$ diff xla_dist.py /anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/distributed/xla_dist.py
19a20
> 
37,38d37
<   # XLA_EMIT_STEPLOG emits a line to stderr every time mark_step is run. It is used for heartbeating.
<   # We shortcircuit this logic.
45c44
<       #'XLA_EMIT_STEPLOG',
---
>       'XLA_EMIT_STEPLOG',
49,50c48
<   #MAX_TPU_RETRY = 50
<   MAX_TPU_RETRY = 1
---
>   MAX_TPU_RETRY = 50
195,199c193,196
<     #proc = subprocess.Popen(
<     #    cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=shell)
<     #if log:
<     #  self._stream_logs(proc, client_worker)
<     proc = subprocess.Popen(cmd, shell=shell)
---
>     proc = subprocess.Popen(
>         cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=shell)
>     if log:
>       self._stream_logs(proc, client_worker)
242,243c239,240
<         #'XLA_EMIT_STEPLOG':
<         #    1,
---
>         'XLA_EMIT_STEPLOG':
>             1,
383,384c380
<     # don't check heartbeat
<     #threading.Thread(target=_regular_health_check, daemon=True).start()
---
>     threading.Thread(target=_regular_health_check, daemon=True).start()
437,438c433
< #          proc.join(10)
<         proc.join()
---
>           proc.join(10)
```

I briefly tried to reproduce today with a minimal example but was unable.  Unfortunately the original failing case is embedded in a huge private code base.  Maybe there is something specific in there that causes it to fail, or maybe it's something in the pytorch-lightning version I'm using.  All I know is that modifying `xla_dist.py` immediately resolved it. 
 For others who may run into this, the symptoms were that the tensorboard logging stops, and on the master node all the python processes become idle (but are still alive) except for the single process running `xla_dist.py`.  Occasionally it resolves itself and training resumes (evident in tensorboard by very long gaps between logging, e.g. if a single epoch usually takes 5 minutes, it will occasionally take 30 minutes then resume as usual).  Eventually it stopped blocking, but then the heartbeating functionality would terminate training if it blocked for long enough and the workers were re-started.  In my case, it would take a few hours for this to happen.

Thanks for your attention and work trying to reproduce it.  Awesome library BTW!
