### ISSUE TITLE
Pool tensor output into one core

### ISSUE THREAD

**Issue by maximedb** [pytorch/xla#2309]
## ❓ Questions and Help

I would like to pool the output of the model between the 8 cores of the TPU before applying a dot product. 
Essentially, I would like to perform an attention dot product over all the examples of the batch (not just the examples of the specific core).
How could I do that `xmp.spawn(..., start_method="fork")` ? Is it possible ?

Thank you!
Maxime.

**Comment by taylanbil** [comment]
If I understand correctly, this could be done by doing an `xm.all_gather` across cores? see https://github.com/pytorch/xla/blob/master/torch_xla/core/xla_model.py#L419.

Also, I would do this on all cores, because it's tensor work, and it's not recommended to do tensor work on just one core.

**Comment by maximedb** [comment]
Thanks! 
I can gather the `keys` and `queries` matrices before computing the loss (which will be equivalent on each core now, I if correctly understood).
Do you recommend doing a xm.rendezvous("..") before doing the `all_gather` call ?

**Comment by taylanbil** [comment]
After you gather, tensors on every core will be equivalent, yes. I have not experimented w/ rendezvous prior to all_gather, but I suspect the result would be identical w/ or w/o.
