### ISSUE TITLE
xm.all_gather freezes

### ISSUE THREAD

**Issue by maximedb** [pytorch/xla#2311]
## ❓ Questions and Help

Question related to the use of `xm.all_gather`. 

As in #2309, I have `query` vectors which are compared against `key` vectors. To increase the number of negative examples, I am trying to pool query and key vectors from all cores with `xm.all_gather`.

This [colab](https://colab.research.google.com/drive/151bK9VOsQKvs8mTjVSF3R2Z87ThK7Wto?usp=sharing) successfully exits without `xm.all_gather`, but hangs at the first step when `xm.all_gather` is enabled.

You can enable gather operation by changing `pool_nce` to `True` in cell 10, line 13. The script will hang at the first step.

Do you know what I can do to make it work ?

Thanks!

Maxime.

**Comment by dlibenzi** [comment]
You cannot do conditional graph executions like:
```Python
if xm.is_master_ordinal():
  do_something_with_tensors()
```

All the cores must be executing the same graph, and code like the above will not do that.
I suggest you use a step closure for reporting:

https://github.com/pytorch/xla/blob/845e32d780639334954f9634a97ddce0a772cc4f/test/test_train_mp_mnist.py#L134

**Comment by maximedb** [comment]
It works ;-)

Thank you @dlibenzi and @taylanbil for your excellent work !
