### ISSUE TITLE
Difference between `tensor.to(device)` and `xm.send_cpu_data_to_device(batch, device)`

### ISSUE THREAD

**Issue by wangshangsam** [pytorch/xla#2320]
## ❓ Questions and Help

Hi,

In http://pytorch.org/xla/release/1.5/index.html, I noticed that in the single-TPU core example, a regular PyTorch DataLoader is used and `tensor.to(device)` is used to move the input data from the VM to the TPU. However, in the multi-processing example, `pl.ParallelLoader` is used where it ultimately calls `xm.send_cpu_data_to_device(batch, device)`. I'm wondering:

- what exactly the differences are between those two functions and is `pl.ParallelLoader` really necessary?
- Can I not simply use a DistributedSampler along with `tensor.to(device)` or `xm.send_cpu_data_to_device(batch, device)` which is what people have been doing for multi-process distributed training on GPU?

Thanks!
Shang

**Comment by wangshangsam** [comment]
CC @eric-zheng

**Comment by dlibenzi** [comment]
The `ParallelLoader` allows to overlap device data send time, with device execution time.
A simple `to(device)` does not.

**Comment by wangshangsam** [comment]
@dlibenzi Thanks a lot for your response! I'm wondering, to be exact, does `xm.send_cpu_data_to_device(batch, device)` allow to overlap device data send time, or is `ParallelLoader` itself in charge of that? Note that, theoretically, `xm.send_cpu_data_to_device(batch, device)` could be used directly with a normal PyTorch `DataLoader` along with `DistributedSampler` in the case of multi-process parallel training:

```python
data_loader = DataLoader(dataset, ...)
...
for batch in data_loader:
  batch = xm.send_cpu_data_to_device(batch, device)
  input, target = batch
  pred = model(input)
  loss = criterion(pred, target)
  loss.backward()
  xm.optimizer_step(optimizer, barrier=True)  # Assuming this performs all-reduce.
```
or something like that.

**Comment by dlibenzi** [comment]
It is the `ParallelLoader` that does the background send.

**Comment by wangshangsam** [comment]
In that case, what exactly is the purpose of `xm.send_cpu_data_to_device(batch, device)` then?

**Comment by dlibenzi** [comment]
The `xm.send_cpu_data_to_device()` does multiple parallel send, contrary to a sequence to `tensor.to()` calls.
But you really have to use `ParallelLoader` if you care about performance.
