### ISSUE TITLE
clip_grad_norm_ fails with latest nightly build.

### ISSUE THREAD

**Issue by nachiket273** [pytorch/xla#2321]
## 🐛 Bug
I have kaggle notebook (https://www.kaggle.com/nachiket273/pytorch-tpu-multi-core), where I'm using nightly xla build to run on tpu. I'm using clip_grad_norm_ to clip gradient in train . It started failing on latest build with below error. It's working fine on 20200630 build.

Exception in device=TPU:6: name ‘inf’ is not defined
Exception in device=TPU:3: name ‘inf’ is not defined
Traceback (most recent call last):
File “/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py”, line 235, in _mp_start_fn
_start_fn(index, pf_cfg, fn, args)
Traceback (most recent call last):
Exception in device=TPU:0: name ‘inf’ is not defined
Traceback (most recent call last):
File “/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py”, line 235, in _mp_start_fn
_start_fn(index, pf_cfg, fn, args)
File “/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py”, line 229, in _start_fn
fn(gindex, *args)
File “/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py”, line 235, in _mp_start_fn
start_fn(index, pf_cfg, fn, args)
File “/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py”, line 229, in start_fn
fn(gindex, *args)
File “”, line 130, in fit
trn_F1, trn_losses, trn_time = train(j, model, para_loader.per_device_loader(device), optimizer, criterion)
File “”, line 130, in fit
trn_F1, trn_losses, trn_time = train(j, model, para_loader.per_device_loader(device), optimizer, criterion)
File “”, line 94, in train
torch.nn.utils.clip_grad_norm(model.parameters(), 0.5)
File “/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py”, line 229, in start_fn
fn(gindex, *args)
File “”, line 94, in train
torch.nn.utils.clip_grad_norm(model.parameters(), 0.5)
File "/opt/conda/lib/python3.7/site-packages/torch_xla/patched_functions.py", line 26, in clip_grad_norm
if norm_type == inf:
File “”, line 130, in fit
trn_F1, trn_losses, trn_time = train(j, model, para_loader.per_device_loader(device), optimizer, criterion)
NameError: name ‘inf’ is not defined
File "/opt/conda/lib/python3.7/site-packages/torch_xla/patched_functions.py", line 26, in clip_grad_norm
if norm_type == inf:
NameError: name ‘inf’ is not defined
File “”, line 94, in train
torch.nn.utils.clip_grad_norm(model.parameters(), 0.5)
File "/opt/conda/lib/python3.7/site-packages/torch_xla/patched_functions.py", line 26, in clip_grad_norm
if norm_type == inf:
NameError: name ‘inf’ is not defined
Exception Traceback (most recent call last)
in
----> 1 xmp.spawn(fit, args=(flags,), nprocs=8, start_method=‘fork’)

/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py in spawn(fn, args, nprocs, join, daemon, start_method)
298 join=join,
299 daemon=daemon,
–> 300 start_method=start_method)
301
302

/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py in start_processes(fn, args, nprocs, join, daemon, start_method)
156
157 # Loop on join until it returns True or raises an exception.
–> 158 while not context.join():
159 pass
160

/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py in join(self, timeout)
111 raise Exception(
112 “process %d terminated with exit code %d” %
–> 113 (error_index, exitcode)
114 )
115

Exception: process 3 terminated with exit code 17

Here's standard training loop:

    for i, (ip, tgt) in enumerate(loader):
            optimizer.zero_grad()                                
            output = torch.sigmoid(model(ip))
            loss = criterion(output, tgt)
            running_loss += loss.item()
            
            # compute gradient and do SGD step
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 0.5)
            xm.optimizer_step(optimizer)

            # Append outputs
            running_F1 += F_score(output, tgt)

**Comment by dlibenzi** [comment]
Yeah, sorry, we found out yesterday. Should be fixed on nightly though.

**Comment by dlibenzi** [comment]
Can you check if your `torch_xla/_patched_functions.py` has this change?

https://github.com/pytorch/xla/pull/2316/files

**Comment by nachiket273** [comment]
no, it doesn't , as I was running it yesterday afternoon IST. I see it merged, i'll use next nightly build. Thanks.

**Comment by Mistobaan** [comment]
I built the docker image today and just got this same hiccup

**Comment by dlibenzi** [comment]
Maybe the build chain failed and the Docker was not refreshed.
I tried locally and there are no more import errors:
```Python
import torch
from torch import nn
import torch_xla
import torch_xla.core.xla_model as xm

device = xm.xla_device()
data = torch.rand(3, 3).to(device)

nn.utils.clip_grad_norm_(data, 1.0)
print(data.cpu())
```

```
tensor([[0.6288, 0.9750, 0.4063],
        [0.6686, 0.6988, 0.7198],
        [0.1389, 0.8265, 0.8210]])
```
