### ISSUE TITLE
First pass and second-pass through training loop compiles

### ISSUE THREAD

**Issue by cjolivier01** [pytorch/xla#2327]
## ❓ Questions and Help
It has been my experience that the first pass through the model and the second pass will generate different hashes and thus, cause a recompile. After that, the graph tends to coalesce (simple fc graph).  I have noticed similar behavior on just about every model I have run, although admittedly, that's not a large number of models.  This would be between the second and third mark_step (the first being upon the first parallel loader iteration which smartly syncs any dangling tensors just before entering the training loop).

The tensors being requested for sync as well as the params for that program from GetPostOrder seem the same characteristics for both passes (count, shape, etc).

My question is, is this expected? Is it well understood why this happens?  Is there a way to make it not compile twice?

**Comment by cjolivier01** [comment]
My suspicion is (I am intending to trace through it more closely sometime soon) it's because leading up to the first pass, tensors are created in some ad-hoc order by PyTorch, which differs slightly from the order in which new tensors replace any tensors which go out of scope when running the training loop on subsequent passes and thus the hash value is computed in slightly different order?  tbh I haven't inspected the two generated graphs for differences, but I certainly can if necessary.

**Comment by dlibenzi** [comment]
It is likely related to the optimizer doing stuff at the first step.

**Comment by cjolivier01** [comment]
Thank you, I will look into that.
