### ISSUE TITLE
What is tracker.rate() and tracker.global_rate()

### ISSUE THREAD

**Issue by sharkdeng** [pytorch/xla#2328]
## ❓ Questions and Help
Hello, I am still trying pytorch tpu. In the pytorch tpu mnist colab tutorial. It uses tracker.rate() and tracker.global_rate(). What are these two things? Thank you!

**Comment by dlibenzi** [comment]
One is the running average, the other (the global) the rate compared to the start of time:

https://github.com/pytorch/xla/blob/8504a1302cdc2baf30fde2d4e178cc8902ac657e/torch_xla/core/xla_model.py#L334

**Comment by sharkdeng** [comment]
Thank you for the clarification.
