### ISSUE TITLE
Cudnn error while building the dockerfile with cuda enabled. 

### ISSUE THREAD

**Issue by gautamkmr** [pytorch/xla#2332]
## 🐛 Bug

I tried to use [Dockerfile](https://github.com/pytorch/xla/blob/master/docker/Dockerfile) and changed it with `cuda=1` ([1](https://github.com/pytorch/xla/blob/master/docker/Dockerfile#L10), [2](https://github.com/pytorch/xla/blob/master/docker/Dockerfile#L18) and got error related to missing symbol.

Dockerfile installs cuda-10.2 and I have cudnn-7.6.5. 

## To Reproduce

Change ([1](https://github.com/pytorch/xla/blob/master/docker/Dockerfile#L10), [2](https://github.com/pytorch/xla/blob/master/docker/Dockerfile#L18) to `cuda=1` in [Dockerfile](https://github.com/pytorch/xla/blob/master/docker/Dockerfile) and try to build it.  

## Environment

 - Reproducible on XLA backend [CPU/TPU]: gpu
 - torch_xla version:  master

## Additional context
Error stack 

 warning generated.
[ 87%] Linking CXX shared library ../lib/libtorch_cuda.so
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../x86_64-linux-gnu/crti.o: In function `_init':
(.init+0x7): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against undefined symbol `__gmon_start__'
CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cudnn/AffineGridGenerator.cpp.o: In function `at::native::cudnn_affine_grid_generator_forward(at::Tensor const&, long, long, long, long)':
AffineGridGenerator.cpp:(.text+0x58): relocation truncated to fit: R_X86_64_GOTPCREL against symbol `c10::UndefinedTensorImpl::_singleton' defined in .bss section in ../lib/libc10.so
AffineGridGenerator.cpp:(.text+0xf1): relocation truncated to fit: R_X86_64_GOTPCREL against symbol `c10::UndefinedTensorImpl::_singleton' defined in .bss section in ../lib/libc10.so
AffineGridGenerator.cpp:(.text+0x130): relocation truncated to fit: R_X86_64_GOTPCREL against symbol `c10::UndefinedTensorImpl::_singleton' defined in .bss section in ../lib/libc10.so
AffineGridGenerator.cpp:(.text+0x1f2): relocation truncated to fit: R_X86_64_GOTPCREL against symbol `c10::UndefinedTensorImpl::_singleton' defined in .bss section in ../lib/libc10.so
AffineGridGenerator.cpp:(.text+0x231): relocation truncated to fit: R_X86_64_GOTPCREL against symbol `c10::UndefinedTensorImpl::_singleton' defined in .bss section in ../lib/libc10.so
AffineGridGenerator.cpp:(.text+0x36e): relocation truncated to fit: R_X86_64_GOTPCREL against symbol `c10::UndefinedTensorImpl::_singleton' defined in .bss section in ../lib/libc10.so
AffineGridGenerator.cpp:(.text+0x71d): relocation truncated to fit: R_X86_64_PC32 against symbol `vtable for c10::CuDNNError' defined in .data.rel.ro._ZTVN3c1010CuDNNErrorE[_ZTVN3c1010CuDNNErrorE] section in CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cudnn/AffineGridGenerator.cpp.o
AffineGridGenerator.cpp:(.text+0x729): relocation truncated to fit: R_X86_64_PC32 against symbol `typeinfo for c10::CuDNNError' defined in .data.rel.ro._ZTIN3c1010CuDNNErrorE[_ZTIN3c1010CuDNNErrorE] section in CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cudnn/AffineGridGenerator.cpp.o
AffineGridGenerator.cpp:(.text+0x7da): relocation truncated to fit: R_X86_64_PC32 against symbol `vtable for c10::CuDNNError' defined in .data.rel.ro._ZTVN3c1010CuDNNErrorE[_ZTVN3c1010CuDNNErrorE] section in CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cudnn/AffineGridGenerator.cpp.o
AffineGridGenerator.cpp:(.text+0x7e6): additional relocation overflows omitted from the output
../lib/libtorch_cuda.so: PC-relative offset overflow in GOT PLT entry for `_ZN2at6native27unrolled_elementwise_kernelI18__nv_hdl_wrapper_tILb0ELb1E11__nv_dl_tagIPFvRNS_14TensorIteratorEEXadL_ZNS0_18lgamma_kernel_cudaES5_EELj1EEFddEJEENS_6detail5ArrayIPcLi2EEE23TrivialOffsetCalculatorILi1EjESG_NS0_6memory15LoadWithoutCastENSH_16StoreWithoutCastEEEviT_T0_T1_T2_T3_T4_'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libtorch_cuda.so] Error 1
caffe2/CMakeFiles/torch_cuda.dir/build.make:5351: recipe for target 'lib/libtorch_cuda.so' failed
make[1]: *** [caffe2/CMakeFiles/torch_cuda.dir/all] Error 2
CMakeFiles/Makefile2:8936: recipe for target 'caffe2/CMakeFiles/torch_cuda.dir/all' failed
make: *** [all] Error 2
Makefile:140: recipe for target 'all' failed
-- Building version 1.7.0a0+04004bf
cmake -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/pytorch/torch -DCMAKE_PREFIX_PATH=/../ -DNUMPY_INCLUDE_DIR=/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/numpy/core/include -DPYTHON_EXECUTABLE=/root/anaconda3/envs/pytorch/bin/python -DPYTHON_INCLUDE_DIR=/root/anaconda3/envs/pytorch/include/python3.6m -DPYTHON_LIBRARY=/root/anaconda3/envs/pytorch/lib/libpython3.6m.so.1.0 -DTORCH_BUILD_VERSION=1.7.0a0+04004bf -DUSE_CUDA=1 -DUSE_NUMPY=True /pytorch
cmake --build . --target install --config Release -- -j 96
Traceback (most recent call last):
  File "setup.py", line 734, in <module>
    build_deps()
  File "setup.py", line 318, in build_deps
    cmake=cmake)
  File "/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/pytorch/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '96']' returned non-zero exit status 2.
The command '/bin/sh -c cd /pytorch && bash xla/scripts/build_torch_wheels.sh ${python_version} ${release_version}' returned a non-zero code: 1

**Comment by dlibenzi** [comment]
That usually means %rip based jumps cannot offset over 2GB relative targets, which seems strange having libraries that size.
Unless the build is trying to stuff the clown car with prebuilt CUDA kernels with many CUDA compute versions.
Using `-mcmodel=large` might solve that, but it hits performance.
I'd look at why libraries gets so big.

**Comment by gautamkmr** [comment]
Thank you. Are you building these container periodically if so would you please point me to it ?

**Comment by dlibenzi** [comment]
We do build the containers ... @jysohn23 where are those in dockerio?

**Comment by jysohn23** [comment]
They're in GCR under `gcr.io/tpu-pytorch/xla`. For CUDA enabled ones `gcr.io/tpu-pytorch/xla:nightly_3.6_cuda` or something like `gcr.io/tpu-pytorch/xla:nightly_3.6_cuda_YYYYMMDD`.

**Comment by gautamkmr** [comment]
Thanks @dlibenzi  and @jysohn23  though name of repo is a bit misleading (has tpu) for cuda container :) 
`gcr.io/tpu-pytorch/xla:nightly_3.6_cuda`

**Comment by gautamkmr** [comment]
@jysohn23  so I used that docker image and tried to run [mnist](https://github.com/pytorch/xla/blob/master/test/test_train_mnist.py) with following setup. 
```
(pytorch) root@15ce86b36df0:/xla/test# export GPU_NUM_DEVICES=1 
(pytorch) root@15ce86b36df0:/xla/test# export XLA_FLAGS='--xla_gpu_cuda_data_dir=/usr/local/cuda/'
```

However test fails 

```
(pytorch) root@15ce86b36df0:/xla/test# python test_train_mnist.py 
2020-07-10 19:36:57.764088: W     129 tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-07-10 19:36:57.764118: W     129 tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
E
======================================================================
ERROR: test_accurracy (__main__.TrainMnist)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_train_mnist.py", line 186, in test_accurracy
    self.assertGreaterEqual(train_mnist(), FLAGS.target_accuracy)
  File "test_train_mnist.py", line 116, in train_mnist
    model_parallel = dp.DataParallel(MNIST, device_ids=devices)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/data_parallel.py", line 57, in __init__
    device_module = deepcopy(module).to(device=torch.device(device))
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 611, in to
    return self._apply(convert)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 358, in _apply
    module._apply(fn)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 380, in _apply
    param_applied = fn(param)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 609, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:381 : Check failed: session->session()->Run( session_work->feed_inputs, session_work->outputs_handles, &outputs) == ::tensorflow::Status::OK() (Invalid argument: Cannot assign a device for operation XRTAllocateFromTensor: {{node XRTAllocateFromTensor}} was explicitly assigned to /job:localservice/replica:0/task:0/device:XLA_GPU:0 but available devices are [ /job:localservice/replica:0/task:0/device:CPU:0, /job:localservice/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[XRTAllocateFromTensor]] vs. OK)
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	
	
	
	
	
	clone
*** End stack trace ***


----------------------------------------------------------------------
Ran 1 test in 0.098s

FAILED (errors=1)

```

**Comment by jysohn23** [comment]
You shouldn't need to export those `XLA_FLAGS` if using our image:

This is what I just ran:
```
jysohn@gpus:~$ docker run -e GPU_NUM_DEVICES=4 --gpus all --network=host --shm-size 16G gcr.io/tpu-pytorch/xla:nightly_3.6_cuda bash -c 'nvidia-smi && python /pytorch/xla/test/test_train_mp_imagenet.py --fake_data'
/usr/local/bin/docker-entrypoint.sh: line 11: conda: command not found
Fri Jul 10 19:44:41 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P0    56W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:00:05.0 Off |                    0 |
| N/A   34C    P0    45W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:00:06.0 Off |                    0 |
| N/A   36C    P0    55W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:00:07.0 Off |                    0 |
| N/A   39C    P0    48W / 300W |      0MiB / 16130MiB |      4%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
==> Preparing data..
| Training Device=xla:0/1 Epoch=1 Step=0 Loss=6.89059 Rate=4.72 GlobalRate=4.72 Time=19:45:25
==> Preparing data..
Epoch 1 train begin 19:44:58
| Training Device=xla:0/0 Epoch=1 Step=0 Loss=6.89059 Rate=4.72 GlobalRate=4.72 Time=19:45:25
==> Preparing data..
| Training Device=xla:0/3 Epoch=1 Step=0 Loss=6.89059 Rate=4.72 GlobalRate=4.72 Time=19:45:25
==> Preparing data..
| Training Device=xla:0/2 Epoch=1 Step=0 Loss=6.89059 Rate=4.72 GlobalRate=4.72 Time=19:45:25
```

**Comment by gautamkmr** [comment]
Thank you @jysohn23  I think we should add some documentation in [README.md](https://github.com/pytorch/xla/blob/master/README.md) that will help us to get started .
