### ISSUE TITLE
Backwards pass and grad functions

### ISSUE THREAD

**Issue by lmorino** [pytorch/xla#2337]
## ❓ Questions and Help
Hello,
I was wondering how gradients are computed for functions that don't have any backwards implementations. For e.g. the grad_fn associated with add is AddBackward0. I don't see how calling backward with the tensor associated with at::Tensor created from XLATensor add will be linked to AddBackward0

**Comment by ailzhang** [comment]
It's handled by pytorch autograd before dispatching to XLA backend. 
Btw it's on our todo list to add more documentation/guideline of how this works.

**Comment by lmorino** [comment]
Thanks that would be super helpful :)

**Comment by lmorino** [comment]
Sorry one more question, PyTorch Functions have an associated Autograd context that specifies tensors that should be saved. Is that idea used in PyTorch/XLA to retain tensors?

**Comment by ailzhang** [comment]
Yes PyTorch/XLA uses pytorch autograd layer exactly the same as normal CPU/GPU backend.

**Comment by lmorino** [comment]
How would PyTorch/XLA know which tensors are saved by the PyTorch computation graph if the only thing being dispatched is the operation + inputs

**Comment by ailzhang** [comment]
Those tensors are saved by autograd, xla backend is a layer below autograd which is agnostic to saved saved tensors. It doesn't need to know this information ;)

**Comment by lmorino** [comment]
Ah I see, thanks!
