### ISSUE TITLE
self.loss.backward() failing at CPP level when trying to train a fastai2 model

### ISSUE THREAD

**Issue by tyoc213** [pytorch/xla#2340]
## 🐛 Bug

We have a problem when a call to `self.loss.backward()` that throws a `RuntimeError: vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)`.

If you see in the prints, the `self.loss` has a value and is on `xla:1`, the captured error and printed just to see if we got anything more than the normal output that is after that print

```
******************** self is <fastai2.learner.Learner object at 0x7fa74c767358> i is 0
begin_batch
shapeeee torch.Size([64, 3, 28, 28])
after_pred
after_loss
******************** self.loss is 0.6995548009872437
******************** self.loss.device = xla:1
******************** will calculate gradient for loss <class 'torch.Tensor'> torch.Size([])
******************** did fail
vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
  File "<ipython-input-135-4b36e6c15e89>", line 17, in one_batch
    self.loss.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 184, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 123, in backward
    allow_unreachable=True)  # allow_unreachable flag
after_batch
after_train
after_epoch
after_fit
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-135-4b36e6c15e89> in <module>()
     34 print(tpu_learner._split)
     35 
---> 36 tpu_learner.fit(1)

/usr/local/lib/python3.6/dist-packages/fastcore/utils.py in _f(*args, **kwargs)
    429         init_args.update(log)
    430         setattr(inst, 'init_args', init_args)
--> 431         return inst if to_return else f(*args, **kwargs)
    432     return _f
    433 

/usr/local/lib/python3.6/dist-packages/fastai2/learner.py in fit(self, n_epoch, lr, wd, cbs, reset_opt)
    201                     try:
    202                         self.epoch=epoch;          self('begin_epoch')
--> 203                         self._do_epoch_train()
    204                         self._do_epoch_validate()
    205                     except CancelEpochException:   self('after_cancel_epoch')

/usr/local/lib/python3.6/dist-packages/fastai2/learner.py in _do_epoch_train(self)
    173         try:
    174             self.dl = self.dls.train;                        self('begin_train')
--> 175             self.all_batches()
    176         except CancelTrainException:                         self('after_cancel_train')
    177         finally:                                             self('after_train')

/usr/local/lib/python3.6/dist-packages/fastai2/learner.py in all_batches(self)
    151     def all_batches(self):
    152         self.n_iter = len(self.dl)
--> 153         for o in enumerate(self.dl): self.one_batch(*o)
    154 
    155     def one_batch(self, i, b):

<ipython-input-135-4b36e6c15e89> in one_batch(self, i, b)
     23               traceback.print_tb(tb) #print_exception(e)
     24 
---> 25             self.loss.backward();                            self('after_backward')
     26             print(f"******************** PASSED")
     27             self.opt.step();                                 self('after_step')

/usr/local/lib/python3.6/dist-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph)
    182                 products. Defaults to ``False``.
    183         """
--> 184         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    185 
    186     def register_hook(self, hook):

/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
    121     Variable._execution_engine.run_backward(
    122         tensors, grad_tensors, retain_graph, create_graph,
--> 123         allow_unreachable=True)  # allow_unreachable flag
    124 
    125 

RuntimeError: vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
```

## To Reproduce

https://colab.research.google.com/github/tyoc213/fastai_xla_extensions/blob/explorations1/explore_nbs/Basic_lenet_exploration.ipynb#scrollTo=sdeNARoitRPW

There we patched the same function on the library but with some extra prints (dont know much how to debug on colab TPU, so this is it).

## Expected behavior

That `after_fit` doesnt crash while calculating the loss.

## Environment

COLAB TPU

## Additional context

@butchland and I are trying to run fastai2 on TPU, he wrapped the loss function to run on tpu and then we checked trained networks like resnet, [they seem to do fine](https://github.com/butchland/fastai_nb_explorations/blob/master/fastai_scratch_with_tpu_mnist_4_experiment4.ipynb), but when trying to train them more we are finding some things that doesnt work on fastai2 specially when we try to train from scratch and I got to "trace" it to that call to `backward()`.

**Comment by dlibenzi** [comment]
Can you try using `nightly` here?

![image](https://user-images.githubusercontent.com/14933084/87160422-caf25f80-c277-11ea-8b45-3d1b1ab544cb.png)

**Comment by tyoc213** [comment]
Will try, but https://github.com/butchland/fastai_xla_extensions/blob/master/explore_nbs/Lenet_GPU_Baseline.ipynb found that changing the runtime to GPU (thing I didnt test) causes instead this error message:

`RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.`

**Comment by tyoc213** [comment]
I think the problem is not the error in itself, but that is not the same as running on GPU.

We have passed this point, so I will close this, thanks.

**Comment by alatas** [comment]
> Can you try using `nightly` here?
> 
> ![image](https://user-images.githubusercontent.com/14933084/87160422-caf25f80-c277-11ea-8b45-3d1b1ab544cb.png)

I had the same issue (`RuntimeError: vector::_M_range_check`) in collab and solved it with the nightly build. Thanks,

**Comment by tyoc213** [comment]
remembering this from a long time a go... just for the note, I think I was calling two times `backward` so the second one failed because it didn't have the `preserve_flag` or something related
