### ISSUE TITLE
Need help with xla_device() name

### ISSUE THREAD

**Issue by rohitgr7** [pytorch/xla#2345]
## ❓ Questions and Help
When training on 8 cores using multiprocessing, why `xm.xla_device()` always prints either `xla:0` or `xla:1` in `_mp_fn`? Shouldn't it be `xla:0`, `xla:1`, `xla:2`, `xla:3`... `xla:7`?

Thanks

**Comment by dlibenzi** [comment]
One should not make any assumptions on the XLA device ordinals, and neither try to build them manually by appending ordinals to `xla:`.
In MP, we spawn N processes each seeing a single device. In each process there is only one device.

**Comment by rohitgr7** [comment]
Is there any way to get the device(core of tpu) the current proces is running on within the process function iteself??

**Comment by dlibenzi** [comment]
`xm.xla_device()`

**Comment by rohitgr7** [comment]
> In MP, we spawn N processes each seeing a single device

Within that process which device will it be seeing since it's always giving either `xla:0` or `xla:1`? I need something like `xla:2`, `xla:3` or something else that can tell me the device(or core) name(or id) being used. Any such option there in xla? Something similar to the way I can get the GPU device name(id) in DDP process.

**Comment by dlibenzi** [comment]
Why you need it?
It's not that from process Pi handling device Di, you can use device Dj.

**Comment by taylanbil** [comment]
Not sure if this helps l, but you could use `xm.get_ordinal()` to
understand which process the prints are coming from, if that is what you
are after.

https://github.com/pytorch/xla/blob/master/torch_xla/core/xla_model.py#L161
to get information about what ordinal th

**Comment by rohitgr7** [comment]
Yeah! I know I can't use device Dj in process Pi neither I want to. I just started looking at xla source code and experimenting a little. Just curious why it is always `xla:0` or `xla:1`? Why not just `xla:0` for each process or seperate `xla:core_idx` for each process.

**Comment by rohitgr7** [comment]
Thanks, @taylanbil.
