### ISSUE TITLE
Fairseq's multihead attention crashes.

### ISSUE THREAD

**Issue by taylanbil** [pytorch/xla#2369]
## 🐛 Bug

Fairseq's multihead attention fails with:
```
/tpu-examples/deps/fairseq/fairseq/modules/multihead_attention.py:174: UserWarning: Output 0 of SplitBackward is a view and is being modified inplace. This view is an output of a function that returns multiple views. Inplace operators on such views are being deprecated and will be forbidden starting from version 1.8. Consider using `unsafe_` version of the function that produced this view or don't modify this view inplace. (Triggered internally at  /pytorch/torch/csrc/autograd/variable.cpp:480.)
Exception in device=TPU:0: one of the variables needed for gradient computation has been modified by an inplace operation: [XLAFloatType [64, 128, 3072]], which is output 0 of AddBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```
line 174 of the relevant file is: q *= self.scaling

## To Reproduce

1. follow tutorial @ https://cloud.google.com/tpu/docs/tutorials/transformer-pytorch

## Expected behavior

expected to train fine.

## Environment

 - Reproducible on XLA backend [CPU/TPU]: TPU
 - torch_xla version: nightly, starting today. Was running fine yesterday on the test grid.

## Additional context
N/A

**Comment by JackCaoG** [comment]
Yeah, the problem is in [this line](https://github.com/pytorch/fairseq/blob/master/fairseq/modules/multihead_attention.py#L212) , after changing it to `q = q * self. scaling ` test doesn't crashes. I searched a bit about this issue and most post seems to suggest modify the in place operation to solve the problem. This [doc](https://pytorch.org/docs/stable/notes/autograd.html#in-place-operations-with-autograd) also suggest not to use in-place operation with autograd. 

I don't think this is a xla specific problem, @ailzhang do you have any insights? @taylanbil Does Fairseq has CI running the similar test with GPU? I would be curious if their test hit the same line and pass. Trying to make a small repo but it is a bit tricky..

**Comment by JackCaoG** [comment]
A repo could be something like https://github.com/pytorch/pytorch/issues/15803#issuecomment-454030272 but like I said this also fails pytorch native.

**Comment by taylanbil** [comment]
Our fairseq fork is currently based on an older upstream commit, so it s
likely that this problem only occurs for us. I will send a pr replacing
that line tmrw, and also pick it to 1.6 as well.

**Comment by ailzhang** [comment]
Hmmm the error message indicates this is a real error (that we have disabled modifying inplace update to a view generated by splitbackward a few months ago I think). 
I'd expect it to fail on CPU/GPU as well tho, if it doesn't please let me know, otherwise we're good to close this issue ;)

**Comment by taylanbil** [comment]
Yeah this happens on cpu as well.

```
In [1]: import torch

In [2]: import torch.nn as nn

In [3]: inp = torch.ones(100,10)

In [4]: layer=nn.Linear(10, 1)

In [5]: out = layer(inp)

In [6]: out *= 6

In [7]: out.backward()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-617965056ac0> in <module>
----> 1 out.backward()

/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph)
    183                 products. Defaults to ``False``.
    184         """
--> 185         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    186
    187     def register_hook(self, hook):

/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
    119         grad_tensors = list(grad_tensors)
    120
--> 121     grad_tensors = _make_grads(tensors, grad_tensors)
    122     if retain_graph is None:
    123         retain_graph = create_graph

/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/autograd/__init__.py in _make_grads(outputs, grads)
     45             if out.requires_grad:
     46                 if out.numel() != 1:
---> 47                     raise RuntimeError("grad can be implicitly created only for scalar outputs")
     48                 new_grads.append(torch.ones_like(out, memory_format=torch.preserve_format))
     49             else:

RuntimeError: grad can be implicitly created only for scalar outputs
```
