### ISSUE TITLE
[PT_BREAK] Default device xla:0 is not a TPU device

### ISSUE THREAD

**Issue by quickwritereader** [pytorch/xla#2375]
hi, could you check what is wrong 
[#41541](https://github.com/pytorch/pytorch/pull/41541)
thanks

**Comment by JackCaoG** [comment]
hmm.. weird, I can't see how your change can result in this error. Let me rerun your `pytorch_xla_linux_bionic_py3_6_clang9_test` and see if it fail at the same place. @ailzhang any ideas?

**Comment by JackCaoG** [comment]
Oh, I do not have the permission to rerun the job. @quickwritereader could you rerun the job? Thanks!

**Comment by quickwritereader** [comment]
pushed new commit. it should run again.

**Comment by quickwritereader** [comment]
thanks, it seems it's solved

**Comment by JackCaoG** [comment]
> thanks, it seems it's solved

Nice, thanks for reporting! I will close this issue for now.
