### ISSUE TITLE
Odd (compilation?) error

### ISSUE THREAD

**Issue by tmabraham** [pytorch/xla#2376]
I was running some PyTorch XLA code (trying to add TPU support to fastai2) and obtained the attached error. What could this be due to? 
[odd_error.txt](https://github.com/pytorch/xla/files/4980198/odd_error.txt)

**Comment by jysohn23** [comment]
Hi,

Looks like the real error is here:
```
  (0) Invalid argument: Computation requires more parameters (787) than supported (limit 236).
	 [[{{node XRTCompile}}]]
  (1) Invalid argument: Computation requires more parameters (787) than supported (limit 236).
	 [[{{node XRTCompile}}]]
	 [[XRTCompile_G3]]
```

The 236 limit should be higher iirc (though not entirely sure if 787 within limits). I don't know how you're updating your TPU runtime but can you follow what our example colab notebooks have? Ex. https://github.com/pytorch/xla/issues/1963#issuecomment-619460620

**Comment by tmabraham** [comment]
@jysohn23 Sorry, I forgot to put in the information about my environment. This was done with a GCP TPU VM. So everything should be set up automatically in the `torch-xla-nightly` environment, no? I had run `. ./scripts/update_nightly_torch_wheels.sh` because I had accidentally downgraded the PyTorch version and it was not working, but I don't think that would affect this, would it?

So if I do have to run the snippet in the linked issue, do I run it inside the conda environment?

**Comment by jysohn23** [comment]
What TPU did you create? `pytorch-nightly` as the TPU software version?

**Comment by tmabraham** [comment]
Yes... Just tested this again right now with same error using torch-xla-nightly conda environment on an n1-standard-16 with a v3-8 with pytorch-nightly...

**Comment by tmabraham** [comment]
@jysohn23 Let me know if you need more information about the bug from me...

**Comment by jysohn23** [comment]
Hmm I believe that "(limit 236)" seems like you're somehow using our old runtime. Do you have the TPU name and zone of the TPU you're currently using? I can try take a look on verifying whether the runtime is the newer one.

Also, however 787 parameters actually looks like it goes over our hard current limit, which is an issue @taylanbil had also reproduced. First let's try to find our why the limit is so low.

**Comment by tmabraham** [comment]
@jysohn23 Here is the information:
![image](https://user-images.githubusercontent.com/37097934/88614029-b2d65a80-d043-11ea-90ed-b95f9f505db4.png)

**Comment by jysohn23** [comment]
I'll take a look once I get back to my laptop, but did you run any `curl -X
POST http://TPU_IP:8475/requestversion/...` command from the GCE VM? If so
what was the exact command you ran?

**Comment by tmabraham** [comment]
@jysohn23 I haven't run any command of that sort. Is that a required command? I have not heard of it being required for PyTorch XLA before...

**Comment by jysohn23** [comment]
No you shouldn't. In case you did the runtime could have been swapped to an incorrect one which is why I was asking. Looking at logs.

**Comment by jysohn23** [comment]
Ah it looks like your TPU was created a very very long time ago. Could you try recreating your TPU? That should at least bump the limit of parameters higher past 236.

**Comment by tmabraham** [comment]
@jysohn23 Yes, I created a new TPU node and tried with that. The error is gone. So I think this is solved. Is there a reason this had come from the old TPU node?

**Comment by jysohn23** [comment]
Yeah so we updated our runtime entirely on the TPU side around February and your TPU seems to have been created back in January.

**Comment by tmabraham** [comment]
@jysohn23 Thank you for the clarification!
