### ISSUE TITLE
Overriding leaf vs non-leaf ops

### ISSUE THREAD

**Issue by lmorino** [pytorch/xla#2378]
## ❓ Questions and Help
Hello, 

I was wondering why leaf ops are overrideable whereas there are only a select few non-leaf ops. 

Thanks

**Comment by JackCaoG** [comment]
The main reason is that even we write XLA lowering for non-leaf ops, they are NOT used when calling from pytorch python & cpp frontend. Non-leaf ops will be break into couple leaf ops and the lowering of those leaf ops will be called. I don't think existing lowering for non-leaf ops is being used right now.

**Comment by lmorino** [comment]
that makes sense, thanks!

**Comment by taylanbil** [comment]
assuming this was reopened inadvertently, closing again.
