### ISSUE TITLE
Training an LM with adaptive inputs (from fairseq) with TPUs seems pretty slow

### ISSUE THREAD

**Issue by jiaaoc** [pytorch/xla#2380]
#### I am running codes for training an LM with adaptive inputs on one TPU V3-8

The memory usage on TPU kept growing (becoming larger than 128GB) and the training became pretty slow. 

Also I checked the utilization of TPU Matrix Units, it was 0.000%.

Do you have any ideas on how to improve the utilization/efficiency when training adaptive inputs LM with TPUs?

#### Code

```
python /usr/share/torch-xla-1.5/tpu-examples/deps/fairseq/train.py data-bin/wikitext-103 \
    --task language_modeling \
    --save-dir checkpoints/transformer_wikitext-103 \
    --arch transformer_lm_wiki103 \
    --max-update 286000 --max-lr 1.0 --t-mult 2 --lr-period-updates 270000 --lr-scheduler cosine --lr-shrink 0.75 \
    --warmup-updates 16000 --warmup-init-lr 1e-07 --min-lr 1e-09  --lr 0.0001 --clip-norm 0.1 \
    --update-freq 10 --tokens-per-sample 512 \
    --sample-break-mode none --skip-invalid-size-inputs-valid-test --ddp-backend=no_c10d --no-epoch-checkpoints \
    --optimizer nag --criterion adaptive_loss \
    --num_cores=8 --metrics_debug \
    --input_shapes 16x512 \
    --log_steps=30 \
    --log-format=simple  
```

#### What have you tried?

When I am running tutorials about MT and Roberta, they work well. 

#### What's your environment?

 - PyTorch Version: pytorch-xla-nightly, also tried pytorch-xla-1.5
 - TPU: V3-8

**Comment by jysohn23** [comment]
Can you share the output metrics? They should look something like this:

```
Metric: CompileTime
  TotalSamples: 202
  Counter: 06m09s401ms746.001us
  ValueRate: 778ms572.062us / second
  Rate: 0.425201 / second
  Percentiles: 1%=001ms32.778us; 5%=001ms61.283us; 10%=001ms79.236us; 20%=001ms110.973us; 50%=001ms228.773us; 80%=001ms339.183us; 90%=001ms434.305us; 95%=002ms921.063us; 99%=21s102ms853.173us
```

It sounds like you might be recompiling over and over again. Though if its constantly recompiling, you probably won't easily get to the end of the epoch to see the metrics report so you might want to set `XLA_METRICS_FILE` such that you get metrics at each step (follow https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#more-debugging-tools). One thing you might also want to try is the master branch of tpu-examples instead of 1.5.

**Comment by taylanbil** [comment]
Not all fairseq tasks/losses/codepaths are enabled in the [`pytorch-tpu`](github.com/pytorch-tpu/fairseq) fork. Specifically, in this command, I believe the criterion you're using needs to be modified, along with possibly some task elements such as the dataset loading etc.. There is tpu functionality added to upstream fairseq, you may get better luck there.

The intention is to merge the two reposgithu, but we just haven't had the time to look into that just yet.
