### ISSUE TITLE
Request for split size option in all-to-all API

### ISSUE THREAD

**Issue by amoghavs** [pytorch/xla#2413]
## 🚀 Feature

Currently the all-to-all support in torch-xla only allows specifying the concat dimension, split dimension and split-count. This assumes that all the ranks will contribute equal number of elements to the operation.

I request an option to specify the input and out split sizes, can support cases where there is imbalance in communication among the ranks.

## Motivation

Pytorch supports specifying input and output split sizes as shown here:
https://github.com/pytorch/pytorch/blob/master/torch/distributed/distributed_c10d.py#L1504-L1505

This is a fairly common used feature in DLRM as shown here:
https://github.com/facebookresearch/dlrm/blob/dist_exp/extend_distributed.py#L270

Without support for this feature, we cannot run realistic setups of DLRM.
Requesting this feature per discussion with @taylanbil and others.
cc: @srinivas212

**Comment by JackCaoG** [comment]
Hi @amoghavs , FYI there is a bug on `all_to_all` and `collective_permute`, we removed it from our documentation in https://github.com/pytorch/xla/pull/2386. We have an internal bug and discussion about how to fix it but until then this api might cause incorrect result. The only collective op we support right now is `all_reduce`

For your question, we can only only run a single program for multiple workers, that's why the code(and input) has to be exactly the same for all the workers. I think padded the input should solve your problem? @taylanbil I think that's how you make DLRM works right?

**Comment by taylanbil** [comment]
Yes, In the dlrm criteo dataset case, there are 26 tables and thus on a v3-8,

- 2 devices have 4 tables
- 8-2=6 devices have 3 tables
- so 6*3 + 2*4 = 26

What I ended up doing is, pad the input on 6 devices so they are of size `4xN` and then drop the relevant indices after `all_to_all`.

**Comment by shz0116** [comment]
> Hi @amoghavs , FYI there is a bug on `all_to_all` and `collective_permute`, we removed them from our documentation in #2386. We have an internal bug and discussion about how to fix them but until then these apis might cause incorrect result. The only collective op we support right now is `all_reduce`
> 
> For your question, we can only only run a single program for multiple workers, that's why the code(and input) has to be exactly the same for all the workers(cores). I think padded the input should solve your problem? @taylanbil I think that's how you make DLRM works right?

Testing test_mp_all_to_all.py example with V3-32. It seems the results still not correct. 
I assume he all_to_all correct problem still exist in the current nightly release ?

**Comment by JackCaoG** [comment]
`all_to_all` should be fixed by nightly. Can you share the code to repo?

**Comment by shz0116** [comment]
I just the standard test:
https://github.com/pytorch/xla/blob/master/test/test_mp_all_to_all.py
Just print out the result_tensor.

Here is the command: (I am using TPUv3-32)
export TPU_NAME=tpu32
python3 -m torch_xla.distributed.xla_dist --tpu=$TPU_NAME --conda-env=torch-xla-nightly --env XLA_USE_BF16=1 --env ANY_OTHER=ENV_VAR -- python3 /usr/share/torch-xla-nightly/pytorch/xla/test/test_mp_all_to_all.py

The data order seems not correct.
2020-11-05 20:18:04 10.164.0.85 [0] Wrong result from core 2: [0, 0, 0, 0, 1, 1, 1, 1, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 15, 16, 16, 16, 16, 17, 17, 17, 17, 18, 18, 18, 18, 19, 19, 19, 19, 2, 2, 2, 2, 20, 20, 20, 20, 21, 21, 21, 21, 22, 22, 22, 22, 23, 23, 23, 23, 24, 24, 24, 24, 25, 25, 25, 25, 26, 26, 26, 26, 27, 27, 27, 27, 28, 28, 28, 28, 29, 29, 29, 29, 3, 3, 3, 3, 30, 30, 30, 30, 31, 31, 31, 31, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9]
