### ISSUE TITLE
training stops on using pytorch xla

### ISSUE THREAD

**Issue by soumochatterjee** [pytorch/xla#2414]
while I am running this
```
import torch_xla.distributed.xla_multiprocessing as xmp
def _mp_fn(rank, flags):
    torch.set_default_tensor_type('torch.FloatTensor')
    a = _run() # it is the training function

FLAGS={}
xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=1, start_method='fork')
```
![image](https://user-images.githubusercontent.com/42636586/89905139-6b38fc80-dc07-11ea-848f-407ea24bf648.png)
![image](https://user-images.githubusercontent.com/42636586/89905247-8efc4280-dc07-11ea-9e4e-acd6ced989e2.png)

I have not put the whole error as its very big

**Comment by jysohn23** [comment]
Can you share a Colab notebook or a small repro with us? That'd help us debug the issue.

**Comment by soumochatterjee** [comment]
This was the error which came while I was using kaggle Kernel
while on Google co-lab it is still running without having any output showing on the console
here's the link to my co-lab notebook --> https://colab.research.google.com/drive/1kAUGTk9seeN2Ym3XIHMpHAEQmcQDzqP7?usp=sharing

**Comment by soumochatterjee** [comment]
It's still running

**Comment by maxwillzq** [comment]
Try to clone the colab and rerun but fail to due kaggle creditintal needed from @soumochatterjee.
Could you help create a small test case for issue reproduce purpose ? You can create some dummy data input and skip kaggle dataset download.

See template like https://colab.research.google.com/gist/maxwillzq/dc3b8f6c81aac7144afe3fa0aa09bd1a/pytorch_xla_debug-session.ipynb#scrollTo=CUnTEsqQdf2P

**Comment by soumochatterjee** [comment]
@maxwillzq , don't clone my repo 

open a new google colab notebook 
write the commands 

```
# dependency install
!pip install kaggle

# uploading kaggle credentials
from google.colab import files
files.upload()

# checking the file is uploaded in the kaggle enviroment or not
!ls -lha kaggle.json

# file configurations
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
```

and then upload your kaggle api token downloaded from your kaggle profile after accepting 
the rules for this competition https://www.kaggle.com/c/contradictory-my-dear-watson/data in kaggle

and then start copying code from my noteboook tab wise and run them
