### ISSUE TITLE
argmax with multiple max values returns last index (pytorch master is changing to return the first index)

### ISSUE THREAD

**Issue by ailzhang** [pytorch/xla#2415]
With https://github.com/pytorch/pytorch/pull/42004/files, pytorch master is moving to return the first index when there are multiple max values. But in xla this is implemented to be last index https://github.com/pytorch/xla/blob/master/torch_xla/csrc/reduction.cpp#L373
Currently we disable the tests to unblock upstream, we should consider whether to match the upstream behavior or put this in documentation for our next release.

**Comment by maxwillzq** [comment]
For curiosity, test pytorch nightly cpu and xla,  it still return last index. So the pytorch master merge is not in. 
See my test code

https://colab.research.google.com/gist/maxwillzq/00adb4e30dd7d7a5ffee1f54153e14d6/pytorch_xla_debug-session.ipynb

**Comment by JackCaoG** [comment]
@maxwillzq Yes, https://github.com/pytorch/pytorch/pull/42004 has not merged yet, argmax should still return the last index for now. I will merge my change once pytorch side pr merged.

**Comment by mruberry** [comment]
Argmin/argmax fix is in on the PyTorch side.
