### ISSUE TITLE
Handling views + in place ops

### ISSUE THREAD

**Issue by lmorino** [pytorch/xla#2418]
## ❓ Questions and Help
Hello, 

I was wondering how view operations and in place operations work together. If there is an input tensor x that is sent to XLA and a view op, for e.g. as_strided is called on it I noticed that this will create a new XLA tensor. If the user wants to get the as_strided output back will x be returned back in the form that as_strided converted it too or will it return a new aten::Tensor

Similarly if the input tensor x was followed by a view operation and an in-place op and the user wants to extract output of the in-place op out of XLA would x be returned? 

Thanks!

**Comment by JackCaoG** [comment]
Could you give a code example? Are you talking about something like 
```
>>> import torch
>>> import torch_xla
>>> t = torch.rand(4, 4, device='xla:0')
>>> b = t.view(2, 8)
>>> b
tensor([[0.1592, 0.3056, 0.3775, 0.1250, 0.2440, 0.9719, 0.3232, 0.2956],
        [0.4262, 0.3404, 0.4221, 0.4301, 0.0128, 0.1434, 0.7474, 0.0826]],
       device='xla:0')
>>> b += 1
>>> b
tensor([[1.1592, 1.3056, 1.3775, 1.1250, 1.2440, 1.9719, 1.3232, 1.2956],
        [1.4262, 1.3404, 1.4221, 1.4301, 1.0128, 1.1434, 1.7474, 1.0826]],
       device='xla:0')
>>> t
tensor([[1.1592, 1.3056, 1.3775, 1.1250],
        [1.2440, 1.9719, 1.3232, 1.2956],
        [1.4262, 1.3404, 1.4221, 1.4301],
        [1.0128, 1.1434, 1.7474, 1.0826]], device='xla:0')
```
?

**Comment by maxwillzq** [comment]
@lmorino  from pytorch document,  "Porch views share underlying data with its base tensor, if you edit the data in the view, it will be reflected in the base tensor as well."

it what your want ?
https://pytorch.org/docs/stable/tensor_view.html

**Comment by lmorino** [comment]
@JackCaoG yes that was what I referring too and @maxwillzq also answered this question for me.

**Comment by daydayfun** [comment]
@JackCaoG   How XLA release the function， when B+=1， and tensor t+1 also？can you show me the source code？

**Comment by daydayfun** [comment]
> Could you give a code example? Are you talking about something like
> 
> ```
> >>> import torch
> >>> import torch_xla
> >>> t = torch.rand(4, 4, device='xla:0')
> >>> b = t.view(2, 8)
> >>> b
> tensor([[0.1592, 0.3056, 0.3775, 0.1250, 0.2440, 0.9719, 0.3232, 0.2956],
>         [0.4262, 0.3404, 0.4221, 0.4301, 0.0128, 0.1434, 0.7474, 0.0826]],
>        device='xla:0')
> >>> b += 1
> >>> b
> tensor([[1.1592, 1.3056, 1.3775, 1.1250, 1.2440, 1.9719, 1.3232, 1.2956],
>         [1.4262, 1.3404, 1.4221, 1.4301, 1.0128, 1.1434, 1.7474, 1.0826]],
>        device='xla:0')
> >>> t
> tensor([[1.1592, 1.3056, 1.3775, 1.1250],
>         [1.2440, 1.9719, 1.3232, 1.2956],
>         [1.4262, 1.3404, 1.4221, 1.4301],
>         [1.0128, 1.1434, 1.7474, 1.0826]], device='xla:0')
> ```
> 
> ?

How the souce code release the feature, can you show me the code ?

**Comment by JackCaoG** [comment]
@daydayfun You can find the view related code in [this file](https://github.com/pytorch/xla/blob/master/torch_xla/csrc/view.cpp). XLA does not have storage, so most view ops are implemented as sequences of `reshape` and `transpose`.

**Comment by daydayfun** [comment]
> @daydayfun You can find the view related code in [this file](https://github.com/pytorch/xla/blob/master/torch_xla/csrc/view.cpp). XLA does not have storage, so most view ops are implemented as sequences of `reshape` and `transpose`.

Thanks a lot
