### ISSUE TITLE
[PT_BREAK] implement NumPy-like functionality maximum, minimum

### ISSUE THREAD

**Issue by RockingJavaBean** [pytorch/xla#2424]
From PR: https://github.com/pytorch/pytorch/pull/42579

## CircleCI error

The `pytorch_xla_linux_bionic_py3_6_clang9_build` failed in the PyTorch PR to implement `torch.maximum` and `torch.minimum` functions.

Below is the error message of the xla build CI.
```
Aug 14 10:05:46 Generated 1499 wrappers for /var/lib/jenkins/workspace/xla/scripts/../../torch/csrc/autograd/generated/RegistrationDeclarations.h
Aug 14 10:05:46 AtenXlaType function missed override: Tensor max(const Tensor& self, const Tensor& other); // max(Tensor,Tensor)->Tensor
Aug 14 10:05:46 AtenXlaType function missed override: Tensor min(const Tensor& self, const Tensor& other); // min(Tensor,Tensor)->Tensor
Aug 14 10:05:46 Traceback (most recent call last):
Aug 14 10:05:46   File "/var/lib/jenkins/workspace/xla/scripts/gen.py", line 1137, in <module>
Aug 14 10:05:46     generate(args)
Aug 14 10:05:46   File "/var/lib/jenkins/workspace/xla/scripts/gen.py", line 1107, in generate
Aug 14 10:05:46     assert check_overrides(overrides, overridden)
Aug 14 10:05:46 AssertionError
```

## Binary Ops change

https://github.com/pytorch/pytorch/pull/42579 tries to promote `torch.maximum` and `torch.minimum` over those hidden overloaded versions of `torch.max` and `torch.min`.

The `aten/src/ATen/native/BinaryOps.cpp` of this PR
```python
Tensor& maximum_out(Tensor& result, const Tensor& self, const Tensor& other) {
  TORCH_CHECK(!self.is_complex() && !other.is_complex(), "maximum does not support complex inputs.");

  auto iter = TensorIterator::binary_op(result, self, other,
                                        /*check_mem_overlap=*/true);
  maximum_stub(iter.device_type(), iter);
  return result;
}

Tensor maximum(const Tensor& self, const Tensor& other) {
  TORCH_CHECK(!self.is_complex() && !other.is_complex(), "maximum does not support complex inputs.");

  Tensor result;
  auto iter = TensorIterator::binary_op(result, self, other);
  maximum_stub(iter.device_type(), iter);
  return iter.output();
}

// binary max, alias for maximum
Tensor& max_out(Tensor& result, const Tensor& self, const Tensor& other) {
  return at::maximum_out(result, self, other);
}

Tensor max(const Tensor& self, const Tensor& other) {
  return at::maximum(self, other);
}
```

~~While `max.other` and `min.other` are removed in the native_functions.yaml.~~ My bad in the previous description,
Please refer to @mruberry 's comment below.

@ailzhang / @dlibenzi / @JackCaoG.
Cc @mruberry

**Comment by mruberry** [comment]
We're not removing `max.other` or `min.other`, but we are redispatching binary `torch.max` and `torch.min` to `torch.maximum` and `torch.minimum`, respectively.

**Comment by JackCaoG** [comment]
Thanks for reporting! Will look into it.

**Comment by JackCaoG** [comment]
It seems like there are actual behavior change and new `minimum_out` node being added. This might need more work than renaming the pt/xla api name... I will try to match pytorch behavior except `Nan`.

**Comment by JackCaoG** [comment]
@mruberry is  pytorch/pytorch#42579 close to final from the behavior point of view? Should I wait for a bit more before I start working on the xla side?

**Comment by mruberry** [comment]
> @mruberry is [pytorch/pytorch#42579](https://github.com/pytorch/pytorch/pull/42579) close to final from the behavior point of view? Should I wait for a bit more before I start working on the xla side?

It is close. There shouldn't be a behavior, just a swap of binary min for minimum and binary max for maximum. Can you elaborate on what you're seeing?

**Comment by JackCaoG** [comment]
@mruberry Oh, I didn't see anything(yet). I saw the `max` node is still there and `maximum` node is added, so I thought there is a behavior difference between them. If that's not the case I am just going to add an `aten:maximum` api and lower it to `max` node we already have.

**Comment by mruberry** [comment]
@JackCaoG great, I think that's all you need to do. Binary max and binary minimum should have the same behavior binary max used to, and they are synonymous with each other.

**Comment by JackCaoG** [comment]
@RockingJavaBean @mruberry xla change is ready now, I will land it when pytorch change merged.

**Comment by RockingJavaBean** [comment]
@JackCaoG thanks so much for your kind help.

**Comment by mruberry** [comment]
torch.minimum and torch.maximum just landed
