### ISSUE TITLE
Torchscript model with XLA fail on node lowering maxpool

### ISSUE THREAD

**Issue by maxwillzq** [pytorch/xla#2431]
## 🐛 Bug

choose a vgg19 model from torchvision, then build torch script model from vgg19.
When apply torch script model,  it is abort with error message

```
File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 575, in _max_pool2d
    if stride is None:
        stride = torch.jit.annotate(List[int], [])
    return torch.max_pool2d(
           ~~~~~~~~~~~~~~~~ <--- HERE
        input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: false INTERNAL ASSERT FAILED at "/pytorch/aten/src/ATen/core/boxing/KernelFunction.cpp":68, please report a bug to PyTorch. Tried to call KernelFunction::callBoxed() on a KernelFunction that can only be called with KernelFunction::call(). opname: aten::max_pool2d If you're using mobile selective build please make sure to include all ops exported from `torch.jit.export_opnames(model)`.
````

## To Reproduce

1. create a pytorch vgg19 model and input tensor on XLA
2.convert model to torch script model
3. apply input tensor on torch script model 

See part 2 of colab file: https://colab.research.google.com/drive/1YAf3_zFRzxyrEn0Hvw76tVAieR-Tpi_V#scrollTo=uLDdWtB2y5ax

## Environment

 - Reproducible on XLA backend [CPU/TPU]:
 - torch_xla version: nightly

**Comment by maxwillzq** [comment]
More debug information.

I add such code to output all ops need for my torch script model:
```python
ops = torch.jit.export_opnames(script_module)
print("ops = ", ops)
```

The result is like this:
```
['aten::adaptive_avg_pool2d',
 'aten::add_.Tensor',
 'aten::addmm',
 'aten::conv2d',
 'aten::dim',
 'aten::dropout',
 'aten::eq.int',
 'aten::flatten.using_ints',
 'aten::gt.int',
 'aten::len.t',
 'aten::matmul',
 'aten::max_pool2d',
 'aten::relu_',
 'aten::size',
 'aten::t',
 'prim::RaiseException'
```

It looks XLA fail to suport aten::max_pool2d ?

**Comment by maxwillzq** [comment]
Another finding: only CPU has no problem.
```python
import torch
import torch_xla
import torchvision
import torch_xla.core.xla_model as xm
import os
model = torchvision.models.vgg19(pretrained=True)
inputs = torch.ones(1, 3, 224, 224, requires_grad=True)
script_module = torch.jit.script(model)
print("script module: ", script_module)
ops = torch.jit.export_opnames(script_module)
print("ops = ", ops)
script_model_outputs = script_module(inputs)
```

it works properly. so we can narrow down the issue that it is max_pool2d + XLA + TorchScript

**Comment by maxwillzq** [comment]
Another test:  XLA model without Torch Script works properly

My test code passes:
```python
print("Method 2: XLA model without Torch Script")
xla_device = xm.xla_device()
xla_model = model.to(xla_device)
xla_inputs = inputs.to(xla_device)
xla_outputs = model(xla_inputs)
```

**Comment by maxwillzq** [comment]
My guess about this issue:
1. aten::max_pool2d should callBoxed since it is dispatched c10 by full.  
2. It looks torch script and normal way have different dispatch path. 
3. This bug may locate on python torch.jit module

Need more discussion with pytorch key developer

**Comment by ailzhang** [comment]
Hi @maxwillzq , thanks for the detailed issue report. A few notes here:
1. pytorch/xla currently support pytorch eager mode (without Torchscript). 
2. For most cases, torchscripted model still runs on xla backend. But the support is at kernel level instead of torchscript IR graph level. Which means although it works sometimes, it is kinda fragile. 
3. max_pool2d is indeed a special case in xla where we force dispatcher to do something special for xla backend. Relevant code is https://github.com/pytorch/xla/blob/master/torch_xla/csrc/aten_autograd_ops.cpp#L18. We do this mainly because pytorch's native implementation always requires materializing indices which is not necessary (and adds overhead) for xla backend.
With that said, given the limited engineer bandwidth, xla backend is recommended for eager mode currently.

**Comment by maxwillzq** [comment]
@ailzhang 

Thanks a lot for your reply. It is very clear.
One more comment.  Since the major purpose of XLA is for runtime improvement.  My understanding is that torch script will serve better for this purpose.  Since XLA use lazy execution which is static graph. 
We will also have more room for graph optimization if user give whole graph from torch script. 
How about your opinion ?

**Comment by ailzhang** [comment]
@maxwillzq Agreed that integrating with torchscript will definitely empower XLA to do more than lazy tensor. Especially it might map control flows directly to XLA IR if possible and gives XLA more room for optimization. The decision to prioritize eager support for now is mainly driven by 
- we want to maximize user experience (eager > torchscript) 
- limited engineer resource
