### ISSUE TITLE
one_hot issue as discussed in PR: #1301

### ISSUE THREAD

**Issue by cjolivier01** [pytorch/xla#2432]
## ❓ Questions and Help

I am running into this for a BERT model which doesn't coalesce due to the use of one_hot.

Y'all discussed this previously here:
  https://github.com/pytorch/xla/pull/1301/files

The item() call is still in pytorch codebase.

What is your recommendation?  Comment out those checks in pytorch?  Should I implement an XLA version of one_hot and submit to this project (i.e. like is done in nll_loss.cpp)?  Something else?

Best regards,

-Chris

**Comment by JackCaoG** [comment]
@cjolivier01 I think the problem here is that `one_hot` is a non-leaf node. Even if we implement the lowering for it, pytorch won't call our lowering. I think you can comment out that check and recompile pytorch. That should work for now.

@ailzhang Is there a workaround for that check?

**Comment by ailzhang** [comment]
The changes I'm working on might make overriding it easier but it's still WIP and might take some time. The fastest way now is probably lowering `one_hot` similar to https://github.com/pytorch/xla/blob/master/torch_xla/csrc/aten_autograd_ops.h#L10 and we'd happily accept a PR for it. :D

**Comment by cjolivier01** [comment]
Thanks for the feedback!  I only just now saw both comments for some reason.
