### ISSUE TITLE
How to speed up the compilation process for contributor for c++ lib

### ISSUE THREAD

**Issue by maxwillzq** [pytorch/xla#2433]
## ❓ Questions and Help

When I only modify 1 c++ file, I expect the compile process only need rebuild this c++ file and do related link process. In PyTorch, it uses ninja to speed up this process.

But when use "DEBUG=1 python setup.py develop", it will recompile whole TensorFlow and xla code by Bazel, it take a long time.
Any best practice your guy can share?
We should write down this part on the contributing.md.
Thanks

**Comment by JackCaoG** [comment]
Hmm, that should not happen. TensorFlow should not be recompiled if you only modify one C++ file(There should be a bazel cache hit). `DEBUG=1` controls PT/XLA (our repo) and `XLA_DEBUG=1` controls TensorFlow and XLA. I always have `DEBUG=1` enabled and I tried to set it to false and recompile, it does not recompile TensorFlow for me. Could you try `python setup.py install`?

**Comment by cjolivier01** [comment]
I have found that bazel likes to recompile all of tensorflow if anything about the environment changes (at least that's my observation).  For example, if I change PYTHONPATH: recompile. Change PATH: recompile. Sneeze: recompile.

How I get around this is I always run the build from a 'sterile" environment, for me, that's the CLion IDE launched from the desktop and *not a bash prompt* and the build launched through a cmake target.  Something similar could be done with vscode, for instance, or some other mechaniosm that assures the environment is the sasme every time.  Doing this, I have never found tensorflow to rebuild unexpectedly, although it used to do it constantly before.

**Comment by maxwillzq** [comment]
Thanks a lot, @JackCaoG  and @cjolivier01.
I will try and let your guy know the feedback soon
