### ISSUE TITLE
Implement remaining unary ops

### ISSUE THREAD

**Issue by vishwakftw** [pytorch/xla#245]
Hi,

I found a few unimplemented unary operations, and was wondering if I could help out with implementing them if you have plans for supporting them in the future.

I've listed them below (taken using an intersection of ops in XLA and PyTorch):
- [x] abs (#254)
- [x] acos (#268)
- [x] asin (#268)
- [x] atan (#289)
- [x] ceil (#298)
- [x] cosh (#268)
- [x] erf (#284)
- [x] erfc (#284)
- [x] erfinv (#340)
- [x] expm1 (#269)
- [x] floor (#298)
- [x] log2 (#331)
- [x] log10 (#341)
- [x] log1p (#269)
- [x] reciprocal (#307)
- [x] rsqrt (#307)
- [x] sign (#332)
- [x] sinh (#268)
- [x] tan (#289)
- [x] tanh (#289)

Thank you.

**Comment by dlibenzi** [comment]
Hi Vishwak,

we are currently implementing an infrastructure with which unsupported TPU
operations will automatically run on CPU.
This will allow models which do not have 100% coverage, to still run.
We are also rushing in with the lowerings of the operations which have a
straight XLA lowering, and the ones you listed there mostly fit the
criteria, so they will be tackled first.
I can expect that in a couple of weeks  they will mostly be implemented
with TPU lowering.
But with the new design, users should be able to run models even if there
are some operators which are not implemented on TPU yet.

**Comment by vishwakftw** [comment]
Thanks, that sounds great! Could I send in pull requests implementing these straight forward ones, if you don't mind? I could use #241 and #242 for reference.

**Comment by dlibenzi** [comment]
Sure!
Let's start with abs() first.
We might tackling those ourselves as well, so you start from the bottom and we eventually start from the top (in alphabetical order) ;)
