### ISSUE TITLE
Requesting support for the torch.baddbmm operator.

### ISSUE THREAD

**Issue by wangshangsam** [pytorch/xla#2451]
## 🚀 Feature

https://pytorch.org/docs/stable/generated/torch.baddbmm.html
I noticed that `torch_xla` can support `bmm` already (`xla::bmm`), however `baddbmm` (which is essentially just `bmm` with bias) is still outsourcing to the CPU (`aten::baddbmm`), which results in outrageous performance (more than 10x worse than `bmm + add bias` on a relatively small set of matrices (2 x 9216 x 128 by 2 x 64 x 9216)) on cloud TPU v3.

## Motivation

1. `baddbmm` is one of the official torch operator, so `torch_xla` should support it.
2. `baddbmm` would definitely have higher performance than `bmm + add` since the bias-add is just an elementwise kernel, which should be able to fused with the gemm kernel ahead of it.

## Pitch

`xla::baddbmm`

## Alternatives

`bmm + add`

## Additional context

Is there a way to request this feature with high priority? We would need this feature (ideally) for a coming paper deadline. Thanks!

cc @eric-zheng

**Comment by JackCaoG** [comment]
I didn't look too closely into `baddbmm` but if `baddbmm` is just `bmm + add`, there shouldn't be a difference if you just workaround it with `bmm + add`. XLA sees the whole graph and always perform the fusion. My lowering will most likely be break `baddbmm` into `bmm` + 'add'.

**Comment by wangshangsam** [comment]
Thanks a lot @JackCaoG for helping us!

**Comment by JackCaoG** [comment]
Close this thread as lowering has been merged

**Comment by wangshangsam** [comment]
@JackCaoG Thank you so much for your effort! I'm assuming we would be able to get this change through the torch-nightly conda environment?

**Comment by JackCaoG** [comment]
@wangshangsam yup, you should see this on tomorrow's nightly, not sure if this one made today's nightly build 😄

**Comment by wangshangsam** [comment]
@JackCaoG Sounds good! I'll try it tomorrow and let you know!

**Comment by wangshangsam** [comment]
@JackCaoG Do I have to create a new VM instance in order to use this change? Or is it a way to update my current `torch-xla-nightly` conda env?

**Comment by JackCaoG** [comment]
@wangshangsam It depends on how you install it. If you install it from docker, you can [pull](https://github.com/pytorch/xla#-consume-prebuilt-docker-images) the latest docker image. If you build it from source then you just need to `git pull` and build it again.

**Comment by wangshangsam** [comment]
I was using it in via pre-built VM instance: https://github.com/pytorch/xla#-consume-prebuilt-compute-vm-images
Although, after I
```bash
(vm)$ cd /usr/share/torch-xla-nightly/pytorch/xla
(vm)$ . ./scripts/update_nightly_torch_wheels.sh
```
I do see `xla::baddbmm`. Thanks a lot!

**Comment by wangshangsam** [comment]
@JackCaoG I'm wondering if there would be an easy way to figure out which line of PyTorch code triggers a re-compile (assuming the cached compile count is really low)?
