### ISSUE TITLE
Any plan for PyTorch XLA quantization ??

### ISSUE THREAD

**Issue by maxwillzq** [pytorch/xla#2455]
## ❓ Questions and Help

I test PyTorch quantization on XLA. currently, XLA does not support quantized dtype.  Any plan for PyTorch XLA quantization support ?

My test notebook:  https://colab.research.google.com/drive/1A9BEPMg1Sxys6wQUPZ2PBTzsW6RoiS-n?usp=sharing

![image](https://user-images.githubusercontent.com/1200986/90983907-7d2f6f00-e526-11ea-8cfd-0bc323c650d1.png)

**Comment by maxwillzq** [comment]
Sometime it will crash with error message:
```
WARNING:root:kernel 623c66b2-2db6-4367-a201-e8d56f1cbc4c restarted
```

**Comment by maxwillzq** [comment]
my torch version: 1.7.0a0+a97ca93

**Comment by JackCaoG** [comment]
Sorry for the late reply, we currently do not have plans to support pytorch quantization.
