### ISSUE TITLE
slowdown in fairseq transformer

### ISSUE THREAD

**Issue by zcain117** [pytorch/xla#2467]
## 🐛 Bug

Looking at Fairseq Transformer's fast config, I see:
Aug 3 VM: 10k wps
Aug 4 VM: 9k wps
Aug 8 VM: 7.6k wps

I used the same TPU version (`pytorch-nightly`) with each of the different VMs.

Metrics attached for sample Aug 3 and Aug 4 runs. We suspected either:
1. new issue in the way we lower the model
2. regression in XLA's execution of the graph

To check 1, I collected graphs using Aug 3, Aug 4, and Aug 8 VM. **The graphs were identical between the 3 VM versions, but note I only collected graphs for the first 10 steps per VM version**.

Possibility 2 we think doesn't make sense because we're using the same TPU version.

Another notable piece of information:
Slowdown only occurs when using 3 shapes, e.g. `--input_shapes 256x64 512x32 640x16`. If I use just 1 shape of any of those sizes or any of the 2 shape combinations, there is no slowdown. I also tried a different 3-shape version `128x128 256x64 512x32` and saw the same slowdown. The 3-shape version I think would have more total HLO graphs that it needs to cache and switch between than the 1-shape or 2-shape versions. @davidel is there any other reason you can think of why 3-shape transformer would be different than 1-shape or 2-shape when all are using the same TPU software version?

[128x128-256x64-512x32-eightcore-aug3vm-aug26-nightlyTPU.txt](https://github.com/pytorch/xla/files/5138894/128x128-256x64-512x32-eightcore-aug3vm-aug26-nightlyTPU.txt)
[128x128-256x64-512x32-eightcore-aug4vm-aug26-nightlyTPU.txt](https://github.com/pytorch/xla/files/5138895/128x128-256x64-512x32-eightcore-aug4vm-aug26-nightlyTPU.txt)
[256x64-512x32-640x16-eightcore-aug3vm-aug25-nightlyTPU.txt](https://github.com/pytorch/xla/files/5138896/256x64-512x32-640x16-eightcore-aug3vm-aug25-nightlyTPU.txt)
[256x64-512x32-640x16-eightcore-aug4vm-aug25-nightlyTPU.txt](https://github.com/pytorch/xla/files/5138897/256x64-512x32-640x16-eightcore-aug4vm-aug25-nightlyTPU.txt)

## To Reproduce

I used `pytorch-nightly` TPU version and can see the wps difference using Aug 3 and Aug 4 VM images, i.e.:

`docker run -it -v $HOME/logs/:/tmp/logs/ -v $HOME/dataset:/tmp/dataset --shm-size 16G gcr.io/tpu-pytorch/xla:nightly_3.6_20200804`

`docker run -it -v $HOME/logs/:/tmp/logs/ -v $HOME/dataset:/tmp/dataset --shm-size 16G gcr.io/tpu-pytorch/xla:nightly_3.6_20200803`

Command I used inside the docker image:

```
python3 tpu-examples/deps/fairseq/train.py \
               /tmp/dataset/wmt18_en_de_bpej32k \
               --metrics_debug \
               --arch=transformer_vaswani_wmt_en_de_big \
               --max-target-positions=64 \
               --attention-dropout=0.1 \
               --no-progress-bar \
               --criterion=label_smoothed_cross_entropy \
               --source-lang=en \
               --lr-scheduler=inverse_sqrt  \
               --min-lr=1e-09 \
               --skip-invalid-size-inputs-valid-test \
               --target-lang=de \
               --label-smoothing=0.1 \
               --update-freq=1 \
               --optimizer=adam \
               --adam-betas='(0.9,0.98)' \
               --warmup-init-lr=1e-07 \
               --lr=0.0005 \
               --warmup-updates=4000 \
               --share-all-embeddings \
               --dropout=0.3 \
               --weight-decay=0.0 \
               --num_cores=8 \
               --save-interval=5 \
               --save-dir=/tmp/checkpoints \
               --max-epoch=3 \
               --log_steps=200 \
               --train-subset=train \
               --valid-subset=valid \
               --input_shapes 256x64 512x32 640x16 2>&1 | tee /tmp/logs/pt-trans-aug3vm-aug21-nightlyTPU.txt
```

**Comment by davidel** [comment]
The `ExecuteTime` is quite different indeed (in the higher percentiles), though the accumulator does not swing too much (certainly not to account for a 25% drop):
```
Metric: ExecuteTime
  TotalSamples: 5392
  Accumulator: 01h19m35s311ms613.667us
  ValueRate: 848ms817.307us / second
  Rate: 1.09276 / second
  Percentiles: 1%=232ms787.088us; 5%=233ms575.599us; 10%=235ms557.673us; 20%=822ms574.804us; 50%=845ms034.623us; 80%=871ms990.221us; 90%=901ms015.515us; 95%=920ms755.829us; 99%=951ms665.957us
```

```
Metric: ExecuteTime
  TotalSamples: 5392
  Accumulator: 01h26m49s202ms767.649us
  ValueRate: 846ms292.656us / second
  Rate: 0.996882 / second
  Percentiles: 1%=232ms873.983us; 5%=232ms492.951us; 10%=234ms476.804us; 20%=822ms653.114us; 50%=844ms436.445us; 80%=01s196ms313.592us; 90%=01s249ms605.445us; 95%=01s268ms781.952us; 99%=01s324ms454.382us
```

BTW, when collecting metrics to compare, it is better to restart the TPU, as service side metrics do not get reset.

The `TransferToServerTime` got slower, but even here does not seem enough to justify a 25% drop.
One way to measure if there is somehow I/O bound is to put a timer around this line:

https://github.com/pytorch/xla/blob/19fc8124d5cbefd18796b2439ddf3fded5c7a9ba/torch_xla/distributed/parallel_loader.py#L38

That should be close to zero if I/O can go totally hidden behind computation.

**Comment by davidel** [comment]
Also, the IR graphs are the same ... but what about the HLO ones?

**Comment by zcain117** [comment]
Between each run, I stopped and started the TPU in GCE. Is that sufficient to reset metrics or do I need to delete and make a new TPU for each run?

The graphs I compared came from:
```
export DEBUG=1 XLA_IR_DEBUG=1 XLA_HLO_DEBUG=1 XLA_SAVE_TENSORS_FMT=hlo
export XLA_SAVE_TENSORS_FILE=/tmp/logs/
< run model for 10 steps >
cat /tmp/logs/00 | xla/scripts/grab_graphs.py --graphdir=/PATH/TO/DIR > report.txt
```
So I think these were HLO graphs. Should I try IR graphs too?


I will try adding the timer in `parallel_loader`

**Comment by davidel** [comment]
Sorry for the delay.
Yes, stop/start the TPU node is enough to reset the XRT metrics.

So looking at the Aug 25 logs it is a bit hard to compare as they did a different number of steps (look at `MarkStep` at the end), but it looks like the slow-down in `ExecuteTime` is there,

Are the IR graphs the same? Are the HLO ones?
Different IR graphs can come from PT issuing different calls into PT/XLA, or from our code translating the calls from PT into different IR.
Different HLO graphs, assuming same IR graphs, can come only from our code (either explicit PT/XLA core code, or linked TF XLA builder translating same calls to different HLO).

Can you get a clean, same number of steps, same shapes, same TPU version, Aug 3 vs Aug 8 logs?

**Comment by zcain117** [comment]
All tests run on Sep 2 using nightly TPU and resetting TPU between runs. All runs using 3 input shapes `256x64 512x32 640x16`:

commit_7a2f049_xla_aug4pytorch.txt:
* pytorch at 8850fd1952c3983793dcac4022fdc8e3913dad96 (i.e. Aug 4)
* pytorch/xla at 7a2f0493986803a277392ca565a883535f990a47 (i.e. midway through Aug 3)
* ~10.9k wps at end of epoch 3

aug4xla_aug3pytorch_runSep2.txt:
* pytorch at bfa94487b968ccb570ef8cd9547029b967e76ed0 (i.e. Aug 3)
* pytorch/xla at 18fa011c3eba79b93ea38cf5b0946920e45b2053 (i.e. Aug 4)
* ~9.4k wps at end of epoch 3

aug3_exclude_cxx11_3shape.txt:
* pytorch at bfa94487b968ccb570ef8cd9547029b967e76ed0 (i.e. Aug 3)
* pytorch/xla at 7a2f0493986803a277392ca565a883535f990a47 (i.e. midway through Aug 3)
* ~10.9k wps at end of epoch 3

This means that adding pytorch/xla commit 18fa011c3eba79b93ea38cf5b0946920e45b2053 and (as far as I can tell) changing nothing else results in the slowdown I've been seeing between Aug 3 and Aug 4. This commit corresponds to: `Disable CXX 11 ABI when building wheels` (#2390)

[commit_7a2f049_xla_aug4pytorch.txt](https://github.com/pytorch/xla/files/5189243/commit_7a2f049_xla_aug4pytorch.txt)
[aug4xla_aug3pytorch_runSep2.txt](https://github.com/pytorch/xla/files/5189247/aug4xla_aug3pytorch_runSep2.txt)
[aug3_exclude_cxx11_3shape.txt](https://github.com/pytorch/xla/files/5189249/aug3_exclude_cxx11_3shape.txt)

**Comment by taylanbil** [comment]
AFAIU, weird thing is, HLO graphs are exactly the same, and there is no slowdown with any of the 1 shapes; `256x64` `512x32` or `640x16`. There is no slowdown with the 2 shape configs either. It's only the 3 shape config that has regressed somehow.

@zcain117, could you confirm this?

**Comment by zcain117** [comment]
Yes these are the main takeaways so far:
1. TPU software version does not matter
2. none of the 1-shape or 2-shape combinations from `256x64 512x32 640x16` is unaffected, only the 3 shape config. I also tried `128x128 256x64 512x32` and saw the same behavior (fast before commit 18fa011 and ~1k wps slower after)
3. 18fa011  is where the slowdown seems to begin

**Comment by jysohn23** [comment]
Based on the comment you made internally it looks like the XrtExecute also is slower for the regression:

```
Metric: XrtExecute
  TotalSamples: 341624
  Accumulator: 03d06h44m08s171ms567.019us
  Mean: 867ms576.894us
  StdDev: 036ms947.658us
  Rate: 8.00076 / second
  Percentiles: 25%=837ms566.639us; 50%=867ms712.713us; 80%=894ms098.337us; 90%=910ms022.084us; 95%=922ms654.358us; 99%=946ms971.920us
```

vs

```
Metric: XrtExecute
  TotalSamples: 341624
  Accumulator: 04d20h47m29s347ms073.339us
  Mean: 01s019ms936.367us
  StdDev: 143ms542.596us
  Rate: 6.76779 / second
  Percentiles: 25%=830ms159.071us; 50%=01s110ms788.588us; 80%=01s132ms656.582us; 90%=01s142ms837.040us; 95%=01s152ms933.821us; 99%=01s173ms408.474us
```

That commit should solely affect client side and I personally don't really see how it could be slowing down the execution on the server side (even on the client side I don't know how ABIs could slow down execution). You can try maybe reverting that commit locally, rebuilding, and benchmarking?
