### ISSUE TITLE
[PT_BREAK] This unrelated PR: https://github.com/pytorch/pytorch/pull/40054 seems to break the XLA test.

### ISSUE THREAD

**Issue by protonu** [pytorch/xla#2468]
## To Reproduce

1.
2.
3.

## Environment

 - Reproducible on XLA backend [CPU/TPU]:
 - torch_xla version:

**Comment by JackCaoG** [comment]
@protonu The failure might not be relevant(grpc failure), could you rerun the `pytorch_xla_linux_bionic_py3_6_clang9_test` task? Thanks!

**Comment by JackCaoG** [comment]
Close this as pytorch pr has been merged
