### ISSUE TITLE
xmp.spawn can not use 2 TPUs on a node

### ISSUE THREAD

**Issue by shz0116** [pytorch/xla#2483]
I am trying to spawn 2 processes on.a TPU node as following:

import torch_xla.distributed.xla_multiprocessing as xmp
xmp.spawn(main, args=(), nprocs=2),

But get the error. It seems I can not use 2 TPU cores only on a node ?

  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 385, in spawn
    pf_cfg = _pre_fork_setup(nprocs)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 201, in _pre_fork_setup
    dev_count, num_devices))
ValueError: The number of devices must be either 1 or 8, got 2 instead

**Comment by JackCaoG** [comment]
We currently only support running with 1 TPU node or 8 TPU nodes.

**Comment by shz0116** [comment]
I think you mean 1 TPU core or 8 TPU cores on a node, right ?
Can I ask why 2, and 4, not supported ? Thanks.

**Comment by JackCaoG** [comment]
Hi @shz0116 sorry for the noise, my previous comments seems wrong. 
The check is in 
https://github.com/pytorch/xla/blob/ec79c5f4720c493d63ac868f8d3e7804f403d907/torch_xla/distributed/xla_multiprocessing.py#L200
I think if you manually export `TPU_NUM_DEVICES` to `2`(It is default to 8) you should be able to only use 2 cores.
