### ISSUE TITLE
Support in roi_align for MaskRCNN

### ISSUE THREAD

**Issue by ofekp** [pytorch/xla#2487]
## 🚀 Feature
Today there is no way to train MaskRCNN from torchvision on TPU since there is no support in roi_align in XLA.

## Motivation
MaskRCNN is widely used in segmentation models, we recently used it in our project and we could not run on TPU purely because we were lacking the implementation of roi_align. OK, there can be more methods we did not get to reach, but this one surely needs to be implemented.

## Pitch
Implementation of roi_align in pytorch/xml.
This is the torchvision equivalent (which does not support XLA devices):
https://pytorch.org/docs/stable/torchvision/ops.html#torchvision.ops.roi_align
CPP implementation from torchvision:
https://github.com/pytorch/vision/blob/131ba1320b8208f10eb58d5feb7416c90ed839bb/torchvision/csrc/cuda/ROIAlign_cuda.cu#L64

## Alternatives
An alternative might be to implement this using other methods in pytorch/xla which are already implemented, not sure it is feasible.

## Additional context
I managed to switch [box_ops.batched_nms](https://pytorch.org/docs/stable/torchvision/ops.html#torchvision.ops.nms) with nms from [torch_xla](http://pytorch.org/xla/release/1.6/index.html#torch_xla.core.functions.nms) but then ran into the **roi_align** method which also has no support in XLA devices and is also not implemented in torch_xla

Thank you!

**Comment by oke-aditya** [comment]
It would be great to have TPU support for all the object detection, instance segmentation required modules in torchvision.

 E.g. NMS, roi align etc. I'm unsure which are supported as of now.

**Comment by asuhan** [comment]
Such functionality can be either supported through interop (convert the XLA tensors to CPU, run the kernel, convert the result back to XLA) or by rewriting it in terms of tensors. Have a look at https://github.com/asuhan/maskrcnn-benchmark/blob/static_shapes/maskrcnn_benchmark/layers/tensor_roi_align.py.

**Comment by ofekp** [comment]
@asuhan I don't have much experience with training on TPU, but I feel like converting to CPU and the back to tensor is missing the point of speeding up training. If the model is trained fast enough even with such modification then please let me know, but I think maybe the conversion and network latency may cause it to be very slow. Did you test this? Do you know what overhead it introduces to the training time (of course it is model dependent put any comparison is better than nothing)?

**Comment by asuhan** [comment]
@ofekp It all depends on how expensive that particular operation is. In the case of ROI align, yes, it'd be very expensive - *a lot* of data to transfer, which is why I re-implemented it in terms of tensors. In other cases, though, it might basically be fast enough. It all depends on the concrete workload.

**Comment by ofekp** [comment]
@asuhan Can you please explain how I can use your implementation while replacing the torchvision implementation which does not support XLA? 🙏

**Comment by asuhan** [comment]
This is what I did: https://github.com/asuhan/maskrcnn-benchmark/blob/753e5d2d0285a6175340e38ca203d899cc07916c/maskrcnn_benchmark/layers/roi_align.py#L59, AFAICT you could make the same change here: https://github.com/pytorch/vision/blob/a4736ea6e8ff25a1265ca5adf9e6e244d78500e8/torchvision/ops/roi_align.py#L71.

**Comment by maramir6** [comment]
Has been any improvement in this topic?

**Comment by codeislife99** [comment]
Hi, has there been any progress on this issue ? I am facing the same problem.

**Comment by byronyi** [comment]
Nah, dynamic shape isn't something XLA like.

Unfortunately torchvision detection models use `nonzero`, `index.Tensor`, and `nms` heavily. All of those produce dynamically sized results.

**Comment by codeislife99** [comment]
So, is the consensus from the XLA team to never officially support PT-XLA ? I believe that a custom model can be written which is more geared towards XLA. What are your thoughts / opinions on this ?

**Comment by byronyi** [comment]
"never officially support PT-XLA" that not what I mean. My hunch is just the underlying hardware (CloudTPU) doesn't run these models efficiently enough to compete with GPU solution, and it manifests itself to be an XLA coverage issue.

**Comment by codeislife99** [comment]
I see, thanks so much for expanding on this , another question I had was that XLA is supposed to cluster and partition only subgraphs of ops that it supports. Therefore, theoretically it should still work with those unsupported ops (NMS, etc..). How does this not happen in this case ?

**Comment by byronyi** [comment]
> Such functionality can be either supported through interop (convert the XLA tensors to CPU, run the kernel, convert the result back to XLA) or by rewriting it in terms of tensors. Have a look at https://github.com/asuhan/maskrcnn-benchmark/blob/static_shapes/maskrcnn_benchmark/layers/tensor_roi_align.py.

@codeislife99 Take a look on the Alex's reply.

**Comment by codeislife99** [comment]
Just checking in on this issue, if I understand correctly, the status is still the same correct, XLA is not supporting detection models from torchvision ?

**Comment by JackCaoG** [comment]
Short answer is yes. @miladm has more info. We are working on the dynamic shape support from the infra side with pytorch core team, without the properly support at the framework level(for example what does `tensor.size` return for a dynamic tensor and how does dynamic dimension propagate) op level support will not be sufficient.

**Comment by codeislife99** [comment]
Thank you

**Comment by aazzolini** [comment]
Hey folks what is the status on this? @miladm  is there a viable path to support roi_align in torch_xla?

**Comment by miladm** [comment]
Here is the latest on roi_align @aazzolini 

https://github.com/pytorch/xla/pull/4703

Turns out the team didn't run into dynamism within roi_align.
