### ISSUE TITLE
After first epoch model was saved, the code failed

### ISSUE THREAD

**Issue by kkissmart** [pytorch/xla#2491]
After the first checkpoint is saved. I got below message.

2020-09-13 02:05:53 | INFO | root | NOTE: XLA compilation detected; too many of these can lead to slow training, but we expect a few in the beginning
2020-09-13 02:05:53 | INFO | fairseq_cli.train | begin validation on "valid" subset
2020-09-13 02:08:48 | INFO | valid | epoch 001 | valid on 'valid' subset | loss 7.298 | ppl 157.42 | wps 1653.6 | wpb 13714.1 | bsz 30.9 | num_updates 1
2020-09-13 02:08:48 | INFO | fairseq_cli.train | begin save checkpoint
terminate called after throwing an instance of 'c10::Error'
  what():  [enforce fail at inline_container.cc:274] . unexpected pos 3695636864 vs 3695636752
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0xa0 (0x7f940977a980 in /anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1cc73f2 (0x7f940b65e3f2 in /anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #2: <unknown function> + 0x1cc145a (0x7f940b65845a in /anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #3: caffe2::serialize::PyTorchStreamWriter::writeRecord(std::string const&, void const*, unsigned long, bool) + 0xa7 (0x7f940b65eda7 in /anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #4: caffe2::serialize::PyTorchStreamWriter::writeEndOfFile() + 0xaa (0x7f940b65f1ea in /anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #5: caffe2::serialize::PyTorchStreamWriter::~PyTorchStreamWriter() + 0x1b (0x7f940b65f52b in /anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x9b9366 (0x7f9412156366 in /anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x391c1b (0x7f9411b2ec1b in /anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x38956c (0x7f9411b2656c in /anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0xf2247 (0x563eab0e2247 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #10: <unknown function> + 0xf20d7 (0x563eab0e20d7 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #11: <unknown function> + 0xf20ed (0x563eab0e20ed in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #12: _PyEval_EvalFrameDefault + 0x255d (0x563eab1aea6d in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #13: <unknown function> + 0x193cfb (0x563eab183cfb in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #14: <unknown function> + 0x199be5 (0x563eab189be5 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #15: _PyEval_EvalFrameDefault + 0x30a (0x563eab1ac81a in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #16: <unknown function> + 0x192f26 (0x563eab182f26 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #17: <unknown function> + 0x193f31 (0x563eab183f31 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #18: <unknown function> + 0x199be5 (0x563eab189be5 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #19: _PyEval_EvalFrameDefault + 0x30a (0x563eab1ac81a in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #20: <unknown function> + 0x193cfb (0x563eab183cfb in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #21: <unknown function> + 0x199be5 (0x563eab189be5 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #22: _PyEval_EvalFrameDefault + 0x30a (0x563eab1ac81a in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #23: <unknown function> + 0x19335e (0x563eab18335e in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #24: <unknown function> + 0x193f31 (0x563eab183f31 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #25: <unknown function> + 0x199be5 (0x563eab189be5 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #26: _PyEval_EvalFrameDefault + 0x30a (0x563eab1ac81a in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #27: <unknown function> + 0x193cfb (0x563eab183cfb in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #28: <unknown function> + 0x199be5 (0x563eab189be5 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #29: _PyEval_EvalFrameDefault + 0x30a (0x563eab1ac81a in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #30: PyEval_EvalCodeEx + 0x329 (0x563eab184a49 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #31: <unknown function> + 0x195976 (0x563eab185976 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #32: PyObject_Call + 0x3e (0x563eab10210e in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #33: _PyEval_EvalFrameDefault + 0x1aaf (0x563eab1adfbf in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #34: <unknown function> + 0x19335e (0x563eab18335e in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #35: <unknown function> + 0x193f31 (0x563eab183f31 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #36: <unknown function> + 0x199be5 (0x563eab189be5 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #37: _PyEval_EvalFrameDefault + 0x30a (0x563eab1ac81a in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #38: PyEval_EvalCodeEx + 0x329 (0x563eab184a49 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #39: <unknown function> + 0x195976 (0x563eab185976 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #40: PyObject_Call + 0x3e (0x563eab10210e in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #41: _PyEval_EvalFrameDefault + 0x1aaf (0x563eab1adfbf in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #42: PyEval_EvalCodeEx + 0x329 (0x563eab184a49 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #43: <unknown function> + 0x195864 (0x563eab185864 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #44: PyObject_Call + 0x3e (0x563eab10210e in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #45: _PyEval_EvalFrameDefault + 0x1aaf (0x563eab1adfbf in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #46: <unknown function> + 0x193cfb (0x563eab183cfb in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #47: <unknown function> + 0x199be5 (0x563eab189be5 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #48: _PyEval_EvalFrameDefault + 0x30a (0x563eab1ac81a in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #49: PyEval_EvalCodeEx + 0x329 (0x563eab184a49 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #50: <unknown function> + 0x195864 (0x563eab185864 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #51: PyObject_Call + 0x3e (0x563eab10210e in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #52: _PyEval_EvalFrameDefault + 0x1aaf (0x563eab1adfbf in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #53: PyEval_EvalCodeEx + 0x329 (0x563eab184a49 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #54: <unknown function> + 0x195976 (0x563eab185976 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #55: PyObject_Call + 0x3e (0x563eab10210e in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #56: _PyEval_EvalFrameDefault + 0x1aaf (0x563eab1adfbf in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #57: <unknown function> + 0x193cfb (0x563eab183cfb in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #58: <unknown function> + 0x199be5 (0x563eab189be5 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #59: _PyEval_EvalFrameDefault + 0x30a (0x563eab1ac81a in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #60: <unknown function> + 0x193cfb (0x563eab183cfb in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #61: <unknown function> + 0x199be5 (0x563eab189be5 in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #62: _PyEval_EvalFrameDefault + 0x30a (0x563eab1ac81a in /anaconda3/envs/torch-xla-nightly/bin/python)
frame #63: <unknown function> + 0x193cfb (0x563eab183cfb in /anaconda3/envs/torch-xla-nightly/bin/python)

Traceback (most recent call last):
  File "train.py", line 14, in <module>
    cli_main()
  File "/home/yinhan/bart_modification/fairseq_cli/train.py", line 343, in cli_main
    distributed_utils.call_main(args, main)
  File "/home/yinhan/bart_modification/fairseq/distributed_utils.py", line 183, in call_main
    nprocs=8,  # use all 8 TPU cores
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 395, in spawn
    start_method=start_method)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 108, in join
    (error_index, name)
Exception: process 0 terminated with signal SIGABRT

**Comment by leo-du** [comment]
Hi, I'm having the same trouble, would you share how you solved this problem? Thanks!

**Comment by kkissmart** [comment]
for me was that the disk ran out of space.

**Comment by hannlp** [comment]
Can you elaborate on the resolution process? thank you very much. @kkissmart

**Comment by kkissmart** [comment]
request a new instance with larger disk.
