### ISSUE TITLE
How to prevent cyclic computation graph in torch xla multiprocessing?

### ISSUE THREAD

**Issue by jpmailoa** [pytorch/xla#2502]
## ❓ Questions and Help
Hi,

I am trying to build a dynamics simulator software on the TPU. On the high level, it basically needs to do this (I have pre-trained the model separately elsewhere):

```
for i in range(num_of_step):
    forces = model(positions)
    new_positions = update_functions(forces, positions)
    positions = new_positions
```

When I do this workflow on a single TPU, it is quite fast. While I am aware that there is generally an issue with slow `tensor.item()` call, the following sequence will work quite fast for me:

```
for i in range(num_of_step):
    positions = torch.Tensor(structure.positions).to(xla_device, non_blocking=True)
    forces = model(positions)
    cpu_forces = forces.to(cpu_device).numpy()
    structure.positions = update_function(cpu_forces, structure.positions)
```

However, when I do xla multiprocessing on the TPU, somehow the `.to(cpu_device)` call will be extremely slow. The code snippet looks like this:

```
def _map_fn(xla_index):
    xla_device = xm.xla_device()
    for i in range(num_of_step):
        positions = torch.Tensor(structure.positions).to(xla_device, non_blocking=True)
        model_indices = indexing_function(positions, xla_index)
        forces = model(positions, model_indices).detach()
        forces = xm.all_reduce(xm.REDUCE_SUM, forces).detach().clone()
        cpu_forces = forces.to(cpu_device).numpy()
        structure.positions = update_function(cpu_forces, structure.positions)
        xm.rendezvous('sync_step')
xmp.spawn(_map_fn, nprocs=8, start_method='fork')
```

If I were to modify the software to eliminate `.to(cpu_device)` call, I can get this to run fast:
```
def _map_fn(xla_index):
    xla_device = xm.xla_device()
    structure.positions = torch.Tensor(structure.positions).to(xla_device, non_blocking=True)

    for i in range(num_of_step):
        positions = structure.positions.detach().clone()
        model_indices = indexing_function(positions, xla_index)
        forces = model(positions, model_indices).detach()
        forces = xm.all_reduce(xm.REDUCE_SUM, forces).detach().clone()
        structure.positions = update_function(forces, structure.positions).detach().clone()
        xm.rendezvous('sync_step')
xmp.spawn(_map_fn, nprocs=8, start_method='fork')
```

However, the compiler seems to have decided to unfold this code snippet into one giant computation graph to execute at once. So I get a weird behavior... on a standard `structure` size, I can run 16 steps but the code won't run at all if I try to run 17 steps (no error thrown either). If I were to increase the input `structure` size by 2x, the compiler will only allow the code snippet to run & finish 8 steps (but won't start at all if I try to run 9 steps instead). So my suspicion is that this code snippet runs when the compiler can place the entire chain in a single graph in the TPU, despite my best effort to separate the computation graph from the `structure.positions` variable.

Do you have any suggestion on what I should look for? Is `.detach().clone()` the right method to separate the computation graph in pytorch XLA?

**Comment by JackCaoG** [comment]
I think what you are looking for is `xm.mark_step()` (more detail in [here](https://github.com/pytorch/xla/blob/9e9bc80ccf1eaa10668a811b8fdb71d98b67730a/API_GUIDE.md#L103)), `xm.optimizer_step()` will also perform the mark_step() internally.  XLA tensor is lazy and it won't get evaluated until the result of the computation is needed. Converting the result to cpu tensor will force the evaluation (but it will also caused the device to host data transfer which can be slow), `mark_step` is the proper way to perform the `barrier` between each steps. A clean pt/xla mp example can be found in [here](https://github.com/pytorch/xla/blob/master/test/test_train_mp_mnist.py)

**Comment by jpmailoa** [comment]
Thank you for the advice! I have in fact tried inserting `xm.mark_step()` previously, to make the code structure look more or less like this:

```
def _map_fn(xla_index):
    xla_device = xm.xla_device()
    structure.positions = torch.Tensor(structure.positions).to(xla_device, non_blocking=True)

    for i in range(num_of_step):
        positions = structure.positions.detach().clone()
        model_indices = indexing_function(positions, xla_index)
        forces = model(positions, model_indices).detach()
        forces = xm.all_reduce(xm.REDUCE_SUM, forces).detach().clone()
        structure.positions = update_function(forces, structure.positions).detach().clone()
        xm.rendezvous('sync_step')
        xm.mark_step()

xmp.spawn(_map_fn, nprocs=8, start_method='fork')
```

This does not work though, as I kept getting error during runtime (part of it below). It seems to be an out of memory error, which is confusing to me because I intentionally keep the number of step small in this test (2 steps, which should be well below the TPU max capacity, and the snippet normally successfully finishes without the `xm.mark_step()` call). Is this because the `xm.mark_step()` function only meant to work with an optimizer set up? My code is basically inference only, so I have no optimizer object in the runtime.

```
0 successful operations.
0 derived errors ignored.
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 235, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 229, in _start_fn
    fn(gindex, *args)
  File "/home/backup_md_torchlimit/md.py", line 400, in full_md_fn
    md_loop(out_list)
  File "/home/backup_md_torchlimit/md.py", line 330, in md_loop
    self.run_structure_update()             # this calls either the NVE or NVT function
  File "/home/backup_md_torchlimit/md.py", line 309, in NVT_update
    update_structure_force()               # self.structure.forces content is updated using the new self.structure.positions content
  File "/home/backup_md_torchlimit/md.py", line 283, in update_structure_force
    xm.mark_step()
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 575, in mark_step
    wait=xu.getenv_as('XLA_SYNC_WAIT', bool, False))
RuntimeError: Resource exhausted: From /job:tpu_worker/replica:0/task:0:
2 root error(s) found.
  (0) Resource exhausted: Failed to allocate request for 1.0KiB (1024B) on device ordinal 1
         [[{{node XRTExecute}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: Failed to allocate request for 1.0KiB (1024B) on device ordinal 1
         [[{{node XRTExecute}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[XRTExecute_G15]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.
Traceback (most recent call last):
  File "simulate_md.py", line 150, in <module>
    main()
  File "simulate_md.py", line 146, in main
    nprocs=args.coreTPU)
  File "/home/backup_md_torchlimit/md.py", line 416, in run
    xmp.spawn(full_md_fn, nprocs=nprocs, start_method='fork')  #, join=not(self.mock_run))  # weird bug in hardware? Need this
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 300, in spawn
    start_method=start_method)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 113, in join
    (error_index, exitcode)
Exception: process 7 terminated with exit code 17
```

I saw the link you sent with example for xmp test loop inference though. It doesn't seem to be using `xm.mark_step()` either, but instead uses the similar setup to my `.to(cpu_device).numpy()` code snippet above with the `.item()` function call to execute the compute graph and transfer the data to the CPU? If the `.item()` call is significantly faster for XLA multiprocessing, is there an equivalent function I can use for a large tensor array? `.to(cpu_device).numpy()` costs me almost 1 minute per call in XLA multiprocessing somehow (unless I am doing something wrong, as it's quite fast in the single TPU workflow).

**Comment by jpmailoa** [comment]
I just want to follow up a bit:
While `xm.mark_step()` call does not seem to help me and causes runtime error, the `xm.reduce_mesh()` I found in the clean example you pointed out does seem to work faster for me compared to `xm.reduce_all()` followed by `.to(cpu_device).numpy()` call I have been doing, so I might get back to cutting the computation graph by having CPU tensors for `structure.positions` instead similar to my single TPU version.

Now my bottleneck seems to be the compile time though. I have done significant re-coding before to make sure that the graph shapes stay constant across different TPUs and loop iterations in this XLA multiprocessing version (but the actual indices accessed by the model will be changing on each time step). However, I notice that the code still does XrtCompile for each loop step. If I try to re-run over loop steps I have done before, it is fast (it probably hits the previously compiled graph cache). But it slows down once the simulation gets to a step I have never reached before.

I am sure that that tensor sizes are constant everywhere though... Do you have suggestion on how I should go about debugging which steps are causing recompilation on each time step?

**Comment by JackCaoG** [comment]
Could you do a debug run following the instruction in [here](https://github.com/pytorch/xla/blob/master/contrib/colab/issue-report.ipynb) and upload the debugging output? This should tell us how many recompile it happens and how does every graph looks like.

**Comment by jpmailoa** [comment]
[reports.tar.gz](https://github.com/pytorch/xla/files/5258451/reports.tar.gz)

There you go. I've uploaded the report for the first 10 steps fresh (no pre-compile from prior runs, in case that matters). Do note that these are from steps # 0-9 in the simulation step loop. I need to do one model compute (step # -1) before starting the loop to get the simulation code running correctly.

In addition, this parallel version of the TPU code is only meant to work with 8 cores right now (I think I can make it run with single core as mentioned in the debug if needed, but will need to do some additional testing first). 

For the single version TPU code, the report looks much simpler with just 1 XrtCompile accumulated at the end of the run regardless of the # of steps. But the single TPU version already looks like a completely different code base compared to the parallel version, so it's probably irrelevant to compare with.

**Comment by jpmailoa** [comment]
I have followed the instruction for debugging, but need to make 2 adjustments:

1. I cannot do 1 TPU on this parallel xmp version. The parallel version's setup code was custom-made for multiprocessing by splitting/indexing the input data into n(=8) separate pieces, and it is throwing error I will need extended effort to debug to get it to run multiprocessing on 1 core. So the debug files are on 8 TPUs.

2. The runtime code will start throwing error if I use all the debug flags requested in the notebook. It will only run if I use these debug flags instead:
os.environ['XLA_IR_DEBUG'] = '1'
os.environ['XLA_HLO_DEBUG'] = '1'
os.environ['TF_CPP_VMODULE'] = 'tensor=5'
#os.environ['XLA_USE_32BIT_LONG'] = '1'   --> I need to comment out this one, can't run the debug otherwise
os.environ['XLA_SAVE_TENSORS_FILE'] = 'tensors.log'
os.environ['XLA_SAVE_TENSORS_FMT'] = 'text'
os.environ['XLA_TRIM_GRAPH_SIZE'] = '1000000'

I have included tensors & reports for the run with debugging flags set, as well as reports for the run without debugging flags. The run is for 10 steps (# 0-9). I also need to do 1 model function call before the loop (step # -1), so I have included that as well in case it is needed.

Unfortunately the file is too big for github even though it's just 10 steps... Is uploading through this link ok?
https://file.io/bPpNoGhxa3F1

**Comment by JackCaoG** [comment]
@jpmailoa I got a "File.io 404 Page not found" when trying to access the page, could you fix that link?

**Comment by jpmailoa** [comment]
> @jpmailoa I got a "File.io 404 Page not found" when trying to access the page, could you fix that link?

Someone must have downloaded the file... the site seems to be a single-time download kind. Can you try again with this new link?
https://file.io/5Q8rUg1ldaof

**Comment by JackCaoG** [comment]
I think I know what's going on. Since the `mark_step` is not used, the computation attached to the xla tensors never got cleared and the actual graph size keep increasing and changing for every step.  Let me show you with an example

```
>>> import torch, torch_xla
>>> import torch_xla.core.xla_model as xm
>>> device = xm.xla_device()
>>> t1 = torch.randn(2,2, device=device)
>>> t2 = torch.randn(2,2, device=device)
>>> t1
tensor([[ 1.3344,  1.0886],
        [-1.3762,  1.0890]], device='xla:0')
>>> t2
tensor([[-1.6597, -0.9738],
        [ 0.3019,  0.0919]], device='xla:0')
>>> t3 = t1 + t2
>>> t3
tensor([[-0.3253,  0.1148],
        [-1.0743,  1.1809]], device='xla:0')
>>> print(torch_xla._XLAC._get_xla_tensors_text([t1]))
IR {
  %0 = s64[] xla::device_data(), location=<module>@<stdin>:1, device=CPU:0
  %1 = s64[] prim::Constant(), location=<module>@<stdin>:1, value=214013
  %2 = s64[] aten::mul(%1, %0), location=<module>@<stdin>:1
  %3 = s64[] prim::Constant(), location=<module>@<stdin>:1, value=2.53101e+06
  %4 = s64[] aten::add(%3, %2), location=<module>@<stdin>:1
  %5 = f32[] prim::Constant(), location=<module>@<stdin>:1, value=1
  %6 = f32[2,2]{1,0} aten::expand(%5), location=<module>@<stdin>:1, size=(2, 2)
  %7 = f32[] prim::Constant(), location=<module>@<stdin>:1, value=0
  %8 = f32[2,2]{1,0} aten::expand(%7), location=<module>@<stdin>:1, size=(2, 2)
  %9 = f32[2,2]{1,0} aten::normal(%8, %6, %4), location=<module>@<stdin>:1, ROOT=0
}

>>> print(torch_xla._XLAC._get_xla_tensors_text([t2]))
IR {
  %0 = s64[] xla::device_data(), location=<module>@<stdin>:1, device=CPU:0
  %1 = s64[] prim::Constant(), location=<module>@<stdin>:1, value=214013
  %2 = s64[] aten::mul(%1, %0), location=<module>@<stdin>:1
  %3 = s64[] prim::Constant(), location=<module>@<stdin>:1, value=2.53101e+06
  %4 = s64[] aten::add(%3, %2), location=<module>@<stdin>:1
  %5 = s64[] prim::Constant(), location=<module>@<stdin>:1, value=214013
  %6 = s64[] aten::mul(%5, %4), location=<module>@<stdin>:1
  %7 = s64[] prim::Constant(), location=<module>@<stdin>:1, value=2.53101e+06
  %8 = s64[] aten::add(%7, %6), location=<module>@<stdin>:1
  %9 = f32[] prim::Constant(), location=<module>@<stdin>:1, value=1
  %10 = f32[2,2]{1,0} aten::expand(%9), location=<module>@<stdin>:1, size=(2, 2)
  %11 = f32[] prim::Constant(), location=<module>@<stdin>:1, value=0
  %12 = f32[2,2]{1,0} aten::expand(%11), location=<module>@<stdin>:1, size=(2, 2)
  %13 = f32[2,2]{1,0} aten::normal(%12, %10, %8), location=<module>@<stdin>:1, ROOT=0
}

>>> print(torch_xla._XLAC._get_xla_tensors_text([t3]))
IR {
  %0 = f32[] prim::Constant(), location=<module>@<stdin>:1, value=1
  %1 = f32[2,2]{1,0} aten::expand(%0), location=<module>@<stdin>:1, size=(2, 2)
  %2 = s64[] xla::device_data(), location=<module>@<stdin>:1, device=CPU:0
  %3 = s64[] prim::Constant(), location=<module>@<stdin>:1, value=214013
  %4 = s64[] aten::mul(%3, %2), location=<module>@<stdin>:1
  %5 = s64[] prim::Constant(), location=<module>@<stdin>:1, value=2.53101e+06
  %6 = s64[] aten::add(%5, %4), location=<module>@<stdin>:1
  %7 = s64[] prim::Constant(), location=<module>@<stdin>:1, value=214013
  %8 = s64[] aten::mul(%7, %6), location=<module>@<stdin>:1
  %9 = s64[] prim::Constant(), location=<module>@<stdin>:1, value=2.53101e+06
  %10 = s64[] aten::add(%9, %8), location=<module>@<stdin>:1
  %11 = f32[] prim::Constant(), location=<module>@<stdin>:1, value=1
  %12 = f32[2,2]{1,0} aten::expand(%11), location=<module>@<stdin>:1, size=(2, 2)
  %13 = f32[] prim::Constant(), location=<module>@<stdin>:1, value=0
  %14 = f32[2,2]{1,0} aten::expand(%13), location=<module>@<stdin>:1, size=(2, 2)
  %15 = f32[2,2]{1,0} aten::normal(%14, %12, %10), location=<module>@<stdin>:1
  %16 = f32[2,2]{1,0} aten::mul(%15, %1), location=<module>@<stdin>:1
  %17 = f32[] prim::Constant(), location=<module>@<stdin>:1, value=1
  %18 = f32[2,2]{1,0} aten::expand(%17), location=<module>@<stdin>:1, size=(2, 2)
  %19 = f32[] prim::Constant(), location=<module>@<stdin>:1, value=0
  %20 = f32[2,2]{1,0} aten::expand(%19), location=<module>@<stdin>:1, size=(2, 2)
  %21 = f32[2,2]{1,0} aten::normal(%20, %18, %6), location=<module>@<stdin>:1
  %22 = f32[2,2]{1,0} aten::add(%21, %16), location=<module>@<stdin>:1, ROOT=0
}

>>> t1 = t3
>>> print(torch_xla._XLAC._get_xla_tensors_text([t1]))
IR {
  %0 = f32[] prim::Constant(), location=<module>@<stdin>:1, value=1
  %1 = f32[2,2]{1,0} aten::expand(%0), location=<module>@<stdin>:1, size=(2, 2)
  %2 = s64[] xla::device_data(), location=<module>@<stdin>:1, device=CPU:0
  %3 = s64[] prim::Constant(), location=<module>@<stdin>:1, value=214013
  %4 = s64[] aten::mul(%3, %2), location=<module>@<stdin>:1
  %5 = s64[] prim::Constant(), location=<module>@<stdin>:1, value=2.53101e+06
  %6 = s64[] aten::add(%5, %4), location=<module>@<stdin>:1
  %7 = s64[] prim::Constant(), location=<module>@<stdin>:1, value=214013
  %8 = s64[] aten::mul(%7, %6), location=<module>@<stdin>:1
  %9 = s64[] prim::Constant(), location=<module>@<stdin>:1, value=2.53101e+06
  %10 = s64[] aten::add(%9, %8), location=<module>@<stdin>:1
  %11 = f32[] prim::Constant(), location=<module>@<stdin>:1, value=1
  %12 = f32[2,2]{1,0} aten::expand(%11), location=<module>@<stdin>:1, size=(2, 2)
  %13 = f32[] prim::Constant(), location=<module>@<stdin>:1, value=0
  %14 = f32[2,2]{1,0} aten::expand(%13), location=<module>@<stdin>:1, size=(2, 2)
  %15 = f32[2,2]{1,0} aten::normal(%14, %12, %10), location=<module>@<stdin>:1
  %16 = f32[2,2]{1,0} aten::mul(%15, %1), location=<module>@<stdin>:1
  %17 = f32[] prim::Constant(), location=<module>@<stdin>:1, value=1
  %18 = f32[2,2]{1,0} aten::expand(%17), location=<module>@<stdin>:1, size=(2, 2)
  %19 = f32[] prim::Constant(), location=<module>@<stdin>:1, value=0
  %20 = f32[2,2]{1,0} aten::expand(%19), location=<module>@<stdin>:1, size=(2, 2)
  %21 = f32[2,2]{1,0} aten::normal(%20, %18, %6), location=<module>@<stdin>:1
  %22 = f32[2,2]{1,0} aten::add(%21, %16), location=<module>@<stdin>:1, ROOT=0
}

>>> xm.mark_step()
>>> print(torch_xla._XLAC._get_xla_tensors_text([t1]))
IR {
  %0 = f32[2,2]{1,0} xla::device_data(), location=<module>@<stdin>:1, device=CPU:0, ROOT=0
}
```

You see, although `t1`'s value has been updated and it is the same shape, but the graph attached to the `t1` has getting a lot longer in the end. Let's say the above code is for a single step, on step 2 when you perform the same operation to the new `t1`, the graph will be different since the graph attached to the `t1` has been different. The way to avoid this is to call `mark_step` in every step to clear the graph attached to every xla tensor and save the result as a value instead of bunch of computations from the input. If you do a `cpu_tensor.to(xla_device)` again it should have the same effect since now `t1` becomes a new tensor with a new value, but this will cost a `cpu` to `tpu` transfer.

**Comment by jpmailoa** [comment]
Hm.. yes, I can see how it is a problem on tensors chained in a loop. In the numpy version of my code which cuts the graph by converting to CPU tensor, it looks like this though:

```
    constant_tensors = get_preprocessed_xla_tensors()
    variable_tensors = process_numpy_vars(structure).to(xla_device, non_blocking=True)   # structure content is all numpy
    variable_tensors[1].requires_grad = True      # this is x, I need to do this because the model's inference output is F = -dE/dx
    padded_masked_indices = indexing_function(variable_tensors)

    forces_on_1_TPU = model(constant_tensors, variable_tensors)
    reduced_forces_CPU = xm.reduce_mesh( 'somename', forces, lambda x: torch.stack(x).sum(dim=0) )
    structure.forces = reduced_forces_CPU.numpy()
````

Since I have the `xm.reduce_mesh` call there, I think this should qualify as moving to a CPU tensor, which clears the graph right? 

I have tried calling `mark_step` on each loop as you suggested when I was doing the torch version, but it did something weird... the code stops progressing once it reaches the first `mark_step` call. Then it hangs there while trying to sync, before eventually running into an out of memory error. I don't have any optimizer in my code at all, in case that matters (the error message is above, on one of my previous posts). Any thoughts on what might be happening there?

**Comment by JackCaoG** [comment]
I don't think optimizer matters in this case, but I could be wrong. @davidel do you see any high level problems with this inference with `mark_step` approach? @jpmailoa Any chance you can provide a small repo (with fake data and 1core if possible)?

`xla->cpu->xla` will clear the graph, so your numpy version of the code should not recompile.

**Comment by jpmailoa** [comment]
Haha unfortunately since I work for a company instead of a university, I can't just send the code without prior NDA/OSS agreement approved by management... let's not go down that route. =P

Maybe you can give me advice on how to debug this graph stack instead? I notice that in tensors.log.0, cycle #-1 has ~2000 graph line, #0 has ~3000, and it keeps growing at a rate of ~1000 per step. The code does run on `xla->cpu->xla` though, with the `forces` being the only variable connecting one step to the next (which I cut off by doing `forces_xla->forces_cpu->forces_xla`. 

Does it matter that I have the constant preprocessed tensors stored in XLA that I re-use in every cycle? Should I just re-generate them from CPU instead on each step? I thought that since they're leaf constant XLA tensors, it shouldn't matter if they stay in XLA the entire time.

**Comment by jpmailoa** [comment]
I've found the problem! Basically I have a tensor leaking from one cycle to the next, in a way which is mathematically irrelevant but will create a new graph each time. In my `model.py`, since my operation on individual TPUs is sparse due to parallelization, I had created temporary zero buffer for subsequent convenient indexing later on:

```
# this is called once in the beginning, before sending the model to the xla_device
def create_buffer(self,n):
    self.register_buffer('convenient_buffer', torch.zeros(n))
```

During each `model.forward()` call, there is a section in my code which does this:
```
def forward(self, indices, ...):
    buffer = self.convenient_buffer
    buffer[:] = 0.0
    buffer[indices,:] = ....
    out = some_function(buffer)
    return out
```
I did it this way because I feel that passing in the xla_device into the model just so that the model knows how to create the buffer it needs in the right TPU is weird. The model's input should be hardware-independent.

Mathematically this was correct. But on torch XLA, in the beginning of each new compute graph, the `model.convenient_buffer` is still contaminated with a few non-zero tensors from the previous cycle. In the beginning of `model.forward()` they got replaced by a constant (zero), but of course the torch XLA compiler cannot differentiate the intent that when I set constant on the entire content of the buffer, it should just be treated as a new leaf tensor, and hence the graph keeps getting longer on each time step since this chain is cumulative.

So I fix this by modifying it this way instead:
```
def forward(self, indices, ...):
    buffer = self.convenient_buffer.clone()
    buffer[indices,:] = ....
    out = some_function(buffer)
    return out
```
This way, there is no longer any tensor chain connecting one step to the next. My numpy-based code is fast now since I am not seeing recompilation anymore. =)

I'd still be interested in learning how we can use `xm.mark_step()` in a way which does not freeze my code trying to sync, since I think the torch version which minimizes the `.to(cpu_device)` calls will still be the best/fastest. Nevertheless, at least I have a minimum viable product now. =P

**Comment by JackCaoG** [comment]
Great debugging! It is hard to guess what's the cause of the hang without accessing the code. `mark_step` call this cpp function internally 
https://github.com/pytorch/xla/blob/4d755122a502f80b140ca2ef116dd420497e1d1b/torch_xla/csrc/init_python_bindings.cpp#L231
which will collect all live tensors and sync their data (truncate the graph and turn them into device_data). Knowing where the code is stuck and maybe which tensor cause the loop will give some hints to the hanging issue.

**Comment by jpmailoa** [comment]
Thanks for the help so far!

What do you mean by live tensors? All un-evaluated lazy tensors?
And what is device_data actually? I read the documentation and saw mentions of device_data, but can't tell if it is different from XLA tensors? It might help me debug the hanging issue better if I know what they are / where to look at related source code for hints.

**Comment by JackCaoG** [comment]
You can consider every xla tensor that is currently accessible being the live tensor.

In the previous example you see how `t1` has a long graph appending to it? Xla device record the `t1` as a series of computation but after the `mark_step` the t1's graph become
```
  %0 = f32[2,2]{1,0} xla::device_data(), location=<module>@<stdin>:1, device=CPU:0, ROOT=0
```
Device data is just a "data" that xla device can access to during the computation. We also refer this `computation->device_data` process as `materialization/materialized ` of tensors. Another short example

```
>>> import torch,torch_xla
>>> import torch_xla.core.xla_model as xm
>>> t1 = torch.tensor(5, device='xla:0')
>>> t1
tensor(5, device='xla:0')
>>> print(torch_xla._XLAC._get_xla_tensors_text([t1]))
IR {
  %0 = s64[] xla::device_data(), location=<module>@<stdin>:1, device=CPU:0
  %1 = s64[] prim::Constant(), location=<module>@<stdin>:1, value=0
  %2 = s64[] xla::as_strided_view_update(%1, %0), location=__format__@tensor.py:528, size=(), stride=(), storage_offset=0
  %3 = s64[] aten::as_strided(%2), location=_scalar_str@_tensor_str.py:161, size=(), stride=(), storage_offset=0, ROOT=0
}
>>> xm.mark_step()
>>> print(torch_xla._XLAC._get_xla_tensors_text([t1]))
IR {
  %0 = s64[] xla::device_data(), location=<module>@<stdin>:1, device=CPU:0, ROOT=0
}

>>> t2 = t1 * 2
>>> t2
tensor(10, device='xla:0')
>>> print(torch_xla._XLAC._get_xla_tensors_text([t2]))
IR {
  %0 = s64[] xla::device_data(), location=<module>@<stdin>:1, device=CPU:0
  %1 = s64[] xla::device_data(), location=<module>@<stdin>:1, device=CPU:0
  %2 = s64[] aten::mul(%1, %0), location=<module>@<stdin>:1, ROOT=0
}

>>> xm.mark_step()
>>> print(torch_xla._XLAC._get_xla_tensors_text([t2]))
IR {
  %0 = s64[] xla::device_data(), location=<module>@<stdin>:1, device=CPU:0, ROOT=0
}

```

`device_data` is a type of XLATensor. You can play around with different tensors and print their `xla_tensor_text/ir_graph` to explore how does a `xla_graph` looks like and how does them turn into `device_data` after the `mark_step`.

Most of the relevant code is under tensor.cpp
https://github.com/pytorch/xla/blob/b73615c02a9992df31493680bf94a844fd91d78d/torch_xla/csrc/tensor.cpp#L1341

**Comment by jpmailoa** [comment]
Great, thank you! I'll play around with `mark_step` to get better understanding of those.
