### ISSUE TITLE
Crash using XLA GPU

### ISSUE THREAD

**Issue by zcain117** [pytorch/xla#2508]
## 🐛 Bug

I'm trying to use pytorch/xla + GPU. I tried running on 4 GPUs (v100) using:

```
unset XRT_TPU_CONFIG
export GPU_NUM_DEVICES=4
python3 pytorch/xla/test/test_train_mp_imagenet.py \
  ...
```

The test ran 1 epoch of training and 1 eval loop successfully and then fails with:

`Traceback (most recent call last): File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn _start_fn(index, pf_cfg, fn, args) File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn fn(gindex, *args) File "/pytorch/xla/test/test_train_mp_imagenet.py", line 259, in _mp_fn accuracy = train_imagenet() File "/pytorch/xla/test/test_train_mp_imagenet.py", line 246, in train_imagenet write_xla_metrics=True) File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/test/test_utils.py", line 72, in write_to_summary metrics = mcu.parse_metrics_report(met.metrics_report()) File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/debug/metrics.py", line 47, in metrics_report return torch_xla._XLAC._xla_metrics_report() RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:1478 : Check failed: session.Run({result}, &outputs) == ::tensorflow::Status::OK() (Invalid argument: The ClusterSpec names the job and task index to be the same names that were provided when the server booted. This is currently not allowed. Job: localservice, task index: 0 vs. OK)`
 

this was on the latest nightly image

**Comment by zcain117** [comment]
I ran the same code on a machine with 1 GPU instead of 4 GPUs and the error did not happen. 1 GPU case trained successfully for 2 epochs and 2 eval loops.

So this error seems specific the the multi-GPU case

**Comment by zcain117** [comment]
I tried on a GCE VM that has 4 GPUs. I am running using the latest `nightly_3.6_cuda` docker image from pytorch/xla

This version succeeds:
```
GPU_NUM_DEVICES=1 python3 /pytorch/xla/test/test_train_mp_imagenet.py --fake_data --num_epochs=2
```
This version succeeds:
```
GPU_NUM_DEVICES=1 python3 /pytorch/xla/test/test_train_mp_imagenet.py --fake_data --num_epochs=2 --metrics_debug
```
This version succeeds:
```
GPU_NUM_DEVICES=4 python3 /pytorch/xla/test/test_train_mp_imagenet.py --fake_data --num_epochs=2
```
This version crashes:
```
GPU_NUM_DEVICES=4 python3 /pytorch/xla/test/test_train_mp_imagenet.py --fake_data --num_epochs=2 --metrics_debug
```

So the issue is only:
1. when using multiple GPUs
2. when using `--metrics_debug`

**Comment by zcain117** [comment]
confirmed that 2 GPUs has the same crash as 4 GPUs

@will-cromar has seen this error with Tensorflow. He said:

* If you start a TF training server with a name, you can't start a session on that server that has the same name
* In the single-worker case, it works anyway for some reason. I think it's because it doesn't actually start a new session or something like that
* In TPU-world, we start our TPU hosts with the name `tpu_worker`, then start a session with the name `worker` to get around the limitation
* The different named sessions is in the TPU runtime and TPU strategy code in TF
* The low-ish level bindings that control this are https://www.tensorflow.org/api_docs/python/tf/compat/v1/Session and https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/protobuf/config.proto
* You set the task name and number in the tf.ConfigProto and pass it to the tf.Session
* (that's for TF 1. don't know how to control that for TF 2)

@JackCaoG @jysohn23 @davidel does anyone know where we create and/or name TF sessions in pytorch/xla?

**Comment by JackCaoG** [comment]
I think tf session is embeeded in a xrt_session in 
https://github.com/pytorch/xla/blob/035878ba68f824d560cbf2ec54c279c4602a4809/third_party/xla_client/xrt_session.h#L94

The creation and the management of the session is within the `xrt_compuation_client.cc`, it looks like config proto is created via
https://github.com/pytorch/xla/blob/4d755122a502f80b140ca2ef116dd420497e1d1b/third_party/xla_client/xrt_computation_client.cc#L1830

**Comment by zcain117** [comment]
@davidel is `torch_xla._XLAC._xla_metrics_report()` intended to work for XLA GPU? Or is it meant to be only for XLA TPU?

If it's not intended to be used for XLA GPU, I can just disable the metrics report for my GPU training

**Comment by davidel** [comment]
It is supposed to be working.
The issue is here, when we try to connect to "alien" (processes handling other devices) workers to fetch the metrics data:

https://github.com/pytorch/xla/blob/7dfa77fd07a792569985324492c108ea0a2246b6/third_party/xla_client/xrt_computation_client.cc#L1460

And here, when we create the local service for the single devices (within the corresponding processes):

https://github.com/pytorch/xla/blob/4d755122a502f80b140ca2ef116dd420497e1d1b/third_party/xla_client/xrt_computation_client.cc#L1899

It should be sufficient to just change the job name when we create the service.
Let me give it a shot...

PS: This should be reproducible even w/out GPUs. Just use CPU_NUM_DEVICES=4 and a simple MP script that prints metrics.

**Comment by davidel** [comment]
Hmm, CPU works:
```python
import torch
import torch_xla
import torch_xla.core.xla_model as xm
import torch_xla.distributed.xla_multiprocessing as xmp
import torch_xla.debug.metrics as met



def _mp_fn(index):
  device = xm.xla_device()
  tmp = torch.randn(2, 3).to(device)
  tt = tmp + 1.0
  print(tt.cpu())
  
  print(met.metrics_report())
  xm.rendezvous('_mp_fn.exit')


if __name__ == '__main__':
  xmp.spawn(_mp_fn, args=())
```

```shell
TF_CPP_VMODULE=xrt_computation_client=6 CPU_NUM_DEVICES=4 python /tmp/mp_met.py
```


Should be the same as GPU.
@zcain117 since I do not have GPU quota, can you try the above on 4 GPUs?

**Comment by davidel** [comment]
Never mind. CPU does not support the old MT style, so each process is only aware of its local device.

**Comment by zcain117** [comment]
I tried this:
```
TF_CPP_VMODULE=xrt_computation_client=6 GPU_NUM_DEVICES=4 python3 /pytorch/xla/test/test_train_mp_imagenet.py --fake_data --num_epochs=2 --metrics_debug
```

and it had the same crash.

I agree that changing the job name will probably fix the issue. I'm wondering if I can just change [this line](https://github.com/pytorch/xla/blob/4d755122a502f80b140ca2ef116dd420497e1d1b/third_party/xla_client/xrt_computation_client.cc#L1893) to:
```
job_name = absl::StrJoin(worker_target.first.name, "_job");
```

**Comment by davidel** [comment]
@zcain117 You can try that (though "_worker" is a better postfix).

**Comment by zcain117** [comment]
Added the "_worker" suffix [here](https://github.com/pytorch/xla/blob/4d755122a502f80b140ca2ef116dd420497e1d1b/third_party/xla_client/xrt_computation_client.cc#L1893) and now training fails immediately with:

```
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "/pytorch/xla/test/test_train_mp_imagenet.py", line 259, in _mp_fn
    accuracy = train_imagenet()
  File "/pytorch/xla/test/test_train_mp_imagenet.py", line 179, in train_imagenet
    model = get_model_property('model_fn')().to(device)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 612, in to
    return self._apply(convert)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 610, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:383 : Check failed: session->session()->Run( session_work->feed_inputs, session_work->outputs_handles, &outputs) == ::tensorflow::Status::OK() (Invalid argument: Cannot assign a device for operation XRTAllocateFromTensor: {{node XRTAllocateFromTensor}} was explicitly assigned to /job:localservice/replica:0/task:1/device:XLA_GPU:0 but available devices are [ /job:localservice_worker/replica:0/task:0/device:CPU:0, /job:localservice_worker/replica:0/task:0/device:GPU:0, /job:localservice_worker/replica:0/task:0/device:XLA_CPU:0, /job:localservice_worker/replica:0/task:0/device:XLA_GPU:0, /job:localservice_worker/replica:0/task:1/device:CPU:0, /job:localservice_worker/replica:0/task:1/device:GPU:0, /job:localservice_worker/replica:0/task:1/device:XLA_CPU:0, /job:localservice_worker/replica:0/task:1/device:XLA_GPU:0, /job:localservice_worker/replica:0/task:2/device:CPU:0, /job:localservice_worker/replica:0/task:2/device:GPU:0, /job:localservice_worker/replica:0/task:2/device:XLA_CPU:0, /job:localservice_worker/replica:0/task:2/device:XLA_GPU:0, /job:localservice_worker/replica:0/task:3/device:CPU:0, /job:localservice_worker/replica:0/task:3/device:GPU:0, /job:localservice_worker/replica:0/task:3/device:XLA_CPU:0, /job:localservice_worker/replica:0/task:3/device:XLA_GPU:0 ]. Make sure the device specification refers to a valid device.
         [[XRTAllocateFromTensor]] vs. OK)
*** Begin stack trace ***
        tensorflow::CurrentStackTrace()
```

So wherever we "explicitly assigned" the operation to a device, we'd also need to add the same suffix

**Comment by davidel** [comment]
Then we go back to square 1 😄 

The changes are more likely here:

https://github.com/pytorch/xla/blob/7dfa77fd07a792569985324492c108ea0a2246b6/third_party/xla_client/xrt_computation_client.cc#L1460

But the changes, especially in view of 1VM, might be of a different kind.
With a 1VM service-less model, there won't be any TF/Session remote service to ping, so this has to change to only do local "XRT" (or later its replacement) metric query, and client mesh aggregation.

Since rain is slowly creeping in around here 😄 .... I might have more time to follow up.
@zcain117 what is the urgency about this?

**Comment by zcain117** [comment]
I don't think this is very urgent.

I wanted to set up tests for XLA GPU so that we can feel more confident that it's working if any user wants to try it. I think it's fine to wait on this especially if the TF/Session code will change for 1VM.

The workaround is:
1. Skip the `--metrics_debug` flag
2. Skip the `--logdir` flag

I think if we do these 2 things, then training on XLA GPU (single node, so 8 or fewer GPUs) should work for now
