### ISSUE TITLE
Is it possible to request a specific pytorch-nightly build when creating a TPU?

### ISSUE THREAD

**Issue by matt-peters** [pytorch/xla#2513]
Hello,

Is it possible to request the pytorch-nightly build for a specific date when creating a TPU node? I'm running into strange and non-deterministic (and not reproducible) crashes after 1 - 5 hours of training.  I'd like to create a TPU node with a known date/build before the crashes started happening to rule changes in the TPU software causing the issues. Is this possible? If so, how to do it?

Thanks!

**Comment by jysohn23** [comment]
After creating your TPU, you can send the following request from your GCE VM to the TPU's IP to select a specific nightly built at `YYYYMMDD`:

```
$ curl -X POST http://$TPU_IP:8475/requestversion/pytorch-dev$YYYYMMDD
```

Similarly, we have this python API that does the above and is useful especially for pod setups: https://cloud.google.com/tpu/docs/version-switching#additional_software_options

**Comment by matt-peters** [comment]
If I'm using a TPU pod should I issue the `curl` command for each of the IPs in the pod (e.g. for a v3-32, should I send 4 different requests)?

Or if I use the python API, will it automatically send the request to all IPs in the pod?  This seems easier for TPU pods.  How do I specify the TPU pod name to the python API?

**Comment by jysohn23** [comment]
Yes correct. And for the Python API you can just specify it as `tpu=$TPU_NAME` kwarg: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tpu/client/client.py#L129

**Comment by matt-peters** [comment]
Thanks for the quick reply, super helpful!
