### ISSUE TITLE
xm.xla_device() freezes and doesn't show any message

### ISSUE THREAD

**Issue by oriram** [pytorch/xla#2514]
## ❓ Questions and Help
Hi,

I get a recurring issue with xm.xla_device() freezing, even though the TPU_IP_ADDRESS is set.
This happens both in my own code, and in the "pytorch/xla/test/test_train_mp_mnist.py" test script.

In addition, this happens in both images: "nightly_3.7" and "r1.6"

Thanks!

**Comment by zcain117** [comment]
Does this happen every time?

You mentioned `TPU_IP_ADDRESS` but what about `XRT_TPU_CONFIG`? `XRT_TPU_CONFIG` is the one that matters; `TPU_IP_ADDRESS` is not used

Could you give a snippet of the failing code if you set `XRT_TPU_CONFIG` and still see the issue?

**Comment by oriram** [comment]
Hi, thanks for the quick response!
1. Yes it's consistent (and happens across different code bases)
2. The XRT_TPU_CONFIG is set to "tpu_worker;0;$TPU_IP_ADDRESS:8470"
3. It happens with the test script from XLA documentation: pytorch/xla/test/test_train_mp_mnist.py. Alternatively, it also happens when running python and the followeing:

`import torch`
`import torch_xla`
`import torch_xla.core.xla_model as xm`
`device = xm.xla_device()`

**Comment by zcain117** [comment]
You're right - it seems our build broke pretty badly starting on Friday and we're looking into it now.

I just verified this workaround that you can use for now:
1. Make a TPU that uses `pytorch-1.6` TPU software version
2. (on a GCE VM): 
    * `docker run -it --shm-size 16G gcr.io/tpu-pytorch/xla:r1.6`
    * `export TPU_IP_ADDRESS=xx.xx.xx.xxx`
    * `export export XRT_TPU_CONFIG="tpu_worker;0;$TPU_IP_ADDRESS:8470"`
    * `python3 pytorch/xla/test/test_train_mp_mnist.py`

I also verified that `test_train_mp_mnist.py` works with `gcr.io/tpu-pytorch/xla:nightly` but again you'd have to use `pytorch-1.6` TPU software version.

Sorry for the hassle and we will update this issue once we know more

**Comment by oriram** [comment]
Thanks!

**Comment by jysohn23** [comment]
Hey @oriram, if you recreate your TPU today with nightly, you should be able to see that the bug has been resolved. Thanks.
