### ISSUE TITLE
Importing ABC directly from collections has been deprecated and will be removed in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [pytorch/xla#2515]
Use collections in Python 2 and collections.abc in Python 3

https://github.com/pytorch/xla/blob/b918dc4ab40bc3d2cc0c18f743996715f2844a43/scripts/gen.py#L16

**Comment by JackCaoG** [comment]
@zcain117 what's our python3 migration status? Do we still support python2?

**Comment by jysohn23** [comment]
No we don't support python2 and don't even release py2 wheels.

**Comment by JackCaoG** [comment]
I see.. I will go ahead and update the usage of `collections` then.

**Comment by JackCaoG** [comment]
Got sidetracked by other things today. @tirkarthi Thanks for the  reporting the issue. we are happy to take this fixes if want to draft it. Otherwise I will do it.

**Comment by tirkarthi** [comment]
I will raise a PR for this.
