### ISSUE TITLE
Error  with running Transformer on Cloud TPU

### ISSUE THREAD

**Issue by aldazero** [pytorch/xla#2547]
## To Reproduce

1. I followed the steps in this  [tutorial](https://cloud.google.com/tpu/docs/tutorials/transformer-pytorch)
2. When I execute the training command the program throws a very long [output log.](https://gofile.io/d/lVpRoF) 
**3. Here is the begining of error message:**
| epoch 001 | training on xla:0/4:      1 / 4830 loss=15.952, nll_loss=15.963, wps=0, ups=0, wpb=3328.000, bsz=128.000, num_updates=1, lr=2.24975e-07, gnorm=6.436, oom=0.000, wall=103, train_wall=0, now=12:22:19
| epoch 001 | training on xla:0/1:      1 / 4830 loss=15.926, nll_loss=15.935, wps=0, ups=0, wpb=5376.000, bsz=128.000, num_updates=1, lr=2.24975e-07, gnorm=6.436, oom=0.000, wall=101, train_wall=0, now=12:22:19
| epoch 001 | training on xla:0/7:      1 / 4830 loss=16.092, nll_loss=16.120, wps=0, ups=0, wpb=512.000, bsz=128.000, num_updates=1, lr=2.24975e-07, gnorm=6.436, oom=0.000, wall=101, train_wall=0, now=12:22:12
| epoch 001 | training on xla:0/5:      1 / 4830 loss=15.926, nll_loss=15.935, wps=0, ups=0, wpb=3968.000, bsz=128.000, num_updates=1, lr=2.24975e-07, gnorm=6.436, oom=0.000, wall=102, train_wall=0, now=12:22:20
| epoch 001 | training on xla:0/3:      1 / 4830 loss=15.989, nll_loss=16.006, wps=0, ups=0, wpb=1792.000, bsz=128.000, num_updates=1, lr=2.24975e-07, gnorm=6.436, oom=0.000, wall=102, train_wall=0, now=12:22:19
| epoch 001 | training on xla:1/0:      1 / 4830 loss=15.923, nll_loss=15.932, wps=0, ups=0, wpb=4224.000, bsz=128.000, num_updates=1, lr=2.24975e-07, gnorm=6.436, oom=0.000, wall=97, train_wall=0, now=12:22:08
| epoch 001 | training on xla:0/2:      1 / 4830 loss=15.951, nll_loss=15.962, wps=0, ups=0, wpb=1280.000, bsz=128.000, num_updates=1, lr=2.24975e-07, gnorm=6.436, oom=0.000, wall=101, train_wall=0, now=12:22:18
| epoch 001 | training on xla:0/6:      1 / 4830 loss=15.911, nll_loss=15.918, wps=0, ups=0, wpb=6454.000, bsz=128.000, num_updates=1, lr=2.24975e-07, gnorm=6.436, oom=0.000, wall=102, train_wall=0, now=12:22:19
2020-10-12 12:22:21.991122: E    2201 tensorflow/compiler/xla/xla_client/xla_util.cc:76] >>> Dumping Computation 0
2020-10-12 12:22:21.991207: E    2201 tensorflow/compiler/xla/xla_client/xla_util.cc:76] HloModule SyncTensorsGraph.20023, input_output_alias={ {0}: (6, {}, may-alias), {1}: (76, {}, may-alias), {2}: (75, {}, may-alias), {3}: (78, {}, may-alias), {4}: (77, {}, may-alias), {5}: (74, {}, may-alias), {6}: (84, {}, may-alias), {7}: (73, {}, may-alias), {8}: (72, {}, may-alias), {9}: (71, {}, may-alias), {10}: (70, {}, may-alias), {11}: (69, {}, may-alias), {12}: (85, {}, may-alias), {13}: (66, {}, may-alias), {14}: (65, {}, may-alias), {15}: (68, {}, may-alias), {16}: (67, {}, may-alias), {17}: (64, {}, may-alias), {18}: (86, {}, may-alias), {19}: (63, {}, may-alias), {20}: (62, {}, may-alias), {21}: (61, {}, may-alias), {22}: (60, {},

**and the very last lines:**

0 successful operations.
0 derived errors ignored.
/usr/share/torch-xla-1.6/tpu-examples/deps/fairseq/fairseq/optim/adam.py:160: UserWarning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  exp_avg.mul_(beta1).add_(1 - beta1, grad)
/usr/share/torch-xla-1.6/tpu-examples/deps/fairseq/fairseq/optim/adam.py:160: UserWarning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  exp_avg.mul_(beta1).add_(1 - beta1, grad)
/usr/share/torch-xla-1.6/tpu-examples/deps/fairseq/fairseq/optim/adam.py:160: UserWarning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  exp_avg.mul_(beta1).add_(1 - beta1, grad)
/usr/share/torch-xla-1.6/tpu-examples/deps/fairseq/fairseq/optim/adam.py:160: UserWarning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  exp_avg.mul_(beta1).add_(1 - beta1, grad)
Traceback (most recent call last):
  File "/usr/share/torch-xla-1.6/tpu-examples/deps/fairseq/train.py", line 719, in <module>
    cli_main()
  File "/usr/share/torch-xla-1.6/tpu-examples/deps/fairseq/train.py", line 709, in cli_main
    xmp.spawn(_mp_fn, args=(args,), nprocs=args.num_cores)
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 300, in spawn
    start_method=start_method)
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 113, in join
    (error_index, exitcode)
Exception: process 1 terminated with exit code 17

## Expected behavior

running without error
## Environment

 - Reproducible on XLA backend [CPU/TPU]:
 - torch_xla version: torch-xla-1.6

- TPU type : v3-8 
- TPU software version: 2.3.1

**Comment by jysohn23** [comment]
Doesn't seem like the root cause error message is on the stack you posted, but I did notice that you're using a TPU SW version of `2.3.1` while using a VM `torch_xla` version of `1.6`. You want to make sure those match versions, so can you try out again with TPU version of `pytorch-1.6`?

cc: @taylanbil

**Comment by aldazero** [comment]
@jysohn23 Thanks for your help. Yes, the problem rooted in the TPU software version. Setting it to `pytorch-1.6` resolved the issue.
