### ISSUE TITLE
Cannot save model

### ISSUE THREAD

**Issue by ArturTan** [pytorch/xla#2557]
## 🐛 Bug
The following error is thrown during saving - when saving second time the same model to the same file:
`RuntimeError: Tensor ID (140143174649752, 'torch') (torch.int64[]) is sharing a view with tensor ID (140144486972656, 'torch') (torch.int64[])
`

## To Reproduce
During training I am saving the state of model and optimizer each 400 steps: 

```
if step % step_modulo == 0: 
        torch.save({
            'model_state_dict': model.cpu().state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'indices': indices
            }, f"model.pt")
        model.to(dev)
```

## Expected behavior
No error is thrown.

## Environment

 - Reproducible on XLA backend [CPU/TPU]: Google Colab, TPU
 - torch_xla version: 1.6+e788e5b

**Comment by jysohn23** [comment]
Is there a way you could just save the tensors without views? Refer to the https://github.com/pytorch/xla/blob/master/API_GUIDE.md#saving-and-loading-xla-tensors section:
> Per the above note on moving XLA tensors to the CPU, care must be taken when working with views. Instead of saving views it's recommended that you recreate them after the tensors have been loaded and moved to their destination device(s).
