### ISSUE TITLE
Question about using met.metrics_report function

### ISSUE THREAD

**Issue by L4zyy** [pytorch/xla#2566]
## ❓ Questions and Help

Hi,

I am trying to switch my project to run on TPU with pytorch xla. When I tried to analyze the model with met.metrics_report, I got a RuntimeError below. Then I try [this page](https://cloud.google.com/tpu/docs/tutorials/resnet-pytorch) (I found the demo code in that page [here](https://github.com/pytorch/xla/blob/master/test/test_train_imagenet.py)) to setup a vm and test with the demo it provided. When I use --metrics_debug flag to open the metrics_report in that demo, I got the similar RuntimeError. I tried on torch-xla-1.5 and torch-xla-1.6 environment.

```
RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:1482 : Check failed: session.Run({result}, &outputs) == ::tensorflow::Status::OK() (Not found: Op type not registered 'XRTMetricsCollect' in binary running on n-3b120065-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. vs. OK)
*** Begin stack trace ***
	tensorflow::CurrentStackTrace()
	xla::XrtComputationClient::GetMetrics() const
	xla::metrics_reader::CreateMetricReport()


	_PyCFunction_FastCallDict

	_PyEval_EvalFrameDefault


	_PyEval_EvalFrameDefault
	PyEval_EvalCodeEx

	PyObject_Call
	_PyEval_EvalFrameDefault



	_PyEval_EvalFrameDefault


	_PyEval_EvalFrameDefault
	PyEval_EvalCodeEx
	PyEval_EvalCode

	PyRun_FileExFlags
	PyRun_SimpleFileExFlags
	Py_Main
	main
	__libc_start_main

*** End stack trace ***
```

Any ideas or help would be much appreciated! Thanks!

**Comment by jysohn23** [comment]
Sound like the TPU version might be too old compared to the conda environment you're using. Can you make sure to create a TPU with version `pytorch-1.6` if using `torch-xla-1.6`? Or are you already using `pytorch-1.6` TPU version?

**Comment by L4zyy** [comment]
> Sound like the TPU version might be too old compared to the conda environment you're using. Can you make sure to create a TPU with version `pytorch-1.6` if using `torch-xla-1.6`? Or are you already using `pytorch-1.6` TPU version?

I am using TPU v3 and here is the command when I create the TPU:

```
  gcloud compute tpus create tpu-vm \
	      --network=default \
	      --accelerator-type=v3-8 \
              --version=2.1
```

**Comment by jysohn23** [comment]
You want matching TPU version so create the TPU using `--version=pytorch-1.6`.

**Comment by L4zyy** [comment]
> You want matching TPU version so create the TPU using `--version=pytorch-1.6`.

That works for me. Thank you for the help ^ ^
