### ISSUE TITLE
Recommended way to save model and optim, when using multi-core TPUs

### ISSUE THREAD

**Issue by KaleabTessera** [pytorch/xla#2573]
## ❓ Questions and Help

Is there a recommended way to save model and optimizers params when running on a tpu, with multiple cores. 

The [API Guide](https://github.com/pytorch/xla/blob/9e9bc80ccf1eaa10668a811b8fdb71d98b67730a/API_GUIDE.md) mentions that `xm.save(model.state_dict(), path)`, but this "only save[s] the data for the master device ordinal". I want to save the final model, after all weights have been updated. 

My current approach, just hangs for a very long time and nothing happens. 

```
def store_model_information(model, grads, epoch_i, optimizer, config, results_folder, tpu=False):
    print(f'Saving model at epoch {epoch_i}')
    curr_state = {
        'epoch': epoch_i,
        'arch': str(model),
        'state_dict': model.state_dict(),
        'optimizer': optimizer.state_dict(),
        'config': config,
        'grads': grads
    }
    if(tpu is False):
        torch.save(
            curr_state, f'{results_folder}/models/model_{epoch_i}.pth')
    else:
        xm.save(curr_state, f'{results_folder}/models/model_{epoch_i}.pth')

 if(xm.is_master_ordinal()):
          store_model_information(model=model, grads=grads, epoch_i=epoch, optimizer=optimizer, config=config, results_folder=results_folder, tpu=True)
```

Should I be using `xser`?  I know xm.save has master_only param so I don't think `xm.is_master_ordinal()` is nec, but would this cause the lag? Is there a better approach to saving tpu models and optims?

**Comment by taylanbil** [comment]
`xm.save` is fine, but it has a `rendezvous` in there, and if you only call `xm.save` from the master ordinal, then the others will never meet the rendezvous and thus your processes may hang. Solution is, remove the line w/ `if xm.is_mater_ordinal`.

**Comment by KaleabTessera** [comment]
Thanks!
