### ISSUE TITLE
XLA test failures when using int32 indices/offsets for nn.EmbeddingBag

### ISSUE THREAD

**Issue by qizzzh** [pytorch/xla#2575]
## ❓ Questions and Help
Hi! 
I'm trying to enable int32 indices/offsets for nn.EmbeddingBag and hit test failures when backend is XLA while CPU/GPU are fine. Could someone help provide suggestions on how to debug this issue? Much appreciated! 

Pull request - https://github.com/pytorch/pytorch/pull/46758

Test - https://app.circleci.com/pipelines/github/pytorch/pytorch/231535/workflows/0244d1a1-2a86-4d41-b15b-6cc04fc8d8ae/jobs/8487389

**Comment by qizzzh** [comment]
cc @ailzhang

**Comment by JackCaoG** [comment]
It seems like you restarted the xla test, I will take a look when it failed again.

**Comment by qizzzh** [comment]
@JackCaoG  Hey Jack, the tests failed again. Could you help take a look? Thanks!

**Comment by JackCaoG** [comment]
hmm.. I didn't go over your change fully but it seem like embeedingBag will try to access the data pointer during the backward after your change. XLA tensor does not have storage so this will fail. 

What's weird is that it seems like your pr should not have any functional change, but even the non int32 test like `test_EmbeddingBag_per_sample_weights_and_new_offsets_xla_int64_float32` started to fail. Do you have any idea why this might be the case?

**Comment by qizzzh** [comment]
Oh I do have places accessing data pointer - the change to make_offset2bag in EmbeddingBag.cpp

**Comment by qizzzh** [comment]
@JackCaoG do you know how should we proceed here?

**Comment by JackCaoG** [comment]
I think the problem here is that pt/xla does not provide the EmbeddingBag lowering, so the pytorch native implementation is used. However the new change made the native implemantion not longer work for pt/xla. @ailzhang What do you think, I think one thing we could do is disabling all `EmbeddingBagTest` on pt/xla side.

@qizzzh Is there a way to achieve the same functionality without access the data pointer?

**Comment by qizzzh** [comment]
@JackCaoG short term it may not be avoidable. Mid term we will re-enable index operation which could avoid accessing the data pointer.

**Comment by ailzhang** [comment]
I commented on the pytorch PR with suggested fixes. :D

**Comment by qizzzh** [comment]
@ailzhang @JackCaoG I updated the PR to use the original code to avoid data pointer. Now it looks like there's some XLA specific code needs to be updated - https://app.circleci.com/pipelines/github/pytorch/pytorch/232244/workflows/ec5b3889-5895-4d85-867e-cdcfc745a243/jobs/8524503/parallel-runs/0/steps/0-107. Could you help change them to support in32 as well:)
