### ISSUE TITLE
[PT_BREAK] Replace -f with -x for pytest tests.

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/xla#2582]
PR breaking XLA: https://github.com/pytorch/pytorch/pull/46967

**Comment by JackCaoG** [comment]
I encountered similar failure earlier today, I think it is a circleCI glitch. Would you mind rerun the xla test (rerun fix it for me)? I will try to repo it locally and check what went wrong tomorrow.

**Comment by JackCaoG** [comment]
Close this as xla test is passing on the above pr.
