### ISSUE TITLE
Counter: aten::upsample_nearest2d CPU fallback

### ISSUE THREAD

**Issue by vict0rsch** [pytorch/xla#2588]
## 🐛 Bug

according to `metrics_report()` I have an op which falls back to CPU making my inference pipleline super slow. I have seen #1227 and [#1239](https://github.com/pytorch/xla/pull/1239) which allegedly fixes it so I'm kind of stuck here. 

## To Reproduce

```python
import time
from argparse import ArgumentParser

import torch
import torch.nn as nn
import torch_xla.core.xla_model as xm
import torch_xla.debug.metrics as met


class ToyModel(nn.Module):
    def __init__(self, upsample):
        super().__init__()
        self.model = [
            nn.Conv2d(3, 3, 3, 1, 1),
        ]
        if upsample:
            self.model.append(nn.Upsample(scale_factor=2))
        self.model = nn.Sequential(*self.model)

    def forward(self, x):
        return self.model(x)


if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument("--upsample", action="store_true", default=False)
    parser.add_argument("--metrics", action="store_true", default=False)
    parser.add_argument("--mark_step", action="store_true", default=False)
    args = parser.parse_args()

    device = xm.xla_device()
    metrics = args.metrics
    upsample = args.upsample
    mark_step = args.mark_step

    tm = ToyModel(upsample).to(device)
    print(tm)

    x = torch.randn(32, 3, 1024, 1024, device=device)
    print(x.shape, x.device)

    st = time.perf_counter()
    y = tm(x)
    print(
        "Inference duration (upsample:{}): {:.6f}".format(
            upsample, time.perf_counter() - st
        )
    )
    if mark_step:
        xm.mark_step()

    if metrics:
        with open(f"./metrics_{upsample}.txt", "w") as f:
            print(met.metrics_report(), file=f)

```

then 

```
$ python debug_nearest.py --metrics
$ python debug_nearest.py --metrics --upsample
```

In `upsample_true.txt`:

```
Counter: aten::upsample_nearest2d
  Value: 1
```

See attached files for the output of those commands containing the metrics

[upsample_true.txt](https://github.com/pytorch/xla/files/5460238/upsample_true.txt)
[upsample_false.txt](https://github.com/pytorch/xla/files/5460239/upsample_false.txt)

## Environment

 - Reproducible on XLA backend [CPU/TPU]: yes
 - torch_xla version: 1.6
 - torch version: 1.6.0
 - TPU image: torch-xla

**Comment by vict0rsch** [comment]
Behaviour is identical using `nn.UpsamplingNearest2d` and `interpolate()`

**Comment by JackCaoG** [comment]
upsample with `scale_factor  != 1.0`  is not supported on xla yet, the current support way of `upsample` is explictly provide the `output size`. 

@davidel currently we will fallback to cpu if `scale_factor != 1` in 
https://github.com/pytorch/xla/blob/db18ba57137e9e082aab9337e148120ce5725b22/torch_xla/csrc/aten_xla_type.cpp#L3289

I think we can calculate the output size given the `scale_factor` and `input_shape`, it will be a bit ugly but should be doable. What do you think?

**Comment by davidel** [comment]
> upsample with `scale_factor != 1.0` is not supported on xla yet, the current support way of `upsample` is explictly provide the `output size`.
> 
> @davidel currently we will fallback to cpu if `scale_factor != 1` in
> https://github.com/pytorch/xla/blob/db18ba57137e9e082aab9337e148120ce5725b22/torch_xla/csrc/aten_xla_type.cpp#L3289
> 
> I think we can calculate the output size given the `scale_factor` and `input_shape`, it will be a bit ugly but should be doable. What do you think?

The lower level pytorch API feels weird to me, with `output_size` and `scale_factor`.
Can you try to log input and output size, as well as scale factors coming out?
If output size is just input*scale, then yes, we can just do it ourselves.

**Comment by vict0rsch** [comment]
@JackCaoG @davidel thank you for your prompt reaction. Removing `scale_factor` does sole my issue. 

For a drop-in replacement in my situation (2D, nearest) I wrote a simple module

```
class InterpolateNearest2d(nn.Module):
    """
    Custom implementation of nn.Upsample because pytroch/xla
    does not yet support scale_factor and needs to be provided with
    the output_size
    """

    def __init__(self, scale_factor=2):
        """
        Create an InterpolateNearest module

        Args:
            scale_factor (int, optional): Output size multiplier. Defaults to 2.
        """
        super().__init__()
        self.scale_factor = scale_factor

    def forward(self, x):
        """
        Interpolate x in "nearest" mode on its last 2 dimensions

        Args:
            x (torch.Tensor): input to interpolate

        Returns:
            torch.Tensor: upsampled tensor with shape
                (...x.shape, x.shape[-2] * scale_factor, x.shape[-1] * scale_factor)
        """
        return nn.functional.interpolate(
            x,
            size=(x.shape[-2] * self.scale_factor, x.shape[-1] * self.scale_factor),
            mode="nearest",
        )
```

which does not trigger cpu fallback (see metrics attached)

[upsample_custom.txt](https://github.com/pytorch/xla/files/5465628/upsample_custom.txt)

**Comment by davidel** [comment]
Thanks @vict0rsch .
@JackCaoG we probably want to have some handling (after proper checks about the pytorch API) on our side as well, in order to not get caught again with a useless CPU trip.

**Comment by JackCaoG** [comment]
> Thanks @vict0rsch .
> @JackCaoG we probably want to have some handling (after proper checks about the pytorch API) on our side as well, in order to not get caught again with a useless CPU trip.

sounds good, I will work on that.

**Comment by WingsleyLui** [comment]
@davidel @JackCaoG This solution does not work for torch-xla-1.7 but for torch-xla-1.6
