### ISSUE TITLE
[PT_BREAK] XLA test fails on PR

### ISSUE THREAD

**Issue by izdeby** [pytorch/xla#2589]
I have this [PR](https://github.com/pytorch/pytorch/pull/46215)
It [fails](https://app.circleci.com/pipelines/github/pytorch/pytorch/231542/workflows/0fc4525f-9040-4fd6-89de-b1e19530f9b0/jobs/8482714) on XLA on `test_accurracy` test.
Other tests are passing fine. 

Can you, please, help figure it out?

**Comment by JackCaoG** [comment]
Hi @izdeby we started to see this from yesterday and test failed somewhat randomly on circleCI due to accuracy. Could you please rerun the xla test and see if test will pass? I don't think this is related to your change.

**Comment by izdeby** [comment]
@JackCaoG , Yes, it keeps [failing](https://app.circleci.com/pipelines/github/pytorch/pytorch/232837/workflows/45ad590f-b67a-46e5-abd5-b05a67d22fa7/jobs/8562811)

**Comment by JackCaoG** [comment]
I will try to repo on my end
