### ISSUE TITLE
[PT_BREAK] Optimize backward performance of torch.repeat failing for XLA and two other tests.

### ISSUE THREAD

**Issue by ejguan** [pytorch/xla#2599]
PR [#46726](https://github.com/pytorch/pytorch/pull/46726) updates torch.repeat to improve the performance of backward algo.
It has three CI test failed, and all related to `ModuleNotFoundError: No module named 'xmlrunner'` for `test_torch.py`.
1. [pytorch_xla_linux_bionic_py3_6_clang9_test](https://app.circleci.com/pipelines/github/pytorch/pytorch/233391/workflows/ae13cf36-3d5e-47bd-85f7-4bcbe7b97bf3/jobs/8617789) 
2. [pytorch_linux_xenial_py3_6_gcc5_4_jit_legacy_test](https://app.circleci.com/pipelines/github/pytorch/pytorch/233391/workflows/ae13cf36-3d5e-47bd-85f7-4bcbe7b97bf3/jobs/8617142)
3. [pytorch_linux_xenial_py3_6_gcc5_4_test](https://app.circleci.com/pipelines/github/pytorch/pytorch/233391/workflows/ae13cf36-3d5e-47bd-85f7-4bcbe7b97bf3/jobs/8617138)

## Issue description

![image](https://user-images.githubusercontent.com/68879799/97915638-cc143480-1d1f-11eb-8d46-5d0d6531c872.png)

**Comment by ailzhang** [comment]
@ejguan At least the current error message shows the failure is not xla specific. You should probably fix the other two jobs and see if xla is the only failed test after it.

**Comment by ailzhang** [comment]
I'm going to close this issue for now as it's not xla related, but feel free to reopen if it does break xla after your fix. Thanks!
