### ISSUE TITLE
does pytorch xla work on 4x4 TPUs?

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [pytorch/xla#2605]
Hi
I am testing a code on 4x4 TPU getting this error when spawing with 32 cores. thanks 

{
  "textPayload": "Traceback (most recent call last):\n  File \"/root/anaconda3/envs/pytorch/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/root/anaconda3/envs/pytorch/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/workdir/seq2seq/xla_spawn.py\", line 73, in <module>\n    app.run(main, flags_parser=parse_args)\n  File \"/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/absl/app.py\", line 300, in run\n    _run_main(main, args)\n  File \"/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/absl/app.py\", line 251, in _run_main\n    sys.exit(main(argv))\n  File \"/workdir/seq2seq/xla_spawn.py\", line 69, in main\n    xmp.spawn(mod._mp_fn, args=(), nprocs=args.num_cores, start_method='fork')\n  File \"/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py\", line 385, in spawn\n    pf_cfg = _pre_fork_setup(nprocs)\n  File \"/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py\", line 201, in _pre_fork_setup\n    dev_count, num_devices))\nValueError: The number of devices must be either 1 or 8, got 32 instead\n",
  "insertId": "78brgx1r1o91xeh0k",
  "resource": {
    "type": "k8s_container",
    "labels": {
      "cluster_name": "xcloud-euw4a-tpu-v3-2048",
      "container_name": "seq2seq",
      "namespace_name": "ruse-xgcp",
      "project_id": "try-ideas-for-rmi",
      "pod_name": "20201105.wmt512cores32.fcc26.0-dknl5",
      "location": "europe-west4-a"
    }
  },
  "timestamp": "2020-11-05T14:37:39.353577625Z",
  "severity": "ERROR",
  "labels": {
    "k8s-pod/job-name": "20201105.wmt512cores32.fcc26.0",
    "k8s-pod/controller-uid": "4e71eee8-6ea4-40e7-ad21-8efd5ec4842a",
    "k8s-pod/jobowner": "ruse-xgcp",
    "k8s-pod/app": "xcloud",
    "k8s-pod/serviceName": "xc-20201105-wmt512cores32-fcc26-0"
  },
  "logName": "projects/try-ideas-for-rmi/logs/stderr",
  "receiveTimestamp": "2020-11-05T14:38:33.574986665Z"
}

**Comment by jysohn23** [comment]
Yes it does. PyTorch/XLA uses a multi-client setup just like PyTorch. So to use a v3-32 you need to spin up an instance group of 4 VMs to feed the v3-32: https://cloud.google.com/tpu/docs/tutorials/pytorch-pod

It looks like however you're on GKE, where it really isn't as easy to spin up 4 containers for 1 TPU 32 core resource. We have a feature request filed to GKE, but for the time being, for our tests that run on GKE we do something like the following: https://github.com/GoogleCloudPlatform/ml-testing-accelerators/pull/56/files For the time being we recommend you follow our tutorial using GCE as above.

**Comment by rabeehkarimimahabadi** [comment]
Hi
thanks, lets assume I have this TPU pod with v3-32, could you share with me
how I need to change the command, from this command:
So previously I was setting num_cores = 8 now that I have 32 cores, how I
can use all of them?
  xmp.spawn(mod._mp_fn, args=(), nprocs=args.num_cores)
thank you
Best
Rabeeh

**Comment by jysohn23** [comment]
I linked this tutorial in the above comment as well: https://cloud.google.com/tpu/docs/tutorials/pytorch-pod

It should have the answer to those questions.

**Comment by rabeehkarimimahabadi** [comment]
Hi
What I see in tutorial is to call like this: "python -m
torch_xla.distributed.xla_dist \
      --tpu=$TPU_NAME", this is not the way I am looking, in my code I have
this way of using it:

xmp.spawn(mod._mp_fn, args=(), nprocs=args.num_cores)

could you tell me how to modify this format? I do NOT see this in the
tutorial thanks

**Comment by jysohn23** [comment]
Code linked in tutorial: https://github.com/pytorch/xla/blob/master/test/test_train_mp_imagenet.py#L267

You just run the same cmd with `num_cores=8` from each instance in the instance group like in the tutorial. Each instance drives 8 cores, so the tutorial uses the default value scaling up, as one instance driving 8 cores is the same whether you're running on v3-8 or v3-32. The only thing that changes is the number of instances on the GCE VM side.

**Comment by rabeehkarimimahabadi** [comment]
Hi 
thank you. In the examples I see when they set num_cores=8, they also set tpu_num_cores = 8, do I need to set both values as 8 always? thanks

**Comment by jysohn23** [comment]
Would you mind clarifying where you see `tpu_num_cores=8`?

**Comment by rabeehkarimimahabadi** [comment]
Hi Pytorch/Xla,
Yes, I am using GKE. I did not get how to use the changes you mentioned. I
really appreciate assisting me and providing me with more information on
how i can set things up to be able to scale.thansk
Best
Rabeeh

**Comment by rabeehkarimimahabadi** [comment]
Hi
I am still struggling with this. I could make the TPU pod on GKE and have
the address now, based on tutorial I need to pass --tpu address, could you
tell me when I call the codes
as below with spawn where I can add this parameter? thanks

xmp.spawn(mod._mp_fn, args=(), nprocs=args.num_cores)
