### ISSUE TITLE
how to make sure pytorch xla is doing data parallelism

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [pytorch/xla#2606]
Hi
when I call xm.spawn to distribute a work over multiple TPU cores, how can I make sure this is actually working and getting use of all cores? thanks

**Comment by taylanbil** [comment]
there could be several ways; simple ones I can think of are; you could run `pgrep python` and count your processes, or you could print [xm.get_ordinal()](https://github.com/pytorch/xla/blob/master/torch_xla/core/xla_model.py#L161) or `xm.xrt_world_size()`

**Comment by rabeehk** [comment]
thanks.
