### ISSUE TITLE
Pytorch XLA support for RL algorithms on TPU 

### ISSUE THREAD

**Issue by denfromufa** [pytorch/xla#2607]
Is RL supported on Pytorch XLA backend? For example DQN algorithm? I don't see any examples, but not sure if there is anything specific in lazy evaluation that would prevent this implementation? 

cc @ailzhang

**Comment by taylanbil** [comment]
That is currently not an officially supported RL model. I am not aware of an RL model that's been tried on torch_xla so far. As long as the model or training process is not too dynamic, there shouldn't be fundamental limitations that would block the model from working well.

We will consider RL as an option when we look 2 adding to our officially supported models list.

**Comment by jysohn23** [comment]
As far as I know, there isn't really anything that should completely prevent it from running. However, I believe performance could be hurt more in the case of RL, since for each step there will need to be data transfer between the CPU running the environment and device (TPU core) doing the learning.

**Comment by denfromufa** [comment]
@jysohn23 any tips for reducing TPU to CPU transfer bottlenecks in RL? I find that this is the main bottleneck right now, at least in Colab Pro. Are there any specific TPU instances in GCP that have better TPU <-> CPU connectivity?

**Comment by jysohn23** [comment]
If you could somehow make the data transfer asynchronous and continuously send it in the background or something on those lines you could use the `MpDeviceLoader` which is basically a dataloader that overlaps computation with data transfer: 

https://github.com/pytorch/xla/blob/master/torch_xla/distributed/parallel_loader.py#L178-L188

**Comment by jysohn23** [comment]
And no, there's no such thing as TPU instances that have better TPU<>CPU connectivity (at least yet). As long as the CPU and TPU are in the same GCP zone it should be optimal in that respect (which Colab already ensure's they are colocated).

**Comment by denfromufa** [comment]
@jysohn23 just passing one value from TPU tensor to CPU is taking more than 10 seconds in Colab PRO! 
```
result = torch.argmax(action_values)
return result.data.cpu()
```

**Comment by jysohn23** [comment]
That's actually probably not true. Up until `torch.argmax` our LazyTensor runtime is building up an IR graph, which when you call `.cpu()` ends up being truncated, lowered to XLA HLO, and then sent to the TPU for compilation, execution, and retrieval of values. A more accurate way to measure that would be to dump the metrics report and see the TransferFromServer time. Alternatively, you could trigger compilation and execution by running:

```
result = torch.argmax(action_values)
xm.mark_step()  # tells it to compile and execute on TPU
return result.data.cpu()
```

**Comment by denfromufa** [comment]
@jysohn23 this is great to know, the conditional random branching in that section of the code might be triggering recompilation. Let me check!

**Comment by taylanbil** [comment]
marking step using `xm.mark_step()` before every transfer will initially cost you some compilation time, but it will pay off in the long run.

**Comment by denfromufa** [comment]
@taylanbil @jysohn23 you were right, back to the optimizations now! The CPU transfer in that place is still ~30% of time and re-compilation with `xm.mark_step()` is now ~20% of time. What profiler do you use for tracing of XLA lazy execution? I am worried that my line_profiler results are not great.

**Comment by denfromufa** [comment]
The issue is mainly due to communication from TPU node to CPU in user VM in Google Cloud or Colab. Hopefully this can be improved once Pytorch XLA can run on CPU of the TPU node, like JAX and TF.

**Comment by JackCaoG** [comment]
Hi @denfromufa, thanks for the feedback. We are working on enable user to use the TPUVM directly, that should improve the CPU<->TPU data transfer.

**Comment by denfromufa** [comment]
@JackCaoG fyi, I have access to tpuvm directly for JAX, but pytorch xla 1.7 is crashing there.

**Comment by JackCaoG** [comment]
Hi @denfromufa, PT/XLA 1.7 won't work for TPUVM. We are continuing working on this and you should hear more from us in this quarter.
