### ISSUE TITLE
making tpu pod having tpu ids

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [pytorch/xla#2612]
Hi
I want to make a tpu pod, lets assume here are some IP_1, IP_2, ... IP_4 each one one TPU. now could you tell me how to create 

XRT_TPU_CONFIG="tpu_worker;0;$TPU_IP_ADDRESS:8470" 

what is TPU_IP_ADDRESS for muliple TPUs?
thanks

**Comment by jysohn23** [comment]
Can you please checkout this tutorial: https://cloud.google.com/tpu/docs/tutorials/pytorch-pod

In there you can see that you launch a Pod training job with something like:
```
python -m torch_xla.distributed.xla_dist \
      --tpu=$TPU_NAME \
      --conda-env=torch-xla-1.7 \
      --env XLA_USE_BF16=1 \
      --env ANY_OTHER=ENV_VAR \
      -- python /usr/share/torch-xla-1.7/pytorch/xla/test/test_train_mp_imagenet.py \
      --fake_data
```

**Comment by rabeehkarimimahabadi** [comment]
Hi
thanks but this not the response to my question. I can only make a pod with
separate TPU IDs, could you tell me how to make a pod using TPU IDS?

**Comment by rabeehkarimimahabadi** [comment]
in the tutorial you only said make it with google cloud, I cannot do it,
all I can do it to reserve 4 TPUs, and then how can I make a pod?

**Comment by jysohn23** [comment]
A TPU pod is fundamentally different from a cluster of single devices (v2/3-8). TPU pods have high speed interconnects between chips across trays, so it's just a completely different product designed specifically for high scalability. So no, you cannot just "create" a pod with separate TPUs. Check out: https://cloud.google.com/tpu/docs/system-architecture#:~:text=your%20TPU%20nodes.-,TPU%20Pods,all%20of%20the%20TPU%20devices.

If it's a quota issue, submit a quota increase request for the Cloud TPU team to approve.

Also, we do have a SeaOfDevices approach that (more similar to what you describe) has been added at the xla and runtime levels, but the complete support and tooling for it is yet to come.
