### ISSUE TITLE
Distributed sampler for iterable datasets 

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [pytorch/xla#2615]
Hi
I have some large-scale TFDS datasets, and I would need to use them with pytorch XLA, and write some distributed sampler for them.Could you provide me with examples on how I can write distributed data samplers for iterable datastes for TPUs? 
thanks.
Best
Rabeeh

**Comment by rabeehkarimimahabadi** [comment]
In non-iterative datasets, one can implement sampler for distributed training over TPUs as below:

```
def get_tpu_sampler(dataset: torch.utils.data.dataset.Dataset):
    if xm.xrt_world_size() <= 1:
        return RandomSampler(dataset)
    return DistributedSampler(dataset, num_replicas=xm.xrt_world_size(), rank=xm.get_ordinal())
```

When having iterative datasets, could you please provide me with examples how to use them with Pytorch XLA efficiently? thanks

**Comment by taylanbil** [comment]
There should not be anything specific to torch_xla when sampling your data. You could sample it as you wish, same way you do on other platforms.

**Comment by rabeehkarimimahabadi** [comment]
Hi
iterative datasets are NOT samplable, so one cannot sample then and I am
not sure how to handle this when it comes to make the model train in
distributed fashion with pytorch XLA. thanks

**Comment by taylanbil** [comment]
This is not a `torch_xla` question really. One thing you could do is, instead of sampling, you could define something like this:

```
1. a generator that loads the GLOBAL batch size
2. according to world size and ordinal, get the slice (in batch dimension) that belongs to this ordinal.
3. do the rest of model, optimizer, etc.
```

**Comment by rabeehkarimimahabadi** [comment]
Hi Tylan,
thank you very much for the info, I got your suggestion, when one trains on
TPU pods, meaning that there are multiple hosts and each host has multiple
devices, could you tell me how data sharding should be handled in this
case? So here is some info:

xm.xrt_world_size() retrieves the number of devices that are taking part in
the replication. (basically the number of cores)
xm.get_ordinal() retrieves the replication ordinal of the current process.
The ordinals range from 0 to xrt_world_size()-1

When we have one host, this is clear to me, but when we have multiple
hosts, could you tell me how I can get host_id and how the dividing of the
data should be?
Does in multiple host case, xrt_world_size shows the total number of cores
across all devices?
thanks for the help.
Best
Rabeeh

**Comment by taylanbil** [comment]
> Does in multiple host case, xrt_world_size shows the total number of cores
across all devices?
Yes, so you could divide using xrt_world_size, and xm_get_ordinal, exactly the same.

**Comment by rabeehkarimimahabadi** [comment]
Hi Tylan,
thank you so much for the reply, so just to iterate to make sure I
understood you correctly, there is no notion of host in pytorch XLA like in
JAX, and one would code everything based on total number of cores. could
you please confirm it?
thanks for all helps.
Best
Rabeeh

**Comment by jysohn23** [comment]
Yes, JAX's paradigm looks a bit different where they only have one client/controller per 8 cores/host, but for us its per-core from the get go.

**Comment by taylanbil** [comment]
Thanks @rabeehkarimimahabadi, closing this issue nowm as it seems to be resolved.

**Comment by rabeehkarimimahabadi** [comment]
thank you both, this was very helpful.
