### ISSUE TITLE
[PT_BREAK] Fixed torch.kthvalue to allow scalar inputs on CUDA

### ISSUE THREAD

**Issue by heitorschueroff** [pytorch/xla#2620]
PR https://github.com/pytorch/pytorch/pull/47600 updated torch.kthvalue to allow scalar inputs on CUDA. It was already allowed on the CPU.

**Comment by JackCaoG** [comment]
@heitorschueroff Thanks for the reporting! I might miss the email but I always check the github issue. Could you give us a heads up before merging the change next time 😄 , so we can at least disable the test.

**Comment by heitorschueroff** [comment]
> @heitorschueroff Thanks for the reporting! I might miss the email but I always check the github issue. Could you give us a heads up before merging the change next time 😄 , so we can at least disable the test.

Yes! I'm sorry, I believe this is the second PR I merged before XLA but it won't happen again. Thanks for being understanding.

**Comment by JackCaoG** [comment]
We had https://github.com/pytorch/xla/issues/1958 open to track scalar input for many ops (including kthvalue), the conclusion at that time is that this will make our common case slower and make code a lot more messer. We will come back to this issue if there is a customer request. 

@heitorschueroff I am wondering if it is possible to put the scalar case into a separate test? This way we can still test the non-scalar cases.

**Comment by heitorschueroff** [comment]
> We had #1958 open to track scalar input for many ops (including kthvalue), the conclusion at that time is that this will make our common case slower and make code a lot more messer. We will come back to this issue if there is a customer request.
> 
> @heitorschueroff I am wondering if it is possible to put the scalar case into a separate test? This way we can still test the non-scalar cases.

I can move the scalar test in test_torch.py to a separate method. Is the scalar case in common_methods_invocation fine however?

**Comment by JackCaoG** [comment]
@heitorschueroff `common_methods_invocation ` should be fine, `test_kthvalue_xla` is the only test that failed on xla by this change.
