### ISSUE TITLE
[PT_BREAK] Narrow Device to 2 bytes by narrowing DeviceType and DeviceIndex

### ISSUE THREAD

**Issue by swolchok** [pytorch/xla#2623]
I am creating this issue following the directions on the CI failure.
PyTorch PR: https://github.com/pytorch/pytorch/pull/47023
Direct link to test failure: https://app.circleci.com/pipelines/github/pytorch/pytorch/237622/workflows/5f7d287e-6327-4291-a358-08b49e009a8e/jobs/8842244

The PR changes the size of DeviceIndex, which threw off some tests in the PyTorch repo that used unrealistically large device numbers. Presumably there's something similar in pytorch/xla.

**Comment by JackCaoG** [comment]
Sorry, the test failure is unrelated, I am landing a pr to disable that test right now. Thanks for the reporting!

**Comment by JackCaoG** [comment]
@swolchok Just merged https://github.com/pytorch/xla/pull/2624, @swolchok do you might rerun the xla test? Thanks!

**Comment by JackCaoG** [comment]
Close this as xla test is passing on the above pr.
