### ISSUE TITLE
Transformer on TPU 

### ISSUE THREAD

**Issue by FabianBell** [pytorch/xla#2627]
## ❓ Questions and Help
I tried to run a transformer model for sentiment analysis on a colab tpu. For training I followed this [notebook](https://colab.research.google.com/github/pytorch/xla/blob/master/contrib/colab/multi-core-alexnet-fashion-mnist.ipynb). I saw #2120 and used 
```python
os.environ['XLA_USE_32BIT_LONG'] = '1'
os.environ['XLA_USE_BF16'] = '1'
os.environ['TRIM_GRAPH_SIZE'] = '1000000'
```
You can find my code in this [notebook](https://colab.research.google.com/drive/1mmTPCQAMsHVrw7_-cFS37JEguLzAjzRA?usp=sharing).
When I run it I get `ProcessExitedException: process X terminated with signal SIGSEGV`. What did I do wrong?

**Comment by zcain117** [comment]
Tried running the code in a GCP VM and I also see an error:
```
xception in device=TPU:3: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:245 : Check failed: default_device_target != options_.global_device_map.end() 
*** Begin stack trace ***
        tensorflow::CurrentStackTrace()
        xla::XrtComputationClient::XrtComputationClient(xla::XrtComputationClient::Options, std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
        xla::ComputationClient::Create()


        xla::ComputationClient::Get()


        _PyCFunction_FastCallDict

        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault
        PyEval_EvalCodeEx

        PyObject_Call

        _PyObject_GenericGetAttrWithDict
        _PyEval_EvalFrameDefault
        _PyEval_EvalFrameDefault
        PyEval_EvalCodeEx
        PyEval_EvalCode

        PyRun_FileExFlags
        PyRun_SimpleFileExFlags
        Py_Main
        main
        __libc_start_main

*** End stack trace ***
```

Not sure yet how to fix this kind of `Check failed: default_device_target != options_.global_device_map.end()` error

Do you get the same outcome with our stable versions:

- `!pip install cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.7-cp36-cp36m-linux_x86_64.whl`
- `!pip install cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.6-cp36-cp36m-linux_x86_64.whl`?

**Comment by FabianBell** [comment]
@zcain117 thank you for your fast response. I cannot reproduce your error on google colab. 
When I run it with `!pip install cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.7-cp36-cp36m-linux_x86_64.whl` I get 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "<ipython-input-7-e47be2a8af9f>", line 39, in map_fn
    out = model(**batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<ipython-input-6-60e7d15f9a78>", line 13, in forward
    return self.model(**inp)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_reformer.py", line 2429, in forward
    return_dict=return_dict,
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_reformer.py", line 2090, in forward
    start_idx_pos_encodings=start_idx_pos_encodings,
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_reformer.py", line 252, in forward
    inputs_embeds = self.word_embeddings(input_ids)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/sparse.py", line 126, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1852, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got XLAIntType instead (while checking arguments for embedding)
```
When I run it with `!pip install cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.6-cp36-cp36m-linux_x86_64.whl` I get
```
ImportError                               Traceback (most recent call last)
<ipython-input-4-7fe098b5b807> in <module>()
----> 1 import torch_xla

/usr/local/lib/python3.6/dist-packages/torch_xla/__init__.py in <module>()
    103 import torch
    104 from ._patched_functions import _apply_patches
--> 105 import _XLAC
    106 
    107 

ImportError: /usr/local/lib/python3.6/dist-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19slow_conv_dilated3dERKNS_6TensorES2_N3c108ArrayRefIlEES2_S5_S5_S5_
```
I updated the notebook for reproduction.

**Comment by zcain117** [comment]
For the error using `torch_xla-1.6`, I think it's because you'd also need to `pip uninstall torch` and `pip install torch==1.6.0` since the default colab version right now is 1.7.0, which is not compatible with our 1.6 wheels. But I don't know if you necessarily need to use the 1.6 version if we can get the 1.7 version working.

Looks like the new error is about `torch.embedding`. I'm not super familiar but we do have an example Colab [here](https://github.com/pytorch/xla/blob/master/contrib/colab/Distributing_Large_Embedding_tables.ipynb) that shows use of embedding tables. It uses `torch.nn.embedding` instead of `torch.embedding`

Maybe @taylanbil can advise on whether we would expect `torch.embedding` to work with PyTorch/XLA

**Comment by FabianBell** [comment]
The model I am using uses `torch.nn.Embedding` as you can see [here](https://github.com/huggingface/transformers/blob/24184e73c441397edd51e9068e0f49c0418d25ab/src/transformers/modeling_reformer.py#L231). The `torch.nn.Embedding` layer uses `torch.embedding` internally as you can see [here](https://github.com/pytorch/pytorch/blob/013e6a3d9d0d3ebe8283bf9af0f3b666ba4d96b7/torch/nn/modules/sparse.py#L145). I created a modified version of my notebook with a very simple model and I still get the same error. You can find my notebook [here](https://colab.research.google.com/drive/1AYSgGnDEW0ghFTggBpKgj9JgD1Mn_uHy?usp=sharing)

**Comment by taylanbil** [comment]
I tried to reproduce this on torch_xla version 1.7, it works for me (after removing `.mean(-1)` in `forward` which messes up dimensions)

**Comment by taylanbil** [comment]
also works in 1.6 for me.

**Comment by FabianBell** [comment]
@taylanbil thank you for your help. Where can I find a list of operations that I am allowed/ not allowed to use when I want to work with TPUs?

**Comment by taylanbil** [comment]
I am not aware of a list, but we certainly do aim for almost everything to work on TPUs/XLA. Transformer and related models are well tested, so I don't think there should be any worries of missing operations in those.

Does the issue still persist for you? I cannot reproduce this issue, the code works fine for me.

**Comment by FabianBell** [comment]
If you run this [notebook](https://colab.research.google.com/drive/1mmTPCQAMsHVrw7_-cFS37JEguLzAjzRA#scrollTo=n3NtcfVOjaHr) you do not get the following?
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "<ipython-input-7-daa8dec4c153>", line 39, in map_fn
    out = model(**batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "<ipython-input-6-fd044100a2c0>", line 9, in forward
    return self.model(**inp)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_bert.py", line 1361, in forward
    return_dict=return_dict,
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_bert.py", line 838, in forward
    input_ids=input_ids, position_ids=position_ids, token_type_ids=token_type_ids, inputs_embeds=inputs_embeds
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_bert.py", line 197, in forward
    inputs_embeds = self.word_embeddings(input_ids)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/sparse.py", line 126, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1852, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got XLAIntType instead (while checking arguments for embedding)
```
I use the BERT implementation of [hugging face](https://huggingface.co/transformers/model_doc/bert.html).

**Comment by taylanbil** [comment]
hmm interesting, I do get the error on colab, but not on my vm.

**Comment by taylanbil** [comment]
Oh, you're setting `os.environ['XLA_USE_32BIT_LONG'] = '1'`. Remove that and it should work. Any reason to set that env variable?

**Comment by FabianBell** [comment]
Thank you for your help. It works with BERT now. Before I tried BERT I tried the Reformer model from [hugging face](https://huggingface.co/transformers/model_doc/reformer.html#reformermodel) on TPU since TPU training is specifically mentioned in the [reformer paper](https://arxiv.org/pdf/2001.04451.pdf). When I remove that env variable I get
```
File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/parallel_loader.py", line 37, in next
    xm.mark_step()
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 716, in mark_step
    wait=xu.getenv_as('XLA_SYNC_WAIT', bool, False))
RuntimeError: Unimplemented: From /job:tpu_worker/replica:0/task:0:
2 root error(s) found.
  (0) Unimplemented: While rewriting computation to not contain X64 element types, XLA encountered an HLO for which this rewriting is not implemented: %sort.2140 = (s64[1,2,1024]{2,1,0}, s32[1,2,1024]{2,1,0}) sort(s64[1,2,1024]{2,1,0} %add.2129, s32[1,2,1024]{2,1,0} %iota.2130), dimensions={2}, to_apply=%compare-less-than.2131
	 [[{{node XRTCompile}}]]
  (1) Unimplemented: While rewriting computation to not contain X64 element types, XLA encountered an HLO for which this rewriting is not implemented: %sort.2140 = (s64[1,2,1024]{2,1,0}, s32[1,2,1024]{2,1,0}) sort(s64[1,2,1024]{2,1,0} %add.2129, s32[1,2,1024]{2,1,0} %iota.2130), dimensions={2}, to_apply=%compare-less-than.2131
	 [[{{node XRTCompile}}]]
	 [[XRTCompile_G6]]
0 successful operations.
0 derived errors ignored.
```
which looked even more wrong to me than the previous error. I modified the [notebook](https://colab.research.google.com/drive/1mmTPCQAMsHVrw7_-cFS37JEguLzAjzRA#scrollTo=n3NtcfVOjaHr) for reproduction.

**Comment by JackCaoG** [comment]
The problem is 
`%sort.2140 = (s64[1,2,1024]{2,1,0}, s32[1,2,1024]{2,1,0}) sort(s64[1,2,1024]{2,1,0} %add.2129, s32[1,2,1024]{2,1,0} %iota.2130), dimensions={2}, to_apply=%compare-less-than.2131`

the `sort` hlo does not support s64 type so it failed to compile.

**Comment by FabianBell** [comment]
I assume that means that the Reformer model from hugging face is currently not supported. Since this was a question I will close this issue. Thank you for your help.
