### ISSUE TITLE
Ran out of memory in memory space `smem`

### ISSUE THREAD

**Issue by phtephanx** [pytorch/xla#2628]
## 🐛 Bug

Multiprocess-training on 8 TPU cores crashes after 2 iterations with ...
```
(0) Resource exhausted: Ran out of memory in memory space smem. It should not be possible to run out of smem - please file a bug against XLA.
```

## To Reproduce

I compiled a [debug.run.tar.gz](https://www.dropbox.com/s/mi0f2031x44zdfw/debug_run.tar.gz?dl=0) following the guidelines.
Apart from that, in this [colab](https://colab.research.google.com/drive/1LclO69NVPBOO4hzWtW8uIjaTgVCR-MDv?usp=sharing) I minimalistically put together the relevant steps of training even though I cannot ensure that this will reproduce the error.

## Environment

 - XLA backend: TPU v3.8
 - `torch_xla==1.6`
- `torch==1.6`

**Comment by taylanbil** [comment]
How many layers does this model have?

**Comment by phtephanx** [comment]
It‘s BART-large with 12 layers in the encoder and another 12 layers in the decoder.

**Comment by taylanbil** [comment]
I wasn't able to reproduce using the colab, my run crashes w/

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/distributed/parallel_loader.py", line 172, in _worker
    batch = xm.send_cpu_data_to_device(batch, device)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 847, in send_cpu_data_to_device
    return ToXlaTensorArena(convert_fn, select_fn).transform(data)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 410, in transform
    self._convert()
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 382, in _convert
    self._converted_tensors = self._convert_fn(self._tensors)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 842, in convert_fn
    return torch_xla._XLAC._xla_tensors_from_aten(tensors, devices)
RuntimeError: torch_xla/csrc/aten_xla_bridge.cpp:227 : Check failed: device.type() == at::kXLA (cpu vs. xla)
```

Could you refresh repro instructions so we can file a bug to xla?

**Comment by phtephanx** [comment]
Fixed it. Unfortunately, the code runs successfully on colab.

With my setup on GC's VM I could produce the `smem` error twice. What strikes me, is that on colab the training reaches pace after few seconds while on my VM it takes over 1h for the model to be copied over and the graph to be stabilized. What could be the reason for this? The training on this VM works in principle since I was able to train BART-base (6 layers each) on a different dataset.

By the way, what does `smem` mean? I couldn't find anything.

**Comment by taylanbil** [comment]
So your code runs on colab, but fails on VM. What are the specs of your vm? what version of torch_xla/tpu combination are you using on GCE?

**Comment by phtephanx** [comment]
**specs:** VM: N1, 12vCPU, 300GB RAM (that huge for testing purposes) \
I tracked host memory usage, it leveled off at 250GB (high but the process didn't, at least, ran out of memory)
**versions/types:** `torch_xla==1.6`, TPU v3.8

**Comment by taylanbil** [comment]
* [here](https://cacm.acm.org/magazines/2020/7/245702-a-domain-specific-supercomputer-for-training-deep-neural-networks/fulltext) is an article where you can find more info on things like smem, etc.
* re: model copying in 1 hour on GCE but not on colab; this should never happen. Are your tpus and vm in the same region/zone? This does not happen normally.
* re: version; could you try on your vm w/ 1.7 torch_xla **and** tpu?

**Comment by phtephanx** [comment]
Thanks for the article! Yes, VM, TPU and Storage, all in `europe-west4-a`. Yes, will try `torch==1.7`, `torch_xla==1.7` with TPU soon and come back here!

**Comment by taylanbil** [comment]
@phtephanx any updates? is this issue good to close?

**Comment by phtephanx** [comment]
Sorry for late response. The problem didn't occur with `1.7` anymore ceteris paribus. However, I ran again into really slow performance even if the shape of all inputs is constant: ~60[s] for 1 training step.

 Feel free to close since this is a different issue.

**Comment by taylanbil** [comment]
sounds good, please refer to our [troubleshooting](https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md) doc to debug slowness.
