### ISSUE TITLE
Exception in device=TPU:5: torch_xla/csrc/tensor_methods.cpp:858 : Check failed: xla::ShapeUtil::Compatible(shapes.back(), tensor_shape) 

### ISSUE THREAD

**Issue by rabeehk** [pytorch/xla#2632]
Hi
I am getting this stack error, when trying to concat two matrices 
 hidden_states = torch.cat((projection_hidden_states, hidden_states), dim=1)

the code works fine on GPUs, fails with these error on TPUs, thank you. 

11/17/2020 17:40:57 - INFO - filelock -   Lock 140696623058504 released on /root/.cache/huggingface/datasets/6264f08d89d6f9c36fc24be56a15dba71c8c86b628ef529ab8a87c867b38e98b.65c743c856669ab431cd2ebf50ced5f0805430a413142f650fe5ae89cfd68acd.py.lock
11/17/2020 17:40:57 - INFO - filelock -   Lock 140698524736648 acquired on /root/.cache/huggingface/datasets/_root_.cache_huggingface_datasets_scitail_snli_format_1.1.0_fd8ccdfc3134ce86eb4ef10ba7f21ee2a125c946e26bb1dd3625fe74f48d3b90.lock
11/17/2020 17:40:57 - INFO - filelock -   Lock 140698524736648 released on /root/.cache/huggingface/datasets/_root_.cache_huggingface_datasets_scitail_snli_format_1.1.0_fd8ccdfc3134ce86eb4ef10ba7f21ee2a125c946e26bb1dd3625fe74f48d3b90.lock
11/17/2020 17:40:57 - INFO - filelock -   Lock 140696622932320 acquired on /root/.cache/huggingface/datasets/_root_.cache_huggingface_datasets_scitail_snli_format_1.1.0_fd8ccdfc3134ce86eb4ef10ba7f21ee2a125c946e26bb1dd3625fe74f48d3b90.lock
Reusing dataset scitail (/root/.cache/huggingface/datasets/scitail/snli_format/1.1.0/fd8ccdfc3134ce86eb4ef10ba7f21ee2a125c946e26bb1dd3625fe74f48d3b90)
11/17/2020 17:40:57 - INFO - filelock -   Lock 140696622932320 released on /root/.cache/huggingface/datasets/_root_.cache_huggingface_datasets_scitail_snli_format_1.1.0_fd8ccdfc3134ce86eb4ef10ba7f21ee2a125c946e26bb1dd3625fe74f48d3b90.lock
Loading cached processed dataset at /root/.cache/huggingface/datasets/scitail/snli_format/1.1.0/fd8ccdfc3134ce86eb4ef10ba7f21ee2a125c946e26bb1dd3625fe74f48d3b90/cache-f8b21e4dbe7c62d8.arrow
11/17/2020 17:40:57 - INFO - filelock -   Lock 139950977155024 acquired on /root/.cache/huggingface/datasets/6264f08d89d6f9c36fc24be56a15dba71c8c86b628ef529ab8a87c867b38e98b.65c743c856669ab431cd2ebf50ced5f0805430a413142f650fe5ae89cfd68acd.py.lock
11/17/2020 17:40:57 - INFO - filelock -   Lock 139950977155024 released on /root/.cache/huggingface/datasets/6264f08d89d6f9c36fc24be56a15dba71c8c86b628ef529ab8a87c867b38e98b.65c743c856669ab431cd2ebf50ced5f0805430a413142f650fe5ae89cfd68acd.py.lock
11/17/2020 17:40:57 - INFO - filelock -   Lock 139952912559016 acquired on /root/.cache/huggingface/datasets/_root_.cache_huggingface_datasets_scitail_snli_format_1.1.0_fd8ccdfc3134ce86eb4ef10ba7f21ee2a125c946e26bb1dd3625fe74f48d3b90.lock
11/17/2020 17:40:57 - INFO - filelock -   Lock 139952912559016 released on /root/.cache/huggingface/datasets/_root_.cache_huggingface_datasets_scitail_snli_format_1.1.0_fd8ccdfc3134ce86eb4ef10ba7f21ee2a125c946e26bb1dd3625fe74f48d3b90.lock
11/17/2020 17:40:57 - INFO - filelock -   Lock 139950977188248 acquired on /root/.cache/huggingface/datasets/_root_.cache_huggingface_datasets_scitail_snli_format_1.1.0_fd8ccdfc3134ce86eb4ef10ba7f21ee2a125c946e26bb1dd3625fe74f48d3b90.lock
Reusing dataset scitail (/root/.cache/huggingface/datasets/scitail/snli_format/1.1.0/fd8ccdfc3134ce86eb4ef10ba7f21ee2a125c946e26bb1dd3625fe74f48d3b90)
11/17/2020 17:40:57 - INFO - filelock -   Lock 139950977188248 released on /root/.cache/huggingface/datasets/_root_.cache_huggingface_datasets_scitail_snli_format_1.1.0_fd8ccdfc3134ce86eb4ef10ba7f21ee2a125c946e26bb1dd3625fe74f48d3b90.lock
Loading cached processed dataset at /root/.cache/huggingface/datasets/scitail/snli_format/1.1.0/fd8ccdfc3134ce86eb4ef10ba7f21ee2a125c946e26bb1dd3625fe74f48d3b90/cache-f8b21e4dbe7c62d8.arrow
Some weights of T5ForConditionalGeneration were not initialized from the model checkpoint at t5-base and are newly initialized: ['encoder.encoder_pooler.query', 'encoder.encoder_pooler.key.weight', 'encoder.encoder_pooler.key.bias', 'encoder.encoder_pooler.value.weight', 'encoder.encoder_pooler.value.bias', 'encoder.encoder_projection.mlp.0.weight', 'encoder.encoder_projection.mlp.0.bias', 'encoder.encoder_projection.mlp.2.weight', 'encoder.encoder_projection.mlp.2.bias', 'encoder.encoder_projection.mlp.4.weight', 'encoder.encoder_projection.mlp.4.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
11/17/2020 17:40:58 - INFO - filelock -   Lock 140177000533632 acquired on /root/.cache/huggingface/datasets/789aac774d2bf75a9745b317dcb7b382aae068999400d5ce515dc3bc89fbbec7.1df81a1be4b8a929a8fa6f7913847f200a3f43753b08afc36a38bf135acae695.py.lock
11/17/2020 17:40:58 - INFO - filelock -   Lock 140177000533632 released on /root/.cache/huggingface/datasets/789aac774d2bf75a9745b317dcb7b382aae068999400d5ce515dc3bc89fbbec7.1df81a1be4b8a929a8fa6f7913847f200a3f43753b08afc36a38bf135acae695.py.lock
Using custom data configuration default
11/17/2020 17:40:58 - INFO - filelock -   Lock 140178927453464 acquired on /root/.cache/huggingface/datasets/_root_.cache_huggingface_datasets_boolq_default_0.1.0_2987db1f15deaa19500ae24de560eabeaf1f8ef51df88c0470beeec72943bf11.lock
11/17/2020 17:40:58 - INFO - filelock -   Lock 140178927453464 released on /root/.cache/huggingface/datasets/_root_.cache_huggingface_datasets_boolq_default_0.1.0_2987db1f15deaa19500ae24de560eabeaf1f8ef51df88c0470beeec72943bf11.lock
11/17/2020 17:40:58 - INFO - filelock -   Lock 140178927453128 acquired on /root/.cache/huggingface/datasets/_root_.cache_huggingface_datasets_boolq_default_0.1.0_2987db1f15deaa19500ae24de560eabeaf1f8ef51df88c0470beeec72943bf11.lock
Reusing dataset boolq (/root/.cache/huggingface/datasets/boolq/default/0.1.0/2987db1f15deaa19500ae24de560eabeaf1f8ef51df88c0470beeec72943bf11)
11/17/2020 17:40:58 - INFO - filelock -   Lock 140178927453128 released on /root/.cache/huggingface/datasets/_root_.cache_huggingface_datasets_boolq_default_0.1.0_2987db1f15deaa19500ae24de560eabeaf1f8ef51df88c0470beeec72943bf11.lock
Loading cached processed dataset at /root/.cache/huggingface/datasets/boolq/default/0.1.0/2987db1f15deaa19500ae24de560eabeaf1f8ef51df88c0470beeec72943bf11/cache-bc57feaf232aadde.arrow
11/17/2020 17:40:58 - INFO - filelock -   Lock 140177000533800 acquired on /root/.cache/huggingface/datasets/6264f08d89d6f9c36fc24be56a15dba71c8c86b628ef529ab8a87c867b38e98b.65c743c856669ab431cd2ebf50ced5f0805430a413142f650fe5ae89cfd68acd.py.lock
11/17/2020 17:40:58 - INFO - filelock -   Lock 140177000533800 released on /root/.cache/huggingface/datasets/6264f08d89d6f9c36fc24be56a15dba71c8c86b628ef529ab8a87c867b38e98b.65c743c856669ab431cd2ebf50ced5f0805430a413142f650fe5ae89cfd68acd.py.lock
11/17/2020 17:40:58 - INFO - filelock -   Lock 140178927394432 acquired on /root/.cache/huggingface/datasets/_root_.cache_huggingface_datasets_scitail_snli_format_1.1.0_fd8ccdfc3134ce86eb4ef10ba7f21ee2a125c946e26bb1dd3625fe74f48d3b90.lock
11/17/2020 17:40:58 - INFO - filelock -   Lock 140178927394432 released on /root/.cache/huggingface/datasets/_root_.cache_huggingface_datasets_scitail_snli_format_1.1.0_fd8ccdfc3134ce86eb4ef10ba7f21ee2a125c946e26bb1dd3625fe74f48d3b90.lock
11/17/2020 17:40:58 - INFO - filelock -   Lock 140177000403296 acquired on /root/.cache/huggingface/datasets/_root_.cache_huggingface_datasets_scitail_snli_format_1.1.0_fd8ccdfc3134ce86eb4ef10ba7f21ee2a125c946e26bb1dd3625fe74f48d3b90.lock
Reusing dataset scitail (/root/.cache/huggingface/datasets/scitail/snli_format/1.1.0/fd8ccdfc3134ce86eb4ef10ba7f21ee2a125c946e26bb1dd3625fe74f48d3b90)
11/17/2020 17:40:58 - INFO - filelock -   Lock 140177000403296 released on /root/.cache/huggingface/datasets/_root_.cache_huggingface_datasets_scitail_snli_format_1.1.0_fd8ccdfc3134ce86eb4ef10ba7f21ee2a125c946e26bb1dd3625fe74f48d3b90.lock
Loading cached processed dataset at /root/.cache/huggingface/datasets/scitail/snli_format/1.1.0/fd8ccdfc3134ce86eb4ef10ba7f21ee2a125c946e26bb1dd3625fe74f48d3b90/cache-f8b21e4dbe7c62d8.arrow
Exception in device=TPU:5: torch_xla/csrc/tensor_methods.cpp:858 : Check failed: xla::ShapeUtil::Compatible(shapes.back(), tensor_shape) 
*** Begin stack trace ***
	tensorflow::CurrentStackTrace()
	torch_xla::XLATensor::cat(absl::lts_2020_02_25::Span<torch_xla::XLATensor const>, long long)
	torch_xla::AtenXlaType::cat(c10::ArrayRef<at::Tensor>, long)
	c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<at::Tensor (*)(c10::ArrayRef<at::Tensor>, long), at::Tensor, c10::guts::typelist::typelist<c10::ArrayRef<at::Tensor>, long> >, at::Tensor (c10::ArrayRef<at::Tensor>, long)>::call(c10::OperatorKernel*, c10::ArrayRef<at::Tensor>, long)
	
	at::cat(c10::ArrayRef<at::Tensor>, long)
	
	
	
	at::cat(c10::ArrayRef<at::Tensor>, long)
	
	_PyCFunction_FastCallDict
	_PyCFunction_FastCallKeywords
	
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	_PyObject_FastCallDict
	_PyObject_Call_Prepend
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	_PyObject_FastCallDict
	_PyObject_Call_Prepend
	PyObject_Call
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	PyEval_EvalCodeEx
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	PyEval_EvalCodeEx
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	PyEval_EvalCodeEx
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	PyEval_EvalCodeEx
	PyEval_EvalCode
	
	PyRun_StringFlags
	PyRun_SimpleStringFlags
	Py_Main
	main
	__libc_start_main
	
*** End stack trace ***
f32[128]{0} vs. s64[128]{0}
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "/home/rabeeh/internship/seq2seq/finetune_t5_trainer.py", line 219, in _mp_fn
    main()
  File "/home/rabeeh/internship/seq2seq/finetune_t5_trainer.py", line 159, in main
    model_path=model_args.model_name_or_path if os.path.isdir(model_args.model_name_or_path) else None
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/transformers/trainer.py", line 775, in train
    tr_loss += self.training_step(model, inputs)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/transformers/trainer.py", line 1112, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/rabeeh/internship/seq2seq/t5_trainer.py", line 289, in compute_loss
    loss, _ = self._compute_loss(model, inputs, labels)
  File "/home/rabeeh/internship/seq2seq/t5_trainer.py", line 282, in _compute_loss
    logits = model(**inputs, use_cache=False)[0]
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/rabeeh/internship/seq2seq/models/t5/modeling_t5.py", line 367, in forward
    attention_mask = torch.cat((attention_mask_projection, attention_mask), dim=1)
RuntimeError: torch_xla/csrc/tensor_methods.cpp:858 : Check failed: xla::ShapeUtil::Compatible(shapes.back(), tensor_shape) 
*** Begin stack trace ***
	tensorflow::CurrentStackTrace()
	torch_xla::XLATensor::cat(absl::lts_2020_02_25::Span<torch_xla::XLATensor const>, long long)
	torch_xla::AtenXlaType::cat(c10::ArrayRef<at::Tensor>, long)
	c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<at::Tensor (*)(c10::ArrayRef<at::Tensor>, long), at::Tensor, c10::guts::typelist::typelist<c10::ArrayRef<at::Tensor>, long> >, at::Tensor (c10::ArrayRef<at::Tensor>, long)>::call(c10::OperatorKernel*, c10::ArrayRef<at::Tensor>, long)
	
	at::cat(c10::ArrayRef<at::Tensor>, long)
	
	
	
	at::cat(c10::ArrayRef<at::Tensor>, long)
	
	_PyCFunction_FastCallDict
	_PyCFunction_FastCallKeywords
	
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	_PyObject_FastCallDict
	_PyObject_Call_Prepend
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	_PyObject_FastCallDict
	_PyObject_Call_Prepend
	PyObject_Call
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	PyEval_EvalCodeEx
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	PyEval_EvalCodeEx
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	PyEval_EvalCodeEx
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	PyEval_EvalCodeEx
	PyEval_EvalCode
	
	PyRun_StringFlags
	PyRun_SimpleStringFlags
	Py_Main
	main
	__libc_start_main
	
*** End stack trace ***
f32[128]{0} vs. s64[128]{0}

  0%|          | 0/660 [00:00<?, ?it/s]/root/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
Traceback (most recent call last):
  File "xla_spawn.py", line 71, in <module>
    main()
  File "xla_spawn.py", line 67, in main
    xmp.spawn(mod._mp_fn, args=(), nprocs=args.num_cores)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 395, in spawn
    start_method=start_method)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 112, in join
    (error_index, exitcode)
Exception: process 5 terminated with exit code 17

**Comment by allenwang28** [comment]
`f32[128]{0} vs. s64[128]{0}`: Could you verify that dtypes of `projection_hidden_states` and `hidden_states` match?

**Comment by taylanbil** [comment]
you could run on 1 core, insert a breakpoint using `import pdb; pdb.set_trace()`, and inspect shapes of `attention_mask_projection, attention_mask` @ this line:

```
File "/home/rabeeh/internship/seq2seq/models/t5/modeling_t5.py", line 367, in forward
attention_mask = torch.cat((attention_mask_projection, attention_mask), dim=1)
```

**Comment by rabeehk** [comment]
Hi
thank you, this solved with setting the same type of dtype for the matrices.
