### ISSUE TITLE
kill all processes of pytroch xla inside a docker file

### ISSUE THREAD

**Issue by rabeehk** [pytorch/xla#2633]
Hi
When I am using pytorch xla inside a docker file, if I stop the job, the next time I want to launch this job inside the same docker image, this becomes too slow, to me not all processes of past job are killed, could you share me the command to kill them? thanks

**Comment by taylanbil** [comment]
you could connect to the running docker image `docker exec -it $runningdockerimg /bin/bash` and look what's consuming memory/resources. You could run `top` to get information on those. You could also run `pgrep python` to get info on running python processes, `kill $jobid1 $jobid2 ...` to kill specific jobs, or `pkill -9 python` to nuke all python jobs.

**Comment by taylanbil** [comment]
@rabeehk does this help? Is this issue good to close?

**Comment by rabeehk** [comment]
Hi Taylan
thank you very much, I will try with this, closed the issue for now.
