### ISSUE TITLE
getting IP address of TPU back to setup environment for pytorch XLA

### ISSUE THREAD

**Issue by rabeehk** [pytorch/xla#2637]
Hi
I am trying to do get a TPU in an script:
gcloud compute tpus create $TPU --project=$PROJECT --zone=$ZONE --network=default --version=pytorch-$VERSION --accelerator-type=v3-$NCORES

Then, I need to set XRT_TPU_CONFIG with IP address of this TPU to be able to run my pytorch XLA codes.
could you assist me how I can setup this variable inside a script?
thank you

**Comment by jysohn23** [comment]
Ex:
```
ipAddress=$(gcloud compute tpus describe --zone=europe-west4-a v3-8 --format "value(ipAddress)") && echo $ipAddress
10.30.15.2
```

**Comment by rabeehk** [comment]
Hi Jin
thank you, here is how I do it:

# create TPU
TPU=$TASKNAME-tpu-$NCORES
# create resource
gcloud compute tpus create $TPU --project=$PROJECT --zone=$ZONE
--network=default --version=pytorch-$VERSION --accelerator-type=v3-$NCORES
echo $TPU
TPU_IP_ADDRESS=$(gcloud compute tpus describe --zone=$ZONE $TPU --format
"value(ipAddress)")
XRT_TPU_CONFIG="tpu_worker;0;$TPU_IP_ADDRESS:8470"
echo $XRT_TPU_CONFIG


gcloud compute ssh --project=$PROJECT --zone=$ZONE $instance --command "
  . /anaconda3/etc/profile.d/conda.sh
  conda activate $CONDAENV
  export XRT_TPU_CONFIG=$XRT_TPU_CONFIG
  echo $XRT_TPU_CONFIG
  python .... calling the codes
"

This results in the error of

/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch/cuda/__init__.py:52:
UserWarning: CUDA initialization: Found no NVIDIA driver on your system.
Please check that you have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx (Triggered internally at
 /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/home/rabeeh//internship/seq2seq/xla_spawn.py", line 71, in <module>
    main()
  File "/home/rabeeh//internship/seq2seq/xla_spawn.py", line 67, in main
    xmp.spawn(mod._mp_fn, args=(), nprocs=args.num_cores)
  File
"/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py",
line 387, in spawn
    _start_fn(0, pf_cfg, fn, args)
  File
"/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py",
line 320, in _start_fn
    gindex = _prepare_env_for_index(index, pf_cfg)
  File
"/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py",
line 286, in _prepare_env_for_index
    os.environ.get(xenv.TPU_CONFIG, None))
  File
"/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py",
line 265, in _setup_tpu_worker
    tpu_config = _parse_tpu_config(tpu_env_config)
  File
"/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py",
line 72, in _parse_tpu_config
    raise ValueError('Bad worker syntax: {}'.format(worker))
ValueError: Bad worker syntax: tpu_worker


Thank you for your help.

**Comment by rabeehk** [comment]
Here is the value of XRT config:
export XRT_TPU_CONFIG=tpu_worker;0;10.19.46.42:8470
looks fine to me, not sure why the issue is happening, thanks for your
help. I am using xla_spawn.py from huggingface repo
which we takled about sometime ago.
thanks

**Comment by taylanbil** [comment]
in the script, do you `export` XRT_TPU_CONFIG or just set it in the line prior to launching the command?

**Comment by rabeehk** [comment]
Hi Tylan,
I do both, I am using this script which you kindly shared with me:
thanks.
Best
Rabeeh

#!/bin/bash

# bash gcp_launch.sh 8 20201118
################### PARAMS BEGIN
VERSION=1.7
NCORES=$1
if [ -z $2 ]
then
  #DATE=`date -d "1 day ago" +%Y%m%d`
  DATE=`date +%Y%m%d`
  echo "no date specified, using $DATE, and version $VERSION"
else
  DATE=$2
  echo "using $DATE, and version $VERSION"
fi
DISKIMG=debian-9-torch-xla-v$DATE
if [ -z $1 ]
then
  echo "give tpu cores as first arg"
  exit
fi
TASKNAME=rabeeh-t5-pods8
PROJECT=ruse-xgcp
MTYPE=e2-standard-32
SERVICEACCT=726688283486-compute@developer.gserviceaccount.com
ZONE=europe-west4-a
DISKTYPE=pd-standard
code_dir=/google/src/cloud/rabeeh/internship/google3/learning/brain/research/ruse/mine/internship/
#DISKTYPE=pd-ssd
################### PARAMS END

set -e
set -x
# Create instance template
IT=$TASKNAME-it
# XXX: create resource
gcloud beta compute --project=$PROJECT instance-templates create $IT
--machine-type=$MTYPE --network=projects/$PROJECT/global/networks/default
--network-tier=PREMIUM --maintenance-policy=MIGRATE
--service-account=$SERVICEACCT --scopes=
https://www.googleapis.com/auth/cloud-platform --image=$DISKIMG
--image-project=ml-images --boot-disk-size=200GB --boot-disk-type=$DISKTYPE
--boot-disk-device-name=$IT --reservation-affinity=any

# create instance group
IG=$TASKNAME-ig
igsize=$(( NCORES / 8 ))

# XXX: create resource
gcloud compute --project=$PROJECT instance-groups managed create $IG
--base-instance-name=$IG --template=$IT --size=$igsize --zone=$ZONE

# create TPU
TPU=$TASKNAME-tpu-$NCORES
# XXX: create resource
gcloud compute tpus create $TPU --project=$PROJECT --zone=$ZONE
--network=default --version=pytorch-$VERSION --accelerator-type=v3-$NCORES
echo $TPU

TPU_IP_ADDRESS=$(gcloud compute tpus describe --zone=$ZONE $TPU --format
"value(ipAddress)")
export XRT_TPU_CONFIG="tpu_worker;0;$TPU_IP_ADDRESS:8470"
echo $XRT_TPU_CONFIG

# prepare vms
gcloud compute instance-groups managed wait-until --stable $IG --zone $ZONE
CONDAENV=torch-xla-$VERSION
pids=
for instance in $(gcloud --project=$PROJECT compute instance-groups managed
list-instances $IG --zone=$ZONE --format='value(NAME)[terminator=" "]')
do
  localpath=$code_dir/seq2seq/requirements.txt
  remotepath=/home/rabeeh/
  #gcloud compute scp --project=$PROJECT --zone=$ZONE
$localpath/requirements.txt $instance:$remotepath
  gcloud compute scp --recurse --project=$PROJECT --zone=$ZONE $code_dir
$instance:$remotepath
  gcloud compute ssh --project=$PROJECT --zone=$ZONE "$instance" --command "
    . /anaconda3/etc/profile.d/conda.sh
    conda activate $CONDAENV
    #cp -r internship $remotepath
    pip install -r $remotepath/internship/seq2seq/requirements.txt
    cd $remotepath/internship/
    python setup.py develop

    # TODO: prepare the vms, download data, install code, whatever.
" &
  pids+=" $!"
done
wait $pids || { echo "failed initializing vms" >&2; exit 1; }

# Wait for healthy tpu
TPU_HEALTHY_ATTEMPTS=300
set +x
echo 'Waiting for tpu to become healthy.'
for x in `seq 1 $TPU_HEALTHY_ATTEMPTS`
do
  echo "  Polling, $x"
  _TPU_HEALTHY=`gcloud compute tpus describe $TPU --zone=$ZONE`
  _health_substr="health: HEALTHY"
  if [[ $_TPU_HEALTHY == *"$_health_substr"* ]]; then
    echo "After $x tries, tpu is healthy."
    break
  fi
  sleep 5
done
set -x
test $TPU_HEALTHY_ATTEMPTS -gt $x
if [ -z $2 ]
then
  echo "No date specified, using nightly tpu runtime"
else
  echo "Updating TPU runtime to $DATE"
  gcloud compute ssh --project=$PROJECT --zone=$ZONE "$instance" --command "
    set -e  # Fail on first failure
    set -x  # echo commands
    GVM_IPS=\$(gcloud --project=${PROJECT} compute tpus describe \
      ${TPU} --zone=$ZONE --format='value(networkEndpoints[].ipAddress)')
    pids=
    for ip in \$(echo \$GVM_IPS | tr ';' '\n')
    do
      curl -X POST http://\${ip}:8475/requestversion/pytorch-dev$DATE &
      pids+=\" \$!\"
    done
    wait \$pids
  "
fi
TPU_HEALTHY_ATTEMPTS=300
set +x
echo 'Waiting for tpu to become healthy.'
for x in `seq 1 $TPU_HEALTHY_ATTEMPTS`
do
  echo "  Polling, $x"
  _TPU_HEALTHY=`gcloud compute tpus describe $TPU --zone=$ZONE`
  _health_substr="health: HEALTHY"
  if [[ $_TPU_HEALTHY == *"$_health_substr"* ]]; then
    echo "After $x tries, tpu is healthy."
    break
  fi
  sleep 5
done

# RUN THE TRAINING JOB:
set +e
set -x
gcloud compute ssh --project=$PROJECT --zone=$ZONE $instance --command "
  . /anaconda3/etc/profile.d/conda.sh
  conda activate $CONDAENV
  export XRT_TPU_CONFIG=$XRT_TPU_CONFIG
  echo $XRT_TPU_CONFIG
  cd $remotepath/internship/seq2seq/
  python $remotepath/internship/seq2seq/xla_spawn.py \
  $remotepath/internship/seq2seq/finetune_t5_trainer.py\
  $remotepath/internship/seq2seq/configs/test_xla.json | tee logs.txt
"

# python -m torch_xla.distributed.xla_dist \
#   --tpu=$TPU \
#   --conda-env=$CONDAENV \
#   -- python3 $remotepath/internship/seq2seq/finetune_t5_trainer.py
$remotepath/internship/seq2seq/configs/test_xla.json | tee logfile.txt

#gcloud compute scp --project=$PROJECT --zone=$ZONE $instance:$pathtomodel
$localpath/model.pt

# CLEANUP
/usr/bin/yes | gcloud compute instance-groups managed delete $IG
--zone=$ZONE
/usr/bin/yes | gcloud compute tpus delete $TPU --project=$PROJECT
--zone=$ZONE
/usr/bin/yes | gcloud compute instance-templates delete $IT

**Comment by taylanbil** [comment]
you need quotes here:

```
gcloud compute ssh --project=$PROJECT --zone=$ZONE $instance --command "
  . /anaconda3/etc/profile.d/conda.sh
  conda activate $CONDAENV
  export XRT_TPU_CONFIG=\"$XRT_TPU_CONFIG\"
  echo \"\$XRT_TPU_CONFIG\"
  cd $remotepath/internship/seq2seq/
  python $remotepath/internship/seq2seq/xla_spawn.py \
  $remotepath/internship/seq2seq/finetune_t5_trainer.py\
  $remotepath/internship/seq2seq/configs/test_xla.json | tee logs.txt
"
```
