### ISSUE TITLE
RuntimeError: torch_xla/csrc/tensor.cpp:486 : Check failed: data_ != nullptr 

### ISSUE THREAD

**Issue by Dapeng960208** [pytorch/xla#2658]
## ❓ Questions and Help

RuntimeError                              Traceback (most recent call last)
<ipython-input-16-1917d7190160> in <module>()
    187       train_loss, GLOBAL_STEPS = train(model=model, device=DEVICE, train_loader=train_loader, optimizer=optimizer,
    188                                       epoch=epoch,
--> 189                                       global_steps=GLOBAL_STEPS)
    190       if epoch>4:
    191           val(model=model, device=DEVICE, val_loader=val_loader,epoch=epoch)

2 frames
/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
    130     Variable._execution_engine.run_backward(
    131         tensors, grad_tensors_, retain_graph, create_graph,
--> 132         allow_unreachable=True)  # allow_unreachable flag
    133 
    134 

RuntimeError: torch_xla/csrc/tensor.cpp:486 : Check failed: data_ != nullptr 
*** Begin stack trace ***
	tensorflow::CurrentStackTrace()
	torch_xla::XLATensor::data() const
	torch_xla::XLATensor::GetIrValue() const
	torch_xla::XLATensor::native_batch_norm_backward(torch_xla::XLATensor const&, torch_xla::XLATensor const&, torch_xla::XLATensor const&, torch_xla::XLATensor const&, torch_xla::XLATensor const&, bool, double)
	torch_xla::AtenXlaType::native_batch_norm_backward(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, bool, double, std::array<bool, 3ul>)
	c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<std::tuple<at::Tensor, at::Tensor, at::Tensor> (*)(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, bool, double, std::array<bool, 3ul>), std::tuple<at::Tensor, at::Tensor, at::Tensor>, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, bool, double, std::array<bool, 3ul> > >, std::tuple<at::Tensor, at::Tensor, at::Tensor> (at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, bool, double, std::array<bool, 3ul>)>::call(c10::OperatorKernel*, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, bool, double, std::array<bool, 3ul>)
	
	at::native_batch_norm_backward(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, bool, double, std::array<bool, 3ul>)
	
	
	
	at::native_batch_norm_backward(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, bool, double, std::array<bool, 3ul>)
	torch::autograd::generated::NativeBatchNormBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&)
	
	torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&)
	torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&)
	torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool)
	torch::autograd::python::PythonEngine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool)
	
	
	clone
*** End stack trace ***
Trying to access a null cursor

**Comment by Dapeng960208** [comment]
this error occur at  loss.mean().backward()

**Comment by Dapeng960208** [comment]
for epoch_step, (images, annotations) in enumerate(train_loader):
        batch_imgs = images.float().to(DEVICE)
        batch_boxes = annotations[:, :, 0:4].to(DEVICE)
        batch_classes = annotations[:, :, 4].to(DEVICE)
                                         
        start_time = time.time()
        # lr = lr_func(global_steps)
        # for param in optimizer.param_groups:
        #     param['lr']= lr
        optimizer.zero_grad()
        losses = model([batch_imgs, batch_boxes, batch_classes])
        loss = losses[-1]
        loss.mean().backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 0.1)
        xm.optimizer_step(optimizer, barrier=True)

**Comment by JackCaoG** [comment]
Hi @Dapeng960208 , could you share a small repo that I can test on my end?

**Comment by Dapeng960208** [comment]
HI ,https://github.com/Dapeng960208/efficientfcosTPU,The file I use is train_voc.py  and The error occurred in ‘loss.mean().backward()’

**Comment by Dapeng960208** [comment]
HI ,he file I use is train_voc.py and The error occurred in ‘loss.mean().backward()’
[https://github.com/Dapeng960208/efficientfcosTPU](url)

**Comment by JackCaoG** [comment]
@Dapeng960208 Can you create a Colab which reproduces the issue following this template?

https://github.com/pytorch/xla/blob/master/contrib/colab/issue-report.ipynb

**Comment by Dapeng960208** [comment]
Sorry, I don't understand many parts of the code in the template. So i can't create

**Comment by Dapeng960208** [comment]
import torch
import torch_xla
import torch_xla.core.xla_model as xm
import torch_xla.distributed.xla_multiprocessing as xmp
from model.EfficientFcos import EfficientFcosDetector
import torch
from dataset.VOC_dataset import VOCDataset
import time,math
import os
import numpy as np
import random
import torch.backends.cudnn as cudnn
import torch.optim as optim
from model.config import DefaultConfig
from dataset.augment import Normalizer, Augmenter, Resizer, collater,DataAugmenter,Small_Resize
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
config = DefaultConfig
config.efficientNet = 'efficientnet-b6'
torch.manual_seed(0)
torch.cuda.manual_seed(0)
torch.cuda.manual_seed_all(0)
np.random.seed(0)
cudnn.benchmark = True
cudnn.deterministic = True
random.seed(0)

BATCH_SIZE = 2
INPUT_RESIZE = 1024
EPOCHS = 30
GLOBAL_STEPS = 0
start_epoch = 1
WARMPUP_STEPS = 100
WARMUP_FACTOR = 1.0 / 3.0
LR_INIT = 5e-4
LR_END = 5e-8
root_path = r'/content/drive/My Drive/checkpoint_EFcos_B6_0.2_128'
log_path = r'/content/drive/MyDrive/EfficientFcosV2/EFcos_B6Log_0.2_128.txt'
loss_path = r'/content/drive/MyDrive/EfficientFcosV2/EFcos_B6Loss_0.2_128.txt'
if not os.path.isdir(root_path):
    os.mkdir(root_path)

# 加载训练集 验证集合
DEVICE = xm.xla_device()
print(DEVICE)
if not xm.is_master_ordinal():
    xm.rendezvous('download_only_once')
train_dataset = VOCDataset(root_dir=r'/content/VOC0712',
                           split='trainval',
                           transform=transforms.Compose([DataAugmenter(),Normalizer(),Resizer(common_size=INPUT_RESIZE),Small_Resize(small=True)]))
val_dataset = VOCDataset(root_dir=r'/content/VOC0712',
                           split='test',
                         transform=transforms.Compose([Normalizer(),Resizer(common_size=INPUT_RESIZE),Small_Resize(small=False)]))
train_loader =DataLoader(train_dataset, 
                         batch_size=BATCH_SIZE, 
                         shuffle=True,
                         collate_fn=collater,
                         num_workers=4,
                         pin_memory=True)
val_loader = DataLoader(val_dataset, 
                         batch_size=BATCH_SIZE, 
                         shuffle=False,
                         collate_fn=collater,
                         num_workers=4,
                         pin_memory=True)

# 加载模型
if not xm.is_master_ordinal():
    xm.rendezvous('download_only_once')
model = EfficientFcosDetector(mode="training").to(DEVICE)
#optimizer = torch.optim.SGD(model.parameters(), lr=LR_INIT, momentum=0.9, weight_decay=5e-4)
optimizer = torch.optim.Adamax(model.parameters(), lr=LR_INIT)
#scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer,factor=0.9, patience=3, verbose=True,min_lr=LR_END)
#optimizer = optim.Adam(model.parameters(), lr=LR_INIT,weight_decay=1e-4)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer,EPOCHS, eta_min=LR_END, last_epoch=-1)
#scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer,factor=0.9, patience=3, verbose=True,min_lr=LR_END)
steps_per_epoch = len(train_dataset) // BATCH_SIZE
#TOTAL_STEPS = steps_per_epoch * EPOCHS
COS_STOP_STEPS = steps_per_epoch*EPOCHS
# try:
#         result = torch.load('/content/drive/MyDrive/checkpoint_EFcos_B4_0.1_192/model_23_0.3549.pth')
#         state = result['state']
#         start_epoch = int(result['start_epoch'])
#         GLOBAL_STEPS = int(result['global_steps'])
#         loss=float(result['loss'])
#         lr = float(result['lr'])
#         for param in optimizer.param_groups:
#             param['lr']=lr
#         model.load_state_dict(state)
#         print('load the best pth \n the loss is %.4f and the epoch is %d'%(loss,start_epoch-1))
# except FileNotFoundError:
#         print('Can\'t load best pth')

def lr_func(global_steps):
     if global_steps < WARMPUP_STEPS:
         lr = global_steps / WARMPUP_STEPS * LR_INIT
     else:
          lr = LR_END + 0.5 * (LR_INIT - LR_END) * (
             (1 + math.cos((global_steps - WARMPUP_STEPS) / (COS_STOP_STEPS - WARMPUP_STEPS) * math.pi))
         )
     return float(lr)

def train(model, device, train_loader, optimizer, epoch, global_steps):
    model.train()
    train_loss = []
    global_steps=global_steps
    optimizer.zero_grad()
    epoch_start_tome =time.time()
    #optimizer.zero_grad()
    for epoch_step, (images, annotations) in enumerate(train_loader):
        batch_imgs = images.float().to(DEVICE)
        batch_boxes = annotations[:, :, 0:4].to(DEVICE)
        batch_classes = annotations[:, :, 4].to(DEVICE)
                                         
        start_time = time.time()
        # lr = lr_func(global_steps)
        # for param in optimizer.param_groups:
        #     param['lr']= lr
        optimizer.zero_grad()
        losses = model([batch_imgs, batch_boxes, batch_classes])
        loss = losses[-1]
        loss.mean().backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 0.1)
        xm.optimizer_step(optimizer, barrier=True)
        for param in optimizer.param_groups:
            lr=param['lr']
        total_loss = round(float(loss.mean()),4)
        end_time = time.time()
        cost_time = int((end_time - start_time) * 10)
        if global_steps % 10 == 0:
            with open(loss_path, 'a+') as f:
                f.write("global_steps:%d epoch:%d steps:%d/%d cls_loss:%.4f cnt_loss:%.4f reg_loss:%.4f lr=%.4e"
                        "total_loss:%.4f\n" % \
                        (global_steps, epoch, epoch_step, steps_per_epoch, losses[0].mean(), losses[1].mean(),
                         losses[2].mean(),lr,total_loss))
            print(
                "global_steps:%d epoch:%d steps:%d/%d cls_loss:%.4f cnt_loss:%.4f reg_loss:%.4f cost_time:%ds lr=%.4e "
                "total_loss:%.4f" % \
                (global_steps, epoch, epoch_step, steps_per_epoch, losses[0].mean(), losses[1].mean(),
                 losses[2].mean(), cost_time,lr,total_loss))
        global_steps += 1
        train_loss.append(total_loss)
    train_loss =np.mean(train_loss)
    scheduler.step()
    if epoch <=5:
        save_path = root_path + "/last.pth"
    else:
        save_path = root_path + "/model_{}_{}.pth".format(epoch, round(train_loss, 4))
    result = {
        'state': model.state_dict(),
        'start_epoch': epoch + 1,
        'global_steps': global_steps,
        'loss': train_loss,
        'lr': lr
    }
    torch.save(result, save_path)
    epoch_end_tome =time.time()
    epoch_cost_time = (epoch_end_tome - epoch_start_tome)/3600
    print('Train set: Epoch:{} Average loss: {:.4f} Cost time : {}hours'.format(epoch,train_loss,epoch_cost_time))
    with open(log_path,'a+') as f:
          f.write('\n Train set: Epoch:{} Average loss: {:.4f} Cost time : {}hours'.format(epoch,train_loss,epoch_cost_time))
    return train_loss, global_steps

@torch.no_grad()
def val(model, device, val_loader,epoch):
    model.eval()
    val_loss = []
    start_time = time.time()
    for epoch_step, (images, annotations) in enumerate(val_loader):
        batch_imgs = images.float().to(DEVICE)
        batch_boxes = annotations[:, :, 0:4].to(DEVICE)
        batch_classes = annotations[:, :, 4].to(DEVICE)
        losses = model([batch_imgs, batch_boxes, batch_classes])
        loss = losses[-1]
        total_loss = round(float(loss.mean()),4)
        val_loss.append(total_loss)
    end_time = time.time()
    cost_time = end_time - start_time
    val_loss =np.mean(val_loss)
    print('Val set: Epoch:{} Average loss: {:.4f}  Cost time : {} s'.format(epoch,val_loss, cost_time))
    with open(log_path,'a+') as f:
          f.write('   Val set: Average loss: {:.4f}  Cost time : {} s'.format(val_loss, cost_time))
    return None  

if __name__=='__main__':
  for epoch in range(start_epoch, EPOCHS + 1):
      train_loss, GLOBAL_STEPS = train(model=model, device=DEVICE, train_loader=train_loader, optimizer=optimizer,
                                      epoch=epoch,
                                      global_steps=GLOBAL_STEPS)
      if epoch>4:
          val(model=model, device=DEVICE, val_loader=val_loader,epoch=epoch)

**Comment by Dapeng960208** [comment]
`import torch
import torch_xla
import torch_xla.core.xla_model as xm
import torch_xla.distributed.xla_multiprocessing as xmp
from model.EfficientFcos import EfficientFcosDetector
import torch
from dataset.VOC_dataset import VOCDataset
import time,math
import os
import numpy as np
import random
import torch.backends.cudnn as cudnn
import torch.optim as optim
from model.config import DefaultConfig
from dataset.augment import Normalizer, Augmenter, Resizer, collater,DataAugmenter,Small_Resize
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
config = DefaultConfig
config.efficientNet = 'efficientnet-b6'
torch.manual_seed(0)
torch.cuda.manual_seed(0)
torch.cuda.manual_seed_all(0)
np.random.seed(0)
cudnn.benchmark = True
cudnn.deterministic = True
random.seed(0)

BATCH_SIZE = 2
INPUT_RESIZE = 1024
EPOCHS = 30
GLOBAL_STEPS = 0
start_epoch = 1
WARMPUP_STEPS = 100
WARMUP_FACTOR = 1.0 / 3.0
LR_INIT = 5e-4
LR_END = 5e-8
root_path = r'/content/drive/My Drive/checkpoint_EFcos_B6_0.2_128'
log_path = r'/content/drive/MyDrive/EfficientFcosV2/EFcos_B6Log_0.2_128.txt'
loss_path = r'/content/drive/MyDrive/EfficientFcosV2/EFcos_B6Loss_0.2_128.txt'
if not os.path.isdir(root_path):
    os.mkdir(root_path)

# 加载训练集 验证集合
DEVICE = xm.xla_device()
print(DEVICE)
if not xm.is_master_ordinal():
    xm.rendezvous('download_only_once')
train_dataset = VOCDataset(root_dir=r'/content/VOC0712',
                           split='trainval',
                           transform=transforms.Compose([DataAugmenter(),Normalizer(),Resizer(common_size=INPUT_RESIZE),Small_Resize(small=True)]))
val_dataset = VOCDataset(root_dir=r'/content/VOC0712',
                           split='test',
                         transform=transforms.Compose([Normalizer(),Resizer(common_size=INPUT_RESIZE),Small_Resize(small=False)]))
train_loader =DataLoader(train_dataset, 
                         batch_size=BATCH_SIZE, 
                         shuffle=True,
                         collate_fn=collater,
                         num_workers=4,
                         pin_memory=True)
val_loader = DataLoader(val_dataset, 
                         batch_size=BATCH_SIZE, 
                         shuffle=False,
                         collate_fn=collater,
                         num_workers=4,
                         pin_memory=True)

# 加载模型
if not xm.is_master_ordinal():
    xm.rendezvous('download_only_once')
model = EfficientFcosDetector(mode="training").to(DEVICE)
#optimizer = torch.optim.SGD(model.parameters(), lr=LR_INIT, momentum=0.9, weight_decay=5e-4)
optimizer = torch.optim.Adamax(model.parameters(), lr=LR_INIT)
#scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer,factor=0.9, patience=3, verbose=True,min_lr=LR_END)
#optimizer = optim.Adam(model.parameters(), lr=LR_INIT,weight_decay=1e-4)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer,EPOCHS, eta_min=LR_END, last_epoch=-1)
#scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer,factor=0.9, patience=3, verbose=True,min_lr=LR_END)
steps_per_epoch = len(train_dataset) // BATCH_SIZE
#TOTAL_STEPS = steps_per_epoch * EPOCHS
COS_STOP_STEPS = steps_per_epoch*EPOCHS
# try:
#         result = torch.load('/content/drive/MyDrive/checkpoint_EFcos_B4_0.1_192/model_23_0.3549.pth')
#         state = result['state']
#         start_epoch = int(result['start_epoch'])
#         GLOBAL_STEPS = int(result['global_steps'])
#         loss=float(result['loss'])
#         lr = float(result['lr'])
#         for param in optimizer.param_groups:
#             param['lr']=lr
#         model.load_state_dict(state)
#         print('load the best pth \n the loss is %.4f and the epoch is %d'%(loss,start_epoch-1))
# except FileNotFoundError:
#         print('Can\'t load best pth')

def lr_func(global_steps):
     if global_steps < WARMPUP_STEPS:
         lr = global_steps / WARMPUP_STEPS * LR_INIT
     else:
          lr = LR_END + 0.5 * (LR_INIT - LR_END) * (
             (1 + math.cos((global_steps - WARMPUP_STEPS) / (COS_STOP_STEPS - WARMPUP_STEPS) * math.pi))
         )
     return float(lr)

def train(model, device, train_loader, optimizer, epoch, global_steps):
    model.train()
    train_loss = []
    global_steps=global_steps
    optimizer.zero_grad()
    epoch_start_tome =time.time()
    #optimizer.zero_grad()
    for epoch_step, (images, annotations) in enumerate(train_loader):
        batch_imgs = images.float().to(DEVICE)
        batch_boxes = annotations[:, :, 0:4].to(DEVICE)
        batch_classes = annotations[:, :, 4].to(DEVICE)
                                         
        start_time = time.time()
        # lr = lr_func(global_steps)
        # for param in optimizer.param_groups:
        #     param['lr']= lr
        optimizer.zero_grad()
        losses = model([batch_imgs, batch_boxes, batch_classes])
        loss = losses[-1]
        loss.mean().backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 0.1)
        xm.optimizer_step(optimizer, barrier=True)
        for param in optimizer.param_groups:
            lr=param['lr']
        total_loss = round(float(loss.mean()),4)
        end_time = time.time()
        cost_time = int((end_time - start_time) * 10)
        if global_steps % 10 == 0:
            with open(loss_path, 'a+') as f:
                f.write("global_steps:%d epoch:%d steps:%d/%d cls_loss:%.4f cnt_loss:%.4f reg_loss:%.4f lr=%.4e"
                        "total_loss:%.4f\n" % \
                        (global_steps, epoch, epoch_step, steps_per_epoch, losses[0].mean(), losses[1].mean(),
                         losses[2].mean(),lr,total_loss))
            print(
                "global_steps:%d epoch:%d steps:%d/%d cls_loss:%.4f cnt_loss:%.4f reg_loss:%.4f cost_time:%ds lr=%.4e "
                "total_loss:%.4f" % \
                (global_steps, epoch, epoch_step, steps_per_epoch, losses[0].mean(), losses[1].mean(),
                 losses[2].mean(), cost_time,lr,total_loss))
        global_steps += 1
        train_loss.append(total_loss)
    train_loss =np.mean(train_loss)
    scheduler.step()
    if epoch <=5:
        save_path = root_path + "/last.pth"
    else:
        save_path = root_path + "/model_{}_{}.pth".format(epoch, round(train_loss, 4))
    result = {
        'state': model.state_dict(),
        'start_epoch': epoch + 1,
        'global_steps': global_steps,
        'loss': train_loss,
        'lr': lr
    }
    torch.save(result, save_path)
    epoch_end_tome =time.time()
    epoch_cost_time = (epoch_end_tome - epoch_start_tome)/3600
    print('Train set: Epoch:{} Average loss: {:.4f} Cost time : {}hours'.format(epoch,train_loss,epoch_cost_time))
    with open(log_path,'a+') as f:
          f.write('\n Train set: Epoch:{} Average loss: {:.4f} Cost time : {}hours'.format(epoch,train_loss,epoch_cost_time))
    return train_loss, global_steps

@torch.no_grad()
def val(model, device, val_loader,epoch):
    model.eval()
    val_loss = []
    start_time = time.time()
    for epoch_step, (images, annotations) in enumerate(val_loader):
        batch_imgs = images.float().to(DEVICE)
        batch_boxes = annotations[:, :, 0:4].to(DEVICE)
        batch_classes = annotations[:, :, 4].to(DEVICE)
        losses = model([batch_imgs, batch_boxes, batch_classes])
        loss = losses[-1]
        total_loss = round(float(loss.mean()),4)
        val_loss.append(total_loss)
    end_time = time.time()
    cost_time = end_time - start_time
    val_loss =np.mean(val_loss)
    print('Val set: Epoch:{} Average loss: {:.4f}  Cost time : {} s'.format(epoch,val_loss, cost_time))
    with open(log_path,'a+') as f:
          f.write('   Val set: Average loss: {:.4f}  Cost time : {} s'.format(val_loss, cost_time))
    return None  

if __name__=='__main__':
  for epoch in range(start_epoch, EPOCHS + 1):
      train_loss, GLOBAL_STEPS = train(model=model, device=DEVICE, train_loader=train_loader, optimizer=optimizer,
                                      epoch=epoch,
                                      global_steps=GLOBAL_STEPS)
      if epoch>4:
          val(model=model, device=DEVICE, val_loader=val_loader,epoch=epoch)`

**Comment by Dapeng960208** [comment]
RuntimeError: torch_xla/csrc/tensor.cpp:486 : Check failed: data_ != nullptr 
*** Begin stack trace ***
	tensorflow::CurrentStackTrace()
	torch_xla::XLATensor::data() const
	torch_xla::XLATensor::GetIrValue() const
	torch_xla::XLATensor::native_batch_norm_backward(torch_xla::XLATensor const&, torch_xla::XLATensor const&, torch_xla::XLATensor const&, torch_xla::XLATensor const&, torch_xla::XLATensor const&, bool, double)
	torch_xla::AtenXlaType::native_batch_norm_backward(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, bool, double, std::array<bool, 3ul>)
	c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<std::tuple<at::Tensor, at::Tensor, at::Tensor> (*)(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, bool, double, std::array<bool, 3ul>), std::tuple<at::Tensor, at::Tensor, at::Tensor>, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, bool, double, std::array<bool, 3ul> > >, std::tuple<at::Tensor, at::Tensor, at::Tensor> (at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, bool, double, std::array<bool, 3ul>)>::call(c10::OperatorKernel*, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, bool, double, std::array<bool, 3ul>)
	
	at::native_batch_norm_backward(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, bool, double, std::array<bool, 3ul>)
	
	
	
	at::native_batch_norm_backward(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, bool, double, std::array<bool, 3ul>)
	torch::autograd::generated::NativeBatchNormBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&)
	
	torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&)
	torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&)
	torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool)
	torch::autograd::python::PythonEngine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool)
	
	
	clone
*** End stack trace ***
Trying to access a null cursor

**Comment by Dapeng960208** [comment]
My error occurred in execution ‘ loss.backward()’
when i print the loss ,the result is tensor(3.3001, device='xla:1', grad_fn=<MeanBackward0>)
and It can run normally on GPU

**Comment by Dapeng960208** [comment]
If anyone can help me solve this problem, please contact me, thank you

**Comment by jiangyangzhou** [comment]
I also meet this problem , how to solve this?
