### ISSUE TITLE
Providing a dummy example with iterative datasets to be trained on TPU

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [pytorch/xla#2659]
Hi
could you provide me with a dummy example with iterative dataloader which runs fine on TPU distributedly. I really need to make some codes work with iterative datasets and I was wondering if I could have a dummy example on this to understand the logics needs to be changed. thanks

**Comment by taylanbil** [comment]
this issue is obsolete per offline discussion, and not torchxla related, but rather distributed training related. closing.
