### ISSUE TITLE
serious performance issue with pytorch XLA

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [pytorch/xla#2660]
Hi
I am working on a model in which in every batch I would get:

torch.Size([256, 128]) torch.Size([256, 128]) torch.Size([256, 128]) scitail

the last element is a string which can change from time to time.
Does this make any performance issue by itself? I have heard that length should be kept the same across batches or something similar for performnace issues. Could you remind me of the rule and how I can handle the last string?

thanks

**Comment by taylanbil** [comment]
how do you use the string? do you tokenize and make a tensor and feed to model? is your string used in an if statement to create a unique graph?

**Comment by taylanbil** [comment]
@rabeehkarimimahabadi is this good to close?

**Comment by rabeehkarimimahabadi** [comment]
Hi Taylan,
yes, I realized the performance issue was mainly related to my batch sizes
not working well with TPU, if needed I can reopen later on.
thanks for your help.
Best
Rabeeh
