### ISSUE TITLE
Need help on the error message

### ISSUE THREAD

**Issue by kkissmart** [pytorch/xla#2661]
## ❓ Questions and Help

What below error message means? Given the code works well on GPU.

Status: Aborted: Session 1def0cea4f60540e is not found.
Exception in device=TPU:6: Aborted: Session 9d9f16636571817e is not found.
Traceback (most recent call last):
File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 329, in _mp_start_fn
_start_fn(index, pf_cfg, fn, args)
File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 323, in _start_fn
fn(gindex, *args)
File "/home/yinhan/bart_modification/fairseq/distributed_utils.py", line 154, in distributed_main
main(args, **kwargs)
File "/home/yinhan/bart_modification/fairseq_cli/train.py", line 120, in main
valid_losses, should_stop = train(args, trainer, task, epoch_itr)
File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/contextlib.py", line 52, in inner
return func(*args, *kwds)
File "/home/yinhan/bart_modification/fairseq_cli/train.py", line 200, in train
log_output = trainer.train_step(samples)
File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/contextlib.py", line 52, in inner
return func(args, **kwds)
File "/home/yinhan/bart_modification/fairseq/trainer.py", line 491, in train_step
xm.mark_step()
File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 718, in mark_step
wait=xu.getenv_as('XLA_SYNC_WAIT', bool, False))
RuntimeError: Aborted: Session 9d9f16636571817e is not found.
terminate called after throwing an instance of 'std::runtime_error'
what(): tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:1110 : Check failed: session->session()->Run( feed_inputs, {}, {cached_node.operations[0]}, &outputs) == ::tensorflow::Status::OK() (Aborted: Session 9d9f16
636571817e is not found. vs. OK)
*** Begin stack trace ***
tensorflow::CurrentStackTrace()
xla::XrtComputationClient::ReleaseHandles(std::vector<xla::XrtComputationClient::DeviceHandle, std::allocatorxla::XrtComputationClient::DeviceHandle >, std::function<xla::XrtSession::CachedNode const& (xla::XrtSession
, tensorflow::Scope const&, std::string const&)> const&, xla::metrics::Metric, xla::metrics::Counter)
xla::XrtComputationClient::HandleReleaser()
xla::util::TriggeredTask::Runner()

    clone
*** End stack trace ***

Exception in device=TPU:7: Aborted: Session 1def0cea4f60540e is not found.

**The code has been tested on GPU, which works fine.**

**Comment by zcain117** [comment]
Sometimes I see this error when a TPU has been pre-empted or died for other reason like maintenance.

Are you using Colab or GCE to create the TPU?

And does this happen every time or only sometimes?

**Comment by kkissmart** [comment]
every time.

**Comment by zcain117** [comment]
Are you using Colab or GCE to create the TPU?  Could you try deleting the TPU and making a new one?  I see you're using `torch-xla-nightly` so it's important that your TPU is using an up-to-date version of the `pytorch-nightly` TPU software

**Comment by kkissmart** [comment]
I use gcloud to create. I am running on V3-8.

(gcloud compute tpus create med3 --zone=us-central1-a  --network=default --version=pytorch-nightly  --accelerator-type=v3-8 )

**Comment by kkissmart** [comment]
Sees below code causes the problem. Any suggestions on why?

        if self.hierarchical_layers is not None:
            n_sentences = src_tokens.eq(self.hierarchical_token).sum(-1) 
            hierarchical_x = torch.zeros((self.fix_hierarchical_size, x.size(1), x.size(-1))).type_as(x)
            hierarchical_padding_mask = torch.ones(encoder_padding_mask.size(0), n_sentences.max().item()).type_as(encoder_padding_mask)
            for j, i in enumerate(n_sentences):
                hierarchical_padding_mask[j, :i] = 0
            hierarchical_x[~hierarchical_padding_mask.transpose(0, 1)] = x[(src_tokens==self.hierarchical_token).transpose(0, 1)]
            for layer in self.hierarchical_layers:
                hierarchical_x = layer(hierarchical_x, hierarchical_padding_mask)
        else:
            hierarchical_x = None
            hierarchical_padding_mask = None

**Comment by zcain117** [comment]
does is happen when `self.hierarchical_layers` is None?  Or only when it's not None?

**Comment by taylanbil** [comment]
This block of code looks benign to me. Any chance we can reproduce this on our side?

is `n_sentences` a tansor? If so, looks like this will be slow due to tpu->cpu data transfer.

**Comment by kkissmart** [comment]
n_sentences is a tensor.
self.hierarchical_layers is None works well on TPU.
self.hierarchical_layers is not None only works on GPU.

**Comment by kkissmart** [comment]
It is extremely slow, and then failed. I can share branch with you along with the code.

**Comment by taylanbil** [comment]
ok so I am not sure if this is the root cause of the current issue, but I definitely think this part is a problem:

```python
        n_sentences = src_tokens.eq(self.hierarchical_token).sum(-1) 
...
        for j, i in enumerate(n_sentences):
            hierarchical_padding_mask[j, :i] = 0
```

`n_sentences` being a tensor, once you enumerate and iterate on it, this causes tpu => cpu transfer slowness.
moreover, value of `i` changing will cause too much dynamism (probably) and you will see a lot of compilations as a result.

Is `self.hierarchical_token` a constant tensor? Is it something you know @ data preparation phase? If so, you could take the computation of `n_sentences` out of model's forward and put there.

It also looks like `hierarchical_padding_mask` is just ones and zeros, which can be computed @ data prep phase, if `n_sentences` can. So I'd move all of this to your `fairseq_dataset`'s `collater`, and pass it to the model's forward. Is this possible?

**Comment by kkissmart** [comment]
seems like a solution.

Let me try it.

**Comment by kkissmart** [comment]
I changed the code,
I have another question. after the change the loop is gone and hierarchical_padding_mask is pre-set during dataprocess.
but my code still has this

        if self.hierarchical_attn is not None:
            residual = x
            hierarchical_x = torch.zeros((self_hierarchical_attn_padding_mask.size(1), x.size(1), x.size(-1))).type_as(x)
            hierarchical_x[~self_hierarchical_attn_padding_mask.transpose(0, 1)] = x[self_hierarchical_x_mask.transpose(0, 1)]

which creates a tensor called hierarchical_x in forward pass and copy some value from original tensor x.
Will this operation create any TPU slow-down?

**Comment by taylanbil** [comment]
yes this looks like it would slow down as well, but perhaps a bit less dramatically;

- looks like `hierarchical_x` is on cpu, and it probably will be sent to tpu later? If the shape of `x` is deterministic, then the shape of `hierarchical_x` will be deterministic, so I suggest moving that to the data prep phase as well.
- I'm assuming `self_hierarchical_attn_padding_mask` or `x` changing over steps. I believe that line causes dynamic graphs. I suggest you rewrite that part as:

```python
ind = self_hierarchical_attn_padding_mask.transpose(0, 1)
hierarchical_x = torch.mul(hierarchical_x, ~ind) + torch.mul(x, ind)
````

this should produce the same result w/o creating a dynamic graph.

@JackCaoG is there a way to always do `index_put` like this on `torch_xla`?

**Comment by kkissmart** [comment]
the shape of torch.mul(hierarchical_x, ~ind) is different from torch.mul(x, self_hierarchical_x_mask.transpose(0, 1))

but the have the same number of non zeros values.

how to walk around this?

**Comment by taylanbil** [comment]
how are they different? more dimensions in one than the other?

**Comment by kkissmart** [comment]
yes. dimension 1  and 2 are the same, but dimension 0 is different (the non-zoros are the same).

**Comment by taylanbil** [comment]
can you `smalltensor.expand_as(largetensor)` and get the expected result? you can prob test this quickly w/ a toy example.

**Comment by kkissmart** [comment]
i want to keep the smalltensor's size for further calculations.. given attn is quadratic, use large tensor is very expensive.
(large tensor is 512, small tensor is 32).

**Comment by taylanbil** [comment]
you could expand the smalltensor out-of-place, to do the addition inside our version of `index_put` properly.

```python
hierarchical_x = torch.mul(hierarchical_x, ~ind1) + torch.mul(x, ind2).expand_as(hierarchical_x)
```

**Comment by kkissmart** [comment]
RuntimeError: The expanded size of the tensor (4) must match the existing size (5) at non-singleton dimension 1.  Target sizes: [2, 4].  Tensor sizes: [2, 5]

do I miss anything here? torch.mul(x, ind2) is (2, 5) it can't be expanded to (2, 4).

**Comment by taylanbil** [comment]
you should not be expanding the big tensor.

What are the exact shapes of tensors in this line:

`hierarchical_x[~self_hierarchical_attn_padding_mask.transpose(0, 1)] = x[self_hierarchical_x_mask.transpose(0, 1)]`

**Comment by kkissmart** [comment]
hierarchical_x : 32*bsz*1024
self_hierarchical_attn_padding_mask.transpose(0, 1): 32*bsz
x: 512*bsz*1024
self_hierarchical_x_mask.transpose(0, 1): 512*bsz

**Comment by taylanbil** [comment]
I haven't been able to rewrite this in a way that would not be dynamic so far. I'd suggest you can unblock yourself by ignoring the flop waste by "given attn is quadratic, use large tensor is very expensive", take the hit and have hierarchical_x be the same shape as x for now.

Question: are the masks you use inside brackets static? if they are always constant, maybe the graph isn't dynamic and we don't need to do anything.

**Comment by kkissmart** [comment]
the mask idxs are dynamic. they are decided by the input tokens in each batch.
Thank you!

**Comment by kkissmart** [comment]
without this optimization -- it takes 4.5min to do 100 steps on V3-8.

it takes 3mins to do 100 steps on 8-V100 GPU.

**Comment by taylanbil** [comment]
@kkissmart we typically compare v3-8s to v100s chip to chip, which amounts to v3-8 vs 4 v100s.

**Comment by kkissmart** [comment]
it is optimized now. thanks! close this issue.
