### ISSUE TITLE
[PT_BREAK] XLA TensorImpl subtype(s) need to override new shallow_copy_and_detach overload

### ISSUE THREAD

**Issue by swolchok** [pytorch/xla#2664]
## Issue description

https://github.com/pytorch/pytorch/pull/48681 added a new overload of this method that is virtual. XLATensorImpl needs to be patched to override this new overload in addition to its existing override (https://github.com/pytorch/xla/blob/master/torch_xla/csrc/tensor_impl.cpp#L65)

## Code example

Dr. CI page: https://dr.pytorch.org/commit-details.html?sha1=866befa5f70a08b405f2dc780b7f7718e8bff085

**Comment by JackCaoG** [comment]
This should be fixed by @ailzhang 's pr on https://github.com/pytorch/xla/pull/2668
