### ISSUE TITLE
device = xm.xla_device() hangs 

### ISSUE THREAD

**Issue by dptam** [pytorch/xla#2667]
Hi, 

I was having an issue with "device = xm.xla_device()" taking a long time on tpu without showing anything. 

I ran the following commands to start the cloud vm and tpu: 
gcloud compute --project=${PROJECT_ID} instances create quick-instance --zone=us-central1-f --machine-type=n1-standard-16  --image-family=torch-xla --image-project=ml-images --scopes=https://www.googleapis.com/auth/cloud-platform
gcloud compute ssh quick-instance --zone=us-central1-f
gcloud compute tpus create quick-tpu --zone=us-central1-f --network=default --version=pytorch-1.6 --accelerator-type=v2-8
export TPU_IP_ADDRESS=$(gcloud compute tpus list --zone=us-central1-f | tail -n 1 | awk '{print $4}')
export XRT_TPU_CONFIG="tpu_worker;0;$TPU_IP_ADDRESS:8470"
conda activate torch-xla-1.6

Then, why I run python and 
import torch_xla.core.xla_model as xm
device = xm.xla_device() 

it freeze. 

I see this is similar to other related issues: #2514? 

Thanks

**Comment by taylanbil** [comment]
you are using 1.6, you should not be running into this issue. are you running this asa script at once? could it be that when you query the tpu ip address, tpu is not ready due to it just having been created, and your xrt_tpu_config is set wrong?

**Comment by dptam** [comment]
Hi, thanks for the comments. 

I was running the commands individually, and saw that the tpu was up and running (ip address was valid and on the console it showed status as green check) before running the later commands. 

Thanks

**Comment by zcain117** [comment]
```
export TPU_IP_ADDRESS=$(gcloud compute tpus list --zone=us-central1-a | tail -n 1 | awk '{p
rint $4}')
export XRT_TPU_CONFIG="tpu_worker;0;$TPU_IP_ADDRESS:8470"
echo $TPU_IP_ADDRESS
  > 10.12.9.178:8470
echo $XRT_TPU_CONFIG
  > tpu_worker;0;10.12.9.178:8470:8470
```
Double check that you don't have an extra port in your string

**Comment by dptam** [comment]
Thanks. It works. That was the bug!
