### ISSUE TITLE
type() not implemented

### ISSUE THREAD

**Issue by foobar8675** [pytorch/xla#2669]
## 🐛 Bug

`t_tpu.type()` gives a 
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-22-28dfc7b21c80> in <module>()
----> 1 t_tpu.type()

RuntimeError: Unimplemented backend XLA
```

## To Reproduce

I added a line to this starter colab

https://colab.research.google.com/drive/1GvKT_jVIymSDlyDjXlG-WNLI63nR-ZWv?authuser=1

Things to avoid in repros is the need to download datasets which require setting up keys or other login information, like Kaggle downloads for example.

-->

see colab

## Expected behavior

I would expect it to give the type.

## Environment

colab

**Comment by JackCaoG** [comment]
Can't access your colab but it is working for me
```
>>> import torch
>>> import torch_xla
>>> import torch_xla.core.xla_model as xm
>>> device = xm.xla_device()
>>> device
device(type='xla', index=1)
>>> device.type
'xla'
```

**Comment by foobar8675** [comment]
sorry about that @JackCaoG , I changed the permissions on the colab.
https://colab.research.google.com/drive/1GvKT_jVIymSDlyDjXlG-WNLI63nR-ZWv?usp=sharing

I was looking for the types on the tensors, and not the device. a snippet is here.

t_tpu = t_cpu.to(dev)
t_tpu.type()

**Comment by JackCaoG** [comment]
can you use `t_tpu.dtype` to workaround?

**Comment by foobar8675** [comment]
yes, I can, I can use a combination of  `t_tpu.device, t_tpu.dtype` to get what I need. I so used to using `type()` i forgot. thanks @JackCaoG !
