### ISSUE TITLE
ipdb.set_trace() not stopping at breakpoints

### ISSUE THREAD

**Issue by foobar8675** [pytorch/xla#2671]
## 🐛 Bug

ipdb.set_trace() not stopping at breakpoints

## To Reproduce
run all for notebook below.
https://colab.research.google.com/drive/1h3qIZJftVH_seLHuuJvG-QQ3N87QmCAq?usp=sharing

see above

## Expected behavior

should stop at breakpoints

## Environment

colab on cpu/tpu

**Comment by JackCaoG** [comment]
I don't think it is a pt/xla specified problem, in `xmp.spawn`, if you set `nprocs=1`, you will see `ipdb` working. 
```
xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=1,
          start_method='fork')
> <ipython-input-15-e9739e6766ba>(12)train_gan()
     11     ipdb.set_trace()
---> 12     torch.manual_seed(1)
     13     mnist_data()

ipdb> 

```

**Comment by foobar8675** [comment]
that is awesome. thank you @JackCaoG

**Comment by taylanbil** [comment]
If you wanted to use `pdb` in a multi-core setting, below is a neat trick. The standard `pdb` or `ipdb` won't work with this, you need something like `fairseq`'s [multi-process pdb](https://github.com/pytorch/fairseq/blob/master/fairseq/pdb.py) to make it work

```
from fairseq import pdb
import torch_xla.core.xla_model as xm
import torch_xla.distributed.xla_multiprocessing as xmp

def main(*a):
    if xm.is_master_ordinal():
        pdb.set_trace()
    xm.rendezvous('hi')
    print('done!')

if __name__ == '__main__':
    xmp.spawn(main, args=(), nprocs=8)
```
