### ISSUE TITLE
TPU stops working

### ISSUE THREAD

**Issue by kkissmart** [pytorch/xla#2676]
## 🐛 Bug

exactly the same code and setting, but since this morning the setting stops working.

## Error
*** End stack trace ***
Failed to connect to client mesh master: heap-base.europe-west4-a.c.birch-research.internal:52997
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    cli_main()
  File "/home/yinhan/bart_modification/fairseq_cli/train.py", line 343, in cli_main
    distributed_utils.call_main(args, main)
  File "/home/yinhan/bart_modification/fairseq/distributed_utils.py", line 183, in call_main
    nprocs=8,  # use all 8 TPU cores
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 394, in spawn
    start_method=start_method)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 205, in start_processes
    while not context.join():
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    exit_code=exitcode
torch.multiprocessing.spawn.ProcessExitedException: process 2 terminated with exit code 17

I tried us-central1-a and europe-west4-a. neither of them works

## Additional context

The same setting worked very well in the last 3 month

**Comment by taylanbil** [comment]
could you please give more info? what torch_xla version, v3-N , etc?

**Comment by kkissmart** [comment]
export VERSION=nightly
conda activate torch-xla-nightly
gcloud compute tpus create heap-base --zone=europe-west4-a  --network=default --version=pytorch-nightly  --accelerator-type=v3-8 --preemptible
gcloud compute tpus list --zone=europe-west4-a
export TPU_IP_ADDRESS=ip-address; \
export XRT_TPU_CONFIG="tpu_worker;0;$TPU_IP_ADDRESS:8470"

python train.py XXX

Then get above error.

**Comment by taylanbil** [comment]
can you run `echo $XRT_TPU_CONFIG` ?

**Comment by kkissmart** [comment]
tpu_worker;0;10.84.156.50:8470

**Comment by taylanbil** [comment]
ok the setup looks ok, could there be a different error in the logs above, maybe during dataloading or something?

**Comment by kkissmart** [comment]
without --tpu arg and  --distributed-world-size 8 , it works fine.

**Comment by kkissmart** [comment]
I think it is a connection issue.. the instance is not able to be connected to TPU, which never happened before.

**Comment by taylanbil** [comment]
are you able to run our train test mp imagenet file w/ fake data ? something like 

`python /usr/share/torch-xla-nightly/pytorch/xla/test/test_train_mp_imagenet.py --fake_data --model=resnet50 --num_epochs=2 --batch_size=128 --log_steps=20`

**Comment by kkissmart** [comment]
no, it doens't work. the same problem.

**Comment by kkissmart** [comment]
I switched to torch-xla-1.7 and it works now. I think you have a bug in nightly. I launched an instance at around 11pm last night. the nightly still worked around that time.

**Comment by taylanbil** [comment]
yes, in fact there seems to be an issue w/ nightly. In the meantime, you can use nightly from yesterday if 1.7 doesn't work for you..

**Comment by kkissmart** [comment]
btw, do you know why 1.7 is slower than nightly? or I am just unlucky to have a slower V3-8?

**Comment by jysohn23** [comment]
On nightly, I've mitigated the issue for now by pinning to yesterday's release while I look for the culprit internally. Will report back once we find cause.

**Comment by taylanbil** [comment]
re: 1.7 vs nightly speed

We'd have to dive deep to understand your 10% speed delta, there could have been an improvement to an op, etc.

**Comment by jysohn23** [comment]
Re: breakage.

Issue should be fixed now.

**Comment by kkissmart** [comment]
thanks, 1.7 is slower than nightly.. it is slower on another arch I have as well. 

I will test nightly and close this issue.
