### ISSUE TITLE
[tests] Decreased Test Coverage

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/xla#2684]
Recently many tests in `test_torch.py` were [moved](https://github.com/pytorch/pytorch/pull/47356) to more relevant test files.

But from the [CI log](https://circleci.com/api/v1.1/project/github/pytorch/pytorch/9551261/output/107/0?file=true&allocation-id=5fd3d593fe701e1fee27a01a-0-build%2F1EFCB0E3), it seems that those files are not being tested.

Files not being tested:
* [ ] test_ops.py
* [ ] test_unary_ufuncs.py
* [ ] test_binary_ufuncs.py
* [ ] test_spectral_ops.py
* [ ] test_reductions.py
* [ ] test_sort_and_select.py
* [ ] test_shape_ops.py

cc: @mruberry

**Comment by JackCaoG** [comment]
@kshitij12345 Thanks for reporting, we will look into adding these test back
