### ISSUE TITLE
 [PT_BREAK]

### ISSUE THREAD

**Issue by eellison** [pytorch/xla#2687]
## 🐛 Bug: pytorch upstream 

Link to PR: https://github.com/pytorch/pytorch/pull/48719#issuecomment-744786206

Some context: we are fixing the lists slicing logic with a negative index. Part of this change involves changing the ir emission for aten::slice to emit None for non-present end value instead of INT_MAX. Rather than have special case logic for all of the builtins type that may or may not support negative striding (lists, tensors, strs) we are updating their implementations so that they can all take in optionals. Actual negative slicing of Tensors is still NYI, but making the schema changes here makes future implementation easier and makes the logic in ir emission cleaner.

**Comment by JackCaoG** [comment]
@eellison Thanks for reporting! Will take a look.

**Comment by JackCaoG** [comment]
@eellison pt/xla pr is ready, I will merge it once pytorch pr merged

**Comment by tugsbayasgalan** [comment]
It seems like when the step size is not supplied from python, it just make it "1" by default. Do you think we should update the slice signature to be (optional int, optional int, int)? @JackCaoG @eellison

**Comment by eellison** [comment]
@tugsbayasgalan i think you can just update your PR and then @JackCaoG will update his PR after (sorry for the churn)

**Comment by tugsbayasgalan** [comment]
Hi @JackCaoG and @eellison,

Actually can we update the signature of slicing to [c10::optional<int64_t> start, c10:optional<int64_t> end, int64_t step]? We realized python makes the step size 1 if nothing is provided. So making it an actual integer makes more sense. Let me know if you need more context

**Comment by JackCaoG** [comment]
> Hi @JackCaoG and @eellison,
> 
> Actually can we update the signature of slicing to [c10::optional<int64_t> start, c10:optional<int64_t> end, int64_t step]? We realized python makes the step size 1 if nothing is provided. So making it an actual integer makes more sense. Let me know if you need more context
> 
> Our current PR ([pytorch/pytorch#49352](https://github.com/pytorch/pytorch/pull/49352)) assumes the step size is an integer, not optional integer

will update pt/xla pr, thanks for the update!

**Comment by tugsbayasgalan** [comment]
@JackCaoG I am just checking in whether you had time to look at it :)?

**Comment by JackCaoG** [comment]
@tugsbayasgalan pt/xla pr is ready, I will merge it once pytorch one is merged

**Comment by tugsbayasgalan** [comment]
@JackCaoG  thanks for the heads up! the PR is merged
