### ISSUE TITLE
Two many sub computation graphs per step harms the training speed?

### ISSUE THREAD

**Issue by eedalong** [pytorch/xla#2696]
## ❓ Questions and Help
I am trying to use xla to train a model, and I have not seen speed gains from xla. I found that every step there are 12 subgraphs executed. I wonder whether switch to many between subgraphs in a single step will cause a severe speed drop ? Thx!

**Comment by eedalong** [comment]
@ailzhang

**Comment by taylanbil** [comment]
Are your graphs changing from one step to the next in a dynamic way? If so, you may be suffering from too many compilations. [Here](https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#known-performance-caveats)'s the known performance caveats.

If they are not changing too much, just the sheer number of subgraphs should not be a problem in and of itself.

**Comment by eedalong** [comment]
graph is static across steps, just the number of subgraphs is 12.  So this will not cause problems in executing right?

**Comment by taylanbil** [comment]
Yes, having 12 graphs in and of itself is fine. If the graphs are large and execution does not fit in to the TPU HBM, it may need to swapping in the TPU VM and thus cause slowness, or straight up HBM OOM and a crash.
