### ISSUE TITLE
lowering upsample_bilinear2d 

### ISSUE THREAD

**Issue by matthewchung74** [pytorch/xla#2703]
## 🚀 Feature
A request for a lowering of upsample_bilinear2d_backward
reference https://github.com/pytorch/xla/issues/2702

(and these 2 as well)
Counter: aten::_local_scalar_dense
Counter: aten::isnan

## Motivation
stylegan makes use of nn.Upsample for its generator, which is causing a call to `grad` to be very slow.  please see 
https://colab.research.google.com/drive/1MEyQ2KMDn1IjxJ2FLHcEgmySBlWNuR5q?usp=sharing
 
## Pitch

I noticed this because my calls using perceptual path length were slow, ie 9 seconds per step. (when doing 100k steps for a GAN, it can be a big slow down)  you can see the example in the colab above. lowering it would make it faster and thus stylegan would be feasible on pytorch tpu

## Alternatives

I don't know of any

**Comment by JackCaoG** [comment]
Hmm, weird. `upsample_bilinear2d ` should be lowered in 
https://github.com/pytorch/xla/blob/1a56d70a9a48446536912d80c6f929519453258e/torch_xla/csrc/aten_xla_type.cpp#L3351

It might be that `scales_h ` and `scales_w ` is not 1.0 so it fallback to CPU

**Comment by JackCaoG** [comment]
Reopening this bug, we should support scale-factor. I think all we need to do is to use `scale_factor` to recompute the output shape which should be trivial.

**Comment by miladm** [comment]
@sy323 please work with @vanbasten23 to ramp up on this ticket.
