### ISSUE TITLE
Is there a similar argument like steps_per_execution in tf?

### ISSUE THREAD

**Issue by rwbfd** [pytorch/xla#2710]
## Is there a similar argument like steps_per_execution in TensorFlow. 

In tensorflow you can specify how much steps_per_execution, which basically controls how much steps you run inside the TPU. It is a very important parameter as it will make the training much faster. I wonder whether there is an equivalent in PyTorch XLA?

**Comment by taylanbil** [comment]
we execute graphs and materialize tensors every time `xm.mark_step` is called. `torch_xla`'s iterators call `mark_step` every time [they yield](https://github.com/pytorch/xla/blob/master/torch_xla/distributed/parallel_loader.py#L37), so if you wanted to do many steps per execution, you could achieve that by yielding N batches in your iterator (that you may wrap with `pl.MpDeviceLoader` and process the batches. Be careful as the graphs growing too large sometimes cause swapping or HBM OOM.

Alternatively, we could change `per_device_loader` and mark_step every `N` times, defaulting N to 1.

**Comment by rwbfd** [comment]
@taylanbil Thanks for the timely reply. I will try the second methods. I don't want to make it too intrusive. I might need some pointers on who calls the `next` methods in `per_device_loader`. That will greatly help me.
