### ISSUE TITLE
tpu is 30% faster with nightly

### ISSUE THREAD

**Issue by kkissmart** [pytorch/xla#2711]
I observed a 30% faster Word per second on env nightly.

However, my image is old, which was created 30 days ago. The question is, do I need to create a new image to have an even better speed or 30% faster is already what is expected.

Thank you so much for the effort. 30% means a lot to us.

**Comment by taylanbil** [comment]
That sounds great :) I don't understand the question though. There are changes that affect some ops and leaves others intact, so some workloads may not be affected.

**Comment by kkissmart** [comment]
I have created some images a month ago. To fully take advantage of your new changes, should I re-create new images?

**Comment by taylanbil** [comment]
Yes, to get the latest and greatest, we recommend getting the official releases or the current nightly. You could update your existing conda environment to latest nightly by running the [update wheels script](https://github.com/pytorch/xla/blob/master/scripts/update_nightly_torch_wheels.sh).

**Comment by kkissmart** [comment]
Observed another 15% improvement on top the 30% last week! Good job!!! Thank you!!!!!
