### ISSUE TITLE
MpDeviceLoader is slower than DataLoader

### ISSUE THREAD

**Issue by tmabraham** [pytorch/xla#2723]
I created a starter kernel for the Kaggle competition using PyTorch XLA and TPU environment over [here](https://www.kaggle.com/tanlikesmath/cassava-pytorch-xla-tpu-starter-training). In [this version](https://www.kaggle.com/tanlikesmath/cassava-pytorch-xla-tpu-starter-training?scriptVersionId=50978912) I defined an `MpDeviceLoader` but forgot to use it, so it was actually directly running with the `DataLoader` (I had put the `DataLoader`-returned tensors on the TPU though). I have since switched to using the `MpDeviceLoader` but noticed a few things:
1. The highest batch size without running into host OOM for `MpDeviceLoader` is 64 (with `num_workers=0`) while for just using the `DataLoader`, it is 128 (with `num_workers=4`).
2. Specifically, after very epoch, the memory usage increases a little bit until it reaches host OOM.
3. Training with the `MpDeviceLoader` is significantly slower compared to with the 	`DataLoader` (likely because of the lower batch size and `num_workers`).

With this said, I have a few questions:
1. Why does `MpDeviceLoader` have higher memory usage over using a regular PyTorch `DataLoader`?
2. Are there any arguments or code that can be used to improve the memory usage of `MpDeviceLoader`?
3. Would there be any disadvantage to sticking with the `DataLoader` instead of using the `MpDeviceLoader`?

**Comment by taylanbil** [comment]
MpDeviceLoader _should_ not have significantly higher memory usage over DataLoader, it's a simple wrapper around DataLoader that pre-fetches some batches and sends to device in the background. We never observed this behavior before. Can you provide a colab so we can reproduce this behavior on our end? Could there be another difference b/w two notebooks, that's causing this behavior?

Sticking to DataLoader will force you to send the input batches to device one by one, and it'll block execution until the data is transferred to device. MpDeviceLoader does this in the background in an efficient fashion.

**Comment by tmabraham** [comment]
@taylanbil I re-checked my code and noticed that the MpDeviceLoader was re-initialized every epoch (like is done in the example PyTorch XLA Colab notebooks) while my code with plain DataLoaders only initialized them once at the beginning. Fixing this lead to similar memory usage and speeds.


Why is re-initializing every epoch the default use of MpDeviceLoader/ParallelLoader?

**Comment by taylanbil** [comment]
I don't understand; [here](https://github.com/pytorch/xla/blob/master/test/test_train_mp_imagenet.py#L231-L236)'s the correct way of using `MpDeviceLoader`. `ParallelLoader` has to be re-initialized at the beginning of every epoch by calling `.per_device_loader(device)`, but `MpDeviceLoader` handles it automatically.

Glad the issue was resolved, but I don't understand what the issue was in the first place :)

**Comment by tmabraham** [comment]
@taylanbil Ah okay I was looking at these Colab notebooks that were using ParallelLoader and thought the MpDeviceLoader usage similar:
https://github.com/pytorch/xla/blob/master/contrib/colab/resnet18-training.ipynb
https://github.com/pytorch/xla/blob/master/contrib/colab/multi-core-alexnet-fashion-mnist.ipynb
