### ISSUE TITLE
 The project happend ProcessExitedException on colab with No obvious error message

### ISSUE THREAD

**Issue by sugangsky** [pytorch/xla#2725]
## ❓ Questions and Help
This is my project on colab [here]。(https://colab.research.google.com/drive/1mgtHa_qPtUr2jSDk1sXK0bXpKEmI51Lf?usp=sharing) it finished with ProcessExitedException, and it's error message is not clear.

@taylanbil

**Comment by taylanbil** [comment]
Any way for us to reproduce this? Seems it would not run on our side due to dataset not being present.

Does this happen w/ 1 core? `xmp.spawn(map_fn, args=(params,), nprocs=1, start_method='fork')`

**Comment by sugangnb** [comment]
if i set the nprocs=1 and num_workers =1 ，the colab will crash and restart.

**Comment by sugangnb** [comment]
the cloab crash log 
![image](https://user-images.githubusercontent.com/31402401/104257242-f3be1080-54b7-11eb-82cc-40d6ebd7ad76.png)

**Comment by taylanbil** [comment]
hard to debug without repro, but you have a high batch size, which makes me think host may be running out of memory.

**Comment by sugangnb** [comment]
after testing, I sure it is except at this line .
![image](https://user-images.githubusercontent.com/31402401/104429100-323ef280-55c0-11eb-8dfc-07366ad5a58a.png)

**Comment by taylanbil** [comment]
Are you using the latest nightly version?

Can you try lowering your batch size on 1 core?

**Comment by ademyanchuk** [comment]
I would like to add a bit. I can't reproduce tutorial example [**"PyTorch on Cloud TPUs: MultiCore Training AlexNet on Fashion MNIST"**](https://colab.research.google.com/github/pytorch/xla/blob/master/contrib/colab/multi-core-alexnet-fashion-mnist.ipynb) Colab notebook. Stable release and 8 cores gives me 600 seconds training and 30 seconds evaluation.
And "nightly build" is crashing with the same "ProcessExitedException".

I can also see those stack trace from C++ perhaps: 

> Failed to connect to client mesh master: 457eb84c329c:60271
Exception in device=TPU:7: tensorflow/compiler/xla/xla_client/mesh_service.cc:316 : Check failed: impl_->channel->WaitForConnected( std::chrono::system_clock::now() + std::chrono::seconds(connect_wait_seconds))

**Comment by taylanbil** [comment]
@ademyanchuk your issue, even though it is the same symptom, is probably different. we think we have resolved that one, could you try again?

**Comment by ademyanchuk** [comment]
Hi, @taylanbil Thank you for quick reply. I fast checked on official Resnet18 example (which I am using as a template for my project). It is now working without any issues on "nightly" build. Thanks again. Cheers))
