### ISSUE TITLE
Dropout slows down speed

### ISSUE THREAD

**Issue by kkissmart** [pytorch/xla#2730]
I have a very interesting finding -- without dropout the speed is 1.3X than that with dropout. The same image, same data, and same code.

Anything I can do here to improve? for those with drpouts to catch?

Thanks

**Comment by taylanbil** [comment]
yes this is known, see https://github.com/pytorch/xla/issues/2636

that issue contains a lot of experiments with dropout, and it is not fully up to date with the latest findings. Internal investigations still going on.

**Comment by taylanbil** [comment]
@kkissmart can you try w/ the latest nightly? dropout should be fast now per https://github.com/pytorch/xla/issues/2636#issuecomment-769481853

**Comment by taylanbil** [comment]
closing, please reopen if needed.
