### ISSUE TITLE
How to install Torch_XLA in my own laptop?

### ISSUE THREAD

**Issue by Huntersts** [pytorch/xla#2733]
## ❓ Questions and Help
I want build a envirment about Torch_XLA on my own laptop by Annconda3. But I do not find any information about this. Is it difficult to use Annconda3 or pip install Torch_XLA?

**Comment by JackCaoG** [comment]
https://github.com/pytorch/xla/blob/master/CONTRIBUTING.md has the instruction to build pt/xla from scrath. You can also install wheel like
```
!pip install cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.7-cp36-cp36m-linux_x86_64.whl
```
[reference](https://github.com/pytorch/xla/blob/02e270008cfabb6417e07d28d469764e3c795c8c/contrib/colab/xla_builder_autograd.ipynb)

**Comment by Huntersts** [comment]
Thanks

**Comment by JackCaoG** [comment]
I will close this issue for now, feel free to reopen if you encountered any more problems.

**Comment by raman-rajarathinam** [comment]
I tried installing `master` to my work env by running `pip install git+https://github.com/pytorch/xla`, which exited with some error.
Can anyone tell me how to install from master?

**Comment by JackCaoG** [comment]
We don't expect `pip install git+https://github.com/pytorch/xla` to work, if you want to build from scratch, please refer to https://github.com/pytorch/xla/issues/2733#issuecomment-760612734
