### ISSUE TITLE
more than 10 times performance degradation with official installation method

### ISSUE THREAD

**Issue by world2vec** [pytorch/xla#2747]
Hi,
Please refer colab notebook,  [official](https://drive.google.com/file/d/1la8AZK4wZ2KtOxGFkWRQr9w3_iuCC9sz/view?usp=sharing) [unofficial](https://drive.google.com/file/d/1fVwtYhjaCmfBgL87sIBduvofiVQ0slBr/view?usp=sharing)

The only difference is the tpu section, see train section for log.
The colab currently use pytorch 1.7, it is same problem with 1.6.
I suspect the performance problem was introduced since we have cloud-tpu-client==0.10

Could you check if this is as expected? 
Can I expect the performance issue will not exist in feature release like 1.8 1.9...?

**Comment by zcain117** [comment]
It seems like your model is fast on `nightly` and slow on `torch-xla-1.7`?

It's possible one of our recent changes helped the performance?

If you include some TPU metrics then we can look at them to see where the big time differences happened

**Comment by world2vec** [comment]
I am not sure if there is change in nightly improve performance. I suspect performance problem may existed for a long time.
Just want if whatever changes made in nightly, it will include in future release.
Thanks.

**Comment by zcain117** [comment]
Yes, generally speaking our release flow is just to snapshot the current nightly build on a certain date. Then we test the build thoroughly for all our supported models and unit tests, and cherrypick in any fixes if needed. Then we release the build once we think it's stable

**Comment by world2vec** [comment]
Thanks.
I will double check  when 1.8 released.

**Comment by world2vec** [comment]
problem was disappear in 1.8
Thanks
