### ISSUE TITLE
My training code freezes with multiprocess TPU on Google Cloud Platform

### ISSUE THREAD

**Issue by AugustasMacys** [pytorch/xla#2749]
Hello, I have a VM which is on Google Cloud Platform. It is n1 with 60Gb of ram. I read that training usually freezes when there is not enough of memory. However, after doing _free -h_ I can see that there is around of 30Gb free. The way I know that the code freezes is because I have both print statements and log file and I can see that after some time (always during the very first epoch) log file does not change and there are no print statements.

I attach my notebook, the training code is at the end. Moreover, I attach the log file which shows that until the code freezes, a lot of pictures are being read at a very fast speed which is good because code works fastly until it freezes.

One important thing to mention that the code freezes at random batch iteration but always on the very first epoch and no error is being thrown.

I tried researching the problem and I read articles like:
https://github.com/pytorch/xla/issues/1562

However, I could not resolve my problem and to be fair I am not even sure what is the problem and why the code freezes.
The code is run in jupyter notebook when I ssh to my VM.

Pytorch Version: 1.6.0
XLA Version: 1.6
TPU version: pytorch-1.6
[training_log_xla_support.log](https://github.com/pytorch/xla/files/5857181/training_log_xla_support.log)

I upload the logs and my code for training to Google Colab and I hope I can get someone to help me to point what is wrong:
https://colab.research.google.com/drive/1DOTbzGD9meJPfc2yjSJ1z2nZRqLIj2rx?usp=sharing

If you do not want to open Colab, this is the training code:

```
MAX_ITERATIONS = 100000
BATCHES_PER_EPOCH = 5000

model_save_path = r"lowest_loss_model.pth"

import torch_xla
import torch_xla.core.xla_model as xm
import torch_xla.distributed.parallel_loader as pl
import torch_xla.distributed.xla_multiprocessing as xmp
import torch_xla.debug.metrics as met

FLAGS = {
    'batch_size': 128,
    'num_workers': 4,
    'world_size': 8,
    'epochs': 20,
    'log_steps': 10,
    'metrics_debug': False
}

WRAPPED_MODEL = xmp.MpModelWrapper(DeepfakeClassifier())

def train_model(rank, FLAGS):
    print("Starting train method on rank: {}".format(rank))
    device = xm.xla_device()
    since = time.time()
    minimum_loss = 0.48
    iteration = 0
    
    model = WRAPPED_MODEL.to(device)
    criterion = F.binary_cross_entropy_with_logits
    lr = 0.005 * xm.xrt_world_size()
    optimizer_ft = optim.SGD(model.parameters(), lr=lr, momentum=0.9, weight_decay=1e-4, nesterov=True)
    lr_scheduler = optim.lr_scheduler.StepLR(optimizer_ft, step_size=1, gamma=0.9)
    
    train_real_df = pd.read_csv(PAIR_REAL_DATAFRAME)
    train_fake_df = pd.read_csv(PAIR_FAKE_DATAFRAME)
    val_df = pd.read_csv(VALIDATION_DATAFRAME_PATH)
    
    probability_distribution = distributions.beta.Beta(0.5, 0.5)
    with open('non_existing_files.pickle', 'rb') as fp:
        non_existing_files = pickle.load(fp)
    
    train_dataset = DeepfakeDataset(train_real_df, train_fake_df, augmentation_pipeline(), non_existing_files, rank)
    train_sampler = torch.utils.data.distributed.DistributedSampler(train_dataset, num_replicas=FLAGS['world_size'], rank=rank, shuffle=True)
    train_loader = DataLoader(train_dataset, batch_size=FLAGS['batch_size'], sampler=train_sampler, num_workers=FLAGS['num_workers'], collate_fn=collate_fn, drop_last=True)
    
    validation_dataset = ValidationDataset(val_df, validation_augmentation_pipeline())
    validation_sampler = torch.utils.data.distributed.DistributedSampler(validation_dataset, num_replicas=FLAGS['world_size'], rank=rank, shuffle=False)
    validation_loader = DataLoader(validation_dataset, batch_size=FLAGS["batch_size"], sampler=validation_sampler, shuffle=False,
                                   num_workers=FLAGS['num_workers'], drop_last=False)
    
    print("Datasets initialised")
    
    dataset_size = {
        "val": len(validation_loader.dataset)
    }
    val_size = dataset_size["val"]

    for epoch in range(FLAGS['epochs']):
        gc.collect()
        batch_number = 0
        if iteration == MAX_ITERATIONS:
            break
            
        
        para_train_loader = pl.ParallelLoader(train_loader, [device]).per_device_loader(device)
        
        logging.info('Epoch {}/{}'.format(epoch, FLAGS['epochs'] - 1))
        logging.info('-' * 10)

        model.train()  # Set model to training mode

        running_training_loss = 0
        total_examples = 0
        for pairs in para_train_loader:
            iteration += 1
            batch_number += 1
            fake_images = pairs['fake']
            real_images = pairs['real']
            
            target = probability_distribution.sample((len(fake_images),)).float().to(device)
            
            fake_weight = target.view(-1, 1, 1, 1)

            input_tensor = (1.0 - fake_weight) * real_images + fake_weight * fake_images

            current_batch_size = input_tensor.shape[0]
            total_examples += current_batch_size

            outputs = model(input_tensor)
            y_pred = outputs.squeeze()
            loss = criterion(y_pred, target)
            
            if batch_number % 50 == 0:
                # since the loss is on all 8 cores, reduce the loss values and print the average (as defined in reduce_fn)
                loss_reduced = xm.mesh_reduce('loss_reduce', loss, reduce_fn) 
 
                xm.master_print(f'batch number={batch_number}, loss={loss_reduced}')

             # zero the parameter gradients
            optimizer_ft.zero_grad()
            loss.backward()
            
            xm.optimizer_step(optimizer_ft)
            lr_scheduler.step()
            
            logging.info("Batch Number: {}, Rank Number: {}".format(batch_number, rank))
            print("Batch Number: {}, Rank Number: {}".format(batch_number, rank))
            
            if batch_number >= BATCHES_PER_EPOCH:
                break

        # Calculate Validation Loss
        del para_train_loader
        gc.collect()
        validation_loss = evaluate(model, minimum_loss, device)
        gc.collect()
        logging.info(validation_loss)

        if FLAGS['metrics_debug']:
            xm.master_print(met.metrics_report())

        # deep copy the model
        if validation_loss < minimum_loss:
            minimum_loss = validation_loss
            logging.info("Minimum loss is: {}".format(minimum_loss))
            minimum_loss_str = str(round(minimum_loss, 5))
            save_path_model = minimum_loss_str + model_save_path 
            torch.save(model.state_dict(), model_save_path)

    time_elapsed = time.time() - since
    
    logging.info('Training complete in {:.0f}m {:.0f}s'.format(
        time_elapsed // 60, time_elapsed % 60))
    logging.info('Loss: {:4f}'.format(minimum_loss))

    # load best model weights
    model.load_state_dict(torch.load(model_save_path))
    return model
```

xmp.spawn(train_model,nprocs=FLAGS['world_size'], args=(FLAGS,), start_method='fork')

I know that in order to read the files you need to connect to google cloud storage, but hopefully, this will not be needed.

**Comment by taylanbil** [comment]
sorry for the delayed response. One thing I'm noticing is, you are sampling the validation dataset, but you've turned off `drop_last`, so it may be that the validation iterators are of different length. That would cause a hang, because the cores w/ extra batch will wait for the other cores to join the rendezvous, but that'll never happen. I'm not sure if this is the case since I'm not able to repro, but could you update the drop last in

```python
    validation_loader = DataLoader(validation_dataset, batch_size=FLAGS["batch_size"], sampler=validation_sampler, shuffle=False,
                                   num_workers=FLAGS['num_workers'], drop_last=False)
```

to `True` ?

**Comment by AugustasMacys** [comment]
Hi @taylanbil ,

I wanted to notify you that I tried your suggestion and it did not help. However, I looked through my flag values again and I a bit played with them and when I set **num_workers** to 0 the code works and not freezes. However, the code is much slower. I have tried looking for information and I found: https://github.com/pytorch/xla/issues/1184

which states that num_workers should be around: **NUM_CPU_CORES - NUM_TPU_CORES**, so using num_workers=4 should have worked. I run my code on JupyterLab in case that would help.

**Comment by taylanbil** [comment]
This sounds like the issue lies in the data-loading part. if you set num workers to 0, main process does the loading. If you set it to 1+, a subprocess is spawned that processes and loads the data.

The root cause can lie in several places; maybe the loading pipeline is not coded up correctly, or maybe the spawned subprocesses are put to sleep by the jupyter notebook, etc. Could you try the following:

- Run the python script from the command line, not thru jupyter, w/ num_workers 4 and see if hangs.
- If that hangs, try to just iterate through the batches instead of training (insert a `continue` after `        for pairs in para_train_loader:
`), 
- If that hangs, just iterate `train_loader` instead of `para_train_loader`, and see if that iterates w/o hang.

**Comment by taylanbil** [comment]
you can also run w/ 1 core, num_workers 4 and see if that hangs as well.

**Comment by AugustasMacys** [comment]
Thanks very much @taylanbil I have not looked into it after yesterday, but I will have a look again tomorrow.

**Comment by zcain117** [comment]
When using multiprocessing, each process will use num_workers

So effectively it will try to spin up 8 * num_workers processes. I'd recommend setting num_workers to be equal or less than num_cpu_cores/8, otherwise you'll get CPU cores swapping between workers and it will get very slow

When I train resnet for example, I use a 64-core VM and I use num_workers=8
