### ISSUE TITLE
Cannot replicate if number of devices (1) is different from 8

### ISSUE THREAD

**Issue by alexander-soare** [pytorch/xla#2753]
## ❓ Questions and Help

I'm working on a Kaggle notebook and keep getting the error in the title

My code now looks like:

```
# This is not a fully working training loop, I'm just building up to it while trying to catch bugs
def _mp_fn(index):
    device = xm.xla_device()
    model = Modle()
    model.to(device)
    
    loss_fn = nn.BCEWithLogitsLoss()
    optimizer = torch.optim.SGD(model.parameters(), lr=2e-3)
    
    for data in tqdm(pl.MpDeviceLoader(data_loaders.train_loader, device)):
        optimizer.zero_grad()
        outputs = model([data['wf'], None])

xmp.spawn(_mp_fn, args=(), nprocs=8, start_method='fork')
```

Note that I have not run `xm.xla_device()` anywhere else in the code ([doing so outside of `_mp_fn` is one reason this error might be raised](https://github.com/PyTorchLightning/pytorch-lightning/issues/3169)).

I've also checked `xm.get_xla_supported_devices()` which gives `['xla:1', 'xla:2', 'xla:3', 'xla:4', 'xla:5', 'xla:6', 'xla:7', 'xla:8']`

One thing I noticed is that it DID WORK the first time around. But after playing around with my code and fixing bugs it started raising that error.

Restarting the kernel is not a good option is it takes a long time to set up.

**Comment by 1374839016** [comment]
Can you share your notebook?I also have this issue yesterday,but I delete xm.xla_device() outside of _mp_fn,and restart the kernel,the bug was fixed.

**Comment by alexander-soare** [comment]
@1374839016 just like you I had the same issue and fixed it that way. But like I mention, somehow it reappears by some other means. Unfortunately I can't share the kernel as it's against Kaggle rules. I may be able to whittle it down to something minimum reproducible though. Was hoping to get some suggestions without having to do that though as it would probably take me more than 30 mins to do.

**Comment by 1374839016** [comment]
I hope you use other public kernels as the basis and add the functions you need instead of migrating your kernel from GPU to TPU, which is easy to go wrong.

**Comment by 1374839016** [comment]
I hope you use other public kernels as the basis and add the functions you need instead of migrating your kernel from GPU to TPU, which is easy to go wrong. @alexander-soare

**Comment by alexander-soare** [comment]
I was migrating my own kernel. I feel like both can easily go wrong, but I'd rather gain a solid understanding of how to use the library.
