### ISSUE TITLE
How can I make a large repo like https://github.com/UKPLab/sentence-transformers compatible for TPU training?

### ISSUE THREAD

**Issue by AmitChaulwar** [pytorch/xla#2754]

**Comment by jysohn23** [comment]
I'd first recommend you read through our https://github.com/pytorch/xla/blob/master/API_GUIDE.md on the basics of `xm.xla_device()`, `pl.MpDeviceLoader`, `xmp.spawn`, `xm.optimizer_step`, `xm.save`. Also check out https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md especially around `Known Performance Caveats` as XLA TPU programming model can be at first confusing for new users. Then basically insert all above APIs throughout that repos stack would be my recommendation.
