### ISSUE TITLE
TypeError: 'mappingproxy' object does not support item assignment

### ISSUE THREAD

**Issue by tchaton** [pytorch/xla#2773]
## To Reproduce

The callbacks type in the checkpoint created by this function raised `TypeError: 'mappingproxy' object does not support item assignment` when running xm.save(checkpoint, ...)

```
    def on_save_checkpoint(self):
        """Called when saving a model checkpoint."""
        callback_states = {}
        for callback in self.callbacks:
            callback_class = type(callback)
            state = callback.on_save_checkpoint(self, self.get_model())
            if state:
                callback_states[callback_class] = state
        return callback_states
```

Would it be possible for you to support resolve this bug, as it is currently breaking PyTorch Lightning TPU support for callbacks states. 

1.
2.
3.

## Environment

 - Reproducible on XLA backend [CPU/TPU]:
 - torch_xla version:

**Comment by zcain117** [comment]
I am able to run e.g. `xm.save(model.state_dict(), 'mnist-xm-save.pth')` and it works as intended

How were you trying to use `xm.save`?

**Comment by tchaton** [comment]
Hey @zcain117,

yes, state_dict works fine, but in PyTorch Lightning, we will save the trainer states too (callbacks, etc ...)

In TPUSpawn, I had to remove callbacks to avoid this error as it seems type can't be saved.
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/plugins/training_type/tpu_spawn.py#L306

Modify this line to trigger the error:
```
self.save(checkpoint, filepath)
```

Best,
T.C

**Comment by zcain117** [comment]
repro steps:
```
create VM:
gcloud compute instances create zcain-vm
--zone=us-central1-a
--machine-type=e2-highmem-16
--image-family=torch-xla
--image-project=ml-images
--boot-disk-size=300GB
--scopes=https://www.googleapis.com/auth/cloud-platform
create TPU:
gcloud compute tpus create zcain-tpu
--zone=us-central1-a
--network=default
--version=pytorch-nightly
--accelerator-type=v3-8
SSH into VM:
(VM) git clone https://github.com/PyTorchLightning/pytorch-lightning.git
(VM) conda activate torch-xla-nightly
(VM) export TPU_IP_ADDRESS=<TPU's IP address>
(VM) export XRT_TPU_CONFIG="tpu_worker;0;$TPU_IP_ADDRESS:8470"
(VM) cd pytorch-lightning
(VM) pip install .
(VM) pip install -r requirements/test.txt
(VM) cd pl_examples/domain_templates/
(VM) vim computer_vision_fine_tuning.py
(VM) <replace GPUs arg with tpu_cores=8,>
(VM) python computer_vision_fine_tuning.py
```
If I use `torch-xla-nightly` I get an unrelated crash that seems to be because of Tensorboard

If I use `torch-xla-1.8` I get a crash like this:
```
  File "/anaconda3/envs/torch-xla-1.8/lib/python3.6/site-packages/pytorch_lightning/plugins/training_type/tpu_spawn.py", line 116, in new_process
    results = trainer.run_stage()
  File "/anaconda3/envs/torch-xla-1.8/lib/python3.6/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 646, in _save_top_k_checkpoint
    self._update_best_and_save(current, epoch, step, trainer, monitor_candidates)
  File "/anaconda3/envs/torch-xla-1.8/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 535, in run_stage
    self.run_train()
  File "/anaconda3/envs/torch-xla-1.8/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 535, in run_stage
    self.run_train()
  File "/anaconda3/envs/torch-xla-1.8/lib/python3.6/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 708, in _update_best_and_save
    self._save_model(trainer, filepath)
  File "/anaconda3/envs/torch-xla-1.8/lib/python3.6/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 410, in _save_model
    self._do_save(trainer, filepath)
  File "/anaconda3/envs/torch-xla-1.8/lib/python3.6/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 422, in _do_save
    self.save_function(filepath, self.save_weights_only)
  File "/anaconda3/envs/torch-xla-1.8/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 599, in run_train
    self.train_loop.run_training_epoch()
  File "/anaconda3/envs/torch-xla-1.8/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 599, in run_train
    self.train_loop.run_training_epoch()
  File "/anaconda3/envs/torch-xla-1.8/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 499, in run_training_epoch
    self.trainer.run_evaluation(on_epoch=True)
TypeError: 'mappingproxy' object does not support item assignment
```

If I use `torch-xla-1.7`, then I get the same crash.

@tchaton it seems like your CI is using `torch-xla-1.7`, since I see a line like this: `Downloaded newer image for pytorchlightning/pytorch_lightning:base-xla-py3.6-torch1.7`. It seems like there is a test to run with disabled checkpoints here: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/tests/models/test_tpu.py#L391

Some of my questions:
1. Is there a CI test that runs with checkpointing enabled, and if so, what version of torch-xla is it using and is it passing?
2. How new is the behavior to save checkpoints plus these callback states?
3. Was there ever a version of `torch-xla-1.8` that worked, maybe before the changed saving behavior?

**Comment by zcain117** [comment]
Ok I think I understand better now:
* there was some new checkpointing behavior added but it doesn't work yet on TPUs, so you built a `checkpoint_callback` flag in the `trainer` to avoid the new behavior. So now your CI is using that flag and that's why it passes.
    * I think the CI is still using 1.7 though (correct me if I'm wrong)
* I verified that training works (at least for `pl_examples/domain_templates/computer_vision_fine_tuning.py`) when using this flag for both `torch-xla-1.7` and `torch-xla-1.8`. I just have to change like this:

```
(torch-xla-nightly) zcain@zcain-vm:~/pytorch-lightning/pl_examples/domain_templates$ git diff computer_vision_fine_tuning.py 
diff --git a/pl_examples/domain_templates/computer_vision_fine_tuning.py b/pl_examples/domain_templates/computer_vision_fine_tuning.py
index 4e148a18..09297baa 100644
--- a/pl_examples/domain_templates/computer_vision_fine_tuning.py
+++ b/pl_examples/domain_templates/computer_vision_fine_tuning.py
@@ -328,9 +328,9 @@ def main(args: argparse.Namespace) -> None:
         weights_summary=None,
         progress_bar_refresh_rate=1,
         num_sanity_val_steps=0,
-        gpus=args.gpus,
+        tpu_cores=8,
         max_epochs=args.nb_epochs,
-        callbacks=[finetuning_callback]
+        checkpoint_callback=False,
     )
 
     trainer.fit(model, datamodule=datamodule)
```

So the goal is to figure out why the new checkpointing behavior doesn't work so that we can stop using the `checkpoint_callback` flag

**Comment by edenlightning** [comment]
@zcain117 let us know if there's work required on the lighting side

**Comment by zcain117** [comment]
Could you share what kind of object is having trouble being saved? And a minimal repro?

**Comment by zcain117** [comment]
the repro I shared above no longer works for me, so I'm wondering if you have any suggested method.

I am doing this:
1. create VM
2. create TPU
3. (inside vm) `git clone https://github.com/PyTorchLightning/pytorch-lightning.git`
4. (inside vm) modify as needed - I added `self.save(checkpoint, filepath)`
5. (inside vm) `cd pytorch-lightning`
6. (inside vm) `pip install .`
7. (inside vm) `pip install -r requirements/test.txt`
8. (inside vm) `conda activate torch-xla-1.8`
9. (inside vm) `export TPU_IP_ADDRESS=10.80.11.2`
10. (inside vm) `export XRT_TPU_CONFIG="tpu_worker;0;$TPU_IP_ADDRESS:8470"`
11. (inside vm) `cd pl_examples/domain_templates/`
12. (inside vm) `vim computer_vision_fine_tuning.py` - replace `gpus` with `tpu_cores=8` in the `trainer`
12. (inside vm) `python computer_vision_fine_tuning.py`

Result: very slow to get started, maybe ~15min to start training. Training made it to:
```
Epoch 0:  98%|██████████████████████████████▎| 47/48 [02:16<00:02,  2.91s/it, loss=0.647, v_num=0, train_acc=0.375^CTraceback (most recent call last):███████████████████████████████████████████▉    | 15/16 [00:24<00:00,  3.80it/s]
```

Then it hung for 10+ minutes before I killed it. I tried the same machine+TPU on a different [test](https://github.com/pytorch/xla/blob/master/test/test_train_mp_mnist.py) and it ran at normal speed (64-core CPU machine).

Please let me know:
1. is there a better method I should use to find the error, maybe a simpler minimal repro
2. any advice for setup to avoid hanging
3. what version of torch-xla is your CI using and is it passing?
4. Was there ever a version of torch-xla-1.8 that worked, maybe before the changed saving behavior?

**Comment by kaushikb11** [comment]
Hi @zcain117 @JackCaoG, you could reproduce the issue in the following steps:

1. pip install lightning-flash[image]
2. Add `tpu_cores=8` in the Trainer object in this [script](https://github.com/PyTorchLightning/lightning-flash/blob/master/flash_examples/finetuning/image_classification.py).

**Comment by zcain117** [comment]
repro is like this:

1. create TPUVM (Kaushik mentioned it also happens on 2VM) - must use `v2-alpha` since `v2-nightly` seems completely broken for PyTorch right now (I pinged the internal hangouts chat about that)
2. `git clone https://github.com/PyTorchLightning/lightning-flash.git`
3. `cd lightning-flash/`
4. `pip3 install lightning-flash[image]`
5. `export XRT_TPU_CONFIG="localservice;0;localhost:51011"`
6. `vim flash_examples/finetuning/image_classification.py` (add `tpu_cores=8` to the Trainer object)
7. `python3 flash_examples/finetuning/image_classification.py`

failure trace is like this:

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/distributed/parallel_loader.py", line 166, in _worker
    batch = xm.send_cpu_data_to_device(batch, device)
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/core/xla_model.py", line 846, in send_cpu_data_to_device
    return ToXlaTensorArena(convert_fn, select_fn).transform(data)
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/core/xla_model.py", line 413, in transform
    return self._replace_tensors(inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/core/xla_model.py", line 406, in _replace_tensors
    return xu.for_each_instance_rewrite(inputs, lambda x: self._select_fn(x),
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/utils/utils.py", line 214, in for_each_instance_rewrite
    return _for_each_instance_rewrite(value, select_fn, fn, rwmap)
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/utils/utils.py", line 194, in _for_each_instance_rewrite
    result.append(_for_each_instance_rewrite(x, select_fn, fn, rwmap))
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/utils/utils.py", line 180, in _for_each_instance_rewrite
    k = _for_each_instance_rewrite(k, select_fn, fn, rwmap)
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/utils/utils.py", line 205, in _for_each_instance_rewrite
    v = _for_each_instance_rewrite(result.__dict__[k], select_fn, fn, rwmap)
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/utils/utils.py", line 206, in _for_each_instance_rewrite
    result.__dict__[k] = v
TypeError: 'mappingproxy' object does not support item assignment
```

I don't think there is any version of pytorch/xla where this worked.

It looks like the Lightning code is trying to send some non-standard object to the TPU using `send_cpu_data_to_device`. Is that expected?  The normal flow that we support is to use `model = torch.load(stuff)` on the CPU and then use `model.to(device)` to send it to the TPU

**Comment by kaushikb11** [comment]
```python
def _maybe_convert_to_cpu(data, convert=True):

  def convert_fn(tensors):
    torch_xla._XLAC._xla_sync_multi(
        tensors, devices=[], wait=True, sync_xla_data=True)
    if not convert:
      return tensors
    return torch_xla._XLAC._xla_get_cpu_tensors(tensors)

  def select_fn(v):
    return type(v) == torch.Tensor and is_xla_tensor(v)

  return ToXlaTensorArena(convert_fn, select_fn).transform(data)


def send_cpu_data_to_device(data, device):

  def convert_fn(tensors):
    devices = [str(device)] * len(tensors)
    return torch_xla._XLAC._xla_tensors_from_aten(tensors, devices)

  def select_fn(v):
    return type(v) == torch.Tensor and v.device.type == 'cpu'

  return ToXlaTensorArena(convert_fn, select_fn).transform(data)
```

Seems like it only supports Tensor objects for transfer.

**Comment by zcain117** [comment]
It seems like the parallel loader is calling `send_cpu_data_to_device` on some kind of intermediate model representation (e.g. weights and/or callbacks etc, not a pytorch model object)

Do you have a sense of whether your code is crashing during the loading step or during the saving step?  Have you tried `xm.save` and then stopping?

**Comment by grudloff** [comment]
Just for future reference, I am getting the same error when fitting in colab with torch_xla 2.0. I set up the environment by calling:

```python
!pip install cloud-tpu-client==0.10 torch torchvision lightning monai https://storage.googleapis.com/tpu-pytorch/wheels/colab/torch_xla-2.0-cp310-cp310-linux_x86_64.whl
```

**Comment by seungduk-yanolja** [comment]
I experiencing the same issue here. Training Mistral-7b with deepspeed in a Google Compute Engine machine.
