### ISSUE TITLE
Is model parallelism supported in xla for tpu?

### ISSUE THREAD

**Issue by chaitnayabasava** [pytorch/xla#2779]
## ❓ Questions and Help
I am trying to train Stylegan2 pytorch implementation on colab TPU. But the session is getting crashed with OM error due to the huge size of the generator model. 

The `xmp.spawn` function is parallelising the data loader and optimization across all available tpu cores but due to the size of the model, it is getting impossible to train on each core.

Each of the 8 available cores is getting an instance of the entire model, is it possible to divide the model load across multiple cores (2 model instances, each model over 4 cores each, with the help of model parallelism) to get over the OM errors.

**Comment by taylanbil** [comment]
There are many types of model-parallelism, and currently some of those ways are possible on pt/xla.

- [here](https://github.com/pytorch/xla/blob/master/contrib/colab/Distributing_Large_Embedding_tables.ipynb) is an example colab that parallelizes the (one) embedding table in an NLP workload.
- [here](https://github.com/taylanbil/dlrm/blob/tpu-criteo-kaggle/dlrm_s_pytorch.py) is a branch of DLRM, it parallelizes the model by putting many scattering the (many) embedding tables to different tpu cores.
- [here](https://github.com/pytorch/fairseq/tree/dev_tpu_mp) is an experimental fairseq branch that achieves megatron style parallelism (`N` attention heads in model, each core holds `N/num_cores` many heads).

The communication b/w cores happen through `xm.all_reduce`'s, `xm.all_gather`'s and `xm.all_to_all`'s.
