### ISSUE TITLE
tf.while, tf.cond

### ISSUE THREAD

**Issue by cjolivier01** [pytorch/xla#2799]
## ❓ Questions and Help
Are there any plans to handle control flow such as tf.cond or tf.while?  Whether by override or direct op?

**Comment by JackCaoG** [comment]
Hi @cjolivier01, you can try our XLA_BUILDER which give you access to XLA ops,
https://github.com/pytorch/xla/blob/3eaee46ef679cc6a0f1f694bd0a007dbfd09c51b/torch_xla/core/xla_builder.py#L567

You can find more example in 
https://github.com/pytorch/xla/blob/7eeaa33973335959110e262689f4324b4429a9a9/test/test_operations.py#L1798

**Comment by cjolivier01** [comment]
whoa, how did I miss that? I guess because I stay mostly out of the python world when I can :)  thank you so much.
