### ISSUE TITLE
ImportError while running the example Multicore Alexnet Notebook

### ISSUE THREAD

**Issue by tumble-weed** [pytorch/xla#2815]
## 🐛 Bug

I get an importerror when importing torch_xla:
ImportError: /usr/local/lib/python3.7/dist-packages/_XLAC.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtERKSt10shared_ptrIS0_EPSo

## To Reproduce

I just ran the example notebook suggested in the README: https://colab.research.google.com/github/pytorch/xla/blob/master/contrib/colab/multi-core-alexnet-fashion-mnist.ipynb

**Comment by jysohn23** [comment]
Can you try running: `!pip install torch==1.8.0` as well?
