### ISSUE TITLE
xm.get_rng_state hangs on tpu version 1.8

### ISSUE THREAD

**Issue by taylanbil** [pytorch/xla#2830]
## 🐛 Bug

`xm.get_rng_state` hangs on tpu version 1.8.

Combinations:

- torchxla 1.7, tpu 1.7 -> no hang
- torchxla 1.8, tpu 1.7 -> no hang
- torchxla 1.7, tpu 1.8 -> hang
- torchxla 1.8, tpu 1.8 -> hang

## To Reproduce

```python
import torch_xla.core.xla_model as xm

print(xm.get_rng_state())
```

## Expected behavior

No hang.

**Comment by JackCaoG** [comment]
It turned out to be a tpu was in a bad state, creating a new tpu with 1.8 solved this problem.
