### ISSUE TITLE
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage, how to resolve it?

### ISSUE THREAD

**Issue by soumochatterjee** [pytorch/xla#2831]
## Issue description
Currently I am trying to solve an object detection problem using FastRCNN model with the help of Pytorch XLA module 
But while training I am getting a  **RuntimeError: Cannot access data pointer of Tensor that doesn't have storage**
It was working fine when I trained the model in GPU kernel, but started giving error when I switched to TPU

## Code example
Here's the link to my notebook --> [Object Detection Kernel](https://www.kaggle.com/mesparky/vunbigdata-chest-xray-object-detection?scriptVersionId=57113528)
![image](https://user-images.githubusercontent.com/42636586/111666653-eca9da80-8839-11eb-9d86-65d47bce4309.png)

## System Info
I am using Kaggle TPU kernel for training my model.

**PLEASE HELP ME RESOLVING THIS ISSUE**

**Comment by soumochatterjee** [comment]
I saw this [forum](https://github.com/pytorch/xla/issues/929) while googling find the answer in order to resolve this but unable to understand where to make the changes.

**Comment by JackCaoG** [comment]
Sorry for the late reply, pytorch/xla has its own version of `nms`, more detail in https://github.com/pytorch/xla/issues/1667. Do you want to give it try?
