### ISSUE TITLE
Inverse of torch_xla._XLAC._xla_set_default_device(device)

### ISSUE THREAD

**Issue by tchaton** [pytorch/xla#2845]
## Motivation

Dear people from XLA Team,

I was wondering if they were a simple way to detect if xla was available. It seems calling xla_device is the only way. However, this attach the xla core to the current process.

This is pretty unfortunate when running TPU CIs and switching between 1-8 cores.
It would be nice to be able to detach a process from xla and have a nice utils to know if is_xla_available.

Best,
T.C

**Comment by JackCaoG** [comment]
Hi @tchaton Could you be a bit more specified about "detect if xla was available". Are you running on TPU machine and want to check if the `device`(tpu core) is already assigned to other process?

**Comment by tchaton** [comment]
Dear @JackCaoG,

In PyTorch Lightning, we are using this code to detect if TPU is available: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/utilities/xla_device.py#L96

```
def inner_f(queue, func, *args, **kwargs):  # pragma: no cover
    try:
        queue.put(func(*args, **kwargs))
    # todo: specify the possible exception
    except Exception:
        traceback.print_exc()
        queue.put(None)


def pl_multi_process(func):

    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        queue = Queue()
        proc = Process(target=inner_f, args=(queue, func, *args), kwargs=kwargs)
        proc.start()
        proc.join(TPU_CHECK_TIMEOUT)
        try:
            return queue.get_nowait()
        except q.Empty:
            traceback.print_exc()
            return False

    return wrapper

    @staticmethod
    @pl_multi_process
    def _is_device_tpu() -> bool:
        """
        Check if device is TPU
        Return:
            A boolean value indicating if the xla device is a TPU device or not
        """

        def _fn(_: int, mp_queue):
            try:
                device = xm.xla_device()
                mp_queue.put(device.type == 'xla')
            except Exception:
                mp_queue.put(False)

        smp = mp.get_context("spawn")
        queue = smp.SimpleQueue()
        xmp.spawn(_fn, args=(queue, ), nprocs=1)
        return queue.get()
```

**Comment by JackCaoG** [comment]
I think you really meant `TPU device` instead of `XLA_DEVICE`.

Couldn't you just check `XRT_TPU_CONFIG`? I think device is generated from this config for TPU case (most likely).
