### ISSUE TITLE
Unable to Load XLA Tensors from Statedict on GPU only Machine

### ISSUE THREAD

**Issue by hyang0129** [pytorch/xla#2858]
## 🐛 Bug

A state dict was saved without using xm save. This resulted in tensors saved as device = XLA. Trying to load the tensors without an XLA device results in the following error. 

>     177 def _rebuild_xla_tensor(data, dtype, device, requires_grad):
> --> 178     tensor = torch.from_numpy(data).to(dtype=dtype, device=device)
>     179     tensor.requires_grad = requires_grad
>     180     return tensor
> 
> RuntimeError: Could not run 'aten::empty_strided' with arguments from the 'XLA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::empty_strided' is only available for these backends: [CPU, CUDA, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradNestedTensor, UNKNOWN_TENSOR_TYPE_ID, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].
> 
> CPU: registered at /pytorch/build/aten/src/ATen/RegisterCPU.cpp:5925 [kernel]
> CUDA: registered at /pytorch/build/aten/src/ATen/RegisterCUDA.cpp:7100 [kernel]
> BackendSelect: registered at /pytorch/build/aten/src/ATen/RegisterBackendSelect.cpp:596 [kernel]
> Named: registered at /pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
> AutogradOther: registered at /pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:9273 [autograd kernel]
> AutogradCPU: registered at /pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:9273 [autograd kernel]
> AutogradCUDA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:9273 [autograd kernel]
> AutogradXLA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:9273 [autograd kernel]
> AutogradNestedTensor: registered at /pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:9273 [autograd kernel]
> UNKNOWN_TENSOR_TYPE_ID: registered at /pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:9273 [autograd kernel]
> AutogradPrivateUse1: registered at /pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:9273 [autograd kernel]
> AutogradPrivateUse2: registered at /pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:9273 [autograd kernel]
> AutogradPrivateUse3: registered at /pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:9273 [autograd kernel]
> Tracer: registered at /pytorch/torch/csrc/autograd/generated/TraceType_0.cpp:10499 [kernel]
> Autocast: fallthrough registered at /pytorch/aten/src/ATen/autocast_mode.cpp:250 [backend fallback]
> Batched: registered at /pytorch/aten/src/ATen/BatchingRegistrations.cpp:1016 [backend fallback]
> VmapMode: fallthrough registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]

## To Reproduce

I believe the team has encountered a similar issue with state dicts not saved via xm.save. Is there a workaround to load the tensors? 

## Expected behavior

Tensors load by default to cpu before being pushed to a device? 

## Environment

Colab TPU and GPU envs. TPU env generated the weights file and GPU env is trying to load the state dict (not into a model, just as a dictionary).

**Comment by hyang0129** [comment]
please change or overload or idk do something to this function  below 

`def _rebuild_xla_tensor(data, dtype, device, requires_grad):
    tensor = torch.from_numpy(data).to(dtype=dtype, device=device)
    tensor.requires_grad = requires_grad
    return tensor
`
the issue is resolved by changing the device = device to device = 'cpu'.

`def _rebuild_xla_tensor(data, dtype, device, requires_grad):
    tensor = torch.from_numpy(data).to(dtype=dtype, device='cpu')
    tensor.requires_grad = requires_grad
    return tensor
`

**Comment by hyang0129** [comment]
Anyone else having the same issue can override the function as the first line of code in your import section

`import torch 

def _rebuild_xla_tensor(data, dtype, device, requires_grad):
    tensor = torch.from_numpy(data).to(dtype=dtype, device='cpu')
    tensor.requires_grad = requires_grad
    return tensor

torch._utils._rebuild_xla_tensor = _rebuild_xla_tensor`

**Comment by JackCaoG** [comment]
Yea, we require user to move the tensor to `CPU`  before calling `xm.save`. more detail in https://github.com/pytorch/xla/blob/08ae1044c2a7e314895f9946104cbe399e096515/API_GUIDE.md#saving-and-loading-xla-tensors

I will close this issue since it is resolved. Please reopen for any further questions.

**Comment by hyang0129** [comment]
@JackCaoG yeah but like why not just update the code to load tensors onto CPU first? I don't consider it a bug, I'm just wondering why it is a feature to load all tensors back to the original device they were trained on? Like this behaviour is not expected when we train GPU tensors and load them on a non GPU device.
