### ISSUE TITLE
[PT_BREAK]Makes torch.cuda.amp.GradScaler scale updates in-place for better composability with graph capture 

### ISSUE THREAD

**Issue by ailzhang** [pytorch/xla#2865]
https://github.com/pytorch/pytorch/pull/55562
This PR requires a followup change on pytorch/xla side, @yaochengji would you mind helping on it? Thanks!

**Comment by yaochengji** [comment]
Sure. I will take a look this week.

**Comment by ailzhang** [comment]
@yaochengji I'm thinking about having a channel among us and @mcarilli on slack to better discuss and cooridinate amp related changes. Do you want to join? ;) (Let me know your email if that sounds good!)

**Comment by ailzhang** [comment]
@yaochengji @byronyi Done! Please let me know if you don't see the invitation email! (there's an open channel called #amp that's created for all amp-related discussions :D

**Comment by yaochengji** [comment]
PR submitted: https://github.com/pytorch/xla/pull/2874
