### ISSUE TITLE
How to dump HLO IR

### ISSUE THREAD

**Issue by KatiaSN602** [pytorch/xla#2883]
## ❓ Questions and Help

Hi, 
I want to extract the HLO PROTO/TEXT of a function/module that I wrote in  PyTorch.
Something similar to what jax is doing [here](https://jax.readthedocs.io/en/latest/jax.html#jax.xla_computation):

```
def f(x): 
     return jax.numpy.sin(jax.numpy.cos(x))
c = jax.xla_computation(f)(3.)
hlo_proto = c. as_serialized_hlo_module_proto() 
hlo_txt = c. as_hlo_text()
```

Is there something similar that I can do it torch_xla?

**Comment by asuhan** [comment]
Yes, set `XLA_SAVE_TENSORS_FILE` to the path where you want the dump and `XLA_SAVE_TENSORS_FMT` to `hlo`. You can fine more details here: https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#environment-variables.
