### ISSUE TITLE
[PT_BREAK] resize functions now take and return const Tensor&

### ISSUE THREAD

**Issue by swolchok** [pytorch/xla#2894]
See PR https://github.com/pytorch/pytorch/pull/55351

**Comment by swolchok** [comment]
I think https://github.com/pytorch/xla/blob/7a067f7de7355195c2a050c65b55b18a48da4405/torch_xla/csrc/aten_xla_type.cpp#L2809 just needs to take & return `const Tensor&` after the patch. Not sure if there's a non-breaking way to land this change though.

**Comment by JackCaoG** [comment]
Thanks for reporting! I can work on a quick fix on the pt/xla part.

**Comment by JackCaoG** [comment]
@swolchok I tried to apply your patch on top of pytorch head and got 
```
../test/cpp/api/functional.cpp:949:5: error: 'this' argument to member function 'set_requires_grad' has type 'const at::Tensor', but function is not marked const
    x.resize_({size, size, size}).set_requires_grad(true);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
aten/src/ATen/core/TensorBody.h:683:11: note: 'set_requires_grad' declared here
  Tensor& set_requires_grad(bool requires_grad) {
          ^
../test/cpp/api/functional.cpp:1613:5: error: 'this' argument to member function 'set_requires_grad' has type 'const at::Tensor', but function is not marked const
    x.resize_({size, size, size}).set_requires_grad(true);
```

I did a `python setup.py clean` before the build. Error message actually make sense given `x.resize_` returns `const Tensor&`. Do you know how can I fix this compilation error?

**Comment by swolchok** [comment]
I think you need to pull; set_requires_grad returns const Tensor& now. https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/templates/TensorBody.h#L683

**Comment by JackCaoG** [comment]
Ah you right, I was actually in a temporary  branch due to previous patch.
