### ISSUE TITLE
Docker Setup

### ISSUE THREAD

**Issue by tianyu-sun** [pytorch/xla#2905]
## ❓ Questions and Help
Hi, I built the torch-xla image and run it. When I started a python cli, I still can not do 'import torch_xla', do you have any assumptions on environmental variables or which python I should use? Thank!

**Comment by JackCaoG** [comment]
Could you try using python3? You can also considering using prebuilt docker image following instructions in https://github.com/pytorch/xla#-consume-prebuilt-docker-images

**Comment by tianyu-sun** [comment]
It works. Thanks!
