### ISSUE TITLE
CPU-only Mode

### ISSUE THREAD

**Issue by tianyu-sun** [pytorch/xla#2906]
## ❓ Questions and Help
Hi, I'm trying to do some prototypes locally and I'm wondering if torch-xla can be used without TPU configuration cuz I don't have TPU locally. Thanks!

**Comment by JackCaoG** [comment]
yup, our circle CI runs on CPU and GPU. You can use
```
export XRT_DEVICE_MAP="CPU:0;/job:localservice/replica:0/task:0/device:XLA_CPU:0" XRT_WORKERS="localservice:0;grpc://localhost:51011"
```
to run pt/xla on CPU.

**Comment by tianyu-sun** [comment]
It works! Thank you!
