### ISSUE TITLE
Dump HLO IR for Function

### ISSUE THREAD

**Issue by tianyu-sun** [pytorch/xla#2907]
## ❓ Questions and Help
Hi, I'm trying to dump HLO IR for my PyTorch code. I'm using the 'torch_xla._XLAC._get_xla_tensor_hlo' function. It seems this function only accept torch tensors. Is there a similar function which takes in a function and produce HLO IR with '%arg'? BTW where can I find the source code of 'torch_xla._XLAC._get_xla_tensor_hlo'?

**Comment by JackCaoG** [comment]
`_get_xla_tensor_hlo`implemention is in 
https://github.com/pytorch/xla/blob/08ae1044c2a7e314895f9946104cbe399e096515/torch_xla/csrc/init_python_bindings.cpp#L749

We don't really have a way to dump hlo for a given python function. You could use https://github.com/pytorch/xla/blob/08ae1044c2a7e314895f9946104cbe399e096515/torch_xla/csrc/init_python_bindings.cpp#L948

to dump all of the tensor with their IR text (set a low nodes_threshold if graph is small). Result should looks something like
```
(Pdb) print(torch_xla._XLAC._xla_tensors_report(5))
Tensor: id=1, shape=f32[5,5]{1,0}, device=CPU:0, ir_nodes=10
Python Frames:
  <module> (/usr/local/google/home/jackcao/Desktop/test/test_sin.py:3)
IR {
  %0 = s64[] xla::device_data(), location=<module>@test_sin.py:3, device=CPU:0
  %1 = s64[] prim::Constant(), location=<module>@test_sin.py:3, value=214013
  %2 = s64[] aten::mul(%1, %0), location=<module>@test_sin.py:3
  %3 = s64[] prim::Constant(), location=<module>@test_sin.py:3, value=2.53101e+06
  %4 = s64[] aten::add(%3, %2), location=<module>@test_sin.py:3
  %5 = f32[] prim::Constant(), location=<module>@test_sin.py:3, value=1
  %6 = f32[5,5]{1,0} aten::expand(%5), location=<module>@test_sin.py:3, size=(5, 5)
  %7 = f32[] prim::Constant(), location=<module>@test_sin.py:3, value=0
  %8 = f32[5,5]{1,0} aten::expand(%7), location=<module>@test_sin.py:3, size=(5, 5)
  %9 = f32[5,5]{1,0} aten::normal(%8, %6, %4), location=<module>@test_sin.py:3, ROOT=0
}
```

You can also check how `XLA_DUMP_HLO_GRAPH `is used and dump all of the HLO executed.

**Comment by tianyu-sun** [comment]
Hi, thanks for the detailed reply! I'm trying to do a similar thing like this in Jax, 'jax.xla_computation(function)(*args)', and I'd like to disentangle function and args so that I don't need to provide the exact args at this time. Do you have a plan for supporting dumping functions? I think this is very important for developers who are using Jax and PyTorch at the same time and we need to be able to do the same thing with PyTorch.

**Comment by JackCaoG** [comment]
I checked how jax implemented `xla_computation` and it seems like they are  using xlaBuilder's python api. I think it will be more complicated for us to implemented the same since the pt/xla depend on pt to call our lowering (JAX is built on xla directly and they have full control of the lowering path).

Feel free to open a feature request for this, we are also happy to take external contributions.

**Comment by KatiaSN602** [comment]
Hi There, I'm actually also interested in this feature.
I was wondering if you could elaborate, why it is more complicated in pt/xla?
Why can't you pybind the function that actually outputs the lowering? Don't you also have at some point a hlo-xla IR of the PyTorch model/function? 
Thanks!

**Comment by JackCaoG** [comment]
The complication coming from `getting the hlo text without running the function`. `XLA_DUMP_HLO_GRAPH ` should already doing sometime similar to dump the hlo text got executed.
