### ISSUE TITLE
Include documentation about Env variables 

### ISSUE THREAD

**Issue by kaushikb11** [pytorch/xla#2923]
## 📚 Documentation

Would have loved to read details about the Environment variables being used in XLA. 
Ref: https://github.com/pytorch/xla/blob/master/torch_xla/core/xla_env_vars.py

**Comment by JackCaoG** [comment]
A lot of these are setup automatically. Most of the environments that we expect user to set is explained in https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#environment-variables
