### ISSUE TITLE
Possible to build xla_ops manually / use JAX?

### ISSUE THREAD

**Issue by thisiscam** [pytorch/xla#2925]
## ❓ Questions and Help

Hi,

My end goal is to be able to compile and run a custom reduce/scan operation on XLA.
e.g. https://github.com/pytorch/xla/blob/master/torch_xla/core/xla_builder.py#L470. 

To that end, I have thought about two alternatives:
1) Is it possible to build a XLA operation manually in pytorch_xla?
2) Since the first option is a bit messy, is it possible to use JAX for this? In particular, is it possible to mix JAX with pytorch_xla? 

Thanks!

**Comment by JackCaoG** [comment]
1. Yes it is possible to build a XLA operation in pt/xla. You can refer to https://github.com/pytorch/xla/pull/2507/files for detail. You don't need to modify the `xla_op_builder.cpp` if the XLAOP you needed is already there.

2. I think it is possible, but imo will be complicated.  We never tried to use JAX and pt/xla in the same time. I would expect both library carry a slightly different version of XLABuilder for example. In the end we just need the HLO text, but I think `pytorch tensor -> JAX OP -> HLO text -> inserted back to pt/xla` would not be an easy path.

**Comment by thisiscam** [comment]
@JackCaoG Thanks for the quick response. 

This is what I figured out:
```python
import torch

import torch_xla
import torch_xla.core.xla_model as xm

import torch_xla.core.xla_builder as xla_builder
import torch_xla.core.xla_op_registry as xor

dev = xm.xla_device()

def custom_sum_op_fn(a, init_val):
  return a.reduce(
      init_value=init_val, 
      computation=lambda a, b: a + b, 
      dimensions=(0, )
  )

op = xor.register("custom_sum",  custom_sum_op_fn)

a = torch.arange(11, device=dev, dtype=torch.float32)
init_val = torch.zeros(tuple(), device=dev)
op(a, init_val) // Correctly prints 0 + ... + 10 = 55
```

Is this the right way to do it?
Specifically, I don't know what magic `xor.register` is doing -- it appears to have lifted my function's arguments to `xla_buider.Op`.

Thanks a bunch

=====
BTW, there's a typo at https://github.com/pytorch/xla/blob/33bd09759fa86329d1723a838be017b1e004b72e/torch_xla/core/xla_builder.py#L769

**Comment by JackCaoG** [comment]
nice catch for the typo.. I will submit a pr to fix it.

Your implementation seems right to me.  If you are wondering how this works, you can check out

https://github.com/pytorch/xla/blob/06dd1e106be159a5e5c8711fcb3e8a5d92bf56db/torch_xla/core/xla_op_registry.py#L42

and 

https://github.com/pytorch/xla/blob/06dd1e106be159a5e5c8711fcb3e8a5d92bf56db/torch_xla/csrc/ops/user_computation.cpp#L33

`xor.register` only register your function and turn it into a XLAComputation. Pytorch/XLA perform the `pytorch tensor - > XLA tensor -> XLA op` lowering and feed the `XLAOP` to your python function in `user_computation.cpp`.

**Comment by thisiscam** [comment]
Thanks for confirming. 

> I think it is possible, but imo will be complicated. We never tried to use JAX and pt/xla in the same time. I would expect both library carry a slightly different version of XLABuilder for example. In the end we just need the HLO text, but I think pytorch tensor -> JAX OP -> HLO text -> inserted back to pt/xla would not be an easy path.

Regarding my 2. point (which I don't need for now): 
I see. I can see that the machinery is there, is just a question whether implementing something like it could be useful.

IMHO, ideally pytorch upstream should provide some API to do loops like JAX's `fori_loop`, `scan` etc. 
These could be unoptimized implementations if not run on XLA, but could use some good speedup otherwise.

Can close for now, I will ask if anything else comes up!

**Comment by JackCaoG** [comment]
Yea, ideally pytorch can provide a node for `for_loop` that we can lower. I will close this issue for now. Thanks!
