### ISSUE TITLE
How to install torch_xla with python version 3.9.2

### ISSUE THREAD

**Issue by NakedKoala** [pytorch/xla#2927]
## ❓ Questions and Help

I have to use 3.9.2 for other dependency. Given that my python version must be 3.9.2, how do I install torch_xla ? 

I tried these 2 method shown in tutorial 

1)

`!pip install cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.8.1-cp37-cp37m-linux_x86_64.whl` 

This ( and c38 c39 variant of it ) does not work. 

<img width="682" alt="Screen Shot 2021-05-03 at 11 18 17 PM" src="https://user-images.githubusercontent.com/14815380/116957477-ec3c9600-ac65-11eb-8e2c-ba5c7050af25.png">

2)
```
VERSION = "20200516"  #@param ["1.5" , "20200516", "nightly"]
!curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
!python pytorch-xla-env-setup.py --version $VERSION
```

Running these gives

<img width="706" alt="Screen Shot 2021-05-03 at 11 20 02 PM" src="https://user-images.githubusercontent.com/14815380/116957546-18f0ad80-ac66-11eb-97c2-4d134f50f90e.png">

## Question

How do I use xla with python 3.9.2 ?

Do I must have python 3.7.x  in order to use xla ???

**Comment by JackCaoG** [comment]
We do not release any wheel for python 3.9, I am not sure if pytorch release 3.9 wheel too. One thing you could try is to build pytorch and pytorch/xla from scratch. Please follow https://github.com/pytorch/xla/blob/master/CONTRIBUTING.md#build-from-source
