### ISSUE TITLE
Check TPU utilization

### ISSUE THREAD

**Issue by sooftware** [pytorch/xla#2934]
## Check tpu utilization❓
  
Hi! Thanks for your great project. I tried MNIST training with TPU using `pytorch_lightning`. I success MNIST training. But I want to check TPU utilization.  
  
Is there a function that returns tpuTPU usage? I want to leave it in the log.  
Thank you!

**Comment by jysohn23** [comment]
We currently don't have `torch_xla` APIs to query for TPU MXU utilization, but you should be able to get such usage metrics by using our profiler tooling, which should give you much more than just the MXU utilization metrics as well: https://cloud.google.com/tpu/docs/pytorch-xla-performance-profiling#tpu_server_profiling

We do have an API for querying TPU device memory usage here in case you find that useful: https://github.com/pytorch/xla/blob/8ee06ba520663bd033c90a0f0313a980fa3987f8/torch_xla/core/xla_model.py#L947

**Comment by sooftware** [comment]
Thank you @jysohn23!!
