### ISSUE TITLE
Error: torch_xla/csrc/convert_ops.cpp:83 : Unsupported XLA type 10

### ISSUE THREAD

**Issue by NakedKoala** [pytorch/xla#2939]
## 🐛 Bug

When using pytorch-lightning to run TPU training, Encounter below error message 
```
File "/root/anaconda3/envs/my-rdkit-env/lib/python3.7/site-packages/torch_xla/distributed/parallel_loader.py", line 46, in next
    xm.mark_step()
  File "/root/anaconda3/envs/my-rdkit-env/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 718, in mark_step
    wait=xu.getenv_as('XLA_SYNC_WAIT', bool, False))
RuntimeError: Error while lowering: f32[24,3,7,7]{0,1,3,2} xla::cast, type=f32, dtype=Float, stype=Half
Error: torch_xla/csrc/convert_ops.cpp:83 : Unsupported XLA type 10
Python Frames:

```
I believe the error related to lowering is coming from xla and not pytorch-lightning.

### To Reproduce

Sorry that I don't have further detailed info on what is causing the error 

Please run this colab notebook, 

https://colab.research.google.com/drive/1IlhXRWP84c3mXgjJMsypmhIC-4sSsDQf?usp=sharing

### Expected behavior

Should be able to run TPU training

**Comment by JackCaoG** [comment]
The code is trying to cast some variable to `float16` which is not supported on TPU. TPU uses `bfloat16`. Do you know where this cast coming from? Are you using AMP for example?
