### ISSUE TITLE
Very low MXU utilization

### ISSUE THREAD

**Issue by ZhaofengWu** [pytorch/xla#2947]
## ❓ Questions and Help
Hi, this is my first time using a TPU -- on Google Cloud's monitoring console, I'm seeing extremely low MXU utilization (mostly 0, with occasional 0.01% spikes). The TPU runtime CPU utilization is normal, at around 100%. This is only for inference, not training, so it's not a crazy workload, but I think 0.01% utilization is still too low. What are some good ways to debug this? The IR looks right to me. I'm using fairseq on Google Cloud. Thanks for your help!

**Comment by jysohn23** [comment]
Are you making sure to batch your requests etc. to maximize utilization?

To monitor your performance with more detail this performance profiling tooling should help: https://cloud.google.com/tpu/docs/pytorch-xla-performance-profiling

**Comment by ZhaofengWu** [comment]
Thanks! If I have seen TPU OOM, does that necessarily mean I have batched things correctly?

**Comment by jysohn23** [comment]
Not necessarily as you may just have been leaking HBM with random tensors that weren't cleaned up. If you observed the OOM as you kept on increasing inference batch size, it probably means you're doing it right.

**Comment by ZhaofengWu** [comment]
Ok, thank you!
