### ISSUE TITLE
Timing execution time only

### ISSUE THREAD

**Issue by ZhaofengWu** [pytorch/xla#2948]
## ❓ Questions and Help
Is there a way to time a run excluding the compilation time? I can place timers around `mark_step()`, but I think that would include the compilation time.

**Comment by JackCaoG** [comment]
Please check https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#get-a-metrics-report. There is a `ExecuteTime` metric

**Comment by ZhaofengWu** [comment]
Thanks, but could you help explain the report a little bit? For example, for the `CompileTime` in the doc that you linked, is `Counter` the total time taken? It seems that it's not the case that `Rate * TotalSamples = Counter`.

Also, if I call `metric_report()` multiple times, are the values accumulated throughout the entire program run?

**Comment by JackCaoG** [comment]
unfortunately we don't have such docs. I think `ValueRate` is just `Counter/Sample`, it doesn't make much sense for most metrics.

Counter is the accumulated value of this metric from the beginning of the run to the time you call `metric_report`. `metric_report` is just a snapshot of the current metric, calling it won't reset anything if that is your question.

**Comment by ZhaofengWu** [comment]
It seems that, at least for the values in the doc, `ValueRate * Sample != Counter`. And `Rate * Sample != Counter` either. The format of `ValueRate` is also a bit strange: `TIME / second`.

![image](https://user-images.githubusercontent.com/11954789/118073819-7b7e3380-b361-11eb-9739-96bfe71130f3.png)
