### ISSUE TITLE
Reshape 3D/4D tensors to 2D?

### ISSUE THREAD

**Issue by fdabek1** [pytorch/xla#2958]
In the original BERT Tensorflow code, they reshape matrices to always be 2D and they reference that it is done to speed up the performance on the TPU.  Does this same logic apply when using XLA on TPU's?

Here is the source code location from the original BERT Tensorflow: https://github.com/google-research/bert/blob/master/modeling.py#L932

```python
def reshape_to_matrix(input_tensor):
  """Reshapes a >= rank 2 tensor to a rank 2 tensor (i.e., a matrix)."""
  ndims = input_tensor.shape.ndims
  if ndims < 2:
    raise ValueError("Input tensor must have at least rank 2. Shape = %s" %
                     (input_tensor.shape))
  if ndims == 2:
    return input_tensor

  width = input_tensor.shape[-1]
  output_tensor = tf.reshape(input_tensor, [-1, width])
  return output_tensor


def reshape_from_matrix(output_tensor, orig_shape_list):
  """Reshapes a rank 2 tensor back to its original rank >= 2 tensor."""
  if len(orig_shape_list) == 2:
    return output_tensor

  output_shape = get_shape_list(output_tensor)

  orig_dims = orig_shape_list[0:-1]
  width = output_shape[-1]

  return tf.reshape(output_tensor, orig_dims + [width])
```

**Comment by JackCaoG** [comment]
Hi @fdabek1 I don't think this will apply to pt/xla. I chatted with Blake from the xla team and it seem like `you have to reshape a >= rank 2 to matrix to improve the speed` is a bug and have been resolved.

**Comment by JackCaoG** [comment]
I will close this issue for now, feel free to reopen if you have any followup questions. 😄
