### ISSUE TITLE
CUDA nightlies performance regression

### ISSUE THREAD

**Issue by rwightman** [pytorch/xla#2976]
## 🐛 Bug

I've been using `nightly_3.7_cuda` containers to test my XLA training code locally during development. There has been a significant performance regression since the 0421 container. I first noticed w/ 0510 nightly but haven't done a bisect to find exact nightly it changed. Since then I've tried two others to see if it was fixed, most recently 0601. Still the same.

## To Reproduce

Issue happens w/ my train script running imagenet training on a ResNet-26 (bottleneck w 2,2,2,2) model. Running distributed on 1 machine with two Titan RTX GPU. AMP enabled. 

At some point after 0421 the throughput went from ~1150img/s -> 650-700img/sec. As mentioned in #2901,  PyTorch XLA (0421) release is already a bit slower than standard PyTorch on GPU. With the drop in the current nightlies it's slower than half of PyTorch 1.8.1 conda release w/ AMP.

Distributed w/ 2 x GPU, AMP enabled:
* 1460 img/s - NGC 21.03 cuDNN 8.1.1
* 1380 img/s - Conda PyTorch 1.8.1 CUDA 11.1, cuDNN 8.0.5
* 1150 img/s - XLA CUDA 0421
* 650 img/s - XLA CUDA 0510 / 0601

For comparison, also ran w/o distributed training on 1 of the two GPU
1 x GPU, AMP enabled:
* 750 img/s - NGC 21.03 cuDNN 8.1.1
* 650 img/s - XLA CUDA 0421
* 400 img/s - XLA CUDA 0510 / 0601

## Environment

 - Reproducible on XLA backend [CPU/TPU]: GPU (CUDA)
 - torch_xla version: Nightly CUDA Python 3.7 0510, 0601

**Comment by JackCaoG** [comment]
Thanks @rwightman , I will try to bisect the change and report to the XLA:GPU team. @yaochengji Did you observer similar regression to your gpu workload?

**Comment by rwightman** [comment]
One more datapoint, less to do with the regression but more to do with the gap btw XLA vs standard PyTorch. W/ channels_last enabled on the NGC 21.05 container, the 2x setup above yields approx 2000 img/s. 

Based on my JAX/Flax usage it was my understanding that XLA should deal with the optimal memory layout and should in theory already be trying to use the optimzied Tensor Core kernels that get activated with channels_last + NGC builds when mixed precision is used.

**Comment by yaochengji** [comment]
I haven't find any regression on resnet-like models yet. What I use is v1.8.1 on V100 GPU, trained on Resnet 50, together with real data pre-processing and peripheral code.

Single GPU:
pytorch: 760 images/s per GPU
torch/xla: 1050 images/s per GPU

8 GPUs:
pytorch: 670 images/s
torch/xla: 950 images/s

**Comment by yaochengji** [comment]
> One more datapoint, less to do with the regression but more to do with the gap btw XLA vs standard PyTorch. W/ channels_last enabled on the NGC 21.05 container, the 2x setup above yields approx 2000 img/s.
> 
> Based on my JAX/Flax usage it was my understanding that XLA should deal with the optimal memory layout and should in theory already be trying to use the optimzied Tensor Core kernels that get activated with channels_last + NGC builds when mixed precision is used.

I also find pytorch could speed up a lot when enabled channels_last. But when it comes to torch/xla, I could not see any apparent improvement.

**Comment by rwightman** [comment]
@yaochengji I don't believe the memory format has any impact in PyTorch XLA, I was under the impression that the XLA compiler should change the memory format if it knows that it's optimal for a given dtype, would also need to know the SM it's targetting and I'm not sure how that works with PyTorch XLA CUDA builds. With JAX I built the jaxlib from source in an NGC container with latest cuDNN.

**Comment by JackCaoG** [comment]
I think this was fixed by https://github.com/pytorch/pytorch/commit/5408f739f79eb1ab2a6b3ef889e8a86a7bd20bdb. AMP speed should back to normal.
