### ISSUE TITLE
Support Stable sort

### ISSUE THREAD

**Issue by JackCaoG** [pytorch/xla#2987]
There was an op signature change to `torch.sort` which support stable sorting. I submited https://github.com/pytorch/xla/commit/2f30eb9541bd5f75687d78fccdf14e1b620a6d6c#diff-f57297d1529a97aaa12d95b780d8305f5bf35a7277c21c042aa394649ffe35bb but later revert this pr with the upstream pytorch pr. I think the stable sort has been separated from native sort for BC reason and is now has a different entry https://github.com/pytorch/pytorch/blob/84061dadad7370b8d37bf48c65526555f1b8ec13/aten/src/ATen/native/native_functions.yaml#L7003. We might as well support it since we only need to change the existing pr a bit.

**Comment by miladm** [comment]
@yeounoh can you please help with this issue?
