### ISSUE TITLE
Can't retrieve data in main from a function called with xmp.spawn

### ISSUE THREAD

**Issue by Dr-Noob** [pytorch/xla#3006]
## ❓ Questions and Help
My goal is to compute something inside a function called with `xmp.spawn` and then use it in the main function, but I'm unable to write to any shared data object between the function and main. Consider the following example:

``` python
def simple_map_fn(index, flags):
  out = flags['out']

  out[index] = 10

  # Barrier to prevent master from exiting before workers connect.
  xm.rendezvous('init')

if __name__ == '__main__':
  out = [0] * 8
  flags = {}
  flags['out'] = out

  xmp.spawn(simple_map_fn, args=(flags,), nprocs=8, start_method='fork') # same results with spawn
  print(out)
```

This prints:
``` python
[0, 0, 0, 0, 0, 0, 0, 0]
```
And I was expecting:
``` python
[10, 10, 10, 10, 10, 10, 10, 10]
```
Why it doesn't work? How can I fix it?

**Comment by zcain117** [comment]
under the hood, the `torch-xla` version of `spawn` is calling `torch.multiprocessing.start_processes`: https://github.com/pytorch/xla/blob/master/torch_xla/distributed/xla_multiprocessing.py#L388

I think by default the args are copied, but maybe it's possible to use shared memory if using a `Tensor` and/or `multiprocessing.Queue`. See here: https://pytorch.org/docs/stable/notes/multiprocessing.html

I haven't tried anything like this using `torch-xla` so maybe there are unique challenges I'm not aware of

**Comment by Dr-Noob** [comment]
I've tried this simple code:

```python
import torch.multiprocessing as multiprocessing

def simple_map_fn(index, flags):
  queue = flags['queue']

  print(hex(id(queue)))

  queue.put(10)

  # Barrier to prevent master from exiting before workers connect.
  xm.rendezvous('init')

if __name__ == '__main__':
  queue = multiprocessing.Queue()
  flags = {}
  flags['queue'] = queue

  print("Queue is ", hex(id(queue)))

  xmp.spawn(simple_map_fn, args=(flags,), nprocs=8, start_method='spawn')
```
But crashes with a SEGFAULT:

```
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    xmp.spawn(simple_map_fn, args=(flags,), nprocs=8, start_method='spawn')
  File "/home/user/.local/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 382, in spawn
    return _run_direct(fn, args, nprocs, join, daemon, start_method)
  File "/home/user/.local/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 346, in _run_direct
    fn, args=args, nprocs=nprocs, join=join, daemon=daemon)
  File "/home/user/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/user/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/user/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 136, in join
    signal_name=name
torch.multiprocessing.spawn.ProcessExitedException: process 2 terminated with signal SIGSEGV
```
Probably related to: https://discuss.pytorch.org/t/segfault-with-multiprocessing-queue/81292. I've tried using `spawn` and `fork` in the `start_method`, but get SIGSEGV in both cases. Using the print to debug, the address of the queue in the main is different than the address of the queue in each of the processes in `simple_map_fn`, and each process also sees a different adress, eg:

```
Queue is  0x7f2fa5512278
0x7f658e8590f0
0x7f881b93b860
0x7f70446bd080
0x7fb7708ca160
0x7f6388d8e160
0x7fe8b166c160
```
Any ideas?

**Comment by dsuess** [comment]
@Dr-Noob Have you managed to solve this issue? It doesn't seem to be pytorch-xla related. I get the same issue with the CPU-only version of pytorch 1.11 on a standard VM in GCP (operating system version Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-1019-gcp x86_64))
