### ISSUE TITLE
Arange op does not support float16

### ISSUE THREAD

**Issue by luchangli03** [pytorch/xla#3025]
## 🐛 Bug

`
import torch
import torch_xla
import torch_xla.core.xla_model as xm

device = xm.xla_device(devkind='GPU')

key_length = 100
position_sequence = torch.arange(key_length, -1, -1.0, device=device,
                                 dtype=torch.float16)

print(position_sequence.dtype)
`
above codes (used in GPT-2) will be failed and give error message: XLA type not supported: 10

**Comment by JackCaoG** [comment]
Close this issue as the fix is merged.
