### ISSUE TITLE
[PT_BREAK] Head build failure

### ISSUE THREAD

**Issue by JackCaoG** [pytorch/xla#3033]
Build with pytorch head currently fail with 
```
/usr/local/google/home/jackcao/Desktop/gitProj2/pytorch/xla/torch_xla/csrc/aten_xla_type.cpp:416:21: error: no member named 'index_put_' in namespace 'torch_xla'
  return torch_xla::index_put_(self, indices, values, accumulate);
         ~~~~~~~~~~~^
/usr/local/google/home/jackcao/Desktop/gitProj2/pytorch/xla/torch_xla/csrc/aten_xla_type.cpp:476:10: error: use of undeclared identifier 'view'
  return view(self, size);
         ^
/usr/local/google/home/jackcao/Desktop/gitProj2/pytorch/xla/torch_xla/csrc/aten_xla_type.cpp:1115:56: error: too many arguments to function call, expected 2, have 3
  return torch_xla::div(self, other, /*rounding_mode=*/c10::nullopt);
```

suspecting this is caused by some pytorch pr merged this morning since some pr has passing test this morning.

**Comment by JackCaoG** [comment]
Suspecting it is because https://github.com/pytorch/pytorch/commit/8bc2ba3fe325817f87370eb15fd627fbc4ac8294 merged, I think we need to merge https://github.com/pytorch/xla/pull/3012

**Comment by miladm** [comment]
Turns out unit tests break when compiling pytorch and pytorch/xla heads. I tested `Max` and `Min`.

**Comment by JackCaoG** [comment]
@miladm I tried the test on my end and it passed. [Circle CI](https://app.circleci.com/pipelines/github/pytorch/xla/9125/workflows/9af6482b-727c-480e-a888-58b98b3329f9/jobs/17990) also seems to be passing. Maybe you need to do a clean before rebuilding pytorch and pytorch xla?

**Comment by JackCaoG** [comment]
Head is green again, close this issue
