### ISSUE TITLE
pytorch-xla-profiling-colab.ipynb doesn't work

### ISSUE THREAD

**Issue by halcy** [pytorch/xla#3047]
## 🐛 Bug

Currently, running pytorch-xla-profiling-colab.ipynb on colab seems to result only in an empty tfevents file without any profiling data.

## To Reproduce

1. Open https://colab.research.google.com/github/pytorch/xla/blob/master/contrib/colab/pytorch-xla-profiling-colab.ipynb
2. Run All

## Expected behavior

A tensorboard instance that shows some (client side, since TPU is not expected to work) profiling data. 

## Environment

 - Reproducible on XLA backend [CPU/TPU]: TPU
 - torch_xla version: torch_xla-1.9-cp37-cp37m-linux_x86_64.whl

**Comment by JackCaoG** [comment]
@jysohn23 Can you take a look?

**Comment by jysohn23** [comment]
Are you selecting the `PROFILE` tab from the dropdown here?
![image](https://user-images.githubusercontent.com/19496130/126499718-fdf11e96-96cd-458f-85d8-90bb0812c865.png)

From a quick repro I was able to get traces in the `xplane.pb` file generated (ex. under `/tmp/tensorboard/plugins/profile/2021_07_21_13_44_21/localhost_9012.xplane.pb`).

**Comment by halcy** [comment]
I do see the files now (I didn't check into the plugin folder before - probably should have), however, my tensorboard (inside the colab cell output) is stuck on this screen:

![image](https://user-images.githubusercontent.com/59633/126513115-fe202742-7d9f-4617-8ac5-3418db5b589a.png)

Tried on both firefox (slightly outdated) and chrome (current), can't get it to show anything, even after 5 minutes. I'm not sure if there is anything in my local setup that could cause this, but if it works for you, then there has to be, I guess.

**Comment by jysohn23** [comment]
I also observed the tensorboard inline cell output for profile tab not progressing from the loading data screen. I'll try to take a look at this issue today.

Alternatively, what I did was download the output from `/tmp/tensorboard` and then spin up a separate tensorboard server locally to visualize.

**Comment by jysohn23** [comment]
Cause of it is https://github.com/tensorflow/tensorboard/issues/5088, you can update the `%tensorboard` command to `%tensorboard --logdir /tmp/tensorboard --load_fast=false`. Will send PR to fix notebook too.
