### ISSUE TITLE
Running regular PyTorch with PT-XLA CUDA Container

### ISSUE THREAD

**Issue by codeislife99** [pytorch/xla#3052]
With the PT-XLA containers for CUDA, it is only possible to run PT-XLA. If one tries to run regular PyTorch, then we get 
`Torch not compiled with CUDA enabled`. Is there any change that can be made to the Dockerfile so that both regular CUDA PyTorch and PT-XLA can be run on the same container ?

**Comment by jysohn23** [comment]
I don't think we've tested it but you could try enabling this for https://github.com/pytorch/pytorch/blob/3d6aa3a2f6e67140a21ca1e33fab089a57600fe7/setup.py#L14: https://github.com/pytorch/xla/blob/c297289b2724549df874418d8ea4cd4161e47f47/docker/Dockerfile#L20
