### ISSUE TITLE
Converting GPU ops to TPU (XLA)

### ISSUE THREAD

**Issue by pulkitgo** [pytorch/xla#3062]
## ❓ Questions and Help
Hi! I am trying to port the following StyleGAN code to TPU: [Op Code](https://github.com/rosinality/stylegan2-pytorch/tree/master/op). Is it possible to convert these ops to XLA ? (I am relatively new to PyTorch XLA, so not sure if something similar can be done here).

Thanks!

**Comment by JackCaoG** [comment]
Hmm, this is something I am less familiar with. I am looking at [this file](https://github.com/rosinality/stylegan2-pytorch/blob/f8dc9ad21746c81029c86eb8a3bfaf92a3988ce6/op/fused_act.py#L15) and it seems like `fused_bias_act.cpp` defines function prototype and `fused_bias_act_kernel.cu` defines the lowering. @bdhirsh Do you know if pt/xla can also do something like this?

**Comment by JackCaoG** [comment]
For the lowering part, you can take a look at [this guide](https://github.com/pytorch/xla/blob/master/OP_LOWERING_GUIDE.md), but I am not sure how we can generate a custom op that xla can lower. One alternative is to build a `XlaBuilderOP`. Some example would be [this pr](https://github.com/pytorch/xla/pull/2507).
