### ISSUE TITLE
What is xm.RateTracker? Why there is no document for this class?

### ISSUE THREAD

**Issue by DayuanJiang** [pytorch/xla#3076]
`xm.RateTracker()` is used in the example script. But I can' find any document for this class(even the doc string does not exist).
What is this class?
## ❓ Questions and Help
https://github.com/pytorch/xla/blob/81eecf457af5db09a3131a00864daf1ca5b8ed20/test/test_train_mp_mnist.py#L123

**Comment by JackCaoG** [comment]
It is pretty self-explanatory, you can check the code in [here](https://github.com/pytorch/xla/blob/815197139b94e5655ed6b347f48864e73dc73011/torch_xla/core/xla_model.py#L328). It is tracking the rate of certain events in a period of time.

**Comment by DayuanJiang** [comment]
@JackCaoG  Thanks!
