### ISSUE TITLE
Can't pull gcr.io image

### ISSUE THREAD

**Issue by kungfu-eric** [pytorch/xla#3077]
## 📚 Documentation

I followed the Consume Prebuilt Compute VM Images but should I be able to pull an image? Gcr.io isnt resolving from inside the compute VM.

`sudo docker run --shm-size 16G -e XRT_TPU_CONFIG="tpu_worker;0;$TPU_IP_ADDRESS:8470" gcr.io/tpu-pytorch/xla:r1.9 python /pytorch/xla/test/test_train_mp_mnist.py
Unable to find image 'gcr.io/tpu-pytorch/xla:r1.9' locally
docker: Error response from daemon: manifest for gcr.io/tpu-pytorch/xla:r1.9 not found: manifest unknown: Failed to fetch "r1.9" from request "/v2/tpu-pytorch/xla/manifests/r1.9".
`

Shouldn't this work? I tried a docker login gcr.io but got permission denied.

**Comment by JackCaoG** [comment]
Sorry about this, it seems like we didn't tag 1.9 correctly. Can you do 
```
sudo docker pull gcr.io/tpu-pytorch/xla:r1.9_3.6
```
or
```
sudo docker pull gcr.io/tpu-pytorch/xla:r1.9_3.7
```
depending on your python version. @jysohn23 Can you help to fix this?

**Comment by jysohn23** [comment]
Could you retry @kungfu-eric?

**Comment by kungfu-eric** [comment]
Works now, thanks!
