### ISSUE TITLE
AMP stop working for Pytorch/XLA

### ISSUE THREAD

**Issue by JackCaoG** [pytorch/xla#3086]
failure message
```
++ command -v nvidia-smi
+ '[' -x /usr/bin/nvidia-smi ']'
+ python test/test_autocast.py
/opt/conda/lib/python3.6/site-packages/torch/autocast_mode.py:139: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
======================================================================
FAIL: test_autocast_banned (__main__.TestAutocast)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_autocast.py", line 223, in test_autocast_banned
    getattr(module, op)(*args)
AssertionError: RuntimeError not raised
```

test is currently only being run on gpu so won't imapct upstream cpu CI. Will try to take a look today and disable it for now if needs additional time.

**Comment by JackCaoG** [comment]
Tried to run amp imagenet using the nightly cuda docker and saw the same
```
/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/autocast_mode.py:139: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
```

Speed dropped to slightly below the non-amp version. Looking into it. 

@bdhirsh @yaochengji @codeislife99 @rwightman FYI.

**Comment by JackCaoG** [comment]
@bdhirsh What do you think is the best way to prevent this kind of regression from happening? We can always try to catch these on pt/xla land but fixing them after is a bit of burden. We currently only run cpu CI on pytorch/xla, would it be feasible to also run gpu CI from upstream? I think running amp test along for GPU would be enough.

**Comment by JackCaoG** [comment]
@ezyang I think the regression is coming from [this pr](https://github.com/pytorch/pytorch/commit/324673a537fc818527b8375700a9b95a83a00c92#diff-688be417042a389cd06bdaa4f45d527c522ea010ced0b08282d0b5e55332497fR138). This is a bit tricky as there is not an easy way to check whether pt/xla is available (try import block would be a bit ugly, but this is the only way I can think of right now). WDYT?

I will disable `test_autocast.py` in the mean time to get a green CI.

**Comment by JackCaoG** [comment]
Ah using `torch.cuda.amp.common.amp_definitely_not_available()` instead resolved this issue, I will send a pr to pytorch.

**Comment by bdhirsh** [comment]
@JackCaoG Running some minimal xla amp tests sounds reasonable. I know we have separate `test_autocast.py` code in core vs. xla. Do you think it would be reasonable to modify a (maybe small piece of) the `test_autocast.py` in core to work with both xla and cuda? We talked a little in the original PR that added the tests to pytorch/xla about how making those tests device-generic is a decent amount of work. Maybe we could make a subset of it run with xla?

**Comment by ezyang** [comment]
Can we make test_autocast.py use the generic backend machinery? If we had that, then XLA could easily reinstantiate it at XLA device and run the tests there.

**Comment by JackCaoG** [comment]
It is actually a bit hard to extend xla as a generic backend to this test because
1. some of the test just go through a list of ops and test amp, but xla doesn't have all lowering for them. When fallback happen the test will failed since some op doesn't have fp16 implementation on native CPU.
2. I only pick a set of test that will pass on pt/xla version of test_autocast.py. Some of the test are doing very cuda specified check that won't work for lxa.

However I found I can actually run `test_autocast.py` on xla::cpu. I will do that and add this to our regular CPU CI to increate the coverage. This should also be run for all pytorch upstream pr then.
