### ISSUE TITLE
Add `torchtext` to `env-setup.py`

### ISSUE THREAD

**Issue by akihironitta** [pytorch/xla#3095]
## 🚀 Feature
I'd like to suggest updating `contrib/scripts/env-setup.py` so that people don't have to manually adjust `torchtext`'s version similarly to `torchvision`'s one which is achieved at:

https://github.com/pytorch/xla/blob/61e3960cb3ad6401d8a4bf0e952a6e140de95ccb/contrib/scripts/env-setup.py#L23

## Motivation
With this change, users don't have to adjust `torchtext` version manually.

## Pitch
Something like https://github.com/akihironitta/xla/commit/1a4a172379dffadb7003406e97f83be0d05d2151.

## Alternatives
None

## Additional context
Action from the maintainers is required (i.e. need to upload wheels for `torchtext` similarly to `torchvision`'s.). This suggestion also applies for `torchaudio`.

**Comment by JackCaoG** [comment]
Hi @akihironitta , thanks for the request! Uploading a wheel is easy for us but we do not have test setup to test `torchtext`(both for stable release and nightly) for now. Adding the support officially will takes us a bit more time and resource. May we know what's your use case of `pytorch/xla` with `torchtext`?

**Comment by akihironitta** [comment]
@JackCaoG Hi, thank you for having a look! I was trying to use Lightning Flash (built on top of PyTorch Lightning) in a Kaggle notebook, and `torchtext` is one of the optional dependencies of Lightning Flash. After installing xla, I need to either:

- manually uninstall `torchtext`
- manually adjust the version `torchtext` for compatibility

to avoid `OSError` shown below. This is because `torchtext` is preinstalled on Kaggle notebook environment and `setup-env.py` doesn't care about installed `torchtext` version (unlike `torchvision`), right. If this issue is addressed, there's no need of any of the manual operations above.

```console
$ # https://www.kaggle.com/akihironitta/pytorch-xla-issues-3095
$ # check preinstalled versions
$ pip list|grep torch|grep -v pytorch
torch                          1.7.0
torchaudio                     0.7.0a0+ac17b64
torchmetrics                   0.4.1
torchtext                      0.8.0a0+cd6902d
torchvision                    0.8.1
$ # install xla with compatible versions of torch and torchvision
$ curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
...
$ python pytorch-xla-env-setup.py --version 1.9 --apt-packages libomp5 libopenblas-dev
...
$ pip list|grep torch|grep -v pytorch
torch                          1.9.0a0+git1a7c23c
torch-xla                      1.9
torchaudio                     0.7.0a0+ac17b64
torchmetrics                   0.4.1
torchtext                      0.8.0a0+cd6902d
torchvision                    0.11.0a0+4658f24
$ # install Lightning Flash which has `torchtext` as an optional dependency
$ pip install git+https://github.com/PytorchLightning/lightning-flash.git@master
...
$ python -c "import flash"
...
OSError: /opt/conda/lib/python3.7/site-packages/torchtext/_torchtext.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtESt10shared_ptrIS0_EPSo
$ pip list|grep torch|grep -v pytorch
torch                          1.9.0a0+git1a7c23c
torch-xla                      1.9
torchaudio                     0.7.0a0+ac17b64
torchmetrics                   0.4.1
torchtext                      0.8.0a0+cd6902d
torchvision                    0.11.0a0+4658f24
```

Reproducible notebook: https://www.kaggle.com/akihironitta/pytorch-xla-issues-3095
Lightning Flash: https://github.com/PyTorchLightning/lightning-flash
PyTorch Lightning: https://github.com/PyTorchLightning/pytorch-lightning
