### ISSUE TITLE
device=xm.xla_device(devkind='GPU')，Calling Net().to(device) interface throws an exception

### ISSUE THREAD

**Issue by ZhongYFeng** [pytorch/xla#3099]
## 🐛 Bug

An exception is thrown when the model calls to translate to an XLA device running

## To Reproduce

>>> import torch
>>> import torch_xla
>>> import torch_xla.core.xla_model as xm
>>> import torch.nn as nn
>>> import torch.nn.functional as F
>>> class Net(nn.Module):
...     def __init__(self):
...         super(Net, self).__init__()
...         self.conv1 = nn.Conv2d(1, 32, 3, 1)
...         self.conv2 = nn.Conv2d(32, 64, 3, 1)
...         self.dropout1 = nn.Dropout(0.25)
...         self.dropout2 = nn.Dropout(0.5)
...         self.fc1 = nn.Linear(9216, 128)
...         self.fc2 = nn.Linear(128, 10)
...     def forward(self, x):
...         x = self.conv1(x)
...         x = F.relu(x)
...         x = self.conv2(x)
...         x = F.relu(x)
...         x = F.max_pool2d(x, 2)
...         x = self.dropout1(x)
...         x = torch.flatten(x, 1)
...         x = self.fc1(x)
...         x = F.relu(x)
...         x = self.dropout2(x)
...         x = self.fc2(x)
...         output = F.log_softmax(x, dim=1)
...         return output
>>> device=xm.xla_device(devkind='GPU')
>>> model = Net().to(device)
## Error
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 852, in to
    return self._apply(convert)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 850, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:421 : Check failed: session->session()->Run(session_work->feed_inputs, session_work->outputs_handles, &outputs) == ::tensorflow::Status::OK() (Invalid argument: Cannot assign a device for operation XRTAllocateFromTensor: {{node XRTAllocateFromTensor}} was explicitly assigned to /job:localservice/replica:0/task:0/device:XLA_GPU:0 but available devices are [ /job:localservice/replica:0/task:0/device:CPU:0, /job:localservice/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device.
         [[XRTAllocateFromTensor]] vs. OK)
*** Begin stack trace ***
        tensorflow::CurrentStackTrace()

        xla::util::MultiWait::Complete(std::function<void ()> const&)

        clone
*** End stack trace ***

## Expected behavior
No exception thrown

## Environment
Collecting environment information...
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.21.1
Libc version: glibc-2.9

Python version: 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 18:21:58) [GCC 7.2.0] (64-bit runtime)
Python platform: Linux-4.4.0-21-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: NVIDIA Tesla V100-SXM2-32GB
GPU 1: NVIDIA Tesla V100-SXM2-32GB
GPU 2: NVIDIA Tesla V100-SXM2-32GB
GPU 3: NVIDIA Tesla V100-SXM2-32GB

Nvidia driver version: 465.19.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.15.4
[pip3] torch==1.9.0
[pip3] torch-xla==1.9
[pip3] torchvision==0.10.0
[conda] mkl-include 2021.3.0
[conda] numpy 1.15.4
[conda] torch 1.9.0
[conda] torch-xla 1.9
[conda] torchvision 0.10.0

**Comment by JackCaoG** [comment]
`was explicitly assigned to /job:localservice/replica:0/task:0/device:XLA_GPU:0 but available devices are [ /job:localservice/replica:0/task:0/device:CPU:0, /job:localservice/replica:0/task:0/device:XLA_CPU:0 ` This means that XRT runtime can not access the GPU device, it can only see CPU devices. Were you using the nightly GPU docker image we published? How did you install the PyTorch/XLA GPU?

**Comment by ZhongYFeng** [comment]
Problems caused by not enabling cuda
