### ISSUE TITLE
unable to resolve the error : Input tensor is not an XLA tensor: torch.FloatTensor

### ISSUE THREAD

**Issue by soumochatterjee** [pytorch/xla#3108]
## ❓ Questions and Help
Need Help in resolving this bug :

> Input tensor is not an XLA tensor: torch.FloatTensor
> An exception has occurred, use %tb to see the full traceback.

Notebook : https://www.kaggle.com/soumochatterjee/g2netpytorch?scriptVersionId=73704807

**Comment by JackCaoG** [comment]
Looking at the stack trace
```
	torch_xla::AtenXlaType::convolution_overrideable(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long)
```

It seems like at least one of the three `at::Tensor` passed to convolution is not a `XLA Tensor`. This usually menas they are a cpu tensor. One easy way to debug this is to print all three tensors before calling `conv` and this should give you a better idea of what is going on.
