### ISSUE TITLE
The TPU system has not been initialized

### ISSUE THREAD

**Issue by lvjiujin** [pytorch/xla#3113]
## ❓ Questions and Help
When I use pytorch on google colab with the tpu, it occur the following error:
`Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:2204: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-30-1d8dd82aac92> in <module>()
      1 for epoch in range(5):
----> 2     train(epoch)

<ipython-input-29-07e343570917> in train(epoch)
     10         # optimizer.zero_grad()
     11         if _%500==0:
---> 12             print(f'Epoch: {epoch}, Loss:  {loss.item()}')
     13 
     14         optimizer.zero_grad()

RuntimeError: Failed precondition: From /job:tpu_worker/replica:0/task:0:
The TPU system has not been initialized.
	 [[{{node XRTCompile}}]]`

**Comment by miladm** [comment]
Can you please provide a reference to the code block / colab link that throws this error?
