### ISSUE TITLE
How to aggregate the results running on multiple tpu cores

### ISSUE THREAD

**Issue by pradeepkr12** [pytorch/xla#3114]
## ❓ Questions and Help
Hi, How can we aggregate the results or say combine all the predictions and use it further.

I understand this could be a issue addressed earlier, if yes please share some links related to this
```
def _run():
    <model loading,  training arguments and etc >
    # using hugging face Trainer fn
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=data_train,
        tokenizer=tokenizer,
        eval_dataset=data_val,
        compute_metrics=compute_metrics,

    )
    trainer.train()
    results = trainer.evaluate()
    return results

def _mp_fn(rank, flags):
    results = _run()

FLAGS={}
xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=8, start_method='fork')
```

**Comment by miladm** [comment]
You call one of PT/XLA's multi-core communication APIs, like `xm.all_reduce`.
Here are a few references to help you further: `[torch_xla.core.xla_model.all_reduce](https://pytorch.org/xla/release/1.9/index.html#torch_xla.core.xla_model.all_reduce)` and `[imagenet example](https://github.com/pytorch/xla/blob/master/test/test_train_mp_imagenet.py#L223)`
