### ISSUE TITLE
Previously working code fails on Cloud TPU with signal SIGABRT

### ISSUE THREAD

**Issue by tgisaturday** [pytorch/xla#3123]
## 🐛 Bug

The source codes which were working fine now throws SIGBART errors. 

Thess codes didn't cause any problem two week ago but now throws this error. 
## To Reproduce

Here's the source codes and example run command:

https://github.com/tgisaturday/dalle-lightning
python train_vae.py --use_tpus --fake_data

https://github.com/tgisaturday/minGPT

python3 minGPT/benchmark.py --n_layer 14 --n_head 16 --n_embed 3072 --batch_size 1 --tpus 8

Although error throws "tcmalloc: large alloc", this seems like somewhat not related to tcmalloc since I can't even run small models and different codes show same errors. 
## Environment

 - Reproducible on XLA backend [CPU/TPU]:
 - torch_xla version:

## Additional context

tcmalloc: large alloc 1694531584 bytes == 0x8044000 @  0x7f714ec58680 0x7f714ec78ff4 0x7f714e76f309 0x7f714e770fb9 0x7f714e771056 0x7f6ec5998659 0x7f6ebb3ce954 0x7f714ee4cb8a 0x7f714ee4cc91 0x7f714ebab915 0x7f714ee510bf 0x7f714ebab8b8 0x7f714ee505fa 0x7f714ea2034c 0x7f714ebab8b8 0x7f714ebab983 0x7f714ea20b59 0x7f714ea203da 0x67299f 0x682dcb 0x684321 0x5c3cb0 0x5f257d 0x56fcb6 0x56822a 0x5f6033 0x56ef97 0x5f5e56 0x56a136 0x5f5e56 0x569f5e
tcmalloc: large alloc 24013623311556608 bytes == (nil) @  0x7f714ec58680 0x7f714ec78ff4 0x7f714e76f309 0x7f714e770fb9 0x7f714e771056 0x7f6ec5998659 0x7f6ebb3cea09 0x7f714ee4cb8a 0x7f714ee4cc91 0x7f714ebab915 0x7f714ee510bf 0x7f714ebab8b8 0x7f714ee505fa 0x7f714ea2034c 0x7f714ebab8b8 0x7f714ebab983 0x7f714ea20b59 0x7f714ea203da 0x67299f 0x682dcb 0x684321 0x5c3cb0 0x5f257d 0x56fcb6 0x56822a 0x5f6033 0x56ef97 0x5f5e56 0x56a136 0x5f5e56 0x569f5e
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
https://symbolize.stripped_domain/r/?trace=7f714ea8e18b,7f714ea8e20f&map=
*** SIGABRT received by PID 8498 (TID 8498) on cpu 0 from PID 8498; stack trace: ***
PC: @     0x7f714ea8e18b  (unknown)  raise
    @     0x7f6f52a951e0        976  (unknown)
    @     0x7f714ea8e210  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7f714ea8e18b,7f6f52a951df,7f714ea8e20f&map=ca1b7ab241ee28147b3d590cadb5dc1b:7f6f45d96000-7f6f52dc8b20
E0912 00:39:45.713889    8498 coredump_hook.cc:292] RAW: Remote crash data gathering hook invoked.
E0912 00:39:45.713907    8498 coredump_hook.cc:384] RAW: Skipping coredump since rlimit was 0 at process start.
E0912 00:39:45.713925    8498 client.cc:222] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E0912 00:39:45.713934    8498 coredump_hook.cc:447] RAW: Sending fingerprint to remote end.
E0912 00:39:45.713943    8498 coredump_socket.cc:124] RAW: Stat failed errno=2 on socket /var/google/services/logmanagerd/remote_coredump.socket
E0912 00:39:45.713987    8498 coredump_hook.cc:451] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] Missing crash reporting socket. Is the listener running?
E0912 00:39:45.714010    8498 coredump_hook.cc:525] RAW: Discarding core.
E0912 00:39:45.716727    8498 process_state.cc:771] RAW: Raising signal 6 with default behavior
Aborted (core dumped)

**Comment by JackCaoG** [comment]
Hi @tgisaturday, thanks for reporting! I want to ask some clarification question
When you mentioned this code previous worked, what's the 
1. PyTorch version
2. PyTorch/XLA version
3. PyTorch Lighting version
4. TPUVM image version(I am guessing you are using TPUVM and the image version should be v2-alpha)?

I want to understand a bit more about what has changed between your previous run and your current run. Does PyTorch/XLA always fail? Could you try some PyTorch/XLA simple test like [test_train_mp_imagenet.py](https://github.com/pytorch/xla/blob/master/test/test_train_mp_imagenet.py) with `python3 test_train_mp_imagenet.py --fake_data`? 

From the first glance this seems to be some c++ allocation failure which might be due to some sort of OOM. I am surprise that even smaller models would fail. Another thing you could try is to create a new TPUVM and see if it make any difference.

**Comment by tgisaturday** [comment]
1. Pytorch version: 1.8.1
2. Pytorch/XLA : 1.8.1
3. Pytorch Lightning: 1.4.0 maybe..? The actual one I was using is forked one here. https://github.com/tgisaturday/pytorch-lightning
4. TPU VM: v2-alpha

and train_mp_imagenet.py was working.

I've also created new TPU VMs but wasn't working either. To be more specific, the imagenet test code is working now, but none of my previously working codes.

And yes, it tcmalloc OOM happens even with small models.
________________________________

**Comment by juneoh** [comment]
This may be something changed on the PyTorch Lightning side, especially since `test_train_mp_imagenet.py` is working and none of our related tests are breaking. Can you try:

1. [Disabling tcmalloc](https://cloud.google.com/tpu/docs/pytorch-xla-ug-tpu-vm#basic_setup) via `unset LD_PRELOAD`; or,
2. Reverting to a version of PyTorch Lightning that was previously working for you?

**Comment by tgisaturday** [comment]
@juneoh 
 1. unset LD_PRELOAD causes errors.
 2. I've been already using my custom PyTorch Lightning Forked repo but same version isn't working now. 
 @kaushikb11, Regrading Lightning, was there any major changes that might effect TPU side?

Here's the error I get when I disable tcmalloc:

free(): invalid pointer
https://symbolize.stripped_domain/r/?trace=7f48bd4c418b,7f48bd4c420f,7f48bd51647b,7f461d72fad2,7f48bd68bb89&map=
*** SIGABRT received by PID 164099 (TID 164099) on cpu 47 from PID 164099; stack trace: ***
PC: @     0x7f48bd4c418b  (unknown)  raise
    @     0x7f46c16001e0        976  (unknown)
    @     0x7f48bd4c4210  (unknown)  (unknown)
    @     0x7f48bd51647c        288  (unknown)
    @     0x7f461d72fad3         64  _GLOBAL__sub_I_xla_cpu_device.cc
    @     0x7f48bd68bb8a  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7f48bd4c418b,7f46c16001df,7f48bd4c420f,7f48bd51647b,7f461d72fad2,7f48bd68bb89&map=ca1b7ab241ee28147b3d590cadb5dc1b:7f46b4901000-7f46c1933b20
E0914 00:02:23.716427  164099 coredump_hook.cc:292] RAW: Remote crash data gathering hook invoked.
E0914 00:02:23.716452  164099 coredump_hook.cc:384] RAW: Skipping coredump since rlimit was 0 at process start.
E0914 00:02:23.716462  164099 client.cc:222] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E0914 00:02:23.716471  164099 coredump_hook.cc:447] RAW: Sending fingerprint to remote end.
E0914 00:02:23.716479  164099 coredump_socket.cc:124] RAW: Stat failed errno=2 on socket /var/google/services/logmanagerd/remote_coredump.socket
E0914 00:02:23.716493  164099 coredump_hook.cc:451] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] Missing crash reporting socket. Is the listener running?
E0914 00:02:23.716497  164099 coredump_hook.cc:525] RAW: Discarding core.
E0914 00:02:23.720000  164099 process_state.cc:771] RAW: Raising signal 6 with default behavior
Aborted (core dumped)

**Comment by JackCaoG** [comment]
@juneoh Can you try to repo this failure? This seems like a memory leak but it only happens when using through lighting. The only good news is that this crash seems deterministic. One thing you try is to switch to 1.9 and see if it makes any difference, we have instruction in [here](https://cloud.google.com/tpu/docs/pytorch-xla-ug-tpu-vm).

`_GLOBAL__sub_I_xla_cpu_device.cc` seems suspicious since pytorch/xla shouldn't try to use xla_cpu device on TPUVM...

**Comment by JackCaoG** [comment]
Something is wrong with our 1.9 wheel, I am working on a fix. Please don't try 1.9 for now.

**Comment by kaushikb11** [comment]
Thanks @JackCaoG for the update!

**Comment by juneoh** [comment]
Trying to repro. tgisaturday/dalle-lightning seems to upgrade torch to the latest version, so I've tried tgisaturday/minGPT instead.

Its dependency on tgisaturday/lightning-pytorch's latest commit had some issues, so trying the previous commit `f1eed87` from yesterday instead. Also, I'm using the  below command:

```bash
python3 benchmark.py --n_layer 4 --n_head 8 --n_embd 2048 --batch_size 1 --tpu_cores 8
```

Got the reported message:

```
https://symbolize.stripped_domain/r/?trace=7f69be754574,7f69be7aa20f,90801f&map=
*** SIGSEGV (@0x7f8cf823c000), see gl__________25#s15 received by PID 41221 (TID 41221) on cpu 95; stack trace: ***
PC: @     0x7f69be754574  (unknown)  sem_trywait@@GLIBC_2.2.5
    @     0x7f673eb831e0        976  (unknown)
    @     0x7f69be7aa210  (unknown)  (unknown)
    @           0x908020  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7f69be754574,7f673eb831df,7f69be7aa20f,90801f&map=ca1b7ab241ee28147b3d590cadb5dc1b:7f6731e84000-7f673eeb6b20
E0914 06:09:02.952476   41221 coredump_hook.cc:292] RAW: Remote crash data gathering hook invoked.
E0914 06:09:02.952492   41221 coredump_hook.cc:384] RAW: Skipping coredump since rlimit was 0 at process start.
E0914 06:09:02.952509   41221 client.cc:222] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E0914 06:09:02.952514   41221 coredump_hook.cc:447] RAW: Sending fingerprint to remote end.
E0914 06:09:02.974499   41221 coredump_socket.cc:124] RAW: Stat failed errno=2 on socket /var/google/services/logmanagerd/remote_coredump.socket
E0914 06:09:02.974562   41221 coredump_hook.cc:451] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] Missing crash reporting socket. Is the listener running?
E0914 06:09:02.974584   41221 coredump_hook.cc:525] RAW: Discarding core.
E0914 06:09:03.175933   41221 process_state.cc:771] RAW: Raising signal 11 with default behavior
```

But if I rewind tgisaturday/pytorch-lightning to `325b67f` the same command is able to train. This looks like that one of the commits for tgisaturday/pytorch-lightning is causing the issue?

I've also noticed that the fork is using pytorch-lightning of version `1.5.0-dev`. You may want to pin it to a stable version.

**Comment by juneoh** [comment]
Also — the 1.9 issue seems unrelated, as I've reproduced this on 1.8.1.

**Comment by tgisaturday** [comment]
> Trying to repro. tgisaturday/dalle-lightning seems to upgrade torch to the latest version, so I've tried tgisaturday/minGPT instead.
> 
> Its dependency on tgisaturday/lightning-pytorch's latest commit had some issues, so trying the previous commit `f1eed87` from yesterday instead. Also, I'm using the below command:
> 
> ```shell
> python3 benchmark.py --n_layer 4 --n_head 8 --n_embd 2048 --batch_size 1 --tpu_cores 8
> ```
> 
> Got the reported message:
> 
> ```
> https://symbolize.stripped_domain/r/?trace=7f69be754574,7f69be7aa20f,90801f&map=
> *** SIGSEGV (@0x7f8cf823c000), see gl__________25#s15 received by PID 41221 (TID 41221) on cpu 95; stack trace: ***
> PC: @     0x7f69be754574  (unknown)  sem_trywait@@GLIBC_2.2.5
>     @     0x7f673eb831e0        976  (unknown)
>     @     0x7f69be7aa210  (unknown)  (unknown)
>     @           0x908020  (unknown)  (unknown)
> https://symbolize.stripped_domain/r/?trace=7f69be754574,7f673eb831df,7f69be7aa20f,90801f&map=ca1b7ab241ee28147b3d590cadb5dc1b:7f6731e84000-7f673eeb6b20
> E0914 06:09:02.952476   41221 coredump_hook.cc:292] RAW: Remote crash data gathering hook invoked.
> E0914 06:09:02.952492   41221 coredump_hook.cc:384] RAW: Skipping coredump since rlimit was 0 at process start.
> E0914 06:09:02.952509   41221 client.cc:222] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
> E0914 06:09:02.952514   41221 coredump_hook.cc:447] RAW: Sending fingerprint to remote end.
> E0914 06:09:02.974499   41221 coredump_socket.cc:124] RAW: Stat failed errno=2 on socket /var/google/services/logmanagerd/remote_coredump.socket
> E0914 06:09:02.974562   41221 coredump_hook.cc:451] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] Missing crash reporting socket. Is the listener running?
> E0914 06:09:02.974584   41221 coredump_hook.cc:525] RAW: Discarding core.
> E0914 06:09:03.175933   41221 process_state.cc:771] RAW: Raising signal 11 with default behavior
> ```
> 
> But if I rewind tgisaturday/pytorch-lightning to `325b67f` the same command is able to train. This looks like that one of the commits for tgisaturday/pytorch-lightning is causing the issue?
> 
> I've also noticed that the fork is using pytorch-lightning of version `1.5.0-dev`. You may want to pin it to a stable version.

I've also tried official lightning stable release with minGPT and caused same error.

**Comment by juneoh** [comment]
Which version did you try? I've just tried installing `pytorch-lightning==1.4.6` asw ell, latest on PyPI, and it was able to train with your latest tgisaturday/minGPT:

```
juneoh_google_com@t1v-n-22ec77e3-w-0:~/minGPT$ python3 benchmark.py --n_layer 4 --n_head 8 --n_embd 2048 --batch_size 1 --tpu_cores 8
2021-09-14 07:07:11.704763: E tensorflow/core/framework/op_kernel.cc:1693] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin
2021-09-14 07:07:11.705688: E tensorflow/core/framework/op_kernel.cc:1693] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey
Global seed set to 42
data has 1115394 characters, 65 unique.
GPU available: False, used: False
TPU available: True, using: 8 TPU cores
IPU available: False, using: 0 IPUs
/home/juneoh_google_com/.local/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py:423: LightningDeprecationWarning: DataModule.setup has already been called, so it will not be called again. In v1.6 this behavior will change to always call DataModule.setup.
  rank_zero_deprecation(
2021-09-14 07:07:39.701044: E tensorflow/core/framework/op_kernel.cc:1693] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin
2021-09-14 07:07:39.701119: E tensorflow/core/framework/op_kernel.cc:1693] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey
Global seed set to 42
Global seed set to 42
2021-09-14 07:08:03.639144: E tensorflow/core/framework/op_kernel.cc:1693] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin
2021-09-14 07:08:03.639204: E tensorflow/core/framework/op_kernel.cc:1693] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey
Global seed set to 42
2021-09-14 07:08:05.519944: E tensorflow/core/framework/op_kernel.cc:1693] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin
2021-09-14 07:08:05.520011: E tensorflow/core/framework/op_kernel.cc:1693] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey
Global seed set to 42
Global seed set to 42
Global seed set to 42
Global seed set to 42
Global seed set to 42
2021-09-14 07:08:07.209986: E tensorflow/core/framework/op_kernel.cc:1693] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin
2021-09-14 07:08:07.210058: E tensorflow/core/framework/op_kernel.cc:1693] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey
2021-09-14 07:08:08.956792: E tensorflow/core/framework/op_kernel.cc:1693] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin
2021-09-14 07:08:08.956860: E tensorflow/core/framework/op_kernel.cc:1693] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey
2021-09-14 07:08:10.659746: E tensorflow/core/framework/op_kernel.cc:1693] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin
2021-09-14 07:08:10.659812: E tensorflow/core/framework/op_kernel.cc:1693] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey
2021-09-14 07:08:12.335544: E tensorflow/core/framework/op_kernel.cc:1693] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin
2021-09-14 07:08:12.335609: E tensorflow/core/framework/op_kernel.cc:1693] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey
2021-09-14 07:08:14.051083: E tensorflow/core/framework/op_kernel.cc:1693] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin
2021-09-14 07:08:14.051155: E tensorflow/core/framework/op_kernel.cc:1693] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey

  | Name    | Type       | Params
---------------------------------------
0 | tok_emb | Embedding  | 133 K
1 | drop    | Dropout    | 0
2 | blocks  | Sequential | 201 M
3 | ln_f    | LayerNorm  | 4.1 K
4 | head    | Linear     | 133 K
---------------------------------------
201 M     Trainable params
0         Non-trainable params
201 M     Total params
807.862   Total estimated model params size (MB)
Average Total memory: 129875.98 MB
Epoch 0:  25%|██████████████████████████████████████████████▏                                                                                                                                        | 273/1081 [00:39<01:56,  6.94it/s, loss=2.82, v_num=0]
```

**Comment by juneoh** [comment]
If `pytorch-lightning==1.4.6` and `tgisaturday/pytorch-lightning@325b67f` are both not working for you, can you try to create a new TPU VM instance and try afresh, for an off chance that the local environment's dependencies may have been corrupted?

**Comment by tgisaturday** [comment]
> If `pytorch-lightning==1.4.6` and `tgisaturday/pytorch-lightning@325b67f` are both not working for you, can you try to create a new TPU VM instance and try afresh, for an off chance that the local environment's dependencies may have been corrupted?

Here is current status in my attempts: 
1. Using minGPT with lightning 1.4.6 is OK. (installing requirements in minGPT)
2. Using dalle-lightning with 1.4.6 is not working. (installing requirements in dalle)
3. Using minGPT with lightning 1.4.6 and more is not working. (installing requirements in dalle)
 @kaushikb11  is there any torch-xla dependency change between lightning 1.4.6 and newest? @JackCaoG Seems like mismatch between certain xla wheel and other requirements is causing the issue.

**Comment by juneoh** [comment]
Nice find! It looks like something inside HuggingFace Transformers is the culprit here. Forcing `transformers==4.8.2` after dalle-pytorch installation works, but nothing higher than 4.8.2.

Digging in deeper, it looks like things broke around 2aa3cd (huggingface/transformers#11786), with a fix from huggingface/transformers#12591 required to run.

Tracing down the import path, the culprit is importing tensorflow before torch_xla. I.e., even without transformers installed, the issue can be reproduced with:

```python
import tensorflow
import torch_xla
```

...but not if the order is reversed.

This may possibly be a legitimate torch_xla issue, which has not surfaced until a recent change in HuggingFace Transformers started importing TF during initialization. This may take some time to fix, but @tgisaturday, you may be able to work around this issue by importing torch_xla before anything else. Sorry for the confusion!

**Comment by tgisaturday** [comment]
@juneoh Thank you for all your dedication to this issue. Glad that simple workaround can temporarily solve this issue.

**Comment by JackCaoG** [comment]
hmm, I have seen this `importing tf and torch_xla` issue on huggingface before, @ultrons do you remembered how we get around it last time? Did we ask huggingface to switch the import order or do a conditional import?

**Comment by ultrons** [comment]
@JackCaoG , sorry for the slow response on this.
I think my problem was solved by setting:
export USE_TORCH=ON

**Comment by ultrons** [comment]
More details in ./src/transformers/file_utils.py
