### ISSUE TITLE
notebook_launcher fails in colab

### ISSUE THREAD

**Issue by quantitative-technologies** [pytorch/xla#3136]
## 🐛 Bug

`xla` is failing with the error

```
ProcessExitedException: process 0 terminated with signal SIGSEGV
```
in a call to `spawn` from huggingface's `notebook_launcher`. This problem only occurs when running colab in the High-RAM TPU runtime type. 

This bug was originally posted to the `huggingface/accelerate` repo [here](https://github.com/huggingface/accelerate/issues/166#issue-999025926) but it was felt that the issue was being caused by a timeout during the wait for TPU availability, as the error occurs before any huggingface code is even run. 

## To Reproduce

1. Open the example huggingface notebook [Simple NLP Example](https://github.com/huggingface/notebooks/blob/9664c8b62e38083952b849da8912af13a35312b0/examples/accelerate/simple_nlp_example.ipynb) in colab.
2. Switch to runtime type -> Runtime shape = High-RAM
3. Run all cells

The last cell which calls `notebook_launcher` gives the following error:

```
Launching a training on 8 TPU cores.

loading configuration file https://huggingface.co/bert-base-cased/resolve/main/config.json from cache at /root/.cache/huggingface/transformers/a803e0468a8fe090683bdc453f4fac622804f49de86d7cecaee92365d4a0f829.a64a22196690e0e82ead56f388a3ef3a50de93335926ccfa20610217db589307
Model config BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.10.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 28996
}

loading weights file https://huggingface.co/bert-base-cased/resolve/main/pytorch_model.bin from cache at /root/.cache/huggingface/transformers/092cc582560fc3833e556b3f833695c26343cb54b7e88cd02d40821462a74999.1f48cab6c959fc6c360d22bea39d06959e90f5b002e77e836d2da45464875cda

---------------------------------------------------------------------------

ProcessExitedException                    Traceback (most recent call last)

<ipython-input-25-a91f3c0bb4fd> in <module>()
      1 from accelerate import notebook_launcher
      2 
----> 3 notebook_launcher(training_function)

3 frames

/usr/local/lib/python3.7/dist-packages/accelerate/notebook_launcher.py in notebook_launcher(function, args, num_processes, use_fp16, use_port)
     67             launcher = PrepareForLaunch(function, distributed_type="TPU")
     68             print(f"Launching a training on {num_processes} TPU cores.")
---> 69             xmp.spawn(launcher, args=args, nprocs=num_processes, start_method="fork")
     70         else:
     71             # No need for a distributed launch otherwise as it's either CPU or one GPU.

/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py in spawn(fn, args, nprocs, join, daemon, start_method)
    392         join=join,
    393         daemon=daemon,
--> 394         start_method=start_method)
    395 
    396 

/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py in start_processes(fn, args, nprocs, join, daemon, start_method)
    186 
    187     # Loop on join until it returns True or raises an exception.
--> 188     while not context.join():
    189         pass
    190 

/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py in join(self, timeout)
    134                     error_pid=failed_process.pid,
    135                     exit_code=exitcode,
--> 136                     signal_name=name
    137                 )
    138             else:

ProcessExitedException: process 0 terminated with signal SIGSEGV
```

## Expected behavior

Runs all cells with no errors. 

## Environment

 - Reproducible on XLA backend [CPU/TPU]: TPU
 - torch_xla version:
torch_xla-1.9-cp37-cp37m-linux_x86_64.whl

**Comment by jysohn23** [comment]
Hi, I'm not able to reproduce your issue using [this colab notebook](https://colab.research.google.com/github/huggingface/notebooks/blob/9664c8b62e38083952b849da8912af13a35312b0/examples/accelerate/simple_nlp_example.ipynb). Is this the right notebook?

![Screen Shot 2021-09-21 at 12 27 52 PM](https://user-images.githubusercontent.com/19496130/134210004-8ff844bb-5ae8-4d22-82f8-955315df5abb.png)

**Comment by quantitative-technologies** [comment]
Yes, it's the right one. Did you change the runtype to High-RAM (TPU) before running it?

**Comment by jysohn23** [comment]
Yeah

**Comment by RobinGeibel** [comment]
Hey, I have the exact same issue. Everything works fine on TPU and when I launch the notebook with an extended rum it crashes. Did you figure out how to solve this?

**Comment by quantitative-technologies** [comment]
No, I never solved it. 

I don't think the dev @jysohn23 really bothered to look at this either. 

I'm not seeing a way to reopen this issue.

**Comment by muellerzr** [comment]
@quantitative-technologies good news is we're able to recreate this, and it stems from `transformers` `from_pretrained`. The interim solution is to download the model *outside* of the loop and run it. 

- [Transformers issue to track](https://github.com/huggingface/transformers/issues/17659)
- [Accelerate TPU issue](https://github.com/huggingface/accelerate/issues/434)
- [Accelerate high-ram GPU issue](https://github.com/huggingface/accelerate/issues/440)
- [HuggingFace forums discussion](https://discuss.huggingface.co/t/simple-nlp-example-not-working/9913)

**Comment by quantitative-technologies** [comment]
Cool! I've alternatives to `notebook_launcher` since then, but perhaps I will try it out again.

**Comment by muellerzr** [comment]
@quantitative-technologies did the transformers code work for you under the alternative to nb launcher? (Also curious what they are)

**Comment by quantitative-technologies** [comment]
@muellerzr Yes. Perhaps "cheating", but I used the huggingface XLA scripts within my colab notebook. For example, I create a bash script including commands such as:

```
python transformers/examples/pytorch/xla_spawn.py --num_cores 8 \
  transformers/examples/pytorch/language-modeling/run_mlm.py \
  --model_name_or_path {mlm_model_path} \
  --output_dir {mlm_model_path} \
  --dataset_name $PERPLEXITY_DATASET \
  --dataset_config_name $PERPLEXITY_DATASET_CONFIG \
  --tokenizer_name $CHECKPOINT \
  --do_eval
```

Then I would call the bash script from the notebook. 

I plan to include the details in the next blog I write and can put a link here when it's done.

**Comment by muellerzr** [comment]
@quantitative-technologies this should be fixed now thanks to the latest release of Accelerate and can be closed.
