### ISSUE TITLE
Update CI image to not be reliant on pytorch/pytorch

### ISSUE THREAD

**Issue by seemethere** [pytorch/xla#3159]
Follow up to https://github.com/pytorch/xla/pull/3158

PyTorch CI is constantly changing and downstream projects should not rely on specific images as a side effect of PyTorch's CI since the upstream CI can change at any moment.

`pytorch/xla` should ideally build its own CI images so that changes to upstream CI should not disrupt CI within this repository

**Comment by JackCaoG** [comment]
As part of this process, we should also migrate to cuda 11.2 since pytorch/xla will drop support for cuda 10.2. @seemethere Do you have any doc/suggestion on how can we build our own docker image? Is there an CI image that come with cuda 11.2(11.1) that we can use in the mean time?

**Comment by yeounoh** [comment]
Hi @seemethere I've created a new build image for xla. Could you help adding it to the PyTorch ECR base image repo?
```
# How to add a new base docker image?
...
Add a repo in AWS ECR to hold your image. It requires access to PyTorch's AWS account to do this step.
```
Repo name can be something like,
```
308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/xla_base:${tag}
```
we can fix the repo name to be `xla_base` per a single repo tracking different base image versions.

**Comment by yeounoh** [comment]
Thanks @seemethere for creating the repo. I've also created one in `gcr`. In case we want to go back and forth between our own and PyTorch ones, it would be easier to go back to the torch repo in `ecr` so we can just do a single authorisation for both.
