### ISSUE TITLE
libtpu can not be installed for 1.10.0 version

### ISSUE THREAD

**Issue by dbalabka** [pytorch/xla#3191]
## 🐛 Bug

During the installation of 1.10.0 version, pip throws an error because of not found file:
https://storage.googleapis.com/cloud-tpu-tpuvm-artifacts-dev/wheels/libtpu-nightly/libtpu_nightly-0.1.dev20211013-py3-none-any.whl

Still, the file exists under a different link:
https://storage.googleapis.com/cloud-tpu-tpuvm-artifacts/wheels/libtpu-nightly/libtpu_nightly-0.1.dev20211013-py3-none-any.whl

## Steps to reproduce

```shell
poetry add https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch_xla-1.10-cp38-cp38-linux_x86_64.whl
```

**Comment by JackCaoG** [comment]
Thanks for reporting, this seems like an link issue on our end. @miaoshasha Can you take a look at this one? I think we need to update https://github.com/pytorch/xla/blob/master/setup.py#L57 for nightly and 1.10. We only need to rebuild the TPUVM wheel for this purpose.

**Comment by miaoshasha** [comment]
to change to 1015 libtpu and update link
https://github.com/pytorch/xla/pull/3198
https://github.com/pytorch/xla/pull/3197

to rebuild wheels and images after these merged in

**Comment by JackCaoG** [comment]
Issue should be fixed now, I tried
```
sudo pip3 install torch_xla[tpuvm] -f https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch_xla-1.10-cp38-cp38-linux_x86_64.whl
```

and it seems like libtpu is being installed correctly.

**Comment by JackCaoG** [comment]
I will close this issue for now, feel free to reopen if you still run into this issue.
