### ISSUE TITLE
torch_xla.distributed.parallel_loader.ParallelLoader lack the definition for the parameter

### ISSUE THREAD

**Issue by rwbfd** [pytorch/xla#3194]
## 📚 Documentation

"batches_per_execution" seems to have no explanation. In TensorFlow, it seems that you can feed several batches together to train, is this the right parameter?

**Comment by JackCaoG** [comment]
Looking at https://github.com/pytorch/xla/blob/223ca031bd7ac92ea55107a9d79e73b035e6cdec/torch_xla/distributed/parallel_loader.py#L44

I think it means the number of batch being loaded before the execution happens. I think it is the right parameter for your purpose.
