### ISSUE TITLE
can not import torch_xla

### ISSUE THREAD

**Issue by NYNYNY67** [pytorch/xla#3211]
The tutorials notebooks do not work correctly now.
it may be version issue, and I have no idea how to fix it.

**Comment by NYNYNY67** [comment]
WARNING:root:Waiting for TPU to be start up with version pytorch-1.9...
WARNING:root:Waiting for TPU to be start up with version pytorch-1.9...
WARNING:root:TPU has started up successfully with version pytorch-1.9
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-ebe519c076f6> in <module>()
      3 
      4 # imports the torch_xla package
----> 5 import torch_xla
      6 import torch_xla.core.xla_model as xm

/usr/local/lib/python3.7/dist-packages/torch_xla/__init__.py in <module>()
    140 import torch
    141 from ._patched_functions import _apply_patches
--> 142 import _XLAC
    143 
    144 

ImportError: /usr/local/lib/python3.7/dist-packages/_XLAC.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at13_foreach_erf_EN3c108ArrayRefINS_6TensorEEE

**Comment by JackCaoG** [comment]
Thanks for reporting! Can you share a bit more detial? We have test running for 1.9 and everything seems fine on our end. Were you using colab or a Cloud VM? Can you share a small repo?

**Comment by rwightman** [comment]
@NYNYNY67 @JackCaoG I just ran into this on a colab notebook that was working 1 day ago, they just switched to pytorch 1.10. Tying `!pip install cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.10-cp37-cp37m-linux_x86_64.whl` didn't work as I end up with the GLIB  error in #3186

**Comment by rwightman** [comment]
At the start of the notebook, uninstalling torch, torchvision, torchtext, torchaudio and then installing 1.9 and related packages before install pytorch xla 1.9 works until there is a 1.10 solution

**Comment by NYNYNY67** [comment]
@JackCaoG 
thanks for your response
I'm using colab notebook.

@rwightman 
It is exactly the issue I had and your solution worked for me thank you.
Added this cell on the top of the notebook.
```
!pip uninstall -y torch
!pip uninstall -y torchvision
!pip uninstall -y torchtext
!pip uninstall -y torchaudio
!pip install torch==1.9
!pip install torchvision==0.10
```

**Comment by JackCaoG** [comment]
@rwightman 1.10 is a known issue, it is tracked in https://github.com/pytorch/xla/issues/3186. We are working on compiling a new wheel that is compatible with colab
