### ISSUE TITLE
FairSeq Roberta tutorial failed: Failed to connect to client mesh master

### ISSUE THREAD

**Issue by DURA18** [pytorch/xla#3220]
## ❓ Questions and Help

Hi there, 

I am trying to learn and run the tutorial 
[Pre-training FairSeq RoBERTa on Cloud TPU using PyTorch](https://cloud.google.com/tpu/docs/tutorials/roberta-pytorch)

However, I got the following errors：

```
Failed to connect to client mesh master: roberta-tutorial.us-central1-a.c.deep-bert.internal:41205
Traceback (most recent call last):
  File "/usr/share/torch-xla-1.10/tpu-examples/deps/fairseq/train.py", line 719, in <module>
    cli_main()
  File "/usr/share/torch-xla-1.10/tpu-examples/deps/fairseq/train.py", line 709, in cli_main
    xmp.spawn(_mp_fn, args=(args,), nprocs=args.num_cores)
  File "/anaconda3/envs/torch-xla-1.10/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 394, in spawn
    start_method=start_method)
  File "/anaconda3/envs/torch-xla-1.10/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/anaconda3/envs/torch-xla-1.10/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 144, in join
    exit_code=exitcode
torch.multiprocessing.spawn.ProcessExitedException: process 4 terminated with exit code 1
```

Could you please help me with this Error?

**Comment by yeounoh** [comment]
Hi @DURA18, I was just able to run the model training following the tutorial instructions on my end. Let's confirm that we have the right setup in place. First stop, could we confirm that we have the correct TPU_IP_ADDRESS (of TPU VM) setup on your Compute VM:

https://cloud.google.com/tpu/docs/tutorials/roberta-pytorch#create_and_configure_the_pytorch_environment

You can find the TPU VM IP address from the cloud console: "It is the internal IP address displayed on the Google Cloud Console, under Compute Engine > TPUs."

**Comment by DURA18** [comment]
Hi @yeounoh, thanks so much for your quick reply and your answer really solved my problem. Would you mind also explaining a bit about the  --input_shapes parameter in the tutorial. I saw there are three groups of input shapes in the tutorial as  
'''
--input_shapes 16x512 18x480 21x384
'''
 I wonder what the batch size of the training model is in this case?

**Comment by jysohn23** [comment]
The `input_shape` argument is a list of `batchsize` x `seqlen` pairs. For longer sequences we use smaller batch sizes, but for sequences with less number of tokens we can afford to increase our batch size since it still fits into HBM. So this way for shorter sequences we end up padding less and wasting less compute and memory at the cost of more initial compilation.

**Comment by yeounoh** [comment]
Thank you @jysohn23 . I am glad to hear that the issue was resolved @DURA18 , I will close the issue for now :)

**Comment by DURA18** [comment]
@yeounoh @jysohn23 Thanks so much for your help
