### ISSUE TITLE
Nightly build test backward compatibility issue with syncfree

### ISSUE THREAD

**Issue by yeounoh** [pytorch/xla#3224]
## 🐛 Bug

Some of nightly build (master) test cases break with latest stable releases (e.g., `r1.10`, `r.1.9`, etc.) with syncfree AMP package import.

## To Reproduce

1. Create a torch-xla VM (use `--image-family=torch-xla`)
2. Activate torch-xla-1.10 virtualenv: `conda activate torch-xla-1.10`
3. Checkout pytorch/xla git repo `master` branch
4. Run: `python test/test_train_mp_mnist_amp.py`

Error traceback:
```
raceback (most recent call last):
  File "test/test_train_mp_mnist_amp.py", line 40, in <module>
    from torch_xla.amp import autocast, GradScaler, syncfree
ImportError: cannot import name 'syncfree' from 'torch_xla.amp' (/anaconda3/envs/torch-xla-1.10/lib/python3.7/site-
packages/torch_xla/amp/__init__.py)
```

## Expected behavior

Nightly build should work with the latest stable release(s). In order to resolve this issue, we should:
- Testing the newly introduced syncfree SGD optimizer within its own test case.
- HOT-FIX/ implement a conditional import and/or syncfree test case if it's not available in the runtime.

**Comment by yeounoh** [comment]
Hi @ymwangg, thank you for the contribution #3145 . As I was investigating the backward compatibility issue here, I've noticed that the following test cases were expanded for different amp optimizer options:

- `test_train_mp_mnist_amp.py`
- `test_train_mp_imagenet.py`

and we have the following test cases as well:

- `test_syncfree_optimizers.py` (using mnist)
- `test_train_mp_mnist.py`

Normally, it would be leaner and more test target specific to:

- have an appropriate/ simple tests for a test target, like you do in `test_syncfree_optimizers.py`
- have a evaluation script wrapping around individual test cases for performance evaluation & comparison
- also, it would be better to have test cases as mutually exclusive as possible, without much overlap.

Going forward, this will become critical as we introduce more optimization options.

As a small step toward these and to fix the backward compatibility issue, I was thinking about reverting:

- `test_train_mp_imagenet.py`,

so it doesn't test different optimizer options; and we can keep:

- `test_syncfree_optimizers.py` (for syncfree specific tests)
- `test_train_mp_mnist_amp.py` (for testing different amp optimizer optinos); also possibly rename this to `test_amp_optimizers.py`

I would like to hear your thoughts as I will be reverting some changes you made to the test scripts. 

cc @JackCaoG

**Comment by ymwangg** [comment]
@yeounoh The optimizer optimization related changes made in `test_train_mp_imagenet.py` and `test_train_mp_mnist_amp.py` are mainly used to demonstrate the performance improvement. Feel free to revert them if necessary.
