### ISSUE TITLE
PyTorch/XLA test failure on PyTorch PR

### ISSUE THREAD

**Issue by wonjoolee95** [pytorch/xla#3225]
Issue for tracking PyTorch/XLA test failure on PyTorch PR -- https://github.com/pytorch/pytorch/pull/67796.

**Comment by wonjoolee95** [comment]
Steps to reproduce:
- Checkout the PR with GitHub CLI (or with `git`)
```
gh pr checkout 67796
```
- Build PyTorch 
```
python setup.py install
```
- Build PyTorch/XLA
```
cd xla/
python setup.py install
```
- Run PyTorch/XLA tests
```
test/run_tests.sh
```

**Comment by pmeier** [comment]
To give a little more context: the failure happens when trying to use `__and__`. It complains that this is only possible with boolean tensors, which seems fine. Problem is that the tensors in question are boolean tensors. They come from one of three sources:

- `.isnan()`
- `.isfinite()`
- `(a <= b)`

Thus, the error should be reproducible with something like

```python
>>> t = torch.tensor([False, True], device="xla")
>>> t & t
```

I don't have direct access to a TPU so I tried to reproduce in Colab, but failed to do so. Since Colab has 1.9 installed my guess is that this is a recent regression.

**Comment by wonjoolee95** [comment]
Just an update, I was able to reproduce the same error by following the steps in the first reply by checking out the PR and running tests with:
```
test/run_tests.sh
```

However, I was not able to reproduce the same error with commands (the code runs without failure):
```
>>> t = torch.tensor([False, True], device="xla")
>>> t & t
```

**Comment by pmeier** [comment]
> However, I was not able to reproduce the same error with commands

Hmm, in that case could you check if [`torch.isclose`](https://pytorch.org/docs/master/generated/torch.isclose) is working as expected? In the PR, I've re-implemented it from Python since it is a composite operator anyway, but the error remains the same.

```python
import torch


def isclose(
    actual: torch.Tensor, expected: torch.Tensor, *, rtol=1e-5, atol=1e-8, equal_nan=False
) -> torch.Tensor:
    matches = actual == expected
    if equal_nan:
        matches[actual.isnan() & expected.isnan()] = True

    if rtol == 0 and atol == 0:
        return matches

    abs_diff = torch.abs(actual - expected)
    tolerance = atol + rtol * torch.abs(expected)
    matches[abs_diff.isfinite() & (abs_diff <= tolerance)] = True

    return matches


t = torch.rand(5, 5)
assert torch.all(isclose(t, t))
```

**Comment by wonjoolee95** [comment]
Thanks for the update, @pmeier. The `torch.isclose` seems to be working as expected from my testing. Also tried reordering the test cases to check if there was some kind of bug in the compilation cache but still seeing the same error. Just for visibility, I've pasted the error that I'm receiving here -- https://gist.github.com/wonjoolee95/65bab9af0f3b90aeb34fbecb7de7d992.

**Comment by pmeier** [comment]
That is weird. Do you need anything from my side to help locating or fixing the error?

**Comment by JackCaoG** [comment]
```
  File "/usr/local/google/home/wonjoo/anaconda3/lib/python3.8/site-packages/torch/testing/_comparison.py", line 854, in _isclose_xla
    mask = a.to(torch.bool) & b.to(torch.bool)
RuntimeError: /usr/local/google/home/wonjoo/pytorch/xla/torch_xla/csrc/tensor_methods.cpp:304 : Check failed: xla::ShapeUtil::ElementIsIntegral(shape) || shape.element_type() == xla::PrimitiveType::PRED 
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	
	torch_xla::XLATensor::bitwise_and(torch_xla::XLATensor const&, torch_xla::XLATensor const&)
```

Hmm, you should try to print the `shape` to debug. Based on `a.to(torch.bool) & b.to(torch.bool)` both `a` and `b` should be `bool` which is a `PRED`.

**Comment by pmeier** [comment]
@wonjoolee95 Could you try to run only the offending test and see if it still fails?

```bash
# pip install pytest or conda install -c conda-forge pytest
pytest test/test_nn.py -rA -k "test_rnn_retain_variables and xla"
```

@JackCaoG When `torch.isclose` is called, all the other checks for `shape`, `device` and so on have already happened. So if there were a mismatching shape, we wouldn't even get to the point the error is happening. Still, could you explain what a `PRED` is?

**Comment by JackCaoG** [comment]
@pmeier `PRED` are pretty much just XLA version of `boolean`.

**Comment by wonjoolee95** [comment]
Just only ran that test `TestNNDeviceTypeXLA.test_rnn_retain_variables_xla_float64` and still seeing the same error. 

Also when I print the tensors `a.to(torch.bool)` and `b.to(torch.bool)`, I see the expected boolean tensors like below:
```
tensor([[[False, False, False, False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False, False, False, False]],
```

**Comment by wonjoolee95** [comment]
I've print the shape of tensors in both places:
- In `torch/testing/_comparison.py`, right before `mask = a.to(torch.bool) & b.to(torch.bool)`. 
```
shape: torch.bool
```
- In `xla/torch_xla/csrc/tensor_methods.cpp`, in the `bitwise_and` function. 
```
f64[5,6,10]{2,1,0}
f64[5,6,10]{2,1,0}
pred[300]{0}
pred[300]{0}
pred[300]{0}
pred[300]{0}
```
So there seems to be some place that incorrectly passes in float tensor `f64[5,6,10]{2,1,0}` to the `bitwise_and` function. Which seems a bit odd, because although the test failure's error message points this line of code (`mask = a.to(torch.bool) & b.to(torch.bool)`) to cause the failure, the dtype as this tensor as shown above seem to correctly be `torch.bool`.

**Comment by JackCaoG** [comment]
@wonjoolee95 What's the `f64[5,6,10]{2,1,0}`? Were you printing `input` and `other` of `bitwise_and`?

It seems like it is going through a reshape from `[5,6,10]` to `[300]`. Maybe you should find the corresponding tensor with shape `[5,6,10]`. It is possible that for some reason computation is delayed and error out in a later time. You can also dump the ir graph of `a` and `b` to check.

**Comment by wonjoolee95** [comment]
That is correct, I'm printing the `input` and `other` for `bitwise_and`. So according to the print statements, it show that there were a total of 3 calls in `bitwise_and` in XLA:
```
1st call:
- input: f64[5,6,10]{2,1,0}
- other: f64[5,6,10]{2,1,0}
2nd call: 
- input: pred[300]{0}
- other: pred[300]{0}
3rd call:
- input: pred[300]{0}
- other: pred[300]{0}
```

**Comment by JackCaoG** [comment]
@wonjoolee95 Can you dump the HLO? Where is the `f64[5,6,10]` coming from and why they are float?

**Comment by wonjoolee95** [comment]
@JackCaoG, thanks for the suggestion, will do. One thing, how do I dump the HLO graph? Never have tried it before 😅 

Do I set the flag `XLA_SAVE_HLO_FILE` while running the tests? I can follow-up offline tomorrow as well.

**Comment by pmeier** [comment]
Maybe this is an XLA thing that I'm not aware of, but shouldn't the error happen in the first call? How are we even getting to the second and third call?

**Comment by wonjoolee95** [comment]
The print statements may not be strictly in order, since it is possible that for some reason computation is delayed and error out in a later time. 

Also have printed the IR graph for `self` and `other` tensors, pasted here -- https://gist.github.com/wonjoolee95/7e38a4bb4aa822cecb9d1347b74b51ba.

**Comment by JackCaoG** [comment]
@pmeier I will work with wonjoo on this issue. How urgent is this pr? I don't want to block you for too long.

**Comment by wonjoolee95** [comment]
Thanks @JackCaoG for the investigation of the issue. 

It seems like the PyTorch/XLA's implementation of `isNan` seems to be the cause of the issue. The `isNan` doesn't cast tensors to boolean tensors correctly underneath the hood. To more simply reproduce the issue, we can do:
```
a = torch.randn(2, 2, device = "xla:0")
b = torch.randn(2, 2, device = "xla:0")
a_isnan = torch.isnan(a)
b_isnan = torch.isnan(b)
a_isnan & b_isnan # ERROR - Operator __and__ is only supported for integer or boolean type tensors, got: f32[2,2]{1,0}
```
As a fix, we'll need to update the PyTorch/XLA's implementation of `isNan` to do the proper casting to boolean tensors. I'll be working on the fix and have a PR out by tomorrow.

**Comment by pmeier** [comment]
> How urgent is this pr? I don't want to block you for too long.

Not urgent yet. I'm also waiting for input of other stakeholders.

**Comment by wonjoolee95** [comment]
Posted a draft PR but currently having some issues with building it locally (not related to this change but due to some other environment changes in my local desktop). Now trying to verify the fix in a VM.

**Comment by wonjoolee95** [comment]
The PR is now ready to be merged (currently just waiting for the CircleCI builds to finish). With the changes in the PR, confirmed that the tests are now passing:
```
(base) wonjoo@wonjoo:~/pytorch$ python test/test_nn.py TestNNDeviceTypeXLA.test_rnn_retain_variables_xla_float64
.
----------------------------------------------------------------------
Ran 1 test in 190.673s

OK

```
Also the following now succeeds:
```
a = torch.randn(2, 2, device = "xla:0")
b = torch.randn(2, 2, device = "xla:0")
a_isnan = torch.isnan(a)
b_isnan = torch.isnan(b)
a_isnan & b_isnan 
```

**Comment by wonjoolee95** [comment]
I've merged the PR above and closed the issue for now. Please feel free to re-open if the issue rises again, @pmeier. Thanks!
