### ISSUE TITLE
Do xla support this operation, like a.data = b. (a is cpu tensor, b is tpu tensor)

### ISSUE THREAD

**Issue by Shan19900305** [pytorch/xla#3226]
## ❓ Questions and Help
Do we have some way to do like this.
a = torch.randn(3,5)
b = torch.randn(3,5, device=xm.xla_device())
a.data = b
a.cpu()

**Comment by JackCaoG** [comment]
We currently does not support this use case. 

For some context, all xla_tesnor data is stored in the device. All XLA tensor will hold a handle(int64) that can be used to look up the actual data on the device. Therefore every time user attempt to access the `b.data`, it will trigger `xla::_to_cpu`. In that case if just want to copy the value you should just do 
```
a.data = b.cpu()
```

if you want `a` also on the TPU device, you should use `.to` or other deep copy method.

**Comment by Shan19900305** [comment]
Thank you very much, but i still confused about this. If XLATensorImpl is inherit from TensorImpl, how to do this feature. (if we support this func, TensorImpl need to cast to XLATensorImpl? )
XLATensorImpl* GetXlaTensorImpl(const at::Tensor& tensor) {
  return dynamic_cast<XLATensorImpl*>(tensor.unsafeGetTensorImpl());
}

**Comment by JackCaoG** [comment]
@bdhirsh might have a better idea

**Comment by bdhirsh** [comment]
@Shan19900305 I don't really follow your question. At the python level, `a.data = b.cpu()` will take `b` (an xla tensor)`, call `_to_cpu()` (in C++) on it to create a new cpu tensor, and set `a.data` to that new cpu tensor.

**Comment by Shan19900305** [comment]
@bdhirsh I mean python code like: a = torch.randn(3,5)
b = torch.randn(3,5, device=xm.xla_device())
a.data = b  // for gpu side, this will using set_data(c++) interface, and shallow-copy b tensorImpl metadate to a tensorImpl.
a.cpu() // this code line is verify set_data operator success.
