### ISSUE TITLE
xla_builder.Op.tuple returns f32 data type regardless of operand data type

### ISSUE THREAD

**Issue by awshaichen** [pytorch/xla#3230]
## 🐛 Bug

When building a function that returns a tuple of tensors with mixed data type using `xla_builder.Op.tuple`, it somehow unifies all data types to f32 regardless of the original operand data type.

## To Reproduce

Applying the following patch into `test/test_operations.py` and then `python test/test_operations.py --verbosity=2`. `op_fn` is supposed to return a tuple of f32 and bf16, but it actually returns a tuple of f32 and f32.

```
diff --git a/test/test_operations.py b/test/test_operations.py
index c95e7f05..d5f61258 100644
--- a/test/test_operations.py
+++ b/test/test_operations.py
@@ -469,6 +469,7 @@ class XlaTestCase(unittest.TestCase):
   def compareResults(self, results, xla_results, rel_err=1e-2, abs_err=1e-5):
     self.maybePrintGraph(xla_results)
     for at, xt in zip(results, xla_results):
+      self.assertEqual(xt.dtype, at.dtype)
       self.assertEqualRel(
           self.makeComparable(xt),
           self.makeComparable(at),
@@ -1927,6 +1928,19 @@ class TestOpBuilder(XlaTestCase):
             'transpose_a': False
         })
 
+  def test_mixed_dtype_tuple(self):
+
+    def op_fn(a):
+      return xb.Op.tuple((a, a.cast(xb.Type.BF16)))
+
+    def aten_fn(a):
+      return a, a.to(torch.bfloat16)
+
+    self.runOpBuilderTest(
+        'test_mixed_dtype_tuple', [torch.randn([2, 3])],
+        op_fn,
+        aten_fn=aten_fn)
+
 
 class MpDecoratorTest(XlaTestCase):
```

It fails with `AssertionError: torch.float32 != torch.bfloat16`.

## Expected behavior

We expect `op_fn` to return a tuple with data types `(f32, bf16)`.

## Environment

 - Reproducible on XLA backend [CPU/TPU]: CPU
 - torch_xla version: 1.11 @ 5039e1064b145d1e0be6079f03d796705fcc5ce3

## Additional context

n/a

**Comment by awshaichen** [comment]
PR: https://github.com/pytorch/xla/pull/3231

**Comment by JackCaoG** [comment]
PR is merged, close this bug
