### ISSUE TITLE
some ops don't work with autograd

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/xla#3247]
I'm working on improving the error messages in the external codegen, and came across some ops in `xla_native_functions.yaml` that don't work with autograd, all of them for the same reason: The op in core doesn't have a derivative formula (it's composite), but xla provides a lowering for it.

Example failure (with `torch.std`):
```
>>> dev1 = 'cpu'
>>> dev2 = xm.xla_device()
>>> a1 = torch.ones(2, device=dev1, requires_grad=True)
>>> a2 = torch.ones(2, device=dev2, requires_grad=True)
>>> b1 = a1.var()
>>> b2 = a2.var()

# backward works on cpu
>>> b1.backward() 

# but not on xla. Why? `var()` has no backward formula defined, and xla is directly overriding the decomposition.
>>> b2.backward() 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/hirsheybar/pytorch-xla-master-env/lib/python3.9/site-packages/torch/_tensor.py", line 352, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/scratch/hirsheybar/pytorch-xla-master-env/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
>>>
```

The problematic ops are:
```
- logical_and
- logical_not
- logical_or
- logical_xor
- _to_cpu
- cross
- ger
- index_add_
- qr
- std
- std.dim
- svd
- var
- var.dim
```

There are a few categories of fixes:

```
- logical_and
- logical_not
- logical_or
- logical_xor
```

The above ops aren't meant to work with autograd, and were improperly labeled in core. I have a fix here: https://github.com/pytorch/pytorch/pull/69169

- [ ] cross
- [ ] ger
- [ ] index_add_
- [ ] qr
- [ ] std
- [ ] std.dim
- [ ] svd
- [ ] var
- [ ] var.dim

The above ops all shouldn't be too hard to fix: They are all CompositeImplicitAutograd ops in core, and xla shouldn't have to override them directly:

`qr` calls into `linalg_qr`, so we should just lower this instead
`svd` calls into `_svd_helper`, so we should probably just lower this instead (although lowering private ops is not great :( )

`std`, `std.dim`, `var`, `var.dim`: I think these can all be deleted - they are composite, but they dispatch into `std.correction` and `var.correction`, respectively, which xla already provides lowerings for.

`index_add_` this will get fixed by https://github.com/pytorch/xla/pull/3209/files

`cross` eventually just calls into.. `reshape` and `operator*`, so I think we can get rid of it.

```
_to_cpu
```

`_to_cpu` is probably a bit special: it is a CompositeImplicitAutograd op in core, but xla has its own lowering for it as an optimization: instead of looping over each tensor individually and moving it to cpu one at a time, we can move them all to cpu together. I think our two options are:

(a) Get rid of this optimization and use the composite kernel. Maybe this optimization isn't as important when we're moving tensors to cpu?
(b) Fix the lowering: We'd need to write a custom autograd function and write a backward function for `_to_cpu()`, which would basically need to move all of the inputs back to xla. This would look pretty similar to what xla does for `max_pool2d` today.

**Comment by JackCaoG** [comment]
Thanks @bdhirsh, can we make these ops in a  check list format so we can all take some to work on when we have time 😄
