### ISSUE TITLE
Support specified fallback device

### ISSUE THREAD

**Issue by rnett** [pytorch/xla#3257]
## 🚀 Feature
According to the docs, any ops without lowerings will fallback to the CPU.  I would like to be able to create a XLA_GPU device that falls back to a non-XLA GPU device.  This will cause fallbacks to have significantly less performance impact compared to falling back all the way to CPU.

Ideally, rather than something GPU-specific, `xla_device` would just take a device to use as the fallback.

## Motivation

 This will cause fallbacks to have significantly less performance impact compared to falling back all the way to CPU.

## Pitch

See the feature description.

## Alternatives

Automatically fall back to the same type of device (i.e. XLA_GPU -> GPU) rather than making it configurable.

**Comment by JackCaoG** [comment]
We have thought about this, the main problem I am seeing is whether `XLA_GPU`(it is a XLA device) holds a lock to the actual GPU device which prevents pytorch uses native CUDA device. We have never run the experiment through.

**Comment by rnett** [comment]
I know I can have eager and jit (i.e. XLA) tensorflow code together on GPU, see [example](https://colab.research.google.com/gist/rnett/f476141d86f8a89c2bde0a7e09cd7e6e/jit_compile.ipynb).  I've never tried it in parallel, but I don't think the XLA device for tf-function is transient so I would expect it to work.
