### ISSUE TITLE
Implementing a runtime JIT compiler around this and/or lazy tensors

### ISSUE THREAD

**Issue by rnett** [pytorch/xla#3258]
I've been toying with the idea of writing a JVM-style runtime JIT compiler for tensor computation graphs that would compile (only) hot paths using XLA.  I've been looking through this repo and pytorch, trying to find what integration and extension points I should look at.  Implementing it directly into [here](https://github.com/pytorch/xla/blob/master/torch_xla/csrc/op_by_op_executor.cpp#L185) seems straightforward enough, but I'd like to make it more generic than that (supporting other compilers) and an add-on, not in-tree.  I stumbled across the lazy tensor work, which looks promising for this if I'm understanding it right (there's lots of links to https://github.com/pytorch/ltc/ which no longer exists).  So I have a few concrete questions:

1. Would creating a lazy backend that wraps a "compile" backend and a "interpret" backend be feasible?  Ideally the python API would be something like `jitCompileDevice(compile=xm.xla_device(), interpret=torch.device('cpu'))`
2. Where can I track the progress on getting lazy tensors merged into mainline pytorch?  The RFC?
3. Can you give any kind of timeline for that?  Just months vs years would be helpful.

**Comment by JackCaoG** [comment]
@wconstab should have better answers. Rule of thumbs is if you are trying to target PyTorch IR, you should implement an Lazy backend. If you are planning to add a XLA backend (take HLO as input instead of pytorch IR), you can extend pytorch/xla code.

**Comment by rnett** [comment]
> target PyTorch IR, you should implement an Lazy backend

Ok cool, this is definitely my target.  I don't have a good grasp on the status of the lazy backend, is the best place to look https://github.com/pytorch/pytorch/tree/lazy_tensor_staging?

**Comment by wconstab** [comment]
Yes, lazy_tensor_staging is our source of truth.  You'll notice that more and more of the core sources are moving to pytorch master branch under torch/csrc/lazy - our plan is to fully land this functionality over the next half.  Currently, it's partially landed and also partially working - it works for a number of models in torchbench (eval/train) but has issues with some.  We're prioritizing getting all the models running first, then optimizing trace overheads and expanding support for other backends.

**Comment by rnett** [comment]
👍 I asked on the forums and didn't get any response, so repeating it here: will ATen support lazy tensor or something similar?  Or just the python bindings?

**Comment by wconstab** [comment]
We're working on landing the stuff that's in lazy_tensor_staging into pytorch master now.  It's integrated deeply with ATen (the dispatcher).  The idea is to provide a native way to capture a graph lazily and export it to XLA or torchscript IR backends.

**Comment by rnett** [comment]
Excellent, that's what I hoped!  I just saw a lot of code under `torch/csrc` and not much in ATen and got worried I wouldn't be able to use it from the C++ bindings.

**Comment by wconstab** [comment]
oh, i see what you mean.  it is possible to use from c++ bindings.  You can see the examples from our lazy tensor unit test:
https://github.com/pytorch/pytorch/blob/lazy_tensor_staging/lazy_tensor_core/test/cpp/test_aten_ltc_ts_tensor.cpp#L9451


This test is part of the test_ptltc binary that gets built by default if you build lazy_tensor_core following the [QUICKSTART.md](https://github.com/pytorch/pytorch/blob/lazy_tensor_staging/lazy_tensor_core/QUICKSTART.md)
