### ISSUE TITLE
[TPU VM] std::bad_alloc if imported after importing tensorflow

### ISSUE THREAD

**Issue by TPFRL** [pytorch/xla#3264]
## ❓ Questions and Help
On TPU-VM (v2-alpha), 
I sometimes get std::bad_alloc when I import packages in particular order.

For example,
1. **tensorflow must be imported after torch_xla**
Failure case : importing tensorflow before importing torch_xla
![image](https://user-images.githubusercontent.com/8455454/147042074-d3a12f3b-d233-491a-8dec-6363fd215b38.png)
Success : 
![image](https://user-images.githubusercontent.com/8455454/147043164-833f9323-2337-46ff-b07e-176983b67e70.png)

2. **'torch_xla' is needed to be import at the very beginning, to safely import some components from transformers library**
Failure case : importing is_tensorboard_available from transformers
![image](https://user-images.githubusercontent.com/8455454/147043069-a813b01e-25a5-4e82-ac1c-d7e65fb5b28f.png)
Success : 
![image](https://user-images.githubusercontent.com/8455454/147043189-738e7864-3fba-498e-8722-878a08449844.png)

Could you explain me why this happens?

**Comment by JackCaoG** [comment]
We don't really support import `tf` and `pt/xla` in the same process since `pt/xla` also carry a version of `tensorflow` and there might be conflicts. If you find a way to get around it(with certain order) I would just stick with that for now.

**Comment by TPFRL** [comment]
Ah, thanks!
