### ISSUE TITLE
Support `sorted` flag in topk implementation

### ISSUE THREAD

**Issue by yeounoh** [pytorch/xla#3265]
## 🚀 Feature
We should support the `sorted` flag in [topk](https://github.com/pytorch/xla/blob/220e879c3308b8477a5fb0d635c0a2f87f67409d/torch_xla/csrc/xla_lower_util.h#L19)), as specified in PyTorch [topk](https://pytorch.org/docs/stable/generated/torch.topk.html).

## Additional context

We have deprecated the flag in #3246  as the current implementation always returns a [sorted result](https://github.com/pytorch/xla/blob/220e879c3308b8477a5fb0d635c0a2f87f67409d/torch_xla/csrc/xla_lower_util.cpp#L367).

**Comment by yeounoh** [comment]
Good first issue, based on an offline discussion with @JackCaoG

**Comment by JackCaoG** [comment]
@will-cromar

**Comment by will-cromar** [comment]
It looks like we are not the first people to get confused by the meaning of the `sorted` flag of `topk`. `sorted` doesn't indicate that the input array is sorted, it indicates that the output array is guaranteed to be sorted. However, while elements are returned in an undefined order when `sorted=False`, that output ordering may still be sorted.

These bugs explain the `sorted` flag:
- https://github.com/pytorch/pytorch/issues/3982
- https://github.com/pytorch/pytorch/issues/60300

For example, with PyTorch on CPU, the output is actually sorted when the number of array elements _n_ is much larger than _k_:

```
>>> torch.topk(torch.randn(100000, device=dev, generator=torch.manual_seed(0)), 10, sorted=False)
torch.return_types.topk(
values=tensor([4.5627, 4.4179, 4.3398, 4.2172, 4.1015, 3.9300, 3.7986, 3.7809, 3.7612,
        3.7506]),
indices=tensor([36885, 80921, 54507, 75488,   393,   337, 32437, 79078, 57786, 65348]))
```

This is determined by a heuristic here (i.e. use [std::partial_sort](https://en.cppreference.com/w/cpp/algorithm/partial_sort) if n >= k*64): https://github.com/pytorch/pytorch/blob/2821574eea6948d9c0e381ae7224a2a5809812bc/aten/src/ATen/native/SortingUtils.h#L119

We can get different outputs between CPU and XLA if n < k*64. For example:

```
# PyTorch CPU
>>> torch.randn(100, generator=torch.manual_seed(0)).topk(5, sorted=False)
torch.return_types.topk(
values=tensor([2.3022, 3.4105, 2.5672, 1.8530, 1.8197]),
indices=tensor([45, 59, 69, 23, 62]))
# PyTorch XLA
>>> torch.randn(100, generator=torch.manual_seed(0), device=dev).topk(5, sorted=False)
torch.return_types.topk(
values=tensor([3.4105, 2.5672, 2.3022, 1.8530, 1.8197], device='xla:1'),
indices=tensor([59, 69, 45, 23, 62], device='xla:1'))
```

When `sorted=False`, the ordering of the outputs is implementation-dependent, and the outputs are not guaranteed to be sorted any particular way. So the existing XLA implementation is actually consistent with the API. See this bug about inconsistent ordering between CPU and CUDA: https://github.com/pytorch/pytorch/issues/70234

We could potentially optimize this implementation when `sorted=False` by implementing something like `std::partial_sort` in XLA to have a better complexity on paper, but my sense is that creating many XLA ops might have so much overhead that it could be slower in practice.

@JackCaoG do you think it's worth it to optimize the `sorted=False` case?

**Comment by JackCaoG** [comment]
Thanks, I think we can drop this one for now
