### ISSUE TITLE
How to specify compute capability when building from soruce to support GPU?

### ISSUE THREAD

**Issue by yxd886** [pytorch/xla#3271]
Hello, when I finish building from soruce to support GPU, and run the test script test_train_mp_imagenet.py, a warning is shown:

TensorFlow was not built with CUDA kernel binaries compatible with compute capability 7.5. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.

I am wondering how to specify the compute capability when building xla ?

Thanks very much!

**Comment by yeounoh** [comment]
Have you tried setting `XLA_CUDA` flag?
```
XLA_CUDA=1 python setup.py install
```

**Comment by ymwangg** [comment]
Building with
```
XLA_CUDA=1 CXX_ABI=0 TF_CUDA_COMPUTE_CAPABILITIES="7.0,7,5" python setup.py install
```
works for me.

**Comment by yxd886** [comment]
> Have you tried setting `XLA_CUDA` flag?
> 
> ```
> XLA_CUDA=1 python setup.py install
> ```

Yes, I solved the problem by setting TF_CUDA_COMPUTE_CAPABILITIES="7.0,7,5".

**Comment by yxd886** [comment]
> Building with
> 
> ```
> XLA_CUDA=1 CXX_ABI=0 TF_CUDA_COMPUTE_CAPABILITIES="7.0,7.5" python setup.py install
> ```
> 
> works for me.

Thanks very much!

**Comment by yeounoh** [comment]
Thank you @yxd886 , glad it worked :)
