### ISSUE TITLE
Training Mnist with pt/xla prints warning message

### ISSUE THREAD

**Issue by JackCaoG** [pytorch/xla#3286]
## 🐛 Bug

Training Mnist with pt/xla prints warning message.

/usr/local/google/home/jackcao/anaconda3/envs/pytorch2/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py:138: UserWarning: An output with one or more elements was resized since it had shape [75264], which does not match the required output shape [96, 1, 28, 28].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  ../aten/src/ATen/native/Resize.cpp:24.)
  return torch.stack(batch, 0, out=out)

## To Reproduce
use pytorch and pytorch/xla nightly
```
python test/test_train_mp_mnist.py
```

## Expected behavior

no error message being printed

## Environment

 - Reproducible on XLA backend [CPU/TPU]:
 - torch_xla version: nightly

## Additional context

doesn't impact training now but this behavior will be deprecated. I am not sure if the error coming from the pt/xla code or pytorch code.

**Comment by yeounoh** [comment]
This was fixed in PyTorch [pr](https://github.com/pytorch/pytorch/pull/71065). Closing.
