### ISSUE TITLE
Should Parameters that are outputs of computation be aliased 

### ISSUE THREAD

**Issue by aws-rhsoln** [pytorch/xla#3290]
## 🐛 Bug
Parameters of an HLO module that live out of entry computation are not aliased with the outputs. In case of XLA_CPU, such HLO module would be modified by the CopyInsertion pass in tensorflow backend resulting in a copy instruction been added. This ends up allocating a new memory for the output tensor. 
## To Reproduce

Consider the example below:
```
device = xm.xla_device()

input1 = torch.zeros(10,).to(device)
out = input1.view(10,)
xm.mark_step()
```

This should generate the following HLO Module:
```
HloModule SyncTensorsGraph.3, input_output_alias={ {0}: (0, {}, may-alias) }

ENTRY %SyncTensorsGraph.3 (p0.1: f32[10]) -> (f32[10], f32[10]) {
  %p0.1 = f32[10]{0} parameter(0)
  ROOT %tuple.2 = (f32[10]{0}, f32[10]{0}) tuple(f32[10]{0} %p0.1, f32[10]{0} %p0.1)
}
```

The [CopyInsertion pass in CPUCompiler](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/service/cpu/cpu_compiler.cc#L550) adds a copy instruction resulting in the following HLO:
```
HloModule SyncTensorsGraph.3, input_output_alias={ {0}: (0, {}, may-alias) }

 ENTRY %SyncTensorsGraph.3 (p0.1: f32[10,1]) -> (f32[10,1], f32[10,1]) {
   %p0.1 = f32[10,1]{1,0} parameter(0)
   %copy.2 = f32[10,1]{1,0} copy(f32[10,1]{1,0} %p0.1)
   ROOT %tuple.1 = (f32[10,1]{1,0}, f32[10,1]{1,0}) tuple(f32[10,1]{1,0} %p0.1, f32[10,1]{1,0} %copy.2)
 }
```
This would result in a new memory that gets allocated for the output (which is a view in this case).

**Note:** Without the CopyInsertion Pass in CPU Compiler, there would be a segfault when the output is deleted and we attempt to use the input1 tensor. Consider the example below:
```
device = xm.xla_device()

input1 = torch.zeros(10,).to(device)
out = input1.view(10,)
xm.mark_step()
out = torch.zeros(1).to(device)
x= out*2
xm.mark_step()
sum_out = input1*2
xm.mark_step()
```

Without the CopyInsertion pass, at first mark_step() out and input1 would share the memory. At second mark_step, the previous out memory is deallocated (thereby deallocating the memory for input1) and a new memory is allocated for out. Now an attempt to use input1 at third mark_step() would result in a seg-fault. 

## Environment

 - Reproducible on XLA backend [CPU/TPU]: CPU
 - torch_xla version: 1.10.0

**Comment by JackCaoG** [comment]
Thanks for reporting. This is a known behavior that `view tensor` will drop its relationship with the base tensor after a `mark_step`. `out` tensor has its own storage is an expected behavior and will prevent segfault( and stop acting as a view ). 

Note that we didn't intend to use `alias` to implement the pytorch `view`. You can check the comment at https://github.com/pytorch/xla/pull/3018. This part of the code will later be upstreamed to the pytorch core.

**Comment by aws-rhsoln** [comment]
So `out` tensor is expected to have its own storage in case of all view operations?

**Comment by JackCaoG** [comment]
yes, we will try to track view relationships between different tensors and update all of them to act as if they share the same underlying storage.. until a `mark_step` materized the tensor and break our view relationship tracking.
