### ISSUE TITLE
View tensors not respecting the definitions

### ISSUE THREAD

**Issue by aws-rhsoln** [pytorch/xla#3291]
## 🐛 Bug
According to pytorch documentation, any changes made to view tensors should be reflected in the input tensor (whose view is been created). This property is not respected if we have a mark_step after view and make the changes to the view after the mark_step. 
Another property that view has: the view and the input tensor share the same storage. It looks to me from the TF logs (turn TF_CPP_MAX_VLOG_LEVEL=3) that this property is not respected. I see that an output memory is allocated at this line: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/service/cpu/cpu_executable.cc#L126

## To Reproduce

Consider the example below:
```
import os
import torch
import torch_xla
import torch_xla.core.xla_model as xm

os.environ['XRT_DEVICE_MAP'] = "CPU:0;/job:localservice/replica:0/task:0/device:XLA_CPU:0"
os.environ['XRT_WORKERS'] = "localservice:0;grpc://localhost:40506"

device = xm.xla_device()

input1 = torch.zeros(1, 10).to(device)

out = input1.view(10,1)
xm.mark_step()
out[0][0] = 1
print(out.to('cpu'))
print(input1.to('cpu'))
```
output from above:
```
tensor([[1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
```

## Expected behavior

In torch:
```
input1 = torch.zeros(1, 10)
out = input1.view(10,1)
out[0][0] = 1
print(out)
print(input1)
print("Data-ptr for out:", out.data_ptr())
print("Data-ptr for input:", input1.data_ptr())
```
Output:
```
tensor([[1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
Data-ptr for out: 426000768
Data-ptr for input: 426000768
```
## Environment

 - Reproducible on XLA backend [CPU/TPU]: CPU
 - torch_xla version: 1.10

**Comment by JackCaoG** [comment]
This is a known behavior, check my comment at https://github.com/pytorch/xla/issues/3290#issuecomment-1011502424. @bdhirsh is working on upstreaming the pt/xla view handling logic to pytorch core. We think that should solve this problem.

In the mean time, we tried to not touch the previous old tensor after a `mark_step` to avoid the computation incorrectness.

**Comment by aws-rhsoln** [comment]
But the users can have such behavior in their script (though a corner case) and might see discrepancies.

Is there a timeline, when the view handling logic will be upstreamed?
