### ISSUE TITLE
Error: torch_xla/csrc/convert_ops.cpp:83 : Unsupported XLA type 15

### ISSUE THREAD

**Issue by zhb0920** [pytorch/xla#3293]
## ❓ Questions and Help
跑到这里就报错
    mask_fft=torch.fft.fft2(mask_sigmoid)
RuntimeError: Error while lowering: f32[288,288]{1,0} xla::cast, type=f32, dtype=Float, stype=ComplexFloat
Error: torch_xla/csrc/convert_ops.cpp:83 : Unsupported XLA type 15

**Comment by JackCaoG** [comment]
Pytorch/XLA currently does not support convert a op from Complex64 to any other type. It seems like you want to convert a C64 to float, what;s the expected behavior?
