### ISSUE TITLE
Why is upsample not supported on GPU？

### ISSUE THREAD

**Issue by ZhongYFeng** [pytorch/xla#3295]
## ❓ Questions and Help
Why is the upsample operation not supported on GPU? This is because the workload is relatively large and has not been completed, or is it impossible to achieve?
```
at::Tensor XLANativeFunctions::upsample_nearest2d(
    const at::Tensor& input, c10::optional<at::IntArrayRef> output_size,
    c10::optional<at::ArrayRef<double>> scale_factors) {
  XLA_FN_COUNTER("xla::");
  XLATensor input_tensor = bridge::GetXlaTensor(input);
  // Only the XLA TPU backend for now implements the CustomCall required by our
  // XLA lowering.
  if (input_tensor.GetDevice().hw_type != DeviceType::TPU) {
    return at::native::call_fallback_fn<&xla_cpu_fallback,
                                        ATEN_OP2(upsample_nearest2d,
                                                 vec)>::call(input, output_size,
                                                             scale_factors);
  }
  absl::Span<const xla::int64_t> input_dims =
      input_tensor.shape().get().dimensions();
  return bridge::AtenFromXlaTensor(XLATensor::upsample_nearest2d(
      input_tensor,
      GetOutputSizeWithScale(input_dims, scale_factors, output_size)));
}
```
If I want to implement upsample on GPU, what do I need to do?

**Comment by JackCaoG** [comment]
Sorry, I missed this one.. It used to be case that our XLA:GPU backend does not support this custom call, I am not sure if it is still the case. Do you still need this feature?

**Comment by ZhongYFeng** [comment]
> 



> Sorry, I missed this one.. It used to be case that our XLA:GPU backend does not support this custom call, I am not sure if it is still the case. Do you still need this feature?

Really hope the community can support this op. This op is too common, I found that many of my models gave up running with XAL because of this.

**Comment by JackCaoG** [comment]
Thanks, I will make a note about this.
