### ISSUE TITLE
better rendervous and less waste of memory and tpu

### ISSUE THREAD

**Issue by sipie800** [pytorch/xla#3296]
torch_xla use a map function to fork a program into each tpu core. The variable or anything are repeatly allocated in each process, which is not good at all. In most programs the thing need to be computed over processes is just very little. 
There is rendervous and is_master_ordinal can deal such things in weird ways. It's confusing and often cause bugs. And the worst thing is the spawn doesn't output error detail in the map function, even if it's a simple spelling error.
So may I suggest giving the map function away, come back to python-like things.

**Comment by JackCaoG** [comment]
I think this behavior(spawn up #core TPU process) will change after we migrate our runtime from XRT to a new run time. The current target date is end of June 2022.
