### ISSUE TITLE
RuntimeError: abs does not support automatic differentiation for outputs with complex dtype.

### ISSUE THREAD

**Issue by hackkhai** [pytorch/xla#3302]
## To Reproduce
import torch
import torch_xla
import torch_xla.core.xla_model as xm
device = xm.xla_device()
x1=torch.randn(2,2,2,2, dtype=torch.cfloat, requires_grad=True).to(device)
x1.abs()

1.Use colab TPU
2.Use the above code to reproduce the error

## Expected behavior

should support backpropogation for complex64 dtype normal pytorch 1.8 supports this

## Environment

 - Reproducible on XLA backend [CPU/TPU]:TPU
 - torch_xla version:1.9

**Comment by JackCaoG** [comment]
hmm.. something weird is going on. This error is thrown on the pytorch side, not the pytorch/xla side. However when convert the tensor to a cpu tensor, I did not see the same error. Will mark this bug and assign someone to take a look.
