### ISSUE TITLE
how to get relative commits of pytorch/pytorch and pytorch/xla ?

### ISSUE THREAD

**Issue by GipsonLeo** [pytorch/xla#3305]
## ❓ Questions and Help
For some reason, i need to install newest torch XLA from sources.  but i don't know the related pytorch/pytorch newest source.  if the pytorch/pytorch and pytorch/xla is not compatible, xla will not work.  how i get a newest relative pair of pytorch/pytorch commit and pytorch/xla commit ?

For example, an old pair is as flow, but too old:
pytorch/pytorch - HEAD git hash is a95abc46
pytorch/xla - HEAD git hash is 9c2f91e

**Comment by JackCaoG** [comment]
we don't keep track of this kind of information on paper. What you could do is to find the pytorch commit on the same day. That usually just works. 

For example the pytorch/xla pr you mentioned above is Mar 17, 2021, find the pytorch commit that is same day should just work.

**Comment by GipsonLeo** [comment]
thanks a lot. i'll try it.

**Comment by JackCaoG** [comment]
I am going to close this issue for now, let me know if you need more help!
