### ISSUE TITLE
XLA in openmmlab， report Check failed: ShapeUtil::Equal(param_shape, buffer_shape)

### ISSUE THREAD

**Issue by wyhhyw123** [pytorch/xla#3307]
im using XLA to accelerate openmmlab, but get the error report [ Check failed: ShapeUtil::Equal(param_shape, buffer_shape) ], i checked the input image shape and input label shape for several foward steps and it always keep the same. What are the possible reasons for this error ?   Thanks

**Comment by wyhhyw123** [comment]
it could run dozens of  forward steps normally, but got breakdown suddenly

**Comment by JackCaoG** [comment]
can you post a small repo and full error log?

**Comment by AkideLiu** [comment]
> im using XLA to accelerate openmmlab, but get the error report [ Check failed: ShapeUtil::Equal(param_shape, buffer_shape) ], i checked the input image shape and input label shape for several foward steps and it always keep the same. What are the possible reasons for this error ? Thanks

Hi, could you please share some ideas or code on how to run mmlab on TPU ?
