### ISSUE TITLE
Calling torch.cuda.is_available() with multiprocessing exhausts memory.

### ISSUE THREAD

**Issue by ymwangg** [pytorch/xla#3347]
## 🐛 Bug

We saw calling `torch.cuda.is_available` or `torch.cuda.device_count` globally or within data classes will exhaust GPU memory when training fairseq or transformers models using multi-GPUs.

## To Reproduce
```python
import torch_xla.distributed.xla_multiprocessing as xmp
from dataclasses import dataclass
import torch
import time

# calling torch.cuda api globally
torch.cuda.is_available()
torch.cuda.device_count()

# or calling torch.cuda api inside dataclass
@dataclass
class Data:
  count = torch.cuda.device_count()

def _mp_fn(index):
  print("hello{}".format(index))
  time.sleep(10)

if __name__ == '__main__':
  xmp.spawn(_mp_fn)
```

If run the above code snippet using `GPU_NUM_DEVICES=8 python test.py` on a 8-GPU node, you can see there are a total of 8x8=64 processes launched by checking `nvidia-smi`.

## Expected behavior

There should be 8 processes launched instead of 64.

## Environment

 - Reproducible on XLA backend: GPU
 - torch_xla version: master

**Comment by JackCaoG** [comment]
Hmm I am guessing this has something to do with how XRT server handles GPU training. My hand is a bit tight right now given 1.11 release is coming. I will try to take a look sometime this week.

**Comment by miladm** [comment]
It should be because of how [`xla_multiprocessing`](https://github.com/pytorch/xla/blob/master/torch_xla/distributed/xla_multiprocessing.py#L364-L365) configures threads.

@ymwangg can you try this line in your script? Let me know how it goes please.

````
xmp.spawn(
      _mp_fn,
      nprocs=1,
      start_method='fork',
```

**Comment by ymwangg** [comment]
@miladm Thanks for the pointer. Using `xmp.spawn(_mp_fn, nprocs=8, start_method='fork')` did seem to solve the 8x8 processes issue in the above script with the following warning:
```
2022-02-10 00:20:13.061410: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NOT_INITIALIZED: initialization error
```
However, if adding some computations like:
```
def _mp_fn(index):
  print("hello{}".format(index))
  device = xm.xla_device()
  x = torch.rand(10).to(device)
  time.sleep(10)
```
You will get the following error with the `fork` method:
```
Exception in device=GPU:3: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:421 : Check failed: session->session()->Run(session_work->feed_inputs, session_work->outputs_handles, &outputs) == ::tensorflow::Status::OK() (INVALID_ARGUMENT: Cannot assign a device for operation XRTAllocateFromTensor: {{node XRTAllocateFromTensor}} was explicitly assigned to /job:localservice/replica:0/task:3/device:XLA_GPU:0 but available devices are [ /job:localservice/replica:0/task:0/device:CPU:0, /job:localservice/replica:0/task:0/device:XLA_CPU:0, /job:localservice/replica:0/task:1/device:CPU:0, /job:localservice/replica:0/task:1/device:XLA_CPU:0, /job:localservice/replica:0/task:2/device:CPU:0, /job:localservice/replica:0/task:2/device:XLA_CPU:0, /job:localservice/replica:0/task:3/device:CPU:0, /job:localservice/replica:0/task:3/device:XLA_CPU:0, /job:localservice/replica:0/task:4/device:CPU:0, /job:localservice/replica:0/task:4/device:XLA_CPU:0, /job:localservice/replica:0/task:5/device:CPU:0, /job:localservice/replica:0/task:5/device:XLA_CPU:0, /job:localservice/replica:0/task:6/device:CPU:0, /job:localservice/replica:0/task:6/device:XLA_CPU:0, /job:localservice/replica:0/task:7/device:CPU:0, /job:localservice/replica:0/task:7/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[XRTAllocateFromTensor]] vs. OK)
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	
	xla::util::MultiWait::Complete(std::function<void ()> const&)
	
	
	
	clone
*** End stack trace ***
```
The full output can be found [here](https://github.com/pytorch/xla/files/8037076/debug.txt).

**Comment by ymwangg** [comment]
After some investigation, I found the main reason is `CUDA_VISIBLE_DEVICES` is ignored by CUDA driver if `torch.cuda.is_available()` is called before setting `CUDA_VISIBLE_DEVICES` so that each process tries to initialize all GPUs.
Below is the minimum example:
```py
import torch
import os
import torch.multiprocessing.spawn as spawn

def func(i):
    #torch.cuda.is_available()
    os.environ['CUDA_VISIBLE_DEVICES'] = str(i)
    print("pid={} count={}".format(i,torch.cuda.device_count()))

if __name__ == '__main__':
    spawn(func,nprocs=2)
```
With `torch.cuda.is_available()`:
```sh
pid=1 count=8
pid=0 count=8
```
Without `torch.cuda.is_available()`:
```sh
pid=1 count=1
pid=0 count=1
```

**Comment by JackCaoG** [comment]
Thanks @ymwangg . This sounds like a bug or at least we should document this somewhere? I am assuming issue does not arise if we don't call `torch.cuda.device_count()` within the spawn function?

**Comment by ptrblck** [comment]
> I found the main reason is `CUDA_VISIBLE_DEVICES` is ignored by CUDA driver if `torch.cuda.is_available()` is called before setting `CUDA_VISIBLE_DEVICES` so that each process tries to initialize all GPUs.

This is expected behavior, as `CUDA_VISIBLE_DEVICES` has to be set before the first CUDA call.

**Comment by ymwangg** [comment]
@ptrblck Thanks for the quick response. @JackCaoG You are right, the issue does arise if we don't call functions like `torch.cuda.device_count()` that perform pytorch cuda initialization. List it as a known issue somewhere will be very helpful. I found this issue when training NLP models using transformers library or fairseq library on multiple GPUs. Maybe this issue can be fixed by moving `CUDA_VISIBLE_DEVICES` setter [here](https://github.com/pytorch/xla/blob/master/torch_xla/distributed/xla_multiprocessing.py#L224) to `__init__.py` or completely removing it.
