### ISSUE TITLE
[Questions] long bernoulli time usage

### ISSUE THREAD

**Issue by cicirori** [pytorch/xla#3352]
## ❓ Questions and Help
I'm using torch xla to train some transformer-like models, and I got the timeline using PyTorch profiler and saw something very strange.
code:
```
import argparse
import time
import torch
import os
import time
from datasets import load_from_disk
from datetime import datetime as dt
from transformers import AutoModelForSequenceClassification, AutoTokenizer, DataCollatorWithPadding


parser = argparse.ArgumentParser()
parser.add_argument('--xla_enabled', action='store_true')
parser.add_argument('--amp_enabled', action='store_true')
parser.add_argument('--pytorch_profile', action='store_true')
parser.add_argument('--syncfree_optimizer', action='store_true')
parser.add_argument('--xla_debug_metrics_enabled', action='store_true')
parser.add_argument('--profile_folder', type=str, default='./profile_folder')
parser.add_argument('--dataset_path', type=str, default='./sst_data/train')
parser.add_argument('--num_epochs', type=int, default=3)
parser.add_argument('--batch_size', type=int, default=11)
parser.add_argument('--max_seq_length', type=int, default=512)
parser.add_argument('--break_step_for_profiling', type=int, default=25)
parser.add_argument('--model_name', type=str, default='gpt2')
args = parser.parse_args()
print("Job running args: ", args)

if args.xla_enabled:
  import torch_xla.core.xla_model as xm


def get_autocast_and_scaler():
  if args.xla_enabled:
    from torch_xla.amp import autocast, GradScaler
    return autocast, GradScaler()

  from torch.cuda.amp import autocast, GradScaler
  return autocast, GradScaler()

def metsumm(step=None):
    rep = met.metrics_report().split('\n')
    # print(rep)
    out = []
    prefix = '\tSTEP {}: '.format(step) if step else ''
    for i, line in enumerate(rep):
        if 'ExecuteTime' in line or 'TransferToServerTime' in line:
            out.extend([line,rep[i+1], rep[i+2]])
    for i in range(3):
        x = '{}{}'.format(prefix, out[i])
        x = x + ' '*(45-len(x)) + out[i+3].split(':')[-1]
        print(x)
    print('')

def loop_with_amp(model, inputs, optimizer, autocast, scaler):
  with autocast():
    outputs = model(**inputs)
    loss = outputs["loss"]

  scaler.scale(loss).backward()
  scaler.step(optimizer)
  scaler.update()

  return loss, optimizer


def loop_without_amp(model, inputs, optimizer):
  outputs = model(**inputs)
  loss = outputs["loss"]
  loss.backward()
  optimizer.step()
  return loss, optimizer


def full_train_epoch(epoch, model, train_device_loader, device, optimizer, autocast, scaler, profiler=None):
  epoch_time = time.time()
  print('Epoch {}/{}'.format(epoch, args.num_epochs - 1), '\n', '-'*50)
  model.train()

  for step, inputs in enumerate(train_device_loader):
    iteration_time = time.time()

    if not args.xla_enabled:
      inputs.to(device)

    optimizer.zero_grad()

    if args.amp_enabled:
      loss, optimizer = loop_with_amp(model, inputs, optimizer, autocast, scaler)
    else:
      loss, optimizer = loop_without_amp(model, inputs, optimizer)

    if args.pytorch_profile and profiler:
      profiler.step()

    if step % 10 == 0:
      iteration_time_elapsed = time.time() - iteration_time
      print(f'[ {dt.now().strftime("%Y-%m-%d-%H:%M:%S.%f")} ] Iteration {step}\t complete in {iteration_time_elapsed // 60}m {iteration_time_elapsed % 60} s', flush=True)
    
    if args.pytorch_profile and (step + 1) == args.break_step_for_profiling:
      break
    if step == 100:
      break

  epoch_time_elapsed = time.time() - epoch_time
  print(f'Epoch complete in {epoch_time_elapsed // 60}m {epoch_time_elapsed % 60}s. Total steps: {step}', '\n', '-'*50)


def train_gpt2():
  model = AutoModelForSequenceClassification.from_pretrained(args.model_name)
  tokenizer = AutoTokenizer.from_pretrained(args.model_name)
  tokenizer.model_max_length = args.max_seq_length
  tokenizer.pad_token = tokenizer.eos_token
  model.config.pad_token_id = model.config.eos_token_id

  training_dataset = load_from_disk(args.dataset_path)
  collator = DataCollatorWithPadding(tokenizer)
  training_dataset = training_dataset.remove_columns(['text'])
  train_device_loader = torch.utils.data.DataLoader(
      training_dataset, batch_size=args.batch_size, collate_fn=collator, shuffle=True, num_workers=0)

  if args.xla_enabled:
    device = xm.xla_device()
  else:
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

  if args.xla_enabled:
    import torch_xla.distributed.parallel_loader as pl
    train_device_loader = pl.MpDeviceLoader(train_device_loader, device)
  lrlast = 1e-3
  model = model.to(device)

  if args.xla_enabled and args.amp_enabled and args.syncfree_optimizer:
    from torch_xla.amp import syncfree
    optimizer = syncfree.Adam(model.parameters(), lr=lrlast)
  else:
    optimizer = torch.optim.Adam(model.parameters(), lr=lrlast)

  autocast, scaler = None, None
  if args.amp_enabled:
    autocast, scaler = get_autocast_and_scaler()

  print('==> Starting Training')
  start_time = time.time()
  if args.pytorch_profile:
    with torch.profiler.profile(schedule=torch.profiler.schedule(wait=2, warmup=10, active=10,repeat=1), with_stack=False,
                                on_trace_ready=torch.profiler.tensorboard_trace_handler(args.profile_folder)) as prof:
      for epoch in range(args.num_epochs):
        full_train_epoch(epoch, model, train_device_loader, device, optimizer, autocast, scaler, profiler=prof)
  else:
    for epoch in range(args.num_epochs):
      full_train_epoch(epoch, model, train_device_loader, device, optimizer, autocast, scaler)

  total_epoch_time = time.time() - start_time
  print(f"Epoch Time(s) for {args.num_epochs} epochs = {total_epoch_time}")

  if args.xla_enabled and args.xla_debug_metrics_enabled:
    import torch_xla.debug.metrics as met
    print(met.metrics_report())


if __name__ == "__main__":
  if args.xla_enabled:
    torch.set_default_tensor_type("torch.FloatTensor")
  train_gpt2()
```

command:

```
GPU_NUM_DEVICES=1 \
CUDA_VISIBLE_DEVICES=0 \
       python   \
       train_sst_gpt2.py --batch_size=12 --xla_enabled --num_epochs 1  --pytorch_profile --profile_folder long_bernoulli
```

Looking at the timeline there are many bernoulli operators that take a long time and show an obvious synchronization behavior between the GPU execution, which I understand is not reasonable?
In this case the trace should be overlap with the execution, can anyone explain why this is happening or point to a general direction of investigation?

![image](https://user-images.githubusercontent.com/32845984/152956676-1a226503-8db9-4081-a825-5f7de2483e90.png)

The long time consumption of copy_from I think is another problem that can be solved by XLA_TENSOR_UPDATE_SYNC=false.

In addition, after commenting out dropout(bernoulli) in the model code, the index op will be stretched, and after commenting out the corresponding code, the div op will be stretched.
This phenomenon makes me wonder whether it is possible to achieve a perfect overlap between trace and execution on the GPU.

**Comment by JackCaoG** [comment]
hmm, weird. I didn't expect you to see `aten::` ops in the profiler. Did you see `CollectSyncTensors` section where we mark in https://github.com/pytorch/xla/blob/master/torch_xla/csrc/tensor.cpp? There are a couple places we mark certain function to make profiler to see it.

Could you also dump the metric of your run using
```
import torch_xla.debug.metrics as met; print(met.metrics_report())
```
after a couple steps?

I want to make sure this is not caused by the op fallback to the CPU.

**Comment by cicirori** [comment]
Thanks for your reply!

```
Metric: CompileTime
  TotalSamples: 3
  Accumulator: 02m45s231ms204.129us
  ValueRate: 02s533ms254.837us / second
  Rate: 0.043711 / second
  Percentiles: 1%=28s350ms202.937us; 5%=28s350ms202.937us; 10%=28s350ms202.937us; 20%=28s350ms202.937us; 50%=37s045ms250.298us; 80%=40s836ms750.894us; 90%=40s836ms750.894us; 95%=40s836ms750.894us; 99%=40s836ms750.894us
Metric: DeviceLockWait
  TotalSamples: 101
  Accumulator: 305.244us
  ValueRate: 002.127us / second
  Rate: 0.703838 / second
  Percentiles: 1%=002.448us; 5%=002.481us; 10%=002.517us; 20%=002.596us; 50%=002.692us; 80%=002.991us; 90%=003.092us; 95%=004.899us; 99%=009.380us
Metric: ExecuteTime
  TotalSamples: 100
  Accumulator: 33s272ms530.336us
  ValueRate: 325ms794.756us / second
  Rate: 0.976194 / second
  Percentiles: 1%=329ms424.127us; 5%=330ms518.305us; 10%=330ms560.427us; 20%=330ms772.896us; 50%=330ms110.831us; 80%=331ms547.473us; 90%=331ms213.873us; 95%=345ms899.272us; 99%=397ms704.525us
Metric: InputOutputAliasCount
  TotalSamples: 3
  Accumulator: 1794.00
  ValueRate: 22.39 / second
  Rate: 0.0374446 / second
  Percentiles: 1%=598.00; 5%=598.00; 10%=598.00; 20%=598.00; 50%=598.00; 80%=598.00; 90%=598.00; 95%=598.00; 99%=598.00
Metric: IrValueTensorToXlaData
  TotalSamples: 101
  Accumulator: 20s187ms296.564us
  ValueRate: 141ms352.687us / second
  Rate: 0.707208 / second
  Percentiles: 1%=462.636us; 5%=509.871us; 10%=528.181us; 20%=676.646us; 50%=273ms785.747us; 80%=297ms429.031us; 90%=310ms621.701us; 95%=311ms766.646us; 99%=313ms168.969us
Metric: OutboundData
  TotalSamples: 450
  Accumulator: 501.91MB
  ValueRate: 3.49MB / second
  Rate: 3.13 / second
  Percentiles: 1%=4.00B; 5%=4.00B; 10%=4.00B; 20%=4.00B; 50%=8.00B; 80%=96.00B; 90%=96.00B; 95%=576.38KB; 99%=576.38KB
Metric: ReleaseDataHandlesTime
  TotalSamples: 2032
  Accumulator: 02s604ms592.306us
  ValueRate: 034ms395.062us / second
  Rate: 55.1514 / second
  Percentiles: 1%=211.091us; 5%=242.676us; 10%=271.096us; 20%=311.018us; 50%=477.610us; 80%=857.481us; 90%=001ms169.842us; 95%=001ms480.548us; 99%=002ms795.915us
Metric: TensorsGraphSize
  TotalSamples: 100
  Accumulator: 866804.00
  ValueRate: 8456.01 / second
  Rate: 0.975539 / second
  Percentiles: 1%=8674.00; 5%=8674.00; 10%=8674.00; 20%=8674.00; 50%=8674.00; 80%=8674.00; 90%=8674.00; 95%=8674.00; 99%=8674.00
Metric: TransferToServerTime
  TotalSamples: 450
  Accumulator: 33s347ms679.008us
  ValueRate: 233ms317.002us / second
  Rate: 3.14852 / second
  Percentiles: 1%=371.840us; 5%=391.513us; 10%=413.526us; 20%=457.124us; 50%=686.936us; 80%=270ms769.924us; 90%=291ms906.507us; 95%=301ms311.155us; 99%=339ms523.182us
Metric: TransferToServerTransformTime
  TotalSamples: 450
  Accumulator: 254ms565.463us
  ValueRate: 002ms763.691us / second
  Rate: 3.13 / second
  Percentiles: 1%=044.314us; 5%=048.437us; 10%=051.159us; 20%=053.854us; 50%=061.618us; 80%=104.610us; 90%=121.929us; 95%=364.951us; 99%=456.457us
Counter: CachedCompile
  Value: 97
Counter: CreateCompileHandles
  Value: 3
Counter: CreateDataHandles
  Value: 60827
Counter: CreateXlaTensor
  Value: 436165
Counter: DestroyDataHandles
  Value: 60194
Counter: DestroyXlaTensor
  Value: 435517
Counter: DeviceDataCacheMiss
  Value: 220
Counter: MarkStep
  Value: 101
Counter: ReleaseDataHandles
  Value: 60194
Counter: SyncTensorsToData
  Value: 173
Counter: UncachedCompile
  Value: 3
Counter: XRTAllocateFromTensor_Empty
  Value: 210
Counter: XrtCompile_Empty
  Value: 128
Counter: XrtExecuteChained_Empty
  Value: 128
Counter: XrtExecute_Empty
  Value: 128
Counter: XrtMemoryInfo_Empty
  Value: 128
Counter: XrtRead_Empty
  Value: 128
Counter: XrtReleaseAllocationHandle_Empty
  Value: 128
Counter: XrtReleaseCompileHandle_Empty
  Value: 128
Counter: XrtSessionCount
  Value: 10
Counter: XrtSubTuple_Empty
  Value: 128
Counter: xla::_copy_from
  Value: 95469
Counter: xla::_index_put_impl_
  Value: 101
Counter: xla::_log_softmax
  Value: 101
Counter: xla::_log_softmax_backward_data
  Value: 101
Counter: xla::_s_where
  Value: 2424
Counter: xla::_softmax
  Value: 1212
Counter: xla::_softmax_backward_data
  Value: 1212
Counter: xla::_unsafe_view
  Value: 2525
Counter: xla::add
  Value: 56209
Counter: xla::addcdiv_
  Value: 15049
Counter: xla::addcmul
  Value: 17574
Counter: xla::addmm
  Value: 4848
Counter: xla::arange_out
  Value: 101
Counter: xla::bernoulli_
  Value: 3737
Counter: xla::bmm
  Value: 7272
Counter: xla::cat
  Value: 1212
Counter: xla::div
  Value: 21210
Counter: xla::embedding
  Value: 303
Counter: xla::embedding_dense_backward
  Value: 303
Counter: xla::empty
  Value: 7137
Counter: xla::expand
  Value: 8484
Counter: xla::fill_
  Value: 101
Counter: xla::index
  Value: 101
Counter: xla::index_put_
  Value: 101
Counter: xla::index_select
  Value: 303
Counter: xla::mm
  Value: 9999
Counter: xla::mul
  Value: 61105
Counter: xla::native_batch_norm
  Value: 2525
Counter: xla::native_batch_norm_backward
  Value: 2525
Counter: xla::ne
  Value: 101
Counter: xla::nll_loss_backward
  Value: 101
Counter: xla::nll_loss_forward
  Value: 101
Counter: xla::permute
  Value: 9696
Counter: xla::pow
  Value: 2424
Counter: xla::rsub
  Value: 101
Counter: xla::slice
  Value: 5050
Counter: xla::split
  Value: 1212
Counter: xla::sqrt
  Value: 15049
Counter: xla::sub
  Value: 101
Counter: xla::sum
  Value: 10100
Counter: xla::t
  Value: 10100
Counter: xla::tanh
  Value: 1212
Counter: xla::tanh_backward
  Value: 1212
Counter: xla::transpose
  Value: 7272
Counter: xla::unsqueeze
  Value: 303
Counter: xla::view
  Value: 70599
Counter: xla::zero_
  Value: 16511
Metric: XrtAllocateFromTensor
  TotalSamples: 1027
  Accumulator: 52s217ms530.429us
  Mean: 049ms915.447us
  StdDev: 147ms585.515us
  Rate: 7.1596 / second
  Percentiles: 25%=062.071us; 50%=116.023us; 80%=359.323us; 90%=070ms958.051us; 95%=461ms748.224us; 99%=709ms223.001us
Metric: XrtCompile
  TotalSamples: 3
  Accumulator: 02m45s1000ms516.899us
  Mean: 35s1000ms838.966us
  StdDev: 05s890ms990.117us
  Rate: 0.043711 / second
  Percentiles: 25%=28s274ms827.839us; 50%=37s971ms513.482us; 80%=40s755ms175.578us; 90%=40s755ms175.578us; 95%=40s755ms175.578us; 99%=40s755ms175.578us
Metric: XrtExecute
  TotalSamples: 100
  Accumulator: 33s052ms705.054us
  Mean: 331ms517.051us
  StdDev: 008ms395.984us
  Rate: 0.976194 / second
  Percentiles: 25%=329ms816.039us; 50%=329ms052.573us; 80%=329ms356.613us; 90%=330ms530.749us; 95%=330ms601.745us; 99%=383ms755.350us
Metric: XrtReleaseAllocation
  TotalSamples: 2032
  Accumulator: 549ms080.900us
  Mean: 295.875us
  StdDev: 487.890us
  Rate: 55.1515 / second
  Percentiles: 25%=022.112us; 50%=129.655us; 80%=503.601us; 90%=799.732us; 95%=001ms100.587us; 99%=001ms433.974us
```

And by adding the timing code, I'm currently sure it's the long elapsed time that occurs inside this function: https://github.com/pytorch/xla/blob/v1.10.0/torch_xla/csrc/aten_xla_type.cpp#L885

![image](https://user-images.githubusercontent.com/32845984/153135388-85c98316-7a65-4951-ba85-9eaa8c66a140.png)

**Comment by cicirori** [comment]
Some updates, I found that TensorToXlaData is taking a lot of time in the subsequent call stack of bernoulli_.
However this code path is not always triggered, it happens whenever devctx->seed_ir_value is false.
And devctx->seed_ir_value will only be set to false in MarkStep.
Does this seem to be the answer to the whole problem?
I'm still trying to figure out if this situation is expected and the exact conditions in which it happens.

![image](https://user-images.githubusercontent.com/32845984/153195551-c1067597-3ba8-43c3-bd03-3b629eb024ec.png)

Hope you can provide some help, thanks!

**Comment by JackCaoG** [comment]
Ahh ok, this is the seed sending issue. I have https://github.com/pytorch/xla/pull/3292 which will make random seed uploading async.... Do you want to try it out 😄 . I am trying to merge this pr but it is a large pr.

**Comment by cicirori** [comment]
I cherry picked this pr to our internally maintained branch based on torch_xla 1.10 with some syncfree optimizer commits.
I found that the bernoulli op is no longer stretched, but the single-step time has increased from 420ms to 600ms. The main time overhead should come from the tracing not being overlap, I wonder if this pr will slow down the tracing?
![image](https://user-images.githubusercontent.com/32845984/153365077-6d10b6f0-4cf1-469b-be0f-3c581d35cf22.png)

And the trace and execution overlap is still unsatisfactory, this time the stretched operator is index (with XLA_TENSOR_UPDATE_SYNC=false, otherwise it should be copy_from), a phenomenon that also existed in my previous investigation.

The stretch of index can be bypassed by modifying the model code by changing [this line](https://github.com/huggingface/transformers/blob/v4.16.2/src/transformers/models/gpt2/modeling_gpt2.py#L1413) `pooled_logits = logits[range(batch_size), sequence_lengths]`  to `pooled_logits = logits[0:12, -1 ]`.
I believe this change is logically equivalent in my case, and it's not clear why changing it this way would eliminate long index.
But after working around the long index, I also ran into  the div op being stretched....

**Comment by cicirori** [comment]
By the way, as I mentioned that we have an internal version of torch_xla, I made the following change when merging this pr, I don't know if it has any impact.

```
diff --git a/torch_xla/csrc/tensor_util.cpp b/torch_xla/csrc/tensor_util.cpp
index 74eb4d9f..b2b410af 100644
--- a/torch_xla/csrc/tensor_util.cpp
+++ b/torch_xla/csrc/tensor_util.cpp
@@ -19,7 +19,6 @@
 #include "tensorflow/core/lib/bfloat16/bfloat16.h"
 #include "torch_xla/csrc/helpers.h"
 #include "torch_xla/csrc/layout_manager.h"
-#include "torch_xla/csrc/torch_util.h"

 namespace torch_xla {
 namespace {
diff --git a/torch_xla/csrc/torch_util.h b/torch_xla/csrc/torch_util.h
index 853f9dc9..baf933ff 100644
--- a/torch_xla/csrc/torch_util.h
+++ b/torch_xla/csrc/torch_util.h
@@ -41,22 +41,22 @@ inline bool IsDefined(const c10::optional<at::Tensor>& tensor) {

 }  // namespace torch_xla

-namespace torch {
-namespace lazy {
-// Adapters that provide torch::lazy Hash functions for xla types
-torch::lazy::hash_t Hash(const xla::Shape& shape);
-
-template <typename T>
-torch::lazy::hash_t Hash(absl::Span<const T> values) {
-  return torch::lazy::ContainerHash(values);
-}
-
-// When specializing Hash(T) also specialize MHash(T, ...) since
-// torch::lazy::MHash template won't be aware of the Hash(T) here
-template <typename T, typename... Targs>
-hash_t MHash(absl::Span<const T> value, Targs... Fargs) {
-  return HashCombine(Hash(value), MHash(Fargs...));
-}
-
-}  // namespace lazy
-}  // namespace torch
+// namespace torch {
+// namespace lazy {
+// // Adapters that provide torch::lazy Hash functions for xla types
+// torch::lazy::hash_t Hash(const xla::Shape& shape);
+
+// template <typename T>
+// torch::lazy::hash_t Hash(absl::Span<const T> values) {
+//   return torch::lazy::ContainerHash(values);
+// }
+
+// // When specializing Hash(T) also specialize MHash(T, ...) since
+// // torch::lazy::MHash template won't be aware of the Hash(T) here
+// template <typename T, typename... Targs>
+// hash_t MHash(absl::Span<const T> value, Targs... Fargs) {
+//   return HashCombine(Hash(value), MHash(Fargs...));
+// }
+
+// }  // namespace lazy
+// }  // namespace torch
```

**Comment by JackCaoG** [comment]
@cicirori Can you dump the metric and check counter `HandleBarrierWait `, `TensorToData` and `TransferToServerTime`? Dump this between steps and see how they incremented.

In each step we need to upload a new rng seed to the server. Without the async pr this operation is synchronous hence it will block the tracing. What this pr does is creating a dummy Data and let the actual upload happens in the background. This will unblock the tracing... until someone actually wants to query the actual value of the RNG seed. I thought this query for the actual value of the random seed won't happen until we need to execute the graph but I might be missing sometime. `HandleBarrierWait` can tell you how long the foreground process hangs for the async upload to finish.


The ideal situation is that `async upload of rng seed` happens at the very beginning of the step and the seed will be ready when the graph execution is about to happen.

**Comment by cicirori** [comment]
And is there any call stack trace api provided in torch xla？This should be helpful for my debugging. Thanks！

**Comment by ymwangg** [comment]
@cicirori Interesting, I've been looking into the same issue recently. Did you see any improvements with @JackCaoG's async RNG seed PR #3292? Maybe I'm missing something but I couldn't see any improvements with this PR. I noticed the XLA RNG may have some room for improvements. Below is a throughput comparison between models with/without the dropout layer:

| model | master | master + async seed PR | pytorch | xla speedup |
| --------- | ------- | -------- | -------- | --------- |
| bert-base-uncased                  | 88.350 |  88.401  | 73.569 | 1.20 |
| bert-base-uncased (no dropout) | 106.504 | 106.697 | 79.652 | 1.33 |

The numbers are collected using a custom script [here](https://github.com/ymwangg/xla/blob/debug_g4dn/debug/bench.py) with the following commands:
```sh
GPU_NUM_DEVICES=1 python debug.py --amp --batch_size 24
```
The dropout layer is removed by applying this [patch](https://github.com/ymwangg/transformers/blob/profile_bert/patches/disable_dropout.patch) to the transformers library.

As you can see by removing the dropout layer, the speedup number using torch_xla increased from 1.20 to 1.33. I also tried the following patch that removes the RngUniform op from the xla graph and I got a throughput of 106.996, which is very similar to the number I got by removing dropout layer.
```diff
diff --git a/torch_xla/csrc/xla_lower_util.cpp b/torch_xla/csrc/xla_lower_util.cpp
index 0e222d76..69a67f95 100644
--- a/torch_xla/csrc/xla_lower_util.cpp
+++ b/torch_xla/csrc/xla_lower_util.cpp
@@ -469,8 +469,7 @@ xla::XlaOp BuildBernoulli(xla::XlaOp probability, xla::XlaOp seed,
       xla::Zero(probability.builder(), probability_shape.element_type());
   xla::XlaOp one =
       xla::One(probability.builder(), probability_shape.element_type());
-  xla::XlaOp noise = RngUniform(seed, probability_shape, zero, one);
-  return xla::ConvertElementType(xla::Lt(noise, probability), type);
+  return xla::ConvertElementType(seed, type) * one * probability;
 }
 
 xla::XlaOp BuildExponential(xla::XlaOp lambda, xla::XlaOp seed,
```
IIUC, if the RNG seed uploading is the real bottleneck, this change won't give such big improvement.

**Comment by cicirori** [comment]
@ymwangg 
In my test model, this pr didn't got speeded up e2e, instead the performance degraded.
But I am currently focusing on how to overlap trace and execution perfectly, so I am not too focused on e2e speed.

Also, I sent an email to your private email, please check it when you have time~

**Comment by JackCaoG** [comment]
Hmm OK. That pr was created to address a slightly different issue. We observed that in some workload, when the execution is really heavy, rng seed uploading can be blocked by the execution. In this case making the seed send async will improve the tracing time significally.

In the workload you guys are running it seems like transfer to server is not blocked, hence making it async won't help the speed too much. I saw `TensorToXlaData` in both config takes 25s. It is somewhat expected since there are small amount of cost we need to pay for making things async(copying data to a separate thread). Rng seed uploading is only one data so should be very cheap to being with.

That being said if rng seed sending is not the cause of the stretch I am wondering what could cause.

**Comment by JackCaoG** [comment]
I will circle back tmr..

**Comment by JackCaoG** [comment]
@cicirori Did you figure out why 
```
            denom = (exp_avg_sq.sqrt() / math.sqrt(bias_correction2)).add_(eps)
```

stretched? Looking at your metric, `HandleBarrierWait` is really short. This means that program is not blocked by the rng seed value inspection.

**Comment by cicirori** [comment]
@JackCaoG
Sorry, I've been busy with other internal things lately. I will continue to investigate this problem in the next few days and will continue to update this issue with any progress. Thank you for your previous help.

**Comment by cicirori** [comment]
@JackCaoG 
It's all about TensorToXlaData. I went through a few of the stretched ops (bernoulli_, index, add, addcdiv_, and I'm sure there are more, but I didn't go further) and found that the most timing cost function were always `TensorToData`.

So I changed the `transfer_async`'s default value of  `TensorToData` and `CreateTensorsData` to `true`. 

Something exciting happened, the GPU execution time ratio increased from ~66% to ~95%: 
![image](https://user-images.githubusercontent.com/32845984/155277738-0f741da3-bfd6-40fe-8552-b979e78f868d.png)

![image](https://user-images.githubusercontent.com/32845984/155277783-109612f6-3e35-4761-bb04-eca8caa22362.png)

and trace of step i+1  overlaps perfectly with the execution of step i:
![image](https://user-images.githubusercontent.com/32845984/155277950-103ec737-5071-445f-ab0c-d8f2088f79c1.png)

Although there still are gpu idle in each iteration, this is consistent with our previous internal analysis due to the overhead of computing graph hash and executing from the cache.

I think this part can be optimized as well, but the expected benefit may not be as high as solving the trace and the execution not being perfectly overlapped.

**Comment by cicirori** [comment]
I haven't read the implementation of transfer_async carefully yet, so I have two concerns now: 

1. is it safe to set its default value to true?
2. are `transfer_async=true` and `transfer_async=false` equivalent from an algorithm engineer's point of view (like model convergence)?

**Comment by JackCaoG** [comment]
Sorry I let this one slipped.. Will take a look tmr.

**Comment by JackCaoG** [comment]
I tested `transfer_async=true` by default and observe some minor slow down(~5%) on resnet50 on TPU, I am not sure if that slow down is real through.

If I understand correctly, sending the RNG seed aysnc slow down your training a bit, but sending all data async will give significant better overlap between tracing and execution? Is my understanding correct?


To your question
1. is it safe to set its default value to true?
From the program perspective it is safe. The main reason I did not do that is I did not spend enough time to benchmark all of the supported model to figure out the speed implication. If you can test some of the model that runs well on GPU with this env, it will give me more data points.

2. are transfer_async=true and transfer_async=false equivalent from an algorithm engineer's point of view (like model convergence)?
Yes. What `transfer_async` does is pretty much create a dummy data handle when user sending a data to the server and update the data handle to the real one when the transfer is completed. In this process transfer thread will hold the data handle lock to prevent accessing the invalid handle(if invalid handle is ever accessed program will crash and you will know).


Now for the next step I think we can do a couple things
1. Do more bench mark to show that `transfer_async=true` does not slow down any of the existing workload.
2. Better handle the parallel loader case

In Pytorch/XLA we have the parallel loader that load the data to server in a background process async. This is implemented in the [python level threading](https://github.com/pytorch/xla/blob/223ca031bd7ac92ea55107a9d79e73b035e6cdec/torch_xla/distributed/parallel_loader.py#L98)  and go through the same `TransferToServer` call. There is obviously no need to start another aysnc thread in C++ level in this case and it will only cause more context switch and slow things down.

**Comment by cicirori** [comment]
I didn't see obvious performance difference on running  resnet50 training with **fake data**

here is the overview generated by torch.profiler:
```
XLA_TRANSFER_SEED_ASYNC=1 
XLA_TRANSFER_ASYNC_GLOBLE=1
XLA_TENSOR_UPDATE_SYNC=false
```
![image](https://user-images.githubusercontent.com/32845984/156313080-f76c69a8-6125-4419-a102-2c1fa27f17e2.png)
```
XLA_TRANSFER_SEED_ASYNC=0
XLA_TRANSFER_ASYNC_GLOBLE=0
XLA_TENSOR_UPDATE_SYNC=true
```
![image](https://user-images.githubusercontent.com/32845984/156313101-921feb57-3e6d-4d7b-bc1f-d99e19bd5119.png)


It seems that async has a slight slowdown on training. But as far as I know, the torch profiler has a large impact on lazy tensor trace speed, so the quantitative metrics obtained are not always reliable. For example, I measured a 20% improvement on gpt2 above, and only 10% using nsys, which is close to the real gain.

Here is the result of running 1000 steps each for async and sync without any external profiling tool, and the difference becomes much smaller.

```
# async
| Training Device=xla:0/0 Epoch=1 Step=1000 Loss=0.00398 Rate=238.99 GlobalRate=346.54 Time=11:28:40
# sync
| Training Device=xla:0/0 Epoch=1 Step=1000 Loss=0.00398 Rate=237.74 GlobalRate=345.45 Time=11:35:18
```

**Comment by JackCaoG** [comment]
Hmm, I guess I can start with adding the env var to enable async upload for all datas (except the one from parallel loader) and leave it off for now. Then we can benchmark it a bit more and decide whether we want to change the default value. I will try to do that after the 1.11 release.

**Comment by aws-rhsoln** [comment]
> Hmm, I guess I can start with adding the env var to enable async upload for all datas (except the one from parallel loader) and leave it off for now. Then we can benchmark it a bit more and decide whether we want to change the default value. I will try to do that after the 1.11 release.

@JackCaoG any update on this? I saw an issue when using the optimizer from hugging face transformers repo. Here in this [optimizer.step](https://github.com/huggingface/transformers/blob/main/src/transformers/optimization.py#L369-L380) , the two lines [transfers a scalar to the server.](https://github.com/pytorch/xla/blob/master/torch_xla/csrc/tensor.cpp#L777) This TransferToServer ends up blocking the tracing.
