### ISSUE TITLE
XLA CompileTime too slow error, error said to post graph dump

### ISSUE THREAD

**Issue by reidsanders** [pytorch/xla#3354]
## ❓ Questions and Help
I am running Pytorch XLA using Pytorch lightning on a tpu vm v3-8. I got lots of errors repeating ~this:
> pt-xla-profiler TransferFromServerTime too frequent 104300 in 34742 steps
> CompileTime too slow: longest instance took 14m30s ... Please open a Github issue with the graph dump for our team to optimize. 

I enabled XLA_SAVE_TENSORS_FILE and XLA_METRICS_FILE and post them here: (XLA_SAVE_TENSORS_FILE is truncated because it was too large to upload here, and I understand multiple runs are appended. I can do a different
 file share if it is needed in full.)
[XLA_SAVE_TENSORS_FILE.txt](https://github.com/pytorch/xla/files/8029381/XLA_SAVE_TENSORS_FILE.txt)
[XLA_METRICS_FILE.txt](https://github.com/pytorch/xla/files/8029314/XLA_METRICS_FILE.txt)
[pipfreeze.txt](https://github.com/pytorch/xla/files/8029431/pipfreeze.txt)
If I am doing something wrong, or there is a known workaround for this I would much appreciate it. Thanks!

**Comment by JackCaoG** [comment]
Compilation is actually fine, it stays at `11` after step 10 and never incremented. 
```
[MetricsData; step=69]
Metric: CompileTime
  TotalSamples: 11
  Accumulator: 07m50s335ms265.522us
  ValueRate: 929ms773.712us / second
  Rate: 0.024898 / second
  Percentiles: 1%=011ms687.489us; 5%=011ms687.489us; 10%=011ms171.336us; 20%=033ms382.168us; 50%=16s474ms715.592us; 80%=01m24s231ms292.359us; 90%=01m28s217ms540.421us; 95%=01m29s392ms903.089us; 99%=01m29s392ms903.089us
```

`TransferFromServerTime` too frequent is usually an indication that you are trying to print something for every step. I was looking at your metric and I saw `TransferFromServer` incremented 4 types per step.

```
Metric: TransferFromServerTime
  TotalSamples: 200
  Accumulator: 339ms192.548us
  ValueRate: 576.263us / second
  Rate: 0.339785 / second
  Percentiles: 1%=702.155us; 5%=743.975us; 10%=779.699us; 20%=816.943us; 50%=983.600us; 80%=001ms206.432us; 90%=001ms392.081us; 95%=008ms192.180us; 99%=022ms369.799us
```

The total amount of time it taken is not significant through. If you want to optimize this you might want to find out where that `transferFromServer` coming from. 

Overall I think your model runs pretty efficiently, did you observe any speed issue?

**Comment by reidsanders** [comment]
Ah, thanks! Speed seems fine, but I assumed I had something hurting performance based on that message (I'm new to tpu training, and don't have a good idea of what speeds to expect). I appreciate your help!
