### ISSUE TITLE
Clean up CXX_ABI setup in pytorch/XLA

### ISSUE THREAD

**Issue by JackCaoG** [pytorch/xla#3390]
## 🚀 Feature
Test if we can remove
```
  if [ "$CXX_ABI" == "0" ]; then
    export CFLAGS="${CFLAGS} -D_GLIBCXX_USE_CXX11_ABI=0"
    export CXXFLAGS="${CXXFLAGS} -D_GLIBCXX_USE_CXX11_ABI=0"
  fi
```
in `scripts/build_torch_wheels.sh` since _GLIBCXX_USE_CXX11_ABI should be enough to control pytorch CXXABI setting. PyTorch/XLA should just read pytorch setting by import torch; print(int(torch._C._GLIBCXX_USE_CXX11_ABI)) in setup.py.

**Comment by JackCaoG** [comment]
More context in https://github.com/pytorch/xla/issues/3386

**Comment by yeounoh** [comment]
I can take a look, have a build environment setup to test already.
