### ISSUE TITLE
Inconsistent tensor.expand(...) behavior

### ISSUE THREAD

**Issue by ymwangg** [pytorch/xla#3394]
## 🐛 Bug

I recently found torch_xla has different behavior in `tensor.expand(..)` comparing to native torch. It looks like torch_xla performs real expansion using `xla::BroadcastInDim` while pytorch doc says "Expanding a tensor does not allocate new memory, but only creates a new view on the existing tensor".
## To Reproduce
```py
import torch
import torch_xla.core.xla_model as xm

device = xm.xla_device()
x = torch.tensor([[1], [2], [3]]).to(device)
y = x.expand(3, 4)
x[0] = 0
xm.mark_step()
print(y)
```
```sh
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]], device='xla:1')
```
```llvm
HloModule IrToHlo.6

ENTRY %IrToHlo.6 (p0.1: s64[3,1]) -> (s64[3,4]) {
  %p0.1 = s64[3,1]{1,0} parameter(0)
  %broadcast.2 = s64[3,1]{1,0} broadcast(s64[3,1]{1,0} %p0.1), dimensions={0,1}
  %reshape.3 = s64[3]{0} reshape(s64[3,1]{1,0} %broadcast.2)
  %broadcast.4 = s64[3,4]{1,0} broadcast(s64[3]{0} %reshape.3), dimensions={0}
  ROOT %tuple.5 = (s64[3,4]{1,0}) tuple(s64[3,4]{1,0} %broadcast.4)
}
```

## Expected behavior
```sh
tensor([[0, 0, 0, 0],
        [2, 2, 2, 2],
        [3, 3, 3, 3]], device='cuda:0')
```

**Comment by JackCaoG** [comment]
This goes back to how view is implemented in pytorch/xla. Short answer is that xla does not expose the memory space to the user hence there really isn't a way to achieve the same "multiple tensor pointing to the same storage" trick. We implement the view ops using functionization which pretty much just allocate a new tensor and keep track of them, update them together if we need to. You might want to read https://github.com/pytorch/xla/issues/3291 and issues linked there.

**Comment by ymwangg** [comment]
@JackCaoG  Thanks for the info. I found this op is inefficient when debugging the t5 model. It sounds like this is due to a limitation in xla and cannot be solved easily. I'll see if this op can be replaced by others.

**Comment by JackCaoG** [comment]
Thanks, if you find a work around that works well I would. love to learn about that 😄 .

**Comment by JackCaoG** [comment]
I will close this issue for now since there isn't much we can do right now, but please let us know if you find a work around that works well 😄 .
