### ISSUE TITLE
Incorrect lowering of torch.arange for 64-bit long

### ISSUE THREAD

**Issue by amithrm** [pytorch/xla#3399]
## 🐛 Bug

When torch.arange() is used to generate a sequence with long dtype, it maps to  constant({...})  i.e. '...' token. For 64-bit values, this generates garbage as indicated in: https://github.com/tensorflow/tensorflow/blob/5e1bc2d8f8a10cf28d36d593a322e7eb4ab11780/tensorflow/compiler/xla/service/hlo_parser.cc#L3576

## To Reproduce

1. torch.arange(start=0, end=2048, device=xm.xla_device()) is lowered to %constant.2760 = s64[2048]{0} constant({...}) in the HLO. 
2. For 32-bit values, this sequence is correctly implemented in the code (link above), but for 64-bit, it essentially concats pairs (32-bit each) leading to wrong results.

## Expected behavior

Should the torch.arange() instead be mapped to an iota operation in HLO and not constant({...}) ?
https://www.tensorflow.org/xla/operation_semantics#iota

**Comment by yeounoh** [comment]
Hi @amithrm , thanks for reporting the bug. We will take a look and circle back soon.

**Comment by JackCaoG** [comment]
Sorry I don't quite understand the issue here, we are lowering `arange` using the `xla::constant`, I didn't quite get `but for 64-bit, it essentially concats pairs (32-bit each) leading to wrong results`

I tried 
```
>>> t1 = torch.arange(start=42294967295, end=42294967350, device='xla:0')
>>> t1
tensor([42294967295, 42294967296, 42294967297, 42294967298, 42294967299,
        42294967300, 42294967301, 42294967302, 42294967303, 42294967304,
        42294967305, 42294967306, 42294967307, 42294967308, 42294967309,
        42294967310, 42294967311, 42294967312, 42294967313, 42294967314,
        42294967315, 42294967316, 42294967317, 42294967318, 42294967319,
        42294967320, 42294967321, 42294967322, 42294967323, 42294967324,
        42294967325, 42294967326, 42294967327, 42294967328, 42294967329,
        42294967330, 42294967331, 42294967332, 42294967333, 42294967334,
        42294967335, 42294967336, 42294967337, 42294967338, 42294967339,
        42294967340, 42294967341, 42294967342, 42294967343, 42294967344,
        42294967345, 42294967346, 42294967347, 42294967348, 42294967349],
       device='xla:0')
```

on `xla:cpu` and it seems correct to me. Could you provide a case that arange will provide incorrect result?

**Comment by JackCaoG** [comment]
@amithrm If you could provide a code snippet that fails for you that would be very helpful.

**Comment by amithrm** [comment]
Hi Jack,

Parsing this:
 HloModule SyncTensorsGraph.7

ENTRY %SyncTensorsGraph.7 () -> (s64[4]) {
  %constant.2760 = s64[4]{0} constant({...})
  ROOT %tuple.6 = (s64[4]) tuple(s64[4] %constant.2760)
}

gives us 4 integers 4294967296, 12884901890, 21474836484, 30064771078

Trying to get more repro cases

**Comment by amithrm** [comment]
An update on this issue..looks like we see this issue if we take the path of compilation via pbtxt files i.e. we dump the HLOs to a text format and then pick these up for the compilation. The parser that does this breaks while seeing the HLO module snippet posted earlier. Otherwise, using the standard path of protobuf for HLOs has no issues. 

We are doing more probing to see what the issue is with pbtxt files.

**Comment by JackCaoG** [comment]
right, Blake from the XLA team also mentioned that this is only an issue when you convert it the string format.

**Comment by amithrm** [comment]
correct..the string format is causing the parser to induce this behavior.

**Comment by JackCaoG** [comment]
Should we close this issue since you are no longer blocked?

**Comment by amithrm** [comment]
yes, we can close this.
