### ISSUE TITLE
xmp.spawn() stucks, never progress in TPU:0

### ISSUE THREAD

**Issue by pat266** [pytorch/xla#3445]
## 🐛 Bug

I have ran it 3 times now and experienced the same issue. The spawn() method would get stuck forever when the model is loading into each of the TPU cores.

This is where the error occurs: https://colab.research.google.com/drive/1Ur_vTUos18u4ze563Oj7wlm9BgrBZ8yR#scrollTo=H4WfXKVLu4NU

## To Reproduce

I know that my notebook is not very clear, so if there is any command line or system variables I can use to output the log to quickly help you would be best.

1. Run the Google Colab file from `question_generation` to `fine-tune`

- `question_generation`: https://colab.research.google.com/drive/1Ur_vTUos18u4ze563Oj7wlm9BgrBZ8yR#scrollTo=SWuIniIzU_So
- `fine-tune` (problem occurs here): https://colab.research.google.com/drive/1Ur_vTUos18u4ze563Oj7wlm9BgrBZ8yR#scrollTo=H4WfXKVLu4NU

This is just an error message caused by the KeyboardInterrupt, but as you can see, the spawn() method is stuck at loading `T5-base` for hours.
![image](https://user-images.githubusercontent.com/69089199/159948844-579c4e3f-4e1a-458d-8c22-f82623bacfcd.png)

## Expected behavior
I expected it to show me the iteration progress bar after waiting for 3 hours.

## Environment

 - Reproducible on XLA backend [CPU/TPU]: TPU
 - torch_xla version: Nightly (I followed the installation steps from 'T5 on TPU using Torch XLA - TPU Bar' tutorial (https://colab.research.google.com/github/trisongz/tpubar/blob/master/docs/T5_on_TPU_Torch_XLA_TPUBar.ipynb#scrollTo=coOmS2s_xDBy)

## Additional context

- I am using WandB to track the progress, but it never come up in the log that it has started, therefore I am assuming that the method gets stuck while loading the dataset.
- The code that I am using came from https://github.com/patil-suraj/question_generation. From what I see, the `run_qg.py` (which is the training file) is very similar to the tutorial code https://colab.research.google.com/github/patil-suraj/exploring-T5/blob/master/T5_on_TPU.ipynb#scrollTo=tty8vuMBqI5L

**Comment by JackCaoG** [comment]
Thanks for reporting. Can you rerun your training with environment variable
```
TF_CPP_MIN_LOG_LEVEL=0 TF_CPP_VMODULE=xrt_computation_client=5,computation_client=5,master=5,tensor=5
```
and see what's the output when it is stuck?

**Comment by pat266** [comment]
@JackCaoG Thank you for responding. I now think that the problem lies on WandB. Here are some of my observations that lead to the conclusion:

1. (First and Second run - signed in to WandB): The TPUMonitor outputs a healthy graph that shows that the TPU is being used. The reason why I thought that xmp.spawn() stucks was that there no progress bar for epoch and iteration (as shown in second point). [Here ](https://colab.research.google.com/drive/1L-5_mzqFXT-Qww51rDzZggm9lgMRA5rY#scrollTo=n7Lt78tsJFbe&uniqifier=2)is the link to the cell in Google Colab that runs with the WandB signed in. (Please ignore the KeyboardInterrupt Error)
![image](https://user-images.githubusercontent.com/69089199/160050954-85a3ca0f-6d66-42f0-b399-95d432b8692c.png)
![image](https://user-images.githubusercontent.com/69089199/160050983-77941c9a-0b8b-4f4b-a340-2bad14f97984.png)

2.  (Third run - not signed in to WandB): The TPUMonitor still output a healthy graph. Another difference is the progress bar for epoch and iteration 
![image](https://user-images.githubusercontent.com/69089199/160054007-35a371d2-4880-497a-9866-ebd4cd6a7e25.png)

I will close this issue for now, and will open it back if there are any errors in the future.
