### ISSUE TITLE
TPU v4 (Early Access) issues with PyTorch XLA (resources exhausted on larger models)

### ISSUE THREAD

**Issue by rwightman** [pytorch/xla#3460]
## 🐛 Bug

I'm running into issues with PT XLA 1.10 and current TPU v4-8 VM instances.

Most notably trying to run equivalent model + batch sizes that work on v3-8 TPU-VM fail to compile on v4-8 TPU with resource exhaustion or OOM errors.

In the Dec 21/Jan 22 time frame I had access to alpha TPU v4. I had it working quite well with PyTorch XLA. There were 4 logical devices (2 cores per, 'MegaCore' mode), so a model that worked on v3-8 would work on v4-8 with 2x the batch size and a nice boost in speed. Often the flexibilty of the combined HBM in MegaCore seemed to allow pushing even further in terms of batch size than I could on v3-8.

Now with 1.10 and the current v4-8 instances I'm failing to succesfully compile any larger models, even after reducing batch sizes to 1/4 of what they should be.

I can get a basic resnet50 baseline (same train code) running at acceptable speeds. But appears that there are now 8 logical devices like the v3-8s. Has MegaCore been disabled?

## To Reproduce

Create a fresh `v4-8` tpu-vm instance with `v2-alpha-tpuv4` version.

Install pytorch 1.10 as per:
```
sudo pip3 uninstall -y torch_xla torch torchvision
sudo pip3 install torch==1.10.0
sudo pip3 install torchvision==0.11.1
sudo pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch_xla-1.10-cp38-cp38-linux_x86_64.whl
sudo mv /usr/lib/libtpu.so /tmp
gsutil cp gs://tpu-pytorch/v4-libtpu-debug/libtpu.so .
sudo cp libtpu.so /lib/libtpu.so
```

Specific models with issues and command lines with an extra lib (timm) installed can be provided.

**Comment by JackCaoG** [comment]
@miladm Can you take this one? Thanks

**Comment by rwightman** [comment]
Some more info..

One of the models I've been focused on recently is a swin transformer v2 variant. `swin_v2_cr_small_224` in timm to be specific. I've been training one on a v3-8 w/ batch size 64. I had to step down to 16 to get it working on a v4-8. Otherwise lots of crashes like
```
2022-03-31 20:59:26.066558: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at tpu_execute_op.cc:266 : RESOURCE_EXHAUSTED: Fail to reserve 11069095936bytes for stack.                 
2022-03-31 20:59:26.105882: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at tpu_execute_op.cc:266 : RESOURCE_EXHAUSTED: Fail to reserve 11069095936bytes for stack.                 
2022-03-31 20:59:26.228236: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at tpu_execute_op.cc:266 : RESOURCE_EXHAUSTED: Fail to reserve 11069095936bytes for stack.
2022-03-31 20:59:26.638359: E tensorflow/compiler/xla/xla_client/xla_util.cc:88] StackTrace:
2022-03-31 20:59:26.638451: E tensorflow/compiler/xla/xla_client/xla_util.cc:88] *** Begin stack trace ***
2022-03-31 20:59:26.638456: E tensorflow/compiler/xla/xla_client/xla_util.cc:88]        tensorflow::CurrentStackTrace()
2022-03-31 20:59:26.638460: E tensorflow/compiler/xla/xla_client/xla_util.cc:88]        xla::util::ReportComputationError(tensorflow::Status const&, absl::lts_20210324::Span<xla::XlaComputation const* 
const>, absl::lts_20210324::Span<xla::Shape const* const>)
2022-03-31 20:59:26.638465: E tensorflow/compiler/xla/xla_client/xla_util.cc:88]        xla::util::ShapeHash(xla::Shape const&)
2022-03-31 20:59:26.638469: E tensorflow/compiler/xla/xla_client/xla_util.cc:88]        xla::XrtComputationClient::ExecuteComputation(xla::ComputationClient::Computation const&, absl::lts_20210324::Spa
n<std::shared_ptr<xla::ComputationClient::Data> const>, std::string const&, xla::ComputationClient::ExecuteComputationOptions const&)
2022-03-31 20:59:26.638474: E tensorflow/compiler/xla/xla_client/xla_util.cc:88] 
2022-03-31 20:59:26.638478: E tensorflow/compiler/xla/xla_client/xla_util.cc:88]        xla::util::MultiWait::Complete(std::function<void ()> const&)
```

**Comment by rwightman** [comment]
And regarding the devices, as I mentioned to @JackCaoG , when I'd used PyTorch with a v4 in alpha phase a few months back, I quicly realized there were 4 logical devices (2 cores per device). There were errors if I tried to use 8. But now using 8 seems to work, and is 2x as fast as forcing 4 with `export TPU_NUM_DEVICES=4` ... 

However, even more puzzling, when I install v4 compatible jax on one of the TPU-VM instances, it definitely reports 4 devices.

**Comment by rwightman** [comment]
I just figured out something re devices... on a new v4-8 instance I had installed jax + jaxlib w/ their libtpu to check `jax.device_count()`. I updated pytorch + xla to 1.10 and left the libtpu as is and now it's a 4-device setup (and errors out with a topology error on device id > 4 that I recall running into in the past), which does not happen with the lib tpu installed as per the first post in this issue...

**Comment by rwightman** [comment]
okee dokee, my `swin_v2_cr_small_224` just ran at batch size 128 (2x the v3-8) without a resource exhaustion error after the jax/jaxlib/libtpu pip install. 

```
sudo pip uninstall jax jaxlib libtpu-nightly libtpu libtpu_-tpuv4 -y
pip install jax[tpu] -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
```

It's still not exactly clear what's going on, none of this seems to touch the system lib folders (/lib, /usr/lib, etc), it changes a libtpu in the python site-packaages, perhaps that has priority over the system lib?

Now last bit, the throughput seems a bit lower (not awful, but not WOW) than I recall (on the resnet baseline), although possibly stil not using an optimal libtpu for pytorch xla + tpu v4....

**Comment by JackCaoG** [comment]
I think I missed few pieces when I build the custom libtpu to bypass the pod issue. I am running some experiments to see how to fix that.

**Comment by JackCaoG** [comment]
pip installed libtpu has higher priority than the `/lib` one

**Comment by JackCaoG** [comment]
Let me assign this to myself, this is related to another bug I am trying to fix for v4 pod. Hopefully the same solution also works for this bug.

**Comment by JackCaoG** [comment]
I think I made a mistake by not enabling the correct mega core config when compiling the 1.10 libtpu wheel. After I tweak it a bit I can observe that single "core" rate of running the resnet 50 example from ~750 to ~1200. I am suspecting this change will also fix the batch size issue.

I am finalizing some changes but should be able to update the libtpu for v4-pod with 1.10 soon.

**Comment by JackCaoG** [comment]
I updated the new wheel, close this bug for now
