### ISSUE TITLE
[LTC] Use upstream ScopePusher, ScopeContext and 

### ISSUE THREAD

**Issue by JackCaoG** [pytorch/xla#3527]
## 🚀 Feature
PyTorch/XLA should not maintain its own Scope related helper function since they have been upstream in https://github.com/pytorch/pytorch/blob/14affba79963c5f67700c5acf591d367a923d0b8/torch/csrc/lazy/core/ir_metadata.cpp#L43.

We should also add test if there isn't already one to make sure we don't introduce any regression.

## Motivation
Clean up the code

**Comment by wonjoolee95** [comment]
Complete with the PRs linked above, closing.
