### ISSUE TITLE
AtenXlaTensorTest.TestDropout fails on TPU

### ISSUE THREAD

**Issue by asuhan** [pytorch/xla#354]
`xla::RngUniform` returns all zeros if the seed is 0. We need to set the seed here: https://github.com/pytorch/xla/blob/master/third_party/xla_client/xrt_computation_client.cc#L511 and here: https://github.com/pytorch/xla/blob/master/third_party/xla_client/xrt_computation_client.cc#L540.

**Comment by dlibenzi** [comment]
That is fudged up!
Am I not getting Kokoro emails, or the thing stopped working?

**Comment by asuhan** [comment]
Kokoro looks green, so maybe it's not running on TPUs?

**Comment by dlibenzi** [comment]
> Kokoro looks green, so maybe it's not running on TPUs?

That would be bad :)

**Comment by dlibenzi** [comment]
Found the culprit talking to Daniel.
We are running on TPU, but run_tests.sh does not run (as well the the MNIST tensor test).
Filing a bug on Daniel to add ...

**Comment by dlibenzi** [comment]
It seems strange though that w/out setting the seed, RngUniform() keeps generating zeros.
That's not very uniform :)
I smell an issue somewhere ...

**Comment by asuhan** [comment]
There is an internal issue about this, this is the current behavior.

**Comment by dlibenzi** [comment]
Bad mojo :|
