### ISSUE TITLE
Host-side memory leak when moving an `nn.Module` object to TPU devices (and sharding it)

### ISSUE THREAD

**Issue by ronghanghu** [pytorch/xla#3545]
## 🐛 Bug

There seems to be a host-side memory leak when we move an `nn.Module` object to a TPU device via `module.to(device)`. Specifically, when constructing a `module` on the host CPU side and then moving it to a TPU device, one would expect that all the parameters in `module` should no longer occupy any host CPU memory after we call `module = module.to(device)` and `xm.mark_step()`, where `device = xm.xla_device()` is a TPU.

However, this turned out not to be the case based on our analysis. After calling `module = module.to(device)` and `xm.mark_step()`, it is still taking a large proportion of the CPU memory, which indicates a potential host-side memory leak after the CPU to TPU transfer.

Such memory leak happens frequently in our real use cases when we try to build large models on the CPU side (e.g. to initialize their parameters) and then transfer them to TPU devices. **It blocks the application of FSDP (#3431) to large models due to host-side OOM.**

I suspect it is probably because the XRT server did not release the CPU tensors in time after transferring them to TPUs. *Could it be that the XRT server trying to cache all the recently compiled graphs and unfortunately also happens to cache the data tensors in them?*

## To Reproduce

Below is a simplified example of our real use case that suffers from this host-side memory leak. It tries to construct 64 ViT blocks, move them to TPU, and take a shard of them.

If there isn't a memory leak, then the script below should take a constant CPU memory after constructing each block. However, we experience that its CPU memory consumption keeps growing after we build new module blocks, even though the previous blocks are already moved to TPU and we are explicitly calling `gc.collect()` after each step.

In our real use cases, this memory leak eventually leads to host-side OOM since we also need memory to store e.g. cached data.

---

To reproduce it:

1. Allocate a v3-8 TPU VM from `tpu-vm-pt-1.10` runtime and install `20220419` version of `torch`, `torchvision`, and `torch_xla`, while keeping `20220408` version of libtpu (due to https://github.com/pytorch/xla/issues/3502#issuecomment-1099777942, I haven't tried newer nightly builds yet). In addition, also install the `timm` package for vision transformers and the `psutil` package to show CPU memory usage as follows.
```
# torch, torchvision and torch_xla 20220419
sudo pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch-nightly+20220419-cp38-cp38-linux_x86_64.whl
sudo pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torchvision-nightly+20220419-cp38-cp38-linux_x86_64.whl
sudo pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch_xla-nightly+20220419-cp38-cp38-linux_x86_64.whl

# libtpu 20220408
sudo pip3 install https://storage.googleapis.com/cloud-tpu-tpuvm-artifacts/wheels/libtpu-nightly/libtpu_nightly-0.1.dev20220408-py3-none-any.whl

# dependencies for this example
sudo pip3 install timm==0.4.12
sudo pip3 install psutil
```

2. Save the following content to a python file (e.g. `/home/ronghanghu/oom_debug.py` below).
```
import argparse
import gc
import time

import torch
import torch_xla.core.xla_model as xm
import torch_xla.distributed.xla_multiprocessing as xmp

# install with `sudo pip3 install psutil timm==0.4.12`
import psutil
from timm.models.vision_transformer import Block


def build_sharded_vit_blocks(send_to_tpu):
    world_size = xm.xrt_world_size()
    rank = xm.get_ordinal()
    device = xm.xla_device() if send_to_tpu else torch.device("cpu")

    num_blocks = 64
    all_blocks = []
    for b_idx in range(num_blocks):
        # Create and shard a ViT block
        block = Block(dim=5120, num_heads=32, mlp_ratio=4.0, qkv_bias=True)
        block = block.to(device)
        block = create_module_shard(block, world_size, rank, device)
        all_blocks.append(block)

        gc.collect()
        xm.mark_step()
        xm.wait_device_ops()
        xm.rendezvous(f"built block {b_idx}")

        # check CPU and TPU memory usage
        cpu_mem_info = psutil.virtual_memory()
        cpu_mem_used_mb = cpu_mem_info.used / 1024 ** 2
        tpu_mem_info = xm.get_memory_info(xm.xla_device())
        tpu_mem_used_mb = (tpu_mem_info["kb_total"] - tpu_mem_info["kb_free"]) // 1024
        xm.master_print(
            f"after building block {b_idx}"
            f"\n\tCPU memory used: {cpu_mem_used_mb:.2f} MB"
            f"\n\tTPU memory used: {tpu_mem_used_mb:.2f} MB"
        )

    return all_blocks


def create_module_shard(module, world_size, rank, device):
    """
    Flatten module parameters into a single vector and shard it (to a slice)
    """
    # flatten parameters into a concatenated vector and pad it to world size
    p_flat = torch.cat([p.view(-1) for p in module.parameters()], dim=0)
    if p_flat.numel() % world_size != 0:
        padding = p_flat.new_zeros(world_size - p_flat.numel() % world_size)
        p_flat = torch.cat([p_flat, padding], dim=0)

    # shard the flattened parameter (i.e. taking a slice of it)
    begin = (p_flat.numel() // world_size) * rank
    end = (p_flat.numel() // world_size) * (rank + 1)
    p_shard = p_flat[begin:end].clone().detach()

    # free all the original model parameters and append the sharded param
    for p in module.parameters():
        p.data = torch.zeros(1, device=device)
    module.p_shard = torch.nn.Parameter(p_shard, requires_grad=True)
    return module


def _mp_fn(index, send_to_tpu):
    all_blocks = build_sharded_vit_blocks(send_to_tpu)
    xm.master_print("all blocks constructed")
    time.sleep(1000000)  # pause here so that we can inspect CPU memory via other tools


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--send_to_tpu", type=int, required=True)
    args = parser.parse_args()
    xmp.spawn(_mp_fn, args=(args.send_to_tpu,), nprocs=8)
```

3. Run this file on the v3-8 TPU VM:
```
python3 /home/ronghanghu/oom_debug.py --send_to_tpu 1
```
It prints
```
after building block 0                                      
        CPU memory used: 23103.51 MB                        
        TPU memory used: 2951.00 MB                         
after building block 1                                      
        CPU memory used: 26145.32 MB                        
        TPU memory used: 3101.00 MB                         
after building block 2                                      
        CPU memory used: 29756.12 MB                        
        TPU memory used: 3251.00 MB
...
after building block 61
        CPU memory used: 144820.79 MB
        TPU memory used: 12115.00 MB
after building block 62
        CPU memory used: 146509.26 MB
        TPU memory used: 12265.00 MB
after building block 63
        CPU memory used: 148226.47 MB
        TPU memory used: 12415.00 MB
all blocks constructed
```
which shows that the CPU memory consumption keeps growing when we construct more ViT blocks, despite that all the blocks are moved to TPU and shouldn't occupy any CPU memory. And below is a screenshot along with `htop` when running it on my v3-8 TPU VM.

<img width="1728" alt="Screen Shot 2022-04-29 at 9 42 28 PM (2)" src="https://user-images.githubusercontent.com/6997335/166091357-942cfcbd-1ac6-46a2-ace7-3a74e71a380d.png">

---

Also note that this memory leak is not due to the timm package itself. In particular, if we don't move the modules to TPU (i.e. keeping them in CPU), it actually uses *less* CPU memory than moving them to TPU, which shows indicates that the memory leak is beyond any CPU-side computation and likely comes from the PyTorch XLA graph tracing or the XRT server.

For example, if we run with ` --send_to_tpu 0` to keep everything on CPU:
```
python3 /home/ronghanghu/oom_debug.py --send_to_tpu 0
```
It prints
```
...
after building block 61
        CPU memory used: 81666.55 MB
        TPU memory used: 0.00 MB
after building block 62
        CPU memory used: 82880.04 MB
        TPU memory used: 0.00 MB
after building block 63
        CPU memory used: 84107.28 MB
        TPU memory used: 0.00 MB
all blocks constructed
```

## Expected behavior

After moving a module to TPU and calling `xm.mark_step`, it should no longer occupy any host-side memory.

## Environment

 - Reproducible on XLA backend [CPU/TPU]: v3-8 TPU VM
 - torch_xla version: 20220419 nightly from `tpu-vm-pt-1.10` (see Step 1 above)

## Additional context

This memory leak is the issue (2) mentioned in https://github.com/pytorch/xla/pull/3431#issuecomment-1112358933

This issue persists (and seems worse) after upgrading torch, torch_xla, and torchvision wheels to their nightly 20220430 versions and using them together with `libtpu-nightly==0.1.dev20220413` as follows:
```
# torch, torchvision and torch_xla 20220430
sudo pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch-nightly+20220430-cp38-cp38-linux_x86_64.whl
sudo pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torchvision-nightly+20220430-cp38-cp38-linux_x86_64.whl
sudo pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch_xla-nightly+20220430-cp38-cp38-linux_x86_64.whl

# libtpu 20220413
sudo pip3 install https://storage.googleapis.com/cloud-tpu-tpuvm-artifacts/wheels/libtpu-nightly/libtpu_nightly-0.1.dev20220413-py3-none-any.whl

# dependencies for this example
sudo pip3 install timm==0.4.12
sudo pip3 install psutil

python3 /home/ronghanghu/oom_debug.py --send_to_tpu 1
```
prints
```
...
after building block 61
        CPU memory used: 153795.23 MB
        TPU memory used: 12115.00 MB
after building block 62
        CPU memory used: 155552.81 MB
        TPU memory used: 12265.00 MB
after building block 63
        CPU memory used: 157576.84 MB
        TPU memory used: 12415.00 MB
all blocks constructed
```
which is even higher CPU memory consumption (148 GB => 157 GB) than in the 20220419 wheels.

<img width="1728" alt="Screen Shot 2022-04-30 at 3 11 55 PM (2)" src="https://user-images.githubusercontent.com/6997335/166124315-05613b81-42ab-450e-9e6c-fa30785b778a.png">

cc: @JackCaoG

**Comment by JackCaoG** [comment]
Thanks for reporting, issue seems to come from the xrt server side, I saw
![image](https://user-images.githubusercontent.com/59073027/166576163-9a2b54cb-c0ac-4164-b319-c2125e866b87.png)

when I run the server in a separate process. Let me look into it a bit more.

**Comment by JackCaoG** [comment]
couple observation
1. `block = block.to(device)` is the line that caused the server memory usage increase 
2. graph being executed in each step(block building) is the same
3. CPU memory consumed by xrt_server does not get reset when traning process exited


Here is the ir_graph being executed
```
IR {
  %0 = f32[5120]{0} xla::device_data(), location=convert@module.py:924, device=CPU:0, ROOT=0
  %1 = f32[5120]{0} xla::device_data(), location=convert@module.py:924, device=CPU:0, ROOT=1
  %2 = f32[15360,5120]{1,0} xla::device_data(), location=convert@module.py:924, device=CPU:0, ROOT=2
  %3 = f32[15360]{0} xla::device_data(), location=convert@module.py:924, device=CPU:0, ROOT=3
  %4 = f32[5120,5120]{1,0} xla::device_data(), location=convert@module.py:924, device=CPU:0, ROOT=4
  %5 = f32[5120]{0} xla::device_data(), location=convert@module.py:924, device=CPU:0, ROOT=5
  %6 = f32[5120]{0} xla::device_data(), location=convert@module.py:924, device=CPU:0, ROOT=6
  %7 = f32[5120]{0} xla::device_data(), location=convert@module.py:924, device=CPU:0, ROOT=7
  %8 = f32[20480,5120]{1,0} xla::device_data(), location=convert@module.py:924, device=CPU:0, ROOT=8
  %9 = f32[20480]{0} xla::device_data(), location=convert@module.py:924, device=CPU:0, ROOT=9
  %10 = f32[5120,20480]{1,0} xla::device_data(), location=convert@module.py:924, device=CPU:0, ROOT=10
  %11 = f32[5120]{0} xla::device_data(), location=convert@module.py:924, device=CPU:0, ROOT=11
}
```
it is pretty much just upload tensor(parameter) to the device, it is not a real execution.

looked at the metric
```
Metric: OutboundData
  TotalSamples: 12
  Accumulator: 1.17GB
  ValueRate: 352.89MB / second
  Rate: 3.52817 / second
  Percentiles: 1%=20.00KB; 5%=20.00KB; 10%=20.00KB; 20%=20.00KB; 50%=60.00KB; 80%=300.00MB; 90%=400.00MB; 95%=400.00MB; 99%=400.00MB
```

for every step we send around 1.2 gb of the data(parameter) to the server.

I commented out the `create_module_shard` and make `num_core` to 1 instead of 8. Here is what I see
```
after building block 0
        CPU memory used: 7825.69 MB
        TPU memory used: 1200.00 MB
after building block 1
        CPU memory used: 8324.89 MB
        TPU memory used: 2400.00 MB
after building block 2
        CPU memory used: 8311.04 MB
        TPU memory used: 3601.00 MB
after building block 3
        CPU memory used: 8329.66 MB
        TPU memory used: 4801.00 MB
after building block 4
        CPU memory used: 8331.41 MB
        TPU memory used: 6001.00 MB
after building block 5
        CPU memory used: 8332.93 MB
        TPU memory used: 7202.00 MB
after building block 6
        CPU memory used: 9142.98 MB
        TPU memory used: 7602.00 MB
after building block 7
        CPU memory used: 10537.95 MB
        TPU memory used: 7602.00 MB
after building block 8
        CPU memory used: 11637.03 MB
        TPU memory used: 7602.00 MB
after building block 9
        CPU memory used: 13124.90 MB
        TPU memory used: 7602.00 MB
after building block 10
        CPU memory used: 13942.70 MB
        TPU memory used: 7602.00 MB
after building block 11
        CPU memory used: 15464.15 MB
        TPU memory used: 7602.00 MB
```

interesting observation is that after block 6, TPU memory no longer increased, then the CPU memory started to increase significantly by each block. More interesting the amount of CPU memory increased every step is ~1gb which matches the tensor we need to allocate on Device.

Here is my theory, in order to build the block, we need to transfer massive parameter to the device. However device can't fit all of the parameter in the HBM at the same time(there is only 16gb of HBM per core). Instead XrtServer save some of the parameter in the CPU RAM and only transfer them into Device when needed. I need to verify this theory..

**Comment by JackCaoG** [comment]
Also, I was doing above test on a `v2-8`, so the HBM available is only 8GB. after block 5, it can no longer fit the parameter in  HBM which might be why it started to use host memory as a virtual memory.

**Comment by ronghanghu** [comment]
Thanks for the updates! It's interesting to see that the XRT server uses the CPU memory as its virtual memory (in the case where we commented out the `create_module_shard` and make `num_core` to 1 instead of 8) instead of raising an OOM error.

Earlier I thought that `xm.mark_step` would force all tensors to materialize on the TPU HBM but from the example above this seems not the case -- the parameters are actually still "lazy" tensors after `xm.mark_step` and only materialize when they are used. I wonder if there are any other cases beyond `xla::device_data()` where XLA tensors still could resize in the XRT server's virtual memory after mark-step?

**Comment by JackCaoG** [comment]
I can try with `create_module_shard` tmr with 8 core. To me materialize means we evaluate the computation and turn it to a concrete value. Device data is always materialized since the  value is known.  One thing you can try is to switch the order of 
```
        block = block.to(device)
        block = create_module_shard(block, world_size, rank, device)
```

This should avoid sending full parameter to each device, that might be the case of unexpected virtual memory usage.

**Comment by ronghanghu** [comment]
> To me materialize means we evaluate the computation and turn it to a concrete value. Device data is always materialized since the value is known.

Thanks, this sounds clear then

> One thing you can try is to switch the order of block = block.to(device)          block = create_module_shard(block, world_size, rank, device)

This could be hard to do, because in our real use cases `create_module_shard` may also involve collective ops such as `xm.all_reduce` or `xm.reduce_scatter` that cannot run on CPU tensors easily (the `create_module_shard` in the example above is a largely simplified version). While I can probably try figuring out a way to get around it, it would be great if we can keep the current order of first moving the module to XLA device before applying further sharing ops on it.

**Comment by JackCaoG** [comment]
hmm, I uninstall everything and run your script unmodified
```
sudo pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch-nightly+20220419-cp38-cp38-linux_x86_64.whl
sudo pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torchvision-nightly+20220419-cp38-cp38-linux_x86_64.whl
sudo pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch_xla-nightly+20220419-cp38-cp38-linux_x86_64.whl
sudo pip3 install https://storage.googleapis.com/cloud-tpu-tpuvm-artifacts/wheels/libtpu-nightly/libtpu_nightly-0.1.dev20220408-py3-none-any.whl
python test_oom.py --send_to_tpu 1
```

the memory usage on both CPU and TPU both seems reasonable to me. I was not able repro the memory leak you observed.
```
after building block 0
        CPU memory used: 28898.76 MB
        TPU memory used: 2951.00 MB
after building block 1
        CPU memory used: 30453.69 MB
        TPU memory used: 3101.00 MB
after building block 2
        CPU memory used: 34854.14 MB
        TPU memory used: 3251.00 MB
after building block 3
        CPU memory used: 35160.80 MB
        TPU memory used: 3401.00 MB
.....
after building block 61
        CPU memory used: 38763.07 MB
        TPU memory used: 12115.00 MB
after building block 62
        CPU memory used: 38675.91 MB
        TPU memory used: 12265.00 MB
after building block 63
        CPU memory used: 38677.39 MB
        TPU memory used: 12415.00 MB
```

I didn't start XRT server in a separate process too, so it should be identical to your experiment. Let me try it on couple other TPUVM i have.

**Comment by JackCaoG** [comment]
I switched to a `tpu-vm-pt-1.10`  TPUVM, now I am able to observe the issue you mentioned.. let me try to figure out what was the difference between 2 vms...

**Comment by JackCaoG** [comment]
Let me create a new v3-8 and try to repo again.

**Comment by ronghanghu** [comment]
Thanks for the further update! Also, as mentioned in the "Additional context" section above, the CPU memory consumption of this same script seems to get worse with the nightly 20220430 wheels with libtpu 20220413, so I guess  this could be related to XRT versions as well.

---

Starting from a v3-8 TPU VM with `tpu-vm-pt-1.10` runtime and do
```
# torch, torchvision and torch_xla 20220430
sudo pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch-nightly+20220430-cp38-cp38-linux_x86_64.whl
sudo pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torchvision-nightly+20220430-cp38-cp38-linux_x86_64.whl
sudo pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch_xla-nightly+20220430-cp38-cp38-linux_x86_64.whl

# libtpu 20220413
sudo pip3 install https://storage.googleapis.com/cloud-tpu-tpuvm-artifacts/wheels/libtpu-nightly/libtpu_nightly-0.1.dev20220413-py3-none-any.whl

# dependencies for this example
sudo pip3 install timm==0.4.12
sudo pip3 install psutil

python3 /home/ronghanghu/oom_debug.py --send_to_tpu 1
```
it prints
```
...
after building block 61
        CPU memory used: 153795.23 MB
        TPU memory used: 12115.00 MB
after building block 62
        CPU memory used: 155552.81 MB
        TPU memory used: 12265.00 MB
after building block 63
        CPU memory used: 157576.84 MB
        TPU memory used: 12415.00 MB
all blocks constructed
```

**Comment by JackCaoG** [comment]
This is weird, so I created a new v3-8 with `tpu-vm-pt-1.10` and I did
```
    1  yes | sudo pip3 uninstall torch
    2  yes | sudo pip3 uninstall torch_xla
    3  sudo pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch-nightly+20220430-cp38-cp38-linux_x86_64.whl
    4  sudo pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torchvision-nightly+20220430-cp38-cp38-linux_x86_64.whl
    5  sudo pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch_xla-nightly+20220430-cp38-cp38-linux_x86_64.whl
    6  sudo rm /usr/lib/libtpu.so 
    7  sudo pip3 install https://storage.googleapis.com/cloud-tpu-tpuvm-artifacts/wheels/libtpu-nightly/libtpu_nightly-0.1.dev20220413-py3-none-any.whl
    8  sudo pip3 install timm==0.4.12
    9  sudo pip3 install psutil
   10  gsuitl cp gs://tpu-pytorch/tmp/oom_debug.py .
   11  gsutil cp gs://tpu-pytorch/tmp/oom_debug.py .
   12  export XRT_TPU_CONFIG='localservice;0;localhost:51011'
   13  python oom_debug.py --send_to_tpu 1
   14  python3 oom_debug.py --send_to_tpu 1
```

but I am still unable to repro the memory leak above, I saw
```
after building block 60
        CPU memory used: 37236.03 MB
        TPU memory used: 11965.00 MB
after building block 61
        CPU memory used: 37225.59 MB
        TPU memory used: 12115.00 MB
after building block 62
        CPU memory used: 37272.94 MB
        TPU memory used: 12265.00 MB
after building block 63
        CPU memory used: 37250.36 MB
        TPU memory used: 12415.00 MB
```

I also verified that `torch` and `torch_xla` version is correct
```
python3
Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch, torch_xla
>>> torch.__version__
'1.12.0a0+git1f1d0b3'
>>> torch_xla.__version__
'1.12+9df591d'
```

@ronghanghu Do you mind creating a fresh vm and redo the step I posted above? Did I miss anything?

**Comment by ronghanghu** [comment]
Hmm, this is weird. Thanks for reporting it! I'll first check it again on my end

**Comment by ronghanghu** [comment]
OK, I figured out the issue here. It's because I didn't have `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4` in my environment variables. I was running `unset LD_PRELOAD` (as part of my `.bashrc`) as in https://cloud.google.com/tpu/docs/pytorch-xla-ug-tpu-vm to use the standard `malloc` on TPU VMs when running on v3-8, to get rid of some warnings like in the screenshot below.

![277197962_3134890303445191_498943550821934350_n](https://user-images.githubusercontent.com/6997335/166864787-f8bd0a86-1a99-4b2a-86de-ae55e2e17530.png)

In the TPU pod case, I also didn't pass in `--env LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4` to `torch_xla.distributed.xla_dist`, which is likely why it fails on my real (pod) use cases.

**If I run `export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4 && python3 oom_debug.py --send_to_tpu 1`, this memory leak doesn't happen.**

@JackCaoG If you have some time, could you try
```
unset LD_PRELOAD && python3 oom_debug.py --send_to_tpu 1
```
and see if you could reproduce the memory leak?

---

This seems to be a quite subtle difference. For a while, I thought (and was probably also told) that `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4` was no longer needed. It also doesn't appear in several docs, such as the "V4-Pod" section in the TPU v4 PyTorch/XLA instruction https://docs.google.com/document/d/1xzJNck0DZ0tlbsVT1nTgsxJg14Wu8F3P1ue5yBgrg0k/edit

If `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4` is indeed the key here, I guess we should remove the `unset LD_PRELOAD` instruction in https://cloud.google.com/tpu/docs/pytorch-xla-ug-tpu-vm and perhaps raise a warning in `torch_xla.distributed.xla_dist` to check whether this environment variable is set in TPU VM mode?

**Comment by JackCaoG** [comment]
Thanks, I will retry. I guess our doc is a bit confusing, `unset LD_PRELOAD` is only recommended for DLRM at the moment. For Resnet we see a significantly better speed using `tcmalloc`. On pod `tcmalloc` is also the default so you don't need to manually set the `LD_PRELOAD`.

**Comment by ronghanghu** [comment]
I verified that the host-side memory issue is resolved in all our cases via `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4`, one should keep using tcmalloc on TPU VMs instead of the standard C++ malloc.
