### ISSUE TITLE
Simple question to use TPU

### ISSUE THREAD

**Issue by Letmebelegend** [pytorch/xla#3599]
## ❓ Questions and Help
I've question that if I use colab TPUv2, and can make same model with pytorch(with xla for TPU)  and tensorflow, which way would be faster? Sure that tensorflow would be faster but how much it would be different normally?

Anyway, I appreciate all works on xla, incredible work

**Comment by Letmebelegend** [comment]
Appreciate you reply. I'm preparing transformer model and would try xla :D

**Comment by JackCaoG** [comment]
Thanks, I will close this issue for now. Feel free to open more specified issue when you running into problems :D.
