### ISSUE TITLE
DistributedDataParallel initialization hanging forever with XLA backend

### ISSUE THREAD

**Issue by will-cromar** [pytorch/xla#3625]
## 🐛 Bug

The call to DistributedDataParallel's constructor does not complete with a simple example model and the `xla` backend.

## To Reproduce

1. Patch this change to fix `TypeError: allgather() takes 3 positional arguments but 4 were given`

```
diff --git a/torch_xla/distributed/xla_backend.py b/torch_xla/distributed/xla_backend.py
index 6dbc7dc0..83e3e277 100644
--- a/torch_xla/distributed/xla_backend.py
+++ b/torch_xla/distributed/xla_backend.py
@@ -61,7 +61,7 @@ class ProcessGroupXla(ProcessGroup):
     xm.all_reduce(reduce_type, tensors, groups=self._mesh, pin_layout=False)
     return WorkXla(tensors)
 
-  def allgather(self, output_tensors_list, input_tensors):
+  def allgather(self, output_tensors_list, input_tensors, opts):
     for input_tensor, output_tensors in zip(input_tensors, output_tensors_list):
       result = xm.all_gather(input_tensor, groups=self._mesh, pin_layout=False)
       for i, slice in enumerate(torch.split(result, input_tensor.shape[0])):
```

2. Run this code snippet with some XLA device (CPU or TPU) to log all Python function calls during DDP initialization

```
import os
import sys
import torch
import torch.nn as nn
import torch.distributed as dist
from torch.nn.parallel import DistributedDataParallel as DDP

import torch_xla.distributed.xla_backend
import torch_xla.core.xla_model as xm


class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.net1 = nn.Linear(10, 10)
        self.relu = nn.ReLU()
        self.net2 = nn.Linear(10, 5)

    def forward(self, x):
        return self.net2(self.relu(self.net1(x)))


def demo_basic(rank, world_size):
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '12355'

    # initialize the process group
    dist.init_process_group("xla", rank=rank, world_size=world_size)

    dev = xm.xla_device(rank)
    model = ToyModel().to(dev)
    print('model', model)
    ddp_model = DDP(model, device_ids=[dev])
    print('ddp', ddp_model)


if __name__ == '__main__':
  def tracefunc(frame, event, arg, indent=[0]):
      if event == "call":
          indent[0] += 2
          print("-" * indent[0] + "> call function", frame.f_code.co_name)
      elif event == "return":
          print("<" + "-" * indent[0], "exit function", frame.f_code.co_name)
          indent[0] -= 2
      return tracefunc

  import sys
  sys.setprofile(tracefunc)
  demo_basic(0, 1)
```

The last Python function logged before the hang is [`allgather`](https://github.com/pytorch/xla/blob/ae61f2f685b3fa83ae035b6447a420a0bee72da1/torch_xla/distributed/xla_backend.py#L64).

## Expected behavior

DDP initialization should complete.

## Environment

 - Reproducible on XLA backend: CPU or TPU (both on XRT and PjRt)
 - torch_xla version: build from master

## Additional context

I believe DDP initialization is getting stuck on [this line](https://github.com/pytorch/pytorch/blob/1c35f37c9f009e10e3df1d10250672f31dd77f29/torch/csrc/distributed/c10d/reducer.cpp#L2073). Note how the next call after `allgather` is `wait`, there is no call to [`WorkXla.work()`](https://github.com/pytorch/xla/blob/ae61f2f685b3fa83ae035b6447a420a0bee72da1/torch_xla/distributed/xla_backend.py#L199) logged when you run my example. Is the default C++ implementation of [`Work::wait`](https://github.com/pytorch/pytorch/blob/52af4fc5baee363bb9c3170017d46d4fe0069c56/torch/csrc/distributed/c10d/ProcessGroup.cpp#L123) being called instead?

**Comment by hjm-aws** [comment]
Looking.

**Comment by hjm-aws** [comment]
@will-cromar Hi Will, to help me understand the problem better, could you please share the printed dump by your `tracefunc`? Also, if you can include `co_filename` and `co_firstlineno` in your `tracefunc`, it would be more helpful. Thanks!

**Comment by hjm-aws** [comment]
@will-cromar Thanks Will, that's very helpful.

Can I ask you to do me another favor, and try changing the line 199 in your local installation of `/home/ptxla/.local/lib/python3.8/site-packages/torch_xla-1.12-py3.8-linux-x86_64.egg/torch_xla/distributed/xla_backend.py` from the following:
```
  def wait(self):
```
to the following:
```
  def wait(self, timeout):
```

After making that change, can you try running your test again?

My theory is that my implementation of `WorkXla::wait` is not actually overriding the base member `Work::wait` because `WorkXla::wait` has a different signature than `Work::wait`.

**Comment by will-cromar** [comment]
I had the same thought, so I tried adding this to `WorkXla` earlier, but still no luck

```
  def wait(self, timeout):
    return self.wait()
```

**Comment by will-cromar** [comment]
I just tried changing line 199, and the script still gets stuck after `allgather`

**Comment by JackCaoG** [comment]
Just a update here, this seems to be a issue from pytorch end, fix is wip.

**Comment by will-cromar** [comment]
We made some progress debugging this issue internally. There are three lingering issues with initialization currently:

- `allgather` needs an optional `opts` argument (see above for fix)
- Initialization hangs forever on `broadcast` with multiple replicas
- Some internal call to `Tensor::is_alias_of` causes this error: `XLA tensors do not have storage`

I implemented fixes for all three of these issues, but am still struggling with an issue where the gradient does not appear to get reset correctly between steps, unless we use DDP's `no_sync`. I shared my working copy as draft PR #3915 along with more detailed comments and instructions to reproduce the error.

**Comment by alanwaketan** [comment]
The initialization should have been fixed by https://github.com/pytorch/xla/pull/3952. And the NaN should have been fixed by https://github.com/pytorch/xla/pull/3966. A correctness test case is added here: https://github.com/pytorch/xla/pull/3980.

**Comment by alanwaketan** [comment]
Close this as all fixes are landed.
