### ISSUE TITLE
wrap numbers as 0dim tensor

### ISSUE THREAD

**Issue by ailzhang** [pytorch/xla#364]
Minimal repro script:

```
import torch
import torch_xla
import torch_xla_py.utils as xu
import torch_xla_py.xla_model as xm

a = torch.randn(3, 800, 1066)
xla_device = xm.xla_device()

b = a.to(xla_device)
c = b + 1
print(c)
```

**Comment by asuhan** [comment]
@ailzhang PR which fixes this is pending. I'd like to understand the rules for heterogeneous device operations. For example, adding a CUDA and a CPU tensor doesn't work:

```
import torch
import torch.nn as nn

x = torch.randn(2, 3, device=torch.device("cuda"))
y = torch.randn(2, 3, device=torch.device("cpu"))
x + y
```
throws: `RuntimeError: expected type torch.cuda.FloatTensor but got torch.FloatTensor`, while `x + 1` (similar to your case) works. We can imitate any behavior, but I'm not sure which automatic device conversions are desirable and which aren't.
