### ISSUE TITLE
docker container does not work on tpuv3 vm

### ISSUE THREAD

**Issue by MrDavinci** [pytorch/xla#3665]
Hi, I'm using a TPU-v3 vm. The prebuilt enviroment is tpu-vm-pt-1.11. It is OK to use tpu by the defult enviroment. But, the error happens when I start an xla container. I have tried several docker images such as nightly_3.7nightly_3.7_20220624, r1.12_3.7_tpuvmr1.12_3.7_tpuvm_20220614, r1.12_3.8_tpuvmr1.12_3.8_tpuvm_20220614. 

sudo docker pull xxxxxxxxx
sudo docker run -it --shm-size 16G gcr.io/tpu-pytorch/xla:nightly_3.8_tpuvm_20210827
export TPU_IP_ADDRESS=10.128.15.203
export XRT_TPU_CONFIG="localservice;0;localhost:51011"
python3
import torch_xla.core.xla_model as xm
dev = xm.xla_device()
-----------------------output------------------
2021-09-17 17:56:35.994077: E      13 tensorflow/core/framework/op_kernel.cc:1623] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey
2021-09-17 17:56:35.994154: E      13 tensorflow/core/framework/op_kernel.cc:1623] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch_xla/core/xla_model.py", line 231, in xla_device
    devices = get_xla_supported_devices(
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch_xla/core/xla_model.py", line 137, in get_xla_supported_devices
    xla_devices = _DEVICES.value
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch_xla/utils/utils.py", line 32, in value
    self._value = self._gen_fn()
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch_xla/core/xla_model.py", line 19, in <lambda>
    _DEVICES = xu.LazyProperty(lambda: torch_xla._XLAC._xla_get_devices())
RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:1291 : Check failed: session.Run({tensorflow::Output(result, 0)}, &outputs) == ::tensorflow::Status::OK() (Invalid argument: No matching devices found for '/job:localservice/replica:0/task:0/device:TPU_SYSTEM:0' vs. OK)
*** Begin stack trace ***
        tensorflow::CurrentStackTrace()
        xla::XrtComputationClient::InitializeAndFetchTopology(std::string const&, int, std::string const&, tensorflow::ConfigProto const&)
        xla::XrtComputationClient::InitializeDevices(std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
        xla::XrtComputationClient::XrtComputationClient(xla::XrtComputationClient::Options, std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
        xla::ComputationClient::Create()

        xla::ComputationClient::Get()

        PyCFunction_Call
        _PyObject_MakeTpCall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall

        _PyObject_GenericGetAttrWithDict
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_Vectorcall

        _PyEval_EvalCodeWithName
        PyEval_EvalCode

        PyRun_InteractiveLoopFlags
        PyRun_AnyFileExFlags

        Py_BytesMain
        __libc_start_main

**Comment by JackCaoG** [comment]
This is most likely a libtpu version mimsatch. I have a doc in https://docs.google.com/document/d/1nPtVYLg8ndk_wpEJ9YIF3dKuXad8rv-DCs1XV24Fyb8/edit?usp=sharing (You will need to request access). We are work on opening source this doc but in the mean time you can just request access to this doc.

**Comment by MrDavinci** [comment]
I'll try it, thanks a lot!
