### ISSUE TITLE
Add PyTorch Symbolic Shape Analysis (SSA) dynamic dimensions to the shape hash function

### ISSUE THREAD

**Issue by miladm** [pytorch/xla#3668]
Add PyTorch Symbolic Shape Analysis (SSA) dynamic dimensions to the shape hash function. 

This is to prevent painful bugs creeping in as a result of adding dynamic shape to PyTorch/XLA. For instance, this feature guards against a corner case that dynamism switches across dimensions of a tensor. One might think of other scenarios also.

Proposal: to keep the hashing overhead minimal, only add the dynamic bit to the hash when its value is `True`.

CC @Krovatkin @Gamrix @wconstab @JackCaoG @shauheen

**Comment by wconstab** [comment]
@miladm did we decide in the end that this is not needed in general?  (The reason being: ops that produce dynamic dimensions are already influencing the graph with their own opcode hash)

For the future case where 'leaf/ input' tensors may have dynamic dimensions expressed on them, i believe we also agreed to use some kind of IR node to mark this 'set dyn dim' property into the graph, obviating the need for hashing on 'is_dynamic_dim'.

cc @Krovatkin

**Comment by miladm** [comment]
@will-cromar: that's correct, we decided that this feature is no longer needed for the scope of our work. We may open it in future phases. Thank you for providing the clear justification! 

Closing.

CC @JackCaoG
