### ISSUE TITLE
Build codegen for `round`

### ISSUE THREAD

**Issue by miladm** [pytorch/xla#3710]
Build codegen for [`round` op](https://github.com/pytorch/xla/blob/master/torch_xla/csrc/ops/ops.cpp#L83)

Please update the [op coverage list](https://github.com/pytorch/xla/issues/3560) once done.

[CODEGEN_MIGRATION_GUIDE](https://github.com/pytorch/xla/blob/master/CODEGEN_MIGRATION_GUIDE.md)

**Comment by miladm** [comment]
@li-yi-dong to work self-assign once he joins this project.

**Comment by li-yi-dong** [comment]
Great!

**Comment by li-yi-dong** [comment]
Generated LazyIr.h:
```
class Round : public XlaNode {
 public:
  static torch::lazy::OpKind ClassOpKind() {
    return torch::lazy::OpKind(at::aten::round);
  }

  Round(const torch::lazy::Value& self, std::vector<torch::lazy::Shape>&& shapes)

      : XlaNode(torch::lazy::OpKind(at::aten::round),
              {self}, std::move(shapes),
              [&]() { return RoundOutputShape(self); },
              /* num_outputs */ 1,
              torch::lazy::MHash())


  {

  }

  std::string ToString() const override {
    std::stringstream ss;
    ss << XlaNode::ToString();

    return ss.str();
  }

  bool CanBeReused(const torch::lazy::Value& self) const {
    return false;
    }

  torch_xla::XlaOpVector Lower(LoweringContext* loctx) const override;




};
```

Generated XLANativeFunctions.cpp:
```
at::Tensor XLANativeFunctions::round(const at::Tensor & self) {

        XLA_FN_COUNTER("xla::");
        auto common_device = torch_xla::bridge::GetXlaDevice(self);
        TORCH_INTERNAL_ASSERT(common_device);

        torch_xla::XLATensorPtr lazy_self = torch_xla::bridge::GetXlaTensorOrCreateForWrappedNumber(self, *common_device);
        torch::lazy::NodePtr node = torch::lazy::ReuseNode<Round>(lazy_self->GetIrValue());
        if (!node) {
            auto out_meta = at::meta::round(self);
            std::vector<torch::lazy::Shape> shapes{
        torch::lazy::Shape(out_meta.scalar_type(), out_meta.sizes().vec())};
            TORCH_INTERNAL_ASSERT(shapes.size() == 1);
            if(torch::lazy::symbolicShapeEnabled()){
                std::vector<torch::jit::IValue> inputs = { self };
                char* schema_str = "aten::round(Tensor self) -> Tensor";
                applySymbolicShapesOnLT(schema_str, inputs, shapes);
            }

            node = torch::lazy::MakeNode<Round>(lazy_self->GetIrValue(), std::move(shapes));
            CacheNode(node);
        }

        auto result = torch_xla::bridge::AtenFromXlaTensor(
                torch_xla::XLATensor::Create(std::move(node), *common_device));
        return result;
    };
```

**Comment by li-yi-dong** [comment]
I get two questions:
1. There are lots of `LazyIr.h ` after building 
<img width="812" alt="截屏2022-07-20 下午2 49 59" src="https://user-images.githubusercontent.com/73142299/179915778-d62814fe-8bdb-4f66-8254-e00c697c3826.png">
What is the relation between them and why the `LazyIr.h` under `Python site-packages` looks like this:
```
#pragma once

// This file contains autogenerated LazyTensor IR nodes
${lazy_ir_sysinc}
${lazy_ir_inc}

${namespace_prologue}
using at::operator<<;

// kNullValue is used to contribute a static hash value any time
// a node has an Optional<Value> input that is nullopt.  It is important
// to differentiate between HASH(nullopt, something) and HASH(something, nullopt),
// and using kNullValue in the hash function in the order of arguments
// serves this purpose.
static const torch::lazy::Value kNullValue = torch::lazy::Value();

${ir_declarations}

${namespace_epilogue}
```
2. Why the method `CanBeReused` generated in `LazyIr.h`  all simply return `False`?

**Comment by li-yi-dong** [comment]
Ah, test failed but not knowing why:
<img width="1131" alt="截屏2022-07-20 下午3 11 13" src="https://user-images.githubusercontent.com/73142299/179919664-77657fe3-d909-41b5-8094-b21fc753d0d1.png">

**Comment by li-yi-dong** [comment]
> Ah, test failed but not knowing why: <img alt="截屏2022-07-20 下午3 11 13" width="1131" src="https://user-images.githubusercontent.com/73142299/179919664-77657fe3-d909-41b5-8094-b21fc753d0d1.png">

Ah, it passed after setting some environment variables

<img width="911" alt="截屏2022-07-20 下午8 40 40" src="https://user-images.githubusercontent.com/73142299/179984674-f9d7a19b-7b68-4a2c-9931-7eb3584f4944.png">

**Comment by wonjoolee95** [comment]
Hi @li-yi-dong, great questions and looks like you're making some good progress!

1. What are the generated files?
In the list of generated files, the one we (PyTorch/XLA) are mostly interested is the only the `pytorch/xla/torch_xla/csrc/generated/LazyIr.h`. This contains the generated code for ops listed under `full_codegen` in the `xla_native_functions.yaml` file, specific to PyTorch/XLA. The other listed files in the screenshot belong to upstream PyTorch, which appear to be include and template files. The file under python `site-packages` appears to be the template that is used by the upstream PyTorch codege.

2. Why the method CanBeReused generated in LazyIr.h all simply return False?
This `CanBeReused` function seems to be related to the property of the re-usability of the IRNode. In the scope of the codegen migration, this function is not used/relevant. 

Regarding the environment variables, they are mentioned in our migration readme under "Before you start" section here at https://github.com/pytorch/xla/blob/master/CODEGEN_MIGRATION_GUIDE.md#before-you-start. 

Also feel free to open a draft PR as you're working on this, so we can directly comment and answer questions there specific to that PR. Again, thanks for working on this!
