### ISSUE TITLE
Error at torch_xla._XLAC._xla_tensors_from_aten(tensors, devices) 

### ISSUE THREAD

**Issue by data-weirdo** [pytorch/xla#3810]
## ❓ Questions and Help

I am trying to use the google TPU, and using transformers' `accelerator` for convenience for the first time.

The TPU that I was allocated is v2-8, and the library versions that I use are as below.
```
transformers: '4.21.0'
accelerate: '0.11.0'
torch: '1.10.0+cu102'
torch_xla: '1.10'
```

And The place where I got stuck is this: 

```
def send_cpu_data_to_device(data, device):

  def convert_fn(tensors):
    devices = [str(device)] * len(tensors)
    return torch_xla._XLAC._xla_tensors_from_aten(tensors, devices)    ### The place where I got stuck. 

  def select_fn(v):
    return type(v) == torch.Tensor and v.device.type == 'cpu'

  return ToXlaTensorArena(convert_fn, select_fn).transform(data)
```

And, the error which appears on the terminal is: 
( I tried to figure out the cause of this error by referring to others', but could not find the case. )

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/43376853/182018918-03e2e28d-b666-4bd6-b6bb-600513402b25.png">

The form of inputs are as below:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/43376853/182019115-b58952ee-b044-4a4c-a202-8aa36472a8e8.png">

I cannot find out the reason why I cannot load the tensors to the torch_xla. 
I need an help :)

Thank you in advance!

**Comment by JackCaoG** [comment]
This might be a OOM. If it is on colab, then inspecting the server log will be complicated. Can you try to reduce the input size? v2-8 only has 8GB of HBM per core.

**Comment by data-weirdo** [comment]
@JackCaoG 
Thank you for your answer. It was not actually an OOM because the batch size was really really small.
Anyway, I deleted the TPU node, and set the environment again as I once did.
Now it works.  Thank you so much for your reply :)

**Comment by JackCaoG** [comment]
Ah nice. It is possible that TPU/XRT server was left in a bad state, restarting usually solved that.
