### ISSUE TITLE
`lazySymIntNode->node_` segfaults on simple dynamic tensor conversation between `SymInt` and `toSymIntNodeImpl`

### ISSUE THREAD

**Issue by miladm** [pytorch/xla#3887]
## 🐛 Bug

While testing `SetupSymSizeProperties` implementation in this [PR](https://github.com/pytorch/xla/pull/3715), I developed a test code block that calls `std::dynamic_pointer_cast<torch::lazy::DimensionNode>(size_node)->getStaticValue()` after constructing a dynamic `SymInt` and passing it to `sizes_and_strides_`.

It seems either `symbolicIntNode` or `lazySymIntNode` is not properly constructed by the upstream pytorch. This leads  to `auto size_node = lazySymIntNode->node_;` call to `segfault`. See below. @Krovatkin wdyt?

```
void XLATensorImpl::SetupSymSizeProperties() {
  size_t generation = tensor_->generation();
  if (generation != generation_) {
    // Fill up the basic dimension data members which the base class
    // implementation uses in its APIs.
    auto shape = tensor_->shape();
    auto rank = tensor_->shape().get().rank();
    c10::SmallVector<c10::SymInt, 5> sym_sizes;
    numel_ = 1;
    for (auto i : c10::irange(rank)) {
      if (tensor_->shape().get().is_dynamic_dimension(i)) {
        XLAIrBuilder a = XLAIrBuilder();
        auto dim_node = a.MakeSizeNode(tensor_->GetIrValue(), i);
        auto* sn = dynamic_cast<torch::lazy::SymIntNodeImpl*>(dim_node.get());
        sym_sizes.push_back(sn->toSymInt());
        numel_ *= dynamic_cast<SizeNode*>(dim_node.get())->getStaticValue();
        std::cout << "Verify getStaticValue: " << dynamic_cast<SizeNode*>(dim_node.get())->getStaticValue() << std::endl;
      } else {
        sym_sizes.push_back(c10::SymInt(tensor_->shape().get().dimensions(i)));
        numel_ *= tensor_->shape().get().dimensions(i);
      }
    }
    sizes_and_strides_.set_sizes(sym_sizes);
    auto updated_strides = torch::lazy::ComputeArrayStrides(
        torch::lazy::ToVector<int64_t>(shape.get().dimensions()));
    for (int i = 0; i < updated_strides.size(); i++) {
      sizes_and_strides_.stride_at_unchecked(i) = updated_strides[i];
    }
    generation_ = generation;





    /**** THIS IS JUST A TEST CODE BLOCK VERIFYING CONVERSION TO DimensionNode WORKS ****/
    std::cout << "Test Code Block Start" << std::endl;
    {
      at::IntArrayRef siz = sizes_default();
      c10::SymIntArrayRef s = c10::SymIntArrayRef(reinterpret_cast<const c10::SymInt*>(siz.data()), siz.size());
      std::cout << "Size of symints: " << s.size() << std::endl;
      c10::SymIntNode symbolicIntNode = s[0].toSymIntNodeImpl();   //I verified dimension 0 is dynamic in this test
      auto* lazySymIntNode = dynamic_cast<torch::lazy::SymIntNodeImpl*>(symbolicIntNode.get());
      std::cout << "before segfault" << std::endl;
      auto size_node = lazySymIntNode->node_;
      std::cout << "after segfault" << std::endl;
      auto upper_bnd = std::dynamic_pointer_cast<torch::lazy::DimensionNode>(size_node)->getStaticValue();
      std::cout << "Re-verify getStaticValue: " << upper_bnd << std::endl;
    }
    std::cout << "Test Code Block End" << std::endl;
  }
}
```

Output:
```
XLANativeFunctions::nonzero
dynamic index: 0
Verify getStaticValue 5                     <-- this value is expected
Test Code Block Start
Size of symints: 2
before segfault
Segmentation fault (core dumped)
```

The output indicates the upper bound information is correctly produced by the main code, but the test block fails to correctly return a valid `DimensionNode` onject.

CC @JackCaoG @Gamrix @ezyang

**Comment by miladm** [comment]
Looking at [this line](https://github.com/pytorch/pytorch/blob/34bdd46e6e6a15dfa1c765c1fb8d9d7bc02dc102/torch/csrc/lazy/core/tensor.h#L16), it seems `dynamic_cast<torch::lazy::SymIntNodeImpl*>(symbolicIntNode.get());` is ok. I wonder if `c10::SymIntNode symbolicIntNode = s[0].toSymIntNodeImpl();` is the root cause of the `segault` issue.

**Comment by miladm** [comment]
I identified this test when I integrated `sym_sizes` with dynamism and tried to verify [`TestExpandSymtInt`](https://github.com/pytorch/xla/pull/3715/files#diff-bb0d401089d221de7a490f4765fc182a09df75e0bca8fa46ba952816afebda5bR4661-R4695). This unit test currently breaks due to this segfault issue.

**Comment by Krovatkin** [comment]
>       at::IntArrayRef siz = sizes_default();

did you change the implementation of this `sizes_default`, since it used to return the **static** upper bounds (i.e. plain ints) no matter what op it's for? We can't convert plain integers to symint nodes, we have to treat them as https://github.com/pytorch/pytorch/blob/master/c10/core/SymInt.h#L112

You could confirm that this is the case by testing `is_symbolic` on `s[0]`. If it returns false, we **should** be segfaulting :)

**Comment by Krovatkin** [comment]
@miladm also due to us switching to reference counting, users should **never** use naked reinterpret casts. Please use this instead: https://github.com/pytorch/pytorch/blob/master/c10/core/SymIntArrayRef.h#L82-L91

**Comment by miladm** [comment]
@Krovatkin I didn't modify any upstream code in this issue. 
`is_symbolic` returns `true` for `s[0]`. That's why I am concerned if the upstream may have an issue.

**Comment by Krovatkin** [comment]
@miladm 

Could you add a print statement to a d-tor of `torch::lazy::SymIntNodeImpl` ? 


```cpp
namespace torch {
 namespace lazy {
~torch::lazy::SymIntNodeImpl() {
   std::cout << "destroying node << this << std::endl;
}
}}
```

and another one right here: `dynamic_cast<torch::lazy::SymIntNodeImpl*>(symbolicIntNode.get())`

```cpp
std::cout << "using node << symbolicIntNode.get() << std::endl;
```

**Comment by Krovatkin** [comment]
@miladm is my understanding correct and this code 

```
 /**** THIS IS JUST A TEST CODE BLOCK VERIFYING CONVERSION TO DimensionNode WORKS ****/
 ```

is also in `SetupSymSizeProperties` ?

**Comment by Krovatkin** [comment]
@miladm  

Oh wait this doesn't look correct to me 

```cpp
        auto dim_node = a.MakeSizeNode(tensor_->GetIrValue(), i);
        auto* sn = dynamic_cast<torch::lazy::SymIntNodeImpl*>(dim_node.get());
```

it should be 

```cpp
auto symint_node = c10::make_intrusive<torch::lazy::SymIntNodeImpl>(dim_node);
SymInt sn(symint_node);
```

**Comment by miladm** [comment]
thanks @Krovatkin! 

Using the following lines avoids the segfault. 

```
if (tensor_->shape().get().is_dynamic_dimension(i)) {
        auto dim_node = a.MakeSizeNode(tensor_->GetIrValue(), i);
        auto symint_node = c10::make_intrusive<torch::lazy::SymIntNodeImpl>(dim_node);
        c10::SymInt sn(symint_node);
        sym_sizes.push_back(sn);
} else {
        ...
}
```

However, I it turns out the dynamic properties of the `SymInt` are not preserved by this code because the following code in the test block returns false on the `0`-th dimension. Seems like I am missing an API call in the code block above.

```
      at::IntArrayRef siz = sizes_default();
      c10::SymIntArrayRef s = c10::SymIntArrayRef(reinterpret_cast<const c10::SymInt*>(siz.data()), siz.size());
      if (s[0].is_symbolic()) {
        std::cout << "Size of symints: " << s.size() << std::endl;
        c10::SymIntNode symbolicIntNode = s[0].toSymIntNodeImpl();   //I verified dimension 0 is dynamic in this test
        auto* lazySymIntNode = dynamic_cast<torch::lazy::SymIntNodeImpl*>(symbolicIntNode.get());
        std::cout << "before segfault" << std::endl;
        auto size_node = lazySymIntNode->node_;
        std::cout << "after segfault" << std::endl;
        auto upper_bnd = std::dynamic_pointer_cast<torch::lazy::DimensionNode>(size_node)->getStaticValue();
        std::cout << "Re-verify getStaticValue: " << upper_bnd << std::endl;
      }
```

**Comment by Krovatkin** [comment]
@miladm  

It doesn't look like you are missing anything.

1. do you mean `if (s[0].is_symbolic())`  returns `false`?
2. what does `std::cout << (void*)sn->toSymInt().as_int_unchecked() << std::endl;` print? (when we create symints)
3. what does `std::cout << siz.size() << std::endl;` print?
4. what does  `std::cout << (void*)s[0].as_int_unchecked() << std::endl;` print? (when we use symints)

**Comment by miladm** [comment]
@Krovatkin my responses:

1. yes, it returns `false`.
2. 1 for `std::cout << sn.as_int_unchecked() << std::endl;`
3. 2 for `std::cout << s.size() << std::endl;`
4. 0x1 for `std::cout << (void*)s[0].as_int_unchecked() << std::endl;`

**Comment by Krovatkin** [comment]
@miladm I'm terribly sorry, it looks like API changed quite a bit after memory management, we should be doing this: 

```cpp

        auto dim_node = a.MakeSizeNode(tensor_->GetIrValue(), i);
        auto symint_node = c10::make_intrusive<torch::lazy::SymIntNodeImpl>(dim_node);
        auto sn = symint_node->toSymInt(); // conversion from symintnode to symint
        sym_sizes.push_back(sn);
```

**Comment by miladm** [comment]
@Krovatkin this last change helped unblock progress. Thanks for sharing the recent API updates here. I now run into a new issues that is captured here: https://github.com/pytorch/xla/issues/3897

**Comment by miladm** [comment]
Turns out I was able to resolve this issue via the last fix to the recent API change. Thanks @Krovatkin.
