### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by dseuss** [pytorch/xla#390]
I am trying to build pytorch-xla using the instructions provided in the README. However, they don't seem to be up to date as there is no `.torch_commit_id` file.

When I simply use the current Pytorch master branch, everything seems to work fine and compile. However, the setup.py script hangs (after building everything) at the following message:
```
building '_XLAC' extension
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/torch_xla
creating build/temp.linux-x86_64-3.7/torch_xla/csrc
creating build/temp.linux-x86_64-3.7/torch_xla/csrc/ops
creating build/temp.linux-x86_64-3.7/torch_xla/csrc/passes
```

**Comment by dlibenzi** [comment]
Hi Daniel, can you try to run:

$ COMPILE_PARALLEL=0 python setup.py install

**Comment by dseuss** [comment]
Thanks @dlibenzi, that worked!
