### ISSUE TITLE
From tfds.load to working pytorch_xla example

### ISSUE THREAD

**Issue by CYHSM** [pytorch/xla#3941]
Thanks for all the work on this project. I have a question if its possible to replace a tensorflow-dataset DataReader with a PyTorch equivalent. As I found out it is not possible to import both TensorFlow / TensorFlow-datasets and pytorch_xla.

I have the following code which runs on GPU but fails on TPU as I have to import tfds:
```python
ds, ds_info = tfds.load("movi_a/128x128", data_dir="gs://kubric-public/tfds", with_info=True)
train_iter = iter(tfds.as_numpy(ds["train"]))
example = next(train_iter)
```

The dataset is from https://github.com/google-research/kubric, and I was wondering if I can get a data loader using TfRecordReader? As I understand correctly this is only reading single TfRecord files right? How would a full replacement of the above code look like in xla without importing TensorFlow? 

Thanks a lot for any help.

**Comment by JackCaoG** [comment]
What's the error you get when trying to import both tf and pt/xla? Can you try to install the cpu version of tf so it does not try to load libtpu on TPUVM.

**Comment by CYHSM** [comment]
Thanks, you are right, after running `pip install tensorflow-cpu`, it works. Although it is super slow, and raises a warning during training: "tcmalloc: large alloc 1485987840 bytes == 0x28130c000". I guess it is related to some of the commands not being supported? My dataloader looks like this: 
```python
class DataLoader(Dataset):
    def __init__(self, data, steps_per_epoch=1000, num_timesteps=8):
        self.dataloader = tfds.as_numpy(data)
        self.dataloader_iterator = iter(self.dataloader)
        self.transform = T.Resize((32, 32))
        self.steps_per_epoch = steps_per_epoch
        self.num_timesteps = 8

    def __getitem__(self, item):
        try:
            batch = next(self.dataloader_iterator)
        except StopIteration:
            self.dataloader_iterator = iter(self.dataloader)
            batch = next(self.dataloader_iterator)
        
        next_iter = torch.Tensor(batch['video'] / 255.0)
        next_iter = next_iter[torch.randperm(next_iter.shape[0])[:self.num_timesteps]]
        next_iter = rearrange(next_iter, 't h w c -> t c h w')
        next_iter = self.transform(next_iter)
        next_iter = rearrange(next_iter, 't c h w -> t h w c')
        return next_iter, []

    def __len__(self):
        return self.steps_per_epoch

ds, ds_info = tfds.load("movi_a/128x128", data_dir="gs://kubric-public/tfds", with_info=True)
train_ds = Scenes(ds["train"], steps_per_epoch=10)
train_loader = DataLoader(train_ds, batch_size=batch_size, num_workers=8)
```
Anyway you think I can speed it up?

**Comment by CYHSM** [comment]
Okay seems to be just as slow with a dummy Dataloader, so not sure why it is so slow
