### ISSUE TITLE
Op type not registered Error

### ISSUE THREAD

**Issue by dseuss** [pytorch/xla#400]
After successfully compiling xla on a Google Cloud server, I am trying to use a TPU instance to run the tests. However, I get the following error message after setting the TPU worker IP address and running `python test/test_operations`:

```
======================================================================
ERROR: test_view (__main__.TestXLATensor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_operations.py", line 1346, in test_view
    out = xt_x.view(-1, 320).to_tensor()
RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:87 : Check failed: session_work.first->session()->Run( session_work.second.feed_inputs, session_work.second.outputs_handles, &outputs) == ::tensorflow::Status::OK() (Not found: Op type not registered 'XRTAllocateFromTensor' in binary running on n-04d145c9-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. vs. OK)
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	xla::XrtComputationClient::TransferToServer(absl::Span<xla::ComputationClient::TensorSource const>)
	torch_xla::TensorToXlaData(at::Tensor const&, torch_xla::Device const&)
	torch_xla::XLATensor::GetIrValue(at::Tensor const&) const
	torch_xla::XLATensor::GetIrValue() const
	torch_xla::XLATensor::CreateView(absl::Span<long long const>) const
	torch_xla::XLATensor::view(torch_xla::XLATensor const&, absl::Span<long long const>)


	_PyMethodDef_RawFastCallKeywords
	_PyCFunction_FastCallKeywords
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallKeywords
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_FastCallDict
	_PyObject_Call_Prepend
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_FastCallDict
	_PyObject_Call_Prepend

	_PyObject_FastCallKeywords
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_FastCallDict
	_PyObject_Call_Prepend
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_FastCallDict
	_PyObject_Call_Prepend

	_PyObject_FastCallKeywords
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_FastCallDict
	_PyObject_Call_Prepend
	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_FastCallDict
	_PyObject_Call_Prepend

	_PyObject_FastCallKeywords
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallKeywords
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallKeywords
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_FastCallDict
	_PyObject_Call_Prepend

	_PyObject_FastCallKeywords
	_PyEval_EvalFrameDefault

	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	PyEval_EvalCodeEx
	PyEval_EvalCode

	PyRun_FileExFlags
	PyRun_SimpleFileExFlags

	_Py_UnixMain
	__libc_start_main

*** End stack trace ***


----------------------------------------------------------------------
```

The TF version on the TPU node is 1.12 and I am using the master branch from this repo as well as Pytorch.

**Comment by asuhan** [comment]
We need a newer TF version on the TPU node, 1.13 will do. @dlibenzi do you know the exact timeline for 1.13?

**Comment by dseuss** [comment]
Ok, so this is currently not usable in google cloud (as 1.12 is the newest version I could find)?

**Comment by asuhan** [comment]
Correct, you'd need access to TPU nodes running nightly TF. IIRC 1.13 should become available within ~1 month.

**Comment by dseuss** [comment]
Thanks for your quick reply. In that case, I'll just need to wait.

**Comment by dlibenzi** [comment]
While this is likely a TF compatibility, I wonder if you can post the complete error.
There should have been more information printed on the console.

**Comment by dlibenzi** [comment]
> While this is likely a TF compatibility, I wonder if you can post the complete error.
> There should have been more information printed on the console.

Never mind. Hidden by small github window :)

_Not found: Op type not registered 'XRTAllocateFromTensor' in binary running on n-04d145c9-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed._

**Comment by mvanelk** [comment]
I'm at a similar point at the moment (GCP VM provisioned with PyTorch & XLA from most recent builds on the storage.googleapis.com/pytorch-tpu-releases, TPU connected and visible), and get the same error (`Op type not registered 'XRTAllocateFromTensor`). 

The answer here refers to needing TF 1.13, which my TPU VM has, however the answer to #602 now mentions TF 1.14 will be necessary. Do I understand correctly that there is currently no way to train PyTorch models on a TPU, until TF 1.14 is released?
