### ISSUE TITLE
[PT_BREAK] #83735 CI job failure due to TestPjRtDistributedDataParallel

### ISSUE THREAD

**Issue by H-Huang** [pytorch/xla#4005]
## ❓ Questions and Help

Hi, I am a developer on the PyTorch distributed team. I am modifying some of the distributed collectives we support (https://github.com/pytorch/pytorch/pull/83735). I recently noticed that an XLA job in CI (https://github.com/pytorch/pytorch/actions/runs/3047706694/jobs/4912201272) started failing due to my changes. The failures are due to tests in this file which were recently added: https://github.com/pytorch/xla/blob/16fa65f4f9b5515cffab9366d683ee51496819e6/test/pjrt/test_ddp.py and it does seem relevant to my changes in distributed, but I am not sure how to fix the tests or work around this.

This is the only job failure in CI that is blocking me so I would appreciate any help!

cc @alanwaketan who added the test (hi again 🙂)

**Comment by JackCaoG** [comment]
@will-cromar Can you take a look?

**Comment by kwen2501** [comment]
Hi @alanwaketan , I notice that the ddp test uses the xla distributed backend:
```
import torch_xla.distributed.xla_backend
```
However, since this backend only implements the Python level subclass, I am not sure how it would contend with Howard's changes in https://github.com/pytorch/pytorch/pull/83735 (which are all C++).
Any suggestion?

**Comment by alanwaketan** [comment]
@H-Huang I saw you merged your changes. Are we good to close this issue?
