### ISSUE TITLE
Add blas and lapack operations

### ISSUE THREAD

**Issue by asuhan** [pytorch/xla#401]
Most of operations in https://pytorch.org/docs/stable/torch.html#blas-and-lapack-operations are either straightforward or have lowerings in the XLA client library (`tensorflow/compiler/xla/client/lib/cholesky.{h, cc}` and `tensorflow/compiler/xla/client/lib/qr.{h, cc}`.

**Comment by vishwakftw** [comment]
Do we take the current version of TensorFlow for XLA reference, or the latest released version for XLA reference? The reason behind the question is that Cholesky has been made a HLO operator, and the files that you have referenced don't exist in the master branch anymore.

**Comment by asuhan** [comment]
Always latest release, I haven't noticed the change to HLO has landed. Updating TF for this is ok -- we want to work with latest anyway.

**Comment by dlibenzi** [comment]
Vishwak, I have a PR that bring TF to new state.
There have been changes there that needed fixes.
That PR contains also other stuff I am looking at, and if it that other stuff does not get to a mergeable state, I will split the TF part out.

**Comment by mruberry** [comment]
@dlibenzi Is this still open?
