### ISSUE TITLE
Add 5D tiled test for ShardingUtil::ShardTensor

### ISSUE THREAD

**Issue by steventk-g** [pytorch/xla#4093]
Adds to tests introduced by https://github.com/pytorch/xla/pull/3684

Add the test to `XLAShardingTest.ShardTensor` in `test/cpp/test_xla_sharding.cpp`

**Comment by steventk-g** [comment]
This task is blocked because there is no `Array5D` class in XLA. It only goes up to 4D right now.

**Comment by yeounoh** [comment]
Thanks @steventk-g , I think we can use the generic `xla::Array<T>` to implement the hypercube mesh. Let me take a look.
