### ISSUE TITLE
Append device ordinal to tensors file being saved

### ISSUE THREAD

**Issue by alanwaketan** [pytorch/xla#4130]
While running multi-processes experiments with XRT, it can smartly save the tensors file according to device ordinal.
Run the following command:
`MASTER_ADDR=localhost MASTER_PORT=6000 XLA_SAVE_TENSORS_FILE=ddp_small_1.txt python test/test_ddp.py TestXrtDistributedDataParallel.test_ddp_correctness --debug`
will result in:
```
ddp_small_1.txt.0
ddp_small_1.txt.1
ddp_small_1.txt.2
ddp_small_1.txt.3
```

However, in PJRT, run:
`PJRT_DEVICE=TPU XLA_SAVE_TENSORS_FILE=ddp_small_1.txt python test/pjrt/test_ddp.py TestPjRtDistributedDataParallel.test_ddp_correctness --debug`
will just result in:
```
ddp_small_1.txt
```

After digging a bit, it looks like the code does the magic is here: https://github.com/pytorch/xla/blob/e3a6e3a832d6652437e6067be4bc77c2fb518bc2/torch_xla/csrc/debug_util.cpp#L120, and then it utilizes an env called `XRT_SHARD_LOCAL_ORDINAL` to grep the device ordinal. I was told by @JackCaoG that @will-cromar is not fan to utilize env to setup device ordinal. Therefore, I will leave this problem to Will.

**Comment by will-cromar** [comment]
I believe this bug was resolved a while ago. Closing.
