### ISSUE TITLE
Is dataset shared across TPU cores? Running out of memory on colab TPU

### ISSUE THREAD

**Issue by brooksidequant** [pytorch/xla#4142]
## ❓ Questions and Help
Hi I've got an existing pytorch model training that I'm trying to migrate off laptop to colab. I tried to pattern my notebook off the excellent multi-core-alexnet-fashion-mnist.ipynb.

The dataset itself is 7Gb and the model is ~200Mb when loaded from saved state_dict. (measured via isolated loads and viewing Activity Monitor on MacBook) Memory usage rises to about 9Gb while doing some of the transforms on the data before creating data sets. But those should be completed before the training starts and thus the resting 7Gb figure seems more relevant here.

The Multi-processing setup limited to single core is running successfully on standard RAM colab instance. (12Gb) This setup has the data loading within the multi-processing context as it seems most of the examples do. (though I think I've seen cases were the dataset is constructed before the map_fxn and just referenced from the data sampler/loader calls within the map_fxn) In any case, my assumption is that the dataset only exists on the TPU since the CPU RAM usage is only about 2Gb while model is training.

Once I try to run this on 8 cores however, even with the high RAM runtime (32Gb) the training crashes after a few steps. I see the RAM in colab shoot up towards 28Gb right before this happens. Pretty unclear why this would be the case in going from 1 core to 8. Any pointers to structural errors in the setup below would be appreciated - thanks!

Relevant code below:

```
# Define Parameters
FLAGS = {}
FLAGS['datapath'] = 'data.pickle'
FLAGS['batch_size'] = 50
FLAGS['num_workers'] = 4
FLAGS['learning_rate'] = 0.01
FLAGS['momentum'] = 0.5
FLAGS['num_epochs'] = 10
FLAGS['num_cores'] = 8
FLAGS['log_steps'] = 20
FLAGS['metrics_debug'] = True

import torch
import torch.nn as nn
from torch import optim
from torch.optim.lr_scheduler import MultiStepLR
from torch.utils.data import TensorDataset, random_split
import torch_xla
import torch_xla.core.xla_model as xm
import torch_xla.distributed.parallel_loader as pl
import torch_xla.distributed.xla_multiprocessing as xmp
import numpy as np
import time
import pickle
import datetime
from pathlib import Path
from project.models import model_0001

#model params
max_z = 80
features = 782

SERIAL_EXEC = xmp.MpSerialExecutor()
# Only instantiate model weights once in memory.
WRAPPED_MODEL = xmp.MpModelWrapper(model_0001.UNet(max_z, features))

def train_model():
  torch.manual_seed(1)
  
  def get_dataset():
    with open(FLAGS['datapath'], 'rb') as f:
      elem_symb = pickle.load(f)
      el_index = pickle.load(f)
      fracs = pickle.load(f)
      wave = pickle.load(f)
      x_data = pickle.load(f)
      y_data = pickle.load(f)

    my_mult = 1.17
    x_data *= my_mult
    y_data *= my_mult
    x_data[x_data < 0] = 0
    y_data[y_data < 0] = 0
    x_shape = x_data.shape
    y_shape = y_data.shape
    xd0 = x_shape[0]
    xd1 = x_shape[1]
    for i in range(xd0):
      x_data[i]= np.log(x_data[i] + 1)
    yd0 = y_shape[0]
    for i in range(yd0):
      y_data[i] = np.log(y_data[i] + 1)
    x_data = torch.tensor(x_data[:,None,:])
    y_data = torch.tensor(y_data)


    spec_ds = TensorDataset(x_data, y_data)
    #create random split for training and validation
    train_len = int(0.8 * len(x_data))
    test_len = len(x_data) - train_len
    train_dataset, test_dataset = random_split(spec_ds,[train_len, test_len])
    
    return train_dataset, test_dataset
  
  # Using the serial executor avoids multiple processes to
  # download the same data.
  train_dataset, test_dataset = SERIAL_EXEC.run(get_dataset)

  train_sampler = torch.utils.data.distributed.DistributedSampler(
    train_dataset,
    num_replicas=xm.xrt_world_size(),
    rank=xm.get_ordinal(),
    shuffle=True)
  train_loader = torch.utils.data.DataLoader(
      train_dataset,
      batch_size=FLAGS['batch_size'],
      sampler=train_sampler,
      num_workers=FLAGS['num_workers'],
      drop_last=True)
  test_loader = torch.utils.data.DataLoader(
      test_dataset,
      batch_size=FLAGS['batch_size'],
      shuffle=False,
      num_workers=FLAGS['num_workers'],
      drop_last=True)

  # Scale learning rate to world size
  lr = FLAGS['learning_rate'] * xm.xrt_world_size()

  # Get loss function, optimizer, and model
  device = xm.xla_device()
  model = WRAPPED_MODEL.to(device)
  optimizer = optim.SGD(model.parameters(), lr=lr, momentum=FLAGS['momentum'])
  loss_fn = nn.MSELoss(reduction='mean')

  def train_loop_fn(loader):
    tracker = xm.RateTracker()
    model.train()
    for x, (data, target) in enumerate(loader):
      optimizer.zero_grad()
      output = model(data)
      loss = loss_fn(output, target)
      loss.backward()
      xm.optimizer_step(optimizer)
      tracker.add(FLAGS['batch_size'])
      if x % FLAGS['log_steps'] == 0:
        print('[xla:{}]({}) Loss={:.5f} Rate={:.2f} GlobalRate={:.2f} Time={}'.format(
            xm.get_ordinal(), x, loss.item(), tracker.rate(),
            tracker.global_rate(), time.asctime()), flush=True)

  def test_loop_fn(loader):
    total_samples = 0
    total_loss = 0
    model.eval()
    data, target = None, None
    for data, target in loader:
      output = model(data)
      total_loss += loss_fn(output, target).item()
      total_samples += data.size()[0]

    avg_loss = total_loss / total_samples
    print('[xla:{}] Avg Loss={:.2f}%'.format(
        xm.get_ordinal(), avg_loss), flush=True)
    return avg_loss, data, target

  # Train and eval loops
  avg_loss = 0.0
  data, target = None, None
  for epoch in range(1, FLAGS['num_epochs'] + 1):
    para_loader = pl.ParallelLoader(train_loader, [device])
    train_loop_fn(para_loader.per_device_loader(device))
    xm.master_print("Finished training epoch {}".format(epoch))

    para_loader = pl.ParallelLoader(test_loader, [device])
    avg_loss, data, target  = test_loop_fn(para_loader.per_device_loader(device))
    if FLAGS['metrics_debug']:
      xm.master_print(met.metrics_report(), flush=True)

  return avg_loss, data, target

# Start training processes
def _mp_fn(rank, flags):
  global FLAGS
  FLAGS = flags
  torch.set_default_tensor_type('torch.FloatTensor')
  avg_loss, data, target = train_model()
  #if rank == 0:
    # Retrieve tensors that are on TPU core 0 and plot.
    #plot_results(data.cpu(), pred.cpu(), target.cpu())

xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=FLAGS['num_cores'],
          start_method='fork')
```

[xla:0](0) Loss=0.76507 Rate=6.64 GlobalRate=6.64 Time=Mon Oct 31 03:43:49 2022
[xla:3](0) Loss=0.75746 Rate=16.30 GlobalRate=16.30 Time=Mon Oct 31 03:44:04 2022
[xla:5](0) Loss=0.72142 Rate=28.52 GlobalRate=28.52 Time=Mon Oct 31 03:44:24 2022
---------------------------------------------------------------------------
ProcessExitedException                    Traceback (most recent call last)
[<ipython-input-9-3774f3e9f3b6>](https://localhost:8080/#) in <module>
     10 
     11 xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=FLAGS['num_cores'],
---> 12           start_method='fork')

2 frames
[/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py](https://localhost:8080/#) in join(self, timeout)
    144                     error_pid=failed_process.pid,
    145                     exit_code=exitcode,
--> 146                     signal_name=name
    147                 )
    148             else:

ProcessExitedException: process 6 terminated with signal SIGKILL

**Comment by brooksidequant** [comment]
I ran an additional experiment, setting the num_cores flag to 1. This runs training successfully but I note that after TPU RAM initially rises to ~8Gb it actually settles back to around 2Gb at the start of training and then grows slowly to ~4Gb. 

Is XLA shuttling the full dataset back to CPU after initially processing it on the TPU? Is there a way (in colab) to observe the CPU RAM? The monitor at top of notebook appears to just report for the TPU.

**Comment by JackCaoG** [comment]
@chandrasekhard2 can you take a look at this one?

**Comment by chandrasekhard2** [comment]
I tried with fake data to see if it succeeds -

```
t = torch.randn((2, 2), device=device)
def get_dataset():
    spec_ds = TensorDataset(t, t)
    train_dataset, test_dataset = spec_ds, spec_ds
    return train_dataset, test_dataset

train_dataset, test_dataset = SERIAL_EXEC.run(get_dataset)
```

I found out that it fails most of the times. My best guess is that non-master nodes are not in sync with the master.

Can you try setting `xm.rendezvous('download_dataset')` after `train_dataset, test_dataset = SERIAL_EXEC.run(get_dataset)` and see if the issue still persists?

Other recommendations to triage -

1. Try with lower batch size.
2. Try with fake_data.
3. Check if data loading happens properly before we hit the training loop.

**Comment by brooksidequant** [comment]
Thanks for suggestion and happy to test out. First though, are xm.rendezvous() and xmp.MpSerialExecutor() meant to be used together? The original example I followed had the rendezvous approach and latter example had SerialExecutor. Seemed it was one or the other to accomplish same purpose. I want to make sure I'm following a/the recommended code pattern first. I'm not trying to do anything too unique here. I think my code follows the referenced example, but not precisely the docs pattern below.

From pytorch docs on XLA:
CLASS torch_xla.distributed.xla_multiprocessing.MpSerialExecutor[[SOURCE]](https://pytorch.org/xla/release/1.7/_modules/torch_xla/distributed/xla_multiprocessing.html#MpSerialExecutor)
Utility to run a function in a serialized fashion among multi-core processes.

Example:

# At global scope.
SERIAL_EXEC = xmp.MpSerialExecutor()

def load_dataset(path):
  return maybe_download_and_load(path)

def _mp_fn(index, ...):
  # Avoid all cores downloading the same data with the serial executor.
  dataset = SERIAL_EXEC.run(lambda: load_dataset('/tmp/mnist-data'))
  ...

xmp.spawn(_mp_fn, ...)

**Comment by brooksidequant** [comment]
In this code segment from the example notebook, I guess I need help understanding what xm.rendezvous() is doing with the non-master threads. Does it cause them to actually skip executions the datasets.FashionMNIST() calls? Or does it simply delay their execution until the master_ordinal reaches that rendezvous? If it's simply delayed - it seems like there is no avoided data download. Unless there is some logic buried in the datasets.FashionMNIST() call to recognize existence of local dataset and NOT download again. (In which case, I think a more transparent example would be more helpful)

```
  if not xm.is_master_ordinal():
    xm.rendezvous('download_only_once')

  train_dataset = datasets.FashionMNIST(
    "/tmp/fashionmnist",
    train=True,
    download=True,
    transform=my_transform)

  test_dataset = datasets.FashionMNIST(
    "/tmp/fashionmnist",
    train=False,
    download=True,
    transform=my_transform)
  
  if xm.is_master_ordinal():
    xm.rendezvous('download_only_once')
```

**Comment by brooksidequant** [comment]
> I tried with fake data to see if it succeeds -
> 
> ```
> t = torch.randn((2, 2), device=device)
> def get_dataset():
>     spec_ds = TensorDataset(t, t)
>     train_dataset, test_dataset = spec_ds, spec_ds
>     return train_dataset, test_dataset
> 
> train_dataset, test_dataset = SERIAL_EXEC.run(get_dataset)
> ```
> 
> I found out that it fails most of the times. My best guess is that non-master nodes are not in sync with the master.
> 
> Can you try setting `xm.rendezvous('download_dataset')` after `train_dataset, test_dataset = SERIAL_EXEC.run(get_dataset)` and see if the issue still persists?
> 
> Other recommendations to triage -
> 
> 1. Try with lower batch size.
> 2. Try with fake_data.
> 3. Check if data loading happens properly before we hit the training loop.
> 
> Regarding your question - Is the dataset shared across TPU cores - The answer is yes for single host with 8 cores (which you are using in this example).

Added the rendezvous where you suggested as:
```
  train_dataset, test_dataset = SERIAL_EXEC.run(get_dataset)
  xm.rendezvous('download_dataset')
```

New error from xmp.spawn() is:
Exception in device=TPU:6: tensorflow/compiler/xla/xla_client/mesh_service.cc:377 : Failed to meet rendezvous 'download_dataset': Socket closed (14)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "<ipython-input-9-3774f3e9f3b6>", line 6, in _mp_fn
    avg_loss, data, target = train_peaks()
  File "<ipython-input-8-75c2cd628fe4>", line 69, in train_peaks
    xm.rendezvous('download_dataset')
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/core/xla_model.py", line 1058, in rendezvous
    return torch_xla._XLAC._xla_rendezvous(get_ordinal(), tag, payload, replicas)
RuntimeError: tensorflow/compiler/xla/xla_client/mesh_service.cc:377 : Failed to meet rendezvous 'download_dataset': Socket closed (14)

ProcessExitedException                    Traceback (most recent call last)
[<ipython-input-9-3774f3e9f3b6>](https://localhost:8080/#) in <module>
     10 
     11 xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=FLAGS['num_cores'],
---> 12           start_method='fork')

2 frames
[/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py](https://localhost:8080/#) in join(self, timeout)
    144                     error_pid=failed_process.pid,
    145                     exit_code=exitcode,
--> 146                     signal_name=name
    147                 )
    148             else:

ProcessExitedException: process 3 terminated with signal SIGKILL

**Comment by brooksidequant** [comment]
I will break this question down into smaller chunks/issues that are easier to address and better structured. My main misunderstanding was thinking that TPU had a form of shared memory that a single copy of dataset could reside in, shared by the data loaders on each core. I can see from some logging that isn't the case. Even if the serial execution or rendezvous are used to force non-master ordinals to wait for master ordinal, they don't see the train/test dataset objects created by the mater ordinal and they go ahead and create their own.
