### ISSUE TITLE
PyTorch/XLA should disable cxx_abi during release.

### ISSUE THREAD

**Issue by vanbasten23** [pytorch/xla#4146]
## 🐛 Bug

PyTorch/XLA release wheel will not be compatible with PyTorch wheel if PyTorch/XLA compiles with cxx_abi.

To release, we need to disable cxx_abi.

It is needed because otherwise pt/xla CI and local build fail. This is caused by https://github.com/pytorch/xla/pull/3714, which was caused by https://github.com/pytorch/pytorch/pull/81058.

## To Reproduce

See https://github.com/pytorch/xla/issues/4133 for more details. PyTorch wheel never build with cxx11 abi.

## Expected behavior

PyTorch XLA should have built without cxx11 abi.

## Environment

TPU VM.

**Comment by yeounoh** [comment]
Did you address this issue already for the 1.14 release?

**Comment by vanbasten23** [comment]
So far, it's only addressed for 1.13 release.

To provide more context when I fixed it with Jack, it sounds we want the cxx_abi to be enabled when we build locally. When build a wheel for nightly or release branches, we want to apply a patch to revert the https://github.com/pytorch/pytorch/pull/81058 such as [this pr](https://github.com/pytorch/xla/commit/dffb9157f16d2fe36d8b56a811840e2f4cb9a566) from pytorch  and disable cxx_abi in pt/xla such as [this pr](https://github.com/pytorch/xla/pull/4134).

For the actionable items in this issue, shall we check in the [patch](https://github.com/pytorch/xla/pull/4137) to our master branch and disable cxx_abi in our docker/Dockerfile in master branch? WDYT @JackCaoG @yeounoh

**Comment by alanwaketan** [comment]
Let me know if I wrongly assigned this to you.

**Comment by JackCaoG** [comment]
@stgpetrovic in case you have some insights

**Comment by vanbasten23** [comment]
To myself: The issue was originally caused by the pytorch [pr](https://github.com/pytorch/pytorch/pull/81058), which failed PyTorch/XLA build so PyTorch/XLA has to enable cxx abi in the release wheel by default in [pr](https://github.com/pytorch/xla/pull/3714) (note, cxx abi was enabled in the CI in the past). This caused pt/xla release wheel to be incompatible with pytorch's release wheel. To mitigate it, we'll have to [disable cxx abi](https://github.com/pytorch/xla/blob/2a11ce05d90f06d5937534f32e3aa7a4afb2ac87/docker/Dockerfile#L11) and apply a pytorch patch to revert the above pytorch pr. So it's error prone in the release process and it can cause other [bugs]([b/273965687](http://b/273965687)). So we want to disable cxx abi in the release wheel (just do the same as PyTorch). 

https://github.com/pytorch/xla/pull/4900 should help disable cxx abi.

**Comment by vanbasten23** [comment]
Verified that the torch_xla wheel with my change complies with pytorch's wheel:

```
xiowei@t1v-n-326ebe45-w-0:~$ sudo docker pull gcr.io/tpu-pytorch/xla:nightly_3.8_tpuvm
xiowei@t1v-n-326ebe45-w-0:~$ sudo docker run --privileged  --shm-size 16G --name tpuvm_docker_3 --net=host -it -d  gcr.io/tpu-pytorch/xla:nightly_3.8_tpuvm
10df07986b8ded05d7aae64dc7d6f64d9f595c2f6a6006ff85cd05e99271d068
xiowei@t1v-n-326ebe45-w-0:~$ sudo docker exec --privileged -it tpuvm_docker_3 /bin/bash
(pytorch) root@t1v-n-326ebe45-w-0:/# yes | pip3 uninstall torch_xla
(pytorch) root@t1v-n-326ebe45-w-0:/# yes | pip3 uninstall torch_xla
WARNING: Skipping torch-xla as it is not installed.
(pytorch) root@t1v-n-326ebe45-w-0:/# yes | pip3 uninstall torch
(pytorch) root@t1v-n-326ebe45-w-0:/# yes | pip3 uninstall torch_vision
WARNING: Skipping torch-vision as it is not installed.

(pytorch) root@t1v-n-0d95297d-w-0:/# pip3 install https://download.pytorch.org/whl/nightly/cpu/torch-2.1.0.dev20230425%2Bcpu-cp38-cp38-linux_x86_64.whl
Collecting torch==2.1.0.dev20230425+cpu
  Downloading https://download.pytorch.org/whl/nightly/cpu/torch-2.1.0.dev20230425%2Bcpu-cp38-cp38-linux_x86_64.whl (197.1 MB)
     |████████████████████████████████| 197.1 MB 38 kB/s
Successfully installed torch-2.1.0.dev20230425+cpu
(pytorch) root@t1v-n-0d95297d-w-0:/# pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch_xla-nightly+20230425-cp38-cp38-linux_x86_64.whl
Collecting torch-xla==nightly+20230425
(pytorch) root@t1v-n-0d95297d-w-0:/# python3 xla/test/test_train_mp_imagenet.py --fake_data --model=resnet50 --num_epochs=1
WARNING:root:XRT configuration not detected. Defaulting to preview PJRT runtime. To silence this warning and continue using PJRT, explicitly set PJRT_DEVICE to a supported device or configure XRT. To disable default device selection, set PJRT_SELECT_DEFAULT_DEVICE=0
WARNING:root:For more information about the status of PJRT, see https://github.com/pytorch/xla/blob/master/docs/pjrt.md
WARNING:root:libtpu.so and TPU device found. Setting PJRT_DEVICE=TPU.
==> Preparing data..
==> Preparing data..
==> Preparing data..
==> Preparing data..
==> Preparing data..
==> Preparing data..
==> Preparing data..
==> Preparing data..
Epoch 1 train begin 21:37:51
| Training Device=xla:1/1 Epoch=1 Step=0 Loss=6.91278 Rate=2.80 GlobalRate=2.80 Time=21:38:37
| Training Device=xla:1/5 Epoch=1 Step=0 Loss=6.91278 Rate=3.14 GlobalRate=3.14 Time=21:38:37
```
