### ISSUE TITLE
[Dynamic Shape]Support `view.symint`

### ISSUE THREAD

**Issue by JackCaoG** [pytorch/xla#4200]
## 🚀 Feature
Currently we always assume input to `view` is a static symint.
https://github.com/pytorch/xla/blob/a843d8bf523d68e49ac2976b92a131c207cd1117/torch_xla/csrc/aten_xla_type.cpp#L2956-L2963
This request tracks the progress of supporting symbolic symint. 

## Motivation

Most models (including a simple liner layer) involve `view` op. We have to support it for dynamic shape.

## Pitch
The change should be somewhat similar to https://github.com/pytorch/xla/pull/3889. IMO view is very similar to reshape, the tricky part is 
1. How to check if a reshape is valid
2. How to use `SetDimensionSize` to correctly perform the dynamic reshape.

## Target code to support
```
import torch
import torch_xla
import torch_xla.core.xla_model as xm

import os
os.environ["XLA_EXPERIMENTAL"] = "nonzero:masked_select:masked_scatter"

dev = xm.xla_device()
size1 = 5
size2 = 2
t1 = torch.zeros([size1, size2], device=dev)
t1[3][0] = 1
# t2 has size [<=10, 2]
t2 = torch.nonzero(t1)
t3 = t2.view([t2.size(0) * t2.size(1)])
```

## Additional context
Since we are in the middle of the functionization migration, I would recommend us to first support `reshape` which is a simpler version of `view`.

FYI @miladm @vanbasten23 @Krovatkin @wconstab

**Comment by miladm** [comment]
Sounds like this issue is blocked on https://github.com/pytorch/xla/issues/4201. Correct?

Marking it as blocked.

**Comment by alanwaketan** [comment]
@vanbasten23 LMK if I wrongly assigned this to you.

**Comment by vanbasten23** [comment]
> Sounds like this issue is blocked on https://github.com/pytorch/xla/issues/4201. Correct? @vanbasten23

This issue has the same problem as https://github.com/pytorch/xla/issues/4201, both are blocked by functionalization per my understanding.

**Comment by vanbasten23** [comment]
Fixing in https://github.com/pytorch/xla/pull/4629

**Comment by vanbasten23** [comment]
Fixed in
