### ISSUE TITLE
[Dynamic Shape] `torch.exapnd` does not work with dynamic target size from python

### ISSUE THREAD

**Issue by JackCaoG** [pytorch/xla#4202]
## 🐛 Bug

In https://github.com/pytorch/xla/pull/3889 we added the support for `exapnd` with `symint`. We have a test at https://github.com/pytorch/xla/blob/a843d8bf523d68e49ac2976b92a131c207cd1117/test/cpp/test_aten_xla_tensor.cpp#L4972-L4978 
to verify that this works at C++ front. However when I try to test this on python it does not work and result into a crash

```
import torch
import torch_xla
import torch_xla.core.xla_model as xm

import os
os.environ["XLA_EXPERIMENTAL"] = "nonzero:masked_select:masked_scatter"

dev = xm.xla_device()
size1 = 5
size2 = 2
t1 = torch.zeros([size1, size2], device=dev)
t1[3][0] = 1
# t2 has size [<=10, 2]
t2 = torch.nonzero(t1)
t5 = torch.tensor(10, device=dev)
t5.expand(t2.size(0))
print(t5.cpu())
```

error
```
(pytorch) root@65d79ef78e4c:/pytorch/xla# python test/test_dynamic_fail.py 
Segmentation fault (core dumped)
```

@miladm @vanbasten23 @Krovatkin @wconstab

**Comment by vanbasten23** [comment]
It sounds we also need to add python tests. Let me fix it and also add your python test to the CI.

**Comment by JackCaoG** [comment]
I think
https://github.com/pytorch/xla/blob/a843d8bf523d68e49ac2976b92a131c207cd1117/test/cpp/test_aten_xla_tensor.cpp#L5003-L5015
is a better example since it is truly dynamic.

**Comment by vanbasten23** [comment]
I followed the example you provided (https://github.com/pytorch/xla/blob/a843d8bf523d68e49ac2976b92a131c207cd1117/test/cpp/test_aten_xla_tensor.cpp#L5003-L5015) and wrote a corresponding python script:
```
import torch
import torch_xla
import torch_xla.core.xla_model as xm

import os
os.environ["XLA_EXPERIMENTAL"] = "nonzero:masked_select:masked_scatter"

dev = xm.xla_device()
size1 = 5
size2 = 2
t1 = torch.zeros([size1, size2], device=dev)
t1[3][0] = 1
t1[3][1] = 1
# t2 has size [<=10, 2]
t2 = torch.nonzero(t1)
t3 = torch.ones(size1, size2)
t4=t3.expand(t2.size(0), size1, size2)
print(t4.cpu())
```

It failed with a different error:
```
Traceback (most recent call last):
  File "test/test_dynamic_shapes2.py", line 17, in <module>
    t4=t3.expand(t2.size(0), size1, size2)
RuntimeError: SymIntArrayRef expected to contain only concrete integers
```
I assume we should support the usage `t4=t3.expand(t2.size(0), size1, size2)`, right?

**Comment by JackCaoG** [comment]
I don't know what's the correct way to construct the 
```
c10::SymIntArrayRef({dynamic_symint, c10::SymInt(3), c10::SymInt(4)})
```
in python. You don't need to copy my c++ test to python since the way to construct symint is different. I think it would be easier if you just do `a.expand(b.size())` where `b.size()` is dynamic.

**Comment by vanbasten23** [comment]
For the original issue you filed, it failed at https://github.com/pytorch/xla/blob/0daf6fe975fea345bc66e92e6121105eb7ed259c/torch_xla/csrc/torch_util.cpp#L18
 where `lazySymNode` seem to be null, which suggests the `dynamic_cast<XLASymNodeImpl*>(symbolicIntNode.get());` failed.

Via gdb, I was able to find `symbolicIntNode.get()` returns a `(c10::SymNodeImpl *)` object. Also, we still have `class TORCH_API XLASymNodeImpl : public c10::SymNodeImpl` and c10::SymNodeImpl has virtual function. Do you have any hints on why the `dynamic_cast` would fail or any suggestions on what else I should look into?

**Comment by JackCaoG** [comment]
@Krovatkin any thoughts regarding xiongfei's comments? It seems like 
https://github.com/pytorch/xla/blob/0daf6fe975fea345bc66e92e6121105eb7ed259c/torch_xla/csrc/torch_util.cpp#L17-L18
has some issue.
Given that CPP test works, my guess is we didn't pass the correct symint node somewhere in python.

**Comment by Krovatkin** [comment]
I assume we should support the usage t4=t3.expand(t2.size(0), size1, size2), right?

I believe this should've worked. We have a very similar test in pytorch core: 

https://github.com/pytorch/pytorch/blob/master/test/test_dynamic_shapes.py#L246

**Comment by JackCaoG** [comment]
hmm, any debugging tips? like where to add debugging messages?

**Comment by Krovatkin** [comment]
@JackCaoG  https://github.com/pytorch/xla/pull/4212

**Comment by miladm** [comment]
Is this issue still relevant? If not, can you please add relevant details to follow up on how this has been resolved?

@vanbasten23

**Comment by vanbasten23** [comment]
So there are 2 issues in this thread:
1) In the first comment (https://github.com/pytorch/xla/issues/4202#issue-1449177496), the script failed with a segfault. Nick has fixed this problem in his [PR](https://github.com/pytorch/xla/pull/4212).
2) In the test I posted in this [comment](https://github.com/pytorch/xla/issues/4202#issuecomment-1316165565) within this GH issue, the test failed with `RuntimeError: SymIntArrayRef expected to contain only concrete integers`. I have a PR for it.

2) is the remaining issue to be solved. Thus, we can't close this issue yet.

**Comment by vanbasten23** [comment]
2) has been resolved with pr https://github.com/pytorch/xla/pull/4291. So close this issue.
