### ISSUE TITLE
Behavior of `F.linear` differs between vanilla Pytorch and XLA/CPU

### ISSUE THREAD

**Issue by pscollins** [pytorch/xla#4234]
## 🐛 Bug

I hit a `RuntimeError` when trying to port an [existing model](https://github.com/facebookresearch/unbiased-teacher-v2) to XLA. I'm running against a locally-built copy of pytorch/XLA using XLA-CPU.

## To Reproduce

```
In [1]: import torch

In [2]: import torch.nn.functional as F

In [3]: F.linear(torch.ones([54400, 17]), torch.ones([17]))
Out[3]: tensor([17., 17., 17.,  ..., 17., 17., 17.])

In [4]: import torch_xla

In [5]: import torch_xla.core.xla_model as xm

In [6]: device = xm.xla_device()

In [7]: F.linear(torch.ones([54400, 17], device=device), torch.ones([17], device=device))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [7], line 1
----> 1 F.linear(torch.ones([54400, 17], device=device), torch.ones([17], device=device))

RuntimeError: Value out of range (expected to be in range of [-1, 0], but got 1)
```

See snippet above

## Expected behavior

Behavior should match between vanilla pytorch and pytorch/XLA (either throw an exception in both cases or don't throw an exception in both cases).

## Environment

 - Reproducible on XLA backend [CPU/TPU]: CPU, did not try TPU
 - torch_xla version: I built torch_xla from HEAD using the "build from source" workflow described in CONTRIBUTING.md around 11/20, `torch_xla/version.py` shows:
```
# Autogenerated file, do not edit!
__version__ = '1.14'
__xla_gitrev__ = 'f790bc8ac411a8e6903b89adf7610b812996537b'
__torch_gitrev__ = '7b0d577c226fae78f377b26feab4122c4203ad59'
```

**Comment by JackCaoG** [comment]
@Liyang90 Do you have cycle to take a look at this one?

**Comment by Liyang90** [comment]
Hi,

I can confirm the issue.
According to [torch.nn.functional.linear](https://pytorch.org/docs/stable/generated/torch.nn.functional.linear.html)
The second argument `weight` can be 2D or 1D: "Weight: (out\_features, in\_features) or (in\_features)", but in PyTorch/XLA, the `weight` can only be 2D. If a 1D tensor is passed in, this error will happen.

@JackCaoG Should we update the implementation to match PyTorch's `torch.nn.functional.linear` behavior?

**Comment by JackCaoG** [comment]
yea, let me see if I can quickly fix this issue(assuming we just forgot about this corner case and it is not a limitation).

**Comment by JackCaoG** [comment]
seems like issue coming from we are trying to transpose a 1d tensor
```
2735│ at::Tensor XLANativeFunctions::t(const at::Tensor& self) {
2736│   XLA_FN_COUNTER("xla::");
2737│   return bridge::AtenFromXlaTensor(
2738├>      XLATensor::transpose(bridge::GetXlaTensor(self), 0, 1));
2739│ }
```

```
(gdb) p self.sizes()
$7 = {Data = 0x55555b487d60, Length = 1}
```

**Comment by JackCaoG** [comment]
```
>>> t1 = torch.ones([17])
>>> t1.t_
<built-in method t_ of Tensor object at 0x7f390b14de30>
>>> t1.t_()
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
```
I guess I will just make it a no-op if it is 1d.
