### ISSUE TITLE
Pytorch-xla not working on GPU

### ISSUE THREAD

**Issue by ghassenBtb** [pytorch/xla#4241]
## To Reproduce

I got an error when running this script

`import os`
`import torch_xla.distributed.xla_multiprocessing as mp`
`import torch`
`import torch_xla`
`num_gpus=1`
`os.environ["XRT_WORKERS"]="localservice:0;grpc://localhost:51011"`
`os.environ["GPU_NUM_DEVICES"] = str(num_gpus)`
`print(torch_xla.core.xla_model.get_xla_supported_devices('GPU'))`
`device=torch_xla.core.xla_model.xla_device()`
`print(device)`
`t = torch.randn(2, 2, device=torch_xla.core.xla_model.xla_device())`

The error is the following <br>
`
  2022-11-23 17:42:42.520099: F tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:479] Non-OK-status: session->session()->Run(session_work->feed_inputs, session_work->outputs_handles, &outputs) status: INVALID_ARGUMENT: Cannot assign a device for operation XRTAllocateFromTensor: {{node XRTAllocateFromTensor}} was explicitly assigned to /job:localservice/replica:0/task:0/device:XLA_GPU:0 but available devices are [ /job:localservice/replica:0/task:0/device:CPU:0, /job:localservice/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device.
           [[XRTAllocateFromTensor]]
  *** Begin stack trace ***
          tsl::CurrentStackTrace()
         xla::util::MultiWait::Complete(std::function<void ()> const&)
         clone
  *** End stack trace ***
  Aborted (core dumped)
`

## Environment
I ran the script on a linux virtual machine with A100 GPUs.
I installed pytorch using these wheels:
`torch-1.13.0+cu116-cp38-cp38-linux_x86_64.whl`
`torchvision-0.14.0+cu116-cp38-cp38-linux_x86_64.whl`
`torch_xla-1.13-cp38-cp38-linux_x86_64.whl`

## Additional context
I also tried with these environment variables without success:
`os.environ['XRT_SHARD_WORLD_SIZE'] = '1'`

`os.environ['XRT_HOST_ORDINAL'] = '0'`

`os.environ['FI_EFA_USE_DEVICE_RDMA'] = '1'`

`os.environ['NCCL_PROTO'] =  'simple'`

`os.environ['XLA_FIX_DIV_FP64']** = '1'`

`os.environ['OFI_NCCL_NIC_DUP_CONNS'] = str(num_gpus)`

`os.environ["XRT_DEVICE_MAP"]="CPU:0;/job:localservice/replica:0/task:0/device:XLA_CPU:0|GPU:0;/job:localservice/replica:0/task:0/device:XLA_GPU:0|GPU:1;/job:localservice/replica:0/task:0/device:XLA_GPU:1|GPU:2;/job:localservice/replica:0/task:0/device:XLA_GPU:2|GPU:3;/job:localservice/replica:0/task:0/device:XLA_GPU:3"`

**Comment by JackCaoG** [comment]
we usually recommend user to use our prebuild gpu dockers, can you try one of the dokcers mentioned in [here](https://github.com/pytorch/xla#-available-images-and-wheels) that is `Cloud compute instances with GPUs`?  Last I tried it I used
```
sudo docker pull gcr.io/tpu-pytorch/xla:nightly_3.7_cuda_11.2
sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent    software-properties-common
nvidia-smi
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
sudo systemctl restart docker
sudo docker run --gpus all -it -d gcr.io/tpu-pytorch/xla:nightly_3.7_cuda_11.2 bin/bash
sudo docker exec -it $(sudo docker ps | awk 'NR==2 { print $1 }') /bin/bash
```

within the docker I just did
```
export GPU_NUM_DEVICES=4
python pytorch/xla/test/test_train_mp_imagenet.py --fake_data    
```

`torch_xla-1.13-cp38-cp38-linux_x86_64.whl` was not compiled with GPU support.

**Comment by ghassenBtb** [comment]
Thank you for your quick response.
I'am looking for a wheel compiled with GPU support which runs on python 3.8.
I only found these wheels: **cuda/112/torch_xla-1.13-cp37-cp37m-linux_x86_64.whl** which only runs on python 3.7.

Are there wheels compiled with GPU support which runs on python 3.8 ?

**Comment by JackCaoG** [comment]
we currently does not have 3.8 wheel, I will try to setup a trigger and see if we can build such wheels.

**Comment by JackCaoG** [comment]
The build passed, I also setup the recurrent builds. You can use
```
gs://tpu-pytorch/wheels/cuda/112/torch-nightly-cp38-cp38-linux_x86_64.whl
gs://tpu-pytorch/wheels/cuda/112/torch_xla-nightly-cp38-cp38-linux_x86_64.whl
```
