### ISSUE TITLE
Access to XLA/HLO Graph

### ISSUE THREAD

**Issue by chrisby** [pytorch/xla#4268]
## ❓ Questions and Help
I was wondering how to best access the XLA/HLO graph. I'd like to visualize it and compare it to the original computation graph.

**Comment by wonjoolee95** [comment]
You can do `print(torch_xla._XLAC._get_xla_tensors_hlo([t]))` to dump the HLO in your python program, where `t` is the tensor.

**Comment by chrisby** [comment]
That works for individual tensors, but how would I get the graph for a complete (small) model?

**Comment by alanwaketan** [comment]
Here are some tools you can use.
For hlo, try:
```
alias save_hlo="XLA_SAVE_TENSORS_FMT='hlo' XLA_SAVE_TENSORS_FILE='/tmp/save1.hlo'"
```
For lazy IR, try:
```
alias save_ir="XLA_SAVE_TENSORS_FMT='text' XLA_SAVE_TENSORS_FILE='/tmp/save1.ir'"
```

**Comment by chrisby** [comment]
Thank you! For jupyter notebooks, I also found the graph representation quite useful:

```
from graphviz import Source

# This is just a simple X * Y + Z example.
x = torch.tensor([[1,2,2,1], [3,4,4,3], [5,6,6,5]], device=device)
y = torch.tensor([[5,6,6,5], [3,4,4,3], [1,2,2,1]], device=device)
z = torch.tensor([[5,6,6,5], [3,4,4,3], [1,2,2,1]], device=device)

s = Source(torch_xla._XLAC._get_xla_tensors_dot([x * y + z]), filename='test', format='png')
s
```

This will render the HLO graph in the notebook.

**Comment by mitkotak** [comment]
Hey sorry for reopening this. Was wondering how I can get access to post-fused HLO. For example in JAX, I am able to do

```
from graphviz import Source
from IPython.display import Image
from jaxlib import xla_client


def todotgraph(x):
   return xla_client._xla.hlo_module_to_dot_graph(xla_client._xla.hlo_module_from_text(x))


with open("fused.dot", "w") as file2:
    file2.write(todotgraph(jax.jit(torch.matmul).lower(x, y).compile().as_text()))
s = Source.from_file("fused.dot")
png_bytes = s.pipe(format='png')
Image(png_bytes)
```

**Comment by JackCaoG** [comment]
try to run your code with `XLA_FLAGS=--xla_dump_to=/tmp/xla_dump`, it will then dump HLOs at all stages(post-compilation, post-buffer-assigniment etc)

**Comment by mitkotak** [comment]
Gotcha any way for me to stitch everything together into a big DAG ?

**Comment by JackCaoG** [comment]
That we don't have an easy way to dump, I can leave this as a todo. I usually use the profiler to visualize the dot graph, check https://youtu.be/40jYVhQHGEA?si=kUceFstPm8Pipxqu&t=2076
