### ISSUE TITLE
Why does XMP.spawn have default start_method = "spawn" - relationship to DataLoader num_workers?

### ISSUE THREAD

**Issue by siddk** [pytorch/xla#4272]
## ❓ Questions and Help
Hi folks! I'm running into some trouble with OOMs on GCP TPU VM instances (v3-8; tpu-vm-pt-1.11). In my PyTorch Dataset class, I'm loading a rather large JSON file (2 GB) containing metadata and paths to images on local disk, which are then loaded via `__getitem__()`. To train efficiently across the 8 TPU cores, I'm setting `num_workers=8` in my DataLoader.

When using the default `xmp.spawn()` in my `mp_fn()` I'm seeing that the memory is growing linearly with `num_workers` – even though normally, on Linux systems, PyTorch's DataLoaders should be `forking` and sharing the copy of the loaded file (since it's loaded in the Dataset `__init__()`). This ends up causing an OOM, crashing the VM (and sometimes forcing the node into an unrecoverable state).

Is there a good fix here? I'm guessing there's a good reason why the start_method for PyTorch XLA is `spawn` instead of `fork`; how should I be loading data to minimize memory usage?

**Comment by JackCaoG** [comment]
@will-cromar can you take this one?

**Comment by will-cromar** [comment]
This default was set well before my time on this team, but my best guess is that we were mirroring the default start method in the [PyTorch implementation of `mp.spawn`](https://pytorch.org/docs/stable/multiprocessing.html). Does setting [`start_method='fork'`](https://github.com/pytorch/xla/blob/f2c87eec1dee2b59739d5553a2920dca47068482/torch_xla/distributed/xla_multiprocessing.py#L362) solve your OOM?

@JackCaoG are you aware of any specific reason to prefer `spawn` over `fork`?

**Comment by siddk** [comment]
Using `fork` does seem to help, but I'm encountering weird memory leaks... every so often, my runs crash with some weird TPU message (or just completely bring the `v3-8` down, in an unrecoverable state). Probably need to investigate this more, but it's probably something to do with the size of the files I'm working with + cleanup at the end of each epoch.

**Comment by alanwaketan** [comment]
@will-cromar LMK if I wrongly assigned this to you.
