### ISSUE TITLE
[Functionalization] test_advancedindex_mixed_cpu_devices_xla

### ISSUE THREAD

**Issue by wonjoolee95** [pytorch/xla#4349]
Running `python test/test_torch.py TestTorchDeviceTypeXLA.test_cdist_empty_xla` fails with
```
RuntimeError: sym_strides() called on an undefined Tensor
```

**Comment by alanwaketan** [comment]
Is this fixed already?

**Comment by wonjoolee95** [comment]
This is fixed with the `null` tensor check and is now enabled as of https://github.com/pytorch/xla/pull/4158/commits/186eba104ff8ed949fe3b14536be17ecf307aa60.
