### ISSUE TITLE
[Functionalization] test_copy_noncontig_xla

### ISSUE THREAD

**Issue by wonjoolee95** [pytorch/xla#4350]
Running `python test/test_torch.py TestTorchDeviceTypeXLA.test_copy_noncontig_xla` fails with
```
RuntimeError: false INTERNAL ASSERT FAILED at "/workspace/pytorch/build/aten/src/ATen/RegisterFunctionalization_0.cpp":3547, please report a bug to PyTorch. mutating a non-functional tensor with a functional tensor is not allowed. Please ensure that all of your inputs are wrapped inside of a functionalize() call.
```

**Comment by alanwaketan** [comment]
Is this fixed already?

**Comment by wonjoolee95** [comment]
It is fixed but requires some changes to the original Brian's PR. I've described the changes at https://github.com/pytorch/pytorch/pull/91001/files#r1052494781. I just wanted to double check with Brian before closing this issue.

**Comment by wonjoolee95** [comment]
This is fixed, closing this.
