### ISSUE TITLE
MpDeviceLoader has a bug in fp16 for model swin_transformer

### ISSUE THREAD

**Issue by Suparjie** [pytorch/xla#4407]
## 🐛 Bug

When I use MpDeviceLoader in FP16 or AMP, model swin_transformer getting data from MpDeviceLoader meets errors sometimes. Data will change and nan is in data.

## To Reproduce
code script:
`
import os
os.environ['GPU_NUM_DEVICES']='1'
os.environ['XLA_USE_FP16'] = '1'
import sys

FLAGS = {}

import torch
import torch.nn as nn
import torch.optim as optim
import torch_xla.distributed.parallel_loader as pl
import torch_xla.core.xla_model as xm
import torch_xla.distributed.xla_multiprocessing as xmp

from torchvision.models.swin_transformer import swin_t

from torch.utils.data import IterableDataset
class FakeDataset(IterableDataset):
    def __init__(self, img_dim):
        super().__init__()
        self.input = torch.randn(3, img_dim, img_dim)
        self.target = torch.zeros(1, dtype=torch.int64)

    def __len__(self):
        return 100000
    def __iter__(self):
        def table_data_iterator():
            while True:
                input = self.input
                target = self.target
                yield (input, target)
        return table_data_iterator()

def collate_fn(batch):
    input = []
    target = []
    for data in batch:
        input.append(data[0])
        target.append(data[1])
    input = torch.stack(input, dim=0)
    target = torch.cat(target)
    return (input, target)

def train():
    print('==> Preparing data..')
    img_dim = 224
    train_dataset = FakeDataset(img_dim)
    train_loader = torch.utils.data.DataLoader(train_dataset,sampler=None,batch_size=40,
    pin_memory=False,drop_last=True,shuffle=False,num_workers=1,
    persistent_workers=False,collate_fn=collate_fn,
    )

    torch.manual_seed(1)

    device = xm.xla_device()
    model = swin_t()
    model = model.to(device)

    optim_cls = optim.SGD
    optimizer = optim_cls(model.parameters(),lr=0.0001, weight_decay=1e-4)
    loss_fn = nn.CrossEntropyLoss()

    def train_loop_fn(loader):
        model.train()
        for step, (input, target) in enumerate(loader):
            for i, (name, parameters) in enumerate(model.named_parameters()):
                if torch.isnan(parameters).any():
                    print('para: ', name, 'has nan', parameters)
                    break
            if torch.isnan(input).any():
                print('data nan: ', input)
                return
            optimizer.zero_grad()
            output = model(input)
            loss = loss_fn(output, target)
            print('step: ', step, 'loss: ', loss)
            loss.backward()
            xm.optimizer_step(optimizer)

    train_device_loader = pl.MpDeviceLoader(train_loader, device)
    train_loop_fn(train_device_loader)

def _mp_fn(index, flags):
  global FLAGS
  FLAGS = flags
  torch.set_default_tensor_type('torch.FloatTensor')
  train()

if __name__ == '__main__':
  xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=1)

`

## Steps to reproduce the behavior:

1. run up script

## Expected behavior
It happens data nan after several steps.
![image](https://user-images.githubusercontent.com/29849035/210478738-5309b270-bf00-4120-8958-f94f07fc01fb.png)

## Environment

 - Reproducible on XLA backend [CPU/TPU]:
 - torch_xla version: 1.11
 - torchvision: 0.13.1
 - torch : 1.11.0
 - gpu: nvidia Tesla V100
 - Cuda 11.2

**Comment by JackCaoG** [comment]
Thanks for raising the issue, it seems like it is pure data loading and doesn't even involve the computation is that correct? If you can refactor the actual training code out and can still observe the same error that would be easier for us to root cause the issue.

**Comment by Suparjie** [comment]
> Thanks for raising the issue, it seems like it is pure data loading and doesn't even involve the computation is that correct? If you can refactor the actual training code out and can still observe the same error that would be easier for us to root cause the issue.

Yes, it's the MpDeviceLoader error, you can use the code script to reproduce the error.

**Comment by JackCaoG** [comment]
The above code is a bit weird, it is single process but you used the `xmp.spawn` API which is for multi device, I tried to simplify above code to 
```
import os
os.environ['XLA_USE_FP16'] = '1'

import torch
import torch.nn as nn
import torch.optim as optim
import torch_xla.distributed.parallel_loader as pl
import torch_xla.core.xla_model as xm

from torch.utils.data import IterableDataset


class FakeDataset(IterableDataset):
    def init(self, img_dim):
        super().init()
        self.input = torch.randn(3, img_dim, img_dim)
        self.target = torch.zeros(1, dtype=torch.int64)

    def __len__(self):
        return 100000

    def __iter__(self):
        def table_data_iterator():
            while True:
                input = self.input
                target = self.target
                yield (input, target)

        return table_data_iterator()


img_dim = 224
import pdb
pdb.set_trace()
train_dataset = FakeDataset(img_dim)
train_loader = torch.utils.data.DataLoader(
    train_dataset,
    sampler=None,
    batch_size=40,
    pin_memory=False,
    drop_last=True,
    shuffle=False,
    num_workers=1,
    persistent_workers=False,
    collate_fn=collate_fn,
)

torch.manual_seed(1)
device = xm.xla_device()

train_device_loader = pl.MpDeviceLoader(train_loader, device)

for step, (input, target) in enumerate(train_device_loader):
    if torch.isnan(input).any():
        print('data nan: ', input)
    else:
        print('ok')
```

but it failed with
```
Traceback (most recent call last):
  File "/tmp/test_loader.py", line 35, in <module>
    train_dataset = FakeDataset(img_dim)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/typing.py", line 821, in __new__
    obj = super().__new__(cls, *args, **kwds)
TypeError: object.__new__() takes exactly one argument (the type to instantiate)
```

I am not sure if this has anything to do with loader, because the input data are just fake datas with `torch.randn(3, img_dim, img_dim)`. Maybe what you want to check is if calling `torch.randn(3, img_dim, img_dim)` 10000 times, whether it will generate nan(which would be really weird). Can you clean up the repo with minmal repo code?


@miladm Rolling over to offcall, maybe we should find a owner from modeling side?

**Comment by Suparjie** [comment]
> 

`
import os
os.environ['GPU_NUM_DEVICES']='1'
os.environ['XLA_USE_FP16'] = '1'
import sys

import torch
import torch.nn as nn
import torch.optim as optim
import torch_xla.distributed.parallel_loader as pl
import torch_xla.core.xla_model as xm


from torchvision.models.swin_transformer import swin_t

from torch.utils.data import IterableDataset
class FakeDataset(IterableDataset):
    def __init__(self, img_dim):
        super().__init__()
        self.input = torch.randn(3, img_dim, img_dim)
        self.target = torch.zeros(1, dtype=torch.int64)

    def __len__(self):
        return 100000
    def __iter__(self):
        def table_data_iterator():
            while True:
                input = self.input
                target = self.target
                yield (input, target)
        return table_data_iterator()

def collate_fn(batch):
    input = []
    target = []
    for data in batch:
        input.append(data[0])
        target.append(data[1])
    input = torch.stack(input, dim=0)
    target = torch.cat(target)
    return (input, target)

def train():
    print('==> Preparing data..')
    img_dim = 224
    train_dataset = FakeDataset(img_dim)
    train_loader = torch.utils.data.DataLoader(train_dataset,sampler=None,batch_size=40,
    pin_memory=False,drop_last=True,shuffle=False,num_workers=1,
    persistent_workers=False,collate_fn=collate_fn,
    )

    torch.manual_seed(1)

    device = xm.xla_device()
    model = swin_t()
    model = model.to(device)

    optim_cls = optim.SGD
    optimizer = optim_cls(model.parameters(),lr=0.0001, weight_decay=1e-4)
    loss_fn = nn.CrossEntropyLoss()

    def train_loop_fn(loader):
        model.train()
        for step, (input, target) in enumerate(loader):
            for i, (name, parameters) in enumerate(model.named_parameters()):
                if torch.isnan(parameters).any():
                    print('para: ', name, 'has nan', parameters)
                    break
            if torch.isnan(input).any():
                print('data nan: ', input)
                return
            optimizer.zero_grad()
            output = model(input)
            loss = loss_fn(output, target)
            print('step: ', step, 'loss: ', loss)
            loss.backward()
            xm.optimizer_step(optimizer)

    train_device_loader = pl.MpDeviceLoader(train_loader, device)
    train_loop_fn(train_device_loader)

if __name__ == '__main__':
    torch.set_default_tensor_type('torch.FloatTensor')
    train()

`

**Comment by Suparjie** [comment]
@JackCaoG Do you have any progress?

**Comment by JackCaoG** [comment]
rolling over to on duty

**Comment by Suparjie** [comment]
>

**Comment by Suparjie** [comment]
> rolling over to on duty

I found it if you add mark_step before optimizer, the error will disapper, just like the coke below:
```
loss.backward()
xm.mark_step()
xm.optimizer_step(optimizer)
```
