### ISSUE TITLE
Master branch unit test TestDynamicShape.test_nonzero_cast is failing

### ISSUE THREAD

**Issue by vanbasten23** [pytorch/xla#4501]
## 🐛 Bug

Master branch unit test TestDynamicShape.test_nonzero_cast is failing. See CI [result](https://app.circleci.com/pipelines/github/pytorch/xla/15909/workflows/b32c857d-9169-4f2e-bcff-30db385bd327/jobs/37481). Failure is:
```
ERROR: test_nonzero_cast (__main__.TestDynamicShape)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pytorch/xla/test/test_operations.py", line 757, in test_nonzero_cast
    t2 = torch.nonzero(t1.int()).float()
RuntimeError: /tmp/pytorch/xla/torch_xla/csrc/aten_xla_type.cpp:1132: SymIntArrayRef expected to contain only concrete integers
```

Per the error message, the error really looks the one I got when I enabled functionalization.
@JackCaoG , do you know how to check if functionalization is enabled?

## To Reproduce

XLA_EXPERIMENTAL="nonzero:masked_select:masked_scatter" python pytorch/xla/test/test_operations.py TestDynamicShape.test_nonzero_cast

## Expected behavior

The test should succeed.

## Environment

 - Reproducible on XLA backend [CPU/TPU]: xla::CPU
 - torch_xla version: nightly.

**Comment by JackCaoG** [comment]
hmm, I don't think functionalization is enabled on master.

**Comment by ManfeiBai** [comment]
after rebase with https://github.com/pytorch/xla/pull/4502,
AtenXlaTensorTest.TestNonzero failed and has PR https://github.com/pytorch/xla/pull/4510 to disable it

**Comment by vanbasten23** [comment]
CPP test also failed. To repro: `./pytorch/xla/test/cpp/build/test_ptxla --gtest_filter=AtenXlaTensorTest.TestNonzero`. Currently, it failed with https://paste.googleplex.com/6362827630575616

**Comment by vanbasten23** [comment]
reenabled all the mentioned test by https://github.com/pytorch/xla/pull/4581
