### ISSUE TITLE
Ops needed to support dynamism

### ISSUE THREAD

**Issue by vanbasten23** [pytorch/xla#4624]
## All ops needed in backward pass model

This issue recorded all ops used in the backward pass NN model and it will help us track the progress.

- [ ] xla::_propagate_xla_data
- [ ] xla::add
- [ ] xla::binary_cross_entropy_backward
- [ ] xla::fill_
- [ ] xla::mm
- [ ] xla::sigmoid_backward
- [ ] xla::sum
- [ ] xla::threshold_backward
- [x] xla::unsqueeze_copy https://github.com/pytorch/xla/pull/4608
- [x] xla::view_copy_symint
- [x] xla::t_copy https://github.com/pytorch/xla/pull/4606

The ops are obtained from `met.metrics_report()`

cc @miladm @JackCaoG @alanwaketan

**Comment by miladm** [comment]
@vanbasten23 is this issue complete?

We discussed opening a similar issue for RoIAlign. Where can I find that issue with the list of its ops?

**Comment by vanbasten23** [comment]
> @vanbasten23 is this issue ready to close? I know dynamism works on the backward pass now.
> 
> We discussed opening a similar issue for RoIAlign. Where can I find that issue with the list of its ops?

Yeah we can close this one now. The RoIAlign ops are documented here https://github.com/pytorch/xla/issues/4707
