### ISSUE TITLE
What's the desired behavior of `view` with dynamic shape when the input tensor is dynamic but the input shape is static?

### ISSUE THREAD

**Issue by vanbasten23** [pytorch/xla#4668]
What's the desired behavior of `view` with dynamic shape when the input tensor is dynamic but the input shape is static?

Let's consider this case:
```
t3 = t2.view(t1.shape)
```

in which t2 has dynamic size [<=6, 1] with real size [6, 1], t1.shape is [2, 3]. After reading the design doc, I'm still not clear about the desired behavior of `view`. Per pytorch official doc for [view](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html), this op `Returns a new tensor with the same data as the self tensor but of a different shape.`. So I expect t3 has the same shape as the input shape [2, 3] and no dynamic shape will be propagated. According the design doc, we should still propagate the dynamism. Also according to the current implementation [GetDynamicReshapeInfo](https://github.com/pytorch/xla/blob/1d313bb08ade4240ffd5ac8d6775264cfddacfa7/torch_xla/csrc/helpers.cpp#L255-L289), our code currently would infer the output shape to be [2, <=3]. Just want to check with you what the desired output shape is. 
@miladm @JackCaoG

**Comment by JackCaoG** [comment]
Will this ever happens in the real model code? The dynamism comes from ops like `non_zero`, however when it is very unlikely for user to do 
```
t1 = torch.non_zero(t0)
t1.view(2,3)
```
since there is no way for user to know the t1's shape. If this is not a real use case we can just error out.

**Comment by miladm** [comment]
It is impossible to know whether or not `t1` has the valid/compatible shape for the true content of `t1` without materializing `t2`. In other words, anecdotally, a `view` op behaves in a conditional way: _if_ the _true_ shape of `t1` is compatible with that of `t2`, let's apply a `view`. Given the conditional nature of this operation, it's fair to say when `t2` is dynamic, `t2` must materialize. I'd say the same argument applies to `reshape`

Having said that, I can't think of an application for the user to call `view` on a dynamic tensor. As such, I agree with @JackCaoG that we throw an error for this use case saying "this behavior is unexpected; if the user believes this must be supported, please file a bug against pt/xla for improving support"

CC @JackCaoG @will-cromar for comments.
