### ISSUE TITLE
Only provide GPU Wheels with cuda112 currently

### ISSUE THREAD

**Issue by qipengh** [pytorch/xla#4704]
## ❓ Questions and Help
Pytorch/xla only provide GPU Wheels for cuda112 currently，but I can't found wheel of torch with cuda112 in https://download.pytorch.org/whl/torch_stable.html . And in https://download.pytorch.org/whl/nightly/ , nightly wheel of torch is based on cuda113+.

So will we consider providing wheels with higher cuda versions? In order to be consistent with torch.

**Comment by JackCaoG** [comment]
We actually have cuda 117 and 118 wheel for nightly now, try
```
https://storage.googleapis.com/tpu-pytorch/wheels/cuda/117/torch_xla-nightly-cp38-cp38-linux_x86_64.whl
https://storage.googleapis.com/tpu-pytorch/wheels/cuda/118/torch_xla-nightly-cp38-cp38-linux_x86_64.whl
```

we will update the doc.

**Comment by qipengh** [comment]
It's great, thanks.
