### ISSUE TITLE
All ops involved in RoIAlign

### ISSUE THREAD

**Issue by vanbasten23** [pytorch/xla#4707]
This issues lists all ops involved in RoIAlign. We need to make them support dynamism. We need to test them to make sure they support dynamism.

They come from the test in this pr https://github.com/pytorch/xla/pull/4703. Both forward/backward tests run to completion so I could generate our metrics and extracts all ops involved.

## Forward RoIAlign

- [ ] xla::_copy_from
- [ ] xla::_propagate_xla_data
- [ ] xla::_to_copy
- [ ] xla::_to_cpu
- [x] xla::clone
- [x] xla::empty_symint
- [x] xla::lift_fresh
   Couldn't find the documentation of it. Per our code, it seems it convert a tensor to its functional version of it. Not sure if it can be tested though as `t3 = torch.lift(t2)` results in `AttributeError: module 'torch' has no attribute 'lift'`.
- [x] xla::uniform_
   `Tensor.uniform_(from=0, to=1) → [Tensor]`. It fills self tensor with numbers sampled from the continuous uniform distribution: p(x) = 1/(to-from). So dynamism shouldn't be involved.

## Backward RoIAlign

- [ ] xla::_copy_from
- [ ] xla::_propagate_xla_data
- [ ] xla::_to_copy
- [ ] xla::_to_cpu
- [x] xla::abs
- [ ] xla::add
- [x] xla::all
   - `all` tests if all elements in `input` evaluate to True. So the shape of the result is `torch.Size([])`.  So we should be good for this op.
- [ ] xla::bitwise_and
- [ ] xla::bitwise_or
- [x] xla::clone
- [ ] xla::copy
- [ ] xla::detach_copy
- [ ] xla::div
- [x] xla::empty_symint
- [ ] xla::eq
- [ ] xla::fill_
- [ ] xla::gt
- [ ] xla::le
- [x] xla::lift_fresh
- [ ] xla::max
- [ ] xla::mul
- [ ] xla::ne
- [ ] xla::select_copy
- [ ] xla::select_scatter
- [ ] xla::slice_copy
- [ ] xla::slice_scatter
- [ ] xla::sub
- [ ] xla::uniform_
- [x] xla::view_copy_symint
- [ ] xla::zero_

cc @miladm @JackCaoG

**Comment by vanbasten23** [comment]
Hi @ymwangg , I'd like to reach out to you and introduce myself. I'm Xiongfei from PyTorch/XLA team and I'm working on dynamic shape project. Thanks for your contribution to this project.

To better collaborate, my team is currently working on RoIAlign and this Github issue contains all ops involved in it. Furthermore, we have [a list of ops](https://github.com/pytorch/xla/issues/4756) that we may need to support dynamic shape. For the ones that we have implemented and tested, I have added a check mark. For the ops that we are or will be working on next, I'll add a `WIP` just so we don't have to work on the same op simultaneously. Feel free to update it so that we are on the same page.

I look forward to working with you.

cc @miladm @JackCaoG

**Comment by ymwangg** [comment]
@vanbasten23 Sounds good! Thanks for reaching out Xiongfei. I'm currently trying to figure out how to make FCOS model work and will cc you anything I find interesting.

**Comment by miladm** [comment]
@ymwangg thanks for the update! 

Do you mind sharing which one of the ops from the above list are required for FCOS model to work (if any)? The idea is to understand where the overlaps are for collaboration at the op-level granularity. Thanks!!

**Comment by ymwangg** [comment]
@miladm FCOS does not use RoIAlign and it's simpler than mask-rcnn. The last time when I test this model, all ops seem to work except xla::nms. For the next stage, I'll mainly focus on resolving integration related issues.

Below is the list of ops used in the forward pass of FCOS.
```
xla::nonzero
torchvision::nms
xla::_copy_from
xla::_propagate_xla_data
xla::_to_copy
xla::_to_cpu
xla::add
xla::addcmul
xla::arange_out
xla::cat
xla::clamp
xla::convolution_overrideable
xla::copy
xla::detach_copy
xla::div
xla::empty_symint
xla::expand_copy_symint
xla::fill_
xla::gt
xla::index
xla::lift_fresh
xla::max
xla::max_pool2d
xla::mul
xla::native_batch_norm
xla::nonzero
xla::permute_copy
xla::relu
xla::remainder
xla::rsqrt
xla::select_copy
xla::select_scatter
xla::sigmoid
xla::slice_copy
xla::slice_scatter
xla::split_with_sizes_copy
xla::sqrt
xla::stack
xla::sub
xla::topk_symint
xla::unbind_copy
xla::unsqueeze_copy
xla::upsample_bilinear2d
xla::upsample_nearest2d
xla::view_copy_symint
```

**Comment by miladm** [comment]
Awesome! thanks for sharing.
+ did you also try the backward pass of FCOS? I expect additional ops to emerge.
+ sounds like the listed ops here should work out of the box. Perhaps we can cross them off as "supported"

**Comment by miladm** [comment]
@vanbasten23, FYI: FPN and NMS are shared between FCOS and Mask-RCNN ([reference](https://learnopencv.com/fcos-anchor-free-object-detection-explained/))

**Comment by ymwangg** [comment]
@miladm I haven't started testing the backward pass as there are new errors after rebasing but will share the results here once it's done.
