### ISSUE TITLE
[RFC] Supporting CPU fallback for the dynamo-xla bridge

### ISSUE THREAD

**Issue by wonjoolee95** [pytorch/xla#4742]
## 🚀 Feature

We propose PyTorch/XLA to leverage `CapabilityBasedPartitioner` from `torch.fx.passes.infra.partitioner` to support CPU fallback for the dynamo-xla bridge. The `CapabilityBasedPartitioner` a tool in torch.fx to partition the FX graph into "backend" parts, given a list of supported operators. The partitioner tries to form the largest subgraphs that only contain the supported ops.

## Motivation

In the current dynamo-xla integration, the dynamo bridge passes down a fx module and expects the backend to return a single function/hash representing the whole model. However, in the cases of that fx model containing the ops that PyTorch/XLA does not support, PyTorch/XLA will fallback at unsupported ops and generate more than one graph. In such cases, the current `torch_xla_bridge` will crash. 

This issue was originally tracked in an upstream issue [feature request](https://github.com/pytorch/torchdynamo/issues/1823). 

## Pitch

In order to support CPU fallback for the dynamo-xla bridge, we propose PyTorch/XLA to leverage `CapabilityBasedPartitioner` from `torch.fx.passes.infra.partitioner`. The `CapabilityBasedPartitioner` a tool in torch.fx to partition the FX graph into "backend" parts given a list of supported operators. This partitioner tries to forms the largest subgraphs that only contain the supported ops. 

Currently, other backends such as `nvFuser` and `onnxruntimer` leverage `CapabilityBasedPartitioner` to achieve a similar use case. 

### CapabilityBasedPartitioner

Example usage of `CapabilityBasedPartitioner` is shown below. First, we need to initialize `CapabilityBasedPartitioner` with the FX graph module and a list of supports ops. Then we can call the partitioner's `partition_and_fuse()` method to produce the `fused_graph_module`.
```
partitioner = CapabilityBasedPartitioner(graph_module, self.supported_ops)
fused_graph_module = partitioner.partition_and_fuse()
```
Now, we need to override fused_module's `__call__()` function with our custom backend function. This looks like: 
```
for node in fused_graph_module.graph.nodes:
    # Identify fused submodule
    if "fused_" in node.name:
        fused_module = getattr(fused_graph_module, node.name)
        fused_module._wrapped_call = my_backend_function
```

The `supported_ops` is provided by overriding the `torch.fx.passes.operator_support.OperatorSupport` class to provide a string dictionary of supported ops and overriding the `OperatorSupport.is_node_supported` function. Example of usage is shown below:
```
class MyOperatorSupport(OperatorSupport):
    def __init__(self):
        support_dict = {
            # List of supports ops
            "torch.ops.aten.add": None,
            "torch.ops.aten.sub": None,
        }

        super().__init__(support_dict)

    def is_node_supported(
        self, submodules: t.Mapping[str, Module], node: Node
    ) -> bool:

        # The FX subgraph should be purely functional
        if node.op not in CALLABLE_NODE_OPS:
            return False

        # ops in supported_dict doesn't have overload name
        # use overloadpacket's qualified_name for OpOverload
        if isinstance(node.target, OpOverload):
            target = _get_qualified_name(node.target.overloadpacket)
            if target in self._support_dict:
                return True

        return super().is_node_supported(submodules, node)
```

## Caveats

Note that PyTorch/XLA also falls back based on input types/values on certain ops. For example, PyTorch/XLA currently only supports `addmm` op with `alpha` and `beta` values of 1 and will fall back on other values. The `CapabilityBasedPartitioner` currently accepts a list of supported op names only and does not provide additional details to fall back on (input shapes, values, etc). We'll need to come up with a separate way to conditionally fallback based on input values.

*[Update as of March 9th, 2023]* One possible solution could be to dry-run our C++ op in the overridden `is_node_supported` function. This way, we can quickly check if the op needs fall back based on input values/types. 

## Additional context

- Same issue that was opened in PyTorch repo: [[Feature Request][XLA] Support fallback for the dynamo-xla bridge](https://github.com/pytorch/torchdynamo/issues/1823)
- Implementation of `CapabilityBasedPartitioner`: https://github.com/pytorch/pytorch/blob/master/torch/fx/passes/infra/partitioner.py. 
- Example of how `nvFuser` uses `CapabilityBasedPartitioner`: https://github.com/YLGH/pytorch/blob/c9a0204ef4fb8edd29aeaebc5c74867fa1093a48/torch/fx/passes/backends/nvfuser.py
- Example of how `onnxruntimer` uses `CapabilityBasedPartitioner`: https://github.com/ramkrishna2910/onnxruntime/blob/master/orttraining/orttraining/python/training/torchdynamo/ort_backend.py

cc @JackCaoG @alanwaketan

**Comment by JackCaoG** [comment]
FYI @SherlockNoMad @wconstab @bdhirsh

**Comment by harishneit** [comment]
Did we consider the possibility of extending dynamo's backend registration to allow for backends specify supported ops 1) through a list or 2) through an OperatorSupport object? Or is the partitioning logic being implemented inside `pytorch/xla` to allow for scenarios where op can't be supported for given operand shape?

**Comment by wonjoolee95** [comment]
IIRC, we did consider that as an option in our older discussion at https://github.com/pytorch/torchdynamo/issues/1823. However, we did not go that route since: 1. it would require involvement/changes in the dynamo's side 2. the `CapabilityBasedPartitioner` seemed to be the standard for these use cases that was already in-place.

**Comment by alanwaketan** [comment]
I guess in `is_node_supported`, you can call into our c++ layer and dry run an op to figure out if it needs fallback or not.

How often this partitioner needs to be run?

**Comment by wonjoolee95** [comment]
> I guess in `is_node_supported`, you can call into our c++ layer and dry run an op to figure out if it needs fallback or not.
> 
> How often this partitioner needs to be run?

That's a great point, it sounds like it could possibly fix the input/shape based op fallback. I'll update the RFC to include that as a possible solution. 

As per the partitioner, if my understanding is correct it's going to run every time the xla-dynamo bridge entry (the `extract_compiled_graph` function) is called at https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/backends/torchxla.py#L24. And this `extract_compiled_graph` is called in the `fwd` function whenever we encounter a new (non-cached) fx graph.

**Comment by alanwaketan** [comment]
Cool. It doesn't sound expansive then.

**Comment by wonjoolee95** [comment]
This is a bit late, but it is merged with https://github.com/pytorch/xla/pull/5000. Thanks everyone for working on this and reviewing it!
