### ISSUE TITLE
[Dynamism] Dynamic Support for torch.unbind

### ISSUE THREAD

**Issue by ymwangg** [pytorch/xla#4749]
[torchvision.ops.boxes._batched_nms_vanilla](https://github.com/pytorch/vision/blob/ea0be26b88778b1033d4a176be68bcdd008ff934/torchvision/ops/boxes.py#L98-L112) has the following usage of dynamic tensors:
```py
for class_id in torch.unique(idxs):
    curr_indices = torch.where(idxs == class_id)[0]
    ...
```
It looks like `__iter__` semantics is not supported by dynamic tensors now. If I run the following code:
```py
import torch
import torch_xla.core.xla_model as xm

device = xm.xla_device()
x = torch.randint(0,2,size=(10,10)).to(device)
y = torch.nonzero(x)
for i in y:
    print(i)
```
I got the following error (with `XLA_EXPERIMENTAL=nonzero`):
```
Traceback (most recent call last):
  File "nonzero.py", line 15, in <module>
    for elem in y:
  File "/home/ubuntu/src/pytorch/torch/_tensor.py", line 940, in __iter__
    return iter(self.unbind(0))
RuntimeError: Cannot call sizes() on tensor with symbolic sizes/strides
```
This error is thrown from here with backtrace [here](https://gist.github.com/ymwangg/d38a247e7fd4380372789a7b1f774158) https://github.com/pytorch/xla/blob/18674daf0c44bef0162cbeddaaef7acc206ecea5/torch_xla/csrc/tensor_impl.cpp#L121

So maybe the solution is to materialize the dynamic tensor and it's shape?

**Comment by JackCaoG** [comment]
@bdhirsh in case you have some insight regarding the size/stride issue.

**Comment by bdhirsh** [comment]
It looks like `__iter__` is defined on `torch.Tensor` to call `torch.Tensor.unbind()` ([code](https://github.com/pytorch/pytorch/blob/7eef469793414c0b794c0fe967d0f5bd0a2878ea/torch/_tensor.py#L940)), which returns a list of tensors.

cc @ezyang but I don't think this is something that we'd really be able to support with dynamic shapes. python's `__iter__()` needs to know when to stop iterating, but in this case it can't without evaluating the size of the result of the nonzero call (not known at trace time).

In terms of what this code should actually do - the options are probably to either loudly error (like it does today, although with a nicer message) to indicate that we can't fully trace through this code, or to silently graph break / perform a device sync, when we need to know the number of elements in the nonzero output?

**Comment by ezyang** [comment]
the explicit for loop can be rewritten to use map, see functorch/experimental/_map.py

**Comment by ezyang** [comment]
In Dynamo, the appropriate thing to do would be to graph break on this call. Not sure about XLA though.

**Comment by vanbasten23** [comment]
hi @ymwangg , I wonder if you've had a chance to try Ed's suggestion: replace the explicit loop with the map.

**Comment by ymwangg** [comment]
@vanbasten23 If I understand it correctly, `functorch.experimental.control_flow` is primarily for making for-loop traceable in fx graph by replacing the for-loop with something like `torch.stack([f(x, *args) for x in xs])`.  I found it hard to rewrite the following code in this way, though it may be possible:
```py
    keep_mask = torch.zeros_like(scores, dtype=torch.bool)
    for class_id in torch.unique(idxs):
        curr_indices = torch.where(idxs == class_id)[0]
        curr_keep_indices = nms(boxes[curr_indices], scores[curr_indices], iou_threshold)
        keep_mask[curr_indices[curr_keep_indices]] = True
    keep_indices = torch.where(keep_mask)[0]
```
So I guess the easiest way is to use the other nms implementation without `torch.unique`: https://github.com/pytorch/vision/blob/ea0be26b88778b1033d4a176be68bcdd008ff934/torchvision/ops/boxes.py#L75.
