### ISSUE TITLE
[Dynamo] Integrating CapabilityBasedPartitioner in PyTorch/XLA

### ISSUE THREAD

**Issue by wonjoolee95** [pytorch/xla#4758]
## ❓ Questions and Help

As per https://github.com/pytorch/xla/issues/4742, we're proposing to use `CapabilityBasedPartitioner` to support CPU fallback for xla-dynamo bridge. The capabilities of `CapabilityBasedPartitioner` seem sufficient for our use case, however, we noticed some differences in the dynamo bridge between existing backends that use `CapabilityBasedPartitioner` and our XLA-dynamo bridge.

This issue will highlight the key differences and serve as a Q&A for discussing and proposing solutions to address these differences. 

## Sources
- nvFuser
  - Backend bridge: [pytorch/torch/fx/passes/backends/nvfuser.py](https://github.com/YLGH/pytorch/blob/c9a0204ef4fb8edd29aeaebc5c74867fa1093a48/torch/fx/passes/backends/nvfuser.py)
  - Dynamo registration:  [pytorch/torch/_dynamo/backends/nvfuser.py](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/backends/nvfuser.py)
- onnxruntime
  - Backend bridge: [onnxruntime/orttraining/orttraining/python/training/torchdynamo/ort_backend.py](https://github.com/ramkrishna2910/onnxruntime/blob/master/orttraining/orttraining/python/training/torchdynamo/ort_backend.py)
  - Dynamo registration: [pytorch/torch/_dynamo/backends/onnxrt.py](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/backends/onnxrt.py)
- XLA
  - Backend bridge: [torch_xla/core/dynamo_bridge.py](https://github.com/pytorch/xla/blob/master/torch_xla/core/dynamo_bridge.py)
  - Dynamo registration: [pytorch/torch/_dynamo/backends/torchxla.py](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/backends/torchxla.py)

## Existing XLA-dynamo integration

The current existing XLA-dynamo bridge is quite simple. XLA bridge's `extract_compiled_graph` function (located here at [torch_xla/core/dynamo_bridge.py](https://github.com/pytorch/xla/blob/master/torch_xla/core/dynamo_bridge.py#L196)) serves as an entry point for dynamo. This `extract_compiled_graph` function has some XLA-specific logic but it mainly executes the `torch.fx.GraphModule` to populate the lazy cache and returns a `optimized_mod` function which dynamo calls the execute the cached graph. 

The dynamo registration code for dynamo is also simple. As shown at [pytorch/torch/_dynamo/backends/torchxla.py](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/backends/torchxla.py), dynamo calls the XLA bridge's `extract_compiled_graph` function to cache and compile the graph. However, now that we looked at other backends on how they integrated with `CapabilityBasedPartitioner`, we noticed some differences in the structure of the dynamo integration which we'll describe below. 

## Differences in the backend bridge

Both `nvFuser` and `onnxruntime` backend bridge code are organized in a similar structure in that they have a `NvFuserBackend`  and `OrtBackend` class implements a `compile()` function that uses the `CapabilityBasedPartitioner`. In more detail, these classes for both bridges do the following:
- Implements a `compile()` function that takes a `torch.fx.GraphModule` and returns a partitioned (partitioned by the `CapabilityBasedPartitioner`) `torch.fx.GraphModule`.
- A backend-specific function to execute the  `torch.fx.GraphModule`. This function is used to override the partitioned graph module's __call__() function [as shown here](https://github.com/YLGH/pytorch/blob/c9a0204ef4fb8edd29aeaebc5c74867fa1093a48/torch/fx/passes/backends/nvfuser.py#L284). 

On the other hand, the XLA bridge code a bit differently. The XLA bridge returns a `optimized_mod` function which dynamo calls to execute the cached graph. 

Now, our questions are:
- What are the reasons behind these differences? Is this structure of `nvFuser` and `onnxruntime` required to integrate with `CapabilityBasedPartitioner`? 
- Also, where are these classes `NvFuserBackend` and `OrtBackend` initialized/invoked? My original thought was that they were going to be invoked somewhere in the dynamo registration code, but it seems like they're not initialized/called. 

## Differences in the dynamo registration 

There seem to be many subtle differences between how XLA-dynamo is registered and how nvFuser/onnxruntime-dynamo is registered. One main difference is that in `nvFuser` dynamo registration, [it registers `fw_compiler`, `bw_compiler`, and `partiton_fn` as such](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/backends/nvfuser.py#L71-L76):
```
    return aot_autograd(
        fw_compiler=partial(prims_executor, executor=executor),
        bw_compiler=partial(prims_executor, executor=executor),
        partition_fn=nvprims_fw_bw_partition_fn,
    )
```

Meanwhile, all XLA does is register a `fwd` function as shown [in the simple registration code](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/backends/torchxla.py#L28) and described above. Now, our questions are:
- Is this `partition_fn` registration required to integrate with the `CapabilityBasedPartitioner`? 

We'll update this issue accordingly as we have more clarifications from our investigations as well.

cc @alanwaketan @JackCaoG @shunting314 @ @SherlockNoMad

**Comment by SherlockNoMad** [comment]
partition_fn partitions the joint_graph into forward and backward partitions. 
You can then further apply CapabilityBasedPartitioner on these two graphs. 

Also, you don't need to do this inside AOTAutograd. This can be a standalone step after AOTAutograd.

**Comment by IvanYashchuk** [comment]
> where are these classes NvFuserBackend and OrtBackend initialized/invoked? My original thought was that they were going to be invoked somewhere in the dynamo registration code, but it seems like they're not initialized/called.

`torch/fx/passes/backends/nvfuser.py` is a dead code, it's not used, and should be removed.

Here's the place where `CapabilityBasedPartitioner` is used for the "nvprims_nvfuser" dynamo backend: https://github.com/pytorch/pytorch/blob/0d66db1b2a9470a50d930308dbffda017500b80b/torch/_prims/nvfuser_executor.py#L424-L442

**Comment by wonjoolee95** [comment]
This is a bit late, but it is merged with https://github.com/pytorch/xla/pull/5000. Thanks everyone for working on this and reviewing it!
