### ISSUE TITLE
`test_optimizer (__main__.TestSyncFreeSGD)` is flaky

### ISSUE THREAD

**Issue by wonjoolee95** [pytorch/xla#4765]
We noticed that test_optimizer (__main__.TestSyncFreeSGD) test in PyTorch/XLA has been flaky recently:
```
======================================================================
FAIL: test_optimizer (__main__.TestSyncFreeSGD)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_syncfree_optimizers.py", line 133, in test_optimizer
    self._test_optimizer(
  File "test/test_syncfree_optimizers.py", line 103, in _test_optimizer
    np.testing.assert_allclose(
  File "/opt/conda/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/opt/conda/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.01, atol=0.01

Mismatched elements: 40 / 16000 (0.25%)
Max absolute difference: 0.07109498
Max relative difference: 5.713371
 x: array([[-0.003926,  0.054342, -0.040796, ...,  0.034988, -0.052126,
         0.035579],
       [-0.03531 , -0.042988, -0.023419, ...,  0.007419,  0.053072,...
 y: array([[-0.003854,  0.053369, -0.040069, ...,  0.034358, -0.051194,
         0.034939],
       [-0.034677, -0.042214, -0.022997, ...,  0.007267,  0.052123,...

----------------------------------------------------------------------
Ran 2 tests in 89.465s
```
We'll disable the test for now while we get confirmation from @ymwangg if it's okay to increase the fault tolerance on this.

**Comment by ymwangg** [comment]
@wonjoolee95 I think this may be related to functionalization, which may change the numerical stability. It seems that this test always fails on newer gpus (A100, A10G), though it didn't fail on V100.

The following command fails on A100 and A10G, though it can pass on V100 (nightly_3.8_cuda_11.7_20230303).
```
docker run --rm --runtime nvidia --gpus all --env GPU_NUM_DEVICES=1 gcr.io/tpu-pytorch/xla:nightly_3.8_cuda_11.7_20230303 bash -c "for i in {1..5}; do python /pytorch/xla/test/test_syncfree_optimizers.py TestSyncFreeSGD; done"
```

The following command can pass on A100, A10G, V100 (nightly_3.8_cuda_11.7_20230302).
```
docker run --rm --runtime nvidia --gpus all --env GPU_NUM_DEVICES=1 gcr.io/tpu-pytorch/xla:nightly_3.8_cuda_11.7_20230302 bash -c "for i in {1..5}; do python /pytorch/xla/test/test_syncfree_optimizers.py TestSyncFreeSGD; done"
```

**Comment by wonjoolee95** [comment]
@ymwangg, thanks for the investigation! Hmm, that's interesting. I wonder if we have confirmed that it's caused by functionalization using the nightly image when functionalization wasn't enabled? 

cc @alanwaketan

**Comment by alanwaketan** [comment]
Hopefully we can have the DISABLE_FUNCTIONALIZATION flag ready soon to do the A/B testing.

**Comment by wonjoolee95** [comment]
> Hopefully we can have the DISABLE_FUNCTIONALIZATION flag ready soon to do the A/B testing.

On that note, seems like I'm seeing some new functionalization/view related errors when I try to disable functionalization within dynamo -- https://github.com/pytorch/xla/pull/4747. I'm looking into it, but just FYI.

**Comment by alanwaketan** [comment]
On the other hand, I believe we run the test on the GPU CI for quite a long time on the func branch, and never see this error before.
