### ISSUE TITLE
Installation problem  google colab TPU  Wheel

### ISSUE THREAD

**Issue by alekseybaev** [pytorch/xla#4802]
## 🐛 Bug

Installation problem Colab TPU Wheel

## To Reproduce

I run the installation in google colab like this:
! pip install https://storage.googleapis.com/tpu-pytorch/wheels/colab/torch_xla-1.13-cp37-cp37m-linux_x86_64.whl.
On this google colab I get the following error message:
ERROR: torch_xla-1.13-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.

## Expected behavior

How can I fix this and make the download successful?

## Environment

 - Reproducible on XLA backend [CPU/TPU]: CPU/TPU
 - torch_xla version: 1.13

**Comment by sr5434** [comment]
I have had this same issue.

**Comment by alekseybaev** [comment]
> I have had this same issue.

If you managed to solve it successfully, tell us how you did it?

**Comment by sr5434** [comment]
I wasn’t able to solve the problem.

**Comment by sr5434** [comment]
Will anyone review this issue?

**Comment by alekseybaev** [comment]
This can help
https://colab.research.google.com/github/pytorch/xla/blob/master/contrib/colab/pytorch-xla-profiling-colab.ipynb#scrollTo=pLQPoJ6Fn8wF

**Comment by sr5434** [comment]
Are you sure that works?

**Comment by alekseybaev** [comment]
Yes, it's fine

вс, 2 апр. 2023 г., 19:25 Samir ***@***.***>:

**Comment by sr5434** [comment]
Ok, I will try it.
