### ISSUE TITLE
How to run XLA compilation thru MLIR

### ISSUE THREAD

**Issue by MUR-83** [pytorch/xla#4837]
## ❓ Questions and Help
Hi,
Is there a way to switch pytorch->XLA to compilation through MLIR chain? (StableHLO/MHLO/LMHLO etc.) Or will it appear only after switch to openxla/xla repository? (I see such pull requests in the list, but according to OpenXLA community meeting slides, these repositories should have the same contents).
So far, using all found env.options, I managed to get dumps only of HLO (non-MLIR) IR and I guess this is a non-MLIR path used by default.

Thank you.

**Comment by vanbasten23** [comment]
Yea. Currently, PyTorch/XLA only uses HLO by default. But we do have a work item to use MLIR and it's currently in the experimental phase. @lsy323 has a [PR](https://github.com/pytorch/xla/pull/4669) to demonstrate how to do that.

**Comment by wonjoolee95** [comment]
Thanks for the answer, @vanbasten23. I'll go ahead and close this issue. Feel free to re-open with any new questions or concerns.
