### ISSUE TITLE
Error when : device = xm.xla_device()

### ISSUE THREAD

**Issue by conchaeloko** [pytorch/xla#4847]
## 🐛 Bug

I get an error when running the commands on the server
>>> from transformers import AutoTokenizer, EsmForProteinFolding
>>> import torch
>>> import torch_xla.core.xla_model as xm
>>> device = xm.xla_device()
WARNING: Logging before InitGoogle() is written to STDERR

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## To Reproduce
gcloud compute instances create ${TPU_NAME}-vm \
  --project=${PROJECT_ID} \
  --zone=${ZONE} \
  --machine-type=n1-standard-4 \
  --image-family=torch-xla \
  --image-project=ml-images \
  --boot-disk-size=200GB \
  --scopes=https://www.googleapis.com/auth/cloud-platform

gcloud compute ssh ${TPU_NAME}-vm --zone=${ZONE} --project=${PROJECT_ID} -- -L 9009:localhost:9009

export XRT_TPU_CONFIG="tpu_worker;0;${TPU_IP_ADDRESS}:8470"

export PJRT_DEVICE=TPU

pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch_xla-2.0-cp38-cp38-linux_x86_64.whl
pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch-2.0-cp38-cp38-linux_x86_64.whl
pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torchvision-2.0-cp38-cp38-linux_x86_64.whl
### I tried using most of the other compatible versions of torch and co.

pip3 install torch_xla[tpuvm]
pip3 install accelerate
pip3 install mkl

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"/anaconda3/envs/esmfold/lib"
echo $LD_LIBRARY_PATH

/anaconda3/envs/esmfold/lib

sudo ln -s /anaconda3/envs/esmfold/lib/libmkl_intel_lp64.so.2 /anaconda3/envs/esmfold/lib/libmkl_intel_lp64.so.1
sudo ln -s /anaconda3/envs/esmfold/lib/libmkl_intel_thread.so.2 /anaconda3/envs/esmfold/lib/libmkl_intel_thread.so.1
sudo ln -s /anaconda3/envs/esmfold/lib/libmkl_core.so.2 /anaconda3/envs/esmfold/lib/libmkl_core.so.1

apt-get install glibc-source
sudo ldconfig

ldd /anaconda3/envs/esmfold/lib/python3.8/site-packages/torch/lib/libtorch.so

## Expected behavior

Being able to load the torch model on the tpu

## Environment

 - Reproducible on XLA backend [CPU/TPU]:
 - torch_xla version:

## Additional context

The rest of the output error : 

>>> from transformers import AutoTokenizer, EsmForProteinFolding
>>> import torch
>>> import torch_xla.core.xla_model as xm
>>> device = xm.xla_device()
WARNING: Logging before InitGoogle() is written to STDERR
I0000 00:00:1680577771.538401    7918 common_lib.cc:145] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577772.039920    7918 common_lib.cc:145] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577772.541487    7918 common_lib.cc:145] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
^CI0000 00:00:1680577773.043037    7918 common_lib.cc:145] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577773.544645    7918 common_lib.cc:145] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577774.046162    7918 common_lib.cc:145] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
Failed to get 'tpu-env' from instance metadata: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577774.548150    7918 common_lib.cc:145] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577775.049597    7918 common_lib.cc:145] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577775.551074    7918 common_lib.cc:145] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577776.052475    7918 common_lib.cc:145] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577776.553983    7918 common_lib.cc:145] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577777.055481    7918 common_lib.cc:145] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
Failed to get 'tpu-env' from instance metadata: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577777.557388    7918 common_lib.cc:145] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577778.058900    7918 common_lib.cc:145] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577778.560542    7918 common_lib.cc:145] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577779.061972    7918 common_lib.cc:145] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577779.563477    7918 common_lib.cc:145] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577780.064901    7918 common_lib.cc:145] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
Failed to get 'tpu-env' from instance metadata: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577780.567004    7918 common_lib.cc:145] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577781.068477    7918 common_lib.cc:145] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577781.570111    7918 common_lib.cc:145] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577782.071781    7918 common_lib.cc:145] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577782.573224    7918 common_lib.cc:145] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577783.074835    7918 common_lib.cc:145] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
Failed to get 'tpu-env' from instance metadata: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577783.576797    7918 common_lib.cc:145] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577784.078289    7918 common_lib.cc:145] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577784.579777    7918 common_lib.cc:145] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577785.081224    7918 common_lib.cc:145] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577785.582815    7918 common_lib.cc:145] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577786.084208    7918 common_lib.cc:145] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
Failed to get accelerator type with error: Failed to fetch URL (http status: 404) No errorI0000 00:00:1680577786.586112    7918 common_lib.cc:145] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577787.087562    7918 common_lib.cc:145] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577787.589032    7918 common_lib.cc:145] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577788.090490    7918 common_lib.cc:145] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577788.591947    7918 common_lib.cc:145] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577789.093346    7918 common_lib.cc:145] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
Failed to get agent-worker-number with error: Failed to fetch URL (http status: 404) No errorI0000 00:00:1680577789.595378    7918 common_lib.cc:145] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577790.096943    7918 common_lib.cc:145] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577790.598422    7918 common_lib.cc:145] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577791.099922    7918 common_lib.cc:145] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577791.601387    7918 common_lib.cc:145] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577792.102907    7918 common_lib.cc:145] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
Failed to get worker list with error: Failed to fetch URL (http status: 404) No errorI0000 00:00:1680577792.604846    7918 common_lib.cc:145] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577793.106249    7918 common_lib.cc:145] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577793.607685    7918 common_lib.cc:145] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577794.109187    7918 common_lib.cc:145] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577794.610722    7918 common_lib.cc:145] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577795.112202    7918 common_lib.cc:145] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577795.614215    7918 common_lib.cc:145] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577796.115690    7918 common_lib.cc:145] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577796.617090    7918 common_lib.cc:145] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577797.118653    7918 common_lib.cc:145] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577797.620091    7918 common_lib.cc:145] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577798.121765    7918 common_lib.cc:145] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577798.623690    7918 common_lib.cc:145] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577799.125106    7918 common_lib.cc:145] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577799.626555    7918 common_lib.cc:145] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577800.127947    7918 common_lib.cc:145] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577800.629417    7918 common_lib.cc:145] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577801.130888    7918 common_lib.cc:145] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577801.632927    7918 common_lib.cc:145] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577802.134463    7918 common_lib.cc:145] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577802.635914    7918 common_lib.cc:145] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577803.137359    7918 common_lib.cc:145] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577803.638803    7918 common_lib.cc:145] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577804.140217    7918 common_lib.cc:145] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577804.642250    7918 common_lib.cc:145] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577805.143772    7918 common_lib.cc:145] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577805.645349    7918 common_lib.cc:145] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577806.146829    7918 common_lib.cc:145] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577806.648400    7918 common_lib.cc:145] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577807.150020    7918 common_lib.cc:145] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577807.651855    7918 common_lib.cc:145] Failed to fetch URL on try 1 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577808.153299    7918 common_lib.cc:145] Failed to fetch URL on try 2 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577808.654784    7918 common_lib.cc:145] Failed to fetch URL on try 3 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577809.156231    7918 common_lib.cc:145] Failed to fetch URL on try 4 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577809.657742    7918 common_lib.cc:145] Failed to fetch URL on try 5 out of 6: Failed to fetch URL (http status: 404) No error
I0000 00:00:1680577810.159405    7918 common_lib.cc:145] Failed to fetch URL on try 6 out of 6: Failed to fetch URL (http status: 404) No error
2023-04-04 03:10:10.727618: F    7918 tensorflow/tsl/platform/statusor.cc:33] Attempting to fetch value instead of handling error UNKNOWN: TPU initialization failed: No ba16c7433 device found.
https://symbolize.stripped_domain/r/?trace=7f071f68b8eb,7f071f82672f,7f06e666cbff,7f06e6970a26,7f06e6953a71,7f06e6955fe2,7f071f823996&map=04ceea301ec570e6abcf4ef3f089f0fde6516664:7f06e3718000-7f06f716f5e0
*** SIGABRT received by PID 7918 (TID 7918) on cpu 1 from PID 7918; stack trace: ***
PC: @     0x7f071f68b8eb  (unknown)  raise
    @     0x7f06e2aeca1a       1152  (unknown)
    @     0x7f071f826730  1174518752  (unknown)
    @     0x7f06e666cc00        400  tsl::internal_statusor::Helper::Crash()
    @     0x7f06e6970a27        768  xla::PjRtComputationClient::PjRtComputationClient()
    @     0x7f06e6953a72       1440  xla::ComputationClient::Create()
    @     0x7f06e6955fe3         32  std::call_once<>()::{lambda()#2}::_FUN()
    @     0x7f071f823997  (unknown)  __pthread_once_slow
https://symbolize.stripped_domain/r/?trace=7f071f68b8eb,7f06e2aeca19,7f071f82672f,7f06e666cbff,7f06e6970a26,7f06e6953a71,7f06e6955fe2,7f071f823996&map=04ceea301ec570e6abcf4ef3f089f0fde6516664:7f06e3718000-7f06f716f5e0,ceee8fa20ddf9c34af43f587221e91de:7f06d5bc4000-7f06e2d03840
E0404 03:10:10.876868    7918 coredump_hook.cc:414] RAW: Remote crash data gathering hook invoked.
E0404 03:10:10.876906    7918 coredump_hook.cc:453] RAW: Skipping coredump since rlimit was 0 at process start.
E0404 03:10:10.876924    7918 client.cc:278] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E0404 03:10:10.876931    7918 coredump_hook.cc:512] RAW: Sending fingerprint to remote end.
E0404 03:10:10.876940    7918 coredump_socket.cc:120] RAW: Stat failed errno=2 on socket /var/google/services/logmanagerd/remote_coredump.socket
E0404 03:10:10.876986    7918 coredump_hook.cc:518] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] Missing crash reporting socket. Is the listener running?
E0404 03:10:10.876994    7918 coredump_hook.cc:580] RAW: Dumping core locally.
E0404 03:10:10.935757    7918 process_state.cc:784] RAW: Raising signal 6 with default behavior
Aborted

**Comment by vanbasten23** [comment]
I don't think `gcloud compute instances create` is the correct command to create a TPU VM. Can you try following the doc https://cloud.google.com/tpu/docs/pytorch-xla-ug-tpu-vm#run_ml_workloads_with_pytorchxla step by step instead? You should be able to use PyTorch/XLA 2.0.

**Comment by conchaeloko** [comment]
Thank you for the remark. I got to run the simple calculation code from the google cloud successfully. However, I am facing a new issue after following the example in "Run PyTorch code on TPU Pod slices".

Here is the code I ran : 
` gcloud compute tpus tpu-vm create ${TPU_NAME} --project=${PROJECT_ID} --zone=${ZONE} --accelerator-type=v2-8 --version=tpu-vm-pt-2.0`
`gcloud compute tpus tpu-vm ssh ${TPU_NAME} --zone=${ZONE} --project=${PROJECT_ID} `

Then : 
`gcloud compute config-ssh`  
`export TPU_NAME=tpu-name`  

And finally : 
`gcloud alpha compute tpus tpu-vm ssh ${TPU_NAME} --zone=${ZONE} --project=${PROJECT_ID} --worker=all \
--command="PJRT_DEVICE=TPU python3 /home/robbyconchaeloko/esmfold_PPT.py"`

However, I get the following error : 
`SSH key found in project metadata; not updating instance.
SSH: Attempting to connect to worker 0...
Warning: Permanently added 'tpu.3555976041055373645-0-oqmblf' (ECDSA) to the list of known hosts.
Downloading (…)okenizer_config.json: 100%|██████████| 40.0/40.0 [00:00<00:00, 5.45kB/s]
Downloading (…)solve/main/vocab.txt: 100%|██████████| 72.0/72.0 [00:00<00:00, 63.7kB/s]
Downloading (…)cial_tokens_map.json: 100%|██████████| 121/121 [00:00<00:00, 68.3kB/s]
Downloading (…)lve/main/config.json: 100%|██████████| 2.10k/2.10k [00:00<00:00, 737kB/s]
Downloading pytorch_model.bin: 100%|██████████| 8.44G/8.44G [00:50<00:00, 167MB/s] 
Some weights of EsmForProteinFolding were not initialized from the model checkpoint at facebook/esmfold_v1 and are newly initialized: ['esm.contact_head.regression.bias', 'esm.contact_head.regression.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2023-04-07 06:47:10.548920: F tensorflow/tsl/platform/statusor.cc:33] Attempting to fetch value instead of handling error RESOURCE_EXHAUSTED: Error allocating device buffer: Attempting to allocate 100.00M. That was not possible. There are 46.30M free.; (0x0x0_HBM0)
https://symbolize.stripped_domain/r/?trace=7f9a80adc00b,7f9a80adc08f,7f993b59dbff,7f993b8a2643,7f9a4c055fbe,7f993b89afbf,8ec834860c78347&map=04ceea301ec570e6abcf4ef3f089f0fde6516664:7f9938649000-7f994c0a05e0
*** SIGABRT received by PID 19903 (TID 19903) on cpu 24 from PID 19903; stack trace: ***
PC: @     0x7f9a80adc00b  (unknown)  raise
    @     0x7f9937a1da1a       1152  (unknown)
    @     0x7f9a80adc090  (unknown)  (unknown)
    @     0x7f993b59dc00        400  tsl::internal_statusor::Helper::Crash()
    @     0x7f993b8a2644       1312  xla::PjRtComputationClient::TransferToServer()
    @     0x7f9a4c055fbf  (unknown)  torch_xla::TensorToXlaData()
    @     0x7f993b89afc0  (unknown)  (unknown)
    @  0x8ec834860c78348  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7f9a80adc00b,7f9937a1da19,7f9a80adc08f,7f993b59dbff,7f993b8a2643,7f9a4c055fbe,7f993b89afbf,8ec834860c78347&map=04ceea301ec570e6abcf4ef3f089f0fde6516664:7f9938649000-7f994c0a05e0,ceee8fa20ddf9c34af43f587221e91de:7f992aaf5000-7f9937c34840
E0407 06:47:10.628736   19903 coredump_hook.cc:414] RAW: Remote crash data gathering hook invoked.
E0407 06:47:10.628747   19903 coredump_hook.cc:453] RAW: Skipping coredump since rlimit was 0 at process start.
E0407 06:47:10.628754   19903 client.cc:278] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E0407 06:47:10.628757   19903 coredump_hook.cc:512] RAW: Sending fingerprint to remote end.
E0407 06:47:10.628766   19903 coredump_socket.cc:120] RAW: Stat failed errno=2 on socket /var/google/services/logmanagerd/remote_coredump.socket
E0407 06:47:10.628773   19903 coredump_hook.cc:518] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] Missing crash reporting socket. Is the listener running?
E0407 06:47:10.628776   19903 coredump_hook.cc:580] RAW: Dumping core locally.
E0407 06:47:10.976148   19903 process_state.cc:784] RAW: Raising signal 6 with default behavior
Retrying: SSH command error: [/usr/bin/ssh] exited with return code [255].`

It sounds like there is an error with the memory, despite me using half of the 8GB model.
Is the amount of memory I have that limited or I am still doing something wrong ? 

Thanks for the help !

Robby

**Comment by vanbasten23** [comment]
Since you are following the [playbook](https://cloud.google.com/tpu/docs/pytorch-pods#pjrt_2), are you able to run the sample model: `(vm)$ gcloud alpha compute tpus tpu-vm ssh \
${TPU_NAME} --zone=us-${ZONE} --project=${PROJECT_ID} --worker=all \
--command="PJRT_DEVICE=TPU python3 /usr/share/pytorch/xla/test/test_train_mp_imagenet.py --fake_data --batch_size=256 --num_epochs=1"`?

**Comment by conchaeloko** [comment]
I tried running the test script as you suggested @vanbasten23 but I got an error related to memory again : 

`gcloud alpha compute tpus tpu-vm ssh ${TPU_NAME} --zone=${ZONE} --project=${PROJECT_ID} --worker=all --command="PJRT_DEVICE=TPU python3 /home/robbyconchaeloko/xla/test/test_train_mp_imagenet.py --fake_data --batch_size=256 --num_epochs=1"

SSH key found in project metadata; not updating instance.
SSH: Attempting to connect to worker 0...
Warning: Permanently added 'tpu.457090026778444084-0-w6qbx+' (ECDSA) to the list of known hosts.
2023-04-08 11:22:09.148143: F tensorflow/tsl/platform/statusor.cc:33] Attempting to fetch value instead of handling error RESOURCE_EXHAUSTED: Error loading program: Attempting to reserve 7.04G at the bottom of memory. That was not possible. There are 6.90G free, 0B reserved, and 6.90G reservable.
https://symbolize.stripped_domain/r/?trace=7ff9fecab00b,7ff9fecab08f,7ff8b4016bff,7ff8b431c5fc,7ff8c581efa7,3d74551f,351284d7,7ff8b4313f3f,2d058b4808ec8347&map=04ceea301ec570e6abcf4ef3f089f0fde6516664:7ff8b10c2000-7ff8c4b195e0
*** SIGABRT received by PID 13755 (TID 16714) on cpu 80 from PID 13755; stack trace: ***
PC: @     0x7ff9fecab00b  (unknown)  raise
    @     0x7ff8b0496a1a       1152  (unknown)
    @     0x7ff9fecab090       3920  (unknown)
2023-04-08 11:22:09.153327: F tensorflow/tsl/platform/statusor.cc:33] Attempting to fetch value instead of handling error RESOURCE_EXHAUSTED: Error loading program: Attempting to reserve 7.04G at the bottom of memory. That was not possible. There are 6.90G free, 0B reserved, and 6.90G reservable.
https://symbolize.stripped_domain/r/?trace=7ff9fecab00b,7ff9fecab08f,7ff8b4016bff,7ff8b431c5fc,7ff8c581efa7,316f033f,334a8037,7ff8b4313f3f,2d058b4808ec8347&map=04ceea301ec570e6abcf4ef3f089f0fde6516664:7ff8b10c2000-7ff8c4b195e0
E0408 11:22:09.153442   16712 process_state.cc:1074] RAW: Signal 6 raised at PC: 0x7ff9fecab00b while already in FailureSignalHandler!
E0408 11:22:09.153446   16712 process_state.cc:1078] RAW: tid: 16712 raised new signal (old_tid: 16714)
2023-04-08 11:22:09.462268: F tensorflow/tsl/platform/statusor.cc:33] Attempting to fetch value instead of handling error RESOURCE_EXHAUSTED: Error loading program: Attempting to reserve 7.04G at the bottom of memory. That was not possible. There are 6.90G free, 0B reserved, and 6.90G reservable.
https://symbolize.stripped_domain/r/?trace=7f270a50800b,7f270a50808f,7f25bf873bff,7f25bfb795fc,7f25d107bfa7,311b433f,3c076777,7f25bfb70f3f,2d058b4808ec8347&map=04ceea301ec570e6abcf4ef3f089f0fde6516664:7f25bc91f000-7f25d03765e0
*** SIGABRT received by PID 13756 (TID 17025) on cpu 2 from PID 13756; stack trace: ***
PC: @     0x7f270a50800b  (unknown)  raise
    @     0x7f25bbcf3a1a       1152  (unknown)
    @     0x7f270a508090       3920  (unknown)
2023-04-08 11:22:09.554783: F tensorflow/tsl/platform/statusor.cc:33] Attempting to fetch value instead of handling error RESOURCE_EXHAUSTED: Error loading program: Attempting to reserve 7.04G at the bottom of memory. That was not possible. There are 6.90G free, 0B reserved, and 6.90G reservable.`

Do I have those limitations in terms of memory because I am under the free trial project ? Or is there something that could be done ?

**Comment by conchaeloko** [comment]
However, it worked when I set the batch size at 20.

**Comment by conchaeloko** [comment]
I got to ssh to a v3-8 and I got the same error. 
`
robbyconchaeloko@t1v-n-c0751df5-w-0:~$ gcloud alpha compute tpus tpu-vm ssh ${TPU_NAME} --zone=${ZONE} --project=${PROJECT_ID} --worker=all --command="PJRT_DEVICE=TPU python3 /home/robbyconchaeloko/esmfold_prediction.py"
SSH key found in project metadata; not updating instance.
SSH: Attempting to connect to worker 0...
Warning: Permanently added 'tpu.4390079425134259280-0-zs/ray' (ECDSA) to the list of known hosts.

Downloading (…)okenizer_config.json: 100%|██████████| 40.0/40.0 [00:00<00:00, 5.99kB/s]
Downloading (…)solve/main/vocab.txt: 100%|██████████| 72.0/72.0 [00:00<00:00, 49.7kB/s]
Downloading (…)cial_tokens_map.json: 100%|██████████| 121/121 [00:00<00:00, 81.4kB/s]
Downloading (…)lve/main/config.json: 100%|██████████| 2.10k/2.10k [00:00<00:00, 1.39MB/s]
Downloading pytorch_model.bin: 100%|██████████| 8.44G/8.44G [03:26<00:00, 40.8MB/s]
Some weights of EsmForProteinFolding were not initialized from the model checkpoint at facebook/esmfold_v1 and are newly initialized: ['esm.contact_head.regression.weight', 'esm.contact_head.regression.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
src/tcmalloc.cc:332] Attempt to free invalid pointer 0x7ffdb8479460
https://symbolize.stripped_domain/r/?trace=7fdf3401900b,7fdf3401908f,fffffffffa86ffff,e900000002bffe88&map=
*** SIGABRT received by PID 9955 (TID 9955) on cpu 74 from PID 9955; stack trace: ***
PC: @     0x7fdf3401900b  (unknown)  raise
    @     0x7fddeaf5aa1a       1152  (unknown)
    @     0x7fdf34019090  294301792  (unknown)
    @ 0xfffffffffa870000  (unknown)  (unknown)
    @ 0xe900000002bffe89  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7fdf3401900b,7fddeaf5aa19,7fdf3401908f,fffffffffa86ffff,e900000002bffe88&map=ceee8fa20ddf9c34af43f587221e91de:7fddde032000-7fddeb171840
E0408 19:14:51.270598    9955 coredump_hook.cc:414] RAW: Remote crash data gathering hook invoked.
E0408 19:14:51.270610    9955 coredump_hook.cc:453] RAW: Skipping coredump since rlimit was 0 at process start.
E0408 19:14:51.270624    9955 client.cc:278] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E0408 19:14:51.270631    9955 coredump_hook.cc:512] RAW: Sending fingerprint to remote end.
E0408 19:14:51.270637    9955 coredump_socket.cc:120] RAW: Stat failed errno=2 on socket /var/google/services/logmanagerd/remote_coredump.socket
E0408 19:14:51.270644    9955 coredump_hook.cc:518] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] Missing crash reporting socket. Is the listener running?
E0408 19:14:51.270647    9955 coredump_hook.cc:580] RAW: Dumping core locally.
E0408 19:14:51.620981    9955 process_state.cc:784] RAW: Raising signal 6 with default behavior
Retrying: SSH command error: [/usr/bin/ssh] exited with return code [255].
`

**Comment by conchaeloko** [comment]
Some additional info : 
```
>>> def esmfold_prediction(tokenized_sequences , path_out) :
...     """
...     The function takes as an input :
...     - 'tokenized_sequences', the output of the function tokenize_fasta
...     - 'path_out', the path of the directory when the pdb files are to be written
...     The function generates the pdb files in the path_out
...
...     """
...     for protein in tokenized_sequences :
...         pdb_files = []
...         print("All good here ...")
...         with torch.no_grad():
...             output = model(protein[1].to(device))
```

Everything works well until I call '''output = model(protein[1].to(device))'''.
The error is : 


```
https://symbolize.stripped_domain/r/?trace=7f684b45500b,7f684b45508f,fffffffffb4affff,e900000002bffe88&map=
*** SIGABRT received by PID 3890 (TID 3890) on cpu 77 from PID 3890; stack trace: ***
PC: @     0x7f684b45500b  (unknown)  raise
    @     0x7f6702306a1a       1152  (unknown)
    @     0x7f684b455090  647155808  (unknown)
    @ 0xfffffffffb4b0000  (unknown)  (unknown)
    @ 0xe900000002bffe89  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7f684b45500b,7f6702306a19,7f684b45508f,fffffffffb4affff,e900000002bffe88&map=ceee8fa20ddf9c34af43f587221e91de:7f66f53de000-7f670251d840
E0408 23:31:17.056598    3890 coredump_hook.cc:414] RAW: Remote crash data gathering hook invoked.
E0408 23:31:17.056610    3890 coredump_hook.cc:453] RAW: Skipping coredump since rlimit was 0 at process start.
E0408 23:31:17.056628    3890 client.cc:278] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E0408 23:31:17.056631    3890 coredump_hook.cc:512] RAW: Sending fingerprint to remote end.
E0408 23:31:17.056639    3890 coredump_socket.cc:120] RAW: Stat failed errno=2 on socket /var/google/services/logmanagerd/remote_coredump.socket
E0408 23:31:17.056647    3890 coredump_hook.cc:518] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] Missing crash reporting socket. Is the listener running?
E0408 23:31:17.056651    3890 coredump_hook.cc:580] RAW: Dumping core locally.
E0408 23:31:17.440092    3890 process_state.cc:784] RAW: Raising signal 6 with default behavior
Aborted (core dumped)
```

**Comment by JackCaoG** [comment]
```
gcloud compute instances create ${TPU_NAME}-vm
--project=${PROJECT_ID}
--zone=${ZONE}
--machine-type=n1-standard-4
--image-family=torch-xla
--image-project=ml-images
--boot-disk-size=200GB
--scopes=https://www.googleapis.com/auth/cloud-platform
```
suggested you are running 2vm, which is a deprecated architure. Can you try https://github.com/pytorch/xla#running-on-a-single-cloud-tpu-vm to create a TPUVM? PJRT does not work on 2vm

**Comment by wonjoolee95** [comment]
@conchaeloko, were you able to fix your issue by setting up a TPUVM (1VM) with the instructions linked above?
