### ISSUE TITLE
Training script ends by out-of-RAM-memory issue

### ISSUE THREAD

**Issue by Kensuke-Mitsuzawa** [pytorch/xla#4863]
## ❓ Questions and Help

Hello, developers. I am a beginner at Torch/XLA. I am stuck with the Out-Of-Memory issue. Could you kindly help me?

### To Reproduce

I am following a simple LSTM model code described in the github issue.
https://github.com/pytorch/xla/issues/1196

Specifically, the code snippet is here on Gist: https://gist.github.com/dlibenzi/a18ab4b6e675208bf8277a53a0f42be5

### Expected behavior and actual

The code is expected to finish the training. However, the script is forcefully killed by a task manager: SIGKILL. The SIGKILL is because of out-of-memory.

I printed timestamps and consumed RAM memory during the training. Here is the output. In the log, `Memory: ` represents GBs.

```
------------
[2023-04-09T18:26:49.024541] STEP:  0
[2023-04-09T18:26:51.894071] before loss backward
Memory: 0.515872
[2023-04-09T18:27:41.966802] after loss backward
Memory: 6.363816
[[{'2023-04-09T18:27:41.967248'}]] before parameter optimization
[[{'2023-04-09T18:27:50.846527'}]] after parameter optimization
Memory: 8.03086
test loss: 0.488284707069397
------------
[2023-04-09T18:28:33.828656] STEP:  1
[2023-04-09T18:28:40.579939] before loss backward
Memory: 11.023312
[2023-04-09T18:29:24.407885] after loss backward
Memory: 13.779288000000001
[[{'2023-04-09T18:29:24.408170'}]] before parameter optimization

SIGKILL
```

### Environment

My Virtual Machine and TPU is on Google Computing Platform (GCP).

- TPU: v2-8  pytorch-1.13
    - region: us-central1-b
- VM: e2-standard-4
    - region: us-west1-b 

The VM has 16GB RAM memory.

Software versions are
- python 3.7.12
- Pytorch 1.13.1 
- Pytorch-xla 1.13

### Questions

Why the script does not release RAM memory?

First of all, why the script consumes RAM memory during backward and optimization? I have supposed that TPU computes backwards and optimization too. If so, too much RAM memory is strange.

**Comment by JackCaoG** [comment]
I think you are using the old 2vm which is deprecated now, can you try TPUVM per https://cloud.google.com/tpu/docs/pytorch-xla-ug-tpu-vm which will let you access the TPU directly. You will have a much stronger TPUVM host which has over 150GB RAM.

**Comment by JackCaoG** [comment]
Training code doesn't need to be changed, you just need to change the way to configure the env var. You should also find some useful info in https://pytorch.org/xla/release/2.0/index.html# (this is for 2.0 release, which we recommend since you can try our new PJRt runtime)

**Comment by Kensuke-Mitsuzawa** [comment]
Thank you for your great suggestion and help. Yes. I was using old 2vm. 

I updated my computational environment.

- TPU VM v3-8 (us-central1-a)
- Python 3.8.10

torch-related packages are as below.

```
pytorch-lightning        2.0.2               
torch                    2.0.0               
torch-xla                2.0                 
torchmetrics             0.11.4              
torchvision              0.15.1 
```

Unfortunately, [the script](https://gist.github.com/dlibenzi/a18ab4b6e675208bf8277a53a0f42be5) does not work as expected. The script is super slow...and even RAM memory usage kept increasing. Here is the print-debug message during the script execution.

```
------------
[2023-04-24T15:18:34.259152] STEP:  0
[2023-04-24T15:18:35.570632] before loss backward
Memory: 2.7999319999999996
[2023-04-24T15:36:26.640804] after loss backward
Memory: 19.778504
[[{'2023-04-24T15:36:26.641393'}]] before parameter optimization
[[{'2023-04-24T15:42:51.939287'}]] after parameter optimization
Memory: 24.759511999999997
test loss: 0.488284707069397
------------
[2023-04-24T15:56:40.627908] STEP:  1
[2023-04-24T15:56:41.866663] before loss backward
Memory: 35.512519999999995
```

Anyway, it does not matter anymore. My target is to train a model using Pytorch-lightning on TPU. 

I tested a sample code of Pytorch-lightning: https://lightning.ai/docs/pytorch/stable/starter/introduction.html
I confirmed that the sample code works well on the created TPU VM environment.

For the moment, I close the issue.
