### ISSUE TITLE
`add` op returns incorrect results when dynamic shape is involved.

### ISSUE THREAD

**Issue by vanbasten23** [pytorch/xla#4870]
## 🐛 Bug

`add` op returns incorrect results when dynamic shape is involved.

## To Reproduce

```
  def test_add(self):
    t1 = torch.tensor([[1, 0, 3, 5, 0, 6]], device=dev)
    t2 = torch.nonzero(t1)
    # print(t2)
    t3 = torch.tensor([[1, 1, 0, 0]], device=dev)
    t4 = torch.nonzero(t3)
    # print(t4)
    # t2.shape=torch.Size([<=6, 2]) with real size [4, 2]
    # t4.shape=torch.Size([<=4, 2]) with real size [2, 2]
    # PyTorch eager mode will output error: "RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 0"
    # self.assertRaises(RuntimeError, lambda: torch.add(t2, t4))
    t5 = torch.add(t2, t4)
    print(t5)
```

Run the above test with
```
export PJRT_DEVICE=TPU_LEGACY
XLA_EXPERIMENTAL="nonzero:masked_select"  python3 pytorch/xla/test/test_dynamic_shapes.py TestDynamicShapes.test_add 2>&1 | tee out.txt
```
The output on my v3/v4 is:
```
root@t1v-n-5d8f2427-w-0:/workspaces/work# XLA_EXPERIMENTAL="nonzero:masked_select"  python3 pytorch/xla/test/test_dynamic_shapes.py TestDynamicShapes.test_add 2>&1 | tee out.txt
.
----------------------------------------------------------------------
Ran 1 test in 0.185s

OK
tensor([[0, 0],
        [0, 3]], device='xla:0', dtype=torch.int32)
```

## Expected behavior

I expect to see a runtime error.

## Environment

 - Reproducible on XLA backend [CPU/TPU]: TPU
 - torch_xla version: nightly at 04/10/2023

## Additional context

cc: @miladm @JackCaoG

**Comment by miladm** [comment]
Why runtime error and not compilation error? I recalled we discussed this topic with the PyTorch team the other week. What's the plan of record for handling two dynamic input tensors? Does PyTorch support two dynamic input tensors in dynamo?

**Comment by vanbasten23** [comment]
> Why runtime error and not compilation error? 

At compile time, I imagine t5 should have shape [<=4, 2] so it should succeed. Only at runtime, we find we couldn't add 2 tensors with shape [4, 2] and [2, 2]. Wdyt?

> I recalled we discussed this topic with the PyTorch team the other week. What's the plan of record for handling two dynamic input tensors? Does PyTorch support two dynamic input tensors in dynamo?

I think you are referring to this [comment](https://github.com/pytorch/xla/issues/4741#issuecomment-1486015241) from Ed. iiuc, he doesn't mean it is impossible to handle adding 2 dynamic tensors. Instead, he wants to say we can memoize the size node from a tensor.
