### ISSUE TITLE
ModuleNotFoundError: `yaml` dependency with PJRT

### ISSUE THREAD

**Issue by carmocca** [pytorch/xla#4871]
## To Reproduce

In a clean environment

```bash
pip install torch
pip install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch_xla-2.0-cp38-cp38-linux_x86_64.whl
python -c "import torch_xla.core.xla_model as xm"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/carmocca/git/venv-3.8/lib/python3.8/site-packages/torch_xla/core/xla_model.py", line 12, in <module>
    from torch_xla.experimental import pjrt
  File "/home/carmocca/git/venv-3.8/lib/python3.8/site-packages/torch_xla/experimental/pjrt.py", line 17, in <module>
    from torch_xla.experimental import tpu, gpu
  File "/home/carmocca/git/venv-3.8/lib/python3.8/site-packages/torch_xla/experimental/tpu.py", line 8, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

`pip install pyyaml` does solve the issue.

Alternatively, the `yaml` import could be made local to the function that uses it:
https://github.com/pytorch/xla/blob/f763d0d2a4dac0872e2e1670332fd490f524b8be/torch_xla/experimental/tpu.py#L139-L144

**Comment by JackCaoG** [comment]
I tried the same install and I am able to get it to run on TPUVM
```
jackcao@t1v-n-f536b11f-w-0:~$ python3
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torch_xla.core.xla_model as xm
>>> import yaml
>>> yaml.__version__
'6.0'
```

which env did you install the wheel? We can make yaml import local through, given it is only being used by TPU I think? @ManfeiBai @will-cromar any thoughts?

**Comment by will-cromar** [comment]
We probably just missed this because `yaml` is already in our test environments. We should add an explicit dependency here:

https://github.com/pytorch/xla/blob/ef95cb419095fc2d46a12502dbf5c1cc9c61a612/setup.py#L368-L371
