### ISSUE TITLE
Build PYTORCH/XLA without build pytorch first

### ISSUE THREAD

**Issue by kevint324** [pytorch/xla#4877]
## 🚀 Feature

Add a option to allow building PyTorch/XLA with PyTorch installed from official PyPI source.

## Motivation

According to the [instructions of build from source](https://github.com/pytorch/xla/blob/master/CONTRIBUTING.md#build-from-source), building pytorch/xla needs to build pytorch first. And pytorch needs to be patched a little bit.

This step should be optional rather than required. From the perspective of xla developers, torch_xla only relies on pip installed pytorch, which can bring some convenience to the development work, such as: faster build speed;  avoid the  _GLIBCXX_USE_CXX11_ABI mess a little bit.

It is also safer to use the native pytorch since it simplifies the xla development process and introducing much less surprises.

## Pitch

I've [filed a PR](https://github.com/pytorch/xla/pull/4869) to fix this.

As described in the modified [CONTRIBUTION.md](https://github.com/pytorch/xla/pull/4869/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R85-R94
). 
A new option is introduced and is controlled by a env variable **BUILD_CPP_TESTS_USE_SITE_PYTORCH** which by default is false, means the current behavior is not affected.

* Prepare _PyTorch_.

  * You can either build _PyTorch_ from source following the regular [instructions](https://github.com/pytorch/pytorch#from-source).

    ```Shell
    python setup.py install
    ```

  * or install PyTorch from PyPI source. The PyTorch version should match with your XLA branch.

    ```Shell
    # Use CPU version PyTorch if you are building PyTorch/XLA without CUDA support
    # Otherwise use the regular version.
    pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

    # Export this environment variable before build the PyTorch/XLA source
    export BUILD_CPP_TESTS_USE_SITE_PYTORCH=1
    ```

## Additional context

I‘ve tested  the patch on ubuntu20 with gcc 9.4 and clang-8 and it works fine with:

```
pip3 install torch==2.0.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
```

The patch change $PT_DIR from relative path to PYTHON_LIBRARY_DIR.

**Comment by JackCaoG** [comment]
@stgpetrovic @will-cromar I remember we had a similar conversation regarding how to achieve it with bazel.

**Comment by ManfeiBai** [comment]
Hi, @will-cromar , is that ok to assign this issue to you?
