### ISSUE TITLE
Increase XLA_IR_SHAPE_CACHE_SIZE default value

### ISSUE THREAD

**Issue by cicirori** [pytorch/xla#4914]
Recently, I upgraded torch xla to version 2.0 and found serious performance degradation on some models, such as diffusers/dreambooth. After investigation, it was found that the shape cache was blown up, so the trace did not hit the cache each time, and the time for trace was much longer than that for execution. This problem did not occur in 1.12, and it may be due to the finer-grained operators in 2.0.

After adjusting XLA_IR_SHAPE_CACHE_SIZE to ten times the original value, the performance became normal. Therefore, we may consider setting the default value of XLA_IR_SHAPE_CACHE_SIZE to a more aggressive value.

**Comment by JackCaoG** [comment]
Thanks for the investigation! We noticed some diffusion models slows down, we will also try to verify your finding.

**Comment by JackCaoG** [comment]
While we are verifying the issue,  I might as well 5x the shape cache for now. Currently value seems too small given the model size growing.
