### ISSUE TITLE
gdb not working for pytorch/xla

### ISSUE THREAD

**Issue by vanbasten23** [pytorch/xla#5017]
## 🐛 Bug

After pytorch/xla started using bazel, I noticed that running gdb wouldn't show any code when it stoped at the break point. Consequently, I couldn't use gdb to debug my program.

## To Reproduce

1. Build pytorch/xla: `/workspaces/work/pytorch/xla$ BAZEL_REMOTE_CACHE=1 SILO_NAME="cache-silo-xiowei-v4" TPUVM_MODE=1  BUILD_CPP_TESTS=0 DEBUG=1  python setup.py install --user 2>&1 | tee ./out.txt`
2. In a new terminal in vscode
```
sudo -i
export HOME=/home/ptxla
cd /workspaces/work
export PJRT_DEVICE=TPU_LEGACY
export XLA_EXPERIMENTAL="nonzero:masked_select"
cgdb python
```
3. 
```
(gdb) break torch_xla::XLANativeFunctions::expand_copy_symint
(gdb) run pytorch/xla/test/ds/test_dynamic_shapes.py TestDynamicShapes.test_simple_expand
```

After running the above program, it would hit the break point, but it wouldn't show the code as before:
```
#0  0x00007ffe6fbf1760 in torch_xla::XLANativeFunctions::expand_copy_symint(at::Tensor const&, c10::ArrayRef<c10::SymInt>, bool)@plt () from /home/ptxla/.local/lib/python3.8/site-p
ackages/torch_xla-2.1.0-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so
```
![image](https://github.com/pytorch/xla/assets/5279639/e75137fa-0c8f-48d2-ad19-d7357a9401a3)

## Expected behavior

As before, when gdb stops at a break point, it should show the code in pytorch/xla.

## Environment

 - Reproducible on XLA backend [CPU/TPU]: TPU
 - torch_xla version: nightly

## Additional context

cc: @JackCaoG

**Comment by vanbasten23** [comment]
hi @stgpetrovic , can you please take a look? Thanks.

**Comment by stgpetrovic** [comment]
Hey there, thanks for all the helpful info.

I'm using `gdb`, and I just have to set up the `dir` for the sources, `dir /path/to/root/of/xla`, and it works.

The binary has debug info (5.5G). 
```
file build/temp.linux-x86_64-3.8/bazel-bin/_XLAC.so
build/temp.linux-x86_64-3.8/bazel-bin/_XLAC.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=e7f4d0436b7bc9fe08a03afc78422de6eecf66e9, with debug_info, not stripped
```

```
hread 1 "python3" hit Breakpoint 1, 0x00007ffe7bc7f3b0 in torch_xla::XLANativeFunctions::expand_copy_symint(at::Tensor const&, c10::ArrayRef<c10::SymInt>, bool)@plt ()
   from /root/.local/lib/python3.8/site-packages/torch_xla-2.1.0-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so
(gdb) l
2       ./Programs/python.c: No such file or directory.
(gdb) list
2       in ./Programs/python.c
(gdb) list
2       in ./Programs/python.c
(gdb) n
Single stepping until exit from function _ZN9torch_xla18XLANativeFunctions18expand_copy_symintERKN2at6TensorEN3c108ArrayRefINS5_6SymIntEEEb@plt,
which has no line number information.
torch_xla::XLANativeFunctions::expand_copy_symint (self=..., sym_size=..., implicit=255) at torch_xla/csrc/aten_xla_type.cpp:1254
1254                                                      bool implicit) {
(gdb) list
1249                                                            /*storage_offset=*/0);
1250    }
1251
1252    at::Tensor XLANativeFunctions::expand_copy_symint(const at::Tensor& self,
1253                                                      at::SymIntArrayRef sym_size,
1254                                                      bool implicit) {
1255      TORCH_LAZY_FN_COUNTER("xla::");
1256      c10::optional<at::IntArrayRef> size = c10::asIntArrayRefSlowOpt(sym_size);
1257      if (size.has_value()) {
1258        return bridge::AtenFromXlaTensor(tensor_methods::expand(
(gdb) 
```

my commands:

```
gdb python3
> break torch_xla::XLANativeFunctions::expand_copy_symint
> dir /workspaces/xla
> run test/ds/test_dynamic_shapes.py TestDynamicShapes.test_simple_expand
```
Not sure how exporting `HOME` works for `gdb`, but I just always set the `dir`.

Hope that helps. Let me know otherwise and I can take a closer look.

**Comment by vanbasten23** [comment]
Thanks. I got the `No such file or directory` as in
```
#2  0x00007ffe712b82b8 in c10::asIntArrayRefSlow (ar=..., file=0x7ffe8a42fea0 "torch_xla/csrc/aten_xla_type.cpp", line=1244) at bazel-out/k8-dbg/bin/external/torch/_virtual_includes/headers
/c10/core/SymIntArrayRef.h:37
37      bazel-out/k8-dbg/bin/external/torch/_virtual_includes/headers/c10/core/SymIntArrayRef.h: No such file or directory.
```

How can I tell gdb/cgdb to find the above file? I tried `(gdb) dir /workspaces/work/pytorch/xla/bazel-out/k8-dbg/bin/torch_xla/csrc` and `(gdb) dir /workspaces/work/pytorch/xla/bazel-out/` but neither works.

**Comment by stgpetrovic** [comment]
I think that just setting the dir to the base is enough, the root directory where bazel-out symlink lives. The paths are relative from there. For external stuff, you'll need the bazel-xla dir, so

```
dir /home/goranpetrovic/work/pytorch/xla/build/temp.linux-x86_64-cpython-38/
dir /home/goranpetrovic/work/pytorch/xla/build/temp.linux-x86_64-cpython-38/bazel-xla/
list

(gdb) list code
file: "external/com_google_absl/absl/status/status.cc", line number: 240, symbol: "absl::lts_20230125::Status::code() const"
235       }
236       status_internal::StatusRep* rep = RepToPointer(rep_);
237       return static_cast<int>(rep->code);
238     }
239
240     absl::StatusCode Status::code() const {
241       return status_internal::MapToLocalCode(raw_code());
242     }
243
```

works for me. I used `python3 setup.py bdist_wheel` to build it that adds a build/temp.linux..... symlink prefix to the command line so the stuff is there. If you build with `bazel build` it will be in the root of the workspace though.

**Comment by vanbasten23** [comment]
> I think that just setting the dir to the base is enough

Can you be more specific? Let's say my vscode has a folder like `ptxla@t1v-n-15d4adcb-w-0:/workspaces/work/pytorch/xla$ `. What's the `base` in order for me to see the file c10/core/SymIntArrayRef.h in pytorch?

**Comment by stgpetrovic** [comment]
Cool. It will depend on how you build your code, but if you use the `setup.py` then I'd do the following:

```
dir /workspaces/work/pytorch/xla
dir /home/goranpetrovic/work/pytorch/xla/build/temp.linux-x86_64-cpython-38/
dir /home/goranpetrovic/work/pytorch/xla/build/temp.linux-x86_64-cpython-38/bazel-xla/
dir /home/goranpetrovic/work/pytorch/xla/build/temp.linux-x86_64-cpython-38/bazel-out/
```

If you build with `bazel build //:_XLAC.so` then you'd do

```
dir /workspaces/work/pytorch/xla
dir /home/goranpetrovic/work/pytorch/xla/bazel-xla/
dir /home/goranpetrovic/work/pytorch/xla/bazel-out/
```

The reason for the difference is that `setup.py` changes the location of the symlink, and runs bazel like this:
```
bazel build //:_XLAC.so --symlink_prefix=build/temp.linux-x86_64-cpython-38/bazel-
```

If in doubt, you can always find the file and add that root dir, e.g. in this case if you need `c10/core/SymIntArrayRef.h`, then you could `find -L . -name "SymIntArrayRef.h" 2>/dev/null` and see where the files are. But it will usually be one of the two above.
