### ISSUE TITLE
Lower count_nonzero

### ISSUE THREAD

**Issue by A9isha** [pytorch/xla#5031]
## 🚀 Feature
Request to lower count_nonzero, https://pytorch.org/docs/stable/generated/torch.count_nonzero.html
## Motivation

This op can be used for fixing autoregressive decoding in TPUs for models like GPT-2 which uses positional embedding

E.g.:

**Comment by JackCaoG** [comment]
@vanbasten23 do you want to pick this up when you have some cycle? This is actually not a dynamic op, I think all we need to do is to first convert the element to contains only `0` and `1` using some mask then reduce in the corresponding dimension to get number of non_zero elements.

**Comment by vanbasten23** [comment]
@JackCaoG  Sorry I didn't see your message earlier. Let me book some time for it this week.

**Comment by JackCaoG** [comment]
The pr is merged, this should be reflected on our nightly tmr and next release.

**Comment by vanbasten23** [comment]
Thanks @JackCaoG for the review.

@A9isha , please give it a try when you have time. I'll close the issue for now. In case you find any issue, feel free to reopen it.
