### ISSUE TITLE
How to recover from 'Exception in device=TPU:0' sickness without terminating session?

### ISSUE THREAD

**Issue by hrbigelow** [pytorch/xla#5034]
I ran all cells in the [mnist-training.ipynb](https://colab.research.google.com/github/pytorch/xla/blob/master/contrib/colab/mnist-training.ipynb) colab successfully.  However, during execution of the last cell:

```python
def _mp_fn(rank, flags):
  global FLAGS
  FLAGS = flags
  torch.set_default_tensor_type('torch.FloatTensor')
  accuracy, data, pred, target = train_mnist()
  if rank == 0:
    # Retrieve tensors that are on TPU core 0 and plot.
    plot_results(data.cpu(), pred.cpu(), target.cpu())

xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=FLAGS['num_cores'],
          start_method='fork')
```

I interrupted execution before it was finished.  On trying to restart that cell, I see the following exception.  On further experimentation, the only way to recover from this situation is through:

    Runtime -> Manage Sessions -> Terminate Current Session

and then restart the whole thing.

The 'Restart runtime' option does not work, nor does the 'Disconnect and Delete Runtime option'

Would anyone know of a faster way to recover from this sick state without completely restarting from scratch?  I've seen several issues posted about this but haven't seen a resolution.

```
Exception in device=TPU:0: INTERNAL: From /job:tpu_worker/replica:0/task:0:
2 root error(s) found.
  (0) INTERNAL: stream did not block host until done; was already in an error state
	 [[{{node XRTExecute}}]]
	 [[XRTExecute_G12]]
  (1) INTERNAL: stream did not block host until done; was already in an error state
	 [[{{node XRTExecute}}]]
0 successful operations.
0 derived errors ignored.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 334, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.10/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 328, in _start_fn
    fn(gindex, *args)
  File "<ipython-input-5-8e919fc51ff8>", line 6, in _mp_fn
    accuracy, data, pred, target = train_mnist()
  File "<ipython-input-4-0bb5e5cb92ef>", line 130, in train_mnist
    train_loop_fn(para_loader.per_device_loader(device))
  File "<ipython-input-4-0bb5e5cb92ef>", line 106, in train_loop_fn
    xm.get_ordinal(), x, loss.item(), tracker.rate(),
RuntimeError: INTERNAL: From /job:tpu_worker/replica:0/task:0:
2 root error(s) found.
  (0) INTERNAL: stream did not block host until done; was already in an error state
	 [[{{node XRTExecute}}]]
	 [[XRTExecute_G12]]
  (1) INTERNAL: stream did not block host until done; was already in an error state
	 [[{{node XRTExecute}}]]
0 successful operations.
0 derived errors ignored.
---------------------------------------------------------------------------
ProcessExitedException                    Traceback (most recent call last)
[<ipython-input-5-8e919fc51ff8>](https://localhost:8080/#) in <cell line: 11>()
      9     plot_results(data.cpu(), pred.cpu(), target.cpu())
     10 
---> 11 xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=FLAGS['num_cores'],
     12           start_method='fork')

2 frames
[/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py](https://localhost:8080/#) in join(self, timeout)
    147                 )
    148             else:
--> 149                 raise ProcessExitedException(
    150                     "process %d terminated with exit code %d" %
    151                     (error_index, exitcode),

ProcessExitedException: process 0 terminated with exit code 17
```

**Comment by JackCaoG** [comment]
Colab is currently under the old TPU Node architecture where the TPU is in a remote VM and colab vm has a grpc connection to the TPU. This makes it difficult to clean up the state since you need to restart the remote grpc runtime. We are on our way to deprecate this design to a new TPUVM(take a look at https://github.com/pytorch/xla#running-on-a-single-cloud-tpu-vm) where you can just do `sudo pkill python` to restart runtime.

On the topic of the colab we are still working with them to move the TPU from TPU Node to TPU VM but we currently does not have a timeline yet.

**Comment by hrbigelow** [comment]
Ahh okay.  Thanks @JackCaoG for the clear description.  I didn't realize there were two separate VMs involved.  That makes a lot more sense now to understand the behavior I see.

That will be very nice to move to the TPUVM setup, I look forward to it.
