### ISSUE TITLE
XLA Conflict Error

### ISSUE THREAD

**Issue by RottenLemons** [pytorch/xla#5040]
## ❓ Questions and Help
I am using Kaggle TPU VM v3-8 for this. The python version is 3.8.16. I used the commands:
``!pip uninstall --yes torch torchvision
!pip uninstall --yes cloud-tpu-client
!pip uninstall --yes torch-xla
!pip install torch==2.0.0+cu118 -f https://download.pytorch.org/whl/torch_stable.html
!pip install cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch_xla-2.0-cp38-cp38-linux_x86_64.whl
!pip install scikit-learn ``

Afterward, I imported torch and torch_xla:
``import os
import gc
import glob
import json
from collections import defaultdict
import multiprocessing as mp
from pathlib import Path
from types import SimpleNamespace
from typing import Dict, List, Optional, Tuple
import warnings

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np
import pandas as pd
import PIL.Image as Image
from sklearn.metrics import fbeta_score
from sklearn.exceptions import UndefinedMetricWarning
import torch
import torch.nn as nn
import torch.optim as optim
import torch.utils.data as thd
import torch.nn.functional as F
from torch.autograd import Variable
from tqdm import tqdm
import math
from functools import partial
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold
import torch_xla
import torch_xla.core.xla_model as xm``

I get the error `ImportError: /usr/local/lib/python3.8/site-packages/_XLAC.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtERKS0_PSo`. I am unsure why it is happening as I checked the compatibility between the python, torch and torch_xla version.

**Comment by vanbasten23** [comment]
Feel free to reopen if the error persists. Closing it for now.
