### ISSUE TITLE
Having trouble running cpp unit tests

### ISSUE THREAD

**Issue by vanbasten23** [pytorch/xla#5067]
## 🐛 Bug

Having trouble running cpp unit tests. The command simply failed.

## To Reproduce

```
ptxla@t1v-n-2e71f932-w-0:/workspaces/work/pytorch/xla$ bazel test --config=remote_cache  --remote_default_exec_properties=cache-silo-key=cache-silo-xiowei-v38  //test/cpp/... --test_filter=AtenXlaTensorTestTest.TestSymSizes
...
ERROR: /workspaces/work/pytorch/xla/test/cpp/build/gtest/src/googletest-src/googlemock/test/BUILD.bazel:51:11: no such package 'googletest/test': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /workspaces/work/pytorch/xla/googletest/test and referenced by '//test/cpp/build/gtest/src/googletest-src/googlemock/test:gmock_test_utils'
ERROR: Analysis of target '//test/cpp/build/gtest/src/googletest-src/googlemock/test:gmock_test_utils' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.385s
INFO: 0 processes.
ERROR: Couldn't start the build. Unable to run tests
INFO: Streaming build results to: https://source.cloud.google.com/results/invocations/193ec688-c7ea-4ec9-ac82-90a14187b7e0
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

## Expected behavior

It should run successfully.

## Environment

 - Reproducible on XLA backend [CPU/TPU]: TPU
 - torch_xla version: nightly.

**Comment by kevint324** [comment]
cpp tests are orgnized with cmake rather than bazel so you cannot run them with `bazel test` cmd

you can check `test/cpp/run_tests.sh` for details.

what you can do:

1. build binary `test_ptxla`
2. run ./test_ptxla --gtest_filter=AtenXlaTensorTestTest.TestSymSizes

**Comment by vanbasten23** [comment]
re @kevint324 , pytorch/xla has migrated off of cmake in https://github.com/pytorch/xla/pull/4755. So the code including the tests are using bazel as the sole build system.

**Comment by vanbasten23** [comment]
I was able to run like `ptxla@t1v-n-15d4adcb-w-0:/workspaces/work/pytorch/xla$ bazel test --config=remote_cache  --remote_default_exec_properties=cache-silo-key=cache-silo-xiowei-v4  //test/cpp/... --test_filter=AtenXlaTensorTest.TestGettingSizeOnDynamicTensor` hence closing this issue.
