### ISSUE TITLE
UPDATE: (False alarm - nothing to do with xm.save)  Issue resolved.)  Failed to meet rendezvous 'torch_xla.core.xla_model.save': Socket closed (14)

### ISSUE THREAD

**Issue by hrbigelow** [pytorch/xla#5096]
## 🐛 Bug

UPDATE May 31:  I tried writing the checkpoints to a gcsfuse mounted bucket inside Colab (instead of gdrive).  The crash still occurs.

UPDATE May 31:  I tested it with the newest change to xm.save in [#4926](https://github.com/pytorch/xla/pull/4926), the symptom appears the same.

UPDATE May 31:  I tested it on GCP TPU-VM (v3-8), writing to a gcsfuse mounted bucket.  It succeeded in writing 14 checkpoints without error.

UPDATE May 30:  @will-cromar I see that you [removed xm.rendezvous](https://github.com/pytorch/xla/pull/4926)  from `xm.save` a month ago and I am using a wheel before that commit:

```
!pip install cloud-tpu-client==0.10 torch==2.0.0 torchvision==0.15.1
!pip install https://storage.googleapis.com/tpu-pytorch/wheels/colab/torch_xla-2.0-cp310-cp310-linux_x86_64.whl
```

In light of this new update, can help clarify the proper use of `xm.save` vs. `torch.save`?

In the main [docs](https://pytorch.org/xla/release/2.0/index.html#saving-and-loading-xla-tensors) on how to use `xm.save` it states:

> import torch
> import torch_xla
> import torch_xla.core.xla_model as xm
> xm.save(model.state_dict(), path)
> In case of multiple devices, the above API will only save the data for the master device ordinal (0).

and:

But in in that PR you had written:

> This PR entirely removes rendezvous  from save, so it essentially becomes a thin wrapper around torch.save. That 
> means that code that only calls torch.save from the master (or another subset of replicas) may just drop in xm.save as
> a replacement, without having to call it on every other replica.

It doesn't look like a thin wrapper around torch.save though.  Here is the most recent version of xm.save - it appears that `_xla_sync_multi` will be called no matter what?

```python
def save(data, file_or_path, master_only=True, global_master=False):
  # ...
  should_write_data = not master_only or is_master_ordinal(
      local=not global_master)

  cpu_data = _maybe_convert_to_cpu(data, convert=should_write_data)
  if should_write_data:
    torch.save(cpu_data, file_or_path)


def _maybe_convert_to_cpu(data, convert=True):

  def convert_fn(tensors):
    torch_xla._XLAC._xla_sync_multi(
        tensors, devices=[], wait=True, sync_xla_data=True)
    if not convert:
      return tensors
    return torch_xla._XLAC._xla_get_cpu_tensors(tensors)

  def select_fn(v):
    return type(v) == torch.Tensor and is_xla_tensor(v)

  return ToXlaTensorArena(convert_fn, select_fn).transform(data)

```

This seems to imply that one should now call `xm.save` "from the master" rather than from all replicas, as in:

```python
if xm.is_master_ordinal():
    ...
   xm.save(...)
```

Is that right?

# Original Bug report below

Okay, this is the ORIGINAL bug report.  I don't know if any of this would still occur with the updated `xm.save` or if I'm using it correctly.

I apologize that I cannot simplify this into a minimal reproducible result.  It seems to be dependent on data size and/or timing.  What would be helpful is some conceptual clarification though.  In particular:

What is the effect of the `wait` argument in `xm.mark_step(wait)`?

The symptom:

I had a model running on Google Colab TPU, with:

I did a set of tests on the same model but varying one of the dimension hyperparameters (M, the transformer d_m parameter), so that the size of the checkpoints were different in each of these tests.  I found that above a certain size, the program was only able to save about 4-6 checkpoints before crashing, but before that, it could continue to at least 15-17 checkpoints (I didn't let these continue for lack of time).

| M |   # ckpt before crash | ckpt size |    error
| -- | ------ | --- | ---
| 415 | 8     |              1.03 GB     |  KILLED
| 400|  4      |             1020 MB    |   Failed to meet rendezvous 'torch_xla.core.xla_model.save': Socket closed (14)
| 398 | 6       |            1014 MB    |   KILLED
| 398 | 13      |            1014 MB   |    no error - interrupted by user
| 397 | 16       |           1012 MB   |    no error - interrupted by user
| 396 | 16       |           1009 MB   |    no error - interrupted by user
| 392 | 17       |            999 MB    |   no error - interrupted by user
| 385 | 15       |            981 MB    |   no error - interrupted by user
| 375 | 17       |            955 MB   |    no error - interrupted by user
| 350 | 17       |            891 MB  |     no error - interrupted by user

Note in the code below that `run.params.update_every` is 16, so I am doing 16 iterations of a forward, then backward on the model, in order to accumulate gradients so that I can achieve a larger effective batch size with smaller memory.

The `run.loader` is a `pl.ParallelLoader::per_device_loader`.   I believe `xm.mark_step` is called every time I call `next(run.loader)`.

I tried to reproduce the bug on Google TPU VM v3-8 but could not reproduce it.

The colab file is [here](https://colab.research.google.com/drive/1YLgZaZPC14gxNa3391Y5AHTtwOnUQmTd?usp=sharing)

The train loop is [here](https://github.com/hrbigelow/transformer-aiayn/blob/80509fcd0608674389d6f63e1cf47ac0a6111f31/aiayn/train.py#L162-L217) and reproduced here:

```python
def train_loop_xla(run):
    print(f'{time.ctime()}: xla:{xm.get_ordinal()}: In train_loop_xla', flush=True)
    run.model.train()
    run.opt.zero_grad()
    dev = xm.xla_device()
    R = run.params.report_every

    loss = t.zeros(R, device=dev)
    steps = t.zeros(R, device=dev)
    learn_rates = t.zeros(R, device=dev)
    scalar_loss = t.zeros((), device=dev)

    # fraction of each shard and update_stage contributing to a gradient update
    loss_fraction = run.params.update_every ** -1

    """
    - Every iteration, performs forward and backward, and accumulates gradients
    - Every `update_every` iterations, takes an optimizer step and zeros grad
    - Every `report_every` * `update_every` iterations, issues a report
    """
    while True:
        report = run.step % R 
        stage_start_time = time.time()
        scalar_loss.fill_(0.0)

        # accumulate gradients over `update_every` iterations
        for update_stage in range(run.params.update_every):
            enc_input, dec_input, load_step, epoch = next(run.loader)
            dec_output = run.model(enc_input, dec_input)
            xent = run.model.loss(dec_input, dec_output) * loss_fraction 
            xent.backward()
            with t.no_grad():
                scalar_loss.add_(xent)

        steps[report] = run.step
        loss[report] = scalar_loss
        learn_rates[report] = run.sched.current_lr()

        xm.optimizer_step(run.opt)
        run.opt.zero_grad()

        stage_end_time = time.time()

        if (run.step % run.params.ckpt_every == 0 and 
                run.step > 0 and run.step != run.params.resume_ckpt):
            path = run.params.ckpt_templ.format(run.step)
            # this crashes if not in a step closure
            xm.add_step_closure(run.save, args=(path,))

        if run.step > 0 and report ==  R - 1:
            combined_loss = xm.mesh_reduce('cl', loss, element_mean_fn)
            args = (run.logger, epoch, steps, loss, learn_rates)
            xm.add_step_closure(report_fn, args, run_async=True)
        
        run.step += 1
        run.sched.update(run.step)
```

UPDATE:  I tried this again, saving a checkpoint every 10 steps and saw a slightly different traceback, which does not show the 'Failed to meet rendezvous' error.

```python
1685388673: epoch=0, steps=tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), loss=tensor([10.0455, 10.0481, 10.0578, 10.0400, 10.0419, 10.0339, 10.0331, 10.0146,
        10.0063,  9.9891])
Saved checkpoint /content/drive/MyDrive/ai/ckpt/aiayn/may29-10.pt using xm.save
1685388837: epoch=0, steps=tensor([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.]), loss=tensor([9.9833, 9.9777, 9.9542, 9.9412, 9.9189, 9.9089, 9.8905, 9.8730, 9.8544,
        9.8443])
Saved checkpoint /content/drive/MyDrive/ai/ckpt/aiayn/may29-20.pt using xm.save
1685389018: epoch=0, steps=tensor([20., 21., 22., 23., 24., 25., 26., 27., 28., 29.]), loss=tensor([9.8194, 9.7942, 9.7854, 9.7548, 9.7351, 9.7181, 9.6969, 9.6694, 9.6498,
        9.6466])
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/aiayn/train.py", line 332, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiayn/train.py", line 320, in main
    xmp.spawn(_mp_fn, args=args, nprocs=8, start_method='fork')
  File "/usr/local/lib/python3.10/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 397, in spawn
    result = torch.multiprocessing.start_processes(
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 140, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGKILL
```

Here was the original traceback:

```python
Exception in device=TPU:7: tensorflow/compiler/xla/xla_client/mesh_service.cc:377 : Failed to meet rendezvous 'torch_xla.core.xla_model.save': Socket closed (14)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 334, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.10/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 328, in _start_fn
    fn(gindex, *args)
  File "/usr/local/lib/python3.10/dist-packages/aiayn/train.py", line 144, in _mp_fn
    train_loop_xla(run)
  File "/usr/local/lib/python3.10/dist-packages/aiayn/train.py", line 189, in train_loop_xla
    enc_input, dec_input, load_step, epoch = next(run.loader)
  File "/usr/local/lib/python3.10/dist-packages/torch_xla/distributed/parallel_loader.py", line 30, in __next__
    return self.next()
  File "/usr/local/lib/python3.10/dist-packages/torch_xla/distributed/parallel_loader.py", line 42, in next
    xm.mark_step()
  File "/usr/local/lib/python3.10/dist-packages/torch_xla/core/xla_model.py", line 956, in mark_step
    devctx = _run_step_closures()
  File "/usr/local/lib/python3.10/dist-packages/torch_xla/core/xla_model.py", line 938, in _run_step_closures
    closure()
  File "/usr/local/lib/python3.10/dist-packages/torch_xla/core/xla_model.py", line 920, in <lambda>
    step_closures.append(lambda a=args: closure(*a))
  File "/usr/local/lib/python3.10/dist-packages/aiayn/pause.py", line 73, in save
    xm.save(ckpt, path)
  File "/usr/local/lib/python3.10/dist-packages/torch_xla/core/xla_model.py", line 1065, in save
    rendezvous('torch_xla.core.xla_model.save')
  File "/usr/local/lib/python3.10/dist-packages/torch_xla/core/xla_model.py", line 1112, in rendezvous
    return torch_xla._XLAC._xla_rendezvous(get_ordinal(), tag, payload, replicas)
RuntimeError: tensorflow/compiler/xla/xla_client/mesh_service.cc:377 : Failed to meet rendezvous 'torch_xla.core.xla_model.save': Socket closed (14)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/aiayn/train.py", line 329, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiayn/train.py", line 317, in main
    xmp.spawn(_mp_fn, args=args, nprocs=8, start_method='fork')
  File "/usr/local/lib/python3.10/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 397, in spawn
    result = torch.multiprocessing.start_processes(
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 140, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGKILL
```

**Comment by JackCaoG** [comment]
I replied in the other thread, do you want to try set the `sync` to false in the `xm.save`?

**Comment by hrbigelow** [comment]
Hi Jack,

> I replied in the other thread, do you want to try set the `sync` to false in the `xm.save`?

That doesn't work either unfortunately.  I should probably clarify since by now the title of this issue is misleading.  Although my original error was 'Failed to meet rendezvous 'torch_xla.xla_model.save', on further tests, I simply got a backtrace with 'SIGKILL' at the end, and no mention of a rendezvous.  

Then, I tried with both versions of xm.save.  For the one with the rendezvous, I used the one available in Colab (note it doesn't have the sync option)

![image](https://github.com/pytorch/xla/assets/5355286/0077ec6b-7617-4111-8787-6a7052c98753)

For one without the rendezvous, I just copy-pasted the most recent version:

```python
def xm_save(data, file_or_path, master_only=True, global_master=False):
    should_write_data = not master_only or xm.is_master_ordinal(
        local=not global_master)

    cpu_data = _maybe_convert_to_cpu(data, convert=should_write_data)
    if should_write_data:
        torch.save(cpu_data, file_or_path)

def _maybe_convert_to_cpu(data, convert=True):
    def convert_fn(tensors):
        torch_xla._XLAC._xla_sync_multi(
                tensors, devices=[], wait=True, sync_xla_data=True)
        if not convert:
            return tensors
        return torch_xla._XLAC._xla_get_cpu_tensors(tensors)

    def select_fn(v):
        return type(v) == torch.Tensor and xm.is_xla_tensor(v)

    return xm.ToXlaTensorArena(convert_fn, select_fn).transform(data)
```

**Comment by hrbigelow** [comment]
> I replied in the other thread, do you want to try set the `sync` to false in the `xm.save`?

Hi Jack,

Sorry I couldn't find the other thread you mention.   Can you please post a link to it?

**Comment by JackCaoG** [comment]
Ah OK I think now I understand the question better. You are right that `xm.save` is a wrapper around the `torch.save`. What it does is it 

1. materialize the tensor by calling `_xla_sync_multi`, you can think of this is a small `mark_step` but only materailze subset of tensors
2. Move the tensor to CPU
3. call torch.save()

We only expect the master ordinal to save the checkpointing, we are still working on distributing checkpointing and GSPMD model parallel training. That's the background.

**Comment by hrbigelow** [comment]
I haven't attempted to try to get a minimum reproducible error, since the SIGKILL arises sporadically:  only after some (small) number of successfully saved checkpoints, and tends to increase with model checkpoint size around the 1014 MB level (but even this is stochastic).  But, I'll look into trying to get a minimal example.

In any case, that colab is [here](https://colab.research.google.com/drive/1YLgZaZPC14gxNa3391Y5AHTtwOnUQmTd?usp=sharing)

I'm definitely willing to try to help debug this.  I'm going to put in a lot of print statements at the different stages.  But I do note also that it seems like even with `flush=True` on the child processes, they don't always make it to the terminal.

Just out of curiosity, how do you debug this?  Is there any way to get more direct information about the cause?  The stack trace has nothing of interest.

**Comment by JackCaoG** [comment]
This is a bit of a special case. Most of our failure is a CHECK failure error which point us to the line(python or C++) that causing it. Your particular issue seems can't be repo consistently. 

That being said, most common reason for SIGKILL is running out of the RAM. Can you try to monitor the machine RAM while `checkpointing` is happening using `ps -aux` or `htop`?

**Comment by hrbigelow** [comment]
I'm working on a simple repro colab, by the way.  I'm already seeing some peculiar things, will post as soon as it is ready.

**Comment by hrbigelow** [comment]
> This is a bit of a special case. Most of our failure is a CHECK failure error which point us to the line(python or C++) that causing it. Your particular issue seems can't be repo consistently.
> 
> That being said, most common reason for SIGKILL is running out of the RAM. Can you try to monitor the machine RAM while `checkpointing` is happening using `ps -aux` or `htop`?

I'm happy to do this, although I can't figure out how to get Colab to display htop output properly.

Is there some way to do it on a per-device level inside _mp_fn to report the memory in the context of executing code?  I guess this still doesn't work since the execution model is asynchronous...

**Comment by hrbigelow** [comment]
Okay, so all of the SIGKILL are going away once I use a lock (either manually, or with `MpModelWrapper`.  Large checkpoints are saving, and everything is functioning normally in the minimal test.  I'm updating the title to reflect this and also going to close this issue since it has nothing to do with xm.save.

**Comment by JackCaoG** [comment]
Glad to see that it worked!

**Comment by hrbigelow** [comment]
Thanks for the help Jack.  Much appreciated.
