### ISSUE TITLE
Couldn't run cpp unit tests with remote cache enabled

### ISSUE THREAD

**Issue by vanbasten23** [pytorch/xla#5133]
## 🐛 Bug

Couldn't run cpp unit tests with remote cache enabled.

## To Reproduce

In the vscode development environment ([set up doc](https://docs.google.com/document/d/1X2Z0VmKjVV6vlUTRmu-soWW8RcDOyshxZSdSUZLkc-U/edit?resourcekey=0-yjGpRCaBlMBIEW0WFoa0qw#bookmark=id.xaa5do61ce0c)), open a terminal in the vscode, then do 
```
ptxla@t1v-n-0d95297d-w-0:/workspaces/work$ export GCLOUD_SERVICE_KEY_FILE=~/.config/gcloud/application_default_credentials.json
ptxla@t1v-n-0d95297d-w-0:/workspaces/work$ gcloud auth application-default login --no-launch-browser
...
Credentials saved to file: [/home/ptxla/.config/gcloud/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).

Quota project "tpu-pytorch" was added to ADC which can be used by Google client libraries for billing and quota. Note that some services may still bill the project owning the resource.

ptxla@t1v-n-0d95297d-w-0:/workspaces/work/pytorch/xla$ export PJRT_DEVICE=CPU
ptxla@t1v-n-0d95297d-w-0:/workspaces/work/pytorch/xla$ bazel test --config=remote_cache  --remote_default_exec_properties=cache-silo-key=cache-silo-xiowei-v3888  //test/cpp/... --test_filter=AtenXlaTensorTest.TestCount_Nonzero_with_multiple_dims
INFO: Invocation ID: 2f0178b2-7db3-4eb4-98f3-925ab2e39391
ERROR: Failed to query remote execution capabilities: Unexpected error refreshing access token
WARNING: The background upload of the Build Event Protocol for the previous invocation failed with the following exception: 'com.google.devtools.build.lib.util.AbruptExitException: The Build Event Protocol upload failed: All retry attempts failed. UNAVAILABLE: 'int com.google.api.client.http.HttpResponseException.getAttemptCount()' UNAVAILABLE: 'int com.google.api.client.http.HttpResponseException.getAttemptCount()''. Ignoring the failure and starting a new invocation...
INFO: Streaming build results to: https://source.cloud.google.com/results/invocations/2f0178b2-7db3-4eb4-98f3-925ab2e39391
```

Note this error doesn't always happen. The above command worked yesterday but didn't work today, even if I opened a brand new terminal and run ` gcloud auth application-default login --no-launch-browser` to refresh the token.

## Expected behavior

We should be able to run the cpp unit tests without any errors.

## Environment

 - Reproducible on XLA backend [CPU/TPU]: TPU
 - torch_xla version: nightly

## Additional context

cc: @JackCaoG

**Comment by vanbasten23** [comment]
hi @stgpetrovic , I wonder if you have seen such issue or have some insight on how to work around it. Thanks!

**Comment by stgpetrovic** [comment]
I'd have to try and reproduce the steps to be sure, but if you run the setp.py it will put the gcloud auth token environment variable and stick it to bazel.commandline as --google_credentials=path/to/auth.json, and if you run bazel yourself you have to either have the gcloud default auth set up or pass the flag yourself, the env var is not used by bazel, only by our setup.py.

See [our bazel docs](https://github.com/pytorch/xla/blob/master/docs/bazel.md#remote-caching) for details.

If this is not the issue I will try and reproduce it. Thanks

**Comment by vanbasten23** [comment]
> if you run bazel yourself you have to either have the gcloud default auth set up or pass the flag yourself

Thanks for the explanation. By `have the gcloud default auth set up`, do you mean setting up as 
```
export GCLOUD_SERVICE_KEY_FILE=~/.config/gcloud/application_default_credentials.json
```
?
If so, I have done it.

**Comment by stgpetrovic** [comment]
Td gcloud auth can be set in multiple ways. [Here](https://cloud.google.com/docs/authentication/application-default-credentials) is the documentation. I usually login using gcloud CLI, but then I have to re-login I think or just set the env var. One env var is used by bazel (from the link here) and the other by setup.py (the above service key). I am not sure where the shell relogin fits here.

**Comment by stgpetrovic** [comment]
Hey there, the link is in the "here" word:
https://cloud.google.com/docs/authentication/application-default-credentials

Hope that helps.

**Comment by vanbasten23** [comment]
Got it. Thanks.
