### ISSUE TITLE
xla::slice is still creating a viewTensor after functionalization

### ISSUE THREAD

**Issue by vanbasten23** [pytorch/xla#5168]
When I symintify xla::slice operation, I found that xla::slice ([code](https://github.com/pytorch/xla/blob/50821daccd08637f4cbd1d8c888e181b3c00124e/torch_xla/csrc/tensor_methods.cpp#L2330-L2331)) is still using `view` after functionalization. I wonder if we can prioritize the work to get rid of `view` in PyTorch/XLA's code base..

cc @alanwaketan @wonjoolee95

**Comment by alanwaketan** [comment]
Here is the updated section of the tasks: https://docs.google.com/document/d/1d1u8oLrL7iZz55NbCfQSYzwLP4M60kb7igvdBVE_X7s/edit?resourcekey=0-W3QvBNHNPUeX84-TkRJjlA#bookmark=id.w80eshe0q1dj

We can use the doc to track the progress.

**Comment by alanwaketan** [comment]
All the tasks are completed.
