### ISSUE TITLE
Moving from multicore single-TPU traning to pod training

### ISSUE THREAD

**Issue by vanIvan** [pytorch/xla#5205]
## ❓ Questions and Help

Hello! I'm sorry for a bit dummy question, but I was not able to find any documentation guidelines (except for [this](https://cloud.google.com/tpu/docs/pytorch-pods) one) on how to go from multicore single-TPU to pod training? If I had my training script that supports multicore single-TPU training, do I only need to run something like, to make it work on pod (assuming that I have data on shared NFS connected to all TPU-VM)?:
```sh
gcloud compute tpus tpu-vm ssh ${TPU_NAME} \
  --zone=${ZONE} \
  --worker=all \
  --command="XRT_TPU_CONFIG=localservice;0;localhost:51011 python3 ~/train.py"
```
or I should change something in dataloading / optimizer steps in train script etc.? Will it work with XRT or I should better move to PJRT?

**Comment by JackCaoG** [comment]
We are in the process of deprecating the XRT, I would recommend you try out the PJRT following https://github.com/pytorch/xla/blob/master/docs/pjrt.md#tpu. Switching to Pod is super easy for PJRT, checkout https://github.com/pytorch/xla/blob/master/docs/pjrt.md#pods

**Comment by vanIvan** [comment]
Thank you for response, I'll try to make version of pipeline with PJRT.
