### ISSUE TITLE
[SPMD][AMP]  Invalid sharding for instruction when using AMP in SPMD.

### ISSUE THREAD

**Issue by baoleai** [pytorch/xla#5248]
## 🐛 Bug

When training using AMP in SPMD, it raises error as follows

Non-OK-status: status.status() status: INVALID_ARGUMENT: during context [Unknown]: Invalid sharding for instruction: %add.388 = f32[] add(f32[] %constant.382, f32[] %convert.387), sharding={devices=[1,4]0,1,2,3}: Number of tile assignment dimensions (excluding subgroups) is different than the input rank. sharding={devices=[1,4]0,1,2,3}, input_shape=f32[]

## To Reproduce
There is a simple example to reproduce the bug:

test_spmd_amp.py
```
import numpy as np
import torch
import torch.utils.checkpoint
import torch_xla.core.xla_model as xm
import torch_xla.experimental.xla_sharding as xs
from torch import nn
from torch_xla.amp import autocast, GradScaler, syncfree
from torch_xla.experimental.xla_sharding import Mesh


class SimpleLinear(nn.Module):

  def __init__(self):
    super(SimpleLinear, self).__init__()
    self.fc0 = nn.Linear(1024, 1024)
    self.fc1 = nn.Linear(1024, 1024)
    self.fc2 = nn.Linear(1024, 1024)
    self.fc3 = nn.Linear(1024, 1024)
    self.relu = nn.ReLU()


  def forward(self, x):
    h = self.relu(self.fc0(x))
    y = self.relu(self.fc1(h) + x)
    z = self.fc3(y)
    return z

def run():
    device = xm.xla_device()
    model = SimpleLinear().to(device)

    num_devices = 4
    devices_ids = np.arange(num_devices)
    row_mesh = Mesh(devices_ids, (num_devices, 1), ('x', 'y'))
    col_mesh = Mesh(devices_ids, (1, num_devices), ('x', 'y'))

    xs.mark_sharding(model.fc1.weight, col_mesh, (0, 1))
    xs.mark_sharding(model.fc2.weight, row_mesh, (0, 1))

    optimizer = syncfree.AdamW(model.parameters(), lr=0.0, betas=(0.9, 0.999), eps=1e-8)
    scaler = GradScaler()

    for step in range(5):
        dummy_data = torch.zeros(64, 1024, device=device)
        x = dummy_data
        with autocast():
            x = model(x)
            dummy_loss = x.sum()
            scaler.scale(dummy_loss).backward()
            scaler.step(optimizer)
            scaler.update()
            optimizer.zero_grad()
            xm.mark_step()
        print(step)


if __name__ == "__main__":
    run()
```

```
XLA_USE_SPMD=1 torchrun --nproc_per_node=4 examples/test_spmd_amp.py
```

## Environment

 - Reproducible on XLA backend [CPU/TPU]: GPU
 - torch_xla version: master
 

The error is caused by the code located at https://github.com/pytorch/xla/blob/master/torch_xla/csrc/xla_lower_util.cpp#L972. The root cause of the error is that we are attempting to shard a scalar value.
So, one possible solution could be to avoid sharding the scalar value. #5249 @JackCaoG @yeounoh

**Comment by JackCaoG** [comment]
Thanks, I think we should stop the sharding annotation being added to the scalar tensor at first place(assuming this is not supported). Do you know how the annotation being added to this scalar at first place? I only see `mark_sharding` being applied to `model.fc1.weight` and `model.fc2.weight`

**Comment by JackCaoG** [comment]
Ah it might be from https://github.com/pytorch/xla/blob/f6409de35892a0d52e88412ad563b74a7a439dc0/torch_xla/csrc/tensor_util.cpp#L603. I am looking into another issue which might be due to the same cause. Let me see if I can fix that first.

**Comment by baoleai** [comment]
The error sharding XLAOp is created in AdamOptimizerStep(XLANode) https://github.com/pytorch/xla/blob/master/torch_xla/csrc/xla_lower_util.cpp#L972, and its sharding is the same as AdamOptimizerStep which is set at https://github.com/pytorch/xla/blob/master/torch_xla/csrc/xla_graph_executor.cpp#L543 (not quite sure).
It seems like the XLAOp in XLANode share the same ShardingSpec, so it is hard to specify Sharding for each XLAOp?

**Comment by JackCaoG** [comment]
Ah good finding.

**Comment by JackCaoG** [comment]
Thanks, I am able to confirm that in the HLO
```
  %add.382 = f32[] add(f32[] %constant.376, f32[] %convert.381), sharding={devices=[1,8]0,1,2,3,4,5,6,7}
```

in the `ColelctSyncTensor` you pointed out I am able to see
```
set sharding for ir with shape [] xla::adam_optimizer_step, num_outputs=5, xla_shape=(f32[], f32[1024,1024]{1,0}, f32[1024,1024]{1,0}, f32[1024,1024]{1,0}, f32[1024,1024]{1,0})
```
`adam_optimizer_step` op has 5 outputs, all of them will inherit the sharding that is being set on IR. The usage of `adam_optimizer_step` is from https://github.com/pytorch/xla/blob/e45cf4041b38d61611b0eb5a082435410d2a720e/torch_xla/amp/syncfree/_functional.py#L21

`adam_optimizer_step_` in https://github.com/pytorch/xla/blob/e45cf4041b38d61611b0eb5a082435410d2a720e/torch_xla/csrc/tensor_methods.cpp#L516-L520  calls `SetInPlaceIrValue` which will preserve the sharding spec from the original tensor.

I think the fix in https://github.com/pytorch/xla/pull/5249 will solve this problem, but I am wondering if it is better to handle the `adam_optimizer_step_` case separately, I think this is the only case where one IR has > 2 outputs. We actually should not try to manually set sharding to all outputs in this case...

**Comment by baoleai** [comment]
Thanks @JackCaoG , `syncfree.AdamW` is not the only case, `syncfree.SGD` will also casue this issue.

**Comment by JackCaoG** [comment]
Ok I think what's the root cause. There are two concepts here `IR Node` can have multiple outputs, `IR Value` represent one output of the `IR Node`. Currently there is only one sharding spec on the `IR Node`, but that's incorrect. Each output of the `IR Node` should have a separate sharding spec. In the `adam_optimizer_step` case above, not every output of the Node should inherit the sharding spec(because of the in place op). I will work on a proper fix.
