### ISSUE TITLE
[SPMD] Change PrepareOutputShardingPropagation to async to reduce gaps between steps

### ISSUE THREAD

**Issue by baoleai** [pytorch/xla#5250]
## 🚀 Feature

Can we change `PrepareOutputShardingPropagation` in https://github.com/pytorch/xla/blob/master/torch_xla/csrc/xla_graph_executor.cpp#L1076 to async one to reduce the gaps between training steps. 
@JackCaoG @yeounoh 
## Motivation

When using SPMD, there are gaps between steps in timeline, this may be caused by `PrepareOutputShardingPropagation`.

**Comment by baoleai** [comment]
Can we parallelize for loop in https://github.com/pytorch/xla/blob/master/torch_xla/csrc/xla_sharding_util.cpp#L534

**Comment by JackCaoG** [comment]
How many overhead has you observed by this function? This function happens before grabing the device lock so it should still be overlapped with previous step's execution(I think). As long as execution is longer than tracing than this should not become a big issue. One thing we can look at is how to cache some of the placeholders. For the most part we are executing the same graph we already know how output sharding will look like.

**Comment by baoleai** [comment]
In my experiments, the overhead is about 10%~30%.

**Comment by ManfeiBai** [comment]
Hi, @JackCaoG, is it ok to assign this issue to you?

**Comment by baoleai** [comment]
One simple but quick fix is to change https://github.com/pytorch/xla/blob/master/torch_xla/csrc/xla_sharding_util.cpp#L510
to 
```
const auto& computation_proto = computation->computation().proto();
```
to avoid actual copy. 
In my case, this operation is the most time-consuming part of function PrepareOutputShardingPropagation?

**Comment by JackCaoG** [comment]
@baoleai oh yea, we should not copy the proto, it is huge. If you send a pr I can approve it.
