### ISSUE TITLE
PR from forked branch fails CI

### ISSUE THREAD

**Issue by lsy323** [pytorch/xla#5255]
## 🐛 Bug

Forked PR will fail CI with ambiguous bazel error `error: command '/usr/local/bin/bazel' failed with exit code 37`([example](https://github.com/pytorch/xla/actions/runs/5369070657/jobs/9765088094?pr=5249)). Thanks for @stgpetrovic, it turns out that the failure is due to repository secrets are not available for forks. Then env var `GCLOUD_SERVICE_KEY` at [here](https://github.com/pytorch/xla/blob/f6409de35892a0d52e88412ad563b74a7a439dc0/.github/workflows/_build.yml#L49) is not correctly set, causing CI to fail.

We need to have forked PR to have access to the secrets.

## To Reproduce
Create PR from forked branch and trigger CI.

cc @JackCaoG @stgpetrovic

**Comment by lsy323** [comment]
cc @malfet to see if any idea on this one

**Comment by lsy323** [comment]
After digging more on the secrets, I found the following [here](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)
>  Although workflows from forks do not have access to sensitive data such as secrets

So it's by design that forks don't have access to repo secrets.

**Comment by ManfeiBai** [comment]
Hi, @lsy323, is it ok to assign this issue to you?

**Comment by lsy323** [comment]
This should already been fixed in https://github.com/pytorch/xla/pull/5259
