### ISSUE TITLE
zeros_like with dtype 

### ISSUE THREAD

**Issue by ailzhang** [pytorch/xla#527]
```
import torch
import torch_xla
import torch_xla_py.utils as xu
import torch_xla_py.xla_model as xm
import pdb
# xla_device = xm.xla_device()
xla_device = 'cpu'
d = torch.rand(3, 3).to(xla_device)
a = torch.zeros_like(d, dtype=torch.int8)
pdb.set_trace()
print(a)
```
Even when `xla_device=cpu`, the script above still complains about `TypeError: _torch_xla_zeros_like() got an unexpected keyword argument 'dtype'`. 
And `torch.zeros_like` with `dtype` should be supported.

**Comment by asuhan** [comment]
The problem is this override: https://github.com/pytorch/xla/blob/master/torch_xla/__init__.py#L8, which is only needed for the optimizer on the JIT path. Is this fix required for a real model or optimizer? Should be an easy fix.

**Comment by ailzhang** [comment]
@asuhan  `zeros_like` is used in maskrcnn model with `dtype` keyword argument. ;) And the override bit me when I create the repro script. Btw why do we have a special override in init? Overriding `aten::zeros_like` doesn't work?

**Comment by asuhan** [comment]
@ailzhang Our JIT path uses `XLATensor` directly, which means the optimizer cannot use the true `zeros_like`. This problem is going away soon, but until then we have to deal with it.
