### ISSUE TITLE
Lower squeeze_copy.dims

### ISSUE THREAD

**Issue by alanwaketan** [pytorch/xla#5276]
In https://github.com/pytorch/xla/pull/5268, we use `t = torch.squeeze(t, dim=tuple(range(tensor_expand)))` and it turns out that squeeze_copy.dims is not lowered. So we should look into this.

On the other hand, maybe @khatwanimohit can restore the loop change to workaround.

cc @wonjoolee95  to help @khatwanimohit to lower the op.

**Comment by wonjoolee95** [comment]
Here is our doc to lower an op -- https://github.com/pytorch/xla/blob/master/OP_LOWERING_GUIDE.md. And here is a link to PyTorch documentation `torch.squeeze`. Let me know if you need more details or help with anything, @khatwanimohit.

**Comment by wonjoolee95** [comment]
Since we already lowered `squeeze.dim`, this lowering was trivial enough to put out a quick PR while I was waiting for my other local builds -- https://github.com/pytorch/xla/pull/5286.

**Comment by alanwaketan** [comment]
Thanks, @wonjoolee95!
