### ISSUE TITLE
Is it possible to use XLA on TPU with BM1684 chip?

### ISSUE THREAD

**Issue by IzhanVarsky** [pytorch/xla#5289]
## ❓ Questions and Help
Hello, I am new to the world of TPU. I have this https://sophon.ai/product/introduce/se5-8.html micro server TPU with BM1684 chip. I tried to install pytorch xla to it (for python 3.8), but every .whl says that it "is not a supported wheel on this platform". Can I use pytorch xla on my TPU or not? If no then how can I find which devices are supported by pytorch xla?

**Comment by JackCaoG** [comment]
I am not aware of https://sophon.ai/product/introduce/se5-8.html, when we talking about TPU we usually means Google TPU. For non-goolgle workoad it is only available on Google Cloud. The issue you run into is just a python whl issue I think, is your machine is on python 3.8? That being said I don't think it will work given I felt like it is a different "TPU".

**Comment by IzhanVarsky** [comment]
Thank you for the response! Yes, I have python 3.8 on my TPU system, but I can't install pytorch xla wheels. So, am I right, that pytorch xla can be used only for Google TPUs but not for other TPU systems?

**Comment by JackCaoG** [comment]
yea, we only support Google TPU.
