### ISSUE TITLE
Can PyTorch/XLA wheel for release branch build with cxx_abi disabled?

### ISSUE THREAD

**Issue by vanbasten23** [pytorch/xla#5325]
Hi @mateuszlewko ,

I wonder if the new wheel build process (with ansible) can disable cxx_abi when it builds a torch_xla wheel for a release branch (such as r2.0). We recently build a torch_xla wheel (on pt/xla branch r2.0, cuda 11.8, python=3.10). From the [log](https://pantheon.corp.google.com/cloud-build/builds;region=us-central1/e115b688-f467-45e4-b19c-a627de605a74?e=13803378&jsmode=o&mods=allow_workbench_image_override&project=tpu-pytorch-releases), it seems it still enables cxx_abi (I see `-D_GLIBCXX_USE_CXX11_ABI=1` in the log above, which make me think it enables cxx_abi. Please correct me if I'm wrong.). Building an official torch_xla with cxx_abi enabled causes torch_xla wheel to be incompatible with torch's wheel.

What we used to do in the release branch, is to first apply a torch patch (as in this [pr](https://github.com/pytorch/xla/commit/dffb9157f16d2fe36d8b56a811840e2f4cb9a566)), then disable the cxx_abi (as in this [pr](https://github.com/pytorch/xla/pull/4134)). So my question is
1. With ansible, does the wheel have cxx abi enabled?
2. If so for above question, with ansible, is it possible to apply the torch patch file first and then set the flag to be false?

Thanks.

cc: @JackCaoG @miladm

**Comment by mateuszlewko** [comment]
Hey,

First some background information.

*Building process*

1. All build related tasks are present in this role:
https://github.com/pytorch/xla/blob/master/infra/ansible/roles/build_srcs/tasks/main.yaml.
They should be self-descriptive, but please reach out if something is
unclear.
2. For non-nightly releases, you should look at Ansible setup version at a
given tag, branch or commit, so in this case branch r2.0:
infra/ansible/roles/build_srcs/tasks/main.yaml#L32-L36
<https://github.com/pytorch/xla/blob/r2.0/infra/ansible/roles/build_srcs/tasks/main.yaml#L32-L36>
-
this is also the step that builds torch_xla.
3. Each ansible.builtin.command task in Ansible has a separate shell
environment, i.e. previous tasks are not polluting env vars of other tasks.
4. Having said that, most tasks are loading env_vars
<https://github.com/pytorch/xla/blob/r2.0/infra/ansible/roles/build_srcs/tasks/main.yaml#L36>
Ansible
dict, which is a combination of vars from the config:
infra/ansible/config/env.yaml#L21-L48
<https://github.com/pytorch/xla/blob/r2.0/infra/ansible/config/env.yaml#L21-L48>
(depending on the arch and accelerator, in this case: common + amd64 +
cuda). Implementation detail: the dicts are combined here
<https://github.com/pytorch/xla/blob/r2.0/infra/ansible/playbook.yaml#L80-L82>
.
*5. Task that builds XLA computation client library, always sets a
parameter `-D_GLIBCXX_USE_CXX11_ABI=1` (in addition to env_vars). *This was
based on the pre-Ansible setup. It can be changed easily. This task is not
running on master (nightly releases) thanks to Bazel migration.

To answer your first question, cxx_abi is explicitly enabled for the XLA
computation client library. It's not explicitly set for PyTorch_XLA, but I
see in the logs it's set anyway (search for "Determined
_GLIBCXX_USE_CXX11_ABI=1" in the logs). I think you need to set it
explicitly to false.
Now the question is, do you want to disable it for all builds or just 2.0?
If just 2.0 then push a new commit to the r2.0 branch with the following
modifications:

1. Remove -D_GLIBCXX_USE_CXX11_ABI=1 from the "Build XLA computation client
library" task: infra/ansible/roles/build_srcs/tasks/main.yaml#L27
<https://github.com/pytorch/xla/blob/r2.0/infra/ansible/roles/build_srcs/tasks/main.yaml#L27>
.

2. Add common env var _GLIBCXX_USE_CXX11_ABI=0 in
https://github.com/pytorch/xla/blob/r2.0/infra/ansible/config/env.yaml#L22.
This will be picked up by all tasks that have environment: "{{ env_vars }}".


*Applying patches*

Sure, it's easy to apply any patches with Ansible. Example of applying TF
patches:
https://github.com/pytorch/xla/blob/r2.0/infra/ansible/roles/fetch_srcs/tasks/main.yaml#L29-L40.
Simply add another task there with the correct directory.

*Testing your changes locally*

You test your changes locally (assuming you have docker installed) by
running the same docker build command as in the cloud build step:
https://screenshot.googleplex.com/6imoM249wTWp2NF.
So run
docker build -f=Dockerfile . --build-arg=accelerator=cuda
--build-arg=arch=amd64 --build-arg=cuda_version=11.8
--build-arg=git_tag=v2.0.0 --build-arg=package_version=2.0
--build-arg=python_version=3.10
--build-arg=ansible_vars='{"accelerator":"cuda","arch":"amd64","cuda_version":"11.8","git_tag":"v2.0.0","package_version":"2.0","python_version":"3.10","pytorch_git_rev":"v2.0.0","xla_git_rev":"v2.0.0"}'
-t="us-central1-docker.pkg.dev/tpu-pytorch-releases/docker/xla:$(echo
r2.0_3.10_cuda_11.8)" -t=local_image

From the infra/ansible directory.

Hope it helps,
Mateusz

**Comment by mateuszlewko** [comment]
Hey,

First some background information.

<ins>Building process</ins>

1. All build related tasks are present in this role:
https://github.com/pytorch/xla/blob/master/infra/ansible/roles/build_srcs/tasks/main.yaml.
They should be self-descriptive, but please reach out if something is unclear.
2. For non-nightly releases, you should look at Ansible setup version at a given tag, branch or commit, so in this case branch r2.0: [infra/ansible/roles/build_srcs/tasks/main.yaml#L32-L36](https://github.com/pytorch/xla/blob/r2.0/infra/ansible/roles/build_srcs/tasks/main.yaml#L32-L36) - this is also the step that builds torch_xla.
3. Each `ansible.builtin.command` task in Ansible has a separate shell
environment, i.e. previous tasks are not polluting env vars of other tasks.
4. Having said that, most tasks are loading env_vars
<https://github.com/pytorch/xla/blob/r2.0/infra/ansible/roles/build_srcs/tasks/main.yaml#L36> Ansible dict, which is a combination of vars from the config: [infra/ansible/config/env.yaml#L21-L48](https://github.com/pytorch/xla/blob/r2.0/infra/ansible/config/env.yaml#L21-L48)
(depending on the arch and accelerator, in this case: common + amd64 + cuda). Implementation detail: the dicts are combined [here](https://github.com/pytorch/xla/blob/r2.0/infra/ansible/playbook.yaml#L80-L82).
5. **Task that builds XLA computation client library, always sets a parameter `-D_GLIBCXX_USE_CXX11_ABI=1` (in addition to env_vars).** This was based on the pre-Ansible setup. It can be changed easily. This task is not running on master branch (nightly releases) thanks to Bazel migration.

To answer your first question, cxx_abi is explicitly enabled for the XLA computation client library. It's not explicitly set for PyTorch_XLA, but I see in the logs it's set anyway (search for `Determined_GLIBCXX_USE_CXX11_ABI=1` in the logs). 
I think you need to set it explicitly to false `0`. 
Now the question is, do you want to disable it for all builds or just 2.0? If just 2.0 then push a new commit to the r2.0 branch with the following modifications:

1. Remove `-D_GLIBCXX_USE_CXX11_ABI=1` from the "Build XLA computation client
library" task: [infra/ansible/roles/build_srcs/tasks/main.yaml#L27](https://github.com/pytorch/xla/blob/r2.0/infra/ansible/roles/build_srcs/tasks/main.yaml#L27).

2. Add common env var `_GLIBCXX_USE_CXX11_ABI=0` in https://github.com/pytorch/xla/blob/r2.0/infra/ansible/config/env.yaml#L22.
This will be picked up by all tasks that have environment: `"{{ env_vars }}"`.

<ins>Applying patches</ins>

Sure, it's easy to apply any patches with Ansible. Example of applying TF
patches: https://github.com/pytorch/xla/blob/r2.0/infra/ansible/roles/fetch_srcs/tasks/main.yaml#L29-L40.
Simply add another task there with the correct directory.

**Testing your changes locally**

You can test your changes locally (assuming you have docker installed) by
running the same docker build command as in the cloud build step:
https://screenshot.googleplex.com/6imoM249wTWp2NF.

In the  `infra/ansible` directory run
```
docker build -f=Dockerfile . --build-arg=accelerator=cuda \
--build-arg=arch=amd64 --build-arg=cuda_version=11.8 \
--build-arg=git_tag=v2.0.0 --build-arg=package_version=2.0 \
--build-arg=python_version=3.10 \
--build-arg=ansible_vars='{"accelerator":"cuda","arch":"amd64","cuda_version":"11.8","git_tag":"v2.0.0","package_version":"2.0","python_version":"3.10","pytorch_git_rev":"v2.0.0","xla_git_rev":"v2.0.0"}' -t=local_image
```

Hope it helps,
Mateusz

**Comment by vanbasten23** [comment]
Thanks @mateuszlewko . I'll give it a try.

**Comment by vanbasten23** [comment]
The [pr](https://github.com/pytorch/xla/pull/5332) has been merged and we started the build. But the build seems [failing](https://pantheon.corp.google.com/cloud-build/builds;region=us-central1/04a3a548-f2c8-4022-a1da-51f56e782118;step=2?e=13803378&jsmode=o&mods=allow_workbench_image_override&project=tpu-pytorch-releases).

**Comment by vanbasten23** [comment]
I looks I need to update the tag v2.0.0 which I did. But the build still failed: [log](https://ffbd4a4e16d8be07d3299ed3a75f22273a33de1281c66659fb8bce8-apidata.googleusercontent.com/download/storage/v1/b/1001674285173.cloudbuild-logs.googleusercontent.com/o/log-8d7d325e-c7bf-4397-9db0-31007926e840.txt?jk=AYvHSRHbY1XT9pGkYEjMnMKn0R0JHvGzhlj4Nr_o9l9oc0L4OZO4VSNWoB2Q_aR-1Vue7zVxpLGUczNMY-wZTkYCa2ptA_jdCbw9aVEEzL4A9IZDhwLHkDEAQllBbALw2IErS7tmFwBwq5wXLOxYSxPW5iQBPVy1D6NPY4GmmADxjLmq63TATk3n8NsjavEDgputD7mUsudB9CZZl1mER5mqkfW61Relx2Nk3Z-iJQXYiKkDjZmVgjkPcBs3LOL1JJmbtbpzFVfAtqh3Fr6Lhv165zRRqOkVmQ_YOvOJFJjjO6bJ_VjVV0aKnPxMCcwqb8W-efmP1eccWnfEUjhkwGFqA_uAF9LwvmI5mkH2ma2LNY7M9c0AzP_f4ZXNGa3j7jqKQ85CPqM8PXkyFoNCci0Qn7TOAMgYgveCM-m6Hkl-ftZ2uIW8QgagsTfyP1jB8VPtO6ZDJyxjcLne9e8yC2yNYMjEmehfEBC4qieCcvZeiTrlUNCAJi0sSGiq0IzzUHP1oR7SHtLkPxgKlAjz53yNZX7NjbQ1qs3WRqzZ1rZQdXbvYsM-_LCEtSarRPvnUY5hOlP1zlKs5q-sOztFRVUrKgaPGIteTaNgPf-4kwRXW37WRhFrAXELVVc-g-8MAqtuCzN4aWtHphrpVfH2RUcajJdDP6lC_6UNx_YhrRVu7ZbnEcAQvKUKqgQy1ElRei1vGDtjYFRYptslmofMbiDxaeRhBdDzdVRoyaY1od1rwhZ9sas9nPWUcWUN4gtyI9w0a6iiZu7i_G_0Oz28Uw29qTyiqINhDg_g6PXBAO-OsMUz7VoSnUqFTCmhqcODv7AeR64o6aKqeI5jgAOPoVPWm2JiPih1BPhSQAVotbzZzJQTSTkBc3KtP2hytG4jwKcLPo7h7hrT3ooPm1_FxTzxkd8oMNY7GBQz59Dj8NPpQbPtv4eNvGm3zPZYsL4BlizzvAZ2iNbUKCZmq7Itnq9pkrz6JWklC8K2wPm5BT5jjxRAt_i0aUQl4bXD9vnbZC2342nQz8Kc9_kC5CTPzPfLlVMBLs_GsykVtewTGC2ToyitFO2J9qT01oe4iJ6tMkXT3Axr0W4P_N00r-SPkxxcxy2a4xscenLcf_m2zHkfiyBRAvVK0JuJ9csEQylxBRARFPE-rSC0gJMSSJD0mO3EvbVUu9WE3Jz0SgAuuEz4y0h_wx3uUFWcSvl4kFadwOXGGUkUjp5xuBuvjNGfS22baOlr4ahm2SawLiqEFXFZAPn3kNzj8749CyV0AFY36JLfUtxKMN1Pi2fngIxqakjKPgx8tooLThBV2Yaq34gcA-xQvdpRWdQeiDtpCFiKVLYuBz861REjH2idjmUdZSFJhd8AJaGhQ-c5whnp_uiuLGxNXL_U4f0zSKV-afx7jDlV9NzJzfBC-oOgTzqhyJYXKSJ8f7RwdMuzm4attBqCgLN0YpBr40PlDHx_5W4xFvWi&isca=1):
- At first, it was able to check out the correct commit
- Then somehow the commit changed: "HEAD is now at 901d154ac Sharding should be per output of IR Node, instead of per IR Node (#5330)". Commit "901d154ac" is the current one at 07/24/2023.

**Comment by vanbasten23** [comment]
I'm able to create a new r2.0 wheel now.
