### ISSUE TITLE
[SPMD] AMP autocast failed when set XLA_USE_SPMD=1

### ISSUE THREAD

**Issue by baoleai** [pytorch/xla#5497]
## 🐛 Bug

AMP autocast failed when set XLA_USE_SPMD=1

## To Reproduce

Let's use the following example

```
import os
import torch

import torch_xla.core.xla_model as xm
from torch_xla.amp import autocast


os.environ["XLA_USE_SPMD"] = "1"

device = xm.xla_device()
t1 = torch.ones([2,3], device=device, dtype=torch.float32)
t2 = torch.ones([3,2], device=device, dtype=torch.float32)

with autocast(device, dtype=torch.bfloat16):
  t3 = torch.matmul(t1, t2)

print(t3.dtype)
xm.mark_step()
```
, the expected result is `torch.bfloat16`, but when setting `os.environ["XLA_USE_SPMD"] = "1"`, the actual output
is `torch.float32`.

I found that the reason is that when XLA_USE_SPMD is set to 1, the devices in the C++ are all SPMD:0, and PyTorch autocast does not recognize the SPMD:0 device. cc @JackCaoG 

## Environment

 - Reproducible on XLA backend [GPU/TPU]: GPU
 - torch_xla version: master

**Comment by baoleai** [comment]
I commit a fix to use actual device instead of SPMD:0. @JackCaoG

**Comment by baoleai** [comment]
Hi, @JackCaoG, do you have any plans or suggestions to address this issue?

**Comment by yeounoh** [comment]
Hi @baoleai, thanks for reporting. I will take a look, cc @JackCaoG

**Comment by yeounoh** [comment]
Hi @baoleai , I wasn't able to repro your issue, but thanks to you, was able to identify an issue where `torch_xla.amp.autocast` works as-is with SPMD, but not with SPMD. Please take a look at #5570 for more details. By the way, I also left a comment on your PR #5568 , could you verify that you've compiled/installed `torch` with `USE_CUDA=0` and `torch_xla` with `XLA_CUDA=1`?

**Comment by yeounoh** [comment]
Hi @baoleai I was able to reproduce your issue, but with an older commit. Also, we will continue make some changes to #5570 , and circle back when it's ready.

**Comment by baoleai** [comment]
After complied with torch with `USE_CUDA=0` and torch_xla with `XLA_CUDA=1`, my test case still print `torch.float32` without #5568 .

**Comment by yeounoh** [comment]
> After complied with torch with `USE_CUDA=0` and torch_xla with `XLA_CUDA=1`, my test case still print `torch.float32` without #5568 .

Thanks, I think we can address it. Does it work without the SPMD flag?

**Comment by yeounoh** [comment]
Hi @baoleai #5570 landed, and your script runs as expected on a GPU VM. I
```
root@6a5398be93ef:/ansible/pytorch/xla# cat ~/amp_test.py 
import os
import torch
import torch_xla

import torch_xla.core.xla_model as xm
from torch_xla.amp import autocast

os.environ["PJRT_DEVICE"] = "GPU"
os.environ["GPU_NUM_DEVICES"] = "4"
os.environ["XLA_USE_SPMD"] = "1"

device = xm.xla_device()
t1 = torch.ones([2,3], device=device, dtype=torch.float32)
t2 = torch.ones([3,2], device=device, dtype=torch.float32)

with autocast(device, dtype=torch.bfloat16):
  t3 = torch.matmul(t1, t2)
print('t3.dtype=', t3.dtype)

root@6a5398be93ef:/ansible/pytorch/xla# python ~/amp_test.py 
t3.dtype= torch.bfloat16
```

Note that the bfloat16 is not fully supported on XLA:GPU without SPMD and cast to float16 or float32. We will have a full support in the near future.

**Comment by baoleai** [comment]
> Thanks, I think we can address it. Does it work without the SPMD flag?
Yes, because without XLA_USE_SPMD flag, the device will be GPU:0 instead of SPMD:0.

**Comment by yeounoh** [comment]
> > Thanks, I think we can address it. Does it work without the SPMD flag?
> 
> Yes, because without XLA_USE_SPMD flag, the device will be GPU:0 instead of SPMD:0.

I don't think the device type was the root-cause of it. It shouldn't have worked with `torch.bfloat16`? I have a patch so that XLA:GPU can also support bfloat16 -- we can verify again once we land this https://github.com/pytorch/xla/pull/5598. 

For the current issue, the patch has landed. I was able to verify on a V100 machine; if you rebuild `torch_xla` from src with `XLA_CUDA=1`, then your script should print `torch.bfloat16` -- let me know how it goes. Thanks @baoleai

**Comment by yeounoh** [comment]
Hi @baoleai #5598 landed. Does your test script from the issue run with the nightly?

**Comment by baoleai** [comment]
> Hi @baoleai #5598 landed. Does your test script from the issue run with the nightly?

Yes, the test script outputs torch.bfloat16 as expected. Thanks, @yeounoh.
So the key fix code is add the following lines:
```
torch.set_autocast_xla_enabled(True)
torch.set_autocast_xla_dtype(torch.bfloat16)
```
?

**Comment by yeounoh** [comment]
> > Hi @baoleai #5598 landed. Does your test script from the issue run with the nightly?
> 
> Yes, the test script outputs torch.bfloat16 as expected. Thanks, @yeounoh. So the key fix code is add the following lines:
> 
> ```
> torch.set_autocast_xla_enabled(True)
> torch.set_autocast_xla_dtype(torch.bfloat16)
> ```
> 
> ?

No, that's just the context management-related, making sure that when you use `torch_xla.amp.autocast` proper flags are set.

I would say the fix was mostly making sure that we run `xla` backend for autocasting for XLA:GPU instead of `cuda` backend.
