### ISSUE TITLE
The exported_program_to_stablehlo API get wrong stablehlo module

### ISSUE THREAD

**Issue by maxwillzq** [pytorch/xla#5544]
See my colab how to reproduce it https://colab.sandbox.google.com/drive/19tl-6mDAevYiBqSFFEQYe-OuaP4vGyLT?resourcekey=0-GIL9MQCxvdDJZaXg6yQJ9A#scrollTo=etpUIEKOMKDl

for python code

```
import jax

def foo(x, y):
  a = torch.sin(x)
  b = torch.cos(y)
  return a + b

  
torch_inputs = (torch.randn(10, 10), torch.randn(10, 10))
torch_inputs_dev = jax.tree_map(lambda x: x.to(xla_device), torch_inputs)
exported = export(foo, torch_inputs)
stablehlo_program = exported_program_to_stablehlo(exported)
print(stablehlo_program.get_stablehlo_text('forward'))
```

The output is 
```
module @IrToHlo.13 attributes {mhlo.cross_program_prefetches = [], mhlo.dynamic_parameter_bindings = [], mhlo.is_dynamic = false, mhlo.use_auto_spmd_partitioning = false} {
  func.func @main(%arg0: tensor<10x10xf32>, %arg1: tensor<10x10xf32>) -> tensor<10x10xf32> {
    %0 = stablehlo.sine %arg1 : tensor<10x10xf32>
    %1 = stablehlo.cosine %arg0 : tensor<10x10xf32>
    %2 = stablehlo.add %0, %1 : tensor<10x10xf32>
    return %2 : tensor<10x10xf32>
  }
}
```

The output stablehlo text is wrong.

The sine argument should be %arg0 but not %arg1.

```
module @IrToHlo.13 {
  func.func @main(%arg0: tensor<10x10xf32>, %arg1: tensor<10x10xf32>) -> tensor<10x10xf32> {
    %0 = stablehlo.sine %arg0 : tensor<10x10xf32>
    %1 = stablehlo.cosine %arg1 : tensor<10x10xf32>
    %2 = stablehlo.add %0, %1 : tensor<10x10xf32>
    return %2 : tensor<10x10xf32>
  }
}
```

**Comment by maxwillzq** [comment]
@qihqi PTAL

**Comment by qihqi** [comment]
So the stablehlo text's inputs does not necessarily match the original input list; and that is expected.

If the model have parameters, other constants etc, those might also become (extra) inputs to this function.
The mapping of original inputs to inputs to stablehlo function is stored in the `_bundle` field, along with other metadata.

Please refer this function: https://github.com/pytorch/xla/blob/master/torch_xla/stablehlo.py#L40

**Comment by maxwillzq** [comment]
Thanks a lot, @qihqi.  So you means the stablehlo function inputs order maybe not same as the pytorch function input args ?
So only the stablehlo is not enough to get all information to reproduce it in JAX ? We need also pass the _bundle info ?
Thanks a lot
