### ISSUE TITLE
How do I install XLA 2.0 or XLA 2.1 on Google Cloud TPU in a Anaconda Environment?

### ISSUE THREAD

**Issue by mukhtarhussainbaloch** [pytorch/xla#5566]
## ❓ Questions and Help
Please forgive my ignorance. I am new to the TPU world. I want to create an anaconda environment and install pytorch with XLA. I am unable to find XLA 2.0 and XLA 2.1 packages on anaconda. When I use pip i only get xla version 1. Can somebody help me please.

**Comment by JackCaoG** [comment]
Hey Can you take a look at https://github.com/pytorch/xla#wheel? We are trying to get our 2.1 whl on pypi so you can pip install for 2.1 when it is out.

**Comment by mukhtarhussainbaloch** [comment]
1. I created a new conda environment and activated it
2. conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
3. pip install https://storage.googleapis.com/pytorch-xla-releases/wheels/tpuvm/torch_xla-nightly-cp310-cp310-linux_x86_64.whl

ERROR: torch_xla-nightly-cp310-cp310-linux_x86_64.whl is not a supported wheel on this platform.

Am I missing something ?

**Comment by JackCaoG** [comment]
I am a bit confuse, why do you need to install cuda? If you are using TPU you don't want to install cuda on it. 

The error is most likely because the python version. the whl above is for python 3.10, if you are using python 3.10, you can do
```
pip3 install https://storage.googleapis.com/pytorch-xla-releases/wheels/tpuvm/torch-nightly-cp310-cp310-linux_x86_64.whl
https://storage.googleapis.com/pytorch-xla-releases/wheels/tpuvm/torch_xla-nightly-cp310-cp310-linux_x86_64.whl
```

if you are using python 3.8, replac ethe `310` in above links to `38`

**Comment by mukhtarhussainbaloch** [comment]
Thank you for the clarification. The installation went smoothly this time.

**Comment by tjingrant** [comment]
Just want to add that I had the same issue without using Anaconda. The problem seems to be specific to the `tpu-vm-pt-2.0` base image, switching to the `tpu-ubuntu2204-base` image the problem goes away.
