### ISSUE TITLE
Run CPP test with nightly image/wheels on GPU

### ISSUE THREAD

**Issue by ManfeiBai** [pytorch/xla#5638]
## ❓ Questions and Help

Hi, @mateuszlewko and @stgpetrovic 

when I try to run CPP test on GPUVM, I would try two solutions, and both of them failed with most tests failed in 0ms:
- try nightly gpu wheel like: 
   - torch: `pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/cuda/118/torch-nightly-cp38-cp38-linux_x86_64.whl`
   - torch_xla: `pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/cuda/118/torch_xla-nightly-cp38-cp38-linux_x86_64.whl`
   - issue: `PJRT_DEVICE=GPU GPU_NUM_DEVICES=X bash test/cpp/run_tests.sh` will most tests failed with 0ms
- try nightly image:
   - image: `us-central1-docker.pkg.dev/tpu-pytorch-releases/docker/xla:nightly_3.8_cuda_11.8`
   - issue: need install nightly torch/torch_xla wheel or build torch/torch_xlafrom scratch, `PJRT_DEVICE=GPU GPU_NUM_DEVICES=X bash test/cpp/run_tests.sh` will most tests failed with 0ms

so what would be the direct way to run CPP tests under `xla/test/cpp` on GPUVM?

and Do we missed any env setup if we met this test result?:
```
+ bazel test //torch_xla/csrc/runtime:all //test/cpp:all --test_timeout 1000
//test/cpp:test_aten_xla_tensor_1                                     NO STATUS
//test/cpp:test_aten_xla_tensor_2                                     NO STATUS
//test/cpp:test_aten_xla_tensor_4                                     NO STATUS
//test/cpp:test_aten_xla_tensor_5                                     NO STATUS
//test/cpp:test_aten_xla_tensor_6                                     NO STATUS
//test/cpp:test_ir                                                    NO STATUS
//test/cpp:test_lazy                                                  NO STATUS
//test/cpp:test_replication                                           NO STATUS
//test/cpp:test_tensor                                                NO STATUS
//test/cpp:test_xla_backend_intf                                      NO STATUS
//test/cpp:test_xla_sharding                                          NO STATUS
//test/cpp:test_aten_xla_tensor_3                               FAILED TO BUILD
//torch_xla/csrc/runtime:async_task_test                                 PASSED in 0.2s
//torch_xla/csrc/runtime:cache_test                                      PASSED in 0.0s
//torch_xla/csrc/runtime:sys_util_test                                   PASSED in 0.0s
//torch_xla/csrc/runtime:util_test                                       PASSED in 0.1s
//torch_xla/csrc/runtime:xla_util_test                                   PASSED in 0.2s
```

cc @vanbasten23

**Comment by mateuszlewko** [comment]
Hey Manfei,

Unfortunately I don't have any context on those cpp tests.

**Comment by ManfeiBai** [comment]
Thanks, Mateusz!

hi, @miladm, I will close this old issue due to GPU focus change
