### ISSUE TITLE
OP lowering for `_prelu_kernel_backward`

### ISSUE THREAD

**Issue by Edelbert** [pytorch/xla#5695]
## 🚀 Feature

Hello! I found out that there is no xla op for `nn.PReLU`, although  `_prelu_kernel` is [supported](https://github.com/pytorch/xla/blob/v2.1.0/codegen/xla_native_functions.yaml#L269), it looks like its not about  `nn.PReLU` function. For the sake of example, I added `PReLU` functions into default [example](https://github.com/pytorch/xla/blob/v2.1.0/test/test_train_mp_mnist.py#L45) .

```
class MNIST(nn.Module):

  def __init__(self):
    super(MNIST, self).__init__()
    self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
    self.prelu1 = nn.PReLU(10)
    self.bn1 = nn.BatchNorm2d(10)
    self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
    self.prelu2 = nn.PReLU(20)
    self.bn2 = nn.BatchNorm2d(20)
    self.fc1 = nn.Linear(320, 50)
    self.prelu3 = nn.PReLU(50)
    self.fc2 = nn.Linear(50, 10)

  def forward(self, x):
    x = self.prelu1(F.max_pool2d(self.conv1(x), 2))
    x = self.bn1(x)
    x = self.prelu2(F.max_pool2d(self.conv2(x), 2))
    x = self.bn2(x)
    x = torch.flatten(x, 1)
    x = self.prelu3(self.fc1(x))
    x = self.fc2(x)
    return F.log_softmax(x, dim=1)
```

Debug output
```
Counter: aten::_prelu_kernel_backward
  Value: 305

pt-xla-profiler: TransferFromServerTime too frequent: 311 counts during 105 steps
pt-xla-profiler: Op(s) not lowered: aten::_prelu_kernel_backward,  Please open a GitHub issue with the above op lowering requests.
```

Packages version:
```
torch                    2.1.0
torch-xla                2.1.0
```

**Comment by JackCaoG** [comment]
@zpcore can you take this one?

**Comment by zpcore** [comment]
> @zpcore can you take this one?

Sure, I can take a look. Thanks

**Comment by Edelbert** [comment]
@zpcore just wanna add, that with packages `torch==2.0.0 torch-xla==2.0.0` this op does not appear in debug output as not lowered one and training goes just fine.

**Comment by JackCaoG** [comment]
It is possible that this op either does not exist or pytorch change their dispatching logic of `PReLU_backward` to this `_prelu_kernel_backward` between 2.0 and 2.1.

**Comment by zpcore** [comment]
_prelu_kernel_backward already exists in 2.0: https://github.com/pytorch/pytorch/blob/c263bd43e8e8502d4726643bc6fd046f0130ac0e/tools/autograd/derivatives.yaml#L2009.
