### ISSUE TITLE
XLA dynamo bridge breaks when there are CPU outputs

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/xla#5722]
## 🐛 Bug

Running Torchbench benchmarks, such as `hf_GPT2`, with XLA dynamo bridge fails due to non-XLA tensors present in the output of a `GraphModule`. 

## To Reproduce

Run the following program:

```python
import torch
import torch_xla.core.xla_model as xm

device = xm.xla_device()

def foo(x):
    return (x + x).cpu()

x = torch.randn(5, device=device)

expected = foo(x)
print(expected)

actual = torch.compile(backend="openxla")(foo)(x)
print(actual)
```

```python
  File "torch/_dynamo/backends/torchxla.py", line 49, in fwd
    compiled_graph = bridge.extract_compiled_graph(model, args)
  File "xla/torch_xla/core/dynamo_bridge.py", line 533, in extract_compiled_graph
    extract_internal(fused_module), node.args, None)
  File "xla/torch_xla/core/dynamo_bridge.py", line 337, in extract_internal
    dumb_return_handler, xla_args_need_update) = extract_graph_helper(xla_model)
  File "xla/torch_xla/core/dynamo_bridge.py", line 284, in extract_graph_helper
    graph_hash = torch_xla._XLAC._get_graph_hash(args_and_out)
RuntimeError: torch_xla/csrc/aten_xla_bridge.cpp:95 : Check failed: xtensor
*** Begin stack trace ***
        tsl::CurrentStackTrace[abi:cxx11]()
        torch_xla::bridge::GetXlaTensor(at::Tensor const&)
```

## Environment

PyTorch/XLA: 5dfcec90ca2dd33d2361adf981677cc0978186fa (Oct 21)

**Comment by ysiraichi** [comment]
One possible solution is to use the `CapabilityBasedPartitioner` to ignore nodes where `node.meta["val"]` (populated by FX proxies) is on CPU. While this works, we may be also ignoring programs that wouldn't fail (e.g. if we use the CPU tensor as indices).

**Comment by JackCaoG** [comment]
yea this is a bit annoying.. What should happen is that we extract the computation that happens on the XLA device, execute the graph and then do things like `res = res_xla.cpu()` to return the final output.

I think currently what happened is that during 
https://github.com/pytorch/xla/blob/43cd6b50d8a66d8337db28b328e6c80f797fc888/torch_xla/core/dynamo_bridge.py#L253

the actual execution has already happened, because `xla_out` contains tensor on CPU. This is against the idea where `xla_out = xla_model(*xla_args)` only captures the graph and not executing anything.

@ezyang is there anyway to make dynamo only ignore the `cpu` in the fx graph and execute that on the side if it is the output of the graph? Otherwise the only idea in my mind is we traverse the fx graph, remove the `.cpu`  in the graph module and then manually do `res = res_xla.cpu()` before returning result back to dynamo..

**Comment by JackCaoG** [comment]
I think https://github.com/pytorch/xla/issues/5676 failed for the same reason.

**Comment by ysiraichi** [comment]
Problem is: there are all sorts of CPU tensors out there, e.g. `full(..., device="cpu")` (appears in the graph). What do you think of my [solution](https://github.com/pytorch/xla/issues/5722#issuecomment-1776037233)?

**Comment by JackCaoG** [comment]
oh.. actually I think what you propose might just works. I was under a wrong impression that if we use the partitioner it just ignore the whole compuations that lead to a CPU tensor. However I think we just separate all `.cpu`  in a separate graph which is exactually what we want. Let's give that approach a try. Mixing CPU and XLA tensor(for example indexing) is a rare use case anyway.

**Comment by ezyang** [comment]
> @ezyang is there anyway to make dynamo only ignore the cpu in the fx graph and execute that on the side if it is the output of the graph? Otherwise the only idea in my mind is we traverse the fx graph, remove the .cpu in the graph module and then manually do res = res_xla.cpu() before returning result back to dynamo..

I think, typically, we would expect a graph pass to change the device on which operations are executed. @eellison was working on that pass.

**Comment by miladm** [comment]
Thanks Ed.
qq: @eellison do you have a PR in flight?

**Comment by eellison** [comment]
Sorry for delay - I can land PR this week. However right now it is only enabled in inductor.  We'd need further work to extend to other backends.

**Comment by ysiraichi** [comment]
@eellison I think I can work on that once your PR lands.

**Comment by JackCaoG** [comment]
This is amazing! Thanks @eellison !

**Comment by miladm** [comment]
Here is the torch_xla [PR](https://github.com/pytorch/xla/pull/5922). Thanks everyone!
