### ISSUE TITLE
Good first issue for torch dynamo bridge?

### ISSUE THREAD

**Issue by AsakusaRinne** [pytorch/xla#5730]
## ❓ Questions and Help

Dear developers, 

I'm an AI Engineer who's interested in torch.fx and torch dynamo. In the early of this year, I made an adaption of fx for [Oneflow](https://github.com/Oneflow-Inc/oneflow) (see [one-fx](https://github.com/Oneflow-Inc/one-fx)). I'm also using pt-xla to train my model now. I'm very much looking forward to participating in the development of the bridge between pt-xla and torch dynamo ([this doc](https://nebula2.alibaba-inc.com/log/logview/xdl/view?task_id=c0ed2eb060b64787a528710d2bc237e0) says there're still some feature gaps).

I followed the [contributing guide](https://github.com/pytorch/xla/blob/master/CONTRIBUTING.md) to try to find a `good first issue` or `help wanted` but couldn't find one. Could you please tell me something about how to start with? I really appreciate that!

**Comment by JackCaoG** [comment]
Hey @AsakusaRinne Thanks for the interest. I think there are a couple different focus on the dynamo development now.

@wonjoolee95 is working on fully enabling the SPMD with Dynamo
@ysiraichi is working on increase the dynamo coverage for pytorch/xla by fixing runtime crashes and will later focus on dynamo + Pytorch/XLA GPU perfomrance
I am mainly working with upstream to enable the single step graph for fwd+ bwd.

I think one good starting project is to test which features upstream in dynamo work/does not work with torch_xla bridge. I actually does not follow too cloesely with the new features on dynamo end. Another place to start i to play with dynamo with more models and see which one breaks and figure out why.

**Comment by AsakusaRinne** [comment]
Thank you for the suggestions! I think enabling the SPMD with Dynamo is the most attractive to me because I also used it in my work. I'll follow the tips to get familiar with XLA and contributing first. Hope I could have the opportunity to push XLA forward with this community. :)
