### ISSUE TITLE
Supporting the Core ATen Opset

### ISSUE THREAD

**Issue by wonjoolee95** [pytorch/xla#5764]
## 🚀 Feature
As PyTorch/XLA tries to support the PyTorch core ATen opset in its entirety, it requires lowering each core ATen op in PyTorch/XLA. As of today, most of these ops are already lowered. This issue will serve as a tracker for our support of the core ATen opset.

## Unlowered core ATen ops

- [ ] AtenAcos_AutoI32
- [ ] AtenAcosh_AutoI32
- [ ] AtenArangeStartStep
- [ ] AtenAsStrided
- [ ] AtenAsStrided_AutoI32
- [ ] AtenAsin_AutoI32
- [ ] AtenAsinh_AutoI32
- [ ] AtenAtan2_AutoI32
- [ ] AtenAtan_AutoI32
- [ ] AtenAvgPool2dBackward
- [ ] AtenAvgPool2dBackward_AutoI32
- [ ] AtenCdistForward_AutoI32
- [ ] AtenCol2im
- [ ] AtenConvolutionBackward
- [ ] AtenCos_AutoI32
- [ ] AtenCosh_AutoI32
- [ ] AtenEmbeddingDenseBackward
- [ ] AtenEmptyStrided
- [ ] AtenErf_AutoI32
- [ ] AtenExp_AutoI32
- [ ] AtenExpm1_AutoI32
- [ ] AtenFull
- [ ] AtenGelu_AutoI32
- [ ] AtenGridSampler2d
- [ ] AtenGridSampler2d_AutoI32
- [ ] AtenIsinf_AutoI32
- [ ] AtenIsnan_AutoI32
- [ ] AtenMaxPool2dWithIndicesBackward
- [ ] AtenMeanDim_AutoI32
- [ ] AtenMean_AutoI32
- [ ] AtenNativeBatchNormLegitNoStats
- [ ] AtenNativeBatchNormLegitNoStats_AutoI32
- [ ] AtenNativeBatchNormLegit
- [ ] AtenNativeBatchNormLegit_AutoI32
- [ ] AtenNativeGroupNormBackward
- [ ] AtenNativeGroupNorm_AutoI32
- [ ] AtenNativeLayerNormBackward
- [ ] AtenNativeLayerNorm_AutoI32
- [ ] AtenPdistForward
- [ ] AtenPdistForward_AutoI32
- [ ] AtenPixelShuffle
- [ ] AtenPixelShuffle_AutoI32
- [ ] AtenPowTensorTensor_AutoI32
- [ ] AtenRand
- [ ] AtenRandn
- [ ] AtenRandperm_AutoI32
- [ ] AtenReflectionPad3d
- [ ] AtenReflectionPad3d_AutoI32
- [ ] AtenReplicationPad3d
- [ ] AtenReplicationPad3d_AutoI32
- [ ] AtenRsqrt_AutoI32
- [ ] AtenScalarTensor
- [ ] AtenSigmoid_AutoI32
- [ ] AtenSin_AutoI32
- [ ] AtenSliceScatter
- [ ] AtenSqrt_AutoI32
- [ ] AtenSymNumel
- [ ] AtenSymSizeInt
- [ ] AtenSymStorageOffset
- [ ] AtenSymStrideInt
- [ ] AtenTopk

**Comment by danielvegamyhre** [comment]
Would working on lowering some of these core ATen ops into Pytorch/XLA be a good first issue for a new contributor? If so, I can work on some, perhaps starting with `AtenAcos_AutoI32`?

**Comment by JackCaoG** [comment]
Absolutely! You can take a look at https://github.com/pytorch/xla/blob/master/OP_LOWERING_GUIDE.md and https://github.com/pytorch/xla/blob/master/CODEGEN_MIGRATION_GUIDE.md to get some background on how to do lowering. You can also check recently merged pr of lowering for reference.

**Comment by danielvegamyhre** [comment]
Awesome, I'll take a look, thanks!

**Comment by miladm** [comment]
cc @qihqi

**Comment by wonjoolee95** [comment]
Marking this as complete, https://github.com/pytorch/xla/projects?type=classic&query=Core+Aten+Opset.
