### ISSUE TITLE
Saving Compiler Cache?

### ISSUE THREAD

**Issue by tjingrant** [pytorch/xla#5801]
## ❓ Questions and Help
Curious is it possible to export and save compilation cache to disk so that they can be re-used? This is helpful for development when the compute graph is large and recompilation is slow (minutes to tens of minutes).

**Comment by JackCaoG** [comment]
Good timing, @jonb377 is working on https://github.com/pytorch/xla/pull/5800

**Comment by tjingrant** [comment]
Fantastic, looking forward to trying it out!

**Comment by jonb377** [comment]
Three PRs to enable this:
- #5800 to add the PersistentCache class
- #5803 to ensure the compilation environment changes the hash
- #5804 to serialize the PjRtLoadedExecutable to disk through PersistentCache

I will work on landing these and post back once the feature is in nightly.

**Comment by jonb377** [comment]
@tjingrant All PRs have been merged, the functionality will be included in the nightly build starting tomorrow and also in the upcoming 2.2 release.

To use, set the `XLA_PERSISTENT_CACHE_PATH` environment variable to the desired cache location. If you want the cache to be readonly (e.g. on a subset of workers in an SPMD context), you can control this by setting `XLA_PERSISTENT_CACHE_READ_ONLY`.

Please let me know if you hit any issues!

**Comment by jonb377** [comment]
Added a Python API to control the cache in #6046, you can follow the api guide for usage details: https://github.com/pytorch/xla/blob/master/API_GUIDE.md#compilation-caching

We will likely be removing direct control of the cache through the environment variables in the future.
