### ISSUE TITLE
[Core ATen Opset] Lower aten_sin

### ISSUE THREAD

**Issue by wonjoolee95** [pytorch/xla#5897]
In order for PyTorch/XLA to support the PyTorch core ATen opset, it requires lowering each core ATen op in PyTorch/XLA. This issue is used to track the PyTorch/XLA lowering for **aten_sin**.

Here are some general guidelines to lowering this op:
  - Uncomment `@unittest.skip` or `@unittest.expectFailure` and run the unit test at [test_core_aten_ops.py](https://github.com/pytorch/xla/blob/master/test/test_core_aten_ops.py). Eg: `pytest test/test_core_aten_ops.py -k test_aten_sin_0`
  - Make code changes until the test passes. Read and follow [fix_lowering_for_core_aten_ops.md](https://github.com/pytorch/xla/blob/master/FIX_LOWERING_FOR_CORE_ATEN_OPS.md) for ideas to fix.
    - There may be multiple unit tests for a single op. For this op, the corresponding unit tests are:
      - test_aten_sin_3
    - Please also uncomment the skips for all these tests and ensure all tests are fixed.
    - Note that sometimes the fix may be to fix the unit tests itself. Please take a look at the corresponding unit tests to make sure the tests are valid.
  - Submit the PR!

For any questions, feel free to leave a comment in this PR.

**Comment by ShatilKhan** [comment]
Hi @wonjoolee95 
Please assign me this issue

**Comment by ShatilKhan** [comment]
Hi, thanks for assigning
I'm  new to PyTorch 
I read the docs a bit & found some setup guides, not sure which one to follow
I found this [PyTorch Notebook](https://www.kaggle.com/code/herbison/pytorch-on-cloud-tpus-multicore-example/notebook) on Kaggle
I read the [CONTRIBUTING](https://github.com/pytorch/xla/blob/master/CONTRIBUTING.md) guide as well , should I start here for setting up?
I found the [OP_LOWERING_GUIDE](https://github.com/pytorch/xla/blob/master/OP_LOWERING_GUIDE.md) too , reading through it.
If any maintainers could provide some guidance or tips to getting started that would be very helpful

**Comment by wonjoolee95** [comment]
Sure thing! Glad you'll be working on this, these should be good first issues to start contributing and get familiar with PyTorch/XLA. To answer your questions:

> I found this [PyTorch Notebook](https://www.kaggle.com/code/herbison/pytorch-on-cloud-tpus-multicore-example/notebook) on Kaggle, is it possible to run the tests in such environments?

Kaggle won't be a good place for you to *develop* (or make code edits to) PyTorch/XLA source code. You should be using your own dev environment, preferably within a docker as mentioned in the answer to the second question below. 

> I read the [CONTRIBUTING](https://github.com/pytorch/xla/blob/master/CONTRIBUTING.md) guide as well , should I start here for setting up?

Yes, this is the correct readme to set-up your dev environment. Note that this readme sets up a docker environment, which is the recommended dev set-up.

> I found the [OP_LOWERING_GUIDE](https://github.com/pytorch/xla/blob/master/OP_LOWERING_GUIDE.md) too , reading through it still.

That readme will be useful. And also we have this readme [FIX_LOWERING_FOR_CORE_ATEN_OPS.md](https://github.com/pytorch/xla/blob/master/FIX_LOWERING_FOR_CORE_ATEN_OPS.md), which contains information specific to fixing/lowering these core aten ops. Note that this readme is linked in the description of this issue.

Let me know if you have any more questions.

**Comment by wonjoolee95** [comment]
Hey @ShatilKhan, since we're targetting to close all core aten issues before the 2.3 release, I took over this issue for now. You can take a look at https://github.com/pytorch/xla/pull/6462 to see how I closed the issue. If you're still interesting in contributing, we still have many open issues at https://github.com/pytorch/xla/labels/good%20first%20issue, feel free to assign any to yourself and I'd be happy to help you onboard!
