### ISSUE TITLE
xr.global_runtime_device_count() always return one

### ISSUE THREAD

**Issue by mmseerrttt** [pytorch/xla#5910]
## 🐛 Bug

torch_xla.runtime.global_runtime_device_count() always return one and the value of  GPU_NUM_DEVICES is set to four.

## To Reproduce

run `PJRT_DEVICE=CUDA GPU_NUM_DEVICES=4 python test.py`

the content of test.py as follows
```
import torch_xla
from torch_xla import runtime as xr
print('global_runtime_device_count: ', xr.global_runtime_device_count())
```
output is
```
global_runtime_device_count:  1
```
## Expected behavior

I want the value of xr.global_runtime_device_count() to be equal to the value of GPU_NUM_DEVICES.
or
There is a mistake in my understanding of xr.global_runtime_device_count()

## Environment

 - Reproducible on XLA backend [CPU/TPU]: CUDA
 - torch_xla version: 2.2.0+git4038f8e

## Additional context

None

**Comment by JackCaoG** [comment]
@will-cromar do you mind taking a look?

**Comment by mmseerrttt** [comment]
Motivation of report this bug:

run the `test/spmd/test_train_spmd_imagenet.py` using the following command,
```XLA_USE_SPMD=1 PJRT_DEVICE=CUDA GPU_NUM_DEVICES=4 python test/spmd/test_train_spmd_imagenet.py --fake_data --model=resnet50 --sharding='batch'
```
modify the test_train_spmd_imagenet.py as follows
```
diff --git a/test/spmd/test_train_spmd_imagenet.py b/test/spmd/test_train_spmd_imagenet.py
index 7d472da83..4ed88cc30 100644
--- a/test/spmd/test_train_spmd_imagenet.py
+++ b/test/spmd/test_train_spmd_imagenet.py
@@ -223,6 +223,7 @@ def train_imagenet():
   input_mesh = None
   if FLAGS.sharding:
     num_devices = xr.global_runtime_device_count()
+    print('num_devices :', num_devices)
     device_ids = np.arange(num_devices)
     # Model sharding
     if 'conv' in FLAGS.sharding:
```
then print 
```
num_devices : 1  //  xr.global_runtime_device_count()
Sharding input along batch dimension with mesh [[[[0]]]]
```
Is the value of  xr.global_runtime_device_count() expected?

**Comment by mmseerrttt** [comment]
Is there any progress.

**Comment by will-cromar** [comment]
@vanbasten23 can you take a look?

**Comment by vanbasten23** [comment]
Yep, will look into it.

**Comment by vanbasten23** [comment]
While fixing this issue, I want to mention that spmd is not supported on GPU as of today.

**Comment by JackCaoG** [comment]
not offically supported I think you mean, we know it runs but we haven;'t done enough tests/benchmarking for it yet.

**Comment by mmseerrttt** [comment]
Thanks for your reply. Are there no official support for both fsdp and spmd on GPU?

**Comment by mars1248** [comment]
I had the same problem

**Comment by mars1248** [comment]
> Thanks for your reply. Are there no official support for both fsdp and spmd on GPU?

I tried fsdp and it works, but fsdp and amp are not compatible

**Comment by yeounoh** [comment]
> > not offically supported I think you mean, we know it runs but we haven;'t done enough tests/benchmarking for it yet.
> 
> I saw that spmd in the master branch mentioned "GPU support and optimization will come in the 2.2 release." May I ask if there are relevant branches in iteration for reference?

The GPU support will happen incrementally and over upcoming releases. In 2.2, it will still be experimental (not officially supported). We will update the `spmd.md` doc cc @zpcore @vanbasten23

**Comment by bmeoaountiful** [comment]
> > Thanks for your reply. Are there no official support for both fsdp and spmd on GPU?
> 
> I tried fsdp and it works, but fsdp and amp are not compatible

Did you use fsdp with single card or multi card? I tried fsdp with multi card and encountered a problem as described in https://github.com/pytorch/xla/issues/5089 .

**Comment by mmseerrttt** [comment]
@vanbasten23 hi. Is there any progress in solving this issue.

**Comment by mars1248** [comment]
@mmseerrttt 
I created an issue of running spmd on multiple Gpus for your reference https://github.com/pytorch/xla/issues/6225

**Comment by vanbasten23** [comment]
@mmseerrttt this API currently is only used for spmd case and it has been fixed for that case in https://github.com/pytorch/xla/pull/6022.
