### ISSUE TITLE
[Core ATen Opset] Lower aten_embedding

### ISSUE THREAD

**Issue by wonjoolee95** [pytorch/xla#5982]
In order for PyTorch/XLA to support the PyTorch core ATen opset, it requires lowering each core ATen op in PyTorch/XLA. This issue is used to track the PyTorch/XLA lowering for **aten_embedding**.

Here are some general guidelines to lowering this op:
  - Uncomment `@unittest.skip` or `@unittest.expectFailure` and run the unit test at [test_core_aten_ops.py](https://raw.githubusercontent.com/pytorch/xla/master/test/test_core_aten_ops.py). Eg: `pytest test/test_core_aten_ops.py -k test_aten_embedding_0`
  - Make code changes until the test passes. Read and follow [fix_lowering_for_core_aten_ops.md](https://github.com/pytorch/xla/blob/master/FIX_LOWERING_FOR_CORE_ATEN_OPS.md) for ideas to fix.
    - There may be multiple unit tests for a single op. For this op, the corresponding unit tests are:
      - test_aten_embedding_1
      - test_aten_embedding_2
    - Please also uncomment the skips for all these tests and ensure all tests are fixed.
    - Note that sometimes the fix may be to fix the unit tests itself. Please take a look at the corresponding unit tests to make sure the tests are valid.
  - Submit the PR!

For any questions, feel free to leave a comment in this PR.

**Comment by wonjoolee95** [comment]
Note to assignee: `_embedding_bag` is also a core aten op (https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/native_functions.yaml#L2318C9-L2318C23) and should also be lowered as part of this. Also we should lower the `_embedding_bag_forward_only` according to https://github.com/pytorch/xla/issues/2215.

**Comment by wonjoolee95** [comment]
Hey @bhavya01, this should be a good next op you can work on. We can discuss details in our sync next week.

**Comment by bhavya01** [comment]
Working on implementing EmbeddingBag. Looking at native pytorch implementation, the op handles a bunch of different use cases depending on the inputs. Will open a PR once a basic mean of the embedding vectors is working. https://github.com/pytorch/pytorch/blob/113138aa5575301d914c18bd882d6ab3735aa18a/aten/src/ATen/native/EmbeddingBag.cpp

**Comment by bhavya01** [comment]
Was able to get a basic sum version of embedding bag working using xla::While node. Working on making small changes for mean, max and taking into account other params for the function.

**Comment by wonjoolee95** [comment]
`aten::embedding` is closed with Bhavya's PR https://github.com/pytorch/xla/pull/6495. While Bhavya is working on `aten::embedding_bag` (WIP PR https://github.com/pytorch/xla/pull/6574), we'll mark this issue as closed since `aten::embedding` is lowered.
