### ISSUE TITLE
[Core ATen Opset] Lower aten_relu

### ISSUE THREAD

**Issue by wonjoolee95** [pytorch/xla#5995]
In order for PyTorch/XLA to support the PyTorch core ATen opset, it requires lowering each core ATen op in PyTorch/XLA. This issue is used to track the PyTorch/XLA lowering for **aten_relu**.

Here are some general guidelines to lowering this op:
  - Uncomment `@unittest.skip` or `@unittest.expectFailure` and run the unit test at [test_core_aten_ops.py](https://raw.githubusercontent.com/pytorch/xla/master/test/test_core_aten_ops.py). Eg: `pytest test/test_core_aten_ops.py -k test_aten_relu_0`
  - Make code changes until the test passes. Read and follow [fix_lowering_for_core_aten_ops.md](https://github.com/pytorch/xla/blob/master/FIX_LOWERING_FOR_CORE_ATEN_OPS.md) for ideas to fix.
    - There may be multiple unit tests for a single op. For this op, the corresponding unit tests are:
      - test_aten_relu_2
    - Please also uncomment the skips for all these tests and ensure all tests are fixed.
    - Note that sometimes the fix may be to fix the unit tests itself. Please take a look at the corresponding unit tests to make sure the tests are valid.
  - Submit the PR!

For any questions, feel free to leave a comment in this PR.

**Comment by Nandika-A** [comment]
Hello! can I work in this issue?

**Comment by kurayami07734** [comment]
assign this issue to me

**Comment by wonjoolee95** [comment]
> assign this issue to me

Done!

**Comment by kurayami07734** [comment]
Are there any similar issue which have been merged?
It will be a good reference for me

**Comment by wonjoolee95** [comment]
The description of this issue should have a lot of good information on how to fix these issues. Also you can look at closed issues with label "core aten opset" -- https://github.com/pytorch/xla/issues?q=label%3A%22core+aten+opset%22+is%3Aclosed.

**Comment by wonjoolee95** [comment]
Hey @kurayami07734, I'll take over this issue for now. Let me know if you're interested in contributing to other issues. Thanks!
