### ISSUE TITLE
new torch.bool

### ISSUE THREAD

**Issue by ailzhang** [pytorch/xla#605]
Recently `torch.bool` became a thing. See https://github.com/pytorch/pytorch/commits?author=izdeby Is it mapping to the `xla::PRED` type? 
```
import torch
import torch_xla
import torch_xla_py.utils as xu
import torch_xla_py.xla_model as xm
import pdb
import torch.nn.functional as F
xla_device = xm.xla_device()
# xla_device = 'cpu'
pdb.set_trace()
b = torch.tensor([True, False, True, True, False], dtype=torch.bool).to(xla_device)
```

**Comment by asuhan** [comment]
Yes, I think that'd work. We'll also have to register the tensor type.

**Comment by asuhan** [comment]
Fixed by https://github.com/pytorch/xla/commit/04faa305342b6162c55a93c97910b9f235e4d3fd.

**Comment by dlibenzi** [comment]
I am not sure we are done with bool (pretty certain the contrary), but I guess we can open a new bug for the missing features/bugs.

**Comment by asuhan** [comment]
Yes, I think it's better to have more concrete bugs as we discover them.
