### ISSUE TITLE
core dump in slicing

### ISSUE THREAD

**Issue by ailzhang** [pytorch/xla#607]
```
import torch
import torch_xla
import torch_xla_py.utils as xu
import torch_xla_py.xla_model as xm
import pdb
import torch.nn.functional as F
xla_device = xm.xla_device()
# xla_device = 'cpu'
v = torch.randn(2, 3, 4, 5).to(xla_device)
pdb.set_trace()
y = v[:, :, :, 1]
z = y[:, 1:1, :]
```

**Comment by dlibenzi** [comment]
This is creating a zero-sized dimension.
@ailzhang How urgent is this. The fix to this test is easy, but having a zero-sized dimension is likely to have avalanche effects on all the ops which are downstream.

**Comment by dlibenzi** [comment]
Take it back on the easy part.
We can't just pass stride=0 to XLA, so we'd have to create a special "thing", which can be anything (since has no values), and handle it along the way.
What are the semantics in PT WRT zero-sized dimensions?

**Comment by ailzhang** [comment]
@dlibenzi  This only showed up when I ran pytorch tests on xla tensors, it's not blocking bert/maskrcnn at the moment. Potentially this might be a blocker in the future, imagine most of our slicing indices are variables, they could happen to be a zero slicing and trigger this core dump. 
I feel this is not a blocker but can be a high pri to come up a proper solution? 
Btw pytorch was following numpy's semantics, more discussions can be found https://github.com/pytorch/pytorch/issues/5014

**Comment by dlibenzi** [comment]
Let me fix that first, then we see what happens downstream.

**Comment by asuhan** [comment]
@dlibenzi What avalanche effects do you have in mind? XLA should handle zero-sized dimensions correctly.

**Comment by dlibenzi** [comment]
Places where we do shape ops, and not handle correctly zeros in dimensions.
