### ISSUE TITLE
How to judge the input parameters in an hlo graph, which is the weight of the model

### ISSUE THREAD

**Issue by ckfgihub** [pytorch/xla#6234]
## ❓ Questions and Help
How to judge the input parameters in an hlo graph, which is the weight of the model (that is, the parameters saved by the model and the parameters thought of the model training), is there any good way to judge it in C++ torch xla source code?
  
  for example: (one model of only linear Op) 
  I want to find out the linear bias and weith. In here,   %arg0: bias and   %arg1: weight .

```
   func.func @main(%arg0: tensor<5xf32>, %arg1: tensor<5x10xf32>, %arg2: tensor<1x10xf32>, %arg3: tensor<1x5xf32>) -> tuple<tensor<1x5xf32>, tensor<f32>> {
    %0 = mhlo.reshape %arg0 : (tensor<5xf32>) -> tensor<1x5xf32>
    %1 = "mhlo.transpose"(%arg1) {permutation = dense<[1, 0]> : tensor<2xi64>, xla_shape = "f32[10,5]{0,1}"} : (tensor<5x10xf32>) -> tensor<10x5xf32>
    %2 = "mhlo.fusion"(%0, %arg2, %1) ({
    ^bb0(%arg4: tensor<1x5xf32>, %arg5: tensor<1x10xf32>, %arg6: tensor<10x5xf32>):
      %10 = "mhlo.dot"(%arg5, %arg6) {precision_config = [#mhlo<precision DEFAULT>, #mhlo<precision DEFAULT>]} : (tensor<1x10xf32>, tensor<10x5xf32>) -> tensor<1x5xf32>
      %11 = mhlo.add %10, %arg4 : tensor<1x5xf32>
      mhlo.return %11 : tensor<1x5xf32>
    }) {fusion_kind = #mhlo<fusion_kind kLoop>} : (tensor<1x5xf32>, tensor<1x10xf32>, tensor<10x5xf32>) -> tensor<1x5xf32>  
    %3 = mhlo.subtract %2, %arg3 : tensor<1x5xf32>
    %4 = mhlo.multiply %3, %3 : tensor<1x5xf32>
    %5 = mhlo.constant dense<0.000000e+00> : tensor<f32>
    %6 = mhlo.reduce(%4 init: %5) across dimensions = [0, 1] : (tensor<1x5xf32>, tensor<f32>) -> tensor<f32>
     reducer(%arg4: tensor<f32>, %arg5: tensor<f32>)  {
      %10 = mhlo.add %arg4, %arg5 : tensor<f32>
      mhlo.return %10 : tensor<f32>
    }
    %7 = mhlo.constant dense<2.000000e-01> : tensor<f32>
    %8 = mhlo.multiply %6, %7 : tensor<f32>   
    %9 = "mhlo.tuple"(%2, %8) {xla_shape = "(f32[1,5]{1,0}, f32[])"} : (tensor<1x5xf32>, tensor<f32>) -> tuple<tensor<1x5xf32>, tensor<f32>>
    return %9 : tuple<tensor<1x5xf32>, tensor<f32>>
  }
```

**Comment by yeounoh** [comment]
You are looking at the program shape (input [args: shape] -> [output shape]), which is how I would also do to reason about the inputs and outputs and their shapes. I am not sure if we can differentiate the tensors based on its meanings, like bias vs. weights in c++. We don't track such metadata, and I normally discern based on the shapes and the operands in the HLO. Looking at here
```
%2 = "mhlo.fusion"(%0, %arg2, %1) ({
    ^bb0(%arg4: tensor<1x5xf32>, %arg5: tensor<1x10xf32>, %arg6: tensor<10x5xf32>):
      %10 = "mhlo.dot"(%arg5, %arg6) {precision_config = [#mhlo<precision DEFAULT>, #mhlo<precision DEFAULT>]} : (tensor<1x10xf32>, tensor<10x5xf32>) -> tensor<1x5xf32>
      %11 = mhlo.add %10, %arg4 : tensor<1x5xf32>
      mhlo.return %11 : tensor<1x5xf32>
    }) {fusion_kind = #mhlo<fusion_kind kLoop>} : (tensor<1x5xf32>, tensor<1x10xf32>, tensor<10x5xf32>) -> tensor<1x5xf32>  
```
I would think that arg0->%0 is the bias, arg1->%1 is the weight, and %arg2 is the input.

**Comment by ckfgihub** [comment]
> You are looking at the program shape (input [args: shape] -> [output shape]), which is how I would also do to reason about the inputs and outputs and their shapes. I am not sure if we can differentiate the tensors based on its meanings, like bias vs. weights in c++. We don't track such metadata, and I normally discern based on the shapes and the operands in the HLO. Looking at here您正在查看程序形状(输入[args:shape] -> [输出形状])，这也是我推断输入和输出及其形状的方法。我不确定我们是否可以根据其含义区分张量，比如 c 中的偏差与权重。我们不跟踪这样的元数据，我通常根据HLO中的形状和操作数来识别。
> 
> ```
> %2 = "mhlo.fusion"(%0, %arg2, %1) ({
>     ^bb0(%arg4: tensor<1x5xf32>, %arg5: tensor<1x10xf32>, %arg6: tensor<10x5xf32>):
>       %10 = "mhlo.dot"(%arg5, %arg6) {precision_config = [#mhlo<precision DEFAULT>, #mhlo<precision DEFAULT>]} : (tensor<1x10xf32>, tensor<10x5xf32>) -> tensor<1x5xf32>
>       %11 = mhlo.add %10, %arg4 : tensor<1x5xf32>
>       mhlo.return %11 : tensor<1x5xf32>
>     }) {fusion_kind = #mhlo<fusion_kind kLoop>} : (tensor<1x5xf32>, tensor<1x10xf32>, tensor<10x5xf32>) -> tensor<1x5xf32>  
> ```
> 
> I would think that arg0->%0 is the bias, arg1->%1 is the weight, and %arg2 is the input.我认为arg0->%0是偏差，arg1->%1是权重，%arg2是输入。

**Comment by ckfgihub** [comment]
thank you

**Comment by ckfgihub** [comment]
> You are looking at the program shape (input [args: shape] -> [output shape]), which is how I would also do to reason about the inputs and outputs and their shapes. I am not sure if we can differentiate the tensors based on its meanings, like bias vs. weights in c++. We don't track such metadata, and I normally discern based on the shapes and the operands in the HLO. Looking at here
> 
> ```
> %2 = "mhlo.fusion"(%0, %arg2, %1) ({
>     ^bb0(%arg4: tensor<1x5xf32>, %arg5: tensor<1x10xf32>, %arg6: tensor<10x5xf32>):
>       %10 = "mhlo.dot"(%arg5, %arg6) {precision_config = [#mhlo<precision DEFAULT>, #mhlo<precision DEFAULT>]} : (tensor<1x10xf32>, tensor<10x5xf32>) -> tensor<1x5xf32>
>       %11 = mhlo.add %10, %arg4 : tensor<1x5xf32>
>       mhlo.return %11 : tensor<1x5xf32>
>     }) {fusion_kind = #mhlo<fusion_kind kLoop>} : (tensor<1x5xf32>, tensor<1x10xf32>, tensor<10x5xf32>) -> tensor<1x5xf32>  
> ```
> 
> I would think that arg0->%0 is the bias, arg1->%1 is the weight, and %arg2 is the input.
