### ISSUE TITLE
Mesh shape "(16, 1)" ?

### ISSUE THREAD

**Issue by isaacr** [pytorch/xla#6397]
## ❓ Questions and Help
In looking at  https://pytorch.org/blog/high-performance-llama-2/   specifically: Fig.2 labeled "Llama 2 SPMD Training MFU on TPU v4 with Different Sequence Lengths",    I am trying to understand how to query (determine and then configure) the mesh shape, 
such as "(16, 1)" and "(32, 1)" or "(32, 4)".

Many thanks!

**Comment by JackCaoG** [comment]
This is corresponding to the accelerator you are using. For v4-32, there are 16 TPU chip, so you can use (16, 1), (4, 4) etc. The rule of thumb is usually for mesh shape (x, y, z), `x * y * z == num_device` . For more detial please take a look at https://github.com/pytorch/xla/blob/master/docs/spmd.md#mesh

**Comment by isaacr** [comment]
Thank you. I am looking to validate my understanding of how to properly articulate an accelerator config at creation:

I understand this is controlled via the `--topology` argument, and the values have to be in a certain order, as below. Is there another way ?  

me@cloud % gcloud compute tpus tpu-vm create myTPU --zone=$ZONE  --project=$PROJECT  --type=v4 --topology=2x4x2 --version=tpu-ubuntu2204-base   --network=$NETWORK
ERROR: (gcloud.compute.tpus.tpu-vm.create) INVALID_ARGUMENT: Cloud TPU received a bad request. Invalid AcceleratorConfig: type:V4  topology:"2x4x2" [EID: 0xd04bb6a77a289812]

me@cloud % gcloud compute tpus tpu-vm create myTPU --zone=$ZONE  --project=$PROJECT  --type=v4 --topology=4x2x2 --version=tpu-ubuntu2204-base   --network=$NETWORK
ERROR: (gcloud.compute.tpus.tpu-vm.create) INVALID_ARGUMENT: Cloud TPU received a bad request. Invalid AcceleratorConfig: type:V4  topology:"4x2x2" [EID: 0xc088915b053dccda]

The below is the only combination that works for a v4-32 for me:

me@cloud % gcloud compute tpus tpu-vm create myTPU --zone=$ZONE  --project=$PROJECT  --type=v4 --topology=2x2x4 --version=tpu-ubuntu2204-base   --network=$NETWORK
Create request issued for: [myTPU]
Waiting for operation [projects/XXXXXXXX/locations/us-central2-b/operations/operation-YYYYYYYYY] to complete...⠛                      


How could I use a (16,1) **vs**. a (4,4) ?

Thanks again!

**Comment by JackCaoG** [comment]
I think there is a difference between the TPU physical topology(which is specified when you created TPU) and the `Mesh shape` you want to use for GSPMD. @jonb377 and @alanwaketan should have more info.

**Comment by alanwaketan** [comment]
Yea, the mesh shape you specify in the code is logical. And the topology you create TPU is physical. For best performance, you typically either do 1D sharding (16, 1), or 2D sharding with one axis equals to the product of a combination of the topology axises, say, 4 or 8...

**Comment by isaacr** [comment]
Thanks, so just to make sure my understanding is fully aligned:

1) there's no variability in how the physical topology is established, i.e. the values for TOPOLOGY column in `gcloud compute tpus tpu-vm  list` can never be different for the same TPU, i.e. a V4-32 will always be: "2x2x4" and a V4-128 will always be: "4x4x4"

2) am I correct in inferring (!) that, in Fig 2. at https://pytorch.org/blog/high-performance-llama-2/ :

-  a (16,1) logical mesh was established with "--spmd_2d_sharding 1" 

- and a (32,4) logical mesh was established with "--spmd_2d_sharding 4" ?

 Many thanks!

**Comment by alanwaketan** [comment]
> Thanks, so just to make sure my understanding is fully aligned:
> 
> 1. there's no variability in how the physical topology is established, i.e. the values for TOPOLOGY column in `gcloud compute tpus tpu-vm  list` can never be different for the same TPU, i.e. a V4-32 will always be: "2x2x4" and a V4-128 will always be: "4x4x4"

No, for anything larger than 128, you can specify the topology.

> 2. am I correct in inferring (!) that, in Fig 2. at [pytorch.org/blog/high-performance-llama-2](https://pytorch.org/blog/high-performance-llama-2/) :
> 
> * a (16,1) logical mesh was established with "--spmd_2d_sharding 1"
> * and a (32,4) logical mesh was established with "--spmd_2d_sharding 4" ?

That's correct.

**Comment by isaacr** [comment]
Got it, thanks for the confirmations. Lastly, coming back to the logical data mesh "(4,4)" .... 
is that the resulting shape on a v4-32 when invoked with  "--spmd_2d_sharding 4" ?

**Comment by alanwaketan** [comment]
> Got it, thanks for the confirmations. Lastly, coming back to the logical data mesh "(4,4)" .... is that the resulting shape on a v4-32 when invoked with "--spmd_2d_sharding 4" ?

Yea.
