### ISSUE TITLE
[torchbench] Compile PyTorch with LAPACK support.

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/xla#6400]
## 🐛 Bug

Some benchmarks are not working (internally) because they fallback on operations that rely on LAPACK functions, such as:

```python
Calling torch.geqrf on a CPU tensor requires compiling PyTorch with LAPACK. Please use PyTorch built with LAPACK support.
```

## Affected Benchmarks

- drq
- soft_actor_critic

## Environment

 - Reproducible on XLA backend [CPU/TPU]: CUDA
 - torch_xla version: 9e4db963a196378e7e812bcb58f8f1af6a8f452f

## Additional Context

Probably because PyTorch is not finding LAPACK libraries, an optional dependency, in the system. Thus, compiling it without LAPACK dependent functions support.

cc @miladm @JackCaoG @cota @frgossen

**Comment by cota** [comment]
After `apt install liblapack-dev libopenblas-dev`, the PyTorch installer was able to find the LAPACK library and the benchmarks now run.
