### ISSUE TITLE
Pytorch XLA SPMD CheckpointManager Optimizer Loading Error

### ISSUE THREAD

**Issue by mfatih7** [pytorch/xla#6546]
Hello

I am using CheckpointManager to save and load checkpoints for models with SPMD.
In my training setup, in the first epoch, the model is trained with lossA only.
After the first epoch, the model is trained using lossA and lossB.
There is no problem while loading checkpoints in the later epochs.
But specifically while loading a checkpoint saved after the first epoch I get the error below.

```
  File "/home/THEUSER/17_featureMatching/run_train_TPU.py", line 101, in <module>
    training_results = train_1_1_each_sample_in_single_batch_TPU_spmd_train_and_val(   
  File "/home/THEUSER/17_featureMatching/process/train_1_1_each_sample_in_single_batch_TPU_spmd.py", line 81, in train_and_val
    loss_checkpoint, proc_time_checkpoint = checkpoint.load_checkpoint( config, device, model, optimizer, chkpt_mgr=chkpt_mgr)    
  File "/home/THEUSER/17_featureMatching/checkpoint.py", line 100, in load_checkpoint
    chkpt_mgr.restore( max(tracked_steps), checkpoint )
  File "/home/THEUSER/env3_8/lib/python3.8/site-packages/torch_xla/experimental/distributed_checkpoint/manager.py", line 319, in restore
    dist_cp.load_state_dict(
  File "/home/THEUSER/env3_8/lib/python3.8/site-packages/torch/distributed/checkpoint/state_dict_loader.py", line 31, in load_state_dict
    return _load_state_dict(
  File "/home/THEUSER/env3_8/lib/python3.8/site-packages/torch/distributed/checkpoint/state_dict_loader.py", line 185, in _load_state_dict
    central_plan = distW.reduce_scatter("plan", local_step, global_step)
  File "/home/THEUSER/env3_8/lib/python3.8/site-packages/torch/distributed/checkpoint/utils.py", line 185, in reduce_scatter
    raise result
torch.distributed.checkpoint.api.CheckpointException: CheckpointException ranks:dict_keys([0])
Traceback (most recent call last): (RANK 0)
  File "/home/THEUSER/env3_8/lib/python3.8/site-packages/torch/distributed/checkpoint/utils.py", line 158, in reduce_scatter
    local_data = map_fun()
  File "/home/THEUSER/env3_8/lib/python3.8/site-packages/torch/distributed/checkpoint/state_dict_loader.py", line 175, in local_step
    local_plan = planner.create_local_plan()
  File "/home/THEUSER/env3_8/lib/python3.8/site-packages/torch_xla/experimental/distributed_checkpoint/planners.py", line 228, in create_local_plan
    plan = create_default_local_load_plan(self.unsharded_state_dict,
  File "/home/THEUSER/env3_8/lib/python3.8/site-packages/torch/distributed/checkpoint/default_planner.py", line 228, in create_default_local_load_plan
    md = metadata.state_dict_metadata[fqn]
KeyError: 'optimizer_state_dict'
```

To generate lossB on the computation graph, no extra parameter is generated.
The checkpoint saving and loading operations work well with GPU, TPU single-core, and TPU multi-core runs. The only problem occurs while loading models and optimizers with TPU SPMD runs.

I can provide a repo if needed.

**Comment by JackCaoG** [comment]
@jonb377 wondering if you have any insights

**Comment by jonb377** [comment]
Hey @mfatih7, thanks for raising the issue! Could you please share the repro? Based on the logs, the `optimizer_state_dict` isn't being tracked in the checkpoint metadata. A few things to sanity check:
- The process group is properly configured (e.g. `dist.init_process_group('gloo', init_method='xla://')` for SPMD TPU).
- The state_dict structure is the same when saving and loading.
- The checkpoint is taken *after the first step* to ensure optimizer parameters are initialized.

Also, some care must be taken when restoring optimizer parameters, since the the optimizer parameters aren't initialized until the first `optim.step()` call. This means when restoring optimizer state, you'll potentially need a dummy train step to prime the optimizer state, then restore the checkpoint into the primed optimizer state_dict.

**Comment by mfatih7** [comment]
Hello @jonb377 

Thank you for the answer.
I traced my code and collected lines that have operations regarding SPMD and checkpoints.
I think it will be easier for you to point out my error.
Here are pseudo codes for training and testing.
The order of operations are same they appear in my code.

```
### Training

...
os.environ['PJRT_DEVICE'] = 'TPU'
...
xr.use_spmd()
dist.init_process_group('gloo', init_method='xla://')
...
model = get_model( config, )
model = model.to(device)
...
optimizer = get_optimizer( config, )
...
### save initial checkpoint, only works at the beginning of epoch 0
tracked_steps = chkpt_mgr.all_steps()
if( len(tracked_steps)==0 ):
	checkpoint = get_checkpoint_template(config, model, optimizer, )
	chkpt_mgr.save_async( 0, checkpoint)
...
### load checkpoint, always works, gets the latest recorded checkpoint
checkpoint = get_checkpoint_template( config, model, optimizer, )
tracked_steps = chkpt_mgr.all_steps()
chkpt_mgr.restore( max(tracked_steps), checkpoint )
model.load_state_dict(checkpoint['model_state_dict'])
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
...
if(config.spmd_type == 'batch'):
	mesh_shape = (num_devices, 1, 1, 1)
	input_mesh = xs.Mesh(device_ids, mesh_shape, ('B', 'C', 'W', 'H'))
...
### training loop, save checkpoint after each epoch
for epoch in range(n_epochs):
	...
	### training
	...
	### validation
	checkpoint = {                  
			'model_state_dict': model.state_dict(),
			'optimizer_state_dict': optimizer.state_dict(),
	}
	chkpt_mgr.save_async(epoch, checkpoint)
```

```
### Testing

...
os.environ['PJRT_DEVICE'] = 'TPU'
...
xr.use_spmd()
dist.init_process_group('gloo', init_method='xla://')
...
optimizer = get_optimizer( config, )
...
if(config.spmd_type == 'batch'):
	mesh_shape = (num_devices, 1, 1, 1)
	input_mesh = xs.Mesh(device_ids, mesh_shape, ('B', 'C', 'W', 'H'))
...
### test loop, for every checkpoint recorded during each training epoch
for epoch in range(n_epochs):
	checkpoint = get_checkpoint_template( config, model, optimizer, )
	chkpt_mgr.restore( epoch, checkpoint )
	model.load_state_dict(checkpoint['model_state_dict'])
	model = model.to(device)
	...
	### testing
	...
```
I can prepare the repo also.
It looks like `optim.step()` operations are missing.

**Comment by jonb377** [comment]
Thanks! Can you share the `get_checkpoint_template` code as well?

**Comment by mfatih7** [comment]
Thank you

Here it is

```
def get_checkpoint_template(config, model, optimizer, ):
    ...    
    checkpoint = {
                  ...                  
                  'model_state_dict': model.state_dict(),
                  'optimizer_state_dict': optimizer.state_dict(),
                  ...
                 }
    return checkpoint
```

**Comment by mfatih7** [comment]
@jonb377 I added some lines to the codes

**Comment by jonb377** [comment]
Hmm, I don't see anything glaringly wrong with the approach. A few questions:
- Can you share some more details about when you hit the error? You mentioned it works sometimes, when does it succeed vs fail?
- Could there be a stale checkpoint in the directory that doesn't contain the optimizer state?

**Comment by jonb377** [comment]
Also for some additional context, is this with a single host or are you using multiple hosts?

**Comment by mfatih7** [comment]
In the first message, I pointed out that the error occurs only after the first epoch.
But, today I did lots of experiments with ADAM and SGD optimizers.
I observe the error also in the later epochs.
But for some experiments, no error occurs. Several times I stopped training, got test results, and restarted the training.

**Comment by mfatih7** [comment]
I make experiments on TPUv2 and TPUv3 hardware.
I do not generate meshes with multiple devices.
I am just trying to implement the model on a single device(with 8 cores).
Using SPMD I am generating models that can fit to 8 cores.

**Comment by mfatih7** [comment]
Here is a screenshot of checkpoint files of experiment 105 on one of my VMs.

![image](https://github.com/pytorch/xla/assets/58260582/d40462f7-b353-4c37-bb97-92b7f448fa62)

**Comment by mfatih7** [comment]
And the output of `pip list`

```
torch                        2.3.0.dev20240108+cpu
torch-xla                    2.3.0+git257f0f5
```

**Comment by mfatih7** [comment]
Should I prepare the repo?

**Comment by jonb377** [comment]
Do you know what epoch's checkpoint causes the issue? It sounds like pausing and resuming works, so when you restore from a high epoch there is no issue. I would suspect that it's only an issue with epoch 0, where the checkpoint is taken before any optimizer state is generated.

In your test script, can you try wrapping the restoration in a try/except block and print which epoch causes the error? Like so:

```python
### test loop, for every checkpoint recorded during each training epoch
for epoch in range(n_epochs):
	checkpoint = get_checkpoint_template( config, model, optimizer, )
        try:
	    chkpt_mgr.restore( epoch, checkpoint )
        except:
             print(f"Restore failed at epoch {epoch}")
             continue
	model.load_state_dict(checkpoint['model_state_dict'])
	model = model.to(device)
       
        # You can even omit the actual test logic here
```

**Comment by mfatih7** [comment]
Actually my code is like that

```
while True:
	if(config.tpu_cores != 'spmd'):
		...
	elif(config.tpu_cores == 'spmd'):
		checkpoint = get_checkpoint_template( config, model, optimizer, )

		tracked_steps = chkpt_mgr.all_steps()
		if( len(tracked_steps) ):
			chkpt_mgr.restore( max(tracked_steps), checkpoint )
			print( f"Loaded checkpoint step {max(tracked_steps)} for SPMD operation" )
			break
```

Is this OK?

**Comment by mfatih7** [comment]
At the beginning of the first epoch, I save the checkpoint as checkpoint 0.
And again at the beginning of the first epoch, this checkpoint is loaded without any error for sure.
After the first epoch, the checkpoint is recorded as checkpoint 2.
When I stop during the second epoch and try to restore from the checkpoint I get the error.

This is for failing experiments.
For successful experiments, no error occurs while restoring.

**Comment by mfatih7** [comment]
In your code, `model = model.to(device)` is called after `model.load_state_dict(checkpoint['model_state_dict'])`
In my training code, I do not pass the model to device.
Can you check? Is this erroneous?

**Comment by mfatih7** [comment]
No no, in my original code, I also use `model = model.to(device)`
I am updating the code above also

**Comment by jonb377** [comment]
> In your code, `model = model.to(device)` is called after `model.load_state_dict(checkpoint['model_state_dict'])` In my training code, I do not pass the model to device. Can you check? Is this erroneous?

Oh sorry, I just copy-pasted the test script from above. I've updated to cut the script down to the minimum needed to verify which epoch causes the failure.

**Comment by mfatih7** [comment]
I will insert try and except. Give me 15 minutes for the completion of the first epoch.

**Comment by jonb377** [comment]
Thanks @mfatih7, looking forward to the results!

One other thing that could help with debugging is disabling async checkpointing by using `chkpt_mgr.save` instead of `chkpt_mgr.save_async`.

**Comment by mfatih7** [comment]
OK, I started an experiment with replaced `chkpt_mgr.save_async` commands with `chkpt_mgr.save`
It restored from checkpoint 0 without error.
Now running the first epoch. Let's see.

**Comment by mfatih7** [comment]
@jonb377 With `try `  `except` I do not observe the error. But why?

**Comment by jonb377** [comment]
Hmm that's interesting... With `try/except` the error would be suppressed, but do you see the `print`ed message anywhere in the output?

Also, was this run with `save` or `save_async`?

**Comment by mfatih7** [comment]
That was with `save_async` and you are right it failed. And started to process the first epoch again.

**Comment by jonb377** [comment]
Ah good to hear! So it's not the initial checkpoint which causes the failure then.

That points to the actual train loop as the culprit. A few more questions:
- I notice that you're not using `get_checkpoint_template` in the train loop, can you try using the same helper there? I don't think this will actually be the fix, but it's good to ensure the state_dict has identical structure.
- How are you constructing the CheckpointManager?
- Which optimizer are you using?

**Comment by mfatih7** [comment]
With `get_checkpoint_template` we get the model, optimizer, and epoch number(equal to 0).
Since `try` is unsuccessful, the training uses the epoch number that it gets with `get_checkpoint_template`.
Since it is equal to 0 the training reruns epoch 1.

**Comment by mfatih7** [comment]
Here is the `get_chkpt_mgr` function

```
def get_chkpt_mgr(config):
    from torch_xla.experimental.distributed_checkpoint import CheckpointManager
    chkpt_mgr = CheckpointManager( os.path.join(config.output_path_local, 'checkpoints' ), 1 )
    return chkpt_mgr
```

**Comment by mfatih7** [comment]
For both ADAM and SGD optimizer I get the same error

**Comment by mfatih7** [comment]
For the case in which `save_async` is replaced with `save` I get the same error when I stop training in the second epoch and try to restore.

**Comment by mfatih7** [comment]
Hello @jonb377 

Here is the minimal [repo](https://github.com/mfatih7/checkpoint_SPMD_debug)

Just run the [file](https://github.com/mfatih7/checkpoint_SPMD_debug/blob/main/17_featureMatching/run_train_TPU.py) for training.

Once checkpoint 0 is generated you can stop the training and restart by running the same file again.
You will see that there will be no error in this case.

After checkpoints 1,2... are generated, you can stop the training.
But this time, when you try to restore the training you will observe the error.

The repo contains minimal input data to run the experiments.
1 epoch is composed of 3 chunks and after each chunk is completed a checkpoint is generated.
The chunk files are too small so that you can get checkpoint files in seconds.

To run the test, activate the [line ](https://github.com/mfatih7/checkpoint_SPMD_debug/blob/main/17_featureMatching/config.py#L9) and run the [test file](https://github.com/mfatih7/checkpoint_SPMD_debug/blob/main/17_featureMatching/run_test_TPU.py)

You will also observe the error in this case.

I am looking forward to your diagnose.

**Comment by mfatih7** [comment]
Hello @jonb377

The origin of the error is the optimizer.
When I comment out lines [1](https://github.com/mfatih7/checkpoint_SPMD_debug/blob/main/17_featureMatching/checkpoint.py#L24), [2](https://github.com/mfatih7/checkpoint_SPMD_debug/blob/main/17_featureMatching/checkpoint.py#L131), [3](https://github.com/mfatih7/checkpoint_SPMD_debug/blob/main/17_featureMatching/checkpoint.py#L166) related to placing optimizer into checkpoint no error occurs.

Just comment out the lines and after that start training, stop-restore, and run testing and you will see no error.

But what do we do wrong regarding the optimizer?

**Comment by mfatih7** [comment]
Hello @jonb377

After adding [make_optimizer_prime_spmd ](https://github.com/mfatih7/checkpoint_SPMD_debug/blob/main/17_featureMatching/checkpoint.py#L9) function and modifying [get_checkpoint_template](https://github.com/mfatih7/checkpoint_SPMD_debug/blob/main/17_featureMatching/checkpoint.py#L22) function I do not get the error.

I will check with my regular long runs.

Using the [repo](https://github.com/mfatih7/checkpoint_SPMD_debug), could you also check if everything is OK?

It is still mystery that without this update, why some of the VMs do give errors regarding the optimizer and some of them do not give?

Is Making the optimizers in the checkpoint prime a necessity for only SPMD operations or is it also important for single-core and multi-core operations? I do not make my optimizers for single-core and multi-core operations and I have not observed any errors regarding the optimizers in single-core and multi-core operations without SPMD.

**Comment by jonb377** [comment]
Thanks for sharing the repo! I'll take a look.

You should only need to prime the optimizer during checkpoint loading, and even then it shouldn't be causing the error you were seeing. I'll see if I can find what's going wrong.

> Is making the optimizers in the checkpoint prime a necessity for only SPMD operations or is it also important for single-core and multi-core operations? 

It's only necessary when loading a checkpoint using the `torch.distributed.checkpoint` APIs, since the state_dict is loaded in-place. In multiprocess, an entirely new state dict is loaded from disk using `torch.load` and can overwrite an empty optimizer state_dict, but with distributed checkpointing the state_dict must already exist so that the necessary shards from the checkpoint can be selected for loading.

**Comment by jonb377** [comment]
> Once checkpoint 0 is generated you can stop the training and restart by running the same file again.
> You will see that there will be no error in this case.

> After checkpoints 1,2... are generated, you can stop the training.
> But this time, when you try to restore the training you will observe the error.

Ah, yeah - this is the issue then. Thanks @mfatih7 for finding this, we'll need to improve the UX since this is an easy trap to fall into, especially since the priming step is only necessary in SPMD. I'll try to explain what's going wrong:

1. The state_dict is "flattened" when taking the checkpoint, so each individual tensor is keyed by its path in the state_dict. For example, if the state_dict is `{'optimizer_state_dict': {'state': torch.tensor(...)}}`, the tensor will be keyed by `optimizer_state_dict.state`
2. In the unprimed optimizer case, the state_dict will look like `{'optimizer_state_key': {}}` and the empty state_dict will be serialized directly and keyed by `optimizer_state_key`.
3. When loading, only the keys in the input state_dict will be looked for.
   a. If the optimizer state is primed before load, that means `optimizer_state_dict.state`
   b. If not, it will look for `optimizer_state_key`
4. After epoch 1, the stored checkpoint contains `optimizer_state_dict.state`, but we're trying to load into an unprimed optimizer state_dict, so the loading logic is only looking for `optimizer_state_key` while the stored checkpoint only provides `optimizer_state_dict.state`, hence the error.

You should only need to prime the state_dict once, before saving or loading any checkpoints.

**Comment by jonb377** [comment]
The prime_optimizer function will be available in tonight's nightly build.
