### ISSUE TITLE
Update IR-level lowerings to proper lowerings

### ISSUE THREAD

**Issue by wonjoolee95** [pytorch/xla#6589]
As a follow-up to https://github.com/pytorch/xla/issues/6294, we realized that many ops in PyTorch/XLA were lowered in IR-level. This caused multiple unnecessary decompositions, causing slowdown in tracing time. See also: https://github.com/pytorch/xla/issues/6294.

This issue will serve as a tracker to identify and properly lower existing IR-level lowerings. Recommended steps to properly lower these ops:
1. Confirm that the op is being improperly lowered in IR-level and is causing unnecessary decompositions. Decompositions can be empirically observed through one of these followings: profile via tensorboard/xprof, torch_xla metrics report, dispatch trace via `TORCH_SHOW_DISPATCH_TRACE`. 
2. Update the IR-level lowering to proper lowering. Example: https://github.com/pytorch/xla/pull/6339.
3. Confirm that the newly properly lowered op now decomposes properly.

The identified list of IR-level lowerings (list is WIP, feel free to add new ones):
- [x] add.Tensor
- [x] add.Scalar
- [x] index_add
- [x] mul.Tensor
- [x] mul.Scalar
- [x] rsub.Tensor
- [x] rsub.Scalar
- [x] sub.Tensor
- [x] sub.Scalar
- [x] trace
- [x] div.Tensor
- [x] div.Sclar

If you're interested on contributing, please create a corresponding issue and link it here under the op.

**Comment by wonjoolee95** [comment]
To divide and conquer this work, I propose the following distribution below. Let me know if you have any concerns or questions.

I can work on: 
- add.Tensor
- add.Scalar
- mul.Tensor
- mul.Scalar

@bhavya01 can work on: 
- index_add
- trace
- div.Tensor
- div.Sclar.

@ang90, would you be able to work on these? 
- rsub.Tensor
- rsub.Scalar
- sub.Tensor
- sub.Scalar

An example PR that does a similar lowering is https://github.com/pytorch/xla/pull/6339. Let me know if this plan sounds okay with you, thanks!

**Comment by anw90** [comment]
Okay, I'll take a look at these ops.

**Comment by wonjoolee95** [comment]
Marking this as complete.
