### ISSUE TITLE
Unable to train model on Google Cloud TPU VM v5-litepod-8

### ISSUE THREAD

**Issue by shub-kris** [pytorch/xla#6611]
## 🐛 Bug

Running out of memory  in memory space vmem while allocating on stack. I took the [SPMD Gemma ft code from Hugging Face](https://huggingface.co/google/gemma-7b/blob/main/examples/example_fsdp.py) and tried to run it on Google Cloud TPU VM v5-litepod-8; it didn't work.

See the stack trace below

## To Reproduce

Create and SSH intoGoogle Cloud VM:
```bash
 gcloud alpha compute tpus tpu-vm create tpu-vm --zone=us-west4-a --accelerator-type=v5litepod-8 --version v2-alpha-tpuv5-lite
 gcloud alpha compute tpus tpu-vm ssh tpu-vm --zone=us-west4-a
```
Install the packages
```bash

pip install torch~=2.2.0 torch_xla[tpu]~=2.2.0 -f https://storage.googleapis.com/libtpu-releases/index.html
pip install transformers==4.38.1 peft trl datasets 
```

Run the script with
```bash
python example_fsdp.py
```

### Stack Trace

```
EXHAUSTED: Ran out of memory in memory space vmem while allocating on stack for %reduce-window.1 = (u32[16,8,128]{2,1,0:T(8,128)S(1)}, u32[16,8,128]{2,1,0:T(8,128)S(1)}) reduce-window(u32[16,8,128]{2,1,0:T(8,128)S(1)} %bitcast.2726, u32[16,8,128]{2,1,0:T(8,128)S(1)} %bitcast.2727, u32[]{:T(128)} %constant.2, u32[]{:T(128)} %constant.2), window={size=1x1x128 pad=0_0x0_0x127_0}, to_apply=%AddComputation.2173.clone. Scoped allocation with size 31.07M and limit 16.00M exceeded scoped vmem limit by 15.07M. It should not be possible to run out of scoped vmem - please file a bug against XLA.
*** Begin stack trace ***
        tsl::CurrentStackTrace()
        std::unique_ptr<xla::PjRtLoadedExecutable, std::default_delete<xla::PjRtLoadedExecutable> > ConsumeValue<std::unique_ptr<xla::PjRtLoadedExecutable, std::default_delete<xla::PjRtLoadedExecutable> > >(absl::lts_20230802::StatusOr<std::unique_ptr<xla::PjRtLoadedExecutable, std::default_delete<xla::PjRtLoadedExecutable> > >&&)
        torch_xla::runtime::PjRtComputationClient::Compile(std::vector<torch_xla::runtime::ComputationClient::CompileInstance, std::allocator<torch_xla::runtime::ComputationClient::CompileInstance> >)
        torch_xla::XLAGraphExecutor::Compile(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > > const&, absl::lts_20230802::Span<std::string const>, torch::lazy::LazyGraphExecutor::SyncTensorCollection const&, torch::lazy::LazyGraphExecutor::PostOrderData*, std::vector<torch::lazy::Value, std::allocator<torch::lazy::Value> > const&)
        torch_xla::XLAGraphExecutor::SyncTensorsGraphInternal(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > >*, absl::lts_20230802::Span<std::string const>, torch::lazy::LazyGraphExecutor::SyncTensorsConfig const&, bool)
        torch_xla::XLAGraphExecutor::GetTensors(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > >*)
        torch_xla::bridge::XlaCreateTensorList(c10::IListRef<at::Tensor> const&)
        torch_xla::XLANativeFunctions::_to_cpu(c10::ArrayRef<at::Tensor>)

        at::_ops::_to_cpu::call(c10::ArrayRef<at::Tensor>)

        at::native::cpu_fallback(c10::OperatorHandle const&, std::vector<c10::IValue, std::allocator<c10::IValue> >*, bool)
        torch_xla::xla_cpu_fallback(c10::OperatorHandle const&, std::vector<c10::IValue, std::allocator<c10::IValue> >*)
        at::native::_call_fallback_fn<&torch_xla::xla_cpu_fallback, at::_ops::_local_scalar_dense, false, c10::Scalar (at::Tensor const&)>::call(at::Tensor const&)
        torch_xla::XLANativeFunctions::_local_scalar_dense(at::Tensor const&)

        c10::Dispatcher::callBoxed(c10::OperatorHandle const&, std::vector<c10::IValue, std::allocator<c10::IValue> >*) const


        at::_ops::_local_scalar_dense::redispatch(c10::DispatchKeySet, at::Tensor const&)


        at::_ops::_local_scalar_dense::call(at::Tensor const&)
        at::native::item(at::Tensor const&)

        at::_ops::item::call(at::Tensor const&)


        _PyEval_EvalFrameDefault


        PyVectorcall_Call

        _PyObject_MakeTpCall

        _PyEval_EvalFrameDefault



        _PyEval_EvalFrameDefault

        _PyEval_EvalFrameDefault

        _PyEval_EvalFrameDefault

        _PyEval_EvalFrameDefault

        _PyObject_FastCallDictTstate
        _PyObject_Call_Prepend

        _PyObject_Call

        _PyObject_MakeTpCall
        _PyEval_EvalFrameDefault

        _PyEval_EvalFrameDefault

        _PyEval_EvalFrameDefault

        _PyEval_EvalFrameDefault

        _PyEval_EvalFrameDefault

        _PyEval_EvalFrameDefault


*** End stack trace ***
```

## Expected behavior
The model would have trained successfully without any error.

## Environment

 - Reproducible on XLA backend: TPU

**Comment by JackCaoG** [comment]
@will-cromar can you take a look?

**Comment by will-cromar** [comment]
The link is a 404 for me. @alanwaketan can you take a look?

**Comment by alanwaketan** [comment]
You need to use the nightly torch-xla. Probably need to reduce the batch size and model size. 7B Gemma currently doesn't fit in v5e thanks to its gigantic embedding table.

**Comment by shub-kris** [comment]
@alanwaketan thanks for the reply. As mentioned, I did use 
```bash
pip install torch_xla[tpu] -f https://storage.googleapis.com/libtpu-releases/index.html
```
To install the nightly version.

I modified the [SPMD Gemma ft code from Hugging Face](https://gist.github.com/shub-kris/0c082c72774345f70f91deef80fc5a18) to use `gemma-2b` with a batch-size of `8` and it still throws the same error.

**Comment by alanwaketan** [comment]
> @alanwaketan The thing that partially worked for me was this modified [test-gemma.py](https://gist.github.com/shub-kris/0c082c72774345f70f91deef80fc5a18) script with the nightly torch_xla version.
> 
> I run it with
> 
> ```
> export PJRT_DEVICE=TPU
> export XLA_USE_SPMD=1
> python test-gemma.py
> ```
> 
> But I then run into this at the end of training :
> 
> ```
> Traceback (most recent call last):
>   File "//workspace/test-gemma.py", line 80, in <module>
>     xmp.spawn(_mp_fn, args=(args,), nprocs=args.num_cores)
>   File "/usr/local/lib/python3.10/site-packages/torch_xla/runtime.py", line 88, in wrapper
>     return fn(*args, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 38, in spawn
>     return pjrt.spawn(fn, nprocs, start_method, args)
>   File "/usr/local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 211, in spawn
>     run_multiprocess(spawn_fn, start_method=start_method)
>   File "/usr/local/lib/python3.10/site-packages/torch_xla/runtime.py", line 88, in wrapper
>     return fn(*args, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 175, in run_multiprocess
>     return _merge_replica_results(replica_results)
>   File "/usr/local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 39, in _merge_replica_results
>     assert num_results == 1, f'{num_results} results for replica {replica}'
> AssertionError: 8 results for replica 0
> ```

For SPMD, you don't need the xmp.spawn thing. The programming paradigm is one process per host.

**Comment by alanwaketan** [comment]
> @alanwaketan thanks for the reply. As you suggested, I installed the nightly version.
> 
> ```shell
> pip install torch_xla[tpu] -f https://storage.googleapis.com/libtpu-releases/index.html
> ```
> 
> I modified the [SPMD Gemma ft code from Hugging Face](https://huggingface.co/google/gemma-7b/blob/main/examples/example_fsdp.py) to use `gemma-2b` with a batch-size of `8` and now I run into a new error:
> 
> ```
> 024-02-27 09:52:24.990707: F ./torch_xla/csrc/runtime/debug_macros.h:20] Non-OK-status: status.status() status: INTERNAL: during context [post-optimization]: Expected instruction to have shape equal to bf16[4,1024,1024]{2,1,0}, actual shape is bf16[4,1024,2048]{2,1,0:T(8,128)(2,1)}:
> %convolution-base-dilated.192.clone.1 = bf16[4,1024,2048]{2,1,0:T(8,128)(2,1)} convolution(bf16[4,1024,2048]{2,1,0:T(8,128)(2,1)} %fusion.3537.clone.1, bf16[4,1024,2048]{2,1,0:T(8,128)(2,1)} %fusion.3538.clone.1), window={size=4 stride=3 lhs_dilate=4}, dim_labels=0bf_0oi->0bf
> *** Begin stack trace ***
>         tsl::CurrentStackTrace()
>         std::unique_ptr<xla::PjRtLoadedExecutable, std::default_delete<xla::PjRtLoadedExecutable> > ConsumeValue<std::unique_ptr<xla::PjRtLoadedExecutable, std::default_delete<xla::PjRtLoadedExecutable> > >(absl::lts_20230802::StatusOr<std::unique_ptr<xla::PjRtLoadedExecutable, std::default_delete<xla::PjRtLoadedExecutable> > >&&)
>         torch_xla::runtime::PjRtComputationClient::Compile(std::vector<torch_xla::runtime::ComputationClient::CompileInstance, std::allocator<torch_xla::runtime::ComputationClient::CompileInstance> >)
>         torch_xla::XLAGraphExecutor::Compile(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > > const&, absl::lts_20230802::Span<std::string const>, torch::lazy::LazyGraphExecutor::SyncTensorCollection const&, torch::lazy::LazyGraphExecutor::PostOrderData*, std::vector<torch::lazy::Value, std::allocator<torch::lazy::Value> > const&)
>         torch_xla::XLAGraphExecutor::SyncTensorsGraphInternal(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > >*, absl::lts_20230802::Span<std::string const>, torch::lazy::LazyGraphExecutor::SyncTensorsConfig const&, bool)
>         torch_xla::XLAGraphExecutor::GetTensors(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > >*)
>         torch_xla::bridge::XlaCreateTensorList(c10::IListRef<at::Tensor> const&)
>         torch_xla::XLANativeFunctions::_to_cpu(c10::ArrayRef<at::Tensor>)
> 
>         at::_ops::_to_cpu::call(c10::ArrayRef<at::Tensor>)
> 
>         at::native::cpu_fallback(c10::OperatorHandle const&, std::vector<c10::IValue, std::allocator<c10::IValue> >*, bool)
>         torch_xla::xla_cpu_fallback(c10::OperatorHandle const&, std::vector<c10::IValue, std::allocator<c10::IValue> >*)
>         at::native::_call_fallback_fn<&torch_xla::xla_cpu_fallback, at::_ops::_local_scalar_dense, false, c10::Scalar (at::Tensor const&)>::call(at::Tensor const&)
>         torch_xla::XLANativeFunctions::_local_scalar_dense(at::Tensor const&)
> 
> 
>         at::_ops::_local_scalar_dense::redispatch(c10::DispatchKeySet, at::Tensor const&)
> 
> 
>         at::_ops::_local_scalar_dense::call(at::Tensor const&)
>         at::native::item(at::Tensor const&)
> 
>         at::_ops::item::call(at::Tensor const&)
> 
> 
>         _PyEval_EvalFrameDefault
> 
> 
>         PyVectorcall_Call
> 
>         _PyObject_MakeTpCall
>         _PyEval_EvalFrameDefault
> 
> 
> 
>         _PyEval_EvalFrameDefault
> 
>         _PyEval_EvalFrameDefault
> 
>         PyEval_EvalCode
> 
> 
> 
>         _PyRun_SimpleFileObject
>         _PyRun_AnyFileObject
>         Py_RunMain
>         Py_BytesMain
>         __libc_start_main
>         _start
> *** End stack trace ***
> 
> https://symbolize.stripped_domain/r/?trace=7feb02cf1ce1,7fdb4f23f6a6,7feb02cf1d5f,7fe82e887eca,7fe82e88f076,7fe82e685ccc,7fe82e687798,7fe82e688528,7fe82e45ae14,7fe82e460c86,7fe82e6c05a7,7feaf7f24d4e,7feaf76cee68,0&map= 
> E0227 09:52:25.034033     267 coredump_hook.cc:442] RAW: Remote crash data gathering hook invoked.
> E0227 09:52:25.034048     267 client.cc:269] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
> E0227 09:52:25.034057     267 coredump_hook.cc:537] RAW: Sending fingerprint to remote end.
> E0227 09:52:25.034081     267 coredump_hook.cc:546] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] stat failed on crash reporting socket /var/google/services/logmanagerd/remote_coredump.socket (Is the listener running?): No such file or directory
> E0227 09:52:25.034087     267 coredump_hook.cc:598] RAW: Dumping core locally.
> E0227 09:52:51.348409     267 process_state.cc:807] RAW: Raising signal 6 with default behavior
> Aborted (core dumped)
> ```

This is interesting, can you try setting XLA_USE_BF16=1?

**Comment by shub-kris** [comment]
@alanwaketan setting the XLA_USE_BF16=1 successfully runs. 

A nice twist to this script again happens, when I add an argument `gradient_checkpointing=True` to the training_arguments 
```

trainer = SFTTrainer(
   model=model,
   train_dataset=data,
   args=TrainingArguments(
   per_device_train_batch_size=8,  # This is actually the global batch size for SPMD.
   num_train_epochs=10,
   max_steps=-1,
   output_dir="./output",
   optim="adafactor",
   logging_steps=1,
  gradient_checkpointing=True, 
  save_steps=50,
   dataloader_drop_last = True,  # Required for SPMD.
   fsdp="full_shard",
   fsdp_config=fsdp_config,
   ),
   peft_config=lora_config,
   dataset_text_field="quote",
   max_seq_length=max_seq_length,
   packing=True,
   )


```

and then it fails with this:

```
tokenizer_config.json: 100%|██████████████████████████████████████| 1.11k/1.11k [00:00<00:00, 7.72MB/s]
tokenizer.model: 100%|████████████████████████████████████████████| 4.24M/4.24M [00:00<00:00, 89.7MB/s]
tokenizer.json: 100%|██████████████████████████████████████████████| 17.5M/17.5M [00:00<00:00, 206MB/s]
special_tokens_map.json: 100%|████████████████████████████████████████| 555/555 [00:00<00:00, 5.62MB/s]
config.json: 100%|████████████████████████████████████████████████████| 627/627 [00:00<00:00, 5.61MB/s]
model.safetensors.index.json: 100%|███████████████████████████████| 13.5k/13.5k [00:00<00:00, 81.1MB/s]
model-00001-of-00002.safetensors: 100%|████████████████████████████| 4.95G/4.95G [00:16<00:00, 297MB/s]
model-00002-of-00002.safetensors: 100%|████████████████████████████| 67.1M/67.1M [00:00<00:00, 260MB/s]
Downloading shards: 100%|████████████████████████████████████████████████| 2/2 [00:17<00:00,  8.59s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████| 2/2 [00:00<00:00,  2.33it/s]
generation_config.json: 100%|██████████████████████████████████████████| 137/137 [00:00<00:00, 924kB/s]
Downloading readme: 100%|█████████████████████████████████████████| 5.55k/5.55k [00:00<00:00, 34.0MB/s]
Downloading data: 100%|█████████████████████████████████████████████| 647k/647k [00:00<00:00, 2.50MB/s]
Generating train split: 2508 examples [00:00, 352677.59 examples/s]
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1709066335.967936      46 pjrt_api.cc:100] GetPjrtApi was found for tpu at /usr/local/lib/python3.10/site-packages/torch_xla/lib/libtpu.so
I0000 00:00:1709066335.967984      46 pjrt_api.cc:79] PJRT_Api is set for device type tpu
I0000 00:00:1709066335.967992      46 pjrt_api.cc:146] The PJRT plugin has PJRT API version 0.40. The framework PJRT API version is 0.40.
Generating train split: 102 examples [00:00, 540.98 examples/s]
/usr/local/lib/python3.10/site-packages/trl/trainer/sft_trainer.py:294: UserWarning: You passed a tokenizer with `padding_side` not equal to `right` to the SFTTrainer. This might lead to some unexpected behaviour due to overflow issues when training a model in half-precision. You might consider adding `tokenizer.padding_side = 'right'` to your code.
  warnings.warn(
  0%|                                                                          | 0/120 [00:00<?, ?it/s]`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
/usr/local/lib/python3.10/site-packages/torch/utils/checkpoint.py:464: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
Traceback (most recent call last):
  File "/workspace/test-gemma.py", line 64, in <module>
    trainer.train()
  File "/usr/local/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 331, in train
    output = super().train(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/trainer.py", line 1624, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/site-packages/transformers/trainer.py", line 1961, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.10/site-packages/transformers/trainer.py", line 2902, in training_step
    loss = self.compute_loss(model, inputs)
  File "/usr/local/lib/python3.10/site-packages/transformers/trainer.py", line 2925, in compute_loss
    outputs = model(**inputs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1529, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch_xla/experimental/spmd_fully_sharded_data_parallel.py", line 146, in forward
    output = self.module(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1529, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1579, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/peft/peft_model.py", line 1083, in forward
    return self.base_model(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1529, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 161, in forward
    return self.model.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/models/gemma/modeling_gemma.py", line 1067, in forward
    outputs = self.model(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1529, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/models/gemma/modeling_gemma.py", line 894, in forward
    layer_outputs = self._gradient_checkpointing_func(
  File "/usr/local/lib/python3.10/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 455, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 25, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 487, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/usr/local/lib/python3.10/site-packages/torch/autograd/function.py", line 573, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 231, in forward
    ctx.device_autocast_kwargs, ctx.cpu_autocast_kwargs = _get_autocast_kwargs(
  File "/usr/local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 200, in _get_autocast_kwargs
    elif _supports_autocast(device):
  File "/usr/local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 219, in _supports_autocast
    device_module = _get_device_module(device)
  File "/usr/local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 97, in _get_device_module
    device_module = getattr(torch, device)
  File "/usr/local/lib/python3.10/site-packages/torch/__init__.py", line 1999, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'torch' has no attribute 'xla'
  0%|          | 0/120 [00:00<?, ?it/s]   

```

I have encountered this issue before too and have opened a ticket here: https://github.com/huggingface/transformers/issues/29314

**Comment by alanwaketan** [comment]
@shub-kris The native grad ckpt doesn't work for XLA. The xla grad ckpt is applied through:
```
# Set up the FSDP config. To enable FSDP via SPMD, set xla_fsdp_v2 to True.
fsdp_config = {"fsdp_transformer_layer_cls_to_wrap": [
        "GemmaDecoderLayer"
    ],
    "xla": True,
    "xla_fsdp_v2": True,
    "xla_fsdp_grad_ckpt": True}
```

**Comment by shub-kris** [comment]
@alanwaketan thanks a lot for the clarification and for answering my stupid questions.

**Comment by alanwaketan** [comment]
> @alanwaketan thanks a lot for the clarification and for answering my stupid questions. Does native grad ckpt won't work even when I don't utilize fsdp and use `xmp.spawn`?

Definitely not stupid questions. Thanks for validating the example!

The native grad ckpt won't work in any cases. We need to apply some special treatment for the XLA compiler to make grad ckpt working. Those are implemented here: https://github.com/pytorch/xla/blob/master/torch_xla/utils/checkpoint.py

However, we do think we should able to integrate our grad ckpt into HF such that users don't need to specify `xla_fsdp_grad_ckpt` in FSDP anymore.
