### ISSUE TITLE
Does XLA use the Nvidia GPU's tensor cores?

### ISSUE THREAD

**Issue by Demis6** [pytorch/xla#6710]
## ❓ Questions and Help
1. Does XLA use the Nvidia GPU's tensor cores?
2. Is Pytorch XLA only designed to accelerate neural network training or does it accelerate their inferencing as well?

**Comment by JackCaoG** [comment]
1. yea. XLA:GPU uses GPU's tensor core. check https://github.com/pytorch/xla/blob/master/docs/gpu.md
2. PyTorch/XLA accelerate both training and inference.

**Comment by yeounoh** [comment]
Closing, as I see @Demis6 has already acked on @JackCaoG 's comment.
