### ISSUE TITLE
Build issue on GCP

### ISSUE THREAD

**Issue by farhaanbukhsh** [pytorch/xla#676]
nvcc fatal   : The version ('7.0') of the host compiler ('clang') is not supported
Makefile:52: recipe for target '/home/jupyter/pytorch/build/nccl/obj/collectives/device/reduce_scatter.dep' failed
make[2]: *** [/home/jupyter/pytorch/build/nccl/obj/collectives/device/reduce_scatter.dep] Error 1
nvcc fatal   : The version ('7.0') of the host compiler ('clang') is not supported
Makefile:52: recipe for target '/home/jupyter/pytorch/build/nccl/obj/collectives/device/functions.dep' failed
make[2]: *** [/home/jupyter/pytorch/build/nccl/obj/collectives/device/functions.dep] Error 1
nvcc fatal   : The version ('7.0') of the host compiler ('clang') is not supported
Makefile:52: recipe for target '/home/jupyter/pytorch/build/nccl/obj/collectives/device/reduce.dep' failed
make[2]: *** [/home/jupyter/pytorch/build/nccl/obj/collectives/device/reduce.dep] Error 1
nvcc fatal   : The version ('7.0') of the host compiler ('clang') is not supported
Makefile:52: recipe for target '/home/jupyter/pytorch/build/nccl/obj/collectives/device/all_reduce.dep' failed
make[2]: *** [/home/jupyter/pytorch/build/nccl/obj/collectives/device/all_reduce.dep] Error 1
nvcc fatal   : The version ('7.0') of the host compiler ('clang') is not supported
Makefile:52: recipe for target '/home/jupyter/pytorch/build/nccl/obj/collectives/device/broadcast.dep' failed
make[2]: *** [/home/jupyter/pytorch/build/nccl/obj/collectives/device/broadcast.dep] Error 1
make[2]: Leaving directory '/home/jupyter/pytorch/third_party/nccl/nccl/src/collectives/device'
Makefile:44: recipe for target '/home/jupyter/pytorch/build/nccl/obj/collectives/device/colldevice.a' failed
make[1]: *** [/home/jupyter/pytorch/build/nccl/obj/collectives/device/colldevice.a] Error 2
make[1]: Leaving directory '/home/jupyter/pytorch/third_party/nccl/nccl/src'
Makefile:25: recipe for target 'src.build' failed
make: *** [src.build] Error 2
[12/3115] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/extension_set.cc.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 728, in <module>
    build_deps()
  File "setup.py", line 294, in build_deps
    build_dir='build')
  File "/home/jupyter/pytorch/tools/build_pytorch_libs.py", line 293, in build_caffe2
    check_call(ninja_cmd, cwd=build_dir, env=my_env)
  File "/opt/anaconda3/lib/python3.7/subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', 'install']' returned non-zero exit status 1

**Comment by asuhan** [comment]
@farhaanbukhsh You can try either with `export NO_CUDA=1` or with gcc 7 (instead of Clang).

**Comment by farhaanbukhsh** [comment]
@asuhan I want cuda support should I try with gcc 7 ?

**Comment by farhaanbukhsh** [comment]
> @farhaanbukhsh You can try either with `export NO_CUDA=1` or with gcc 7 (instead of Clang).

gcc7 doesn't work it fails the simple test of compiling the program, when I did a install

**Comment by asuhan** [comment]
I don't understand what failed -- compiling a simple C++ program with gcc or something else?

**Comment by farhaanbukhsh** [comment]
![image](https://user-images.githubusercontent.com/7670449/57747770-9bd47280-76f4-11e9-950e-2ae4b218a4cf.png)


This is what I got when I ran with `export NO_CUDA=1` and  `COMPILE_PARALLEL=0 python setup.py install`

**Comment by farhaanbukhsh** [comment]
![image](https://user-images.githubusercontent.com/7670449/57749563-22d91900-76fc-11e9-803f-aa517f660ca6.png)
`export CC=gcc CXX=g++-7` and COMPILE_PARALLEL=0 python setup.py install`

I realised  i could be mistaken I should have used `export CC=gcc-7 CXX=g++-7`

**Comment by farhaanbukhsh** [comment]
![image](https://user-images.githubusercontent.com/7670449/57752126-96cbef00-7705-11e9-9e2b-04745c84eb59.png)

export CC=gcc-7 CXX=g++-7

**Comment by dlibenzi** [comment]
I suggest you using clang-7, as it is the one we used to work on and test internally.
But the blas error is likely due to a specific version of MKL liked by pytorch.
These are the versions a `conda list` shows me in my setup:
```
blas                      1.0                         mkl  
mkl                       2019.3                      199  
mkl-include               2019.1                      144  
mkl-service               1.1.2            py36he904b0f_5  
mkl_fft                   1.0.10           py36ha843d7b_0  
mkl_random                1.0.2            py36hd81dba3_0 
```

**Comment by ailzhang** [comment]
In general if you want to build with both Cuda and XLA support, use gcc to build pytorch and clang7 to build torch_xla works well for me. If you only want XLA support clang7 should work as well building pytorch with `USE_CUDA=0`. 
As @dlibenzi said above, upgrading `mkl` version should fix the error shown in the last snapshot.  
Closing issue as resolved, please feel free to reopen if you have follow up questions.
