### ISSUE TITLE
Regression caused by recent open XLA pin update

### ISSUE THREAD

**Issue by vanbasten23** [pytorch/xla#6816]
## 🐛 Bug

We will use this ticket to trace the regression caused by the recent open XLA pin update. It's continuation of an internal ticket.

1. pin update: https://github.com/pytorch/xla/pull/6677 
It caused error:
```
double free or corruption (!prev)
Aborted (core dumped)
```
But it has been fixed in a follow-up pin update.

2. https://github.com/pytorch/xla/pull/6770 (03/20)

It caused compile_time to be doubled.

3. https://github.com/pytorch/xla/pull/6797 (03/22) 

## Environment

 - Reproducible on XLA backend [CPU/TPU/CUDA]: CUDA
 - torch_xla version: nightly

## Additional context

cc: @ysiraichi @JackCaoG @miladm @zpcore

**Comment by zpcore** [comment]
Just checked with @miladm , the `compile_time to be doubled` issue is mostly affect the V100. `H100` and `L4` were less impacted.

**Comment by vanbasten23** [comment]
SGTM!
