### ISSUE TITLE
pytorch/xla build fails at 'name 'ProtoInfo' is not defined'

### ISSUE THREAD

**Issue by singam-sanjay** [pytorch/xla#690]
After building and installing PyTorch, `~/pytorch/xla$ python setup.py install` fails with the following error under the following system environment,
```
ERROR: /home/user/.cache/bazel/_bazel_user/d8447ee09863213d5ccbcb3eeef5e515/external/io_bazel_rules_closure/closure/protobuf/closure_proto_library.bzl:66:21: name 'ProtoInfo' is not defined
ERROR: error loading package '': Extension 'closure/protobuf/closure_proto_library.bzl' has errors
ERROR: error loading package '': Extension 'closure/protobuf/closure_proto_library.bzl' has errors
INFO: Elapsed time: 3.034s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

System Environment:
- PyTorch : v1.1.0
- Bazel : 0.12
- conda : 4.6.14
- CUDA : 10.1

A quick search reveals this could be caused by using an older version of bazel. On trying bazel 0.13, 0.19.1 and 0.20.0, the build fails due to the same reason.

What am I missing here ? How can I work around this issue ?

Thank for any help !
Sanjay

**Comment by dlibenzi** [comment]
You need recent Bazel.

https://github.com/pytorch/xla/blob/9fe779a7478b05983b5cfa3de06689bafeb92cd9/.circleci/build.sh#L49

**Comment by singam-sanjay** [comment]
Thank You !
