### ISSUE TITLE
SPMD + Dynamo

### ISSUE THREAD

**Issue by BitPhinix** [pytorch/xla#6916]
## ❓ Questions and Help

Is there a way to get SPMD working with Dynamo/`torch.compile` to reduce the overhead of Pytorch re-tracing the module every time it gets called?

**Comment by JackCaoG** [comment]
It should work, check the test in https://github.com/pytorch/xla/blob/master/test/spmd/test_dynamo_spmd.py. The trick is to call `mark_sharding` or use Dtensor api to shard parameter outside of the `torch.compile` region.

If you want to shard the tensor inside the `torch.compile` region. @wonjoolee95 recently added the activation sharding support for dynamo so it should also work(with a slightly different api).

**Comment by wonjoolee95** [comment]
> If you want to shard the tensor inside the torch.compile region. @wonjoolee95 recently added the activation sharding support for dynamo so it should also work(with a slightly different api).

The API when you want to shard the tensor within `torch.compile` looks like:
```
# Activation output sharding
import torch_xla.experimental.dynamo_mark_sharding
device_ids = [i for i in range(self.num_devices)] # List[int]
mesh_shape = [self.num_devices//2, 1, 2] # List[int]
axis_names = 'None' # string version of axis_names
partition_spec = '(0, 1, 2)' # string version of partition spec
torch.ops.xla.dynamo_mark_sharding(output, device_ids, mesh_shape, axis_names, partition_spec)
```
The API interface is a bit ugly due to the restrictions of what code Dynamo is able to trace, but let me know if you run through any issues!

**Comment by BitPhinix** [comment]
@wonjoolee95 that seems to have done it! Thanks 🙏

**Comment by wonjoolee95** [comment]
Glad it worked! Please note that this is still an experimental feature, so let us know if there are any issues/bugs when you try it out, we'll try our best to fix them.
