### ISSUE TITLE
Optimizers in XLA: Not Executing on XLA Devices, Inconsistency with Original PyTorch Algorithms

### ISSUE THREAD

**Issue by MrAru** [pytorch/xla#6977]
Optimizers in XLA: Not Executing on XLA Devices, Inconsistency with Original PyTorch Algorithms

Hi, PyTorch/XLA Community!

I'm trying to use XLA to accelerate the training process of our model. Referring to the example instructions, I compared the original PyTorch version with the code that using XLA:

```python
def torch_version():
    EPOCH = 10
    DEVICE = torch.device("cuda")

    model = MyCustomModel().train().to(DEVICE)
    loss_fn = nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.00001)
    x, y = torch.randn(...).to(DEVICE), torch.randn(...).to(DEVICE)

    for idx in range(EPOCH):
        optimizer.zero_grad()
        yhat = model(x)
        loss = loss_fn(yhat, y)
        loss.backward()
        optimizer.step()
        torch.cuda.synchronize()

def xla_version():
    EPOCH = 10
    DEVICE = xm.xla_device()

    model = MyCustomModel().train().to(DEVICE)
    loss_fn = nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.00001)
    x, y = torch.randn(...).to(DEVICE), torch.randn(...).to(DEVICE)

    for idx in range(EPOCH):
        optimizer.zero_grad()
        yhat = model(x)
        loss = loss_fn(yhat, y)
        loss.backward()
        xm.optimizer_step(optimizer, barrier=True)
```

As you can see, the only difference between the above two codes is changing `DEVICE` to XLA device and replacing `optimizer.step()` with `xm.optimizer_step(optimizer, barrier=True)`. I then conducted a performance profiling for above two function, and I found the following issues in the profile result, hope to get some hints here:

[1] profiling result for PyTorch code
![torch_adam](https://github.com/pytorch/xla/assets/26517155/51be0303-177f-4018-aa23-326d8bd1d03e)

[2] profiling result for XLA code
![xla_adam](https://github.com/pytorch/xla/assets/26517155/8a62fd96-ba20-41f5-92ef-65a7d283eb34)

1. Different optimizer algorithms

The original PyTorch's Adam optimizer uses many vectorized methods, while the Adam optimizer in XLA seems to expand (unroll) each operation. I'd like to confirm if this behavior is expected?

2. Optimizer not running on XLA device

If I understand correctly, the green arrows in the diagram represent the CPU dispatching the actual operations to the GPU or XLA device for execution. In the original PyTorch code, the optimizer indeed updates the model's parameters on GPU. However, in the XLA code, I did not observe the parameters updating operation being dispatched to the XLA device. According to my understanding, in my above code I have already moved the model to `DEVICE`, so the model's parameters should be on `DEVICE`, and thus the updates to the parameters should also occur on the same device. I'm not sure if there's a problem with my code, or if I'm doing the profiling wrong? How can I confirm on which device the actual computation of the parameter updates occurs?

Environment info: `Python 3.8`, `PyTorch 2.2.2`, `torch_xla 2.2.0` in docker `us-central1-docker.pkg.dev/tpu-pytorch-releases/docker/xla:nightly_3.8_cuda_12.1` 

Thank you in advance for any advice!

**Comment by JackCaoG** [comment]
1. We have to lower the torch operations into XLA primitves(HLO) so XLA can compile the program. It is up to the XLA compiler how to fuse these primitives.

2. Looking at your code I think optimizer should happens on the device. One easy way to confirm is to dump the HLO with https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#common-debugging-environment-variables-combinations . You can try to dump the HLO with optimizer and dump when commenting out optimizer. I think in the with optimizer cases you will see a bunch more `add` HLO in the graph. Note that HLO dumpping is per execution, so try to limit the steps you run so the HLO dump is not too long.

**Comment by MrAru** [comment]
Hi @JackCaoG  thanks for your help! I have confirmed that the optimizer is running on the device, just as you pointed out. I'm happy to close this issue!
