### ISSUE TITLE
Persistent Cache will not recompile when `XLA_IR_DEBUG` and `XLA_HLO_DEBUG` changed

### ISSUE THREAD

**Issue by JackCaoG** [pytorch/xla#7169]
## 🐛 Bug

When the persistent cache is enabled and `XLA_IR_DEBUG` and `XLA_HLO_DEBUG` env var changed, PyTorch/XLA will not recompile a graph with the HLO metadata

## To Reproduce

run the same pytorch/xla problem with persistent cache but flip the `XLA_IR_DEBUG` and `XLA_HLO_DEBUG`.

## Expected behavior

We recompile
## Environment

 - Reproducible on XLA backend: all
 - torch_xla version: nightly

cc @jonb377

**Comment by JackCaoG** [comment]
This is not necessary a problem for non-persisent cache case but a bit annoying with persistent cahce. I found out this by using the cache without `XLA_HLO_DEBUG` first and then found that I can't profiler to work with the hints.

**Comment by JackCaoG** [comment]
I think the easy solution is to let our compilation hash to also include `XLA_IR_DEBUG` and `XLA_HLO_DEBUG`. However there is still a catch, we do not cache on the content on the HLO metadata. This means if we use persistent cache and change the tracing annotation we still won't recompile.

That being said I don't think we should cache the HLO metadata, it will make tracing slower.

**Comment by jonb377** [comment]
Hmm we can add `XLA_IR_DEBUG` and `XLA_HLO_DEBUG` to this list to change the hash: https://github.com/pytorch/xla/blob/7938bb5da6c993609aff614ccfa5b722a339d158/torch_xla/csrc/runtime/env_hash.cc#L96

Do these env vars actually change the compilation result though?

**Comment by JackCaoG** [comment]
Computation wise it's the same. It only affect the metadata we see during profiling.

**Comment by jonb377** [comment]
Sure, I can open a PR for that. I'm still concerned about your second point:

> This means if we use persistent cache and change the tracing annotation we still won't recompile.

Should we instead just disable the persistent cache if these env vars are set?

**Comment by JackCaoG** [comment]
throwing some kind of warning message should be enough.
