### ISSUE TITLE
Test export HLO instructions

### ISSUE THREAD

**Issue by duncantech** [pytorch/xla#7188]
## 📚 Documentation

The export HLO example has not been run through in a bit and might need to be updated.  

Work through the instructions here:  
https://github.com/pytorch/xla/blob/master/docs/stablehlo.md 

Run through the instructions and update them as needed.

**Comment by duncantech** [comment]
@Arshi81099, haven't heard any updates from you yet and were wondering if you still had this ticket?   We will be unassigning it if we don't hear back as a heads up!

**Comment by Arshi81099** [comment]
Hi @duncantech, I am already on it.
I will update it ASAP

**Comment by Arshi81099** [comment]
### Changes and Improvements:

- **Device Selection**: Added flexibility to choose between XLA (TPU) and CPU based on availability (`xm.is_xla_available()`).
  
- **Model Preparation**: Ensured the model is properly moved to the selected device (`device`), which is crucial for correct execution.

- **Clarification**: Provided additional comments and explanations to enhance understanding, particularly regarding device handling and model export.

- **Optional Dependencies**: Clarified optional installation steps for TensorFlow Serving (`tf-nightly`) if serving functionalities are required.

This version of the README.md file aims to provide comprehensive guidance while maintaining clarity and ease of use, suitable for both local setups (like Mac) and cloud environments (like Google Colab with CPU).

**Comment by Arshi81099** [comment]
Torch Export to StableHLO (Prototype feature)
This document describes how to use Torch export with Torch XLA to export models to [StableHLO](https://github.com/openxla/stablehlo) format.

NOTE: This feature is currently in prototype and may undergo changes in future releases.

How to Use:
python
Copy code
from torch.export import export
from torch_xla.stablehlo import exported_program_to_stablehlo
import torch_xla.core.xla_model as xm
import torchvision
import torch

# Initialize XLA device
xla_device = xm.xla_device()

# Load a model (example with ResNet18)
resnet18 = torchvision.models.resnet18()

# Sample input (tuple of tensors)
sample_input = (torch.randn(4, 3, 224, 224), )

# Forward pass to ensure model initialization
output = resnet18(*sample_input)

# Export model to StableHLO format
exported = export(resnet18, sample_input)
stablehlo_program = exported_program_to_stablehlo(exported)

# Display StableHLO text representation
print(stablehlo_program.get_stablehlo_text('forward'))

# Display StableHLO bytecode
print(stablehlo_program.get_stablehlo_bytecode('forward'))

# Run the module on XLA device
sample_input_xla = tuple(s.to(xla_device) for s in sample_input)
output2 = stablehlo_program(*sample_input_xla)

# Compare outputs between original and StableHLO-backed models
print(torch.allclose(output, output2.cpu(), atol=1e-5))
Saving StableHLO Bytecodes to Disk
Save StableHLO to disk using:

python
Copy code
stablehlo_program.save('/tmp/stablehlo_dir')
Load the saved StableHLO program from disk:

python
Copy code
from torch_xla.stablehlo import StableHLOGraphModule
stablehlo_program2 = StableHLOGraphModule.load('/tmp/stablehlo_dir')
output3 = stablehlo_program2(*sample_input_xla)
Converting for Serving with TensorFlow Serving
To use StableHLO with TensorFlow Serving, convert it to tf.saved_model format:

bash
Copy code
stablehlo-to-saved-model /tmp/stablehlo_dir /tmp/resnet_tf/1
Run TensorFlow Serving with Docker:

bash
Copy code
docker pull tensorflow/serving
docker run -p 8500:8500 \
--mount type=bind,source=/tmp/resnet_tf,target=/models/resnet_tf \
-e MODEL_NAME=resnet_tf -t tensorflow/serving &
Alternatively, use TensorFlow Serving without Docker:

bash
Copy code
tensorflow_model_server --rest_api_port=8501 --model_name=resnet_tf --model_base_path=/tmp/resnet_tf
For more details, refer to the [TensorFlow Serving guide](https://www.tensorflow.org/tfx/serving/serving_basic).

Common Wrappers
For saving directly to tf.saved_model format without an additional command:

python
Copy code
from torch_xla.tf_saved_model_integration import save_torch_module_as_tf_saved_model

save_torch_module_as_tf_saved_model(
    resnet18,  # Original PyTorch torch.nn.Module
    sample_input,  # Sample inputs used for tracing
    '/tmp/resnet_tf'  # Directory for tf.saved_model
)
Other common wrappers include functions like save_as_stablehlo for saving StableHLO directly from an ExportedProgram.

Files Produced by save_as_stablehlo
In the saved directory (/tmp/stablehlo_dir), you'll find directories such as data, constants, and functions, containing necessary artifacts for the StableHLO program.

**Comment by Arshi81099** [comment]
Above is the updated file.

**Comment by Arshi81099** [comment]
hey @duncantech, is commenting on the issue enough?

**Comment by duncantech** [comment]
If you could submit a PR with the changes to the instructions that'd be great too

**Comment by Arshi81099** [comment]
Sure, Thank you!!

here is PR for the same : https://github.com/pytorch/xla/pull/7317

**Comment by Arshi81099** [comment]
https://github.com/pytorch/xla/pull/7317

**Comment by Arshi81099** [comment]
Hi @duncantech, Can you please that when will I receive Github badge for Docathon?
