### ISSUE TITLE
Incomplete Checkpoints for Non-Sharded Parameters During SPMD Training in PyTorch XLA

### ISSUE THREAD

**Issue by huzama** [pytorch/xla#7215]
#### Environment:
- **Framework**: PyTorch with XLA
- **Distributed Library**: torch_xla
- **Model Sharding**: SPMD 

#### Detailed Description:
I am training a model using the Single Program Multiple Data (SPMD) approach in XLA, with the following parameter sharding code:

```python
for name, param in self.model.named_parameters():
    if "embed_tokens" in name:
        xs.mark_sharding(param, self.spmd_mesh, ("model", "data"))
    elif "q_proj" in name or "k_proj" in name or "v_proj" in name:
        xs.mark_sharding(param, self.spmd_mesh, ("data", "model"))
    elif "o_proj" in name:
        xs.mark_sharding(param, self.spmd_mesh, ("model", "data"))
    elif "gate_proj" in name or "up_proj" in name:
        xs.mark_sharding(param, self.spmd_mesh, ("model", "data"))
    elif "down_proj" in name:
        xs.mark_sharding(param, self.spmd_mesh, ("data", "model"))
    elif "lm_head" in name:
        xs.mark_sharding(param, self.spmd_mesh, ("model", "data"))
    elif len(param.shape) == 2:
        xs.mark_sharding(param, self.spmd_mesh, (None, None))
    else:
        xs.mark_sharding(param, self.spmd_mesh, (None,))
```

I am encountering an issue when attempting to save and load a distributed checkpoint. The saving process does not include tensors that are not shared, and loading via `dist_cp.load()` raises an exception regarding missing keys.

#### Steps to Reproduce:
1. **Sharding**: Shard the model's parameters as per the provided code.
2. **Saving Checkpoint**:
    ```python
    xm.mark_step(wait=True)
    xm.wait_device_ops()

    state_dict = {
        "model": self.model.state_dict(),
    }

    dist_cp.save(
        state_dict=state_dict,
        storage_writer=FsspecWriter(full_path),
        planner=xc.SPMDSavePlanner(),
        process_group=self.process_group,
    )
    ```
3. **Loading Checkpoint**:
    Attempt to load the checkpoint using `dist_cp.load()`, resulting in a KeyError for missing keys.
3. **Loading Checkpoint**:
    Attempt to load the checkpoint using the following code:
    ```python
    state_dict = {
        "model": self.model.state_dict(),
    }

    dist_cp.load(
        state_dict=state_dict,
        storage_reader=FsspecReader(resume),
        planner=xc.SPMDLoadPlanner(),
        process_group=self.process_group,
    )
    ```

#### Error Message:
```
KeyError: 'Missing keys in state dictionary'
```
#### Additional Context:

- This error does not occur when I save the model immediately after loading it, before starting the training process. The issue manifests once I start training the model and attempt to save it at the end of each epoch.
- There are only two 2D parameters I am not sharding: AE and MEMORY, initialized as below.

```python

self.MEMORY = nn.Parameter(
            torch.randn(
                self.args.num_virtual_tokens,
                self.encoder.config.hidden_size,
                dtype=self.dtype,
            )
        )
```

I would appreciate any insights into what might be going wrong or suggestions for things to try.

Thank you for your help!

@jonb377  Maybe you know the answer to that.

**Comment by huzama** [comment]
The Torch 2.3.1 update, released yesterday (20240606), seems to have resolved the issue. Never mind!

**Comment by jonb377** [comment]
Hey @huzama, this is strange. Glad to hear it was resolved with 2.3.1. 

> The saving process does not include tensors that are not shared

We rely on the upstream default checkpoint logic for unsharded tensors, so if these are missing from the checkpoint, something may be going wrong with our integration.
- Do you still have the specific torch and torch_xla versions which broke this?
- Do you have a full backtrace for the error message?

Thanks!

**Comment by huzama** [comment]
I was using `torch==2.3.0` and `torch_xla==2.3.0`. While there was no error when saving the model, I encountered an error when loading the model related to [this line](https://github.com/pytorch/pytorch/blob/97ff6cfd9c86c5c09d7ce775ab64ec5c99230f5d/torch/distributed/checkpoint/default_planner.py#L235). Upon further investigation, I discovered that the `.metadata` file does not contain the mentioned 'AE' and 'MEMORY' parameters. 

I used the following code to check the metadata:

```python
from torch.distributed.checkpoint.storage import StorageReader
from torch.distributed.checkpoint._storage_utils import _storage_setup
from torch.distributed.checkpoint._fsspec_filesystem import FsspecReader, FsspecWriter

from typing import Any, cast, Dict, Optional, Set, Union

storage_reader = cast(
    StorageReader,
    _storage_setup(
        FsspecReader(path),
        path,
        reader=True,
    ),
)

metadata = storage_reader.read_metadata()

metadata.state_dict_metadata.keys()
```

This revealed that the 'AE' and 'MEMORY' parameters were missing from the metadata, which likely caused the loading error.

Regarding the full backtrace for the error message: Unfortunately, I didn't capture the backtrace at the time. However, if it would be helpful, I can downgrade my torch version back to 2.3.0 to reproduce the error and obtain the full backtrace. Please let me know if that would be useful.

**Comment by jonb377** [comment]
Thanks for confirming, I'll see if I can repro with a simple model using those torch versions.
