### ISSUE TITLE
Delete main branch

### ISSUE THREAD

**Issue by ezyang** [pytorch/xla#7224]
Self explanatory. I keep accidentally checking it out lol

**Comment by JackCaoG** [comment]
lol I guess the point is to move to "main" branch from `master` but we never completed that...

**Comment by JackCaoG** [comment]
@ManfeiBai I remembered you had some prior work to move to main, what;s the progress?

**Comment by JackCaoG** [comment]
OK I delete it for now

**Comment by ManfeiBai** [comment]
> @ManfeiBai I remembered you had some prior work to move to main, what;s the progress?

thanks, we have this PR:https://github.com/pytorch/xla/pull/5673, and agree to delete it due to too old PR
