### ISSUE TITLE
Op info test for `diag_embed`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7378]
## Fix the Op info test for `diag_embed`

1. Find the line 44 of [test_ops.py](test/test_ops.py) and remove
   `diag_embed` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by ManfeiBai** [comment]
hi, cc @tqfan28, this github issue would be one of the second issue to try, please feel free to reply this issue, so that we could assign this issue to you

**Comment by ManfeiBai** [comment]
https://github.com/pytorch/xla/pull/8036

**Comment by ManfeiBai** [comment]
hi, this op passed test in https://github.com/pytorch/xla/pull/8036
