### ISSUE TITLE
Op info test for `diagflat`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7379]
## Fix the Op info test for `diagflat`

1. Find the line 45 of [test_ops.py](test/test_ops.py) and remove
   `diagflat` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by simonteozw** [comment]
Hi @ManfeiBai was scanning through some good first issues and don't mind working on this!

**Comment by simonteozw** [comment]
Hi @ManfeiBai checking if theres still work to be done for this issue or can be marked as completed

**Comment by ManfeiBai** [comment]
Thanks, this op has been fixed

**Comment by ManfeiBai** [comment]
> Hi @ManfeiBai checking if theres still work to be done for this issue or can be marked as completed

Thanks, @simonteozw, reassigned https://github.com/pytorch/xla/issues/7497 and https://github.com/pytorch/xla/issues/7517 as the second issue to try, please let me know if anything needed
