### ISSUE TITLE
Op info test for `div`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7385]
## Fix the Op info test for `div`

1. Find the line 51 of [test_ops.py](test/test_ops.py) and remove
   `div` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by ManfeiBai** [comment]
Hi, @nupurbaghel, thanks for contribution! This issue would be one of the first issue, please feel free to reply this issue, so that we could assign it to you

**Comment by nupurbaghel** [comment]
Thanks @ManfeiBai happy to take up this issue.

**Comment by nupurbaghel** [comment]
@ManfeiBai I don't see div in the skip list. 
Also jaten.py suggests its already implemented. [code](https://github.com/pytorch/xla/blob/2a5897d4574b186125ad20e608b46b812a6eb76c/experimental/torch_xla2/torch_xla2/ops/jaten.py#L306-L327)

**Comment by ManfeiBai** [comment]
> @ManfeiBai I don't see div in the skip list. Also jaten.py suggests its already implemented. [code](https://github.com/pytorch/xla/blob/2a5897d4574b186125ad20e608b46b812a6eb76c/experimental/torch_xla2/torch_xla2/ops/jaten.py#L306-L327)

Thanks for notice, Nupur, yes, its has been implemented, let me reassign you another issue to try: https://github.com/pytorch/xla/issues/7381
