### ISSUE TITLE
Op info test for `bitwise_right_shift`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7392]
## Fix the Op info test for `bitwise_right_shift`

1. Find the line 19 of [test_ops.py](test/test_ops.py) and remove
   `bitwise_right_shift` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by ManfeiBai** [comment]
Hi, @Barney-s, thanks for contribution! This issue would be one of the first issue, please feel free to reply this issue, so that we could assign it to you

**Comment by barney-s** [comment]
@ManfeiBai - Can i close this one ?

**Comment by ManfeiBai** [comment]
yes, please

**Comment by ManfeiBai** [comment]
Thanks
