### ISSUE TITLE
Op info test for `bucketize`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7396]
## Fix the Op info test for `bucketize`

1. Find the line 23 of [test_ops.py](test/test_ops.py) and remove
   `bucketize` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by ManfeiBai** [comment]
Hi, @simonteozw, thanks for the contribution, this issue would be the first issue to try, please reply in this issue, so that could assign this issue to you

**Comment by simonteozw** [comment]
Hi there, may I be assigned this issue? Thanks!

**Comment by ManfeiBai** [comment]
> Hi there, may I be assigned this issue? Thanks!

thanks, assigned to you

**Comment by simonteozw** [comment]
@ManfeiBai checking if theres still work to be done for this issue or can be marked as completed

**Comment by ManfeiBai** [comment]
Thanks, @simonteozw, this op has been added, let's mark it as done
