### ISSUE TITLE
Coral Edge TPU

### ISSUE THREAD

**Issue by Queuecumber** [pytorch/xla#742]
Does this project work on the Coral Edge TPU (https://coral.withgoogle.com/products/accelerator) for inference, or is it only cloud TPUs?

**Comment by dlibenzi** [comment]
No, sorry. It works either on local CPU, and on Cloud TPUs.

**Comment by Queuecumber** [comment]
Thanks for the quick response, any eventual plans to support edge TPUs or are they completely different in design from the cloud models?

**Comment by dlibenzi** [comment]
If XLA get's an OSS compiler backend for Coral Edge TPUs, yes :)
ATM we use XLA to lower our IR graphs, so XLA support for the target HW is necessary.

**Comment by Queuecumber** [comment]
Cool thanks a lot for the information
