### ISSUE TITLE
Op info test for `gather`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7437]
## Fix the Op info test for `gather`

1. Find the line 84 of [test_ops.py](test/test_ops.py) and remove
   `gather` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by ManfeiBai** [comment]
Hi, @dvhg, this issue will be part of the first issues to try, please feel free to reply so that we could assign this issue to you

**Comment by dvhg** [comment]
Looks like this is already fixed as a part of #8040

**Comment by ManfeiBai** [comment]
Thanks for pointing out, let's replace it with https://github.com/pytorch/xla/issues/7402
