### ISSUE TITLE
Op info test for `log_softmax .. logdet`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7506]
## Fix the Op info test for `log_softmax .. logdet`

1. Find the lines 148 to 152 of [test_ops.py](test/test_ops.py) and remove
   `log_softmax` .. `logdet` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by ManfeiBai** [comment]
reopen for op `logaddexp2`, `logaddexp`, `logcumsumexp`, and `logdet`

**Comment by yenkwang** [comment]
Hello Manfei,

May you create a separate issue for "logdet" or put it together with "linalg.slogdet" or "linalg.det"? It requires more time for me to get "logdet" right.

Thank you!

**Comment by ManfeiBai** [comment]
> Hello Manfei,
> 
> May you create a separate issue for "logdet" or put it together with "linalg.slogdet" or "linalg.det"? It requires more time for me to get "logdet" right.
> 
> Thank you!

sure, sg

created https://github.com/pytorch/xla/issues/7958 for `logdet`, feel free to mention `linalg.slogdet` or `linalg.det` there

let's close this ticke since https://github.com/pytorch/xla/pull/7957 merged
