### ISSUE TITLE
Op info test for `masked.log_softmax .. masked.median`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7509]
## Fix the Op info test for `masked.log_softmax .. masked.median`

1. Find the lines 163 to 167 of [test_ops.py](test/test_ops.py) and remove
   `masked.log_softmax` .. `masked.median` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by ManfeiBai** [comment]
add `masked.log_softmax` to `masked.mean` in https://github.com/pytorch/xla/pull/8014, `masked.median` is hard and created https://github.com/pytorch/xla/issues/8017 to continue track
