### ISSUE TITLE
Op info test for `masked.norm .. masked_select`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7510]
## Fix the Op info test for `masked.norm .. masked_select`

1. Find the lines 168 to 172 of [test_ops.py](test/test_ops.py) and remove
   `masked.norm` .. `masked_select` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by ManfeiBai** [comment]
Hi, @anishfish2, would you mind help to reply this PR? this PR would be your first issue, and after you comment, I would be able to assign it to you

**Comment by anishfish2** [comment]
Claiming this issue!

**Comment by ManfeiBai** [comment]
let's reopen this ticket for `masked_scatter` and `masked_select`

**Comment by ManfeiBai** [comment]
Thanks for the contriburtion!
