### ISSUE TITLE
Op info test for `min .. nanmedian`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7513]
## Fix the Op info test for `min .. nanmedian`

1. Find the lines 183 to 187 of [test_ops.py](test/test_ops.py) and remove
   `min` .. `nanmedian` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by ManfeiBai** [comment]
Hi, @commander, thanks for contribute! this would be the first issue to try to add torch_xla2 ops, please feel free to comment and then I would help to assign this to you

**Comment by simonteozw** [comment]
Hi @ManfeiBai was scanning through some good first issues and don't mind working on this!

**Comment by ManfeiBai** [comment]
Thanks
