### ISSUE TITLE
Op info test for `nanquantile .. native_layer_norm`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7514]
## Fix the Op info test for `nanquantile .. native_layer_norm`

1. Find the lines 188 to 192 of [test_ops.py](test/test_ops.py) and remove
   `nanquantile` .. `native_layer_norm` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by ManfeiBai** [comment]
cc @matinehakhlaghinia, its would be the first issue to try to add torchxla2 ops

**Comment by matinehAkhlaghinia** [comment]
> cc @matinehAkhlaghinia, its would be the first issue to try to add torchxla2 ops

Sounds good, I can work on this

**Comment by ManfeiBai** [comment]
Hi, @matinehAkhlaghinia, thanks for contribution

please feel free to continue to add `nanquantile` and `native_layer_norm`, and we could mention them here too

**Comment by matinehAkhlaghinia** [comment]
Hi, @ManfeiBai, this issue is done now. What would be a good second issue to pick up?

**Comment by ManfeiBai** [comment]
Thanks for your amazing contribution, @matinehAkhlaghinia! These five ops would be the second issue to try: https://github.com/pytorch/xla/issues/7410, https://github.com/pytorch/xla/issues/7413, https://github.com/pytorch/xla/issues/7488, https://github.com/pytorch/xla/issues/7489, https://github.com/pytorch/xla/issues/7490
