### ISSUE TITLE
Op info test for `new_empty .. nn.functional.adaptive_avg_pool2d`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7515]
## Fix the Op info test for `new_empty .. nn.functional.adaptive_avg_pool2d`

1. Find the lines 193 to 197 of [test_ops.py](test/test_ops.py) and remove
   `new_empty` .. `nn.functional.adaptive_avg_pool2d` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by ManfeiBai** [comment]
let's reopen this issue for: "new_empty", "new_empty_strided", "nextafter", "nn.functional.adaptive_avg_pool1d"

**Comment by ManfeiBai** [comment]
Thanks
