### ISSUE TITLE
Op info test for `nn.functional.adaptive_avg_pool3d .. nn.functional.alpha_dropout`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7516]
## Fix the Op info test for `nn.functional.adaptive_avg_pool3d .. nn.functional.alpha_dropout`

1. Find the lines 198 to 202 of [test_ops.py](test/test_ops.py) and remove
   `nn.functional.adaptive_avg_pool3d` .. `nn.functional.alpha_dropout` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by ManfeiBai** [comment]
cc @wenxindongwork
