### ISSUE TITLE
Op info test for `nn.functional.binary_cross_entropy .. nn.functional.conv_transpose2d`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7518]
## Fix the Op info test for `nn.functional.binary_cross_entropy .. nn.functional.conv_transpose2d`

1. Find the lines 208 to 212 of [test_ops.py](test/test_ops.py) and remove
   `nn.functional.binary_cross_entropy` .. `nn.functional.conv_transpose2d` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by ManfeiBai** [comment]
left ops: "nn.functional.conv_transpose1d", "nn.functional.conv_transpose2d"

Hi, @tqfan28, would you like to cover these ops too?
