### ISSUE TITLE
Op info test for `renorm .. rot90`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7531]
## Fix the Op info test for `renorm .. rot90`

1. Find the lines 278 to 282 of [test_ops.py](test/test_ops.py) and remove
   `renorm` .. `rot90` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by ManfeiBai** [comment]
`repeat_interleave` is hard issue, created new issue ticket to track: https://github.com/pytorch/xla/issues/7997
