### ISSUE TITLE
Op info test for `select_scatter .. special.airy_ai`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7533]
## Fix the Op info test for `select_scatter .. special.airy_ai`

1. Find the lines 288 to 292 of [test_ops.py](test/test_ops.py) and remove
   `select_scatter` .. `special.airy_ai` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by yenkwang** [comment]
> [ManfeiBai](/ManfeiBai)

Hi @ManfeiBai, may you split "special.airy_ai" into a separate issue? It takes more time to fix that one.
Here are some useful reference links to implement "special.airy_ai":
* [related commit](https://github.com/pytorch/xla/commit/b13fb655858add672cab251cb2b2391d4eb050d2)
* [reference implementation](https://github.com/pytorch/pytorch/blob/f8f41dcb24cb4f4e87a51bb04847942dd835e496/aten/src/ATen/native/Math.h#L2200-L2377)

Thank you!

**Comment by ManfeiBai** [comment]
> > [ManfeiBai](/ManfeiBai)
> 
> Hi @ManfeiBai, may you split "special.airy_ai" into a separate issue? It takes more time to fix that one. Here are some useful reference links to implement "special.airy_ai":
> 
> * [related commit](https://github.com/pytorch/xla/commit/b13fb655858add672cab251cb2b2391d4eb050d2)
> * [reference implementation](https://github.com/pytorch/pytorch/blob/f8f41dcb24cb4f4e87a51bb04847942dd835e496/aten/src/ATen/native/Math.h#L2200-L2377)
> 
> Thank you!

thanks, sure, created in https://github.com/pytorch/xla/issues/7926
