### ISSUE TITLE
Op info test for `uniform .. var_mean`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7542]
## Fix the Op info test for `uniform .. var_mean`

1. Find the lines 333 to 337 of [test_ops.py](test/test_ops.py) and remove
   `uniform` .. `var_mean` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by ManfeiBai** [comment]
current target should be: "unique_consecutive", "unique", "unravel_index", "var_mean"

**Comment by ManfeiBai** [comment]
HI, @mrguenther, this will be the first issue to try, please feel free to reply so that we would assign it to you

**Comment by mrguenther** [comment]
Sounds good; feel free to assign it to me.

**Comment by mrguenther** [comment]
This can be closed when my pending PRs are merged.
