### ISSUE TITLE
Op info test for `atan2 .. bfloat16`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7545]
## Fix the Op info test for `atan2 .. bfloat16`

1. Find the lines 353 to 357 of [test_ops.py](test/test_ops.py) and remove
   `atan2` .. `bfloat16` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by ManfeiBai** [comment]
current target should be "atleast_1d", "atleast_2d", "atleast_3d", "bfloat16"
