### ISSUE TITLE
Op info test for `index_add .. linalg.diagonal`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7554]
## Fix the Op info test for `index_add .. linalg.diagonal`

1. Find the lines 398 to 402 of [test_ops.py](test/test_ops.py) and remove
   `index_add` .. `linalg.diagonal` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by wenxindongwork** [comment]
working on this

**Comment by wenxindongwork** [comment]
fixed in https://github.com/pytorch/xla/pull/7835
