### ISSUE TITLE
Op info test for `linalg.vecdot .. meshgrid`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7555]
## Fix the Op info test for `linalg.vecdot .. meshgrid`

1. Find the lines 403 to 407 of [test_ops.py](test/test_ops.py) and remove
   `linalg.vecdot` .. `meshgrid` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by wenxindongwork** [comment]
these OPs already pass the tests (no fix needed)

Issue can be closed.

**Comment by wenxindongwork** [comment]
working on this

**Comment by wenxindongwork** [comment]
done in https://github.com/pytorch/xla/pull/7835
