### ISSUE TITLE
Op info test for `native_dropout_backward .. nn.functional.binary_cross_entropy_with_logits`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7557]
## Fix the Op info test for `native_dropout_backward .. nn.functional.binary_cross_entropy_with_logits`

1. Find the lines 413 to 417 of [test_ops.py](test/test_ops.py) and remove
   `native_dropout_backward` .. `nn.functional.binary_cross_entropy_with_logits` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by wenxindongwork** [comment]
working on this

**Comment by wenxindongwork** [comment]
done in https://github.com/pytorch/xla/pull/7835
