### ISSUE TITLE
Failed to install xla gpu

### ISSUE THREAD

**Issue by Beakboomboom** [pytorch/xla#7634]
## ❓ Questions and Help
pip install torch_xla-2.2.0-cp310-cp310-manylinux_2_28_x86_64.whl
But got the error:
ERROR: torch_xla-2.2.0-cp310-cp310-manylinux_2_28_x86_64.whl is not a supported wheel on this platform.

How can i install torch_xla on GPU ?

**Comment by miladm** [comment]
@Beakboomboom 

did you try `https://storage.googleapis.com/pytorch-xla-releases/wheels/cuda/12.1/torch_xla-2.2.0-cp310-cp310-manylinux_2_28_x86_64.whl` from the GPU whl installation instructions on the landing page (https://github.com/pytorch/xla). Let us know if this works for you please.
