### ISSUE TITLE
ddp documentation issues

### ISSUE THREAD

**Issue by miladm** [pytorch/xla#7774]
## 📚 Documentation

Our [documentations](https://pytorch.org/xla/release/2.3/index.html#how-to-use-distributeddataparallel) suggests users must use the following parameters while setting up DDP. This information is outdated. Please remove any such documentations.

```
os.environ['MASTER_ADDR'] = 'localhost'
os.environ['MASTER_PORT'] = '12355'
```

replace with
```
os.environ['PJRT_DEVICE'] = 'TPU'
```

**Comment by mikegre-google** [comment]
Created [PR](https://github.com/pytorch/xla/pull/8322)
