### ISSUE TITLE
[XLA:GPU] compile xla main for gpu，but got error: nvcc fatal   : Unsupported gpu architecture 'compute_35'

### ISSUE THREAD

**Issue by FatJhon** [pytorch/xla#7783]
## ❓ Questions and Help
detail:
NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4
ERROR:
 /root/.cache/bazel/_bazel_root/c0e2b0858c1252f8bcd793250718631d/external/xla/xla/service/gpu/BUILD:4127:13: Compiling xla/service/gpu/[stream_executor_util_kernel.cu.cc](http://stream_executor_util_kernel.cu.cc/) failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command (from target @xla//xla/service/gpu:stream_executor_util_kernel) external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF ... (remaining 66 arguments skipped)
nvcc fatal   : Unsupported gpu architecture 'compute_35'
Target //:_[XLAC.so](http://xlac.so/) failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.532s, Critical Path: 0.22s
INFO: 129 processes: 129 internal.
FAILED: Build did NOT complete successfully

ERROR: /root/.cache/bazel/_bazel_root/c0e2b0858c1252f8bcd793250718631d/external/xla/xla/service/gpu/kernels/BUILD:370:13: Compiling xla/service/gpu/kernels/[cutlass_gemm_kernel_bf16xbf16_to_bf16.cu.cc](http://cutlass_gemm_kernel_bf16xbf16_to_bf16.cu.cc/) failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command (from target @xla//xla/service/gpu/kernels:cutlass_gemm_kernel_bf16xbf16_to_bf16) external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF ... (remaining 126 arguments skipped)
nvcc fatal   : Unsupported gpu architecture 'compute_35'
Target //:_[XLAC.so](http://xlac.so/) failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.101s, Critical Path: 0.24s
INFO: 343 processes: 343 internal.
FAILED: Build did NOT complete successfully
error: command '/usr/local/bin/bazel' failed with exit code 1

**Comment by lsy323** [comment]
Hi @FatJhon, I think Kepler GPUs are removed from CUDA 12.x.

Ref: https://docs.nvidia.com/cuda/archive/12.2.1/cuda-toolkit-release-notes/index.html#cuda-libraries

**Comment by FatJhon** [comment]
> crosstool_wrapper_driver_is_not_gcc

hi@lsy323，thanks for reply. Since Kepler GPUs are removed from CUDA 12.x, i should get lower version of cuda to compile master xla or delete test cu. However, the guide of xla :https://github.com/pytorch/xla/blob/master/docs/gpu.md ,told to use CUDA 12.1, is the text makes a error or i get a wrong understanding.

**Comment by lsy323** [comment]
Hi @FatJhon, we dropped `cuda 11.8` support since 2.2 release. You could try compile with CUDA 11.8 but it's not necessarily work.

**Comment by lsy323** [comment]
Hi @FatJhon, I would recommend to use CUDA 12.x, it's the CUDA version that xla:gpu tested.

**Comment by FatJhon** [comment]
> Kepler GPUs are removed from CUDA 12.x.

i really fused. since  Kepler GPUs are removed from CUDA 12.x, compute_35 error is always exit in cuda 12.x.

**Comment by FatJhon** [comment]
> > Kepler GPUs are removed from CUDA 12.x.
> 
> i really fused. since Kepler GPUs are removed from CUDA 12.x, compute_35 error is always exit in cuda 12.x.

i run on A800.

**Comment by FatJhon** [comment]
> Hi @FatJhon, I would recommend to use CUDA 12.x, it's the CUDA version that xla:gpu tested.

Hi @lsy323，i fused about the solution.  since  Kepler GPUs are removed from CUDA 12.x， how can i compile for gpu dvice using CUDA 12.x，my device is A800.  the compute_35 error is always exits.

**Comment by bhavya01** [comment]
> > Hi @FatJhon, I would recommend to use CUDA 12.x, it's the CUDA version that xla:gpu tested.
> 
> Hi @lsy323，i fused about the solution. since Kepler GPUs are removed from CUDA 12.x， how can i compile for gpu dvice using CUDA 12.x，my device is A800. the compute_35 error is always exits.

I don't see A800 devices in this list https://developer.nvidia.com/cuda-gpus but if you know the compute capability of your device, you can set it using this environment variableTF_CUDA_COMPUTE_CAPABILITY. 

For e.g.
```
export TF_CUDA_COMPUTE_CAPABILITY=compute_75
```
