### ISSUE TITLE
`xla_real_devices()` and `get_xla_supported_devices()` show different results with/without `xmp.spawn()`

### ISSUE THREAD

**Issue by miladm** [pytorch/xla#7790]
## 🐛 Usability Bug

When `xm.xla_real_devices()` or `xm.get_xla_supported_devices()` is called without `xmp.spawn()`, the result is a report of all host devices. After a `xmp.spawn()` call, each process scope is limited to the device it sees - i.e. one device:

Output of `xm.xla_real_devices()` without `xmp.spawn()` on TPU v4-8: 
```
['TPU:0', 'TPU:1', 'TPU:2', 'TPU:3']
```

Output of  `xm.xla_real_devices()` with `xmp.spawn()` on TPU v4-8 - e.g. from the third device process:
```
['TPU:2']
```

This output behavior may confuse users. Suggest we offer a consistent experience independent of the host multi-processing behavior.
It'd be acceptable to cover both use cases under two separate APIs that better represent output expectations.

Perhaps, as part of `xmp.spawn` overhaul, we address this issue also.

cc @will-cromar

**Comment by JackCaoG** [comment]
that's intended, after spawn one host only has one device. without spawn there is only one process and it grabs all of the device.

**Comment by will-cromar** [comment]
This is WAI. `xla.real_devices` corresponds to the output of `xla.devices`, ie only the addressable devices in the current process. PyTorch does not have a device type that represents non-addressable devices, so something like JAX's `jax.devices` (all global devices, including other process') would not make sense in PyTorch/XLA.
