### ISSUE TITLE
Is it possible free TPU memory without restarting in pytorch xla?

### ISSUE THREAD

**Issue by fengyang0317** [pytorch/xla#7849]
## 📚 Documentation
I have tried to move a TPU tensor to CPU or delete the tensor. However, the memory is not released.

https://colab.research.google.com/drive/1pTTDu_eJssUwjsrjBDiiyo6tlOEZTjMf?usp=sharing

**Comment by JackCaoG** [comment]
The XLA memory is controlled by the reference counted, if you remove all of the reference to the XLATensor and do a python garbage collect the XLA memory should be released.

**Comment by fengyang0317** [comment]
Thanks for reply.

**Comment by fengyang0317** [comment]
@JackCaoG  I tested using a GPU. I have set `PJRT_DEVICE=CUDA`

```
import gc
import os

import torch
import torch_xla  # noqa

os.system('nvidia-smi --query-gpu=memory.used,memory.free,memory.total --format=csv')

x = torch.zeros([1000, 1000, 1000]).to('xla')

os.system('nvidia-smi --query-gpu=memory.used,memory.free,memory.total --format=csv,noheader')

del x
gc.collect()

os.system('nvidia-smi --query-gpu=memory.used,memory.free,memory.total --format=csv,noheader')

```

The above commands outputs
```
memory.used [MiB], memory.free [MiB], memory.total [MiB]
104 MiB, 8006 MiB, 8192 MiB
6280 MiB, 1830 MiB, 8192 MiB
6280 MiB, 1830 MiB, 8192 MiB
```

After garbage collect, the GPU memory is still used.

**Comment by fengyang0317** [comment]
If using pytorch, the memory is freed.

```
import gc
import os
import torch

os.system('nvidia-smi --query-gpu=memory.used,memory.free,memory.total --format=csv')

x = torch.zeros([1000, 1000, 1000]).to('cuda')

os.system('nvidia-smi --query-gpu=memory.used,memory.free,memory.total --format=csv,noheader')

del x
gc.collect()
torch.cuda.empty_cache()
os.system('nvidia-smi --query-gpu=memory.used,memory.free,memory.total --format=csv,noheader')
```

```
memory.used [MiB], memory.free [MiB], memory.total [MiB]
104 MiB, 8006 MiB, 8192 MiB
4010 MiB, 4100 MiB, 8192 MiB
194 MiB, 7916 MiB, 8192 MiB
```

**Comment by JackCaoG** [comment]
GPU is a bit special I believe, I think the default behavior of the GPU runtime is to grab a certain percentage(75% default I believe) of GPU memory and keep it for the runtime. This way runtime does not need to constantly request small amount of memory from the GPU for small allocation and this will make overall run time better.

**Comment by fengyang0317** [comment]
I see. Thanks
