### ISSUE TITLE
torch_xla.distributed.parallel_loader doesn't shard data

### ISSUE THREAD

**Issue by davidaknowles** [pytorch/xla#7904]
## ❓ Questions and Help

Maybe this is a misunderstanding on my part, but I assumed part of `MpDeviceLoader`s job was to split/shard data across devices. However the test below shows it doesn't do this: all 4 devices on my v4 receive all 12 datapoints. What am I missing here? Thanks. 

```
import torch
import torch_xla.core.xla_model as xm
from torch_xla import runtime as xr
import torch_xla.distributed.parallel_loader as pl
import torch_xla.distributed.xla_multiprocessing as xmp

def test_parallel_loader(rank):

    data = torch.arange(12).reshape(-1, 1)
    dataset = torch.utils.data.TensorDataset(data)
    dataloader = torch.utils.data.DataLoader(dataset, batch_size=2)
    
    parallel_loader = pl.MpDeviceLoader(dataloader, xm.xla_device())
    results = sum([batch[0].tolist() for batch in parallel_loader], [])

    print(f"Device {rank} received data: {results}")
    
    expected_data_size = len(data) // xr.world_size()
    print(f"Device {rank} received {len(results)} datapoints, expected {expected_data_size}")

if __name__ == "__main__":
    xmp.spawn(test_parallel_loader, args=()) 
```

**Comment by JackCaoG** [comment]
Let me take a look

**Comment by bhavya01** [comment]
In this case, it is working as expected. The MpDeviceLoader in each spawned process will asynchronously get batches from the torch dataloader and put them on the TPU. If you use SPMD and just spawn one process and specify `input_sharding` such that it shard on the batch size, then you should see that batch is spread out over multiple devices.

**Comment by JackCaoG** [comment]
To add on what @bhavya01 ParallelLoader itself does not handle distributing the correct data to each worker, it is the dataloder it wrapped needs to do that.

In our MP example it is 
https://github.com/pytorch/xla/blob/3d860bf4f5ad0f20665245ba470ac7f5886f50f7/test/test_train_mp_imagenet.py#L222-L226
doing this work. In the GSPMD case it is the sharding we passed to the `ParallelLoader` does that distribution. In my example I only used fake data loader so this is not an issue, I can fix that to make it more clear.

**Comment by davidaknowles** [comment]
I see, this is just a documentation issue then, e.g. https://pytorch.org/xla/release/r2.4/index.html#running-on-multiple-xla-devices-with-multi-processing gave me the impression wrapping my existing (single process) dataloader was sufficient. And yes it would probably be helpful to have your toy data use DistributedSampler so if people just their own real data in there it will do something sensible.

**Comment by JackCaoG** [comment]
yea let me update
