### ISSUE TITLE
Documentation: Discoverability of http://pytorch.org/xla

### ISSUE THREAD

**Issue by tengyifei** [pytorch/xla#7911]
## 📚 Documentation: Discoverability of http://pytorch.org/xla

The docs are very hard to find _despite_ being hosted on [pytorch.org](http://pytorch.org/). If I visit [pytorch.org](http://pytorch.org/) I can't find any link that goes to [pytorch.org/xla](http://pytorch.org/xla). The closest I could find is somewhere deep in https://pytorch.org/pytorch-domains and even then it links to version 2.1! I think the discoverability can use some support possibly after we've polished up the landing page.

**Comment by tengyifei** [comment]
cc @mikegre-google  Milad mentioned you may be able to help with this. Putting it on your radar. Thanks!

**Comment by tengyifei** [comment]
@mikegre-google What are your thoughts on how this could be improved?

**Comment by mikegre-google** [comment]
@tengyifei  I'm working on reorganizing the docs and their TOC. We'd have to create a PR to add a link to the Pytorch/XLA docs. The question is where the link should go. I'll look into this. I don't see a way to assign this issue to me. It may be a permissions issue. Can you assign it to me? Thanks!

**Comment by tengyifei** [comment]
Thanks! I think I set the assignee correctly now.

**Comment by mikegre-google** [comment]
Yes, it's assigned to me now. Thanks!

**Comment by mikegre-google** [comment]
I created a PR (https://github.com/pytorch/xla/pull/7988) that reorganizes the documentation on pytorch.org/xla

**Comment by mikegre-google** [comment]
The PR (https://github.com/pytorch/xla/pull/8246) has been merged. The new TOC will be available when PyTorch/XLA 2.5 is released.
