### ISSUE TITLE
Prepare a documentation to explain the use cases for `torch.compile`, `torch_xla.compile`, torch_xla eager mode, torchxla2

### ISSUE THREAD

**Issue by miladm** [pytorch/xla#7925]
## 📚 Documentation

Author a documentation to explain the use cases for `torch.compile`, `torch_xla.compile`, torch_xla eager mode, torchxla2. Users and customers look for clarity on the "the utility" of each option, pros/cons, small example to demonstrate correct use.

cc @ManfeiBai @JackCaoG @will-cromar @qihqi

**Comment by miladm** [comment]
cc @jeffhataws @amithrm

**Comment by will-cromar** [comment]
Thanks @JackCaoG for writing https://github.com/pytorch/xla/blob/master/docs/eager.md
