### ISSUE TITLE
How to use a cluster of tpus?

### ISSUE THREAD

**Issue by Rexhaif** [pytorch/xla#793]
Hi,
The documentation described the use case with only one cloud tpu. However, in tensorflow it is possible to setup multiple TPU's via TPUClusterResolver. So, how to setup pytorch-xla for training on a multiple tpu devices?. In my case it is 25 preemptible v2-8 TPUs.

**Comment by dlibenzi** [comment]
The support for TF-like interconnected TPUs (as/similar to TPUClusterResolver) will come towards the end of this year.
