### ISSUE TITLE
[hard] Op info test for `masked.median`

### ISSUE THREAD

**Issue by ManfeiBai** [pytorch/xla#8017]
## Fix the Op info test for `repeat_interleave`

1. Find the lines of `masked.median` in [test_ops.py](test/test_ops.py) and remove
   `masked.median` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by ManfeiBai** [comment]
working in https://github.com/pytorch/xla/pull/8016

**Comment by dvhg** [comment]
`masked.median` is passing as of #8296
