### ISSUE TITLE
Is there any detailed document on how to build and train Pytorch network on TPU?

### ISSUE THREAD

**Issue by anhle-uet** [pytorch/xla#802]
Hi, I couldn't find any detailed guide or tutorial on how to use this project. Could you point me out some? Thanks a lot!

**Comment by dlibenzi** [comment]
Hi Anh,
have you seen the README file?

https://github.com/pytorch/xla/blob/master/README.md

This is normal PyTorch, so aside some minor outer code (main function / training loop) changes for multi-core support, you should be able to just run pytorch code.
Assuming you have a Google Cloud TPU VM configured.

**Comment by anhle-uet** [comment]
@dlibenzi  Thank you for quick reply!
All I see in README file is installation instructions. I'm still clueless about some "some minor outer code changes" that you've mentioned. Beside, can the trained model run on GPU?

**Comment by dlibenzi** [comment]
Maybe looking at the MNIST example will help?

https://github.com/pytorch/xla/blob/master/test/test_train_mnist.py

That is all normal PyTorch code, aside few lines to get the supported XLA devices, create a `DataParallel`, and run the optimizer step (`xm.optimizer_step()`).

Running using PyTorch/XLA with GPU support (effectively using XLA to generate code for GPU) is currently not supported.
The good news is that normal PyTorch already haas good GPU support.
