### ISSUE TITLE
How to monitor the TPU utilization and memory usage when training?

### ISSUE THREAD

**Issue by anhle-uet** [pytorch/xla#803]

**Comment by jysohn23** [comment]
You can capture the [TPU profile](https://cloud.google.com/tpu/docs/cloud-tpu-tools#capture_profile) and then view it on Tensorboard or stream the [TPU utilization](https://cloud.google.com/tpu/docs/cloud-tpu-tools#monitor_job). This should tell you the device utilization levels (MXU utilization, device memory usage, etc).

To see the host (not device) CPU, Memory, etc. utilization levels, you can check the GCP UI for TPUs, after you click on a single TPU.

**Comment by jysohn23** [comment]
Closing for now. Feel free to reopen if you have any more questions.

**Comment by NightMachinary** [comment]
How does this work for Colab?

**Comment by JackCaoG** [comment]
@NightMachinary Please take a look at https://github.com/pytorch/xla/blob/master/contrib/colab/pytorch-xla-profiling-colab.ipynb
