### ISSUE TITLE
test_operations.py NaN error

### ISSUE THREAD

**Issue by zcain117** [pytorch/xla#817]
If I run test/test_operations.py on CPU, the tests all pass.

If I run on TPU, the TestParallelTensorMNIST fails with:

Exception in model function for device=xla:1: nan not less than 3.0
Traceback (most recent call last):
  File "/home/zcain/pytorch/xla/torch_xla_py/data_parallel.py", line 226, in _module_runner
    result.result = loop_fn(module, loader, torch.device(device), context)
  File "xla/test/test_operations.py", line 285, in loop_fn
    self.assertLess(loss.cpu().item(), 3.0)
  File "/home/zcain/anaconda3/envs/pytorch/lib/python3.6/unittest/case.py", line 1209, in assertLess
    self.fail(self._formatMessage(msg, standardMsg))
  File "/home/zcain/anaconda3/envs/pytorch/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: nan not less than 3.0

The model seems to proceed successfully for several iterations before the loss explodes:

Model: 53.206ms
Model: 49.959ms
Loss: 0.902ms
Model: 51.759ms
Loss: 0.627ms
Model: 47.058ms
Model: 52.084ms
Loss: 1.127ms
Loss: 0.681ms
Loss: 0.648ms
Model: 53.775ms
Model: 51.949ms
Loss: 0.687ms
Loss: 0.524ms
LossBkw: 5.672ms
LossBkw: 7.027ms
LossBkw: 6.371ms
LossBkw: 7.101ms
LossBkw: 4.480ms
LossBkw: 9.143ms
LossBkw: 5.608ms
Model: 59.875ms
Loss: 0.692ms
LossBkw: 4.728ms
Step: 42.586ms
Step: 46.797ms
Step: 37.877ms
Step: 46.587ms
Step: 45.343ms
Step: 46.446ms
Step: 136.001ms
Step: 132.756ms
Training loop: 525.523ms
Training loop: 527.763ms
Training loop: 525.106ms
Training loop: 532.019ms
Training loop: 529.574ms
Model: 5.948ms
Model: 5.851ms
Model: 6.446ms
Loss: 0.552ms
Model: 5.419ms
Loss: 0.559ms
Model: 6.527ms
Loss: 1.799ms
Loss: 0.656ms
Loss: 0.629ms
LossBkw: 5.052ms
LossBkw: 6.268ms
LossBkw: 4.664ms
LossBkw: 5.510ms
LossBkw: 5.860ms
Training loop: 570.138ms
Model: 3.114ms
Loss: 0.592ms
LossBkw: 4.574ms
Training loop: 603.838ms
Model: 3.017ms
Loss: 0.641ms
LossBkw: 4.619ms
Training loop: 675.843ms

**Comment by zcain117** [comment]
This was using TPU v2-8 | pytorch-0.1 and after building from scratch on a fresh red VM using scripts/build_torch_wheels.sh

**Comment by jysohn23** [comment]
You probably want to use nightly TPU version if you're using the latest HEAD on the client side. I was able to get all the tests to pass with latest docker (gcr.io/tpu-pytorch/xla:nightly_20190711) + nightly TPU.

**Comment by zcain117** [comment]
Good call!
The tests in this file all pass when building from head and using nightly TPU
