### ISSUE TITLE
Model support for `stable_diffusion_unet` with Torch_XLA2

### ISSUE THREAD

**Issue by ManfeiBai** [pytorch/xla#8184]
## Fix the model test for `stable_diffusion_unet.py`

1. setup env according to [Run a model under torch_xla2](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/support_a_new_model.md)
2. Run model test under `run_torchbench/` with `python models/your_target_model_name.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/support_a_new_model.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7583

**Comment by barney-s** [comment]
Please assign it to me. Iam starting to work on this.

**Comment by barney-s** [comment]
Installing requirements failed: 
```
% python3 install.py stable_diffusion_unet 

checking packages numpy, torch, torchvision, torchaudio are installed, generating constaints...OK
Failed to install torchbenchmark requirements:
b"Collecting git+https://github.com/huggingface/pytorch-image-models.git@730b907 (from -r requirements.txt (line 12))\n  Cloning https://github.com/huggingface/pytorch-image-models.git (to revision 730b907) to /tmp/pip-req-build-_tkp2_a1\n  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/pytorch-image-models.git /tmp/pip-req-build-_tkp2_a1\n  WARNING: Did not find branch or tag '730b907', assuming revision or ref.\n  Running command git checkout -q 730b907\n  Resolved https://github.com/huggingface/pytorch-image-models.git to commit 730b907\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'done'\n  Preparing metadata (pyproject.toml): started\n  Preparing metadata (pyproject.toml): finished with status 'done'\nCollecting accelerate (from -r requirements.txt (line 1))\n  Downloading accelerate-1.0.1-py3-none-any.whl.metadata (19 kB)\nCollecting boto3 (from -r requirements.txt (line 2))\n  Downloading boto3-1.35.46-py3-none-any.whl.metadata (6.7 kB)\nCollecting bs4 (from -r requirements.txt (line 3))\n  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)\nCollecting patch (from -r requirements.txt (line 4))\n  Downloading patch-1.16.zip (12 kB)\n  Preparing metadata (setup.py): started\n  Preparing metadata (setup.py): finished with status 'done'\nCollecting py-cpuinfo (from -r requirements.txt (line 5))\n  Downloading py_cpuinfo-9.0.0-py3-none-any.whl.metadata (794 bytes)\nCollecting distro (from -r requirements.txt (line 6))\n  Downloading distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)\nCollecting iopath (from -r requirements.txt (line 7))\n  Downloading iopath-0.1.10.tar.gz (42 kB)\n  Preparing metadata (setup.py): started\n  Preparing metadata (setup.py): finished with status 'done'\nRequirement already satisfied: pytest in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (8.3.2)\nCollecting pytest-benchmark (from -r requirements.txt (line 9))\n  Downloading pytest_benchmark-4.0.0-py3-none-any.whl.metadata (23 kB)\nRequirement already satisfied: requests in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (2.32.3)\nCollecting tabulate (from -r requirements.txt (line 11))\n  Downloading tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)\nCollecting transformers==4.44.2 (from -r requirements.txt (line 15))\n  Downloading transformers-4.44.2-py3-none-any.whl.metadata (43 kB)\nCollecting MonkeyType (from -r requirements.txt (line 16))\n  Downloading MonkeyType-23.3.0-py3-none-any.whl.metadata (12 kB)\nCollecting psutil (from -r requirements.txt (line 17))\n  Downloading psutil-6.1.0-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (22 kB)\nRequirement already satisfied: pyyaml in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from -r requirements.txt (line 18)) (6.0.2)\nRequirement already satisfied: numpy in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from -r requirements.txt (line 19)) (1.26.4)\nCollecting opencv-python (from -r requirements.txt (line 20))\n  Downloading opencv_python-4.10.0.84-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)\nCollecting submitit (from -r requirements.txt (line 21))\n  Downloading submitit-1.5.2-py3-none-any.whl.metadata (7.9 kB)\nCollecting pynvml (from -r requirements.txt (line 22))\n  Downloading pynvml-11.5.3-py3-none-any.whl.metadata (8.8 kB)\nRequirement already satisfied: filelock in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from transformers==4.44.2->-r requirements.txt (line 15)) (3.15.4)\nCollecting huggingface-hub<1.0,>=0.23.2 (from transformers==4.44.2->-r requirements.txt (line 15))\n  Downloading huggingface_hub-0.26.1-py3-none-any.whl.metadata (13 kB)\nRequirement already satisfied: packaging>=20.0 in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from transformers==4.44.2->-r requirements.txt (line 15)) (24.1)\nCollecting regex!=2019.12.17 (from transformers==4.44.2->-r requirements.txt (line 15))\n  Downloading regex-2024.9.11-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)\nCollecting safetensors>=0.4.1 (from transformers==4.44.2->-r requirements.txt (line 15))\n  Downloading safetensors-0.4.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)\nCollecting tokenizers<0.20,>=0.19 (from transformers==4.44.2->-r requirements.txt (line 15))\n  Downloading tokenizers-0.19.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)\nCollecting tqdm>=4.27 (from transformers==4.44.2->-r requirements.txt (line 15))\n  Downloading tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)\nINFO: pip is looking at multiple versions of accelerate to determine which version is compatible with other requirements. This could take a while.\nCollecting accelerate (from -r requirements.txt (line 1))\n  Downloading accelerate-1.0.0-py3-none-any.whl.metadata (19 kB)\n  Downloading accelerate-0.34.2-py3-none-any.whl.metadata (19 kB)\n  Downloading accelerate-0.34.1-py3-none-any.whl.metadata (19 kB)\n  Downloading accelerate-0.34.0-py3-none-any.whl.metadata (19 kB)\n  Downloading accelerate-0.33.0-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.32.1-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.32.0-py3-none-any.whl.metadata (18 kB)\nINFO: pip is still looking at multiple versions of accelerate to determine which version is compatible with other requirements. This could take a while.\n  Downloading accelerate-0.31.0-py3-none-any.whl.metadata (19 kB)\n  Downloading accelerate-0.30.1-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.30.0-py3-none-any.whl.metadata (19 kB)\n  Downloading accelerate-0.29.3-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.29.2-py3-none-any.whl.metadata (18 kB)\nINFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.\n  Downloading accelerate-0.29.1-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.29.0-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.28.0-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.27.2-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.27.1-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.27.0-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.26.1-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.26.0-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.25.0-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.24.1-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.24.0-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.23.0-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.22.0-py3-none-any.whl.metadata (17 kB)\n  Downloading accelerate-0.21.0-py3-none-any.whl.metadata (17 kB)\n  Downloading accelerate-0.20.3-py3-none-any.whl.metadata (17 kB)\n  Downloading accelerate-0.20.2-py3-none-any.whl.metadata (17 kB)\n  Downloading accelerate-0.20.1-py3-none-any.whl.metadata (17 kB)\n  Downloading accelerate-0.20.0-py3-none-any.whl.metadata (17 kB)\n  Downloading accelerate-0.19.0-py3-none-any.whl.metadata (16 kB)\n  Downloading accelerate-0.18.0-py3-none-any.whl.metadata (16 kB)\n  Downloading accelerate-0.17.1-py3-none-any.whl.metadata (16 kB)\n  Downloading accelerate-0.17.0-py3-none-any.whl.metadata (16 kB)\n  Downloading accelerate-0.16.0-py3-none-any.whl.metadata (15 kB)\n  Downloading accelerate-0.15.0-py3-none-any.whl.metadata (15 kB)\n  Downloading accelerate-0.14.0-py3-none-any.whl.metadata (15 kB)\n  Downloading accelerate-0.13.2-py3-none-any.whl.metadata (15 kB)\n  Downloading accelerate-0.13.1-py3-none-any.whl.metadata (15 kB)\n  Downloading accelerate-0.13.0-py3-none-any.whl.metadata (15 kB)\n  Downloading accelerate-0.12.0-py3-none-any.whl.metadata (15 kB)\n  Downloading accelerate-0.11.0-py3-none-any.whl.metadata (14 kB)\n  Downloading accelerate-0.10.0-py3-none-any.whl.metadata (14 kB)\n  Downloading accelerate-0.9.0-py3-none-any.whl.metadata (13 kB)\n  Downloading accelerate-0.8.0-py3-none-any.whl.metadata (13 kB)\n  Downloading accelerate-0.7.1-py3-none-any.whl.metadata (13 kB)\n  Downloading accelerate-0.7.0-py3-none-any.whl.metadata (13 kB)\n  Downloading accelerate-0.6.2-py3-none-any.whl.metadata (13 kB)\n  Downloading accelerate-0.6.1-py3-none-any.whl.metadata (13 kB)\n  Downloading accelerate-0.6.0-py3-none-any.whl.metadata (13 kB)\n  Downloading accelerate-0.5.1-py3-none-any.whl.metadata (11 kB)\n  Downloading accelerate-0.5.0-py3-none-any.whl.metadata (11 kB)\n  Downloading accelerate-0.4.0-py3-none-any.whl.metadata (11 kB)\n  Downloading accelerate-0.3.0-py3-none-any.whl.metadata (9.4 kB)\n  Downloading accelerate-0.2.1-py3-none-any.whl.metadata (8.5 kB)\n  Downloading accelerate-0.2.0-py3-none-any.whl.metadata (8.5 kB)\n  Downloading accelerate-0.1.0-py3-none-any.whl.metadata (9.7 kB)\n  Downloading accelerate-0.0.1-py3-none-any.whl.metadata (853 bytes)\nCollecting botocore<1.36.0,>=1.35.46 (from boto3->-r requirements.txt (line 2))\n  Downloading botocore-1.35.46-py3-none-any.whl.metadata (5.7 kB)\nCollecting jmespath<2.0.0,>=0.7.1 (from boto3->-r requirements.txt (line 2))\n  Downloading jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)\nCollecting s3transfer<0.11.0,>=0.10.0 (from boto3->-r requirements.txt (line 2))\n  Downloading s3transfer-0.10.3-py3-none-any.whl.metadata (1.7 kB)\nCollecting beautifulsoup4 (from bs4->-r requirements.txt (line 3))\n  Downloading beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)\nRequirement already satisfied: typing_extensions in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from iopath->-r requirements.txt (line 7)) (4.12.2)\nCollecting portalocker (from iopath->-r requirements.txt (line 7))\n  Downloading portalocker-2.10.1-py3-none-any.whl.metadata (8.5 kB)\nRequirement already satisfied: iniconfig in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from pytest->-r requirements.txt (line 8)) (2.0.0)\nRequirement already satisfied: pluggy<2,>=1.5 in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from pytest->-r requirements.txt (line 8)) (1.5.0)\nRequirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from pytest->-r requirements.txt (line 8)) (1.2.2)\nRequirement already satisfied: tomli>=1 in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from pytest->-r requirements.txt (line 8)) (2.0.1)\nRequirement already satisfied: charset-normalizer<4,>=2 in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from requests->-r requirements.txt (line 10)) (3.3.2)\nRequirement already satisfied: idna<4,>=2.5 in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from requests->-r requirements.txt (line 10)) (3.8)\nRequirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from requests->-r requirements.txt (line 10)) (2.2.2)\nRequirement already satisfied: certifi>=2017.4.17 in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from requests->-r requirements.txt (line 10)) (2024.8.30)\nINFO: pip is looking at multiple versions of timm to determine which version is compatible with other requirements. This could take a while.\nERROR: Cannot install -r requirements.txt (line 12) because these package versions have conflicting dependencies.\n\nThe conflict is caused by:\n    timm 0.9.7 depends on torch>=1.7\n    The user requested (constraint) torch==2.5.0+cu124\n\nTo fix this you could try to:\n1. loosen the range of package versions you've specified\n2. remove package versions to allow pip to attempt to solve the dependency conflict\n\nERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts\n"
barni@barni ~/workspace/pytorch/benchmark
 % 
```

**Comment by ManfeiBai** [comment]
> Installing requirements failed:
> 
> ```
> % python3 install.py stable_diffusion_unet 
> 
> checking packages numpy, torch, torchvision, torchaudio are installed, generating constaints...OK
> Failed to install torchbenchmark requirements:
> b"Collecting git+https://github.com/huggingface/pytorch-image-models.git@730b907 (from -r requirements.txt (line 12))\n  Cloning https://github.com/huggingface/pytorch-image-models.git (to revision 730b907) to /tmp/pip-req-build-_tkp2_a1\n  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/pytorch-image-models.git /tmp/pip-req-build-_tkp2_a1\n  WARNING: Did not find branch or tag '730b907', assuming revision or ref.\n  Running command git checkout -q 730b907\n  Resolved https://github.com/huggingface/pytorch-image-models.git to commit 730b907\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'done'\n  Preparing metadata (pyproject.toml): started\n  Preparing metadata (pyproject.toml): finished with status 'done'\nCollecting accelerate (from -r requirements.txt (line 1))\n  Downloading accelerate-1.0.1-py3-none-any.whl.metadata (19 kB)\nCollecting boto3 (from -r requirements.txt (line 2))\n  Downloading boto3-1.35.46-py3-none-any.whl.metadata (6.7 kB)\nCollecting bs4 (from -r requirements.txt (line 3))\n  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)\nCollecting patch (from -r requirements.txt (line 4))\n  Downloading patch-1.16.zip (12 kB)\n  Preparing metadata (setup.py): started\n  Preparing metadata (setup.py): finished with status 'done'\nCollecting py-cpuinfo (from -r requirements.txt (line 5))\n  Downloading py_cpuinfo-9.0.0-py3-none-any.whl.metadata (794 bytes)\nCollecting distro (from -r requirements.txt (line 6))\n  Downloading distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)\nCollecting iopath (from -r requirements.txt (line 7))\n  Downloading iopath-0.1.10.tar.gz (42 kB)\n  Preparing metadata (setup.py): started\n  Preparing metadata (setup.py): finished with status 'done'\nRequirement already satisfied: pytest in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (8.3.2)\nCollecting pytest-benchmark (from -r requirements.txt (line 9))\n  Downloading pytest_benchmark-4.0.0-py3-none-any.whl.metadata (23 kB)\nRequirement already satisfied: requests in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (2.32.3)\nCollecting tabulate (from -r requirements.txt (line 11))\n  Downloading tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)\nCollecting transformers==4.44.2 (from -r requirements.txt (line 15))\n  Downloading transformers-4.44.2-py3-none-any.whl.metadata (43 kB)\nCollecting MonkeyType (from -r requirements.txt (line 16))\n  Downloading MonkeyType-23.3.0-py3-none-any.whl.metadata (12 kB)\nCollecting psutil (from -r requirements.txt (line 17))\n  Downloading psutil-6.1.0-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (22 kB)\nRequirement already satisfied: pyyaml in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from -r requirements.txt (line 18)) (6.0.2)\nRequirement already satisfied: numpy in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from -r requirements.txt (line 19)) (1.26.4)\nCollecting opencv-python (from -r requirements.txt (line 20))\n  Downloading opencv_python-4.10.0.84-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)\nCollecting submitit (from -r requirements.txt (line 21))\n  Downloading submitit-1.5.2-py3-none-any.whl.metadata (7.9 kB)\nCollecting pynvml (from -r requirements.txt (line 22))\n  Downloading pynvml-11.5.3-py3-none-any.whl.metadata (8.8 kB)\nRequirement already satisfied: filelock in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from transformers==4.44.2->-r requirements.txt (line 15)) (3.15.4)\nCollecting huggingface-hub<1.0,>=0.23.2 (from transformers==4.44.2->-r requirements.txt (line 15))\n  Downloading huggingface_hub-0.26.1-py3-none-any.whl.metadata (13 kB)\nRequirement already satisfied: packaging>=20.0 in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from transformers==4.44.2->-r requirements.txt (line 15)) (24.1)\nCollecting regex!=2019.12.17 (from transformers==4.44.2->-r requirements.txt (line 15))\n  Downloading regex-2024.9.11-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)\nCollecting safetensors>=0.4.1 (from transformers==4.44.2->-r requirements.txt (line 15))\n  Downloading safetensors-0.4.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)\nCollecting tokenizers<0.20,>=0.19 (from transformers==4.44.2->-r requirements.txt (line 15))\n  Downloading tokenizers-0.19.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)\nCollecting tqdm>=4.27 (from transformers==4.44.2->-r requirements.txt (line 15))\n  Downloading tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)\nINFO: pip is looking at multiple versions of accelerate to determine which version is compatible with other requirements. This could take a while.\nCollecting accelerate (from -r requirements.txt (line 1))\n  Downloading accelerate-1.0.0-py3-none-any.whl.metadata (19 kB)\n  Downloading accelerate-0.34.2-py3-none-any.whl.metadata (19 kB)\n  Downloading accelerate-0.34.1-py3-none-any.whl.metadata (19 kB)\n  Downloading accelerate-0.34.0-py3-none-any.whl.metadata (19 kB)\n  Downloading accelerate-0.33.0-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.32.1-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.32.0-py3-none-any.whl.metadata (18 kB)\nINFO: pip is still looking at multiple versions of accelerate to determine which version is compatible with other requirements. This could take a while.\n  Downloading accelerate-0.31.0-py3-none-any.whl.metadata (19 kB)\n  Downloading accelerate-0.30.1-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.30.0-py3-none-any.whl.metadata (19 kB)\n  Downloading accelerate-0.29.3-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.29.2-py3-none-any.whl.metadata (18 kB)\nINFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.\n  Downloading accelerate-0.29.1-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.29.0-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.28.0-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.27.2-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.27.1-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.27.0-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.26.1-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.26.0-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.25.0-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.24.1-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.24.0-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.23.0-py3-none-any.whl.metadata (18 kB)\n  Downloading accelerate-0.22.0-py3-none-any.whl.metadata (17 kB)\n  Downloading accelerate-0.21.0-py3-none-any.whl.metadata (17 kB)\n  Downloading accelerate-0.20.3-py3-none-any.whl.metadata (17 kB)\n  Downloading accelerate-0.20.2-py3-none-any.whl.metadata (17 kB)\n  Downloading accelerate-0.20.1-py3-none-any.whl.metadata (17 kB)\n  Downloading accelerate-0.20.0-py3-none-any.whl.metadata (17 kB)\n  Downloading accelerate-0.19.0-py3-none-any.whl.metadata (16 kB)\n  Downloading accelerate-0.18.0-py3-none-any.whl.metadata (16 kB)\n  Downloading accelerate-0.17.1-py3-none-any.whl.metadata (16 kB)\n  Downloading accelerate-0.17.0-py3-none-any.whl.metadata (16 kB)\n  Downloading accelerate-0.16.0-py3-none-any.whl.metadata (15 kB)\n  Downloading accelerate-0.15.0-py3-none-any.whl.metadata (15 kB)\n  Downloading accelerate-0.14.0-py3-none-any.whl.metadata (15 kB)\n  Downloading accelerate-0.13.2-py3-none-any.whl.metadata (15 kB)\n  Downloading accelerate-0.13.1-py3-none-any.whl.metadata (15 kB)\n  Downloading accelerate-0.13.0-py3-none-any.whl.metadata (15 kB)\n  Downloading accelerate-0.12.0-py3-none-any.whl.metadata (15 kB)\n  Downloading accelerate-0.11.0-py3-none-any.whl.metadata (14 kB)\n  Downloading accelerate-0.10.0-py3-none-any.whl.metadata (14 kB)\n  Downloading accelerate-0.9.0-py3-none-any.whl.metadata (13 kB)\n  Downloading accelerate-0.8.0-py3-none-any.whl.metadata (13 kB)\n  Downloading accelerate-0.7.1-py3-none-any.whl.metadata (13 kB)\n  Downloading accelerate-0.7.0-py3-none-any.whl.metadata (13 kB)\n  Downloading accelerate-0.6.2-py3-none-any.whl.metadata (13 kB)\n  Downloading accelerate-0.6.1-py3-none-any.whl.metadata (13 kB)\n  Downloading accelerate-0.6.0-py3-none-any.whl.metadata (13 kB)\n  Downloading accelerate-0.5.1-py3-none-any.whl.metadata (11 kB)\n  Downloading accelerate-0.5.0-py3-none-any.whl.metadata (11 kB)\n  Downloading accelerate-0.4.0-py3-none-any.whl.metadata (11 kB)\n  Downloading accelerate-0.3.0-py3-none-any.whl.metadata (9.4 kB)\n  Downloading accelerate-0.2.1-py3-none-any.whl.metadata (8.5 kB)\n  Downloading accelerate-0.2.0-py3-none-any.whl.metadata (8.5 kB)\n  Downloading accelerate-0.1.0-py3-none-any.whl.metadata (9.7 kB)\n  Downloading accelerate-0.0.1-py3-none-any.whl.metadata (853 bytes)\nCollecting botocore<1.36.0,>=1.35.46 (from boto3->-r requirements.txt (line 2))\n  Downloading botocore-1.35.46-py3-none-any.whl.metadata (5.7 kB)\nCollecting jmespath<2.0.0,>=0.7.1 (from boto3->-r requirements.txt (line 2))\n  Downloading jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)\nCollecting s3transfer<0.11.0,>=0.10.0 (from boto3->-r requirements.txt (line 2))\n  Downloading s3transfer-0.10.3-py3-none-any.whl.metadata (1.7 kB)\nCollecting beautifulsoup4 (from bs4->-r requirements.txt (line 3))\n  Downloading beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)\nRequirement already satisfied: typing_extensions in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from iopath->-r requirements.txt (line 7)) (4.12.2)\nCollecting portalocker (from iopath->-r requirements.txt (line 7))\n  Downloading portalocker-2.10.1-py3-none-any.whl.metadata (8.5 kB)\nRequirement already satisfied: iniconfig in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from pytest->-r requirements.txt (line 8)) (2.0.0)\nRequirement already satisfied: pluggy<2,>=1.5 in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from pytest->-r requirements.txt (line 8)) (1.5.0)\nRequirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from pytest->-r requirements.txt (line 8)) (1.2.2)\nRequirement already satisfied: tomli>=1 in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from pytest->-r requirements.txt (line 8)) (2.0.1)\nRequirement already satisfied: charset-normalizer<4,>=2 in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from requests->-r requirements.txt (line 10)) (3.3.2)\nRequirement already satisfied: idna<4,>=2.5 in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from requests->-r requirements.txt (line 10)) (3.8)\nRequirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from requests->-r requirements.txt (line 10)) (2.2.2)\nRequirement already satisfied: certifi>=2017.4.17 in /usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages (from requests->-r requirements.txt (line 10)) (2024.8.30)\nINFO: pip is looking at multiple versions of timm to determine which version is compatible with other requirements. This could take a while.\nERROR: Cannot install -r requirements.txt (line 12) because these package versions have conflicting dependencies.\n\nThe conflict is caused by:\n    timm 0.9.7 depends on torch>=1.7\n    The user requested (constraint) torch==2.5.0+cu124\n\nTo fix this you could try to:\n1. loosen the range of package versions you've specified\n2. remove package versions to allow pip to attempt to solve the dependency conflict\n\nERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts\n"
> barni@barni ~/workspace/pytorch/benchmark
>  % 
> ```

please run commands like this to install model:
```
git clone https://github.com/pytorch-tpu/run_torchbench.git
cd run_torchbench
pip install torchvision torchaudio
git clone https://github.com/pytorch/benchmark.git
cd benchmark
python3 install.py
```

**Comment by barney-s** [comment]
Running the test mode under xla2 env results in a crash. Debuggin session: 

https://gist.github.com/barney-s/44896bf40c5154d386b5d5528b52de2c

**Comment by barney-s** [comment]
https://github.com/pytorch-tpu/run_torchbench/pull/4
