### ISSUE TITLE
Make sure type promotion logic matches pytorch

### ISSUE THREAD

**Issue by dlibenzi** [pytorch/xla#820]
https://github.com/pytorch/pytorch/pull/22273

**Comment by asuhan** [comment]
Fortunately, looks like our tests will still pass indeed: https://circleci.com/gh/pytorch/pytorch/2161630?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link. We'll just need to reject additional patterns.

**Comment by asuhan** [comment]
Actually, that appears to be just the build. @ailzhang can we trigger a full run?

**Comment by ailzhang** [comment]
@asuhan In pytorch CI, build and test are separate jobs ;) as in this case, build passes but test failed.

**Comment by asuhan** [comment]
https://github.com/pytorch/xla/pull/822 proactively addresses the test breakage.

**Comment by asuhan** [comment]
Our proactive fix worked, the tests are green now. Should we close this issue and create a new one to make our behavior consistent with vanilla PyTorch (less implicit casts)?

**Comment by ailzhang** [comment]
Hmmm looks like this indeed no longer breaks, but I'd use this issue to make sure our type promotion logic matches pytorch once the PR merges. I'll change the label ;)

**Comment by ailzhang** [comment]
This task has been done. 
The only thing left is cleanup of Scalar which is more relevant to pytorch core. I'll follow up on that in a separate issue.
