### ISSUE TITLE
How are PJRT asynchronous executions throttled by torch_xla?

### ISSUE THREAD

**Issue by mcuiaws** [pytorch/xla#8380]
## 🐛 Bug

Here at AWS we have a single PJRT device plugin for both PyTorch and JAX, and recently we've made implements to our device plugin to make it work better with JAX. I.e. now `PJRT_LoadedExecutable_Execute()` is fully asynchronous, we queue up an execution and return immediately, and expect the caller to wait on the `returned_future`, whereas before, execution was synchronous and is completed when `PJRT_LoadedExecutable_Execute()` returns.

As soon as we switched to the new implementation, we noticed that now torch_xla queues up as many executions it can without any throttling in PJRT or torch_xla, which causes us to easily exhaust device memory. It appears that now that there are no internal throttling mechanisms, and only explicit ones which needs to be triggered by user code:
1. when `xm.wait_device_ops()` is called, which calls down to `WaitDeviceOps()`
2. when tensor is read, which internally calls `WaitDeviceOps()`
However, `WaitDeviceOps()` is a heavy hammer because it pauses the world until the entire pipeline is drained. Ideally we do not want to rely on this mechanism for throttling. Also we do not want the user to have to guess when to insert these calls to avoid running out of memory. Some sensible internal throttling mechanism is needed.

The main issue here is that [pjrt_computation_client.cc ](https://github.com/pytorch/xla/blob/master/torch_xla/csrc/runtime/pjrt_computation_client.cc#L744) does not await on the `returned_future` from PJRT. It simply throws it away.

However, according to torch's [lazy_graph_executor](https://github.com/pytorch/pytorch/blob/main/torch/csrc/lazy/core/lazy_graph_executor.h#L164), "only one asynchronous operation can execute at the same time, on a given device." This is controlled by a device lock, which is supposed to be held for the entire duration of the asynchronous execution. However, in torch_xla's [xla_graph_executor.cpp](https://github.com/pytorch/xla/blob/master/torch_xla/csrc/xla_graph_executor.cpp#L826), the device locks acquired by torch are released as soon as `ExecuteComputation()` returns, and `ExecuteComputaton()` does not actually wait for the actual computation to complete. Therefore, torch lazy_graph_executor's throttling mechanism is defeated here.

**Comment by JackCaoG** [comment]
We controlled it by `XLA_TPU_MAX_INFLIGHT_COMPUTATIONS` but I guess that's a TPU specified flag.

**Comment by mcuiaws** [comment]
We can do something similar for neuron. How is `XLA_TPU_MAX_INFLIGHT_COMPUTATIONS` implemented? Do you block inside `PJRT_LoadedExecutable_Execute()` if the client queues up too many executions?

**Comment by JackCaoG** [comment]
`only one asynchronous operation can execute at the same time` was a old design choice for the XRT runtime. Back then the async execution was implemented in the torch_xla level. It is more of a design constrain not a design choice.

Ever since we move to the PJRT runtime, the runtime itself supports async transfer and async execution, it is better to let runtime handle this kind of stuff. We want to make sure the program is not tracing bound so it is better to unblock from tracing as many graphs as possible.

**Comment by mcuiaws** [comment]
Should we move the max inflight logic to torch_xla's prjt_computation_client.cc? PJRT's Execute APIs are asynchronous, and asynchronous APIs should not block, ideally...
