### ISSUE TITLE
Getting "undefined symbol: _ZN5torch4lazy13MetricFnValueB5cxx11E" with torch-xla nightly wheel for 2.6

### ISSUE THREAD

**Issue by jeffhataws** [pytorch/xla#8406]
## 🐛 Bug

Currently, if I install from nightly using instructions from README.md, and try to run a simple test, I see "undefined symbol: _ZN5torch4lazy13MetricFnValueB5cxx11E" which has "cxx11" in it indicating that torch-xla nightly may have ABI cxx11 on by default:

```
(aws_neuron_venv_pytorch_pt26) ubuntu@ip-10-0-8-190:~$ python -c "import torch; import torch_xla; x=torch.ones((10,10), device='xla'); print(x*x)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/aws_neuron_venv_pytorch_pt26/lib/python3.10/site-packages/torch_xla/__init__.py", line 20, in <module>
    import _XLAC
ImportError: /home/ubuntu/aws_neuron_venv_pytorch_pt26/lib/python3.10/site-packages/_XLAC.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN5torch4lazy13MetricFnValueB5cxx11E
```

## To Reproduce

Install nightly torch-xla together with torch using instructions from https://github.com/pytorch/xla/blob/master/README.md#installation.

```
pip3 install --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/cpu
pip install 'torch_xla[tpu] @ https://storage.googleapis.com/pytorch-xla-releases/wheels/tpuvm/torch_xla-2.6.0.dev-cp310-cp310-linux_x86_64.whl' -f https://storage.googleapis.com/libtpu-releases/index.html
```

Then run

```
python -c "import torch; import torch_xla; x=torch.ones((10,10), device='xla'); print(x*x)"
```

## Expected behavior

Since the default torch is still non-cxx11 version, it would be good to keep default to be non-cxx11.

## Environment

 - Reproducible on XLA backend [CPU/TPU/CUDA]: CPU/Neuron
 - torch_xla version: 2.6

**Comment by JackCaoG** [comment]
@tengyifei did we switch the default ABI config?

**Comment by tengyifei** [comment]
Shoot, it looks like I screwed up the cxx11 ABI for `torch_xla-2.6.0.dev-cp311-cp311-linux_x86_64.whl` in particular. I'll assign this bug to me and fix it.

In the meantime @jeffhataws if you're blocked, you can try a filename with a date:

```
pip install https://storage.googleapis.com/pytorch-xla-releases/wheels/tpuvm/torch_xla-2.6.0.dev20241121-cp310-cp310-linux_x86_64.whl
```

This one doesn't have C++11 ABI.

**Comment by tengyifei** [comment]
Hi, I'm just back from vacation. This is still on my radar to be fixed. Does the workaround work for you or you're still blocked on it?

**Comment by jeffhataws** [comment]
Hi @tengyifei welcome back. The workaround works but since we want to test nightly builds, we don't want to hardcode the date and have to change it everyday, so its best if we have the non-ABI CXX11 version for nightlies.

**Comment by tengyifei** [comment]
https://github.com/pytorch/xla/pull/8465 should fix it

**Comment by jeffhataws** [comment]
Just want to note here that torch 2.6 has C++11 ABI off by default, but torch 2.7 will have C++11 ABI on by default.
