### ISSUE TITLE
Is it possible to execute jax code in torch_xla?

### ISSUE THREAD

**Issue by lime-j** [pytorch/xla#8451]
##  Is it possible to execute jax code in torch_xla?
After reading the docs, I realized that customized kernels via Jax Pallas can be adopted as kernels. I wonder if it is possible to execute jax code in torch_xla. It seems torch_xla._XLAC._xla_tpu_custom_call only accept custom kernels. Is there a way to execute jax ir code?

**Comment by qihqi** [comment]
Hi, 

with torch_xla's _xla_tpu_custom_call it can only execute the bytecode lowered from Pallas but not regular Jax code.

However, we do have a sister project [torch_xla2](https://github.com/pytorch/xla/tree/master/experimental/torch_xla2) that offers full Jax interoperability (for example, training torch models with `jax.grad` and `optax`: https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/examples/basic_training_jax.py).

**Comment by lime-j** [comment]
Thanks for you comment! :)
