### ISSUE TITLE
The clip_grad_norm patch causes upstream CI failure

### ISSUE THREAD

**Issue by pietern** [pytorch/xla#846]
I saw a CI failure on https://github.com/pytorch/pytorch/pull/23223 for [pytorch_linux_trusty_py3_6_gcc5_4_test](https://circleci.com/gh/pytorch/pytorch/2255555) and it seems to be caused by the patch at https://github.com/pytorch/xla/blob/master/torch_patches/X10-clip_grad.diff.

The error:

```
Jul 23 18:37:31 ERROR: test_clip_grad_norm (__main__.TestNN)
Jul 23 18:37:31 ----------------------------------------------------------------------
Jul 23 18:37:31 Traceback (most recent call last):
Jul 23 18:37:31   File "test_nn.py", line 1921, in test_clip_grad_norm
Jul 23 18:37:31     norm = clip_grad_norm_(l.parameters(), max_norm, norm_type=norm_type)
Jul 23 18:37:31   File "/opt/conda/lib/python3.6/site-packages/torch/nn/utils/clip_grad.py", line 36, in clip_grad_norm_
Jul 23 18:37:31     clip_coef = torch.tensor(max_norm, device=device) / (total_norm + 1e-6)
Jul 23 18:37:31 UnboundLocalError: local variable 'device' referenced before assignment
```

**Comment by pietern** [comment]
I don't know why this patch is applied for a non-XLA build.

**Comment by dlibenzi** [comment]
@ailzhang The patch likely needs a refresh?
@pietern Not sure whether they share the same build or it is a bug.

**Comment by pietern** [comment]
Neither the patch has changed nor the upstream source for that file has changed... 

One possible explanation is that this build isn't supposed to run, AND that the XLA path only exercises the `else` branch of that patch, so that the `device` variable is always set.

**Comment by dlibenzi** [comment]
Created https://github.com/pytorch/xla/pull/848

**Comment by asuhan** [comment]
Fix merged.
