### ISSUE TITLE
DataParallel

### ISSUE THREAD

**Issue by huiwudiyi** [pytorch/xla#849]
1.  if I use    model.to(device)  ,    one TPU   or  one core?

2. DataParallel(model, device_ids=devices)  ，the  code does not continue！

**Comment by jysohn23** [comment]
1. If you use `model.to(xm.xla_device())` it will use one TPU core (a single Cloud TPU has 8 cores).
2. Can you provide more detail? Do you mean that the model is hanging when training? What model are you training? What is the size of your Compute VM (we recommend at least `n1-standard-16`)?

**Comment by huiwudiyi** [comment]
thanks very much!   my computer VM  is n1-standard-1 ,I will try it!

**Comment by jysohn23** [comment]
Yes, let us know if this still doesn't work. The hanging issue you reported is already being tracked by https://github.com/pytorch/xla/issues/821 and we are working on fixing it.

**Comment by huiwudiyi** [comment]
it works ,  thanks very much!

**Comment by jysohn23** [comment]
Great. Feel free to reopen if you have any more questions.
