### ISSUE TITLE
HalfTensor support

### ISSUE THREAD

**Issue by ailzhang** [pytorch/xla#867]
Got `RuntimeError: torch_xla/csrc/tensor_util.cpp:652 : Type not supported: Half` error when I try to convert HalfTensor to xla. If we decide not to support it for now, we should probably add it to our 2 pages guidelines.

```
import torch
import torch_xla

device = 'xla:0'

a = torch.rand(3, 3).half()
b = a.to(device)
print(b)
```

**Comment by gupta-abhay** [comment]
saw the comment that was added for `XLA_USE_BF16`. Let's say that I do this:

```
import os
import torch_xla
import torch_xla.core.xla_model as xm

class My_Model_1(nn.Module):
    def __init__(self,D_in,D_out):
        super(My_Model_1, self).__init__()
        self.layer = nn.Linear(D_in,D_out)
    def forward(self,x):
        out = self.layer(x)
        return out

os.environ["XLA_USE_BF16"] = "1"
model_1 = My_Model_1(10,10)
device = xm.xla_device()
model.to(device)

print (model_1.layer.weight.dtype)
```

what should be the expected output? `torch.float32` or `torch.float16` or `torch.bfloat16`
