### ISSUE TITLE
tensor.narrow with tensor args

### ISSUE THREAD

**Issue by ibeltagy** [pytorch/xla#871]
`tensor.narrow` is expecting integer `start` and `length`. I have a use case where `star` and `length` are tensors computed from the values of the other tensors in the tpu. Is it possible to call `tensor.narrow` with `start` and `length` being tensors, and without a trip to the cpu to convert them to integers?

Here's an example: 

```import torch
import torch_xla_py.xla_model as xm

zero =  torch.tensor(0) 
one =  torch.tensor(1)  
t = torch.rand(3, 5)

xla_device = xm.xla_device()
zero = zero.to(xla_device)
one = one.to(xla_device)
t = t.to(xla_device)

x = t.narrow(0, 0, 1)
import torch_xla; print(torch_xla._XLAC._xla_metrics_report())
x = t.narrow(0, zero, one)
import torch_xla; print(torch_xla._XLAC._xla_metrics_report())  # two trips to the CPU```

**Comment by dlibenzi** [comment]
Even if PyTorch would add a tensor-based narrow, we would not be able to lower it to XLA.
A tensor based narrow would mean dynamic shapes, which we do not support ATM.
