### ISSUE TITLE
xla tensor with copy.copy() returns CPU tensor. 

### ISSUE THREAD

**Issue by ailzhang** [pytorch/xla#876]
Minimal repro:
```
import torch
import torch_xla

device = 'xla:0'

from copy import copy
a = torch.rand(3, 3)
b = a.to(device)
c = copy(b)
print(c.device) # should be xla
c.fill_(1)
# c and a should be exactly same
print(c == a)
```

**Comment by ailzhang** [comment]
Hmmm I think this behavior is indeed intended due to patch to make `torch.save` work. https://github.com/pytorch/xla/blob/master/torch_patches/X10-torch_save.diff 
Maybe we should just document this behavior and close this? cc: @dlibenzi  @asuhan

**Comment by asuhan** [comment]
I don't understand how `torch.save` is related to this. In any case, shouldn't at least the shallow `copy` preserve the device?

**Comment by ailzhang** [comment]
@asuhan Our patch is patched to `__reduce_ex__` method which is called in all tensor serializations. https://github.com/pytorch/xla/blob/master/torch_patches/X10-torch_save.diff#L6 So with the patch it's indeed expected to have a cpu tensor returned. Is this behavior not what we want?

**Comment by asuhan** [comment]
I see. What's the behavior if we use a `cuda` device instead of `xla:0`, can you check? If it's the same I agree we could close this.

**Comment by dlibenzi** [comment]
If `copy()` call serialization, then we assume the current behavior is the expected one, or we fix `torch.save` in a different way.

**Comment by ailzhang** [comment]
Hmmm so the right fix might be a bit tricky, this could be a low pri. I'll take a look next week.

**Comment by asuhan** [comment]
Is this fixed now?

**Comment by ailzhang** [comment]
Ah the automatic close didn't catch this. Closing manually
