### ISSUE TITLE
Error importing torch_xla 

### ISSUE THREAD

**Issue by umgupta** [pytorch/xla#897]
#### To reproduce:
Follow steps in [consuming prebuilt VM instance](https://github.com/pytorch/xla#consume-prebuilt-compute-vm-images) to create VM instance. 
- Activate conda env
` conda activate pytorch-0.1`
- open `ipython` terminal in `home` folder
- execute `import torch_xla` which will give the error
`AttributeError: module 'torch_xla' has no attribute '_XLAC'`

I guess the problem is with pre-configured conda environment. 

I could work around it by adding `/usr/share/torch-xla-0.1/pytorch/xla/` to `PYTHONPATH` but I am not sure if this is the expected behaviour.

**Comment by umgupta** [comment]
Nevermind it was a mistake on my side.

**Comment by zcain117** [comment]
For me, I need to cd into pytorch/xla before running ipython or python2 or python3, otherwise I can't import torch or torch_xla.

Same for running scripts, they need to be in pytorch/xla directory or the script can't import torch_xla

**Comment by jysohn23** [comment]
You should be able to import from anywhere as long as the conda environment has been activated.

**Comment by umgupta** [comment]
I made a stupid mistake earlier. I am able to import from anywhere. Thanks for replying so quick :)

**Comment by zcain117** [comment]
Thanks Daniel, you're right. You can import these from anywhere except the pytorch directory since it has a directory named "torch"
