### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'getattr_or'

### ISSUE THREAD

**Issue by tweetyone** [pytorch/xla#917]
My code is like this:
![image](https://user-images.githubusercontent.com/30562332/62739389-85833d80-b9e9-11e9-9729-6aa7988b4335.png)
Why it have `'dict' object has no attribute 'getattr_or'` error
![image](https://user-images.githubusercontent.com/30562332/62739285-4bb23700-b9e9-11e9-8c27-c4276ff6c8c9.png)

**Comment by taylanbil** [comment]
it looks like your `context` variable is a dict, whereas it needs to be a `Context` object as in: https://github.com/pytorch/xla/blob/master/torch_xla_py/data_parallel.py#L18

**Comment by dlibenzi** [comment]
You are mixing new code (the `getattr_or()`) with old 0.1 version.
You need to be on nightly (check the README file) to use that code.

**Comment by tweetyone** [comment]
@dlibenzi  but I notice test_train_mnist also use `getattr_or()`, and I can run it on pytorch-0.1 env
https://github.com/pytorch/xla/blob/68704a54af5708acd011a3bd488478276616e160/test/test_train_mnist.py#L98

**Comment by tweetyone** [comment]
@taylanbil my network need to add 3 loss together, so the optimizer will be like my code shows.  How to change my code to let the dict to be an Context object? Thanks!

**Comment by dlibenzi** [comment]
> @dlibenzi but I notice test_train_mnist also use `getattr_or()`, and I can run it on pytorch-0.1 env
> https://github.com/pytorch/xla/blob/68704a54af5708acd011a3bd488478276616e160/test/test_train_mnist.py#L98

Looking at your error, it seems the `context` is a `dict`, which was true if you were using an `data_parallel.py` module of some time ago (used to be a dict).

**Comment by tweetyone** [comment]
@dlibenzi I'm using  PyTorch/XLA Image of GCP - pytorch-0.1, is it an old version? 
Should I use pytorch-nightly of that image?

**Comment by dlibenzi** [comment]
I suggest using nightly (on user and TPU VM - like the README describes for nightly setups).
Things are happening fast at this time, and releases get old quickly.

In your case it seems you grabbed a recent `test_train_mnist.py` and used it with r0.1.

**Comment by Crysitna** [comment]
> @dlibenzi but I notice test_train_mnist also use `getattr_or()`, and I can run it on pytorch-0.1 env
> https://github.com/pytorch/xla/blob/68704a54af5708acd011a3bd488478276616e160/test/test_train_mnist.py#L98

if u are running the mnist example with the command in readme
```
(pytorch-0.1)$ cd /usr/share/torch-xla-0.1/pytorch/xla
(pytorch-0.1)$ python test/test_train_mnist.py
```
then this `test_train_mnist.py` is not not really using `getattr_or`: 
line96: `optimizer = optim.SGD(model.parameters(), lr=lr, mementum=FLAGS.momentum)`

**Comment by tweetyone** [comment]
Thanks! @Crysitna it solves my problem!
