### ISSUE TITLE
train with multiple tpus

### ISSUE THREAD

**Issue by tweetyone** [pytorch/xla#932]
I met ran out of memory problem.
![image](https://user-images.githubusercontent.com/30562332/62986207-43923700-bdef-11e9-85b0-4d2af8cc9976.png)
![image](https://user-images.githubusercontent.com/30562332/62986225-64f32300-bdef-11e9-8948-c9552cc53844.png)

Do you have any code to train on multiple TPUs? Thanks!

**Comment by jysohn23** [comment]
When you face device HBM OOM, try reducing the batch size first. 

Training with multiple TPUs would not help in this case as long as we have the same per-core batch size, unless we use model parallelism, which we currently don't support. But we working to support distributed training on TPU Pods later this year.

**Comment by tweetyone** [comment]
Got, just my model is too big, to avoid the OOM error, the batch size can only be 16. Really hope you can support distributed training!
I also have another question: like the following image shows, why one step need to run on each xla device? why not just run one step on one core?
![image](https://user-images.githubusercontent.com/30562332/62997765-232da100-be1e-11e9-8fc7-1405014913b0.png)

**Comment by dlibenzi** [comment]
This is not Intel x86 architecture ;)
Each core has its own memory (16GB in TPU v3), and the other cores cannot access it (or they could, at HUGE costs).
So you cannot run on a single core using the whole TPU combined memory.

**Comment by jysohn23** [comment]
> I also have another question: like the following image shows, why one step need to run on each xla device? why not just run one step on one core?

I'm not sure I understand this question, but each TPU core (v3-8 has 8 TPU cores) is considered a single xla device so `v3-8` would have `xla:1` ... `xla:8` devices.

**Comment by tweetyone** [comment]
Sorry I didn't make my question clear enough. :) 
My question is: 
The 1～8 lines is the result of the same training step, right? So why we use 8 devices to run a same training step 8 times and get different loss results? Does this make the training process faster or you have another reason to do this?
Thanks!

**Comment by jysohn23** [comment]
> The 1～8 lines is the result of the same training step, right? So why we use 8 devices to run a same training step 8 times and get different loss results? Does this make the training process faster or you have another reason to do this?

So each of the devices gets a different mini batch. So even though each of the devices has the exact same model weights (synchronous gradient descent) since the batches that each of the devices gets is different the losses are also different. So essentially during a single global step (where all 8 devices take a synchronized step) the global batch size is the `--batch_size` flag times 8. Is that a little more clear?

**Comment by tweetyone** [comment]
clear enough! thank you :)
